	.text
	.file	"memcpy.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/stdint.h"
	.section	.text.__memcpy_wram_4align,"ax",@progbits
	.globl	__memcpy_wram_4align            // -- Begin function __memcpy_wram_4align
	.type	__memcpy_wram_4align,@function
__memcpy_wram_4align:                   // @__memcpy_wram_4align
.Lfunc_begin0:
	.file	2 "/root" "uPIMulator_frontend/sdk/stdlib/memcpy.c"
	.loc	2 13 0                          // uPIMulator_frontend/sdk/stdlib/memcpy.c:13:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __memcpy_wram_4align:dest <- $r0
	//DEBUG_VALUE: __memcpy_wram_4align:dest <- $r0
	//DEBUG_VALUE: __memcpy_wram_4align:src <- $r1
	//DEBUG_VALUE: __memcpy_wram_4align:src <- $r1
	//DEBUG_VALUE: __memcpy_wram_4align:len <- $r2
	//DEBUG_VALUE: __memcpy_wram_4align:len <- $r2
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: __memcpy_wram_4align:dw <- $r0
	//DEBUG_VALUE: __memcpy_wram_4align:dw <- $r0
	//DEBUG_VALUE: __memcpy_wram_4align:sw <- $r1
	//DEBUG_VALUE: __memcpy_wram_4align:sw <- $r1
	//DEBUG_VALUE: i <- 0
	.loc	2 17 35 prologue_end            // uPIMulator_frontend/sdk/stdlib/memcpy.c:17:35
	lsr r2, r2, 2, z, .LBB0_3
.Ltmp0:
// %bb.1:
	//DEBUG_VALUE: __memcpy_wram_4align:sw <- $r1
	//DEBUG_VALUE: __memcpy_wram_4align:src <- $r1
	//DEBUG_VALUE: __memcpy_wram_4align:dw <- $r0
	//DEBUG_VALUE: __memcpy_wram_4align:dest <- $r0
	//DEBUG_VALUE: i <- 0
	.loc	2 0 35 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:35
	move r3, r0
.Ltmp1:
.LBB0_2:                                // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: __memcpy_wram_4align:dw <- $r0
	//DEBUG_VALUE: __memcpy_wram_4align:dest <- $r0
	//DEBUG_VALUE: i <- undef
	.loc	2 18 17 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memcpy.c:18:17
	lw r4, r1, 0
	.loc	2 18 15 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/memcpy.c:18:15
	sw r3, 0, r4
.Ltmp2:
	//DEBUG_VALUE: i <- [DW_OP_plus_uconst 1, DW_OP_stack_value] undef
	.loc	2 17 28 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memcpy.c:17:28
	add r3, r3, 4
	add r1, r1, 4
	add r2, r2, -1, nz, .LBB0_2
.Ltmp3:
.LBB0_3:
	//DEBUG_VALUE: __memcpy_wram_4align:dw <- $r0
	//DEBUG_VALUE: __memcpy_wram_4align:dest <- $r0
	.loc	2 20 5                          // uPIMulator_frontend/sdk/stdlib/memcpy.c:20:5
	jump r23
.Ltmp4:
.Lfunc_end0:
	.size	__memcpy_wram_4align, .Lfunc_end0-__memcpy_wram_4align
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__memcpy_wram_4align
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.__memcpy_wram_4align,"ax",@progbits
                                        // -- End function
	.section	.text.memcpy,"ax",@progbits
	.globl	memcpy                          // -- Begin function memcpy
	.type	memcpy,@function
memcpy:                                 // @memcpy
.Lfunc_begin1:
	.loc	2 25 0                          // uPIMulator_frontend/sdk/stdlib/memcpy.c:25:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: memcpy:dest <- $r0
	//DEBUG_VALUE: memcpy:dest <- $r0
	//DEBUG_VALUE: memcpy:src <- $r1
	//DEBUG_VALUE: memcpy:src <- $r1
	//DEBUG_VALUE: memcpy:len <- $r2
	//DEBUG_VALUE: memcpy:len <- $r2
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: memcpy:d <- $r0
	//DEBUG_VALUE: memcpy:d <- $r0
	//DEBUG_VALUE: memcpy:s <- $r1
	//DEBUG_VALUE: memcpy:s <- $r1
	.loc	2 31 43 prologue_end            // uPIMulator_frontend/sdk/stdlib/memcpy.c:31:43
	add r2, r0, r2
.Ltmp5:
	//DEBUG_VALUE: memcpy:body <- undef
	//DEBUG_VALUE: memcpy:tail <- $r2
	.loc	2 35 31                         // uPIMulator_frontend/sdk/stdlib/memcpy.c:35:31
	xor r3, r1, r0
.Ltmp6:
	.loc	2 35 9 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memcpy.c:35:9
	add r4, r0, 3
	and r5, r4, -4
.Ltmp7:
	.loc	2 35 31                         // uPIMulator_frontend/sdk/stdlib/memcpy.c:35:31
	and r4, r3, 3
.Ltmp8:
	.loc	2 35 9                          // uPIMulator_frontend/sdk/stdlib/memcpy.c:35:9
	move r3, r2
	jgtu r5, r2, .LBB1_2
.Ltmp9:
// %bb.1:
	//DEBUG_VALUE: memcpy:tail <- $r2
	//DEBUG_VALUE: memcpy:s <- $r1
	//DEBUG_VALUE: memcpy:src <- $r1
	//DEBUG_VALUE: memcpy:d <- $r0
	//DEBUG_VALUE: memcpy:dest <- $r0
	move r3, r5
.Ltmp10:
.LBB1_2:
	//DEBUG_VALUE: memcpy:tail <- $r2
	//DEBUG_VALUE: memcpy:s <- $r1
	//DEBUG_VALUE: memcpy:src <- $r1
	//DEBUG_VALUE: memcpy:d <- $r0
	//DEBUG_VALUE: memcpy:dest <- $r0
	//DEBUG_VALUE: memcpy:body <- undef
	jeq r4, 0, .LBB1_4
.Ltmp11:
// %bb.3:
	//DEBUG_VALUE: memcpy:tail <- $r2
	//DEBUG_VALUE: memcpy:s <- $r1
	//DEBUG_VALUE: memcpy:src <- $r1
	//DEBUG_VALUE: memcpy:d <- $r0
	//DEBUG_VALUE: memcpy:dest <- $r0
	move r3, r2
.Ltmp12:
.LBB1_4:
	//DEBUG_VALUE: memcpy:tail <- $r2
	//DEBUG_VALUE: memcpy:s <- $r1
	//DEBUG_VALUE: memcpy:src <- $r1
	//DEBUG_VALUE: memcpy:d <- $r0
	//DEBUG_VALUE: memcpy:dest <- $r0
	.loc	2 0 9                           // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:9
	and r6, r2, -4
.Ltmp13:
	//DEBUG_VALUE: memcpy:head <- $r3
	//DEBUG_VALUE: memcpy:body <- $r6
	//DEBUG_VALUE: i <- 0
	//DEBUG_VALUE: memcpy:head_len <- $r5
	.loc	2 49 30 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memcpy.c:49:30
	sub r5, r3, r0, z, .LBB1_7
.Ltmp14:
// %bb.5:
	//DEBUG_VALUE: memcpy:body <- $r6
	//DEBUG_VALUE: memcpy:head <- $r3
	//DEBUG_VALUE: memcpy:tail <- $r2
	//DEBUG_VALUE: memcpy:s <- $r1
	//DEBUG_VALUE: memcpy:src <- $r1
	//DEBUG_VALUE: memcpy:d <- $r0
	//DEBUG_VALUE: memcpy:dest <- $r0
	//DEBUG_VALUE: i <- 0
	.loc	2 0 30 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:30
	move r4, r1
	move r7, r0
	move r8, r5
.Ltmp15:
.LBB1_6:                                // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: memcpy:body <- $r6
	//DEBUG_VALUE: memcpy:head <- $r3
	//DEBUG_VALUE: memcpy:tail <- $r2
	//DEBUG_VALUE: memcpy:s <- $r1
	//DEBUG_VALUE: memcpy:src <- $r1
	//DEBUG_VALUE: memcpy:d <- $r0
	//DEBUG_VALUE: memcpy:dest <- $r0
	//DEBUG_VALUE: i <- undef
	.loc	2 52 20 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memcpy.c:52:20
	lbs r9, r4, 0
	.loc	2 52 18 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/memcpy.c:52:18
	sb r7, 0, r9
.Ltmp16:
	//DEBUG_VALUE: i <- [DW_OP_plus_uconst 1, DW_OP_stack_value] undef
	.loc	2 51 32 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memcpy.c:51:32
	add r7, r7, 1
	add r4, r4, 1
	add r8, r8, -1, nz, .LBB1_6
.Ltmp17:
.LBB1_7:
	//DEBUG_VALUE: memcpy:body <- $r6
	//DEBUG_VALUE: memcpy:head <- $r3
	//DEBUG_VALUE: memcpy:tail <- $r2
	//DEBUG_VALUE: memcpy:s <- $r1
	//DEBUG_VALUE: memcpy:src <- $r1
	//DEBUG_VALUE: memcpy:d <- $r0
	//DEBUG_VALUE: memcpy:dest <- $r0
	//DEBUG_VALUE: memcpy:dw <- $r3
	//DEBUG_VALUE: memcpy:sw <- undef
	.loc	2 0 32 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:32
	move r4, 0
	.loc	2 59 25 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memcpy.c:59:25
	jltu r6, r3, .LBB1_9
.Ltmp18:
// %bb.8:
	//DEBUG_VALUE: memcpy:body <- $r6
	//DEBUG_VALUE: memcpy:dw <- $r3
	//DEBUG_VALUE: memcpy:head <- $r3
	//DEBUG_VALUE: memcpy:tail <- $r2
	//DEBUG_VALUE: memcpy:s <- $r1
	//DEBUG_VALUE: memcpy:src <- $r1
	//DEBUG_VALUE: memcpy:d <- $r0
	//DEBUG_VALUE: memcpy:dest <- $r0
	.loc	2 0 25 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:25
	sub r4, r6, r3
	asr r4, r4, 2
.Ltmp19:
.LBB1_9:
	//DEBUG_VALUE: memcpy:body <- $r6
	//DEBUG_VALUE: memcpy:dw <- $r3
	//DEBUG_VALUE: memcpy:head <- $r3
	//DEBUG_VALUE: memcpy:tail <- $r2
	//DEBUG_VALUE: memcpy:s <- $r1
	//DEBUG_VALUE: memcpy:src <- $r1
	//DEBUG_VALUE: memcpy:d <- $r0
	//DEBUG_VALUE: memcpy:dest <- $r0
	add r1, r1, r5
.Ltmp20:
	//DEBUG_VALUE: memcpy:body_len <- $r4
	//DEBUG_VALUE: memcpy:sw <- $r1
	and r5, r4, 1073741823
	//DEBUG_VALUE: __memcpy_wram_4align:dw <- $r3
	//DEBUG_VALUE: i <- 0
	//DEBUG_VALUE: __memcpy_wram_4align:sw <- $r1
	//DEBUG_VALUE: __memcpy_wram_4align:len <- [DW_OP_constu 2, DW_OP_shl, DW_OP_stack_value] $r4
	//DEBUG_VALUE: __memcpy_wram_4align:src <- $r1
	//DEBUG_VALUE: __memcpy_wram_4align:dest <- $r3
	.loc	2 60 9 is_stmt 1                // uPIMulator_frontend/sdk/stdlib/memcpy.c:60:9
	jeq r5, 0, .LBB1_12
.Ltmp21:
// %bb.10:
	//DEBUG_VALUE: memcpy:body <- $r6
	//DEBUG_VALUE: __memcpy_wram_4align:len <- [DW_OP_constu 2, DW_OP_shl, DW_OP_stack_value] $r4
	//DEBUG_VALUE: memcpy:body_len <- $r4
	//DEBUG_VALUE: __memcpy_wram_4align:dest <- $r3
	//DEBUG_VALUE: __memcpy_wram_4align:dw <- $r3
	//DEBUG_VALUE: memcpy:dw <- $r3
	//DEBUG_VALUE: memcpy:head <- $r3
	//DEBUG_VALUE: memcpy:tail <- $r2
	//DEBUG_VALUE: __memcpy_wram_4align:src <- $r1
	//DEBUG_VALUE: __memcpy_wram_4align:sw <- $r1
	//DEBUG_VALUE: memcpy:sw <- $r1
	//DEBUG_VALUE: memcpy:d <- $r0
	//DEBUG_VALUE: memcpy:dest <- $r0
	//DEBUG_VALUE: i <- 0
	.loc	2 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:9
	move r6, r1
.Ltmp22:
	move r7, r3
.Ltmp23:
.LBB1_11:                               // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: __memcpy_wram_4align:len <- [DW_OP_constu 2, DW_OP_shl, DW_OP_stack_value] $r4
	//DEBUG_VALUE: memcpy:body_len <- $r4
	//DEBUG_VALUE: __memcpy_wram_4align:dest <- $r3
	//DEBUG_VALUE: __memcpy_wram_4align:dw <- $r3
	//DEBUG_VALUE: memcpy:dw <- $r3
	//DEBUG_VALUE: memcpy:head <- $r3
	//DEBUG_VALUE: memcpy:tail <- $r2
	//DEBUG_VALUE: __memcpy_wram_4align:src <- $r1
	//DEBUG_VALUE: __memcpy_wram_4align:sw <- $r1
	//DEBUG_VALUE: memcpy:sw <- $r1
	//DEBUG_VALUE: memcpy:d <- $r0
	//DEBUG_VALUE: memcpy:dest <- $r0
	//DEBUG_VALUE: i <- undef
	.loc	2 18 17 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memcpy.c:18:17
	lw r8, r6, 0
	.loc	2 18 15 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/memcpy.c:18:15
	sw r7, 0, r8
.Ltmp24:
	//DEBUG_VALUE: i <- [DW_OP_plus_uconst 1, DW_OP_stack_value] undef
	.loc	2 17 28 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memcpy.c:17:28
	add r7, r7, 4
	add r6, r6, 4
	add r5, r5, -1, nz, .LBB1_11
.Ltmp25:
.LBB1_12:
	//DEBUG_VALUE: memcpy:body_len <- $r4
	//DEBUG_VALUE: memcpy:dw <- $r3
	//DEBUG_VALUE: memcpy:head <- $r3
	//DEBUG_VALUE: memcpy:tail <- $r2
	//DEBUG_VALUE: memcpy:sw <- $r1
	//DEBUG_VALUE: memcpy:d <- $r0
	//DEBUG_VALUE: memcpy:dest <- $r0
	.loc	2 65 24                         // uPIMulator_frontend/sdk/stdlib/memcpy.c:65:24
	lsl_add r3, r3, r4, 2
.Ltmp26:
	//DEBUG_VALUE: memcpy:s <- undef
	//DEBUG_VALUE: memcpy:d <- $r3
	//DEBUG_VALUE: i <- 0
	//DEBUG_VALUE: memcpy:tail_len <- $r2
	.loc	2 67 30                         // uPIMulator_frontend/sdk/stdlib/memcpy.c:67:30
	sub r2, r2, r3, z, .LBB1_15
.Ltmp27:
// %bb.13:
	//DEBUG_VALUE: memcpy:body_len <- $r4
	//DEBUG_VALUE: memcpy:d <- $r3
	//DEBUG_VALUE: memcpy:sw <- $r1
	//DEBUG_VALUE: memcpy:dest <- $r0
	//DEBUG_VALUE: i <- 0
	.loc	2 0 30 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:30
	lsl_add r1, r1, r4, 2
.Ltmp28:
	//DEBUG_VALUE: memcpy:s <- $r1
	move r4, 0
.Ltmp29:
.LBB1_14:                               // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: memcpy:d <- $r3
	//DEBUG_VALUE: memcpy:s <- $r1
	//DEBUG_VALUE: memcpy:dest <- $r0
	//DEBUG_VALUE: i <- $r4
	.loc	2 70 20 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memcpy.c:70:20
	add r5, r1, r4
	lbs r5, r5, 0
	.loc	2 70 18 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/memcpy.c:70:18
	add r6, r3, r4
	.loc	2 69 44 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memcpy.c:69:44
	add r4, r4, 1
.Ltmp30:
	//DEBUG_VALUE: i <- $r4
	.loc	2 70 18                         // uPIMulator_frontend/sdk/stdlib/memcpy.c:70:18
	sb r6, 0, r5
.Ltmp31:
	.loc	2 69 9                          // uPIMulator_frontend/sdk/stdlib/memcpy.c:69:9
	jltu r4, r2, .LBB1_14
.Ltmp32:
.LBB1_15:
	//DEBUG_VALUE: memcpy:d <- $r3
	//DEBUG_VALUE: memcpy:dest <- $r0
	.loc	2 73 5                          // uPIMulator_frontend/sdk/stdlib/memcpy.c:73:5
	jump r23
.Ltmp33:
.Lfunc_end1:
	.size	memcpy, .Lfunc_end1-memcpy
	.cfi_endproc
	.file	3 "/root" "uPIMulator_frontend/sdk/stdlib/stddef.h"
	.section	.stack_sizes,"o",@progbits,.text.memcpy
	.long	.Lfunc_begin1
	.byte	0
	.section	.text.memcpy,"ax",@progbits
                                        // -- End function
	.section	.text.__memcpy_mw,"ax",@progbits
	.globl	__memcpy_mw                     // -- Begin function __memcpy_mw
	.type	__memcpy_mw,@function
__memcpy_mw:                            // @__memcpy_mw
.Lfunc_begin2:
	.loc	2 78 0                          // uPIMulator_frontend/sdk/stdlib/memcpy.c:78:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __memcpy_mw:dest <- $r0
	//DEBUG_VALUE: __memcpy_mw:src <- $r1
	//DEBUG_VALUE: __memcpy_mw:len <- $r2
	.cfi_def_cfa_offset -48
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 40, d22
	add r22, r22, 48
	.cfi_offset 15, -24
	.cfi_offset 14, -20
	sd r22, -24, d14
	.cfi_offset 17, -32
	.cfi_offset 16, -28
	sd r22, -32, d16
	.cfi_offset 19, -40
	.cfi_offset 18, -36
	sd r22, -40, d18
	.cfi_offset 21, -48
	.cfi_offset 20, -44
	sd r22, -48, d20
	move r15, r2
	move r16, r1
	move r14, r0
.Ltmp34:
	//DEBUG_VALUE: __memcpy_mw:destCache <- undef
	//DEBUG_VALUE: __memcpy_mw:len <- $r15
	//DEBUG_VALUE: __memcpy_mw:src <- $r16
	//DEBUG_VALUE: __memcpy_mw:dest <- $r14
	.loc	2 82 40 prologue_end            // uPIMulator_frontend/sdk/stdlib/memcpy.c:82:40
	and r18, r16, 7
.Ltmp35:
	//DEBUG_VALUE: __memcpy_mw:srcOff <- $r18
	//DEBUG_VALUE: __memcpy_mw:idx <- 0
	//DEBUG_VALUE: __memcpy_mw:remaining <- undef
	//DEBUG_VALUE: __memcpy_mw:destOff <- $r19
	.loc	2 83 42                         // uPIMulator_frontend/sdk/stdlib/memcpy.c:83:42
	and r19, r14, 7, z, .LBB2_1
.Ltmp36:
// %bb.2:
	//DEBUG_VALUE: __memcpy_mw:srcOff <- $r18
	//DEBUG_VALUE: __memcpy_mw:src <- $r16
	//DEBUG_VALUE: __memcpy_mw:len <- $r15
	//DEBUG_VALUE: __memcpy_mw:dest <- $r14
	//DEBUG_VALUE: __memcpy_mw:idx <- 0
	.loc	2 89 23                         // uPIMulator_frontend/sdk/stdlib/memcpy.c:89:23
	sub r0, 8, r19
	move r17, r15
	jgtu r0, r15, .LBB2_4
.Ltmp37:
// %bb.3:
	//DEBUG_VALUE: __memcpy_mw:srcOff <- $r18
	//DEBUG_VALUE: __memcpy_mw:src <- $r16
	//DEBUG_VALUE: __memcpy_mw:len <- $r15
	//DEBUG_VALUE: __memcpy_mw:dest <- $r14
	//DEBUG_VALUE: __memcpy_mw:idx <- 0
	move r17, r0
.Ltmp38:
.LBB2_4:
	//DEBUG_VALUE: __memcpy_mw:srcOff <- $r18
	//DEBUG_VALUE: __memcpy_mw:src <- $r16
	//DEBUG_VALUE: __memcpy_mw:len <- $r15
	//DEBUG_VALUE: __memcpy_mw:dest <- $r14
	//DEBUG_VALUE: __memcpy_mw:idx <- 0
	//DEBUG_VALUE: part <- $r17
	.loc	2 0 23 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:23
	add r20, r22, -16
.Ltmp39:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:from <- $r14
	.file	4 "/root" "uPIMulator_frontend/sdk/syslib/mram.h"
	.loc	4 35 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r20, r14, 0
.Ltmp40:
	.loc	2 91 26                         // uPIMulator_frontend/sdk/stdlib/memcpy.c:91:26
	or r0, r20, r19
	.loc	2 91 9 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memcpy.c:91:9
	move r1, r16
	move r2, r17
	call r23, memcpy
.Ltmp41:
	//DEBUG_VALUE: mram_write:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_write:to <- $r14
	.loc	4 53 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:53:24
	sdma r20, r14, 0
.Ltmp42:
	.loc	2 93 19                         // uPIMulator_frontend/sdk/stdlib/memcpy.c:93:19
	sub r15, r15, r17
.Ltmp43:
	//DEBUG_VALUE: mram_write:from <- [DW_OP_constu 16, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 16, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: __memcpy_mw:idx <- $r17
	//DEBUG_VALUE: __memcpy_mw:remaining <- $r15
	//DEBUG_VALUE: __memcpy_mw:remaining <- $r15
	//DEBUG_VALUE: __memcpy_mw:idx <- $r17
	.loc	2 97 9                          // uPIMulator_frontend/sdk/stdlib/memcpy.c:97:9
	jneq r18, r19, .LBB2_6
.Ltmp44:
.LBB2_8:
	//DEBUG_VALUE: __memcpy_mw:srcOff <- $r18
	//DEBUG_VALUE: __memcpy_mw:idx <- $r17
	//DEBUG_VALUE: __memcpy_mw:src <- $r16
	//DEBUG_VALUE: __memcpy_mw:remaining <- $r15
	//DEBUG_VALUE: __memcpy_mw:dest <- $r14
	.loc	2 98 9                          // uPIMulator_frontend/sdk/stdlib/memcpy.c:98:9
	jltu r15, 8, .LBB2_10
.Ltmp45:
.LBB2_9:                                // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: __memcpy_mw:srcOff <- $r18
	//DEBUG_VALUE: __memcpy_mw:idx <- $r17
	//DEBUG_VALUE: __memcpy_mw:src <- $r16
	//DEBUG_VALUE: __memcpy_mw:remaining <- $r15
	//DEBUG_VALUE: __memcpy_mw:dest <- $r14
	//DEBUG_VALUE: __memcpy_mw:remaining <- $r15
	//DEBUG_VALUE: __memcpy_mw:idx <- $r17
	.loc	2 99 40                         // uPIMulator_frontend/sdk/stdlib/memcpy.c:99:40
	add r0, r16, r17
.Ltmp46:
	//DEBUG_VALUE: mram_write:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_write:to <- undef
	//DEBUG_VALUE: mram_write:from <- undef
	.loc	4 53 24                         // uPIMulator_frontend/sdk/syslib/mram.h:53:24
	add r1, r14, r17
	sdma r0, r1, 0
.Ltmp47:
	.loc	2 101 17                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:101:17
	add r17, r17, 8
.Ltmp48:
	//DEBUG_VALUE: __memcpy_mw:idx <- $r17
	.loc	2 100 23                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:100:23
	add r15, r15, -8
.Ltmp49:
	//DEBUG_VALUE: __memcpy_mw:remaining <- $r15
	.loc	2 98 9                          // uPIMulator_frontend/sdk/stdlib/memcpy.c:98:9
	jgtu r15, 7, .LBB2_9
	jump .LBB2_10
.Ltmp50:
.LBB2_1:
	//DEBUG_VALUE: __memcpy_mw:srcOff <- $r18
	//DEBUG_VALUE: __memcpy_mw:src <- $r16
	//DEBUG_VALUE: __memcpy_mw:len <- $r15
	//DEBUG_VALUE: __memcpy_mw:dest <- $r14
	//DEBUG_VALUE: __memcpy_mw:idx <- 0
	.loc	2 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:9
	move r17, 0
.Ltmp51:
	//DEBUG_VALUE: __memcpy_mw:remaining <- $r15
	//DEBUG_VALUE: __memcpy_mw:idx <- $r17
	.loc	2 97 9 is_stmt 1                // uPIMulator_frontend/sdk/stdlib/memcpy.c:97:9
	jeq r18, r19, .LBB2_8
.Ltmp52:
.LBB2_6:
	//DEBUG_VALUE: __memcpy_mw:srcOff <- $r18
	//DEBUG_VALUE: __memcpy_mw:idx <- $r17
	//DEBUG_VALUE: __memcpy_mw:src <- $r16
	//DEBUG_VALUE: __memcpy_mw:remaining <- $r15
	//DEBUG_VALUE: __memcpy_mw:dest <- $r14
	.loc	2 104 9                         // uPIMulator_frontend/sdk/stdlib/memcpy.c:104:9
	jltu r15, 8, .LBB2_10
.Ltmp53:
.LBB2_7:                                // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: __memcpy_mw:srcOff <- $r18
	//DEBUG_VALUE: __memcpy_mw:idx <- $r17
	//DEBUG_VALUE: __memcpy_mw:src <- $r16
	//DEBUG_VALUE: __memcpy_mw:remaining <- $r15
	//DEBUG_VALUE: __memcpy_mw:dest <- $r14
	//DEBUG_VALUE: __memcpy_mw:remaining <- $r15
	//DEBUG_VALUE: __memcpy_mw:idx <- $r17
	.loc	2 105 13                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:105:13
	add r2, r16, r17
	lbu.u d0, r2, 1
	lbu.u d4, r2, 0
	lslx r3, r1, 8
	lsl_add r6, r3, r0, 8
	lbu.u d8, r2, 3
	lsl r7, r1, 8
	or r1, r7, r5
	or r0, r6, r4
	lbu.u d4, r2, 2
	lslx r3, r9, 8
	lsl_add r6, r3, r8, 8
	lsl r7, r9, 8
	or r5, r7, r5
	or r4, r6, r4
	lslx r3, r5, 16
	lbu.u d6, r2, 5
	lsl_add r8, r3, r4, 16
	lsl r9, r5, 16
	lbu.u d4, r2, 4
	lslx r3, r7, 8
	lsl_add r10, r3, r6, 8
	lbu.u d12, r2, 7
	lsl r11, r7, 8
	or r5, r11, r5
	or r4, r10, r4
	lbu.u d2, r2, 6
	lslx r6, r13, 8
	lsl_add r6, r6, r12, 8
	lsl r7, r13, 8
	or r3, r7, r3
	or r2, r6, r2
	lslx r6, r3, 16
	lsl_add r6, r6, r2, 16
	lsl r7, r3, 16
	or r3, r7, r5
	or r2, r6, r4
	move r5, 0
	or r1, r9, r1
	or r0, r8, r0
	move r4, r3
	or r1, r5, r1
	or r0, r4, r0
	sd r22, -16, d0
.Ltmp54:
	//DEBUG_VALUE: mram_write:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_write:to <- undef
	.loc	4 53 24                         // uPIMulator_frontend/sdk/syslib/mram.h:53:24
	add r0, r14, r17
	add r1, r22, -16
	sdma r1, r0, 0
.Ltmp55:
	.loc	2 108 17                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:108:17
	add r17, r17, 8
.Ltmp56:
	//DEBUG_VALUE: mram_write:from <- [DW_OP_constu 16, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: __memcpy_mw:idx <- $r17
	.loc	2 107 23                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:107:23
	add r15, r15, -8
.Ltmp57:
	//DEBUG_VALUE: __memcpy_mw:remaining <- $r15
	.loc	2 0 23 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:23
	jgtu r15, 7, .LBB2_7
.Ltmp58:
.LBB2_10:
	//DEBUG_VALUE: __memcpy_mw:srcOff <- $r18
	//DEBUG_VALUE: __memcpy_mw:idx <- $r17
	//DEBUG_VALUE: __memcpy_mw:src <- $r16
	//DEBUG_VALUE: __memcpy_mw:remaining <- $r15
	//DEBUG_VALUE: __memcpy_mw:dest <- $r14
	//DEBUG_VALUE: __memcpy_mw:remaining <- $r15
	//DEBUG_VALUE: __memcpy_mw:idx <- $r17
	.loc	2 112 9 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memcpy.c:112:9
	jeq r15, 0, .LBB2_12
.Ltmp59:
// %bb.11:
	//DEBUG_VALUE: __memcpy_mw:srcOff <- $r18
	//DEBUG_VALUE: __memcpy_mw:idx <- $r17
	//DEBUG_VALUE: __memcpy_mw:src <- $r16
	//DEBUG_VALUE: __memcpy_mw:remaining <- $r15
	//DEBUG_VALUE: __memcpy_mw:dest <- $r14
	.loc	2 113 24                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:113:24
	add r19, r14, r17
	add r18, r22, -16
.Ltmp60:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:from <- $r19
	.loc	4 35 24                         // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r18, r19, 0
.Ltmp61:
	.loc	2 114 31                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:114:31
	add r1, r16, r17
	.loc	2 114 9 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/memcpy.c:114:9
	move r0, r18
	move r2, r15
	call r23, memcpy
.Ltmp62:
	//DEBUG_VALUE: mram_write:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_write:to <- $r19
	.loc	4 53 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:53:24
	sdma r18, r19, 0
.Ltmp63:
	//DEBUG_VALUE: mram_write:from <- [DW_OP_constu 16, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 16, DW_OP_minus, DW_OP_stack_value] $r22
.LBB2_12:
	//DEBUG_VALUE: __memcpy_mw:idx <- $r17
	//DEBUG_VALUE: __memcpy_mw:src <- $r16
	//DEBUG_VALUE: __memcpy_mw:remaining <- $r15
	//DEBUG_VALUE: __memcpy_mw:dest <- $r14
	.loc	2 118 5                         // uPIMulator_frontend/sdk/stdlib/memcpy.c:118:5
	move r0, r14
	ld d20, r22, -48
	ld d18, r22, -40
	ld d16, r22, -32
.Ltmp64:
	ld d14, r22, -24
.Ltmp65:
	ld d22, r22, -8
	jump r23
.Ltmp66:
.Lfunc_end2:
	.size	__memcpy_mw, .Lfunc_end2-__memcpy_mw
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__memcpy_mw
	.long	.Lfunc_begin2
	.byte	48
	.section	.text.__memcpy_mw,"ax",@progbits
                                        // -- End function
	.section	.text.__memcpy_wm,"ax",@progbits
	.globl	__memcpy_wm                     // -- Begin function __memcpy_wm
	.type	__memcpy_wm,@function
__memcpy_wm:                            // @__memcpy_wm
.Lfunc_begin3:
	.loc	2 123 0                         // uPIMulator_frontend/sdk/stdlib/memcpy.c:123:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __memcpy_wm:dest <- $r0
	//DEBUG_VALUE: __memcpy_wm:src <- $r1
	//DEBUG_VALUE: __memcpy_wm:len <- $r2
	.cfi_def_cfa_offset -40
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 32, d22
	add r22, r22, 40
	.cfi_offset 15, -24
	.cfi_offset 14, -20
	sd r22, -24, d14
	.cfi_offset 17, -32
	.cfi_offset 16, -28
	sd r22, -32, d16
	.cfi_offset 19, -40
	.cfi_offset 18, -36
	sd r22, -40, d18
	move r17, r2
	move r15, r1
	move r14, r0
.Ltmp67:
	//DEBUG_VALUE: __memcpy_wm:srcCache <- undef
	//DEBUG_VALUE: __memcpy_wm:len <- $r17
	//DEBUG_VALUE: __memcpy_wm:src <- $r15
	//DEBUG_VALUE: __memcpy_wm:dest <- $r14
	.loc	2 127 40 prologue_end           // uPIMulator_frontend/sdk/stdlib/memcpy.c:127:40
	and r18, r15, 7
.Ltmp68:
	//DEBUG_VALUE: __memcpy_wm:srcOff <- $r18
	.loc	2 132 19                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:132:19
	sub r0, 8, r18
	.loc	2 128 42                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:128:42
	and r19, r14, 7
.Ltmp69:
	//DEBUG_VALUE: __memcpy_wm:idx <- 0
	//DEBUG_VALUE: __memcpy_wm:remaining <- $r17
	//DEBUG_VALUE: __memcpy_wm:destOff <- $r19
	.loc	2 132 19                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:132:19
	move r16, r17
	jgtu r0, r17, .LBB3_2
.Ltmp70:
// %bb.1:
	//DEBUG_VALUE: __memcpy_wm:destOff <- $r19
	//DEBUG_VALUE: __memcpy_wm:srcOff <- $r18
	//DEBUG_VALUE: __memcpy_wm:remaining <- $r17
	//DEBUG_VALUE: __memcpy_wm:len <- $r17
	//DEBUG_VALUE: __memcpy_wm:src <- $r15
	//DEBUG_VALUE: __memcpy_wm:dest <- $r14
	//DEBUG_VALUE: __memcpy_wm:idx <- 0
	move r16, r0
.Ltmp71:
.LBB3_2:
	//DEBUG_VALUE: __memcpy_wm:destOff <- $r19
	//DEBUG_VALUE: __memcpy_wm:srcOff <- $r18
	//DEBUG_VALUE: __memcpy_wm:remaining <- $r17
	//DEBUG_VALUE: __memcpy_wm:len <- $r17
	//DEBUG_VALUE: __memcpy_wm:src <- $r15
	//DEBUG_VALUE: __memcpy_wm:dest <- $r14
	//DEBUG_VALUE: __memcpy_wm:idx <- 0
	//DEBUG_VALUE: __memcpy_wm:part <- $r16
	.loc	2 0 19 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:19
	add r0, r22, -16
.Ltmp72:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:from <- $r15
	.loc	4 35 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r0, r15, 0
.Ltmp73:
	.loc	2 135 27                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:135:27
	or r1, r0, r18
	.loc	2 135 5 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/memcpy.c:135:5
	move r0, r14
	move r2, r16
	call r23, memcpy
.Ltmp74:
	.loc	2 136 15 is_stmt 1              // uPIMulator_frontend/sdk/stdlib/memcpy.c:136:15
	sub r2, r17, r16
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 16, DW_OP_minus, DW_OP_stack_value] $r22
.Ltmp75:
	//DEBUG_VALUE: __memcpy_wm:idx <- $r16
	//DEBUG_VALUE: __memcpy_wm:remaining <- $r2
	.loc	2 139 9                         // uPIMulator_frontend/sdk/stdlib/memcpy.c:139:9
	jneq r18, r19, .LBB3_3
.Ltmp76:
// %bb.5:
	//DEBUG_VALUE: __memcpy_wm:destOff <- $r19
	//DEBUG_VALUE: __memcpy_wm:srcOff <- $r18
	//DEBUG_VALUE: __memcpy_wm:len <- $r17
	//DEBUG_VALUE: __memcpy_wm:idx <- $r16
	//DEBUG_VALUE: __memcpy_wm:part <- $r16
	//DEBUG_VALUE: __memcpy_wm:src <- $r15
	//DEBUG_VALUE: __memcpy_wm:dest <- $r14
	//DEBUG_VALUE: __memcpy_wm:remaining <- $r2
	.loc	2 140 9                         // uPIMulator_frontend/sdk/stdlib/memcpy.c:140:9
	jltu r2, 8, .LBB3_7
.Ltmp77:
.LBB3_6:                                // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: __memcpy_wm:destOff <- $r19
	//DEBUG_VALUE: __memcpy_wm:srcOff <- $r18
	//DEBUG_VALUE: __memcpy_wm:len <- $r17
	//DEBUG_VALUE: __memcpy_wm:idx <- $r16
	//DEBUG_VALUE: __memcpy_wm:src <- $r15
	//DEBUG_VALUE: __memcpy_wm:dest <- $r14
	//DEBUG_VALUE: __memcpy_wm:remaining <- $r2
	//DEBUG_VALUE: __memcpy_wm:remaining <- $r2
	//DEBUG_VALUE: __memcpy_wm:idx <- $r16
	.loc	2 141 39                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:141:39
	add r0, r15, r16
.Ltmp78:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:to <- undef
	//DEBUG_VALUE: mram_read:from <- undef
	.loc	4 35 24                         // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	add r1, r14, r16
	ldma r1, r0, 0
.Ltmp79:
	.loc	2 143 17                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:143:17
	add r16, r16, 8
.Ltmp80:
	//DEBUG_VALUE: __memcpy_wm:idx <- $r16
	.loc	2 142 23                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:142:23
	add r2, r2, -8
.Ltmp81:
	//DEBUG_VALUE: __memcpy_wm:remaining <- $r2
	.loc	2 140 9                         // uPIMulator_frontend/sdk/stdlib/memcpy.c:140:9
	jgtu r2, 7, .LBB3_6
	jump .LBB3_7
.Ltmp82:
.LBB3_3:
	//DEBUG_VALUE: __memcpy_wm:destOff <- $r19
	//DEBUG_VALUE: __memcpy_wm:srcOff <- $r18
	//DEBUG_VALUE: __memcpy_wm:len <- $r17
	//DEBUG_VALUE: __memcpy_wm:idx <- $r16
	//DEBUG_VALUE: __memcpy_wm:part <- $r16
	//DEBUG_VALUE: __memcpy_wm:src <- $r15
	//DEBUG_VALUE: __memcpy_wm:dest <- $r14
	//DEBUG_VALUE: __memcpy_wm:remaining <- $r2
	.loc	2 146 9                         // uPIMulator_frontend/sdk/stdlib/memcpy.c:146:9
	jltu r2, 8, .LBB3_7
.Ltmp83:
.LBB3_4:                                // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: __memcpy_wm:destOff <- $r19
	//DEBUG_VALUE: __memcpy_wm:srcOff <- $r18
	//DEBUG_VALUE: __memcpy_wm:len <- $r17
	//DEBUG_VALUE: __memcpy_wm:idx <- $r16
	//DEBUG_VALUE: __memcpy_wm:src <- $r15
	//DEBUG_VALUE: __memcpy_wm:dest <- $r14
	//DEBUG_VALUE: __memcpy_wm:remaining <- $r2
	//DEBUG_VALUE: __memcpy_wm:remaining <- $r2
	//DEBUG_VALUE: __memcpy_wm:idx <- $r16
	//DEBUG_VALUE: mram_read:from <- undef
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	.loc	4 35 24                         // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	add r0, r15, r16
	add r1, r22, -16
	ldma r1, r0, 0
.Ltmp84:
	.loc	2 148 13                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:148:13
	ld d0, r22, -16
	add r3, r14, r16
	sb r3, 4, r0
	sb r3, 0, r1
	lsr.u d4, r0, 24
	sb r3, 7, r5
	lsr.u d4, r0, 16
	sb r3, 6, r5
	lsr.u d4, r0, 8
	sb r3, 5, r5
	lsr r4, r1, 24
	sb r3, 3, r4
	lsr r4, r1, 16
	sb r3, 2, r4
	lsr r0, r1, 8
	sb r3, 1, r0
	.loc	2 150 17                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:150:17
	add r16, r16, 8
.Ltmp85:
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 16, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: __memcpy_wm:idx <- $r16
	.loc	2 149 23                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:149:23
	add r2, r2, -8
.Ltmp86:
	//DEBUG_VALUE: __memcpy_wm:remaining <- $r2
	.loc	2 0 23 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:23
	jgtu r2, 7, .LBB3_4
.Ltmp87:
.LBB3_7:
	//DEBUG_VALUE: __memcpy_wm:destOff <- $r19
	//DEBUG_VALUE: __memcpy_wm:srcOff <- $r18
	//DEBUG_VALUE: __memcpy_wm:len <- $r17
	//DEBUG_VALUE: __memcpy_wm:idx <- $r16
	//DEBUG_VALUE: __memcpy_wm:src <- $r15
	//DEBUG_VALUE: __memcpy_wm:dest <- $r14
	//DEBUG_VALUE: __memcpy_wm:remaining <- $r2
	//DEBUG_VALUE: __memcpy_wm:remaining <- $r2
	//DEBUG_VALUE: __memcpy_wm:idx <- $r16
	.loc	2 154 9 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memcpy.c:154:9
	jeq r2, 0, .LBB3_9
.Ltmp88:
// %bb.8:
	//DEBUG_VALUE: __memcpy_wm:destOff <- $r19
	//DEBUG_VALUE: __memcpy_wm:srcOff <- $r18
	//DEBUG_VALUE: __memcpy_wm:len <- $r17
	//DEBUG_VALUE: __memcpy_wm:idx <- $r16
	//DEBUG_VALUE: __memcpy_wm:src <- $r15
	//DEBUG_VALUE: __memcpy_wm:dest <- $r14
	//DEBUG_VALUE: __memcpy_wm:remaining <- $r2
	.loc	2 155 23                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:155:23
	add r0, r15, r16
	add r1, r22, -16
.Ltmp89:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:from <- $r0
	.loc	4 35 24                         // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r1, r0, 0
.Ltmp90:
	.loc	2 156 21                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:156:21
	add r0, r14, r16
.Ltmp91:
	.loc	2 156 9 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/memcpy.c:156:9
	call r23, memcpy
.Ltmp92:
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 16, DW_OP_minus, DW_OP_stack_value] $r22
.LBB3_9:
	//DEBUG_VALUE: __memcpy_wm:destOff <- $r19
	//DEBUG_VALUE: __memcpy_wm:srcOff <- $r18
	//DEBUG_VALUE: __memcpy_wm:len <- $r17
	//DEBUG_VALUE: __memcpy_wm:idx <- $r16
	//DEBUG_VALUE: __memcpy_wm:src <- $r15
	//DEBUG_VALUE: __memcpy_wm:dest <- $r14
	//DEBUG_VALUE: __memcpy_wm:remaining <- $r2
	.loc	2 159 5 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memcpy.c:159:5
	move r0, r14
	ld d18, r22, -40
.Ltmp93:
	ld d16, r22, -32
.Ltmp94:
	ld d14, r22, -24
.Ltmp95:
	ld d22, r22, -8
	jump r23
.Ltmp96:
.Lfunc_end3:
	.size	__memcpy_wm, .Lfunc_end3-__memcpy_wm
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__memcpy_wm
	.long	.Lfunc_begin3
	.byte	40
	.section	.text.__memcpy_wm,"ax",@progbits
                                        // -- End function
	.section	.text.__memcpy_mm,"ax",@progbits
	.globl	__memcpy_mm                     // -- Begin function __memcpy_mm
	.type	__memcpy_mm,@function
__memcpy_mm:                            // @__memcpy_mm
.Lfunc_begin4:
	.loc	2 164 0                         // uPIMulator_frontend/sdk/stdlib/memcpy.c:164:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __memcpy_mm:dest <- $r0
	//DEBUG_VALUE: __memcpy_mm:src <- $r1
	//DEBUG_VALUE: __memcpy_mm:len <- $r2
	.cfi_def_cfa_offset -72
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 64, d22
	add r22, r22, 72
	.cfi_offset 15, -48
	.cfi_offset 14, -44
	sd r22, -48, d14
	.cfi_offset 17, -56
	.cfi_offset 16, -52
	sd r22, -56, d16
	.cfi_offset 19, -64
	.cfi_offset 18, -60
	sd r22, -64, d18
	.cfi_offset 21, -72
	.cfi_offset 20, -68
	sd r22, -72, d20
	move r21, r1
	move r20, r0
.Ltmp97:
	//DEBUG_VALUE: __memcpy_mm:destCache <- undef
	//DEBUG_VALUE: __memcpy_mm:srcCache <- undef
	//DEBUG_VALUE: __memcpy_mm:src <- $r21
	//DEBUG_VALUE: __memcpy_mm:dest <- $r20
	.loc	2 170 40 prologue_end           // uPIMulator_frontend/sdk/stdlib/memcpy.c:170:40
	and r3, r21, 7
.Ltmp98:
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	.loc	2 171 42                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:171:42
	and r14, r20, 7
.Ltmp99:
	//DEBUG_VALUE: __memcpy_mm:remaining <- undef
	//DEBUG_VALUE: __memcpy_mm:destOff <- [DW_OP_constu 7, DW_OP_and, DW_OP_stack_value] $r20
	.loc	2 0 42 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:42
	move r15, r2
.Ltmp100:
	//DEBUG_VALUE: __memcpy_mm:len <- $r15
	.loc	2 174 9 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memcpy.c:174:9
	jneq r3, r14, .LBB4_10
.Ltmp101:
// %bb.1:
	//DEBUG_VALUE: __memcpy_mm:src <- $r21
	//DEBUG_VALUE: __memcpy_mm:destOff <- [DW_OP_constu 7, DW_OP_and, DW_OP_stack_value] $r20
	//DEBUG_VALUE: __memcpy_mm:dest <- $r20
	//DEBUG_VALUE: __memcpy_mm:len <- $r15
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	//DEBUG_VALUE: idx <- 0
	.loc	2 177 13                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:177:13
	jeq r3, 0, .LBB4_2
.Ltmp102:
// %bb.3:
	//DEBUG_VALUE: __memcpy_mm:src <- $r21
	//DEBUG_VALUE: __memcpy_mm:destOff <- [DW_OP_constu 7, DW_OP_and, DW_OP_stack_value] $r20
	//DEBUG_VALUE: __memcpy_mm:dest <- $r20
	//DEBUG_VALUE: __memcpy_mm:len <- $r15
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	//DEBUG_VALUE: idx <- 0
	.loc	2 178 27                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:178:27
	sub r0, 8, r3
	move r18, r15
	jgtu r0, r15, .LBB4_5
.Ltmp103:
// %bb.4:
	//DEBUG_VALUE: __memcpy_mm:src <- $r21
	//DEBUG_VALUE: __memcpy_mm:destOff <- [DW_OP_constu 7, DW_OP_and, DW_OP_stack_value] $r20
	//DEBUG_VALUE: __memcpy_mm:dest <- $r20
	//DEBUG_VALUE: __memcpy_mm:len <- $r15
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	//DEBUG_VALUE: idx <- 0
	move r18, r0
.Ltmp104:
.LBB4_5:
	//DEBUG_VALUE: __memcpy_mm:src <- $r21
	//DEBUG_VALUE: __memcpy_mm:destOff <- [DW_OP_constu 7, DW_OP_and, DW_OP_stack_value] $r20
	//DEBUG_VALUE: __memcpy_mm:dest <- $r20
	//DEBUG_VALUE: __memcpy_mm:len <- $r15
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	//DEBUG_VALUE: idx <- 0
	//DEBUG_VALUE: part <- $r18
	.loc	2 0 27 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:27
	add r14, r22, -32
.Ltmp105:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:from <- $r20
	.loc	4 35 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r14, r20, 0
	add r1, r22, -40
.Ltmp106:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 32, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: mram_read:from <- $r21
	.loc	4 35 24 is_stmt 0               // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r1, r21, 0
.Ltmp107:
	.loc	2 181 30 is_stmt 1              // uPIMulator_frontend/sdk/stdlib/memcpy.c:181:30
	or r0, r14, r3
	.loc	2 181 50 is_stmt 0              // uPIMulator_frontend/sdk/stdlib/memcpy.c:181:50
	or r1, r1, r3
	.loc	2 181 13                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:181:13
	move r2, r18
	call r23, memcpy
.Ltmp108:
	//DEBUG_VALUE: mram_write:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_write:to <- $r20
	.loc	4 53 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:53:24
	sdma r14, r20, 0
.Ltmp109:
	.loc	2 183 23                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:183:23
	sub r15, r15, r18
.Ltmp110:
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 40, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: mram_write:from <- [DW_OP_constu 32, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: idx <- $r18
	//DEBUG_VALUE: __memcpy_mm:remaining <- $r15
	//DEBUG_VALUE: __memcpy_mm:remaining <- $r15
	//DEBUG_VALUE: idx <- $r18
	.loc	2 187 9                         // uPIMulator_frontend/sdk/stdlib/memcpy.c:187:9
	jltu r15, 8, .LBB4_8
.Ltmp111:
.LBB4_7:                                // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: __memcpy_mm:src <- $r21
	//DEBUG_VALUE: __memcpy_mm:destOff <- [DW_OP_constu 7, DW_OP_and, DW_OP_stack_value] $r20
	//DEBUG_VALUE: __memcpy_mm:dest <- $r20
	//DEBUG_VALUE: idx <- $r18
	//DEBUG_VALUE: __memcpy_mm:remaining <- $r15
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	//DEBUG_VALUE: __memcpy_mm:remaining <- $r15
	//DEBUG_VALUE: idx <- $r18
	//DEBUG_VALUE: mram_read:from <- undef
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	.loc	4 35 24                         // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	add r0, r21, r18
	add r1, r22, -40
	ldma r1, r0, 0
.Ltmp112:
	//DEBUG_VALUE: mram_write:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_write:to <- undef
	.loc	4 53 24                         // uPIMulator_frontend/sdk/syslib/mram.h:53:24
	add r0, r20, r18
	sdma r1, r0, 0
.Ltmp113:
	.loc	2 191 17                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:191:17
	add r18, r18, 8
.Ltmp114:
	//DEBUG_VALUE: mram_write:from <- [DW_OP_constu 40, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 40, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: idx <- $r18
	.loc	2 190 23                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:190:23
	add r15, r15, -8
.Ltmp115:
	//DEBUG_VALUE: __memcpy_mm:remaining <- $r15
	.loc	2 187 9                         // uPIMulator_frontend/sdk/stdlib/memcpy.c:187:9
	jgtu r15, 7, .LBB4_7
.Ltmp116:
.LBB4_8:
	//DEBUG_VALUE: __memcpy_mm:src <- $r21
	//DEBUG_VALUE: __memcpy_mm:destOff <- [DW_OP_constu 7, DW_OP_and, DW_OP_stack_value] $r20
	//DEBUG_VALUE: __memcpy_mm:dest <- $r20
	//DEBUG_VALUE: idx <- $r18
	//DEBUG_VALUE: __memcpy_mm:remaining <- $r15
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	.loc	2 194 13                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:194:13
	jeq r15, 0, .LBB4_28
.Ltmp117:
// %bb.9:
	//DEBUG_VALUE: __memcpy_mm:src <- $r21
	//DEBUG_VALUE: __memcpy_mm:destOff <- [DW_OP_constu 7, DW_OP_and, DW_OP_stack_value] $r20
	//DEBUG_VALUE: __memcpy_mm:dest <- $r20
	//DEBUG_VALUE: idx <- $r18
	//DEBUG_VALUE: __memcpy_mm:remaining <- $r15
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	.loc	2 195 28                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:195:28
	add r14, r20, r18
	add r17, r22, -32
.Ltmp118:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:from <- $r14
	.loc	4 35 24                         // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r17, r14, 0
.Ltmp119:
	.loc	2 196 27                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:196:27
	add r0, r21, r18
	add r1, r22, -40
.Ltmp120:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 32, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: mram_read:from <- $r0
	.loc	4 35 24                         // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r1, r0, 0
.Ltmp121:
	.loc	2 197 13                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:197:13
	move r0, r17
.Ltmp122:
	move r2, r15
	call r23, memcpy
.Ltmp123:
	//DEBUG_VALUE: mram_write:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_write:to <- $r14
	.loc	4 53 24                         // uPIMulator_frontend/sdk/syslib/mram.h:53:24
	sdma r17, r14, 0
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 40, DW_OP_minus, DW_OP_stack_value] $r22
.Ltmp124:
	//DEBUG_VALUE: mram_write:from <- [DW_OP_constu 32, DW_OP_minus, DW_OP_stack_value] $r22
	.loc	4 0 24 is_stmt 0                // uPIMulator_frontend/sdk/syslib/mram.h:0:24
	jump .LBB4_28
.Ltmp125:
.LBB4_10:
	//DEBUG_VALUE: __memcpy_mm:src <- $r21
	//DEBUG_VALUE: __memcpy_mm:destOff <- [DW_OP_constu 7, DW_OP_and, DW_OP_stack_value] $r20
	//DEBUG_VALUE: __memcpy_mm:dest <- $r20
	//DEBUG_VALUE: __memcpy_mm:len <- $r15
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	//DEBUG_VALUE: srcIdx <- 0
	//DEBUG_VALUE: destIdx <- 0
	.loc	2 203 26 is_stmt 1              // uPIMulator_frontend/sdk/stdlib/memcpy.c:203:26
	move r0, r14
	jgtu r3, r14, .LBB4_12
.Ltmp126:
// %bb.11:
	//DEBUG_VALUE: __memcpy_mm:src <- $r21
	//DEBUG_VALUE: __memcpy_mm:destOff <- [DW_OP_constu 7, DW_OP_and, DW_OP_stack_value] $r20
	//DEBUG_VALUE: __memcpy_mm:dest <- $r20
	//DEBUG_VALUE: __memcpy_mm:len <- $r15
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	//DEBUG_VALUE: destIdx <- 0
	//DEBUG_VALUE: srcIdx <- 0
	move r0, r3
.Ltmp127:
.LBB4_12:
	//DEBUG_VALUE: __memcpy_mm:src <- $r21
	//DEBUG_VALUE: __memcpy_mm:destOff <- [DW_OP_constu 7, DW_OP_and, DW_OP_stack_value] $r20
	//DEBUG_VALUE: __memcpy_mm:dest <- $r20
	//DEBUG_VALUE: __memcpy_mm:len <- $r15
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	//DEBUG_VALUE: destIdx <- 0
	//DEBUG_VALUE: srcIdx <- 0
	sub r0, 8, r0
.Ltmp128:
	//DEBUG_VALUE: initLen <- undef
	.loc	2 205 13                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:205:13
	jgeu r0, r15, .LBB4_13
.Ltmp129:
// %bb.14:
	//DEBUG_VALUE: __memcpy_mm:src <- $r21
	//DEBUG_VALUE: __memcpy_mm:destOff <- [DW_OP_constu 7, DW_OP_and, DW_OP_stack_value] $r20
	//DEBUG_VALUE: __memcpy_mm:dest <- $r20
	//DEBUG_VALUE: __memcpy_mm:len <- $r15
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	//DEBUG_VALUE: destIdx <- 0
	//DEBUG_VALUE: srcIdx <- 0
	.loc	2 0 13 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:13
	add r0, r22, -40
.Ltmp130:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:from <- $r21
	.loc	4 35 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r0, r21, 0
.Ltmp131:
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 40, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: srcIdx <- 8
	.loc	2 216 13                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:216:13
	jeq r14, 0, .LBB4_15
.Ltmp132:
// %bb.16:
	//DEBUG_VALUE: __memcpy_mm:src <- $r21
	//DEBUG_VALUE: __memcpy_mm:destOff <- [DW_OP_constu 7, DW_OP_and, DW_OP_stack_value] $r20
	//DEBUG_VALUE: __memcpy_mm:dest <- $r20
	//DEBUG_VALUE: __memcpy_mm:len <- $r15
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	//DEBUG_VALUE: srcIdx <- 8
	//DEBUG_VALUE: destIdx <- 0
	.loc	2 217 40                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:217:40
	add r0, r14, 7
	move r1, -1
.Ltmp133:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- $r0
	//DEBUG_VALUE: mram_read:from <- $r20
	.loc	4 35 24                         // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	lsr_add r1, r1, r0, 3
	add r0, r22, -32
.Ltmp134:
	lsl_add r1, r0, r1, 24
	ldma r1, r20, 0
.Ltmp135:
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 32, DW_OP_minus, DW_OP_stack_value] $r22
	.loc	2 219 17                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:219:17
	jgeu r3, r14, .LBB4_18
.Ltmp136:
// %bb.17:
	//DEBUG_VALUE: __memcpy_mm:src <- $r21
	//DEBUG_VALUE: __memcpy_mm:destOff <- [DW_OP_constu 7, DW_OP_and, DW_OP_stack_value] $r20
	//DEBUG_VALUE: __memcpy_mm:dest <- $r20
	//DEBUG_VALUE: __memcpy_mm:len <- $r15
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	//DEBUG_VALUE: srcIdx <- 8
	//DEBUG_VALUE: destIdx <- 0
	.loc	2 220 47                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:220:47
	sub r17, 8, r14
.Ltmp137:
	//DEBUG_VALUE: part <- $r17
	.loc	2 221 34                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:221:34
	or r0, r0, r14
	add r1, r22, -40
	.loc	2 221 54 is_stmt 0              // uPIMulator_frontend/sdk/stdlib/memcpy.c:221:54
	or r1, r1, r3
	.loc	2 221 17                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:221:17
	move r2, r17
	move r14, r3
	call r23, memcpy
.Ltmp138:
	.loc	2 0 17                          // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:17
	move r3, r14
.Ltmp139:
	.loc	2 223 24 is_stmt 1              // uPIMulator_frontend/sdk/stdlib/memcpy.c:223:24
	add r3, r3, r17
.Ltmp140:
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	.loc	2 0 24 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:24
	move r14, 8, true, .LBB4_19
.Ltmp141:
.LBB4_13:
	//DEBUG_VALUE: __memcpy_mm:src <- $r21
	//DEBUG_VALUE: __memcpy_mm:destOff <- [DW_OP_constu 7, DW_OP_and, DW_OP_stack_value] $r20
	//DEBUG_VALUE: __memcpy_mm:dest <- $r20
	//DEBUG_VALUE: __memcpy_mm:len <- $r15
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	//DEBUG_VALUE: destIdx <- 0
	//DEBUG_VALUE: srcIdx <- 0
	add r16, r22, -32
.Ltmp142:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:from <- $r20
	.loc	4 35 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r16, r20, 0
	add r1, r22, -40
.Ltmp143:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 32, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: mram_read:from <- $r21
	.loc	4 35 24 is_stmt 0               // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r1, r21, 0
.Ltmp144:
	.loc	2 208 30 is_stmt 1              // uPIMulator_frontend/sdk/stdlib/memcpy.c:208:30
	or r0, r16, r14
	.loc	2 208 50 is_stmt 0              // uPIMulator_frontend/sdk/stdlib/memcpy.c:208:50
	or r1, r1, r3
	.loc	2 208 13                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:208:13
	move r2, r15
	call r23, memcpy
.Ltmp145:
	//DEBUG_VALUE: mram_write:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_write:to <- $r20
	.loc	4 53 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:53:24
	sdma r16, r20, 0
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 40, DW_OP_minus, DW_OP_stack_value] $r22
.Ltmp146:
	//DEBUG_VALUE: mram_write:from <- [DW_OP_constu 32, DW_OP_minus, DW_OP_stack_value] $r22
	.loc	4 0 24 is_stmt 0                // uPIMulator_frontend/sdk/syslib/mram.h:0:24
	jump .LBB4_28
.Ltmp147:
.LBB4_2:
	//DEBUG_VALUE: __memcpy_mm:src <- $r21
	//DEBUG_VALUE: __memcpy_mm:destOff <- [DW_OP_constu 7, DW_OP_and, DW_OP_stack_value] $r20
	//DEBUG_VALUE: __memcpy_mm:dest <- $r20
	//DEBUG_VALUE: __memcpy_mm:len <- $r15
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	//DEBUG_VALUE: idx <- 0
	move r18, 0
.Ltmp148:
	//DEBUG_VALUE: __memcpy_mm:remaining <- $r15
	//DEBUG_VALUE: idx <- $r18
	.loc	2 187 9 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memcpy.c:187:9
	jgeu r15, 8, .LBB4_7
	jump .LBB4_8
.Ltmp149:
.LBB4_15:
	//DEBUG_VALUE: __memcpy_mm:src <- $r21
	//DEBUG_VALUE: __memcpy_mm:destOff <- [DW_OP_constu 7, DW_OP_and, DW_OP_stack_value] $r20
	//DEBUG_VALUE: __memcpy_mm:dest <- $r20
	//DEBUG_VALUE: __memcpy_mm:len <- $r15
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	//DEBUG_VALUE: srcIdx <- 8
	//DEBUG_VALUE: destIdx <- 0
	.loc	2 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:9
	move r14, 8
	move r16, 0
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
.Ltmp150:
	//DEBUG_VALUE: __memcpy_mm:remaining <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: destIdx <- $r16
	sw r22, -24, r20
	sw r22, -20, r21
	.loc	2 241 9 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memcpy.c:241:9
	jgeu r15, 8, .LBB4_22
.Ltmp151:
.LBB4_21:
	//DEBUG_VALUE: __memcpy_mm:src <- $r21
	//DEBUG_VALUE: __memcpy_mm:destOff <- [DW_OP_constu 7, DW_OP_and, DW_OP_stack_value] $r20
	//DEBUG_VALUE: __memcpy_mm:dest <- $r20
	//DEBUG_VALUE: destIdx <- $r16
	//DEBUG_VALUE: __memcpy_mm:remaining <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	.loc	2 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:9
	move r20, r3, true, .LBB4_24
.Ltmp152:
.LBB4_18:
	//DEBUG_VALUE: __memcpy_mm:src <- $r21
	//DEBUG_VALUE: __memcpy_mm:destOff <- [DW_OP_constu 7, DW_OP_and, DW_OP_stack_value] $r20
	//DEBUG_VALUE: __memcpy_mm:dest <- $r20
	//DEBUG_VALUE: __memcpy_mm:len <- $r15
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	//DEBUG_VALUE: srcIdx <- 8
	//DEBUG_VALUE: destIdx <- 0
	.loc	2 225 47 is_stmt 1              // uPIMulator_frontend/sdk/stdlib/memcpy.c:225:47
	sub r17, 8, r3
.Ltmp153:
	//DEBUG_VALUE: part <- $r17
	.loc	2 226 34                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:226:34
	or r18, r0, r14
	add r19, r22, -40
	.loc	2 226 54 is_stmt 0              // uPIMulator_frontend/sdk/stdlib/memcpy.c:226:54
	or r1, r19, r3
	.loc	2 226 17                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:226:17
	move r0, r18
	move r2, r17
	move r16, r3
	call r23, memcpy
.Ltmp154:
	.loc	2 227 31 is_stmt 1              // uPIMulator_frontend/sdk/stdlib/memcpy.c:227:31
	add r0, r21, 8
.Ltmp155:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:from <- $r0
	.loc	4 35 24                         // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r19, r0, 0
.Ltmp156:
	//DEBUG_VALUE: srcIdx <- 16
	.loc	2 230 39                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:230:39
	sub r16, r16, r14
.Ltmp157:
	//DEBUG_VALUE: part2 <- $r16
	.loc	2 231 44                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:231:44
	add r0, r18, r17
.Ltmp158:
	.loc	2 231 17 is_stmt 0              // uPIMulator_frontend/sdk/stdlib/memcpy.c:231:17
	move r1, r19
	move r2, r16
	call r23, memcpy
.Ltmp159:
	.loc	2 0 17                          // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:17
	move r3, r16
.Ltmp160:
	//DEBUG_VALUE: part2 <- $r3
	move r14, 16
.Ltmp161:
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 40, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
.LBB4_19:
	//DEBUG_VALUE: __memcpy_mm:src <- $r21
	//DEBUG_VALUE: __memcpy_mm:destOff <- [DW_OP_constu 7, DW_OP_and, DW_OP_stack_value] $r20
	//DEBUG_VALUE: __memcpy_mm:dest <- $r20
	//DEBUG_VALUE: __memcpy_mm:len <- $r15
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	//DEBUG_VALUE: destIdx <- 0
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	//DEBUG_VALUE: srcIdx <- $r14
	add r0, r22, -32
.Ltmp162:
	//DEBUG_VALUE: mram_write:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_write:to <- $r20
	.loc	4 53 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:53:24
	sdma r0, r20, 0
.Ltmp163:
	//DEBUG_VALUE: destIdx <- 8
	.loc	2 238 42                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:238:42
	or r0, r20, -8
	.loc	2 238 23 is_stmt 0              // uPIMulator_frontend/sdk/stdlib/memcpy.c:238:23
	add r15, r0, r15
.Ltmp164:
	//DEBUG_VALUE: __memcpy_mm:remaining <- $r15
	.loc	2 0 23                          // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:23
	move r16, 8
.Ltmp165:
	//DEBUG_VALUE: mram_write:from <- [DW_OP_constu 32, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	//DEBUG_VALUE: __memcpy_mm:remaining <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: destIdx <- $r16
	sw r22, -24, r20
	sw r22, -20, r21
	.loc	2 241 9 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memcpy.c:241:9
	jltu r15, 8, .LBB4_21
.Ltmp166:
.LBB4_22:
	//DEBUG_VALUE: __memcpy_mm:src <- $r21
	//DEBUG_VALUE: __memcpy_mm:destOff <- [DW_OP_constu 7, DW_OP_and, DW_OP_stack_value] $r20
	//DEBUG_VALUE: __memcpy_mm:dest <- $r20
	//DEBUG_VALUE: destIdx <- $r16
	//DEBUG_VALUE: __memcpy_mm:remaining <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	.loc	2 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:9
	sub r0, 8, r3
	add r19, r22, -40
	add r1, r19, r3
	sw r22, -16, r1
	add r21, r22, -32
.Ltmp167:
	move r18, r0
	add r17, r21, r0
	move r20, r3
.Ltmp168:
.LBB4_23:                               // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: destIdx <- $r16
	//DEBUG_VALUE: __memcpy_mm:remaining <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	//DEBUG_VALUE: __memcpy_mm:remaining <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: destIdx <- $r16
	//DEBUG_VALUE: part <- $r18
	.loc	2 243 13 is_stmt 1              // uPIMulator_frontend/sdk/stdlib/memcpy.c:243:13
	move r0, r21
	lw r1, r22, -16
	move r2, r18
	call r23, memcpy
.Ltmp169:
	//DEBUG_VALUE: mram_read:from <- undef
	.loc	4 35 24                         // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	lw r0, r22, -20
.Ltmp170:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	add r0, r0, r14
	ldma r19, r0, 0
.Ltmp171:
	.loc	2 245 20                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:245:20
	add r14, r14, 8
.Ltmp172:
	//DEBUG_VALUE: part2 <- $r20
	//DEBUG_VALUE: srcIdx <- $r14
	.loc	2 248 13                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:248:13
	move r0, r17
	move r1, r19
	move r2, r20
	call r23, memcpy
.Ltmp173:
	//DEBUG_VALUE: mram_write:to <- undef
	.loc	4 53 24                         // uPIMulator_frontend/sdk/syslib/mram.h:53:24
	lw r0, r22, -24
.Ltmp174:
	//DEBUG_VALUE: mram_write:nb_of_bytes <- 8
	add r0, r0, r16
	sdma r21, r0, 0
.Ltmp175:
	.loc	2 251 21                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:251:21
	add r16, r16, 8
.Ltmp176:
	//DEBUG_VALUE: mram_write:from <- [DW_OP_constu 32, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 40, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: destIdx <- $r16
	.loc	2 250 23                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:250:23
	add r15, r15, -8
.Ltmp177:
	//DEBUG_VALUE: __memcpy_mm:remaining <- $r15
	.loc	2 241 9                         // uPIMulator_frontend/sdk/stdlib/memcpy.c:241:9
	jgtu r15, 7, .LBB4_23
.Ltmp178:
.LBB4_24:
	//DEBUG_VALUE: destIdx <- $r16
	//DEBUG_VALUE: __memcpy_mm:remaining <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	.loc	2 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:9
	move r0, r20
	lw r20, r22, -24
	lw r21, r22, -20
	.loc	2 254 13 is_stmt 1              // uPIMulator_frontend/sdk/stdlib/memcpy.c:254:13
	jeq r15, 0, .LBB4_28
.Ltmp179:
// %bb.25:
	//DEBUG_VALUE: destIdx <- $r16
	//DEBUG_VALUE: __memcpy_mm:remaining <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	.loc	2 255 28                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:255:28
	add r16, r20, r16
.Ltmp180:
	.loc	2 0 28 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:28
	add r17, r22, -32
.Ltmp181:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:from <- $r16
	.loc	4 35 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r17, r16, 0
.Ltmp182:
	.loc	2 257 43                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:257:43
	sub r19, 8, r0
.Ltmp183:
	//DEBUG_VALUE: part <- $r19
	.loc	2 0 43 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memcpy.c:0:43
	add r18, r22, -40
	.loc	2 258 40 is_stmt 1              // uPIMulator_frontend/sdk/stdlib/memcpy.c:258:40
	add r1, r18, r0
	.loc	2 258 13 is_stmt 0              // uPIMulator_frontend/sdk/stdlib/memcpy.c:258:13
	move r0, r17
	move r2, r19
	call r23, memcpy
.Ltmp184:
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 32, DW_OP_minus, DW_OP_stack_value] $r22
	.loc	2 260 17 is_stmt 1              // uPIMulator_frontend/sdk/stdlib/memcpy.c:260:17
	jleu r15, r19, .LBB4_27
.Ltmp185:
// %bb.26:
	//DEBUG_VALUE: part <- $r19
	//DEBUG_VALUE: __memcpy_mm:remaining <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	.loc	2 261 42                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:261:42
	sub r2, r15, r19
.Ltmp186:
	//DEBUG_VALUE: part2 <- $r2
	.loc	2 262 31                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:262:31
	add r0, r21, r14
.Ltmp187:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:from <- $r0
	.loc	4 35 24                         // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r18, r0, 0
.Ltmp188:
	.loc	2 263 34                        // uPIMulator_frontend/sdk/stdlib/memcpy.c:263:34
	add r0, r17, r19
.Ltmp189:
	.loc	2 263 17 is_stmt 0              // uPIMulator_frontend/sdk/stdlib/memcpy.c:263:17
	move r1, r18
	call r23, memcpy
.Ltmp190:
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 40, DW_OP_minus, DW_OP_stack_value] $r22
.LBB4_27:
	//DEBUG_VALUE: part <- $r19
	//DEBUG_VALUE: __memcpy_mm:remaining <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	//DEBUG_VALUE: mram_write:to <- $r16
	//DEBUG_VALUE: mram_write:nb_of_bytes <- 8
	.loc	4 53 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:53:24
	sdma r17, r16, 0
.Ltmp191:
	//DEBUG_VALUE: mram_write:from <- [DW_OP_constu 32, DW_OP_minus, DW_OP_stack_value] $r22
.LBB4_28:
	//DEBUG_VALUE: __memcpy_mm:srcOff <- $r3
	.loc	2 271 1                         // uPIMulator_frontend/sdk/stdlib/memcpy.c:271:1
	move r0, r20
	ld d20, r22, -72
	ld d18, r22, -64
	ld d16, r22, -56
	ld d14, r22, -48
	ld d22, r22, -8
	jump r23
.Ltmp192:
.Lfunc_end4:
	.size	__memcpy_mm, .Lfunc_end4-__memcpy_mm
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__memcpy_mm
	.long	.Lfunc_begin4
	.byte	72
	.section	.text.__memcpy_mm,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp1-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc1:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc2:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp1-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc3:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp1-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc4:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Lfunc_begin1-.Lfunc_begin1
	.long	.Ltmp20-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc5:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Lfunc_begin1-.Lfunc_begin1
	.long	.Ltmp5-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc6:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Lfunc_begin1-.Lfunc_begin1
	.long	.Ltmp26-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp26-.Lfunc_begin1
	.long	.Lfunc_end1-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc7:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Lfunc_begin1-.Lfunc_begin1
	.long	.Ltmp20-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp28-.Lfunc_begin1
	.long	.Ltmp32-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc8:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp13-.Lfunc_begin1
	.long	.Ltmp22-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	86                              // DW_OP_reg6
	.long	0
	.long	0
.Ldebug_loc9:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp5-.Lfunc_begin1
	.long	.Ltmp27-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc10:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp13-.Lfunc_begin1
	.long	.Ltmp26-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc11:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp13-.Lfunc_begin1
	.long	.Ltmp14-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	0
	.long	0
.Ldebug_loc12:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp17-.Lfunc_begin1
	.long	.Ltmp26-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc13:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp20-.Lfunc_begin1
	.long	.Ltmp28-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc14:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp20-.Lfunc_begin1
	.long	.Ltmp29-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	0
	.long	0
.Ldebug_loc15:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp26-.Lfunc_begin1
	.long	.Ltmp27-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc16:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Lfunc_begin2-.Lfunc_begin2
	.long	.Ltmp34-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp34-.Lfunc_begin2
	.long	.Ltmp65-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	0
	.long	0
.Ldebug_loc17:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Lfunc_begin2-.Lfunc_begin2
	.long	.Ltmp34-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp34-.Lfunc_begin2
	.long	.Ltmp64-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	96                              // DW_OP_reg16
	.long	0
	.long	0
.Ldebug_loc18:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Lfunc_begin2-.Lfunc_begin2
	.long	.Ltmp34-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp34-.Lfunc_begin2
	.long	.Ltmp43-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	.Ltmp50-.Lfunc_begin2
	.long	.Ltmp52-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	0
	.long	0
.Ldebug_loc19:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp35-.Lfunc_begin2
	.long	.Ltmp60-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	98                              // DW_OP_reg18
	.long	0
	.long	0
.Ldebug_loc20:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp35-.Lfunc_begin2
	.long	.Ltmp43-.Lfunc_begin2
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp43-.Lfunc_begin2
	.long	.Ltmp50-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	97                              // DW_OP_reg17
	.long	.Ltmp50-.Lfunc_begin2
	.long	.Ltmp51-.Lfunc_begin2
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp51-.Lfunc_begin2
	.long	.Ltmp64-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	97                              // DW_OP_reg17
	.long	0
	.long	0
.Ldebug_loc21:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp43-.Lfunc_begin2
	.long	.Ltmp50-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	.Ltmp51-.Lfunc_begin2
	.long	.Ltmp65-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	0
	.long	0
.Ldebug_loc22:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp35-.Lfunc_begin2
	.long	.Ltmp36-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	99                              // DW_OP_reg19
	.long	0
	.long	0
.Ldebug_loc23:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp38-.Lfunc_begin2
	.long	.Ltmp44-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	97                              // DW_OP_reg17
	.long	0
	.long	0
.Ldebug_loc24:
	.long	-1
	.long	.Lfunc_begin3                   //   base address
	.long	.Lfunc_begin3-.Lfunc_begin3
	.long	.Ltmp67-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp67-.Lfunc_begin3
	.long	.Ltmp95-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	0
	.long	0
.Ldebug_loc25:
	.long	-1
	.long	.Lfunc_begin3                   //   base address
	.long	.Lfunc_begin3-.Lfunc_begin3
	.long	.Ltmp67-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp67-.Lfunc_begin3
	.long	.Ltmp95-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	0
	.long	0
.Ldebug_loc26:
	.long	-1
	.long	.Lfunc_begin3                   //   base address
	.long	.Lfunc_begin3-.Lfunc_begin3
	.long	.Ltmp67-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp67-.Lfunc_begin3
	.long	.Ltmp94-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	97                              // DW_OP_reg17
	.long	0
	.long	0
.Ldebug_loc27:
	.long	-1
	.long	.Lfunc_begin3                   //   base address
	.long	.Ltmp68-.Lfunc_begin3
	.long	.Ltmp93-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	98                              // DW_OP_reg18
	.long	0
	.long	0
.Ldebug_loc28:
	.long	-1
	.long	.Lfunc_begin3                   //   base address
	.long	.Ltmp69-.Lfunc_begin3
	.long	.Ltmp75-.Lfunc_begin3
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp75-.Lfunc_begin3
	.long	.Ltmp94-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	96                              // DW_OP_reg16
	.long	0
	.long	0
.Ldebug_loc29:
	.long	-1
	.long	.Lfunc_begin3                   //   base address
	.long	.Ltmp69-.Lfunc_begin3
	.long	.Ltmp75-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	97                              // DW_OP_reg17
	.long	.Ltmp75-.Lfunc_begin3
	.long	.Lfunc_end3-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc30:
	.long	-1
	.long	.Lfunc_begin3                   //   base address
	.long	.Ltmp69-.Lfunc_begin3
	.long	.Ltmp93-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	99                              // DW_OP_reg19
	.long	0
	.long	0
.Ldebug_loc31:
	.long	-1
	.long	.Lfunc_begin3                   //   base address
	.long	.Ltmp71-.Lfunc_begin3
	.long	.Ltmp77-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	96                              // DW_OP_reg16
	.long	.Ltmp82-.Lfunc_begin3
	.long	.Ltmp83-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	96                              // DW_OP_reg16
	.long	0
	.long	0
.Ldebug_loc32:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Lfunc_begin4-.Lfunc_begin4
	.long	.Ltmp97-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp97-.Lfunc_begin4
	.long	.Ltmp168-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	100                             // DW_OP_reg20
	.long	0
	.long	0
.Ldebug_loc33:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Lfunc_begin4-.Lfunc_begin4
	.long	.Ltmp97-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp97-.Lfunc_begin4
	.long	.Ltmp167-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	101                             // DW_OP_reg21
	.long	0
	.long	0
.Ldebug_loc34:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Lfunc_begin4-.Lfunc_begin4
	.long	.Ltmp100-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp100-.Lfunc_begin4
	.long	.Ltmp110-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	.Ltmp125-.Lfunc_begin4
	.long	.Ltmp151-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	.Ltmp152-.Lfunc_begin4
	.long	.Ltmp164-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	0
	.long	0
.Ldebug_loc35:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Ltmp98-.Lfunc_begin4
	.long	.Ltmp139-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp140-.Lfunc_begin4
	.long	.Ltmp160-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp161-.Lfunc_begin4
	.long	.Lfunc_end4-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc36:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Ltmp110-.Lfunc_begin4
	.long	.Ltmp125-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	.Ltmp148-.Lfunc_begin4
	.long	.Ltmp149-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	.Ltmp150-.Lfunc_begin4
	.long	.Ltmp152-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	.Ltmp164-.Lfunc_begin4
	.long	.Ltmp191-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	0
	.long	0
.Ldebug_loc37:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Ltmp99-.Lfunc_begin4
	.long	.Ltmp168-.Lfunc_begin4
	.short	5                               // Loc expr size
	.byte	132                             // DW_OP_breg20
	.byte	0                               // 0
	.byte	55                              // DW_OP_lit7
	.byte	26                              // DW_OP_and
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc38:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Ltmp101-.Lfunc_begin4
	.long	.Ltmp110-.Lfunc_begin4
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp110-.Lfunc_begin4
	.long	.Ltmp125-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	98                              // DW_OP_reg18
	.long	.Ltmp148-.Lfunc_begin4
	.long	.Ltmp149-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	98                              // DW_OP_reg18
	.long	0
	.long	0
.Ldebug_loc39:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Ltmp104-.Lfunc_begin4
	.long	.Ltmp111-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	98                              // DW_OP_reg18
	.long	0
	.long	0
.Ldebug_loc40:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Ltmp124-.Lfunc_begin4
	.long	.Ltmp125-.Lfunc_begin4
	.short	3                               // Loc expr size
	.byte	134                             // DW_OP_breg22
	.byte	96                              // -32
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc41:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Ltmp125-.Lfunc_begin4
	.long	.Ltmp131-.Lfunc_begin4
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp131-.Lfunc_begin4
	.long	.Ltmp141-.Lfunc_begin4
	.short	2                               // Loc expr size
	.byte	56                              // DW_OP_lit8
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp141-.Lfunc_begin4
	.long	.Ltmp147-.Lfunc_begin4
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp150-.Lfunc_begin4
	.long	.Ltmp152-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	.Ltmp152-.Lfunc_begin4
	.long	.Ltmp156-.Lfunc_begin4
	.short	2                               // Loc expr size
	.byte	56                              // DW_OP_lit8
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp156-.Lfunc_begin4
	.long	.Ltmp161-.Lfunc_begin4
	.short	2                               // Loc expr size
	.byte	64                              // DW_OP_lit16
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp161-.Lfunc_begin4
	.long	.Ltmp191-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	0
	.long	0
.Ldebug_loc42:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Ltmp125-.Lfunc_begin4
	.long	.Ltmp147-.Lfunc_begin4
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp150-.Lfunc_begin4
	.long	.Ltmp152-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	96                              // DW_OP_reg16
	.long	.Ltmp152-.Lfunc_begin4
	.long	.Ltmp163-.Lfunc_begin4
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp163-.Lfunc_begin4
	.long	.Ltmp165-.Lfunc_begin4
	.short	2                               // Loc expr size
	.byte	56                              // DW_OP_lit8
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp165-.Lfunc_begin4
	.long	.Ltmp180-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	96                              // DW_OP_reg16
	.long	0
	.long	0
.Ldebug_loc43:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Ltmp133-.Lfunc_begin4
	.long	.Ltmp134-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc44:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Ltmp137-.Lfunc_begin4
	.long	.Ltmp141-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	97                              // DW_OP_reg17
	.long	0
	.long	0
.Ldebug_loc45:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Ltmp146-.Lfunc_begin4
	.long	.Ltmp147-.Lfunc_begin4
	.short	3                               // Loc expr size
	.byte	134                             // DW_OP_breg22
	.byte	96                              // -32
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc46:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Ltmp153-.Lfunc_begin4
	.long	.Ltmp161-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	97                              // DW_OP_reg17
	.long	0
	.long	0
.Ldebug_loc47:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Ltmp157-.Lfunc_begin4
	.long	.Ltmp160-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	96                              // DW_OP_reg16
	.long	.Ltmp160-.Lfunc_begin4
	.long	.Ltmp161-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc48:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Ltmp170-.Lfunc_begin4
	.long	.Ltmp178-.Lfunc_begin4
	.short	2                               // Loc expr size
	.byte	56                              // DW_OP_lit8
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc49:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Ltmp172-.Lfunc_begin4
	.long	.Ltmp178-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	100                             // DW_OP_reg20
	.long	0
	.long	0
.Ldebug_loc50:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Ltmp174-.Lfunc_begin4
	.long	.Ltmp178-.Lfunc_begin4
	.short	2                               // Loc expr size
	.byte	56                              // DW_OP_lit8
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc51:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Ltmp183-.Lfunc_begin4
	.long	.Ltmp191-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	99                              // DW_OP_reg19
	.long	0
	.long	0
.Ldebug_loc52:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Ltmp186-.Lfunc_begin4
	.long	.Ltmp190-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	11                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	12                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	13                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	14                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	15                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	16                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	17                              // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	18                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	19                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	20                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	21                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	22                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	1                               // DW_CHILDREN_yes
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	23                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	24                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	25                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	26                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	28                              // DW_AT_const_value
	.byte	15                              // DW_FORM_udata
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	27                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	28                              // Abbreviation Code
	.ascii	"\211\202\001"                  // DW_TAG_GNU_call_site
	.byte	0                               // DW_CHILDREN_no
	.ascii	"\223B"                         // DW_AT_GNU_call_site_target
	.byte	24                              // DW_FORM_exprloc
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	29                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	30                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	5                               // DW_FORM_data2
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	31                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	1                               // DW_CHILDREN_yes
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	5                               // DW_FORM_data2
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	32                              // Abbreviation Code
	.byte	1                               // DW_TAG_array_type
	.byte	1                               // DW_CHILDREN_yes
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	33                              // Abbreviation Code
	.byte	33                              // DW_TAG_subrange_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	55                              // DW_AT_count
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	34                              // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x9de DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	0                               // DW_AT_low_pc
	.long	.Ldebug_ranges2                 // DW_AT_ranges
	.byte	2                               // Abbrev [2] 0x26:0x5 DW_TAG_pointer_type
	.long	43                              // DW_AT_type
	.byte	3                               // Abbrev [3] 0x2b:0xb DW_TAG_typedef
	.long	54                              // DW_AT_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	48                              // DW_AT_decl_line
	.byte	4                               // Abbrev [4] 0x36:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	2                               // Abbrev [2] 0x3d:0x5 DW_TAG_pointer_type
	.long	66                              // DW_AT_type
	.byte	3                               // Abbrev [3] 0x42:0xb DW_TAG_typedef
	.long	77                              // DW_AT_type
	.long	.Linfo_string6                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	40                              // DW_AT_decl_line
	.byte	4                               // Abbrev [4] 0x4d:0x7 DW_TAG_base_type
	.long	.Linfo_string5                  // DW_AT_name
	.byte	8                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	2                               // Abbrev [2] 0x54:0x5 DW_TAG_pointer_type
	.long	89                              // DW_AT_type
	.byte	5                               // Abbrev [5] 0x59:0x5 DW_TAG_const_type
	.long	66                              // DW_AT_type
	.byte	3                               // Abbrev [3] 0x5e:0xb DW_TAG_typedef
	.long	54                              // DW_AT_type
	.long	.Linfo_string7                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	144                             // DW_AT_decl_line
	.byte	6                               // Abbrev [6] 0x69:0x1 DW_TAG_pointer_type
	.byte	7                               // Abbrev [7] 0x6a:0x4c DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	182                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x79:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	194                             // DW_AT_abstract_origin
	.byte	9                               // Abbrev [9] 0x80:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	205                             // DW_AT_abstract_origin
	.byte	9                               // Abbrev [9] 0x89:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	216                             // DW_AT_abstract_origin
	.byte	10                              // Abbrev [10] 0x92:0x7 DW_TAG_variable
	.byte	1                               // DW_AT_location
	.byte	80
	.long	227                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x99:0x9 DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	238                             // DW_AT_abstract_origin
	.byte	12                              // Abbrev [12] 0xa2:0x13 DW_TAG_lexical_block
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Ltmp3-.Lfunc_begin0            // DW_AT_high_pc
	.byte	11                              // Abbrev [11] 0xab:0x9 DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	250                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	13                              // Abbrev [13] 0xb6:0x51 DW_TAG_subprogram
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	12                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	105                             // DW_AT_type
                                        // DW_AT_external
	.byte	1                               // DW_AT_inline
	.byte	14                              // Abbrev [14] 0xc2:0xb DW_TAG_formal_parameter
	.long	.Linfo_string9                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	12                              // DW_AT_decl_line
	.long	105                             // DW_AT_type
	.byte	14                              // Abbrev [14] 0xcd:0xb DW_TAG_formal_parameter
	.long	.Linfo_string10                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	12                              // DW_AT_decl_line
	.long	263                             // DW_AT_type
	.byte	14                              // Abbrev [14] 0xd8:0xb DW_TAG_formal_parameter
	.long	.Linfo_string11                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	12                              // DW_AT_decl_line
	.long	269                             // DW_AT_type
	.byte	15                              // Abbrev [15] 0xe3:0xb DW_TAG_variable
	.long	.Linfo_string13                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	14                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	15                              // Abbrev [15] 0xee:0xb DW_TAG_variable
	.long	.Linfo_string14                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	15                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	16                              // Abbrev [16] 0xf9:0xd DW_TAG_lexical_block
	.byte	15                              // Abbrev [15] 0xfa:0xb DW_TAG_variable
	.long	.Linfo_string15                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	17                              // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	2                               // Abbrev [2] 0x107:0x5 DW_TAG_pointer_type
	.long	268                             // DW_AT_type
	.byte	17                              // Abbrev [17] 0x10c:0x1 DW_TAG_const_type
	.byte	3                               // Abbrev [3] 0x10d:0xb DW_TAG_typedef
	.long	54                              // DW_AT_type
	.long	.Linfo_string12                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	26                              // DW_AT_decl_line
	.byte	18                              // Abbrev [18] 0x118:0x14a DW_TAG_subprogram
	.long	.Lfunc_begin1                   // DW_AT_low_pc
	.long	.Lfunc_end1-.Lfunc_begin1       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string21                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	24                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	105                             // DW_AT_type
                                        // DW_AT_external
	.byte	19                              // Abbrev [19] 0x12d:0xd DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	.Linfo_string9                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	24                              // DW_AT_decl_line
	.long	105                             // DW_AT_type
	.byte	20                              // Abbrev [20] 0x13a:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	.Linfo_string10                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	24                              // DW_AT_decl_line
	.long	263                             // DW_AT_type
	.byte	20                              // Abbrev [20] 0x149:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc5                    // DW_AT_location
	.long	.Linfo_string11                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	24                              // DW_AT_decl_line
	.long	269                             // DW_AT_type
	.byte	21                              // Abbrev [21] 0x158:0xf DW_TAG_variable
	.long	.Ldebug_loc6                    // DW_AT_location
	.long	.Linfo_string25                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	26                              // DW_AT_decl_line
	.long	61                              // DW_AT_type
	.byte	21                              // Abbrev [21] 0x167:0xf DW_TAG_variable
	.long	.Ldebug_loc7                    // DW_AT_location
	.long	.Linfo_string26                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	27                              // DW_AT_decl_line
	.long	84                              // DW_AT_type
	.byte	21                              // Abbrev [21] 0x176:0xf DW_TAG_variable
	.long	.Ldebug_loc8                    // DW_AT_location
	.long	.Linfo_string27                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	33                              // DW_AT_decl_line
	.long	2479                            // DW_AT_type
	.byte	21                              // Abbrev [21] 0x185:0xf DW_TAG_variable
	.long	.Ldebug_loc9                    // DW_AT_location
	.long	.Linfo_string28                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	31                              // DW_AT_decl_line
	.long	2484                            // DW_AT_type
	.byte	21                              // Abbrev [21] 0x194:0xf DW_TAG_variable
	.long	.Ldebug_loc10                   // DW_AT_location
	.long	.Linfo_string29                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	30                              // DW_AT_decl_line
	.long	61                              // DW_AT_type
	.byte	21                              // Abbrev [21] 0x1a3:0xf DW_TAG_variable
	.long	.Ldebug_loc11                   // DW_AT_location
	.long	.Linfo_string30                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	49                              // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	21                              // Abbrev [21] 0x1b2:0xf DW_TAG_variable
	.long	.Ldebug_loc12                   // DW_AT_location
	.long	.Linfo_string13                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	28                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	21                              // Abbrev [21] 0x1c1:0xf DW_TAG_variable
	.long	.Ldebug_loc13                   // DW_AT_location
	.long	.Linfo_string14                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	29                              // DW_AT_decl_line
	.long	2489                            // DW_AT_type
	.byte	21                              // Abbrev [21] 0x1d0:0xf DW_TAG_variable
	.long	.Ldebug_loc14                   // DW_AT_location
	.long	.Linfo_string31                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	59                              // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	21                              // Abbrev [21] 0x1df:0xf DW_TAG_variable
	.long	.Ldebug_loc15                   // DW_AT_location
	.long	.Linfo_string32                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	67                              // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	12                              // Abbrev [12] 0x1ee:0x15 DW_TAG_lexical_block
	.long	.Ltmp15                         // DW_AT_low_pc
	.long	.Ltmp17-.Ltmp15                 // DW_AT_high_pc
	.byte	15                              // Abbrev [15] 0x1f7:0xb DW_TAG_variable
	.long	.Linfo_string15                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	51                              // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x203:0x47 DW_TAG_inlined_subroutine
	.long	182                             // DW_AT_abstract_origin
	.long	.Ltmp23                         // DW_AT_low_pc
	.long	.Ltmp25-.Ltmp23                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	61                              // DW_AT_call_line
	.byte	9                               // DW_AT_call_column
	.byte	8                               // Abbrev [8] 0x213:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	83
	.long	194                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x21a:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	205                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x221:0xb DW_TAG_formal_parameter
	.byte	5                               // DW_AT_location
	.byte	116
	.byte	0
	.byte	50
	.byte	36
	.byte	159
	.long	216                             // DW_AT_abstract_origin
	.byte	10                              // Abbrev [10] 0x22c:0x7 DW_TAG_variable
	.byte	1                               // DW_AT_location
	.byte	83
	.long	227                             // DW_AT_abstract_origin
	.byte	10                              // Abbrev [10] 0x233:0x7 DW_TAG_variable
	.byte	1                               // DW_AT_location
	.byte	81
	.long	238                             // DW_AT_abstract_origin
	.byte	12                              // Abbrev [12] 0x23a:0xf DW_TAG_lexical_block
	.long	.Ltmp23                         // DW_AT_low_pc
	.long	.Ltmp25-.Ltmp23                 // DW_AT_high_pc
	.byte	23                              // Abbrev [23] 0x243:0x5 DW_TAG_variable
	.long	250                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	12                              // Abbrev [12] 0x24a:0x17 DW_TAG_lexical_block
	.long	.Ltmp29                         // DW_AT_low_pc
	.long	.Ltmp32-.Ltmp29                 // DW_AT_high_pc
	.byte	24                              // Abbrev [24] 0x253:0xd DW_TAG_variable
	.byte	1                               // DW_AT_location
	.byte	84
	.long	.Linfo_string15                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	69                              // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	25                              // Abbrev [25] 0x262:0x2a DW_TAG_subprogram
	.long	.Linfo_string16                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	33                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.byte	1                               // DW_AT_inline
	.byte	14                              // Abbrev [14] 0x26a:0xb DW_TAG_formal_parameter
	.long	.Linfo_string17                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	33                              // DW_AT_decl_line
	.long	263                             // DW_AT_type
	.byte	14                              // Abbrev [14] 0x275:0xb DW_TAG_formal_parameter
	.long	.Linfo_string18                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	33                              // DW_AT_decl_line
	.long	105                             // DW_AT_type
	.byte	14                              // Abbrev [14] 0x280:0xb DW_TAG_formal_parameter
	.long	.Linfo_string19                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	33                              // DW_AT_decl_line
	.long	54                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	25                              // Abbrev [25] 0x28c:0x2a DW_TAG_subprogram
	.long	.Linfo_string20                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	51                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.byte	1                               // DW_AT_inline
	.byte	14                              // Abbrev [14] 0x294:0xb DW_TAG_formal_parameter
	.long	.Linfo_string17                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	51                              // DW_AT_decl_line
	.long	263                             // DW_AT_type
	.byte	14                              // Abbrev [14] 0x29f:0xb DW_TAG_formal_parameter
	.long	.Linfo_string18                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	51                              // DW_AT_decl_line
	.long	105                             // DW_AT_type
	.byte	14                              // Abbrev [14] 0x2aa:0xb DW_TAG_formal_parameter
	.long	.Linfo_string19                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	51                              // DW_AT_decl_line
	.long	54                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	18                              // Abbrev [18] 0x2b6:0x179 DW_TAG_subprogram
	.long	.Lfunc_begin2                   // DW_AT_low_pc
	.long	.Lfunc_end2-.Lfunc_begin2       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string22                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	77                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	105                             // DW_AT_type
                                        // DW_AT_external
	.byte	20                              // Abbrev [20] 0x2cb:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc16                   // DW_AT_location
	.long	.Linfo_string9                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	77                              // DW_AT_decl_line
	.long	105                             // DW_AT_type
	.byte	20                              // Abbrev [20] 0x2da:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc17                   // DW_AT_location
	.long	.Linfo_string10                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	77                              // DW_AT_decl_line
	.long	263                             // DW_AT_type
	.byte	20                              // Abbrev [20] 0x2e9:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc18                   // DW_AT_location
	.long	.Linfo_string11                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	77                              // DW_AT_decl_line
	.long	269                             // DW_AT_type
	.byte	24                              // Abbrev [24] 0x2f8:0xe DW_TAG_variable
	.byte	2                               // DW_AT_location
	.byte	145
	.byte	112
	.long	.Linfo_string33                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	79                              // DW_AT_decl_line
	.long	2499                            // DW_AT_type
	.byte	15                              // Abbrev [15] 0x306:0xb DW_TAG_variable
	.long	.Linfo_string37                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	80                              // DW_AT_decl_line
	.long	105                             // DW_AT_type
	.byte	21                              // Abbrev [21] 0x311:0xf DW_TAG_variable
	.long	.Ldebug_loc19                   // DW_AT_location
	.long	.Linfo_string38                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	82                              // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	21                              // Abbrev [21] 0x320:0xf DW_TAG_variable
	.long	.Ldebug_loc20                   // DW_AT_location
	.long	.Linfo_string39                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	86                              // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	21                              // Abbrev [21] 0x32f:0xf DW_TAG_variable
	.long	.Ldebug_loc21                   // DW_AT_location
	.long	.Linfo_string40                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	84                              // DW_AT_decl_line
	.long	269                             // DW_AT_type
	.byte	21                              // Abbrev [21] 0x33e:0xf DW_TAG_variable
	.long	.Ldebug_loc22                   // DW_AT_location
	.long	.Linfo_string41                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	83                              // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	12                              // Abbrev [12] 0x34d:0x55 DW_TAG_lexical_block
	.long	.Ltmp36                         // DW_AT_low_pc
	.long	.Ltmp43-.Ltmp36                 // DW_AT_high_pc
	.byte	21                              // Abbrev [21] 0x356:0xf DW_TAG_variable
	.long	.Ldebug_loc23                   // DW_AT_location
	.long	.Linfo_string42                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	89                              // DW_AT_decl_line
	.long	269                             // DW_AT_type
	.byte	22                              // Abbrev [22] 0x365:0x1e DW_TAG_inlined_subroutine
	.long	610                             // DW_AT_abstract_origin
	.long	.Ltmp39                         // DW_AT_low_pc
	.long	.Ltmp40-.Ltmp39                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	90                              // DW_AT_call_line
	.byte	9                               // DW_AT_call_column
	.byte	8                               // Abbrev [8] 0x375:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	94
	.long	618                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x37c:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	640                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x383:0x1e DW_TAG_inlined_subroutine
	.long	652                             // DW_AT_abstract_origin
	.long	.Ltmp41                         // DW_AT_low_pc
	.long	.Ltmp42-.Ltmp41                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	92                              // DW_AT_call_line
	.byte	9                               // DW_AT_call_column
	.byte	8                               // Abbrev [8] 0x393:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	94
	.long	671                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x39a:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	682                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x3a2:0x21 DW_TAG_inlined_subroutine
	.long	652                             // DW_AT_abstract_origin
	.long	.Ltmp46                         // DW_AT_low_pc
	.long	.Ltmp47-.Ltmp46                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	99                              // DW_AT_call_line
	.byte	13                              // DW_AT_call_column
	.byte	27                              // Abbrev [27] 0x3b2:0x5 DW_TAG_formal_parameter
	.long	660                             // DW_AT_abstract_origin
	.byte	27                              // Abbrev [27] 0x3b7:0x5 DW_TAG_formal_parameter
	.long	671                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x3bc:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	682                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x3c3:0x1c DW_TAG_inlined_subroutine
	.long	652                             // DW_AT_abstract_origin
	.long	.Ltmp54                         // DW_AT_low_pc
	.long	.Ltmp55-.Ltmp54                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	106                             // DW_AT_call_line
	.byte	13                              // DW_AT_call_column
	.byte	27                              // Abbrev [27] 0x3d3:0x5 DW_TAG_formal_parameter
	.long	671                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x3d8:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	682                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x3df:0x1e DW_TAG_inlined_subroutine
	.long	610                             // DW_AT_abstract_origin
	.long	.Ltmp60                         // DW_AT_low_pc
	.long	.Ltmp61-.Ltmp60                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	113                             // DW_AT_call_line
	.byte	9                               // DW_AT_call_column
	.byte	8                               // Abbrev [8] 0x3ef:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	99
	.long	618                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x3f6:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	640                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x3fd:0x23 DW_TAG_inlined_subroutine
	.long	652                             // DW_AT_abstract_origin
	.long	.Ltmp62                         // DW_AT_low_pc
	.long	.Ltmp63-.Ltmp62                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	115                             // DW_AT_call_line
	.byte	9                               // DW_AT_call_column
	.byte	27                              // Abbrev [27] 0x40d:0x5 DW_TAG_formal_parameter
	.long	660                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x412:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	99
	.long	671                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x419:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	682                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	28                              // Abbrev [28] 0x420:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp41                         // DW_AT_low_pc
	.byte	28                              // Abbrev [28] 0x427:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp62                         // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	18                              // Abbrev [18] 0x42f:0x12e DW_TAG_subprogram
	.long	.Lfunc_begin3                   // DW_AT_low_pc
	.long	.Lfunc_end3-.Lfunc_begin3       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string23                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	122                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	105                             // DW_AT_type
                                        // DW_AT_external
	.byte	20                              // Abbrev [20] 0x444:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc24                   // DW_AT_location
	.long	.Linfo_string9                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	122                             // DW_AT_decl_line
	.long	105                             // DW_AT_type
	.byte	20                              // Abbrev [20] 0x453:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc25                   // DW_AT_location
	.long	.Linfo_string10                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	122                             // DW_AT_decl_line
	.long	263                             // DW_AT_type
	.byte	20                              // Abbrev [20] 0x462:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc26                   // DW_AT_location
	.long	.Linfo_string11                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	122                             // DW_AT_decl_line
	.long	269                             // DW_AT_type
	.byte	24                              // Abbrev [24] 0x471:0xe DW_TAG_variable
	.byte	2                               // DW_AT_location
	.byte	145
	.byte	112
	.long	.Linfo_string43                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	124                             // DW_AT_decl_line
	.long	2499                            // DW_AT_type
	.byte	15                              // Abbrev [15] 0x47f:0xb DW_TAG_variable
	.long	.Linfo_string44                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	125                             // DW_AT_decl_line
	.long	105                             // DW_AT_type
	.byte	21                              // Abbrev [21] 0x48a:0xf DW_TAG_variable
	.long	.Ldebug_loc27                   // DW_AT_location
	.long	.Linfo_string38                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	127                             // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	21                              // Abbrev [21] 0x499:0xf DW_TAG_variable
	.long	.Ldebug_loc28                   // DW_AT_location
	.long	.Linfo_string39                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	131                             // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	21                              // Abbrev [21] 0x4a8:0xf DW_TAG_variable
	.long	.Ldebug_loc29                   // DW_AT_location
	.long	.Linfo_string40                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	129                             // DW_AT_decl_line
	.long	269                             // DW_AT_type
	.byte	21                              // Abbrev [21] 0x4b7:0xf DW_TAG_variable
	.long	.Ldebug_loc30                   // DW_AT_location
	.long	.Linfo_string41                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	128                             // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	21                              // Abbrev [21] 0x4c6:0xf DW_TAG_variable
	.long	.Ldebug_loc31                   // DW_AT_location
	.long	.Linfo_string42                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	132                             // DW_AT_decl_line
	.long	269                             // DW_AT_type
	.byte	22                              // Abbrev [22] 0x4d5:0x1e DW_TAG_inlined_subroutine
	.long	610                             // DW_AT_abstract_origin
	.long	.Ltmp72                         // DW_AT_low_pc
	.long	.Ltmp73-.Ltmp72                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	134                             // DW_AT_call_line
	.byte	5                               // DW_AT_call_column
	.byte	8                               // Abbrev [8] 0x4e5:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	95
	.long	618                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x4ec:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	640                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x4f3:0x21 DW_TAG_inlined_subroutine
	.long	610                             // DW_AT_abstract_origin
	.long	.Ltmp78                         // DW_AT_low_pc
	.long	.Ltmp79-.Ltmp78                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	141                             // DW_AT_call_line
	.byte	13                              // DW_AT_call_column
	.byte	27                              // Abbrev [27] 0x503:0x5 DW_TAG_formal_parameter
	.long	618                             // DW_AT_abstract_origin
	.byte	27                              // Abbrev [27] 0x508:0x5 DW_TAG_formal_parameter
	.long	629                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x50d:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	640                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x514:0x1c DW_TAG_inlined_subroutine
	.long	610                             // DW_AT_abstract_origin
	.long	.Ltmp83                         // DW_AT_low_pc
	.long	.Ltmp84-.Ltmp83                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	147                             // DW_AT_call_line
	.byte	13                              // DW_AT_call_column
	.byte	27                              // Abbrev [27] 0x524:0x5 DW_TAG_formal_parameter
	.long	618                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x529:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	640                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x530:0x1e DW_TAG_inlined_subroutine
	.long	610                             // DW_AT_abstract_origin
	.long	.Ltmp89                         // DW_AT_low_pc
	.long	.Ltmp90-.Ltmp89                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	155                             // DW_AT_call_line
	.byte	9                               // DW_AT_call_column
	.byte	8                               // Abbrev [8] 0x540:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	618                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x547:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	640                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	28                              // Abbrev [28] 0x54e:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp74                         // DW_AT_low_pc
	.byte	28                              // Abbrev [28] 0x555:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp92                         // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	18                              // Abbrev [18] 0x55d:0x452 DW_TAG_subprogram
	.long	.Lfunc_begin4                   // DW_AT_low_pc
	.long	.Lfunc_end4-.Lfunc_begin4       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string24                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	163                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	105                             // DW_AT_type
                                        // DW_AT_external
	.byte	20                              // Abbrev [20] 0x572:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc32                   // DW_AT_location
	.long	.Linfo_string9                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	163                             // DW_AT_decl_line
	.long	105                             // DW_AT_type
	.byte	20                              // Abbrev [20] 0x581:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc33                   // DW_AT_location
	.long	.Linfo_string10                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	163                             // DW_AT_decl_line
	.long	263                             // DW_AT_type
	.byte	20                              // Abbrev [20] 0x590:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc34                   // DW_AT_location
	.long	.Linfo_string11                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	163                             // DW_AT_decl_line
	.long	269                             // DW_AT_type
	.byte	24                              // Abbrev [24] 0x59f:0xe DW_TAG_variable
	.byte	2                               // DW_AT_location
	.byte	145
	.byte	88
	.long	.Linfo_string43                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	165                             // DW_AT_decl_line
	.long	2499                            // DW_AT_type
	.byte	24                              // Abbrev [24] 0x5ad:0xe DW_TAG_variable
	.byte	2                               // DW_AT_location
	.byte	145
	.byte	96
	.long	.Linfo_string33                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	166                             // DW_AT_decl_line
	.long	2499                            // DW_AT_type
	.byte	15                              // Abbrev [15] 0x5bb:0xb DW_TAG_variable
	.long	.Linfo_string37                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	168                             // DW_AT_decl_line
	.long	105                             // DW_AT_type
	.byte	15                              // Abbrev [15] 0x5c6:0xb DW_TAG_variable
	.long	.Linfo_string44                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	167                             // DW_AT_decl_line
	.long	105                             // DW_AT_type
	.byte	21                              // Abbrev [21] 0x5d1:0xf DW_TAG_variable
	.long	.Ldebug_loc35                   // DW_AT_location
	.long	.Linfo_string38                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	170                             // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	21                              // Abbrev [21] 0x5e0:0xf DW_TAG_variable
	.long	.Ldebug_loc36                   // DW_AT_location
	.long	.Linfo_string40                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	172                             // DW_AT_decl_line
	.long	269                             // DW_AT_type
	.byte	21                              // Abbrev [21] 0x5ef:0xf DW_TAG_variable
	.long	.Ldebug_loc37                   // DW_AT_location
	.long	.Linfo_string41                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	171                             // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	29                              // Abbrev [29] 0x5fe:0x123 DW_TAG_lexical_block
	.long	.Ldebug_ranges0                 // DW_AT_ranges
	.byte	21                              // Abbrev [21] 0x603:0xf DW_TAG_variable
	.long	.Ldebug_loc38                   // DW_AT_location
	.long	.Linfo_string39                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	175                             // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	12                              // Abbrev [12] 0x612:0x73 DW_TAG_lexical_block
	.long	.Ltmp102                        // DW_AT_low_pc
	.long	.Ltmp110-.Ltmp102               // DW_AT_high_pc
	.byte	21                              // Abbrev [21] 0x61b:0xf DW_TAG_variable
	.long	.Ldebug_loc39                   // DW_AT_location
	.long	.Linfo_string42                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	178                             // DW_AT_decl_line
	.long	269                             // DW_AT_type
	.byte	22                              // Abbrev [22] 0x62a:0x1e DW_TAG_inlined_subroutine
	.long	610                             // DW_AT_abstract_origin
	.long	.Ltmp105                        // DW_AT_low_pc
	.long	.Ltmp106-.Ltmp105               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	179                             // DW_AT_call_line
	.byte	13                              // DW_AT_call_column
	.byte	8                               // Abbrev [8] 0x63a:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	100
	.long	618                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x641:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	640                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x648:0x1e DW_TAG_inlined_subroutine
	.long	610                             // DW_AT_abstract_origin
	.long	.Ltmp106                        // DW_AT_low_pc
	.long	.Ltmp107-.Ltmp106               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	180                             // DW_AT_call_line
	.byte	13                              // DW_AT_call_column
	.byte	8                               // Abbrev [8] 0x658:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	101
	.long	618                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x65f:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	640                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x666:0x1e DW_TAG_inlined_subroutine
	.long	652                             // DW_AT_abstract_origin
	.long	.Ltmp108                        // DW_AT_low_pc
	.long	.Ltmp109-.Ltmp108               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	182                             // DW_AT_call_line
	.byte	13                              // DW_AT_call_column
	.byte	8                               // Abbrev [8] 0x676:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	100
	.long	671                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x67d:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	682                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x685:0x1c DW_TAG_inlined_subroutine
	.long	610                             // DW_AT_abstract_origin
	.long	.Ltmp111                        // DW_AT_low_pc
	.long	.Ltmp112-.Ltmp111               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	188                             // DW_AT_call_line
	.byte	13                              // DW_AT_call_column
	.byte	27                              // Abbrev [27] 0x695:0x5 DW_TAG_formal_parameter
	.long	618                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x69a:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	640                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x6a1:0x1c DW_TAG_inlined_subroutine
	.long	652                             // DW_AT_abstract_origin
	.long	.Ltmp112                        // DW_AT_low_pc
	.long	.Ltmp113-.Ltmp112               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	189                             // DW_AT_call_line
	.byte	13                              // DW_AT_call_column
	.byte	27                              // Abbrev [27] 0x6b1:0x5 DW_TAG_formal_parameter
	.long	671                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x6b6:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	682                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x6bd:0x1e DW_TAG_inlined_subroutine
	.long	610                             // DW_AT_abstract_origin
	.long	.Ltmp118                        // DW_AT_low_pc
	.long	.Ltmp119-.Ltmp118               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	195                             // DW_AT_call_line
	.byte	13                              // DW_AT_call_column
	.byte	8                               // Abbrev [8] 0x6cd:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	94
	.long	618                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x6d4:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	640                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x6db:0x1e DW_TAG_inlined_subroutine
	.long	610                             // DW_AT_abstract_origin
	.long	.Ltmp120                        // DW_AT_low_pc
	.long	.Ltmp121-.Ltmp120               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	196                             // DW_AT_call_line
	.byte	13                              // DW_AT_call_column
	.byte	8                               // Abbrev [8] 0x6eb:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	618                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x6f2:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	640                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x6f9:0x27 DW_TAG_inlined_subroutine
	.long	652                             // DW_AT_abstract_origin
	.long	.Ltmp123                        // DW_AT_low_pc
	.long	.Ltmp125-.Ltmp123               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	198                             // DW_AT_call_line
	.byte	13                              // DW_AT_call_column
	.byte	9                               // Abbrev [9] 0x709:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc40                   // DW_AT_location
	.long	660                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x712:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	94
	.long	671                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x719:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	682                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	29                              // Abbrev [29] 0x721:0x247 DW_TAG_lexical_block
	.long	.Ldebug_ranges1                 // DW_AT_ranges
	.byte	21                              // Abbrev [21] 0x726:0xf DW_TAG_variable
	.long	.Ldebug_loc41                   // DW_AT_location
	.long	.Linfo_string45                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	201                             // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	21                              // Abbrev [21] 0x735:0xf DW_TAG_variable
	.long	.Ldebug_loc42                   // DW_AT_location
	.long	.Linfo_string46                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	202                             // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	15                              // Abbrev [15] 0x744:0xb DW_TAG_variable
	.long	.Linfo_string47                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	203                             // DW_AT_decl_line
	.long	269                             // DW_AT_type
	.byte	22                              // Abbrev [22] 0x74f:0x1e DW_TAG_inlined_subroutine
	.long	610                             // DW_AT_abstract_origin
	.long	.Ltmp130                        // DW_AT_low_pc
	.long	.Ltmp131-.Ltmp130               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	213                             // DW_AT_call_line
	.byte	9                               // DW_AT_call_column
	.byte	8                               // Abbrev [8] 0x75f:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	101
	.long	618                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x766:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	640                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x76d:0x21 DW_TAG_inlined_subroutine
	.long	610                             // DW_AT_abstract_origin
	.long	.Ltmp133                        // DW_AT_low_pc
	.long	.Ltmp135-.Ltmp133               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	217                             // DW_AT_call_line
	.byte	13                              // DW_AT_call_column
	.byte	8                               // Abbrev [8] 0x77d:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	100
	.long	618                             // DW_AT_abstract_origin
	.byte	9                               // Abbrev [9] 0x784:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc43                   // DW_AT_location
	.long	640                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	12                              // Abbrev [12] 0x78e:0x19 DW_TAG_lexical_block
	.long	.Ltmp136                        // DW_AT_low_pc
	.long	.Ltmp141-.Ltmp136               // DW_AT_high_pc
	.byte	21                              // Abbrev [21] 0x797:0xf DW_TAG_variable
	.long	.Ldebug_loc44                   // DW_AT_location
	.long	.Linfo_string42                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	220                             // DW_AT_decl_line
	.long	269                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	12                              // Abbrev [12] 0x7a7:0x46 DW_TAG_lexical_block
	.long	.Ltmp152                        // DW_AT_low_pc
	.long	.Ltmp161-.Ltmp152               // DW_AT_high_pc
	.byte	21                              // Abbrev [21] 0x7b0:0xf DW_TAG_variable
	.long	.Ldebug_loc46                   // DW_AT_location
	.long	.Linfo_string42                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	225                             // DW_AT_decl_line
	.long	269                             // DW_AT_type
	.byte	21                              // Abbrev [21] 0x7bf:0xf DW_TAG_variable
	.long	.Ldebug_loc47                   // DW_AT_location
	.long	.Linfo_string48                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	230                             // DW_AT_decl_line
	.long	269                             // DW_AT_type
	.byte	22                              // Abbrev [22] 0x7ce:0x1e DW_TAG_inlined_subroutine
	.long	610                             // DW_AT_abstract_origin
	.long	.Ltmp155                        // DW_AT_low_pc
	.long	.Ltmp156-.Ltmp155               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	227                             // DW_AT_call_line
	.byte	17                              // DW_AT_call_column
	.byte	8                               // Abbrev [8] 0x7de:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	618                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x7e5:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	640                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x7ed:0x1e DW_TAG_inlined_subroutine
	.long	652                             // DW_AT_abstract_origin
	.long	.Ltmp162                        // DW_AT_low_pc
	.long	.Ltmp163-.Ltmp162               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	236                             // DW_AT_call_line
	.byte	13                              // DW_AT_call_column
	.byte	8                               // Abbrev [8] 0x7fd:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	100
	.long	671                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x804:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	682                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x80b:0x1e DW_TAG_inlined_subroutine
	.long	610                             // DW_AT_abstract_origin
	.long	.Ltmp142                        // DW_AT_low_pc
	.long	.Ltmp143-.Ltmp142               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	206                             // DW_AT_call_line
	.byte	13                              // DW_AT_call_column
	.byte	8                               // Abbrev [8] 0x81b:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	100
	.long	618                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x822:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	640                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x829:0x1e DW_TAG_inlined_subroutine
	.long	610                             // DW_AT_abstract_origin
	.long	.Ltmp143                        // DW_AT_low_pc
	.long	.Ltmp144-.Ltmp143               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	207                             // DW_AT_call_line
	.byte	13                              // DW_AT_call_column
	.byte	8                               // Abbrev [8] 0x839:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	101
	.long	618                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x840:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	640                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x847:0x27 DW_TAG_inlined_subroutine
	.long	652                             // DW_AT_abstract_origin
	.long	.Ltmp145                        // DW_AT_low_pc
	.long	.Ltmp147-.Ltmp145               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	209                             // DW_AT_call_line
	.byte	13                              // DW_AT_call_column
	.byte	9                               // Abbrev [9] 0x857:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc45                   // DW_AT_location
	.long	660                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x860:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	100
	.long	671                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x867:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	682                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	12                              // Abbrev [12] 0x86e:0x64 DW_TAG_lexical_block
	.long	.Ltmp168                        // DW_AT_low_pc
	.long	.Ltmp177-.Ltmp168               // DW_AT_high_pc
	.byte	24                              // Abbrev [24] 0x877:0xd DW_TAG_variable
	.byte	1                               // DW_AT_location
	.byte	98
	.long	.Linfo_string42                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	242                             // DW_AT_decl_line
	.long	269                             // DW_AT_type
	.byte	21                              // Abbrev [21] 0x884:0xf DW_TAG_variable
	.long	.Ldebug_loc49                   // DW_AT_location
	.long	.Linfo_string48                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	247                             // DW_AT_decl_line
	.long	269                             // DW_AT_type
	.byte	22                              // Abbrev [22] 0x893:0x1f DW_TAG_inlined_subroutine
	.long	610                             // DW_AT_abstract_origin
	.long	.Ltmp169                        // DW_AT_low_pc
	.long	.Ltmp171-.Ltmp169               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	244                             // DW_AT_call_line
	.byte	13                              // DW_AT_call_column
	.byte	27                              // Abbrev [27] 0x8a3:0x5 DW_TAG_formal_parameter
	.long	618                             // DW_AT_abstract_origin
	.byte	9                               // Abbrev [9] 0x8a8:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc48                   // DW_AT_location
	.long	640                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x8b2:0x1f DW_TAG_inlined_subroutine
	.long	652                             // DW_AT_abstract_origin
	.long	.Ltmp173                        // DW_AT_low_pc
	.long	.Ltmp175-.Ltmp173               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	249                             // DW_AT_call_line
	.byte	13                              // DW_AT_call_column
	.byte	27                              // Abbrev [27] 0x8c2:0x5 DW_TAG_formal_parameter
	.long	671                             // DW_AT_abstract_origin
	.byte	9                               // Abbrev [9] 0x8c7:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc50                   // DW_AT_location
	.long	682                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	12                              // Abbrev [12] 0x8d2:0x95 DW_TAG_lexical_block
	.long	.Ltmp179                        // DW_AT_low_pc
	.long	.Ltmp191-.Ltmp179               // DW_AT_high_pc
	.byte	30                              // Abbrev [30] 0x8db:0x10 DW_TAG_variable
	.long	.Ldebug_loc51                   // DW_AT_location
	.long	.Linfo_string42                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	257                             // DW_AT_decl_line
	.long	269                             // DW_AT_type
	.byte	22                              // Abbrev [22] 0x8eb:0x1e DW_TAG_inlined_subroutine
	.long	610                             // DW_AT_abstract_origin
	.long	.Ltmp181                        // DW_AT_low_pc
	.long	.Ltmp182-.Ltmp181               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	255                             // DW_AT_call_line
	.byte	13                              // DW_AT_call_column
	.byte	8                               // Abbrev [8] 0x8fb:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	96
	.long	618                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x902:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	640                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	12                              // Abbrev [12] 0x909:0x39 DW_TAG_lexical_block
	.long	.Ltmp185                        // DW_AT_low_pc
	.long	.Ltmp190-.Ltmp185               // DW_AT_high_pc
	.byte	30                              // Abbrev [30] 0x912:0x10 DW_TAG_variable
	.long	.Ldebug_loc52                   // DW_AT_location
	.long	.Linfo_string48                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	261                             // DW_AT_decl_line
	.long	269                             // DW_AT_type
	.byte	31                              // Abbrev [31] 0x922:0x1f DW_TAG_inlined_subroutine
	.long	610                             // DW_AT_abstract_origin
	.long	.Ltmp187                        // DW_AT_low_pc
	.long	.Ltmp188-.Ltmp187               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.short	262                             // DW_AT_call_line
	.byte	17                              // DW_AT_call_column
	.byte	8                               // Abbrev [8] 0x933:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	618                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x93a:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	640                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	31                              // Abbrev [31] 0x942:0x24 DW_TAG_inlined_subroutine
	.long	652                             // DW_AT_abstract_origin
	.long	.Ltmp190                        // DW_AT_low_pc
	.long	.Ltmp191-.Ltmp190               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.short	266                             // DW_AT_call_line
	.byte	13                              // DW_AT_call_column
	.byte	27                              // Abbrev [27] 0x953:0x5 DW_TAG_formal_parameter
	.long	660                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x958:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	96
	.long	671                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x95f:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	682                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	28                              // Abbrev [28] 0x968:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp108                        // DW_AT_low_pc
	.byte	28                              // Abbrev [28] 0x96f:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp123                        // DW_AT_low_pc
	.byte	28                              // Abbrev [28] 0x976:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp138                        // DW_AT_low_pc
	.byte	28                              // Abbrev [28] 0x97d:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp145                        // DW_AT_low_pc
	.byte	28                              // Abbrev [28] 0x984:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp154                        // DW_AT_low_pc
	.byte	28                              // Abbrev [28] 0x98b:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp159                        // DW_AT_low_pc
	.byte	28                              // Abbrev [28] 0x992:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp169                        // DW_AT_low_pc
	.byte	28                              // Abbrev [28] 0x999:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp173                        // DW_AT_low_pc
	.byte	28                              // Abbrev [28] 0x9a0:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp184                        // DW_AT_low_pc
	.byte	28                              // Abbrev [28] 0x9a7:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp190                        // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	5                               // Abbrev [5] 0x9af:0x5 DW_TAG_const_type
	.long	38                              // DW_AT_type
	.byte	5                               // Abbrev [5] 0x9b4:0x5 DW_TAG_const_type
	.long	61                              // DW_AT_type
	.byte	2                               // Abbrev [2] 0x9b9:0x5 DW_TAG_pointer_type
	.long	2494                            // DW_AT_type
	.byte	5                               // Abbrev [5] 0x9be:0x5 DW_TAG_const_type
	.long	43                              // DW_AT_type
	.byte	32                              // Abbrev [32] 0x9c3:0xc DW_TAG_array_type
	.long	2511                            // DW_AT_type
	.byte	33                              // Abbrev [33] 0x9c8:0x6 DW_TAG_subrange_type
	.long	2529                            // DW_AT_type
	.byte	1                               // DW_AT_count
	.byte	0                               // End Of Children Mark
	.byte	3                               // Abbrev [3] 0x9cf:0xb DW_TAG_typedef
	.long	2522                            // DW_AT_type
	.long	.Linfo_string35                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	53                              // DW_AT_decl_line
	.byte	4                               // Abbrev [4] 0x9da:0x7 DW_TAG_base_type
	.long	.Linfo_string34                 // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	34                              // Abbrev [34] 0x9e1:0x7 DW_TAG_base_type
	.long	.Linfo_string36                 // DW_AT_name
	.byte	8                               // DW_AT_byte_size
	.byte	7                               // DW_AT_encoding
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_ranges,"",@progbits
.Ldebug_ranges0:
	.long	.Ltmp101
	.long	.Ltmp125
	.long	.Ltmp148
	.long	.Ltmp149
	.long	0
	.long	0
.Ldebug_ranges1:
	.long	.Ltmp125
	.long	.Ltmp147
	.long	.Ltmp150
	.long	.Ltmp191
	.long	0
	.long	0
.Ldebug_ranges2:
	.long	.Lfunc_begin0
	.long	.Lfunc_end0
	.long	.Lfunc_begin1
	.long	.Lfunc_end1
	.long	.Lfunc_begin2
	.long	.Lfunc_end2
	.long	.Lfunc_begin3
	.long	.Lfunc_end3
	.long	.Lfunc_begin4
	.long	.Lfunc_end4
	.long	0
	.long	0
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/stdlib/memcpy.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=152
.Linfo_string3:
	.asciz	"unsigned int"                  // string offset=173
.Linfo_string4:
	.asciz	"uint32_t"                      // string offset=186
.Linfo_string5:
	.asciz	"unsigned char"                 // string offset=195
.Linfo_string6:
	.asciz	"uint8_t"                       // string offset=209
.Linfo_string7:
	.asciz	"uintptr_t"                     // string offset=217
.Linfo_string8:
	.asciz	"__memcpy_wram_4align"          // string offset=227
.Linfo_string9:
	.asciz	"dest"                          // string offset=248
.Linfo_string10:
	.asciz	"src"                           // string offset=253
.Linfo_string11:
	.asciz	"len"                           // string offset=257
.Linfo_string12:
	.asciz	"size_t"                        // string offset=261
.Linfo_string13:
	.asciz	"dw"                            // string offset=268
.Linfo_string14:
	.asciz	"sw"                            // string offset=271
.Linfo_string15:
	.asciz	"i"                             // string offset=274
.Linfo_string16:
	.asciz	"mram_read"                     // string offset=276
.Linfo_string17:
	.asciz	"from"                          // string offset=286
.Linfo_string18:
	.asciz	"to"                            // string offset=291
.Linfo_string19:
	.asciz	"nb_of_bytes"                   // string offset=294
.Linfo_string20:
	.asciz	"mram_write"                    // string offset=306
.Linfo_string21:
	.asciz	"memcpy"                        // string offset=317
.Linfo_string22:
	.asciz	"__memcpy_mw"                   // string offset=324
.Linfo_string23:
	.asciz	"__memcpy_wm"                   // string offset=336
.Linfo_string24:
	.asciz	"__memcpy_mm"                   // string offset=348
.Linfo_string25:
	.asciz	"d"                             // string offset=360
.Linfo_string26:
	.asciz	"s"                             // string offset=362
.Linfo_string27:
	.asciz	"body"                          // string offset=364
.Linfo_string28:
	.asciz	"tail"                          // string offset=369
.Linfo_string29:
	.asciz	"head"                          // string offset=374
.Linfo_string30:
	.asciz	"head_len"                      // string offset=379
.Linfo_string31:
	.asciz	"body_len"                      // string offset=388
.Linfo_string32:
	.asciz	"tail_len"                      // string offset=397
.Linfo_string33:
	.asciz	"destCache64"                   // string offset=406
.Linfo_string34:
	.asciz	"long unsigned int"             // string offset=418
.Linfo_string35:
	.asciz	"uint64_t"                      // string offset=436
.Linfo_string36:
	.asciz	"__ARRAY_SIZE_TYPE__"           // string offset=445
.Linfo_string37:
	.asciz	"destCache"                     // string offset=465
.Linfo_string38:
	.asciz	"srcOff"                        // string offset=475
.Linfo_string39:
	.asciz	"idx"                           // string offset=482
.Linfo_string40:
	.asciz	"remaining"                     // string offset=486
.Linfo_string41:
	.asciz	"destOff"                       // string offset=496
.Linfo_string42:
	.asciz	"part"                          // string offset=504
.Linfo_string43:
	.asciz	"srcCache64"                    // string offset=509
.Linfo_string44:
	.asciz	"srcCache"                      // string offset=520
.Linfo_string45:
	.asciz	"srcIdx"                        // string offset=529
.Linfo_string46:
	.asciz	"destIdx"                       // string offset=536
.Linfo_string47:
	.asciz	"initLen"                       // string offset=544
.Linfo_string48:
	.asciz	"part2"                         // string offset=552
	.addrsig
	.addrsig_sym __memcpy_wram_4align
	.addrsig_sym __memcpy_mw
	.addrsig_sym __memcpy_wm
	.addrsig_sym __memcpy_mm
	.section	.debug_line,"",@progbits
.Lline_table_start0:
