	.text
	.file	"memcmp.c"
	.section	.text.memcmp,"ax",@progbits
	.globl	memcmp                          // -- Begin function memcmp
	.type	memcmp,@function
memcmp:                                 // @memcmp
.Lfunc_begin0:
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/memcmp.c"
	.loc	1 10 0                          // uPIMulator_frontend/sdk/stdlib/memcmp.c:10:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: memcmp:area1 <- $r0
	//DEBUG_VALUE: memcmp:area2 <- $r1
	//DEBUG_VALUE: memcmp:size <- $r2
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: memcmp:ptr1 <- $r0
	//DEBUG_VALUE: memcmp:ptr2 <- $r1
	move r4, 0
.Ltmp0:
	//DEBUG_VALUE: each_byte <- 0
	//DEBUG_VALUE: memcmp:ptr2 <- $r1
	//DEBUG_VALUE: memcmp:ptr1 <- $r0
	//DEBUG_VALUE: memcmp:size <- $r2
	//DEBUG_VALUE: memcmp:area2 <- $r1
	//DEBUG_VALUE: memcmp:area1 <- $r0
	.loc	1 14 5 prologue_end             // uPIMulator_frontend/sdk/stdlib/memcmp.c:14:5
	jeq r2, 0, .LBB0_4
.Ltmp1:
.LBB0_1:                                // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: each_byte <- undef
	.loc	1 15 20                         // uPIMulator_frontend/sdk/stdlib/memcmp.c:15:20
	lbu r3, r0, 0
	.loc	1 15 38 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/memcmp.c:15:38
	lbu r5, r1, 0
.Ltmp2:
	//DEBUG_VALUE: diff <- $r3
	//DEBUG_VALUE: each_byte <- [DW_OP_plus_uconst 1, DW_OP_stack_value] undef
	.loc	1 15 36                         // uPIMulator_frontend/sdk/stdlib/memcmp.c:15:36
	sub r3, r3, r5, nz, .LBB0_5
.Ltmp3:
// %bb.2:                               //   in Loop: Header=BB0_1 Depth=1
	//DEBUG_VALUE: each_byte <- [DW_OP_plus_uconst 1, DW_OP_stack_value] undef
	.loc	1 14 42 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memcmp.c:14:42
	add r1, r1, 1
	add r0, r0, 1
	add r2, r2, -1, nz, .LBB0_1
.Ltmp4:
.LBB0_4:
	.loc	1 0 42 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memcmp.c:0:42
	move r3, r4
.LBB0_5:
	.loc	1 22 1 is_stmt 1                // uPIMulator_frontend/sdk/stdlib/memcmp.c:22:1
	move r0, r3
	jump r23
.Ltmp5:
.Lfunc_end0:
	.size	memcmp, .Lfunc_end0-memcmp
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.memcmp
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.memcmp,"ax",@progbits
                                        // -- End function
	.file	2 "/root" "uPIMulator_frontend/sdk/stdlib/stddef.h"
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp1-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp1-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp1-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp1-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc4:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp1-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc5:
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp1-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc6:
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp3-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0xdf DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x5 DW_TAG_pointer_type
	.long	43                              // DW_AT_type
	.byte	3                               // Abbrev [3] 0x2b:0x5 DW_TAG_const_type
	.long	48                              // DW_AT_type
	.byte	4                               // Abbrev [4] 0x30:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	8                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	5                               // Abbrev [5] 0x37:0x93 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	202                             // DW_AT_type
                                        // DW_AT_external
	.byte	6                               // Abbrev [6] 0x4c:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string6                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
	.long	209                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x5b:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string7                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
	.long	209                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x6a:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string8                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
	.long	215                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0x79:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string11                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	11                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	7                               // Abbrev [7] 0x88:0xf DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	.Linfo_string12                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	12                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0x97:0x32 DW_TAG_lexical_block
	.long	.Ltmp0                          // DW_AT_low_pc
	.long	.Ltmp4-.Ltmp0                   // DW_AT_high_pc
	.byte	7                               // Abbrev [7] 0xa0:0xf DW_TAG_variable
	.long	.Ldebug_loc5                    // DW_AT_location
	.long	.Linfo_string13                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	14                              // DW_AT_decl_line
	.long	215                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0xaf:0x19 DW_TAG_lexical_block
	.long	.Ltmp1                          // DW_AT_low_pc
	.long	.Ltmp3-.Ltmp1                   // DW_AT_high_pc
	.byte	7                               // Abbrev [7] 0xb8:0xf DW_TAG_variable
	.long	.Ldebug_loc6                    // DW_AT_location
	.long	.Linfo_string14                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	15                              // DW_AT_decl_line
	.long	202                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	4                               // Abbrev [4] 0xca:0x7 DW_TAG_base_type
	.long	.Linfo_string5                  // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	2                               // Abbrev [2] 0xd1:0x5 DW_TAG_pointer_type
	.long	214                             // DW_AT_type
	.byte	9                               // Abbrev [9] 0xd6:0x1 DW_TAG_const_type
	.byte	10                              // Abbrev [10] 0xd7:0xb DW_TAG_typedef
	.long	226                             // DW_AT_type
	.long	.Linfo_string10                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	26                              // DW_AT_decl_line
	.byte	4                               // Abbrev [4] 0xe2:0x7 DW_TAG_base_type
	.long	.Linfo_string9                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/stdlib/memcmp.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=152
.Linfo_string3:
	.asciz	"unsigned char"                 // string offset=173
.Linfo_string4:
	.asciz	"memcmp"                        // string offset=187
.Linfo_string5:
	.asciz	"int"                           // string offset=194
.Linfo_string6:
	.asciz	"area1"                         // string offset=198
.Linfo_string7:
	.asciz	"area2"                         // string offset=204
.Linfo_string8:
	.asciz	"size"                          // string offset=210
.Linfo_string9:
	.asciz	"unsigned int"                  // string offset=215
.Linfo_string10:
	.asciz	"size_t"                        // string offset=228
.Linfo_string11:
	.asciz	"ptr1"                          // string offset=235
.Linfo_string12:
	.asciz	"ptr2"                          // string offset=240
.Linfo_string13:
	.asciz	"each_byte"                     // string offset=245
.Linfo_string14:
	.asciz	"diff"                          // string offset=255
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
