	.text
	.file	"memmove.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/stdint.h"
	.section	.text.memmove,"ax",@progbits
	.globl	memmove                         // -- Begin function memmove
	.type	memmove,@function
memmove:                                // @memmove
.Lfunc_begin0:
	.file	2 "/root" "uPIMulator_frontend/sdk/stdlib/memmove.c"
	.loc	2 13 0                          // uPIMulator_frontend/sdk/stdlib/memmove.c:13:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: memmove:dest <- $r0
	//DEBUG_VALUE: memmove:src <- $r1
	//DEBUG_VALUE: memmove:len <- $r2
	.cfi_def_cfa_offset -16
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 8, d22
	add r22, r22, 16
	.cfi_offset 15, -16
	.cfi_offset 14, -12
	sd r22, -16, d14
	move r14, r0
	//DEBUG_VALUE: memmove:len <- $r2
	//DEBUG_VALUE: memmove:src <- $r1
.Ltmp0:
	//DEBUG_VALUE: memmove:dest <- $r14
	.loc	2 14 43 prologue_end            // uPIMulator_frontend/sdk/stdlib/memmove.c:14:43
	jleu r14, r1, .LBB0_2
.Ltmp1:
// %bb.1:
	//DEBUG_VALUE: memmove:dest <- $r14
	//DEBUG_VALUE: memmove:len <- $r2
	//DEBUG_VALUE: memmove:src <- $r1
	.loc	2 0 43 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memmove.c:0:43
	add r0, r1, r2
	.loc	2 14 43                         // uPIMulator_frontend/sdk/stdlib/memmove.c:14:43
	jleu r0, r14, .LBB0_2
.Ltmp2:
// %bb.3:
	//DEBUG_VALUE: memmove:dest <- $r14
	//DEBUG_VALUE: memmove:len <- $r2
	//DEBUG_VALUE: memmove:src <- $r1
	.loc	2 20 32 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memmove.c:20:32
	add r3, r14, r2
.Ltmp3:
	//DEBUG_VALUE: body <- undef
	//DEBUG_VALUE: tail <- $r14
	//DEBUG_VALUE: s <- undef
	//DEBUG_VALUE: d <- $r3
	.loc	2 29 35                         // uPIMulator_frontend/sdk/stdlib/memmove.c:29:35
	xor r0, r1, r14
.Ltmp4:
	.loc	2 29 13 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/memmove.c:29:13
	and r5, r3, -4
.Ltmp5:
	.loc	2 29 35                         // uPIMulator_frontend/sdk/stdlib/memmove.c:29:35
	and r4, r0, 3
.Ltmp6:
	.loc	2 29 13                         // uPIMulator_frontend/sdk/stdlib/memmove.c:29:13
	move r0, r14
	jltu r5, r14, .LBB0_5
.Ltmp7:
// %bb.4:
	//DEBUG_VALUE: tail <- $r14
	//DEBUG_VALUE: memmove:dest <- $r14
	//DEBUG_VALUE: d <- $r3
	//DEBUG_VALUE: memmove:len <- $r2
	//DEBUG_VALUE: memmove:src <- $r1
	move r0, r5
.Ltmp8:
.LBB0_5:
	//DEBUG_VALUE: tail <- $r14
	//DEBUG_VALUE: memmove:dest <- $r14
	//DEBUG_VALUE: d <- $r3
	//DEBUG_VALUE: memmove:len <- $r2
	//DEBUG_VALUE: memmove:src <- $r1
	.loc	2 0 0                           // uPIMulator_frontend/sdk/stdlib/memmove.c:0:0
	add r5, r14, 3
.Ltmp9:
	//DEBUG_VALUE: body <- undef
	.loc	2 29 13                         // uPIMulator_frontend/sdk/stdlib/memmove.c:29:13
	jeq r4, 0, .LBB0_7
.Ltmp10:
// %bb.6:
	//DEBUG_VALUE: tail <- $r14
	//DEBUG_VALUE: memmove:dest <- $r14
	//DEBUG_VALUE: d <- $r3
	//DEBUG_VALUE: memmove:len <- $r2
	//DEBUG_VALUE: memmove:src <- $r1
	move r0, r14
.Ltmp11:
.LBB0_7:
	//DEBUG_VALUE: tail <- $r14
	//DEBUG_VALUE: memmove:dest <- $r14
	//DEBUG_VALUE: d <- $r3
	//DEBUG_VALUE: memmove:len <- $r2
	//DEBUG_VALUE: memmove:src <- $r1
	.loc	2 0 13                          // uPIMulator_frontend/sdk/stdlib/memmove.c:0:13
	and r4, r5, -4
.Ltmp12:
	//DEBUG_VALUE: head <- $r0
	//DEBUG_VALUE: body <- $r4
	.loc	2 43 31 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memmove.c:43:31
	sub r5, r3, r0
	//DEBUG_VALUE: i <- [DW_OP_constu 1, DW_OP_minus, DW_OP_stack_value] $r5
.Ltmp13:
	//DEBUG_VALUE: head_len <- $r5
	//DEBUG_VALUE: i <- $r6
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/stdlib/memmove.c:0:0
	add r6, r5, -1, mi, .LBB0_10
.Ltmp14:
// %bb.8:
	//DEBUG_VALUE: tail <- $r14
	//DEBUG_VALUE: memmove:dest <- $r14
	//DEBUG_VALUE: head_len <- $r5
	//DEBUG_VALUE: body <- $r4
	//DEBUG_VALUE: d <- $r3
	//DEBUG_VALUE: memmove:len <- $r2
	//DEBUG_VALUE: memmove:src <- $r1
	//DEBUG_VALUE: head <- $r0
	.loc	2 44 9 is_stmt 1                // uPIMulator_frontend/sdk/stdlib/memmove.c:44:9
	add r6, r2, -1
	add r2, r14, r6
.Ltmp15:
	add r6, r1, r6
	move r7, r5
.Ltmp16:
.LBB0_9:                                // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: tail <- $r14
	//DEBUG_VALUE: memmove:dest <- $r14
	//DEBUG_VALUE: head_len <- $r5
	//DEBUG_VALUE: body <- $r4
	//DEBUG_VALUE: d <- $r3
	//DEBUG_VALUE: memmove:src <- $r1
	//DEBUG_VALUE: head <- $r0
	.loc	2 45 31                         // uPIMulator_frontend/sdk/stdlib/memmove.c:45:31
	lbs r8, r6, 0
	.loc	2 45 29 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/memmove.c:45:29
	sb r2, 0, r8
.Ltmp17:
	//DEBUG_VALUE: i <- [DW_OP_constu 1, DW_OP_minus, DW_OP_stack_value] undef
	.loc	2 44 42 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memmove.c:44:42
	add r2, r2, -1
	add r6, r6, -1
	add r7, r7, -1
.Ltmp18:
	.loc	2 44 9 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memmove.c:44:9
	jgts r7, 0, .LBB0_9
.Ltmp19:
.LBB0_10:
	//DEBUG_VALUE: tail <- $r14
	//DEBUG_VALUE: memmove:dest <- $r14
	//DEBUG_VALUE: head_len <- $r5
	//DEBUG_VALUE: body <- $r4
	//DEBUG_VALUE: d <- $r3
	//DEBUG_VALUE: memmove:src <- $r1
	//DEBUG_VALUE: head <- $r0
	.loc	2 48 29 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memmove.c:48:29
	sub r2, r3, r5
.Ltmp20:
	//DEBUG_VALUE: dw <- $r2
	//DEBUG_VALUE: sw <- undef
	.loc	2 0 29 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memmove.c:0:29
	move r3, 0
.Ltmp21:
	.loc	2 51 29 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memmove.c:51:29
	jltu r2, r4, .LBB0_12
.Ltmp22:
// %bb.11:
	//DEBUG_VALUE: tail <- $r14
	//DEBUG_VALUE: memmove:dest <- $r14
	//DEBUG_VALUE: head_len <- $r5
	//DEBUG_VALUE: body <- $r4
	//DEBUG_VALUE: dw <- $r2
	//DEBUG_VALUE: memmove:src <- $r1
	//DEBUG_VALUE: head <- $r0
	.loc	2 0 29 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memmove.c:0:29
	sub r3, r2, r4
	asr r3, r3, 2
.Ltmp23:
.LBB0_12:
	//DEBUG_VALUE: tail <- $r14
	//DEBUG_VALUE: memmove:dest <- $r14
	//DEBUG_VALUE: head_len <- $r5
	//DEBUG_VALUE: body <- $r4
	//DEBUG_VALUE: dw <- $r2
	//DEBUG_VALUE: memmove:src <- $r1
	//DEBUG_VALUE: head <- $r0
	//DEBUG_VALUE: body_len <- $r3
	//DEBUG_VALUE: i <- [DW_OP_constu 1, DW_OP_minus, DW_OP_stack_value] $r3
	.loc	2 52 9 is_stmt 1                // uPIMulator_frontend/sdk/stdlib/memmove.c:52:9
	jlts r3, 1, .LBB0_15
.Ltmp24:
// %bb.13:
	//DEBUG_VALUE: tail <- $r14
	//DEBUG_VALUE: memmove:dest <- $r14
	//DEBUG_VALUE: head_len <- $r5
	//DEBUG_VALUE: body <- $r4
	//DEBUG_VALUE: i <- [DW_OP_constu 1, DW_OP_minus, DW_OP_stack_value] $r3
	//DEBUG_VALUE: body_len <- $r3
	//DEBUG_VALUE: dw <- $r2
	//DEBUG_VALUE: memmove:src <- $r1
	//DEBUG_VALUE: head <- $r0
	add r4, r3, 1
.Ltmp25:
	add r0, r0, -4
.Ltmp26:
	sub r5, r0, r14
.Ltmp27:
	add r5, r1, r5
.Ltmp28:
.LBB0_14:                               // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: tail <- $r14
	//DEBUG_VALUE: memmove:dest <- $r14
	//DEBUG_VALUE: body_len <- $r3
	//DEBUG_VALUE: dw <- $r2
	//DEBUG_VALUE: memmove:src <- $r1
	.loc	2 53 32                         // uPIMulator_frontend/sdk/stdlib/memmove.c:53:32
	lw r6, r5, 0
	.loc	2 53 30 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/memmove.c:53:30
	sw r0, 0, r6
.Ltmp29:
	//DEBUG_VALUE: i <- [DW_OP_constu 2, DW_OP_minus, DW_OP_constu 1, DW_OP_minus, DW_OP_stack_value] $r4
	.loc	2 52 42 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memmove.c:52:42
	add r0, r0, -4
	add r5, r5, -4
	add r4, r4, -1
.Ltmp30:
	.loc	2 52 9 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memmove.c:52:9
	jgts r4, 1, .LBB0_14
.Ltmp31:
.LBB0_15:
	//DEBUG_VALUE: tail <- $r14
	//DEBUG_VALUE: memmove:dest <- $r14
	//DEBUG_VALUE: body_len <- $r3
	//DEBUG_VALUE: dw <- $r2
	//DEBUG_VALUE: memmove:src <- $r1
	.loc	2 56 25 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memmove.c:56:25
	lsl_sub r0, r2, r3, 2
.Ltmp32:
	//DEBUG_VALUE: s <- undef
	//DEBUG_VALUE: d <- $r0
	.loc	2 59 31                         // uPIMulator_frontend/sdk/stdlib/memmove.c:59:31
	sub r0, r0, r14
.Ltmp33:
	//DEBUG_VALUE: i <- [DW_OP_constu 1, DW_OP_minus, DW_OP_stack_value] $r0
	//DEBUG_VALUE: tail_len <- $r0
	//DEBUG_VALUE: i <- $r2
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/stdlib/memmove.c:0:0
	add r2, r0, -1, mi, .LBB0_17
.Ltmp34:
.LBB0_16:                               // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: tail <- $r14
	//DEBUG_VALUE: memmove:dest <- $r14
	//DEBUG_VALUE: memmove:src <- $r1
	.loc	2 61 31 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memmove.c:61:31
	add r2, r1, r0
	lbs r2, r2, -1
	.loc	2 61 29 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/memmove.c:61:29
	add r3, r14, r0
	sb r3, -1, r2
.Ltmp35:
	//DEBUG_VALUE: i <- [DW_OP_constu 1, DW_OP_minus, DW_OP_stack_value] undef
	.loc	2 60 42 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memmove.c:60:42
	add r0, r0, -1
.Ltmp36:
	.loc	2 60 9 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memmove.c:60:9
	jgts r0, 0, .LBB0_16
.Ltmp37:
.LBB0_17:
	//DEBUG_VALUE: memmove:dest <- $r14
	//DEBUG_VALUE: memmove:src <- $r1
	.loc	2 65 1 is_stmt 1                // uPIMulator_frontend/sdk/stdlib/memmove.c:65:1
	move r0, r14
	ld d14, r22, -16
.Ltmp38:
	ld d22, r22, -8
	jump r23
.Ltmp39:
.LBB0_2:
	//DEBUG_VALUE: memmove:dest <- $r14
	//DEBUG_VALUE: memmove:len <- $r2
	//DEBUG_VALUE: memmove:src <- $r1
	.loc	2 17 16                         // uPIMulator_frontend/sdk/stdlib/memmove.c:17:16
	move r0, r14
	call r23, memcpy
.Ltmp40:
	.loc	2 65 1                          // uPIMulator_frontend/sdk/stdlib/memmove.c:65:1
	move r0, r14
	ld d14, r22, -16
.Ltmp41:
	ld d22, r22, -8
	jump r23
.Ltmp42:
.Lfunc_end0:
	.size	memmove, .Lfunc_end0-memmove
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.memmove
	.long	.Lfunc_begin0
	.byte	16
	.section	.text.memmove,"ax",@progbits
                                        // -- End function
	.section	.text.__memmove_mm,"ax",@progbits
	.globl	__memmove_mm                    // -- Begin function __memmove_mm
	.type	__memmove_mm,@function
__memmove_mm:                           // @__memmove_mm
.Lfunc_begin1:
	.loc	2 69 0                          // uPIMulator_frontend/sdk/stdlib/memmove.c:69:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __memmove_mm:dest <- $r0
	//DEBUG_VALUE: __memmove_mm:src <- $r1
	//DEBUG_VALUE: __memmove_mm:len <- $r2
	.cfi_def_cfa_offset -64
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 56, d22
	add r22, r22, 64
	.cfi_offset 15, -40
	.cfi_offset 14, -36
	sd r22, -40, d14
	.cfi_offset 17, -48
	.cfi_offset 16, -44
	sd r22, -48, d16
	.cfi_offset 19, -56
	.cfi_offset 18, -52
	sd r22, -56, d18
	.cfi_offset 21, -64
	.cfi_offset 20, -60
	sd r22, -64, d20
	move r15, r2
	move r21, r0
.Ltmp43:
	//DEBUG_VALUE: __memmove_mm:len <- $r15
	//DEBUG_VALUE: __memmove_mm:src <- $r1
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	.loc	2 70 43 prologue_end            // uPIMulator_frontend/sdk/stdlib/memmove.c:70:43
	jleu r21, r1, .LBB1_2
.Ltmp44:
// %bb.1:
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	//DEBUG_VALUE: __memmove_mm:len <- $r15
	//DEBUG_VALUE: __memmove_mm:src <- $r1
	.loc	2 70 80 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/memmove.c:70:80
	add r14, r1, r15
.Ltmp45:
	.loc	2 70 9                          // uPIMulator_frontend/sdk/stdlib/memmove.c:70:9
	jleu r14, r21, .LBB1_2
.Ltmp46:
// %bb.3:
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	//DEBUG_VALUE: __memmove_mm:len <- $r15
	//DEBUG_VALUE: __memmove_mm:src <- $r1
	//DEBUG_VALUE: srcCache <- undef
	//DEBUG_VALUE: destCache <- undef
	//DEBUG_VALUE: srcIdx <- $r14
	.loc	2 81 40 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memmove.c:81:40
	add r16, r21, r15
.Ltmp47:
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: dstIdx <- $r16
	.loc	2 84 47                         // uPIMulator_frontend/sdk/stdlib/memmove.c:84:47
	and r20, r14, 7
.Ltmp48:
	//DEBUG_VALUE: srcOff <- $r20
	.loc	2 85 47                         // uPIMulator_frontend/sdk/stdlib/memmove.c:85:47
	and r17, r16, 7
.Ltmp49:
	//DEBUG_VALUE: dstOff <- $r17
	.loc	2 87 13                         // uPIMulator_frontend/sdk/stdlib/memmove.c:87:13
	jneq r20, r17, .LBB1_12
.Ltmp50:
// %bb.4:
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	//DEBUG_VALUE: srcOff <- $r20
	//DEBUG_VALUE: dstOff <- $r17
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: __memmove_mm:len <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: __memmove_mm:src <- $r1
	.loc	2 88 27                         // uPIMulator_frontend/sdk/stdlib/memmove.c:88:27
	move r17, r15
.Ltmp51:
	jgtu r20, r15, .LBB1_6
.Ltmp52:
// %bb.5:
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	//DEBUG_VALUE: srcOff <- $r20
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: __memmove_mm:len <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: __memmove_mm:src <- $r1
	move r17, r20
.Ltmp53:
.LBB1_6:
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	//DEBUG_VALUE: srcOff <- $r20
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: __memmove_mm:len <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: __memmove_mm:src <- $r1
	//DEBUG_VALUE: part <- $r17
	//DEBUG_VALUE: off <- undef
	.loc	2 91 17                         // uPIMulator_frontend/sdk/stdlib/memmove.c:91:17
	jeq r20, 0, .LBB1_8
.Ltmp54:
// %bb.7:
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	//DEBUG_VALUE: srcOff <- $r20
	//DEBUG_VALUE: part <- $r17
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: __memmove_mm:len <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: __memmove_mm:src <- $r1
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/stdlib/memmove.c:0:0
	sub r1, r20, r17
.Ltmp55:
	//DEBUG_VALUE: off <- $r1
	.loc	2 92 24 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memmove.c:92:24
	sub r14, r14, r20
.Ltmp56:
	//DEBUG_VALUE: srcIdx <- $r14
	.loc	2 93 24                         // uPIMulator_frontend/sdk/stdlib/memmove.c:93:24
	sub r16, r16, r20
.Ltmp57:
	//DEBUG_VALUE: dstIdx <- $r16
	.loc	2 0 24 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memmove.c:0:24
	add r18, r22, -24
.Ltmp58:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:from <- $r16
	.file	3 "/root" "uPIMulator_frontend/sdk/syslib/mram.h"
	.loc	3 35 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r18, r16, 0
	add r2, r22, -32
.Ltmp59:
	//DEBUG_VALUE: mram_read:from <- $r14
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 24, DW_OP_minus, DW_OP_stack_value] $r22
	.loc	3 35 24 is_stmt 0               // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r2, r14, 0
.Ltmp60:
	.loc	2 97 34 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memmove.c:97:34
	add r0, r18, r1
	.loc	2 97 50 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/memmove.c:97:50
	add r1, r2, r1
.Ltmp61:
	.loc	2 97 17                         // uPIMulator_frontend/sdk/stdlib/memmove.c:97:17
	move r2, r17
	call r23, memcpy
.Ltmp62:
	//DEBUG_VALUE: mram_write:to <- $r16
	//DEBUG_VALUE: mram_write:nb_of_bytes <- 8
	.loc	3 53 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:53:24
	sdma r18, r16, 0
.Ltmp63:
	.loc	2 99 27                         // uPIMulator_frontend/sdk/stdlib/memmove.c:99:27
	sub r15, r15, r17
.Ltmp64:
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 32, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: mram_write:from <- [DW_OP_constu 24, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: remaining <- $r15
.LBB1_8:
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	//DEBUG_VALUE: srcOff <- $r20
	//DEBUG_VALUE: part <- $r17
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: srcIdx <- [DW_OP_constu 8, DW_OP_minus, DW_OP_stack_value] $r14
	//DEBUG_VALUE: dstIdx <- [DW_OP_constu 8, DW_OP_minus, DW_OP_stack_value] $r16
	//DEBUG_VALUE: remaining <- $r15
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/stdlib/memmove.c:0:0
	add r0, r14, -8
	add r14, r16, -8
.Ltmp65:
	//DEBUG_VALUE: dstIdx <- $r14
	//DEBUG_VALUE: srcIdx <- $r0
	.loc	2 105 13 is_stmt 1              // uPIMulator_frontend/sdk/stdlib/memmove.c:105:13
	jltu r15, 8, .LBB1_10
.Ltmp66:
.LBB1_9:                                // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	//DEBUG_VALUE: srcOff <- $r20
	//DEBUG_VALUE: part <- $r17
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: remaining <- $r15
	.loc	2 0 13 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memmove.c:0:13
	add r1, r22, -32
.Ltmp67:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:from <- $r0
	.loc	3 35 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r1, r0, 0
.Ltmp68:
	//DEBUG_VALUE: mram_write:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_write:to <- $r14
	.loc	3 53 24                         // uPIMulator_frontend/sdk/syslib/mram.h:53:24
	sdma r1, r14, 0
.Ltmp69:
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/stdlib/memmove.c:0:0
	add r0, r0, -8
.Ltmp70:
	add r14, r14, -8
.Ltmp71:
	//DEBUG_VALUE: mram_write:from <- [DW_OP_constu 32, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 32, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: dstIdx <- $r14
	//DEBUG_VALUE: srcIdx <- $r0
	.loc	2 108 27 is_stmt 1              // uPIMulator_frontend/sdk/stdlib/memmove.c:108:27
	add r15, r15, -8
.Ltmp72:
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: dstIdx <- [DW_OP_constu 8, DW_OP_minus, DW_OP_stack_value] $r14
	//DEBUG_VALUE: srcIdx <- [DW_OP_constu 8, DW_OP_minus, DW_OP_stack_value] $r0
	.loc	2 105 13                        // uPIMulator_frontend/sdk/stdlib/memmove.c:105:13
	jgtu r15, 7, .LBB1_9
.Ltmp73:
.LBB1_10:
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	//DEBUG_VALUE: srcOff <- $r20
	//DEBUG_VALUE: part <- $r17
	//DEBUG_VALUE: remaining <- $r15
	.loc	2 113 17                        // uPIMulator_frontend/sdk/stdlib/memmove.c:113:17
	jeq r15, 0, .LBB1_29
.Ltmp74:
// %bb.11:
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	//DEBUG_VALUE: srcOff <- $r20
	//DEBUG_VALUE: part <- $r17
	//DEBUG_VALUE: remaining <- $r15
	.loc	2 114 48                        // uPIMulator_frontend/sdk/stdlib/memmove.c:114:48
	sub r1, 8, r15
.Ltmp75:
	//DEBUG_VALUE: off <- $r1
	.loc	2 0 48 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memmove.c:0:48
	add r16, r22, -24
.Ltmp76:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:from <- $r14
	.loc	3 35 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r16, r14, 0
	add r2, r22, -32
.Ltmp77:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 24, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: mram_read:from <- $r0
	.loc	3 35 24 is_stmt 0               // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r2, r0, 0
.Ltmp78:
	.loc	2 118 34 is_stmt 1              // uPIMulator_frontend/sdk/stdlib/memmove.c:118:34
	add r0, r16, r1
.Ltmp79:
	.loc	2 118 50 is_stmt 0              // uPIMulator_frontend/sdk/stdlib/memmove.c:118:50
	add r1, r2, r1
.Ltmp80:
	.loc	2 118 17                        // uPIMulator_frontend/sdk/stdlib/memmove.c:118:17
	move r2, r15
	call r23, memcpy
.Ltmp81:
	//DEBUG_VALUE: mram_write:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_write:to <- $r14
	.loc	3 53 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:53:24
	sdma r16, r14, 0
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 32, DW_OP_minus, DW_OP_stack_value] $r22
.Ltmp82:
	//DEBUG_VALUE: mram_write:from <- [DW_OP_constu 24, DW_OP_minus, DW_OP_stack_value] $r22
	.loc	3 0 24 is_stmt 0                // uPIMulator_frontend/sdk/syslib/mram.h:0:24
	jump .LBB1_29
.Ltmp83:
.LBB1_2:
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	//DEBUG_VALUE: __memmove_mm:len <- $r15
	//DEBUG_VALUE: __memmove_mm:src <- $r1
	.loc	2 73 42 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/memmove.c:73:42
	move r0, r21
	move r2, r15
	call r23, __memcpy_mm
.Ltmp84:
.LBB1_29:
	.loc	2 191 1                         // uPIMulator_frontend/sdk/stdlib/memmove.c:191:1
	move r0, r21
	ld d20, r22, -64
	ld d18, r22, -56
	ld d16, r22, -48
	ld d14, r22, -40
	ld d22, r22, -8
	jump r23
.LBB1_12:
.Ltmp85:
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	//DEBUG_VALUE: srcOff <- $r20
	//DEBUG_VALUE: dstOff <- $r17
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: __memmove_mm:len <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: __memmove_mm:src <- $r1
	.loc	2 122 30                        // uPIMulator_frontend/sdk/stdlib/memmove.c:122:30
	move r0, r17
	jltu r17, r20, .LBB1_14
.Ltmp86:
// %bb.13:
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	//DEBUG_VALUE: srcOff <- $r20
	//DEBUG_VALUE: dstOff <- $r17
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: __memmove_mm:len <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: __memmove_mm:src <- $r1
	move r0, r20
.Ltmp87:
.LBB1_14:
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	//DEBUG_VALUE: srcOff <- $r20
	//DEBUG_VALUE: dstOff <- $r17
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: __memmove_mm:len <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: __memmove_mm:src <- $r1
	//DEBUG_VALUE: initLen <- undef
	.loc	2 124 17                        // uPIMulator_frontend/sdk/stdlib/memmove.c:124:17
	jgeu r0, r15, .LBB1_15
.Ltmp88:
// %bb.16:
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	//DEBUG_VALUE: srcOff <- $r20
	//DEBUG_VALUE: dstOff <- $r17
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: __memmove_mm:len <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: __memmove_mm:src <- $r1
	.loc	2 0 17 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memmove.c:0:17
	add r0, r22, -32
.Ltmp89:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:from <- $r14
	.loc	3 35 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r0, r14, 0
.Ltmp90:
	.loc	2 133 20                        // uPIMulator_frontend/sdk/stdlib/memmove.c:133:20
	add r14, r14, -8
.Ltmp91:
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 32, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: srcIdx <- $r14
	.loc	2 135 17                        // uPIMulator_frontend/sdk/stdlib/memmove.c:135:17
	jeq r17, 0, .LBB1_21
.Ltmp92:
// %bb.17:
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	//DEBUG_VALUE: srcOff <- $r20
	//DEBUG_VALUE: dstOff <- $r17
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: __memmove_mm:len <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: __memmove_mm:src <- $r1
	.loc	2 136 31                        // uPIMulator_frontend/sdk/stdlib/memmove.c:136:31
	add r0, r17, 7
	and r0, r0, 8
.Ltmp93:
	//DEBUG_VALUE: part <- $r0
	.loc	2 0 31 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memmove.c:0:31
	add r18, r22, -24
	.loc	2 137 45 is_stmt 1              // uPIMulator_frontend/sdk/stdlib/memmove.c:137:45
	sub r1, r18, r0
.Ltmp94:
	.loc	2 137 63 is_stmt 0              // uPIMulator_frontend/sdk/stdlib/memmove.c:137:63
	add r1, r1, 8
	move r2, -1
.Ltmp95:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- $r0
	//DEBUG_VALUE: mram_read:from <- $r16
	//DEBUG_VALUE: mram_read:to <- $r1
	.loc	3 35 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	lsr_add r0, r2, r0, 3
.Ltmp96:
	lsl_add r0, r1, r0, 24
	ldma r0, r16, 0
.Ltmp97:
	.loc	2 139 21                        // uPIMulator_frontend/sdk/stdlib/memmove.c:139:21
	jgeu r17, r20, .LBB1_19
.Ltmp98:
// %bb.18:
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	//DEBUG_VALUE: srcOff <- $r20
	//DEBUG_VALUE: dstOff <- $r17
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: __memmove_mm:len <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: part <- $r17
	.loc	2 0 21 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memmove.c:0:21
	add r0, r22, -32
.Ltmp99:
	.loc	2 141 48 is_stmt 1              // uPIMulator_frontend/sdk/stdlib/memmove.c:141:48
	or r0, r0, r20
	.loc	2 141 57 is_stmt 0              // uPIMulator_frontend/sdk/stdlib/memmove.c:141:57
	sub r1, r0, r17
	add r0, r22, -24
	.loc	2 141 21                        // uPIMulator_frontend/sdk/stdlib/memmove.c:141:21
	move r2, r17
	call r23, memcpy
.Ltmp100:
	//DEBUG_VALUE: srcOff <- $r20
	.loc	2 142 28 is_stmt 1              // uPIMulator_frontend/sdk/stdlib/memmove.c:142:28
	sub r20, r20, r17, true, .LBB1_20
.Ltmp101:
.LBB1_15:
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	//DEBUG_VALUE: srcOff <- $r20
	//DEBUG_VALUE: dstOff <- $r17
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: __memmove_mm:len <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: __memmove_mm:src <- $r1
	.loc	2 0 28 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memmove.c:0:28
	add r14, r22, -24
.Ltmp102:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:from <- $r21
	.loc	3 35 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r14, r21, 0
	add r2, r22, -32
.Ltmp103:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 24, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: mram_read:from <- $r1
	.loc	3 35 24 is_stmt 0               // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r2, r1, 0
.Ltmp104:
	.loc	2 127 34 is_stmt 1              // uPIMulator_frontend/sdk/stdlib/memmove.c:127:34
	or r0, r14, r17
	.loc	2 127 43 is_stmt 0              // uPIMulator_frontend/sdk/stdlib/memmove.c:127:43
	sub r0, r0, r15
	.loc	2 127 65                        // uPIMulator_frontend/sdk/stdlib/memmove.c:127:65
	or r1, r2, r20
.Ltmp105:
	.loc	2 127 74                        // uPIMulator_frontend/sdk/stdlib/memmove.c:127:74
	sub r1, r1, r15
	.loc	2 127 17                        // uPIMulator_frontend/sdk/stdlib/memmove.c:127:17
	move r2, r15
	call r23, memcpy
.Ltmp106:
	//DEBUG_VALUE: mram_write:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_write:to <- $r21
	.loc	3 53 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:53:24
	sdma r14, r21, 0
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 32, DW_OP_minus, DW_OP_stack_value] $r22
.Ltmp107:
	//DEBUG_VALUE: mram_write:from <- [DW_OP_constu 24, DW_OP_minus, DW_OP_stack_value] $r22
	.loc	3 0 24 is_stmt 0                // uPIMulator_frontend/sdk/syslib/mram.h:0:24
	jump .LBB1_29
.Ltmp108:
.LBB1_19:
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	//DEBUG_VALUE: srcOff <- $r20
	//DEBUG_VALUE: dstOff <- $r17
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: __memmove_mm:len <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: part <- $r20
	.loc	2 145 38 is_stmt 1              // uPIMulator_frontend/sdk/stdlib/memmove.c:145:38
	or r0, r18, r17
	.loc	2 145 47 is_stmt 0              // uPIMulator_frontend/sdk/stdlib/memmove.c:145:47
	sub r0, r0, r20
	add r19, r22, -32
	.loc	2 145 21                        // uPIMulator_frontend/sdk/stdlib/memmove.c:145:21
	move r1, r19
	move r2, r20
	call r23, memcpy
.Ltmp109:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:from <- $r14
	.loc	3 35 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r19, r14, 0
.Ltmp110:
	.loc	2 147 28                        // uPIMulator_frontend/sdk/stdlib/memmove.c:147:28
	add r14, r14, -8
.Ltmp111:
	//DEBUG_VALUE: srcIdx <- $r14
	.loc	2 149 43                        // uPIMulator_frontend/sdk/stdlib/memmove.c:149:43
	sub r20, r17, r20
.Ltmp112:
	//DEBUG_VALUE: part2 <- $r20
	.loc	2 150 48                        // uPIMulator_frontend/sdk/stdlib/memmove.c:150:48
	sub r0, r19, r20
	.loc	2 150 66 is_stmt 0              // uPIMulator_frontend/sdk/stdlib/memmove.c:150:66
	add r1, r0, 8
	.loc	2 150 21                        // uPIMulator_frontend/sdk/stdlib/memmove.c:150:21
	move r0, r18
	move r2, r20
	call r23, memcpy
.Ltmp113:
	.loc	2 152 46 is_stmt 1              // uPIMulator_frontend/sdk/stdlib/memmove.c:152:46
	sub r20, 8, r20
.Ltmp114:
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 32, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: srcOff <- $r20
.LBB1_20:
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	//DEBUG_VALUE: dstOff <- $r17
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: __memmove_mm:len <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: srcOff <- $r20
	.loc	2 0 46 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memmove.c:0:46
	add r0, r22, -24
.Ltmp115:
	//DEBUG_VALUE: mram_write:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_write:to <- $r16
	.loc	3 53 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:53:24
	sdma r0, r16, 0
.Ltmp116:
	.loc	2 156 24                        // uPIMulator_frontend/sdk/stdlib/memmove.c:156:24
	add r16, r16, -8
.Ltmp117:
	//DEBUG_VALUE: dstIdx <- $r16
	.loc	2 157 27                        // uPIMulator_frontend/sdk/stdlib/memmove.c:157:27
	sub r15, r15, r17
.Ltmp118:
	//DEBUG_VALUE: mram_write:from <- [DW_OP_constu 24, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: remaining <- $r15
.LBB1_21:
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	//DEBUG_VALUE: srcOff <- $r20
	//DEBUG_VALUE: dstOff <- $r17
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: srcOff <- $r20
	sw r22, -12, r21
	.loc	2 160 13                        // uPIMulator_frontend/sdk/stdlib/memmove.c:160:13
	jltu r15, 8, .LBB1_22
.Ltmp119:
// %bb.23:
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	//DEBUG_VALUE: srcOff <- $r20
	//DEBUG_VALUE: dstOff <- $r17
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	.loc	2 0 13 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memmove.c:0:13
	add r17, r22, -32
.Ltmp120:
	add r0, r20, r17
	sw r22, -16, r0
	sub r19, 8, r20
	move r18, r20
	add r20, r22, -24
.Ltmp121:
	sub r0, r20, r18
	add r21, r0, 8
.Ltmp122:
.LBB1_24:                               // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: part <- $r18
	.loc	2 162 17 is_stmt 1              // uPIMulator_frontend/sdk/stdlib/memmove.c:162:17
	move r0, r21
	move r1, r17
	move r2, r18
	call r23, memcpy
.Ltmp123:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:from <- $r14
	.loc	3 35 24                         // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r17, r14, 0
.Ltmp124:
	.loc	2 164 24                        // uPIMulator_frontend/sdk/stdlib/memmove.c:164:24
	add r14, r14, -8
.Ltmp125:
	//DEBUG_VALUE: part2 <- $r19
	//DEBUG_VALUE: srcIdx <- $r14
	.loc	2 167 17                        // uPIMulator_frontend/sdk/stdlib/memmove.c:167:17
	move r0, r20
	lw r1, r22, -16
	move r2, r19
	call r23, memcpy
.Ltmp126:
	//DEBUG_VALUE: mram_write:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_write:to <- $r16
	.loc	3 53 24                         // uPIMulator_frontend/sdk/syslib/mram.h:53:24
	sdma r20, r16, 0
.Ltmp127:
	.loc	2 169 24                        // uPIMulator_frontend/sdk/stdlib/memmove.c:169:24
	add r16, r16, -8
.Ltmp128:
	//DEBUG_VALUE: dstIdx <- $r16
	.loc	2 170 27                        // uPIMulator_frontend/sdk/stdlib/memmove.c:170:27
	add r15, r15, -8
.Ltmp129:
	//DEBUG_VALUE: mram_write:from <- [DW_OP_constu 24, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 32, DW_OP_minus, DW_OP_stack_value] $r22
	//DEBUG_VALUE: remaining <- $r15
	.loc	2 160 13                        // uPIMulator_frontend/sdk/stdlib/memmove.c:160:13
	jgtu r15, 7, .LBB1_24
	jump .LBB1_25
.Ltmp130:
.LBB1_22:
	//DEBUG_VALUE: __memmove_mm:dest <- $r21
	//DEBUG_VALUE: srcOff <- $r20
	//DEBUG_VALUE: dstOff <- $r17
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	.loc	2 0 13 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memmove.c:0:13
	move r18, r20
.Ltmp131:
.LBB1_25:
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	move r20, r18
	lw r21, r22, -12
	.loc	2 173 17 is_stmt 1              // uPIMulator_frontend/sdk/stdlib/memmove.c:173:17
	jeq r15, 0, .LBB1_29
.Ltmp132:
// %bb.26:
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	.loc	2 0 17 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/memmove.c:0:17
	add r18, r22, -24
.Ltmp133:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:from <- $r16
	.loc	3 35 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r18, r16, 0
.Ltmp134:
	//DEBUG_VALUE: part <- $r20
	.loc	2 177 34                        // uPIMulator_frontend/sdk/stdlib/memmove.c:177:34
	add r19, r18, 8
	//DEBUG_VALUE: part <- $r20
	.loc	2 177 52 is_stmt 0              // uPIMulator_frontend/sdk/stdlib/memmove.c:177:52
	sub r0, r19, r20
	add r17, r22, -32
	.loc	2 177 17                        // uPIMulator_frontend/sdk/stdlib/memmove.c:177:17
	move r1, r17
	move r2, r20
	call r23, memcpy
.Ltmp135:
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 24, DW_OP_minus, DW_OP_stack_value] $r22
	.loc	2 179 21 is_stmt 1              // uPIMulator_frontend/sdk/stdlib/memmove.c:179:21
	jleu r15, r20, .LBB1_28
.Ltmp136:
// %bb.27:
	//DEBUG_VALUE: part <- $r20
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	.loc	2 180 46                        // uPIMulator_frontend/sdk/stdlib/memmove.c:180:46
	sub r2, r15, r20
.Ltmp137:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 8
	//DEBUG_VALUE: mram_read:from <- $r14
	//DEBUG_VALUE: part2 <- $r2
	.loc	3 35 24                         // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r17, r14, 0
.Ltmp138:
	.loc	2 182 56                        // uPIMulator_frontend/sdk/stdlib/memmove.c:182:56
	sub r0, r19, r15
	.loc	2 182 78 is_stmt 0              // uPIMulator_frontend/sdk/stdlib/memmove.c:182:78
	sub r1, r17, r2
	.loc	2 182 96                        // uPIMulator_frontend/sdk/stdlib/memmove.c:182:96
	add r1, r1, 8
	.loc	2 182 21                        // uPIMulator_frontend/sdk/stdlib/memmove.c:182:21
	call r23, memcpy
.Ltmp139:
	//DEBUG_VALUE: mram_read:to <- [DW_OP_constu 32, DW_OP_minus, DW_OP_stack_value] $r22
.LBB1_28:
	//DEBUG_VALUE: part <- $r20
	//DEBUG_VALUE: dstIdx <- $r16
	//DEBUG_VALUE: remaining <- $r15
	//DEBUG_VALUE: srcIdx <- $r14
	//DEBUG_VALUE: mram_write:to <- $r16
	//DEBUG_VALUE: mram_write:nb_of_bytes <- 8
	.loc	3 53 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mram.h:53:24
	sdma r18, r16, 0
.Ltmp140:
	//DEBUG_VALUE: mram_write:from <- [DW_OP_constu 24, DW_OP_minus, DW_OP_stack_value] $r22
	.loc	3 0 24 is_stmt 0                // uPIMulator_frontend/sdk/syslib/mram.h:0:24
	jump .LBB1_29
.Ltmp141:
.Lfunc_end1:
	.size	__memmove_mm, .Lfunc_end1-__memmove_mm
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__memmove_mm
	.long	.Lfunc_begin1
	.byte	64
	.section	.text.__memmove_mm,"ax",@progbits
                                        // -- End function
	.file	4 "/root" "uPIMulator_frontend/sdk/stdlib/stddef.h"
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp38-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	.Ltmp39-.Lfunc_begin0
	.long	.Ltmp41-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	0
	.long	0
.Ldebug_loc1:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp15-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp39-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc2:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp12-.Lfunc_begin0
	.long	.Ltmp25-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	0
	.long	0
.Ldebug_loc3:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp37-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	0
	.long	0
.Ldebug_loc4:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp21-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp32-.Lfunc_begin0
	.long	.Ltmp33-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc5:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp12-.Lfunc_begin0
	.long	.Ltmp26-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc6:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp13-.Lfunc_begin0
	.long	.Ltmp14-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	86                              // DW_OP_reg6
	.long	0
	.long	0
.Ldebug_loc7:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp13-.Lfunc_begin0
	.long	.Ltmp27-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	0
	.long	0
.Ldebug_loc8:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp20-.Lfunc_begin0
	.long	.Ltmp34-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc9:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp23-.Lfunc_begin0
	.long	.Ltmp34-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc10:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp23-.Lfunc_begin0
	.long	.Ltmp28-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	115                             // DW_OP_breg3
	.byte	127                             // -1
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp29-.Lfunc_begin0
	.long	.Ltmp30-.Lfunc_begin0
	.short	5                               // Loc expr size
	.byte	116                             // DW_OP_breg4
	.byte	126                             // -2
	.byte	49                              // DW_OP_lit1
	.byte	28                              // DW_OP_minus
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc11:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp33-.Lfunc_begin0
	.long	.Ltmp34-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc12:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp33-.Lfunc_begin0
	.long	.Ltmp34-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc13:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Lfunc_begin1-.Lfunc_begin1
	.long	.Ltmp43-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp43-.Lfunc_begin1
	.long	.Ltmp84-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	101                             // DW_OP_reg21
	.long	.Ltmp85-.Lfunc_begin1
	.long	.Ltmp122-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	101                             // DW_OP_reg21
	.long	.Ltmp130-.Lfunc_begin1
	.long	.Ltmp131-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	101                             // DW_OP_reg21
	.long	0
	.long	0
.Ldebug_loc14:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Lfunc_begin1-.Lfunc_begin1
	.long	.Ltmp55-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp83-.Lfunc_begin1
	.long	.Ltmp84-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp85-.Lfunc_begin1
	.long	.Ltmp94-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp101-.Lfunc_begin1
	.long	.Ltmp105-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc15:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Lfunc_begin1-.Lfunc_begin1
	.long	.Ltmp43-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp43-.Lfunc_begin1
	.long	.Ltmp64-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	.Ltmp83-.Lfunc_begin1
	.long	.Ltmp84-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	.Ltmp85-.Lfunc_begin1
	.long	.Ltmp118-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	0
	.long	0
.Ldebug_loc16:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp46-.Lfunc_begin1
	.long	.Ltmp64-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	.Ltmp64-.Lfunc_begin1
	.long	.Ltmp65-.Lfunc_begin1
	.short	3                               // Loc expr size
	.byte	126                             // DW_OP_breg14
	.byte	120                             // -8
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp65-.Lfunc_begin1
	.long	.Ltmp66-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp71-.Lfunc_begin1
	.long	.Ltmp72-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp72-.Lfunc_begin1
	.long	.Ltmp73-.Lfunc_begin1
	.short	3                               // Loc expr size
	.byte	112                             // DW_OP_breg0
	.byte	120                             // -8
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp85-.Lfunc_begin1
	.long	.Ltmp102-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	.Ltmp108-.Lfunc_begin1
	.long	.Lfunc_end1-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	0
	.long	0
.Ldebug_loc17:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp47-.Lfunc_begin1
	.long	.Ltmp83-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	.Ltmp85-.Lfunc_begin1
	.long	.Lfunc_end1-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	0
	.long	0
.Ldebug_loc18:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp47-.Lfunc_begin1
	.long	.Ltmp64-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	96                              // DW_OP_reg16
	.long	.Ltmp64-.Lfunc_begin1
	.long	.Ltmp65-.Lfunc_begin1
	.short	3                               // Loc expr size
	.byte	128                             // DW_OP_breg16
	.byte	120                             // -8
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp65-.Lfunc_begin1
	.long	.Ltmp66-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	.Ltmp71-.Lfunc_begin1
	.long	.Ltmp72-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	.Ltmp72-.Lfunc_begin1
	.long	.Ltmp73-.Lfunc_begin1
	.short	3                               // Loc expr size
	.byte	126                             // DW_OP_breg14
	.byte	120                             // -8
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp85-.Lfunc_begin1
	.long	.Lfunc_end1-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	96                              // DW_OP_reg16
	.long	0
	.long	0
.Ldebug_loc19:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp48-.Lfunc_begin1
	.long	.Ltmp83-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	100                             // DW_OP_reg20
	.long	.Ltmp85-.Lfunc_begin1
	.long	.Ltmp112-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	100                             // DW_OP_reg20
	.long	.Ltmp114-.Lfunc_begin1
	.long	.Ltmp121-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	100                             // DW_OP_reg20
	.long	.Ltmp130-.Lfunc_begin1
	.long	.Ltmp131-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	100                             // DW_OP_reg20
	.long	0
	.long	0
.Ldebug_loc20:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp49-.Lfunc_begin1
	.long	.Ltmp51-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	97                              // DW_OP_reg17
	.long	.Ltmp85-.Lfunc_begin1
	.long	.Ltmp120-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	97                              // DW_OP_reg17
	.long	.Ltmp130-.Lfunc_begin1
	.long	.Ltmp131-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	97                              // DW_OP_reg17
	.long	0
	.long	0
.Ldebug_loc21:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp53-.Lfunc_begin1
	.long	.Ltmp83-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	97                              // DW_OP_reg17
	.long	0
	.long	0
.Ldebug_loc22:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp55-.Lfunc_begin1
	.long	.Ltmp61-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc23:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp75-.Lfunc_begin1
	.long	.Ltmp80-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc24:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp82-.Lfunc_begin1
	.long	.Ltmp83-.Lfunc_begin1
	.short	3                               // Loc expr size
	.byte	134                             // DW_OP_breg22
	.byte	104                             // -24
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc25:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp93-.Lfunc_begin1
	.long	.Ltmp96-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp98-.Lfunc_begin1
	.long	.Ltmp101-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	97                              // DW_OP_reg17
	.long	.Ltmp108-.Lfunc_begin1
	.long	.Ltmp112-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	100                             // DW_OP_reg20
	.long	0
	.long	0
.Ldebug_loc26:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp95-.Lfunc_begin1
	.long	.Ltmp96-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc27:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp107-.Lfunc_begin1
	.long	.Ltmp108-.Lfunc_begin1
	.short	3                               // Loc expr size
	.byte	134                             // DW_OP_breg22
	.byte	104                             // -24
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc28:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp112-.Lfunc_begin1
	.long	.Ltmp114-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	100                             // DW_OP_reg20
	.long	0
	.long	0
.Ldebug_loc29:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp125-.Lfunc_begin1
	.long	.Ltmp130-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	99                              // DW_OP_reg19
	.long	0
	.long	0
.Ldebug_loc30:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp134-.Lfunc_begin1
	.long	.Lfunc_end1-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	100                             // DW_OP_reg20
	.long	0
	.long	0
.Ldebug_loc31:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp137-.Lfunc_begin1
	.long	.Ltmp139-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc32:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp140-.Lfunc_begin1
	.long	.Lfunc_end1-.Lfunc_begin1
	.short	3                               // Loc expr size
	.byte	134                             // DW_OP_breg22
	.byte	104                             // -24
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	11                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	12                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	13                              // Abbreviation Code
	.ascii	"\211\202\001"                  // DW_TAG_GNU_call_site
	.byte	0                               // DW_CHILDREN_no
	.ascii	"\223B"                         // DW_AT_GNU_call_site_target
	.byte	24                              // DW_FORM_exprloc
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	14                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	15                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	16                              // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	17                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	18                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	19                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	1                               // DW_CHILDREN_yes
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	20                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	21                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	28                              // DW_AT_const_value
	.byte	15                              // DW_FORM_udata
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	22                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	23                              // Abbreviation Code
	.byte	1                               // DW_TAG_array_type
	.byte	1                               // DW_CHILDREN_yes
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	24                              // Abbreviation Code
	.byte	33                              // DW_TAG_subrange_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	55                              // DW_AT_count
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	25                              // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x69c DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	0                               // DW_AT_low_pc
	.long	.Ldebug_ranges2                 // DW_AT_ranges
	.byte	2                               // Abbrev [2] 0x26:0xb DW_TAG_typedef
	.long	49                              // DW_AT_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	144                             // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x31:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x38:0x5 DW_TAG_pointer_type
	.long	61                              // DW_AT_type
	.byte	3                               // Abbrev [3] 0x3d:0x7 DW_TAG_base_type
	.long	.Linfo_string5                  // DW_AT_name
	.byte	6                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x44:0x5 DW_TAG_pointer_type
	.long	73                              // DW_AT_type
	.byte	5                               // Abbrev [5] 0x49:0x5 DW_TAG_const_type
	.long	61                              // DW_AT_type
	.byte	4                               // Abbrev [4] 0x4e:0x5 DW_TAG_pointer_type
	.long	83                              // DW_AT_type
	.byte	2                               // Abbrev [2] 0x53:0xb DW_TAG_typedef
	.long	49                              // DW_AT_type
	.long	.Linfo_string6                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	48                              // DW_AT_decl_line
	.byte	6                               // Abbrev [6] 0x5e:0x1 DW_TAG_pointer_type
	.byte	7                               // Abbrev [7] 0x5f:0x12b DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string12                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	12                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	94                              // DW_AT_type
                                        // DW_AT_external
	.byte	8                               // Abbrev [8] 0x74:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string14                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	12                              // DW_AT_decl_line
	.long	94                              // DW_AT_type
	.byte	9                               // Abbrev [9] 0x83:0xd DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	.Linfo_string15                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	12                              // DW_AT_decl_line
	.long	436                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x90:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string16                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	12                              // DW_AT_decl_line
	.long	1616                            // DW_AT_type
	.byte	10                              // Abbrev [10] 0x9f:0xe3 DW_TAG_lexical_block
	.long	.Ltmp2                          // DW_AT_low_pc
	.long	.Ltmp37-.Ltmp2                  // DW_AT_high_pc
	.byte	11                              // Abbrev [11] 0xa8:0xf DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string18                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	27                              // DW_AT_decl_line
	.long	1627                            // DW_AT_type
	.byte	11                              // Abbrev [11] 0xb7:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string19                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	25                              // DW_AT_decl_line
	.long	1632                            // DW_AT_type
	.byte	12                              // Abbrev [12] 0xc6:0xb DW_TAG_variable
	.long	.Linfo_string20                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	21                              // DW_AT_decl_line
	.long	68                              // DW_AT_type
	.byte	11                              // Abbrev [11] 0xd1:0xf DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	.Linfo_string21                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	20                              // DW_AT_decl_line
	.long	56                              // DW_AT_type
	.byte	11                              // Abbrev [11] 0xe0:0xf DW_TAG_variable
	.long	.Ldebug_loc5                    // DW_AT_location
	.long	.Linfo_string22                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	24                              // DW_AT_decl_line
	.long	56                              // DW_AT_type
	.byte	11                              // Abbrev [11] 0xef:0xf DW_TAG_variable
	.long	.Ldebug_loc7                    // DW_AT_location
	.long	.Linfo_string26                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	43                              // DW_AT_decl_line
	.long	83                              // DW_AT_type
	.byte	11                              // Abbrev [11] 0xfe:0xf DW_TAG_variable
	.long	.Ldebug_loc8                    // DW_AT_location
	.long	.Linfo_string27                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
	.long	78                              // DW_AT_type
	.byte	12                              // Abbrev [12] 0x10d:0xb DW_TAG_variable
	.long	.Linfo_string28                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	23                              // DW_AT_decl_line
	.long	1655                            // DW_AT_type
	.byte	11                              // Abbrev [11] 0x118:0xf DW_TAG_variable
	.long	.Ldebug_loc9                    // DW_AT_location
	.long	.Linfo_string29                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	51                              // DW_AT_decl_line
	.long	83                              // DW_AT_type
	.byte	11                              // Abbrev [11] 0x127:0xf DW_TAG_variable
	.long	.Ldebug_loc12                   // DW_AT_location
	.long	.Linfo_string30                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	59                              // DW_AT_decl_line
	.long	83                              // DW_AT_type
	.byte	10                              // Abbrev [10] 0x136:0x19 DW_TAG_lexical_block
	.long	.Ltmp13                         // DW_AT_low_pc
	.long	.Ltmp19-.Ltmp13                 // DW_AT_high_pc
	.byte	11                              // Abbrev [11] 0x13f:0xf DW_TAG_variable
	.long	.Ldebug_loc6                    // DW_AT_location
	.long	.Linfo_string23                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	44                              // DW_AT_decl_line
	.long	1637                            // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x14f:0x19 DW_TAG_lexical_block
	.long	.Ltmp23                         // DW_AT_low_pc
	.long	.Ltmp31-.Ltmp23                 // DW_AT_high_pc
	.byte	11                              // Abbrev [11] 0x158:0xf DW_TAG_variable
	.long	.Ldebug_loc10                   // DW_AT_location
	.long	.Linfo_string23                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	52                              // DW_AT_decl_line
	.long	1637                            // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x168:0x19 DW_TAG_lexical_block
	.long	.Ltmp33                         // DW_AT_low_pc
	.long	.Ltmp37-.Ltmp33                 // DW_AT_high_pc
	.byte	11                              // Abbrev [11] 0x171:0xf DW_TAG_variable
	.long	.Ldebug_loc11                   // DW_AT_location
	.long	.Linfo_string23                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	60                              // DW_AT_decl_line
	.long	1637                            // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	13                              // Abbrev [13] 0x182:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp40                         // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	14                              // Abbrev [14] 0x18a:0x2a DW_TAG_subprogram
	.long	.Linfo_string7                  // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	33                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.byte	1                               // DW_AT_inline
	.byte	15                              // Abbrev [15] 0x192:0xb DW_TAG_formal_parameter
	.long	.Linfo_string8                  // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	33                              // DW_AT_decl_line
	.long	436                             // DW_AT_type
	.byte	15                              // Abbrev [15] 0x19d:0xb DW_TAG_formal_parameter
	.long	.Linfo_string9                  // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	33                              // DW_AT_decl_line
	.long	94                              // DW_AT_type
	.byte	15                              // Abbrev [15] 0x1a8:0xb DW_TAG_formal_parameter
	.long	.Linfo_string10                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	33                              // DW_AT_decl_line
	.long	49                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	4                               // Abbrev [4] 0x1b4:0x5 DW_TAG_pointer_type
	.long	441                             // DW_AT_type
	.byte	16                              // Abbrev [16] 0x1b9:0x1 DW_TAG_const_type
	.byte	14                              // Abbrev [14] 0x1ba:0x2a DW_TAG_subprogram
	.long	.Linfo_string11                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	51                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.byte	1                               // DW_AT_inline
	.byte	15                              // Abbrev [15] 0x1c2:0xb DW_TAG_formal_parameter
	.long	.Linfo_string8                  // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	51                              // DW_AT_decl_line
	.long	436                             // DW_AT_type
	.byte	15                              // Abbrev [15] 0x1cd:0xb DW_TAG_formal_parameter
	.long	.Linfo_string9                  // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	51                              // DW_AT_decl_line
	.long	94                              // DW_AT_type
	.byte	15                              // Abbrev [15] 0x1d8:0xb DW_TAG_formal_parameter
	.long	.Linfo_string10                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	51                              // DW_AT_decl_line
	.long	49                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x1e4:0x46c DW_TAG_subprogram
	.long	.Lfunc_begin1                   // DW_AT_low_pc
	.long	.Lfunc_end1-.Lfunc_begin1       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string13                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	68                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	94                              // DW_AT_type
                                        // DW_AT_external
	.byte	8                               // Abbrev [8] 0x1f9:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc13                   // DW_AT_location
	.long	.Linfo_string14                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	68                              // DW_AT_decl_line
	.long	94                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0x208:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc14                   // DW_AT_location
	.long	.Linfo_string15                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	68                              // DW_AT_decl_line
	.long	436                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x217:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc15                   // DW_AT_location
	.long	.Linfo_string16                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	68                              // DW_AT_decl_line
	.long	1616                            // DW_AT_type
	.byte	17                              // Abbrev [17] 0x226:0x3dc DW_TAG_lexical_block
	.long	.Ldebug_ranges1                 // DW_AT_ranges
	.byte	18                              // Abbrev [18] 0x22b:0xe DW_TAG_variable
	.byte	2                               // DW_AT_location
	.byte	145
	.byte	96
	.long	.Linfo_string31                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	75                              // DW_AT_decl_line
	.long	1665                            // DW_AT_type
	.byte	18                              // Abbrev [18] 0x239:0xe DW_TAG_variable
	.byte	2                               // DW_AT_location
	.byte	145
	.byte	104
	.long	.Linfo_string35                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	76                              // DW_AT_decl_line
	.long	1665                            // DW_AT_type
	.byte	12                              // Abbrev [12] 0x247:0xb DW_TAG_variable
	.long	.Linfo_string36                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	77                              // DW_AT_decl_line
	.long	94                              // DW_AT_type
	.byte	12                              // Abbrev [12] 0x252:0xb DW_TAG_variable
	.long	.Linfo_string37                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	78                              // DW_AT_decl_line
	.long	94                              // DW_AT_type
	.byte	11                              // Abbrev [11] 0x25d:0xf DW_TAG_variable
	.long	.Ldebug_loc16                   // DW_AT_location
	.long	.Linfo_string38                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	80                              // DW_AT_decl_line
	.long	436                             // DW_AT_type
	.byte	11                              // Abbrev [11] 0x26c:0xf DW_TAG_variable
	.long	.Ldebug_loc17                   // DW_AT_location
	.long	.Linfo_string39                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	82                              // DW_AT_decl_line
	.long	83                              // DW_AT_type
	.byte	11                              // Abbrev [11] 0x27b:0xf DW_TAG_variable
	.long	.Ldebug_loc18                   // DW_AT_location
	.long	.Linfo_string40                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	81                              // DW_AT_decl_line
	.long	94                              // DW_AT_type
	.byte	11                              // Abbrev [11] 0x28a:0xf DW_TAG_variable
	.long	.Ldebug_loc19                   // DW_AT_location
	.long	.Linfo_string41                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	84                              // DW_AT_decl_line
	.long	83                              // DW_AT_type
	.byte	11                              // Abbrev [11] 0x299:0xf DW_TAG_variable
	.long	.Ldebug_loc20                   // DW_AT_location
	.long	.Linfo_string42                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	85                              // DW_AT_decl_line
	.long	83                              // DW_AT_type
	.byte	10                              // Abbrev [10] 0x2a8:0x13a DW_TAG_lexical_block
	.long	.Ltmp50                         // DW_AT_low_pc
	.long	.Ltmp83-.Ltmp50                 // DW_AT_high_pc
	.byte	11                              // Abbrev [11] 0x2b1:0xf DW_TAG_variable
	.long	.Ldebug_loc21                   // DW_AT_location
	.long	.Linfo_string43                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	88                              // DW_AT_decl_line
	.long	1616                            // DW_AT_type
	.byte	11                              // Abbrev [11] 0x2c0:0xf DW_TAG_variable
	.long	.Ldebug_loc22                   // DW_AT_location
	.long	.Linfo_string44                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	89                              // DW_AT_decl_line
	.long	83                              // DW_AT_type
	.byte	19                              // Abbrev [19] 0x2cf:0x1e DW_TAG_inlined_subroutine
	.long	394                             // DW_AT_abstract_origin
	.long	.Ltmp58                         // DW_AT_low_pc
	.long	.Ltmp59-.Ltmp58                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	95                              // DW_AT_call_line
	.byte	17                              // DW_AT_call_column
	.byte	20                              // Abbrev [20] 0x2df:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	96
	.long	402                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x2e6:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	424                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	19                              // Abbrev [19] 0x2ed:0x1e DW_TAG_inlined_subroutine
	.long	394                             // DW_AT_abstract_origin
	.long	.Ltmp59                         // DW_AT_low_pc
	.long	.Ltmp60-.Ltmp59                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	96                              // DW_AT_call_line
	.byte	17                              // DW_AT_call_column
	.byte	20                              // Abbrev [20] 0x2fd:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	94
	.long	402                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x304:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	424                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	19                              // Abbrev [19] 0x30b:0x1e DW_TAG_inlined_subroutine
	.long	442                             // DW_AT_abstract_origin
	.long	.Ltmp62                         // DW_AT_low_pc
	.long	.Ltmp63-.Ltmp62                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	98                              // DW_AT_call_line
	.byte	17                              // DW_AT_call_column
	.byte	20                              // Abbrev [20] 0x31b:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	96
	.long	461                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x322:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	472                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	19                              // Abbrev [19] 0x329:0x1e DW_TAG_inlined_subroutine
	.long	394                             // DW_AT_abstract_origin
	.long	.Ltmp67                         // DW_AT_low_pc
	.long	.Ltmp68-.Ltmp67                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	106                             // DW_AT_call_line
	.byte	17                              // DW_AT_call_column
	.byte	20                              // Abbrev [20] 0x339:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	402                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x340:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	424                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	19                              // Abbrev [19] 0x347:0x1e DW_TAG_inlined_subroutine
	.long	442                             // DW_AT_abstract_origin
	.long	.Ltmp68                         // DW_AT_low_pc
	.long	.Ltmp69-.Ltmp68                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	107                             // DW_AT_call_line
	.byte	17                              // DW_AT_call_column
	.byte	20                              // Abbrev [20] 0x357:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	94
	.long	461                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x35e:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	472                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x365:0x7c DW_TAG_lexical_block
	.long	.Ltmp74                         // DW_AT_low_pc
	.long	.Ltmp83-.Ltmp74                 // DW_AT_high_pc
	.byte	11                              // Abbrev [11] 0x36e:0xf DW_TAG_variable
	.long	.Ldebug_loc23                   // DW_AT_location
	.long	.Linfo_string44                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	114                             // DW_AT_decl_line
	.long	83                              // DW_AT_type
	.byte	19                              // Abbrev [19] 0x37d:0x1e DW_TAG_inlined_subroutine
	.long	394                             // DW_AT_abstract_origin
	.long	.Ltmp76                         // DW_AT_low_pc
	.long	.Ltmp77-.Ltmp76                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	116                             // DW_AT_call_line
	.byte	17                              // DW_AT_call_column
	.byte	20                              // Abbrev [20] 0x38d:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	94
	.long	402                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x394:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	424                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	19                              // Abbrev [19] 0x39b:0x1e DW_TAG_inlined_subroutine
	.long	394                             // DW_AT_abstract_origin
	.long	.Ltmp77                         // DW_AT_low_pc
	.long	.Ltmp78-.Ltmp77                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	117                             // DW_AT_call_line
	.byte	17                              // DW_AT_call_column
	.byte	20                              // Abbrev [20] 0x3ab:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	402                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x3b2:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	424                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	19                              // Abbrev [19] 0x3b9:0x27 DW_TAG_inlined_subroutine
	.long	442                             // DW_AT_abstract_origin
	.long	.Ltmp81                         // DW_AT_low_pc
	.long	.Ltmp83-.Ltmp81                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	119                             // DW_AT_call_line
	.byte	17                              // DW_AT_call_column
	.byte	22                              // Abbrev [22] 0x3c9:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc24                   // DW_AT_location
	.long	450                             // DW_AT_abstract_origin
	.byte	20                              // Abbrev [20] 0x3d2:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	94
	.long	461                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x3d9:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	472                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x3e2:0x21f DW_TAG_lexical_block
	.long	.Ltmp85                         // DW_AT_low_pc
	.long	.Ltmp141-.Ltmp85                // DW_AT_high_pc
	.byte	12                              // Abbrev [12] 0x3eb:0xb DW_TAG_variable
	.long	.Linfo_string45                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	122                             // DW_AT_decl_line
	.long	1616                            // DW_AT_type
	.byte	19                              // Abbrev [19] 0x3f6:0x1e DW_TAG_inlined_subroutine
	.long	394                             // DW_AT_abstract_origin
	.long	.Ltmp89                         // DW_AT_low_pc
	.long	.Ltmp90-.Ltmp89                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	132                             // DW_AT_call_line
	.byte	13                              // DW_AT_call_column
	.byte	20                              // Abbrev [20] 0x406:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	94
	.long	402                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x40d:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	424                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	17                              // Abbrev [17] 0x414:0x92 DW_TAG_lexical_block
	.long	.Ldebug_ranges0                 // DW_AT_ranges
	.byte	11                              // Abbrev [11] 0x419:0xf DW_TAG_variable
	.long	.Ldebug_loc25                   // DW_AT_location
	.long	.Linfo_string43                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	136                             // DW_AT_decl_line
	.long	1616                            // DW_AT_type
	.byte	19                              // Abbrev [19] 0x428:0x28 DW_TAG_inlined_subroutine
	.long	394                             // DW_AT_abstract_origin
	.long	.Ltmp95                         // DW_AT_low_pc
	.long	.Ltmp97-.Ltmp95                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	137                             // DW_AT_call_line
	.byte	17                              // DW_AT_call_column
	.byte	20                              // Abbrev [20] 0x438:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	96
	.long	402                             // DW_AT_abstract_origin
	.byte	20                              // Abbrev [20] 0x43f:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	413                             // DW_AT_abstract_origin
	.byte	22                              // Abbrev [22] 0x446:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc26                   // DW_AT_location
	.long	424                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x450:0x37 DW_TAG_lexical_block
	.long	.Ltmp108                        // DW_AT_low_pc
	.long	.Ltmp114-.Ltmp108               // DW_AT_high_pc
	.byte	11                              // Abbrev [11] 0x459:0xf DW_TAG_variable
	.long	.Ldebug_loc28                   // DW_AT_location
	.long	.Linfo_string46                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	149                             // DW_AT_decl_line
	.long	1616                            // DW_AT_type
	.byte	19                              // Abbrev [19] 0x468:0x1e DW_TAG_inlined_subroutine
	.long	394                             // DW_AT_abstract_origin
	.long	.Ltmp109                        // DW_AT_low_pc
	.long	.Ltmp110-.Ltmp109               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	146                             // DW_AT_call_line
	.byte	21                              // DW_AT_call_column
	.byte	20                              // Abbrev [20] 0x478:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	94
	.long	402                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x47f:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	424                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	19                              // Abbrev [19] 0x487:0x1e DW_TAG_inlined_subroutine
	.long	442                             // DW_AT_abstract_origin
	.long	.Ltmp115                        // DW_AT_low_pc
	.long	.Ltmp116-.Ltmp115               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	155                             // DW_AT_call_line
	.byte	17                              // DW_AT_call_column
	.byte	20                              // Abbrev [20] 0x497:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	96
	.long	461                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x49e:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	472                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	19                              // Abbrev [19] 0x4a6:0x1e DW_TAG_inlined_subroutine
	.long	394                             // DW_AT_abstract_origin
	.long	.Ltmp102                        // DW_AT_low_pc
	.long	.Ltmp103-.Ltmp102               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	125                             // DW_AT_call_line
	.byte	17                              // DW_AT_call_column
	.byte	20                              // Abbrev [20] 0x4b6:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	101
	.long	402                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x4bd:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	424                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	19                              // Abbrev [19] 0x4c4:0x1e DW_TAG_inlined_subroutine
	.long	394                             // DW_AT_abstract_origin
	.long	.Ltmp103                        // DW_AT_low_pc
	.long	.Ltmp104-.Ltmp103               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	126                             // DW_AT_call_line
	.byte	17                              // DW_AT_call_column
	.byte	20                              // Abbrev [20] 0x4d4:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	402                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x4db:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	424                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	19                              // Abbrev [19] 0x4e2:0x27 DW_TAG_inlined_subroutine
	.long	442                             // DW_AT_abstract_origin
	.long	.Ltmp106                        // DW_AT_low_pc
	.long	.Ltmp108-.Ltmp106               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	128                             // DW_AT_call_line
	.byte	17                              // DW_AT_call_column
	.byte	22                              // Abbrev [22] 0x4f2:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc27                   // DW_AT_location
	.long	450                             // DW_AT_abstract_origin
	.byte	20                              // Abbrev [20] 0x4fb:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	101
	.long	461                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x502:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	472                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x509:0x62 DW_TAG_lexical_block
	.long	.Ltmp122                        // DW_AT_low_pc
	.long	.Ltmp129-.Ltmp122               // DW_AT_high_pc
	.byte	18                              // Abbrev [18] 0x512:0xd DW_TAG_variable
	.byte	1                               // DW_AT_location
	.byte	98
	.long	.Linfo_string43                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	161                             // DW_AT_decl_line
	.long	1616                            // DW_AT_type
	.byte	11                              // Abbrev [11] 0x51f:0xf DW_TAG_variable
	.long	.Ldebug_loc29                   // DW_AT_location
	.long	.Linfo_string46                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	166                             // DW_AT_decl_line
	.long	1616                            // DW_AT_type
	.byte	19                              // Abbrev [19] 0x52e:0x1e DW_TAG_inlined_subroutine
	.long	394                             // DW_AT_abstract_origin
	.long	.Ltmp123                        // DW_AT_low_pc
	.long	.Ltmp124-.Ltmp123               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	163                             // DW_AT_call_line
	.byte	17                              // DW_AT_call_column
	.byte	20                              // Abbrev [20] 0x53e:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	94
	.long	402                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x545:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	424                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	19                              // Abbrev [19] 0x54c:0x1e DW_TAG_inlined_subroutine
	.long	442                             // DW_AT_abstract_origin
	.long	.Ltmp126                        // DW_AT_low_pc
	.long	.Ltmp127-.Ltmp126               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	168                             // DW_AT_call_line
	.byte	17                              // DW_AT_call_column
	.byte	20                              // Abbrev [20] 0x55c:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	96
	.long	461                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x563:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	472                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x56b:0x95 DW_TAG_lexical_block
	.long	.Ltmp133                        // DW_AT_low_pc
	.long	.Ltmp141-.Ltmp133               // DW_AT_high_pc
	.byte	11                              // Abbrev [11] 0x574:0xf DW_TAG_variable
	.long	.Ldebug_loc30                   // DW_AT_location
	.long	.Linfo_string43                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	176                             // DW_AT_decl_line
	.long	1616                            // DW_AT_type
	.byte	19                              // Abbrev [19] 0x583:0x1e DW_TAG_inlined_subroutine
	.long	394                             // DW_AT_abstract_origin
	.long	.Ltmp133                        // DW_AT_low_pc
	.long	.Ltmp134-.Ltmp133               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	174                             // DW_AT_call_line
	.byte	17                              // DW_AT_call_column
	.byte	20                              // Abbrev [20] 0x593:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	96
	.long	402                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x59a:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	424                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x5a1:0x37 DW_TAG_lexical_block
	.long	.Ltmp136                        // DW_AT_low_pc
	.long	.Ltmp139-.Ltmp136               // DW_AT_high_pc
	.byte	11                              // Abbrev [11] 0x5aa:0xf DW_TAG_variable
	.long	.Ldebug_loc31                   // DW_AT_location
	.long	.Linfo_string46                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	180                             // DW_AT_decl_line
	.long	1616                            // DW_AT_type
	.byte	19                              // Abbrev [19] 0x5b9:0x1e DW_TAG_inlined_subroutine
	.long	394                             // DW_AT_abstract_origin
	.long	.Ltmp137                        // DW_AT_low_pc
	.long	.Ltmp138-.Ltmp137               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	181                             // DW_AT_call_line
	.byte	21                              // DW_AT_call_column
	.byte	20                              // Abbrev [20] 0x5c9:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	94
	.long	402                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x5d0:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	424                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	19                              // Abbrev [19] 0x5d8:0x27 DW_TAG_inlined_subroutine
	.long	442                             // DW_AT_abstract_origin
	.long	.Ltmp139                        // DW_AT_low_pc
	.long	.Ltmp141-.Ltmp139               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	185                             // DW_AT_call_line
	.byte	17                              // DW_AT_call_column
	.byte	22                              // Abbrev [22] 0x5e8:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc32                   // DW_AT_location
	.long	450                             // DW_AT_abstract_origin
	.byte	20                              // Abbrev [20] 0x5f1:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	96
	.long	461                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x5f8:0x6 DW_TAG_formal_parameter
	.byte	8                               // DW_AT_const_value
	.long	472                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	13                              // Abbrev [13] 0x602:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp62                         // DW_AT_low_pc
	.byte	13                              // Abbrev [13] 0x609:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp81                         // DW_AT_low_pc
	.byte	13                              // Abbrev [13] 0x610:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp84                         // DW_AT_low_pc
	.byte	13                              // Abbrev [13] 0x617:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp100                        // DW_AT_low_pc
	.byte	13                              // Abbrev [13] 0x61e:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp106                        // DW_AT_low_pc
	.byte	13                              // Abbrev [13] 0x625:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp109                        // DW_AT_low_pc
	.byte	13                              // Abbrev [13] 0x62c:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp113                        // DW_AT_low_pc
	.byte	13                              // Abbrev [13] 0x633:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp123                        // DW_AT_low_pc
	.byte	13                              // Abbrev [13] 0x63a:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp126                        // DW_AT_low_pc
	.byte	13                              // Abbrev [13] 0x641:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp135                        // DW_AT_low_pc
	.byte	13                              // Abbrev [13] 0x648:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp139                        // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	2                               // Abbrev [2] 0x650:0xb DW_TAG_typedef
	.long	49                              // DW_AT_type
	.long	.Linfo_string17                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	26                              // DW_AT_decl_line
	.byte	5                               // Abbrev [5] 0x65b:0x5 DW_TAG_const_type
	.long	78                              // DW_AT_type
	.byte	5                               // Abbrev [5] 0x660:0x5 DW_TAG_const_type
	.long	56                              // DW_AT_type
	.byte	2                               // Abbrev [2] 0x665:0xb DW_TAG_typedef
	.long	1648                            // DW_AT_type
	.long	.Linfo_string25                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	29                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x670:0x7 DW_TAG_base_type
	.long	.Linfo_string24                 // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x677:0x5 DW_TAG_pointer_type
	.long	1660                            // DW_AT_type
	.byte	5                               // Abbrev [5] 0x67c:0x5 DW_TAG_const_type
	.long	83                              // DW_AT_type
	.byte	23                              // Abbrev [23] 0x681:0xc DW_TAG_array_type
	.long	1677                            // DW_AT_type
	.byte	24                              // Abbrev [24] 0x686:0x6 DW_TAG_subrange_type
	.long	1695                            // DW_AT_type
	.byte	1                               // DW_AT_count
	.byte	0                               // End Of Children Mark
	.byte	2                               // Abbrev [2] 0x68d:0xb DW_TAG_typedef
	.long	1688                            // DW_AT_type
	.long	.Linfo_string33                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	53                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x698:0x7 DW_TAG_base_type
	.long	.Linfo_string32                 // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	25                              // Abbrev [25] 0x69f:0x7 DW_TAG_base_type
	.long	.Linfo_string34                 // DW_AT_name
	.byte	8                               // DW_AT_byte_size
	.byte	7                               // DW_AT_encoding
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_ranges,"",@progbits
.Ldebug_ranges0:
	.long	.Ltmp92
	.long	.Ltmp101
	.long	.Ltmp108
	.long	.Ltmp118
	.long	0
	.long	0
.Ldebug_ranges1:
	.long	.Ltmp46
	.long	.Ltmp83
	.long	.Ltmp85
	.long	.Ltmp141
	.long	0
	.long	0
.Ldebug_ranges2:
	.long	.Lfunc_begin0
	.long	.Lfunc_end0
	.long	.Lfunc_begin1
	.long	.Lfunc_end1
	.long	0
	.long	0
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/stdlib/memmove.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=153
.Linfo_string3:
	.asciz	"unsigned int"                  // string offset=174
.Linfo_string4:
	.asciz	"uintptr_t"                     // string offset=187
.Linfo_string5:
	.asciz	"char"                          // string offset=197
.Linfo_string6:
	.asciz	"uint32_t"                      // string offset=202
.Linfo_string7:
	.asciz	"mram_read"                     // string offset=211
.Linfo_string8:
	.asciz	"from"                          // string offset=221
.Linfo_string9:
	.asciz	"to"                            // string offset=226
.Linfo_string10:
	.asciz	"nb_of_bytes"                   // string offset=229
.Linfo_string11:
	.asciz	"mram_write"                    // string offset=241
.Linfo_string12:
	.asciz	"memmove"                       // string offset=252
.Linfo_string13:
	.asciz	"__memmove_mm"                  // string offset=260
.Linfo_string14:
	.asciz	"dest"                          // string offset=273
.Linfo_string15:
	.asciz	"src"                           // string offset=278
.Linfo_string16:
	.asciz	"len"                           // string offset=282
.Linfo_string17:
	.asciz	"size_t"                        // string offset=286
.Linfo_string18:
	.asciz	"body"                          // string offset=293
.Linfo_string19:
	.asciz	"tail"                          // string offset=298
.Linfo_string20:
	.asciz	"s"                             // string offset=303
.Linfo_string21:
	.asciz	"d"                             // string offset=305
.Linfo_string22:
	.asciz	"head"                          // string offset=307
.Linfo_string23:
	.asciz	"i"                             // string offset=312
.Linfo_string24:
	.asciz	"int"                           // string offset=314
.Linfo_string25:
	.asciz	"int32_t"                       // string offset=318
.Linfo_string26:
	.asciz	"head_len"                      // string offset=326
.Linfo_string27:
	.asciz	"dw"                            // string offset=335
.Linfo_string28:
	.asciz	"sw"                            // string offset=338
.Linfo_string29:
	.asciz	"body_len"                      // string offset=341
.Linfo_string30:
	.asciz	"tail_len"                      // string offset=350
.Linfo_string31:
	.asciz	"srcCache64"                    // string offset=359
.Linfo_string32:
	.asciz	"long unsigned int"             // string offset=370
.Linfo_string33:
	.asciz	"uint64_t"                      // string offset=388
.Linfo_string34:
	.asciz	"__ARRAY_SIZE_TYPE__"           // string offset=397
.Linfo_string35:
	.asciz	"destCache64"                   // string offset=417
.Linfo_string36:
	.asciz	"srcCache"                      // string offset=429
.Linfo_string37:
	.asciz	"destCache"                     // string offset=438
.Linfo_string38:
	.asciz	"srcIdx"                        // string offset=448
.Linfo_string39:
	.asciz	"remaining"                     // string offset=455
.Linfo_string40:
	.asciz	"dstIdx"                        // string offset=465
.Linfo_string41:
	.asciz	"srcOff"                        // string offset=472
.Linfo_string42:
	.asciz	"dstOff"                        // string offset=479
.Linfo_string43:
	.asciz	"part"                          // string offset=486
.Linfo_string44:
	.asciz	"off"                           // string offset=491
.Linfo_string45:
	.asciz	"initLen"                       // string offset=495
.Linfo_string46:
	.asciz	"part2"                         // string offset=503
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
