	.text
	.file	"strchr.c"
	.section	.text.strchr,"ax",@progbits
	.globl	strchr                          // -- Begin function strchr
	.type	strchr,@function
strchr:                                 // @strchr
.Lfunc_begin0:
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/strchr.c"
	.loc	1 10 0                          // uPIMulator_frontend/sdk/stdlib/strchr.c:10:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: strchr:string <- $r0
	//DEBUG_VALUE: strchr:string <- $r0
	//DEBUG_VALUE: strchr:character <- $r1
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: strchr:str <- $r0
	//DEBUG_VALUE: strchr:str <- $r0
	//DEBUG_VALUE: strchr:c <- undef
	.loc	1 0 0 prologue_end              // uPIMulator_frontend/sdk/stdlib/strchr.c:0:0
	lbu r3, r0, 0
.Ltmp0:
	//DEBUG_VALUE: strchr:c <- $r3
	//DEBUG_VALUE: strchr:character <- $r1
	.loc	1 15 13                         // uPIMulator_frontend/sdk/stdlib/strchr.c:15:13
	jneq r3, r1, .LBB0_2
.Ltmp1:
// %bb.1:
	//DEBUG_VALUE: strchr:c <- $r3
	//DEBUG_VALUE: strchr:character <- $r1
	//DEBUG_VALUE: strchr:str <- $r0
	//DEBUG_VALUE: strchr:string <- $r0
	.loc	1 25 1                          // uPIMulator_frontend/sdk/stdlib/strchr.c:25:1
	jump r23
.Ltmp2:
.LBB0_2:                                // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: strchr:character <- $r1
	//DEBUG_VALUE: strchr:str <- $r0
	.loc	1 18 15                         // uPIMulator_frontend/sdk/stdlib/strchr.c:18:15
	and r2, r3, 255
.Ltmp3:
	.loc	1 18 13 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/strchr.c:18:13
	jeq r2, 0, .LBB0_3
.Ltmp4:
// %bb.4:                               //   in Loop: Header=BB0_2 Depth=1
	//DEBUG_VALUE: strchr:character <- $r1
	//DEBUG_VALUE: strchr:str <- $r0
	.loc	1 0 0                           // uPIMulator_frontend/sdk/stdlib/strchr.c:0:0
	lbu r3, r0, 1
.Ltmp5:
	//DEBUG_VALUE: strchr:c <- $r3
	.loc	1 22 12 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/strchr.c:22:12
	add r2, r0, 1
.Ltmp6:
	//DEBUG_VALUE: strchr:c <- undef
	//DEBUG_VALUE: strchr:str <- $r2
	.loc	1 0 12 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/strchr.c:0:12
	move r0, r2
	.loc	1 15 13 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/strchr.c:15:13
	jneq r3, r1, .LBB0_2
.Ltmp7:
// %bb.5:
	//DEBUG_VALUE: strchr:str <- $r2
	//DEBUG_VALUE: strchr:character <- $r1
	.loc	1 25 1                          // uPIMulator_frontend/sdk/stdlib/strchr.c:25:1
	move r0, r2
	jump r23
.Ltmp8:
.LBB0_3:
	//DEBUG_VALUE: strchr:character <- $r1
	//DEBUG_VALUE: strchr:str <- $r0
	.loc	1 0 1 is_stmt 0                 // uPIMulator_frontend/sdk/stdlib/strchr.c:0:1
	move r2, 0
	.loc	1 25 1                          // uPIMulator_frontend/sdk/stdlib/strchr.c:25:1
	move r0, r2
.Ltmp9:
	jump r23
.Ltmp10:
.Lfunc_end0:
	.size	strchr, .Lfunc_end0-strchr
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.strchr
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.strchr,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp2-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp6-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp6-.Lfunc_begin0
	.long	.Ltmp8-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp8-.Lfunc_begin0
	.long	.Ltmp9-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp2-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp5-.Lfunc_begin0
	.long	.Ltmp6-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x90 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x5 DW_TAG_pointer_type
	.long	43                              // DW_AT_type
	.byte	3                               // Abbrev [3] 0x2b:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	6                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x32:0x50 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	38                              // DW_AT_type
                                        // DW_AT_external
	.byte	5                               // Abbrev [5] 0x47:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string5                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
	.long	130                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x56:0xd DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	.Linfo_string6                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
	.long	140                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0x63:0xf DW_TAG_variable
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string8                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	11                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	7                               // Abbrev [7] 0x72:0xf DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string9                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	12                              // DW_AT_decl_line
	.long	147                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	2                               // Abbrev [2] 0x82:0x5 DW_TAG_pointer_type
	.long	135                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x87:0x5 DW_TAG_const_type
	.long	43                              // DW_AT_type
	.byte	3                               // Abbrev [3] 0x8c:0x7 DW_TAG_base_type
	.long	.Linfo_string7                  // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	3                               // Abbrev [3] 0x93:0x7 DW_TAG_base_type
	.long	.Linfo_string10                 // DW_AT_name
	.byte	8                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/stdlib/strchr.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=152
.Linfo_string3:
	.asciz	"char"                          // string offset=173
.Linfo_string4:
	.asciz	"strchr"                        // string offset=178
.Linfo_string5:
	.asciz	"string"                        // string offset=185
.Linfo_string6:
	.asciz	"character"                     // string offset=192
.Linfo_string7:
	.asciz	"int"                           // string offset=202
.Linfo_string8:
	.asciz	"str"                           // string offset=206
.Linfo_string9:
	.asciz	"c"                             // string offset=210
.Linfo_string10:
	.asciz	"unsigned char"                 // string offset=212
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
