	.text
	.file	"strcat.c"
	.section	.text.strcat,"ax",@progbits
	.globl	strcat                          // -- Begin function strcat
	.type	strcat,@function
strcat:                                 // @strcat
.Lfunc_begin0:
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/strcat.c"
	.loc	1 10 0                          // uPIMulator_frontend/sdk/stdlib/strcat.c:10:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: strcat:destination <- $r0
	//DEBUG_VALUE: strcat:source <- $r1
	.cfi_def_cfa_offset -16
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 8, d22
	add r22, r22, 16
	.cfi_offset 15, -16
	.cfi_offset 14, -12
	sd r22, -16, d14
	move r15, r1
	move r14, r0
.Ltmp0:
	//DEBUG_VALUE: strcat:source <- $r15
	//DEBUG_VALUE: strcat:destination <- $r14
	.loc	1 11 21 prologue_end            // uPIMulator_frontend/sdk/stdlib/strcat.c:11:21
	call r23, strlen
.Ltmp1:
	.loc	1 14 17                         // uPIMulator_frontend/sdk/stdlib/strcat.c:14:17
	lbu r2, r15, 0
.Ltmp2:
	//DEBUG_VALUE: strcat:i <- 0
	//DEBUG_VALUE: strcat:length <- $r0
	.loc	1 14 5 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/strcat.c:14:5
	jeq r2, 0, .LBB0_1
.Ltmp3:
// %bb.2:
	//DEBUG_VALUE: strcat:source <- $r15
	//DEBUG_VALUE: strcat:destination <- $r14
	//DEBUG_VALUE: strcat:length <- $r0
	//DEBUG_VALUE: strcat:i <- 0
	add r1, r14, r0
	move r3, 0
.Ltmp4:
.LBB0_3:                                // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: strcat:source <- $r15
	//DEBUG_VALUE: strcat:destination <- $r14
	//DEBUG_VALUE: strcat:length <- $r0
	//DEBUG_VALUE: strcat:i <- $r3
	.loc	1 15 33 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/strcat.c:15:33
	add r4, r1, r3
	sb r4, 0, r2
.Ltmp5:
	.loc	1 14 17                         // uPIMulator_frontend/sdk/stdlib/strcat.c:14:17
	add r2, r15, r3
	lbu r2, r2, 1
	.loc	1 14 37 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/strcat.c:14:37
	add r4, r3, 1
.Ltmp6:
	//DEBUG_VALUE: strcat:i <- $r4
	.loc	1 0 37                          // uPIMulator_frontend/sdk/stdlib/strcat.c:0:37
	move r3, r4
.Ltmp7:
	.loc	1 14 5                          // uPIMulator_frontend/sdk/stdlib/strcat.c:14:5
	jneq r2, 0, .LBB0_3
	jump .LBB0_4
.Ltmp8:
.LBB0_1:
	//DEBUG_VALUE: strcat:source <- $r15
	//DEBUG_VALUE: strcat:destination <- $r14
	//DEBUG_VALUE: strcat:length <- $r0
	//DEBUG_VALUE: strcat:i <- 0
	.loc	1 0 5                           // uPIMulator_frontend/sdk/stdlib/strcat.c:0:5
	move r4, 0
.Ltmp9:
.LBB0_4:
	//DEBUG_VALUE: strcat:source <- $r15
	//DEBUG_VALUE: strcat:destination <- $r14
	//DEBUG_VALUE: strcat:length <- $r0
	.loc	1 18 24 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/strcat.c:18:24
	add r0, r4, r0
.Ltmp10:
	.loc	1 18 5 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/strcat.c:18:5
	add r0, r14, r0
	.loc	1 18 29                         // uPIMulator_frontend/sdk/stdlib/strcat.c:18:29
	sb r0, 0, 0
	.loc	1 20 5 is_stmt 1                // uPIMulator_frontend/sdk/stdlib/strcat.c:20:5
	move r0, r14
	ld d14, r22, -16
.Ltmp11:
	ld d22, r22, -8
	jump r23
.Ltmp12:
.Lfunc_end0:
	.size	strcat, .Lfunc_end0-strcat
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.strcat
	.long	.Lfunc_begin0
	.byte	16
	.section	.text.strcat,"ax",@progbits
                                        // -- End function
	.file	2 "/root" "uPIMulator_frontend/sdk/stdlib/stddef.h"
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp11-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp11-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp4-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp4-.Lfunc_begin0
	.long	.Ltmp6-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp6-.Lfunc_begin0
	.long	.Ltmp8-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp8-.Lfunc_begin0
	.long	.Ltmp9-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp10-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.ascii	"\211\202\001"                  // DW_TAG_GNU_call_site
	.byte	0                               // DW_CHILDREN_no
	.ascii	"\223B"                         // DW_AT_GNU_call_site_target
	.byte	24                              // DW_FORM_exprloc
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x9d DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x59 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string3                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	127                             // DW_AT_type
                                        // DW_AT_external
	.byte	3                               // Abbrev [3] 0x3b:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string5                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
	.long	127                             // DW_AT_type
	.byte	3                               // Abbrev [3] 0x4a:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string6                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
	.long	139                             // DW_AT_type
	.byte	4                               // Abbrev [4] 0x59:0xf DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string7                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	12                              // DW_AT_decl_line
	.long	149                             // DW_AT_type
	.byte	4                               // Abbrev [4] 0x68:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string9                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	11                              // DW_AT_decl_line
	.long	156                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0x77:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp1                          // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	6                               // Abbrev [6] 0x7f:0x5 DW_TAG_pointer_type
	.long	132                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0x84:0x7 DW_TAG_base_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	6                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	6                               // Abbrev [6] 0x8b:0x5 DW_TAG_pointer_type
	.long	144                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x90:0x5 DW_TAG_const_type
	.long	132                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0x95:0x7 DW_TAG_base_type
	.long	.Linfo_string8                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	9                               // Abbrev [9] 0x9c:0xb DW_TAG_typedef
	.long	149                             // DW_AT_type
	.long	.Linfo_string10                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	26                              // DW_AT_decl_line
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/stdlib/strcat.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=152
.Linfo_string3:
	.asciz	"strcat"                        // string offset=173
.Linfo_string4:
	.asciz	"char"                          // string offset=180
.Linfo_string5:
	.asciz	"destination"                   // string offset=185
.Linfo_string6:
	.asciz	"source"                        // string offset=197
.Linfo_string7:
	.asciz	"i"                             // string offset=204
.Linfo_string8:
	.asciz	"unsigned int"                  // string offset=206
.Linfo_string9:
	.asciz	"length"                        // string offset=219
.Linfo_string10:
	.asciz	"size_t"                        // string offset=226
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
