	.text
	.file	"strcpy.c"
	.section	.text.strcpy,"ax",@progbits
	.globl	strcpy                          // -- Begin function strcpy
	.type	strcpy,@function
strcpy:                                 // @strcpy
.Lfunc_begin0:
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/strcpy.c"
	.loc	1 10 0                          // uPIMulator_frontend/sdk/stdlib/strcpy.c:10:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: strcpy:destination <- $r0
	//DEBUG_VALUE: strcpy:source <- $r1
	//DEBUG_VALUE: strcpy:source <- $r1
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: strcpy:ptr <- $r0
	.loc	1 0 0 prologue_end              // uPIMulator_frontend/sdk/stdlib/strcpy.c:0:0
	lbu r2, r1, 0
.Ltmp0:
	//DEBUG_VALUE: strcpy:c <- undef
	//DEBUG_VALUE: strcpy:c <- $r2
	//DEBUG_VALUE: strcpy:ptr <- $r0
	//DEBUG_VALUE: strcpy:destination <- $r0
	move r3, r0
	.loc	1 14 5                          // uPIMulator_frontend/sdk/stdlib/strcpy.c:14:5
	jeq r2, 0, .LBB0_3
.Ltmp1:
// %bb.1:
	//DEBUG_VALUE: strcpy:c <- $r2
	//DEBUG_VALUE: strcpy:source <- $r1
	//DEBUG_VALUE: strcpy:ptr <- $r0
	//DEBUG_VALUE: strcpy:destination <- $r0
	add r1, r1, 1
.Ltmp2:
	.loc	1 0 5 is_stmt 0                 // uPIMulator_frontend/sdk/stdlib/strcpy.c:0:5
	move r3, r0
.Ltmp3:
.LBB0_2:                                // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: strcpy:destination <- $r0
	//DEBUG_VALUE: strcpy:source <- [DW_OP_constu 1, DW_OP_minus, DW_OP_stack_value] $r1
	//DEBUG_VALUE: strcpy:ptr <- $r3
	.loc	1 15 14 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/strcpy.c:15:14
	sb r3, 0, r2
.Ltmp4:
	.loc	1 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/stdlib/strcpy.c:0:0
	lbu r2, r1, 0
.Ltmp5:
	//DEBUG_VALUE: strcpy:c <- $r2
	.loc	1 16 12 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/strcpy.c:16:12
	add r3, r3, 1
.Ltmp6:
	//DEBUG_VALUE: strcpy:c <- undef
	//DEBUG_VALUE: strcpy:ptr <- $r3
	//DEBUG_VALUE: strcpy:source <- $r1
	.loc	1 14 5                          // uPIMulator_frontend/sdk/stdlib/strcpy.c:14:5
	add r1, r1, 1
.Ltmp7:
	jneq r2, 0, .LBB0_2
.Ltmp8:
.LBB0_3:
	//DEBUG_VALUE: strcpy:destination <- $r0
	.loc	1 21 10                         // uPIMulator_frontend/sdk/stdlib/strcpy.c:21:10
	sb r3, 0, 0
	.loc	1 23 5                          // uPIMulator_frontend/sdk/stdlib/strcpy.c:23:5
	jump r23
.Ltmp9:
.Lfunc_end0:
	.size	strcpy, .Lfunc_end0-strcpy
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.strcpy
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.strcpy,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp2-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp6-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	113                             // DW_OP_breg1
	.byte	127                             // -1
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp6-.Lfunc_begin0
	.long	.Ltmp7-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp3-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp8-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp3-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp5-.Lfunc_begin0
	.long	.Ltmp6-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x82 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x50 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string3                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	118                             // DW_AT_type
                                        // DW_AT_external
	.byte	3                               // Abbrev [3] 0x3b:0xd DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	.Linfo_string5                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
	.long	118                             // DW_AT_type
	.byte	4                               // Abbrev [4] 0x48:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string6                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
	.long	130                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0x57:0xf DW_TAG_variable
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string7                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	11                              // DW_AT_decl_line
	.long	118                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0x66:0xf DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string8                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	12                              // DW_AT_decl_line
	.long	123                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	6                               // Abbrev [6] 0x76:0x5 DW_TAG_pointer_type
	.long	123                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0x7b:0x7 DW_TAG_base_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	6                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	6                               // Abbrev [6] 0x82:0x5 DW_TAG_pointer_type
	.long	135                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x87:0x5 DW_TAG_const_type
	.long	123                             // DW_AT_type
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/stdlib/strcpy.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=152
.Linfo_string3:
	.asciz	"strcpy"                        // string offset=173
.Linfo_string4:
	.asciz	"char"                          // string offset=180
.Linfo_string5:
	.asciz	"destination"                   // string offset=185
.Linfo_string6:
	.asciz	"source"                        // string offset=197
.Linfo_string7:
	.asciz	"ptr"                           // string offset=204
.Linfo_string8:
	.asciz	"c"                             // string offset=208
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
