	.text
	.file	"strcspn.c"
	.section	.text.strcspn,"ax",@progbits
	.globl	strcspn                         // -- Begin function strcspn
	.type	strcspn,@function
strcspn:                                // @strcspn
.Lfunc_begin0:
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/strcspn.c"
	.loc	1 18 0                          // uPIMulator_frontend/sdk/stdlib/strcspn.c:18:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: strcspn:string <- $r0
	//DEBUG_VALUE: strcspn:string <- $r0
	//DEBUG_VALUE: strcspn:reject <- $r1
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: strcspn:prefix_length <- 0
	.loc	1 21 29 prologue_end            // uPIMulator_frontend/sdk/stdlib/strcspn.c:21:29
	lbu r3, r0, 0
.Ltmp0:
	//DEBUG_VALUE: strcspn:reject <- $r1
	.loc	1 21 5 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/strcspn.c:21:5
	jeq r3, 0, .LBB0_1
.Ltmp1:
// %bb.2:
	//DEBUG_VALUE: strcspn:reject <- $r1
	//DEBUG_VALUE: strcspn:string <- $r0
	//DEBUG_VALUE: strcspn:prefix_length <- 0
	.loc	1 0 5                           // uPIMulator_frontend/sdk/stdlib/strcspn.c:0:5
	lbu r2, r1, 0
	.loc	1 21 5                          // uPIMulator_frontend/sdk/stdlib/strcspn.c:21:5
	jeq r2, 0, .LBB0_5
.Ltmp2:
// %bb.3:
	//DEBUG_VALUE: strcspn:reject <- $r1
	//DEBUG_VALUE: strcspn:string <- $r0
	//DEBUG_VALUE: strcspn:prefix_length <- 0
	add r4, r1, 1
	move r1, 0
.Ltmp3:
.LBB0_4:                                // =>This Loop Header: Depth=1
                                        //     Child Loop BB0_8 Depth 2
	//DEBUG_VALUE: strcspn:string <- $r0
	//DEBUG_VALUE: strcspn:prefix_length <- $r1
	.loc	1 0 5                           // uPIMulator_frontend/sdk/stdlib/strcspn.c:0:5
	move r5, r4
	move r6, r2
	//DEBUG_VALUE: reject_index <- 0
.Ltmp4:
.LBB0_8:                                //   Parent Loop BB0_4 Depth=1
                                        // =>  This Inner Loop Header: Depth=2
	//DEBUG_VALUE: strcspn:prefix_length <- $r1
	//DEBUG_VALUE: strcspn:string <- $r0
	//DEBUG_VALUE: reject_index <- undef
	.loc	1 25 38 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/strcspn.c:25:38
	and r7, r3, 255
	and r6, r6, 255
.Ltmp5:
	//DEBUG_VALUE: reject_index <- [DW_OP_plus_uconst 1, DW_OP_stack_value] undef
	.loc	1 25 17 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/strcspn.c:25:17
	jeq r6, r7, .LBB0_10
.Ltmp6:
// %bb.7:                               //   in Loop: Header=BB0_8 Depth=2
	//DEBUG_VALUE: strcspn:prefix_length <- $r1
	//DEBUG_VALUE: strcspn:string <- $r0
	//DEBUG_VALUE: reject_index <- [DW_OP_plus_uconst 1, DW_OP_stack_value] undef
	.loc	1 24 45 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/strcspn.c:24:45
	lbu r6, r5, 0
.Ltmp7:
	.loc	1 24 9 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/strcspn.c:24:9
	add r5, r5, 1
	jneq r6, 0, .LBB0_8
.Ltmp8:
// %bb.9:                               //   in Loop: Header=BB0_4 Depth=1
	//DEBUG_VALUE: strcspn:prefix_length <- $r1
	//DEBUG_VALUE: strcspn:string <- $r0
	.loc	1 21 60 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/strcspn.c:21:60
	add r1, r1, 1
.Ltmp9:
	//DEBUG_VALUE: strcspn:prefix_length <- $r1
	.loc	1 21 29 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/strcspn.c:21:29
	add r3, r0, r1
	lbu r3, r3, 0
.Ltmp10:
	.loc	1 21 5                          // uPIMulator_frontend/sdk/stdlib/strcspn.c:21:5
	jneq r3, 0, .LBB0_4
	jump .LBB0_10
.Ltmp11:
.LBB0_1:
	//DEBUG_VALUE: strcspn:reject <- $r1
	//DEBUG_VALUE: strcspn:string <- $r0
	//DEBUG_VALUE: strcspn:prefix_length <- 0
	.loc	1 0 5                           // uPIMulator_frontend/sdk/stdlib/strcspn.c:0:5
	move r1, 0
.Ltmp12:
	.loc	1 32 1 is_stmt 1                // uPIMulator_frontend/sdk/stdlib/strcspn.c:32:1
	move r0, r1
.Ltmp13:
	jump r23
.Ltmp14:
.LBB0_5:
	//DEBUG_VALUE: strcspn:reject <- $r1
	//DEBUG_VALUE: strcspn:string <- $r0
	//DEBUG_VALUE: strcspn:prefix_length <- 0
	.loc	1 0 1 is_stmt 0                 // uPIMulator_frontend/sdk/stdlib/strcspn.c:0:1
	move r2, 0
.Ltmp15:
.LBB0_6:                                // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: strcspn:string <- $r0
	//DEBUG_VALUE: strcspn:prefix_length <- $r2
	.loc	1 21 29 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/strcspn.c:21:29
	add r1, r0, r2
	lbu r3, r1, 1
	.loc	1 21 60 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/strcspn.c:21:60
	add r1, r2, 1
.Ltmp16:
	//DEBUG_VALUE: strcspn:prefix_length <- $r1
	.loc	1 0 60                          // uPIMulator_frontend/sdk/stdlib/strcspn.c:0:60
	move r2, r1
.Ltmp17:
	.loc	1 21 5                          // uPIMulator_frontend/sdk/stdlib/strcspn.c:21:5
	jneq r3, 0, .LBB0_6
.Ltmp18:
.LBB0_10:
	//DEBUG_VALUE: strcspn:prefix_length <- $r1
	//DEBUG_VALUE: strcspn:string <- $r0
	.loc	1 32 1 is_stmt 1                // uPIMulator_frontend/sdk/stdlib/strcspn.c:32:1
	move r0, r1
.Ltmp19:
	jump r23
.Ltmp20:
.Lfunc_end0:
	.size	strcspn, .Lfunc_end0-strcspn
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.strcspn
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.strcspn,"ax",@progbits
                                        // -- End function
	.file	2 "/root" "uPIMulator_frontend/sdk/stdlib/stddef.h"
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp13-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Ltmp19-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp3-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp11-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Ltmp15-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp3-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp11-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp11-.Lfunc_begin0
	.long	.Ltmp15-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp15-.Lfunc_begin0
	.long	.Ltmp16-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp16-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0xac DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x6d DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string3                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	17                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	147                             // DW_AT_type
                                        // DW_AT_external
	.byte	3                               // Abbrev [3] 0x3b:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string5                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	17                              // DW_AT_decl_line
	.long	154                             // DW_AT_type
	.byte	3                               // Abbrev [3] 0x4a:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string7                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	17                              // DW_AT_decl_line
	.long	154                             // DW_AT_type
	.byte	4                               // Abbrev [4] 0x59:0xf DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string8                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	19                              // DW_AT_decl_line
	.long	171                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0x68:0x2a DW_TAG_lexical_block
	.long	.Ltmp4                          // DW_AT_low_pc
	.long	.Ltmp8-.Ltmp4                   // DW_AT_high_pc
	.byte	6                               // Abbrev [6] 0x71:0xb DW_TAG_variable
	.long	.Linfo_string11                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
	.long	164                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0x7c:0x15 DW_TAG_lexical_block
	.long	.Ltmp4                          // DW_AT_low_pc
	.long	.Ltmp8-.Ltmp4                   // DW_AT_high_pc
	.byte	6                               // Abbrev [6] 0x85:0xb DW_TAG_variable
	.long	.Linfo_string10                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	24                              // DW_AT_decl_line
	.long	147                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x93:0x7 DW_TAG_base_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	8                               // Abbrev [8] 0x9a:0x5 DW_TAG_pointer_type
	.long	159                             // DW_AT_type
	.byte	9                               // Abbrev [9] 0x9f:0x5 DW_TAG_const_type
	.long	164                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0xa4:0x7 DW_TAG_base_type
	.long	.Linfo_string6                  // DW_AT_name
	.byte	6                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	10                              // Abbrev [10] 0xab:0xb DW_TAG_typedef
	.long	147                             // DW_AT_type
	.long	.Linfo_string9                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	26                              // DW_AT_decl_line
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/stdlib/strcspn.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=153
.Linfo_string3:
	.asciz	"strcspn"                       // string offset=174
.Linfo_string4:
	.asciz	"unsigned int"                  // string offset=182
.Linfo_string5:
	.asciz	"string"                        // string offset=195
.Linfo_string6:
	.asciz	"char"                          // string offset=202
.Linfo_string7:
	.asciz	"reject"                        // string offset=207
.Linfo_string8:
	.asciz	"prefix_length"                 // string offset=214
.Linfo_string9:
	.asciz	"size_t"                        // string offset=228
.Linfo_string10:
	.asciz	"reject_index"                  // string offset=235
.Linfo_string11:
	.asciz	"c"                             // string offset=248
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
