	.text
	.file	"strncmp.c"
	.section	.text.strncmp,"ax",@progbits
	.globl	strncmp                         // -- Begin function strncmp
	.type	strncmp,@function
strncmp:                                // @strncmp
.Lfunc_begin0:
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/strncmp.c"
	.loc	1 10 0                          // uPIMulator_frontend/sdk/stdlib/strncmp.c:10:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: strncmp:string1 <- $r0
	//DEBUG_VALUE: strncmp:string2 <- $r1
	//DEBUG_VALUE: strncmp:size <- $r2
	.cfi_def_cfa_offset 0
	move r4, 0
.Ltmp0:
	//DEBUG_VALUE: len <- 0
	//DEBUG_VALUE: strncmp:size <- $r2
	//DEBUG_VALUE: strncmp:string2 <- $r1
	//DEBUG_VALUE: strncmp:string1 <- $r0
	.loc	1 11 5 prologue_end             // uPIMulator_frontend/sdk/stdlib/strncmp.c:11:5
	jeq r2, 0, .LBB0_5
.Ltmp1:
.LBB0_1:                                // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: len <- undef
	.loc	1 12 28                         // uPIMulator_frontend/sdk/stdlib/strncmp.c:12:28
	lbu r5, r0, 0
.Ltmp2:
	//DEBUG_VALUE: c1 <- undef
	.loc	1 13 28                         // uPIMulator_frontend/sdk/stdlib/strncmp.c:13:28
	lbu r3, r1, 0
.Ltmp3:
	//DEBUG_VALUE: c2 <- undef
	//DEBUG_VALUE: len <- [DW_OP_plus_uconst 1, DW_OP_stack_value] undef
	.loc	1 15 18                         // uPIMulator_frontend/sdk/stdlib/strncmp.c:15:18
	sub r3, r5, r3, sz, .LBB0_6
.Ltmp4:
// %bb.2:                               //   in Loop: Header=BB0_1 Depth=1
	.loc	1 0 18 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/strncmp.c:0:18
	jneq r3, 0, .LBB0_6
// %bb.3:                               //   in Loop: Header=BB0_1 Depth=1
.Ltmp5:
	//DEBUG_VALUE: len <- [DW_OP_plus_uconst 1, DW_OP_stack_value] undef
	.loc	1 11 30 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/strncmp.c:11:30
	add r1, r1, 1
	add r0, r0, 1
	add r2, r2, -1, nz, .LBB0_1
.Ltmp6:
.LBB0_5:
	.loc	1 0 30 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/strncmp.c:0:30
	move r3, r4
.LBB0_6:
	.loc	1 21 1 is_stmt 1                // uPIMulator_frontend/sdk/stdlib/strncmp.c:21:1
	move r0, r3
	jump r23
.Ltmp7:
.Lfunc_end0:
	.size	strncmp, .Lfunc_end0-strncmp
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.strncmp
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.strncmp,"ax",@progbits
                                        // -- End function
	.file	2 "/root" "uPIMulator_frontend/sdk/stdlib/stddef.h"
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp1-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp1-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp1-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp1-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0xc9 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x7c DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string3                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	162                             // DW_AT_type
                                        // DW_AT_external
	.byte	3                               // Abbrev [3] 0x3b:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string5                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
	.long	169                             // DW_AT_type
	.byte	3                               // Abbrev [3] 0x4a:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string7                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
	.long	169                             // DW_AT_type
	.byte	3                               // Abbrev [3] 0x59:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string8                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
	.long	186                             // DW_AT_type
	.byte	4                               // Abbrev [4] 0x68:0x39 DW_TAG_lexical_block
	.long	.Ltmp0                          // DW_AT_low_pc
	.long	.Ltmp6-.Ltmp0                   // DW_AT_high_pc
	.byte	5                               // Abbrev [5] 0x71:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string11                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	11                              // DW_AT_decl_line
	.long	186                             // DW_AT_type
	.byte	4                               // Abbrev [4] 0x80:0x20 DW_TAG_lexical_block
	.long	.Ltmp1                          // DW_AT_low_pc
	.long	.Ltmp4-.Ltmp1                   // DW_AT_high_pc
	.byte	6                               // Abbrev [6] 0x89:0xb DW_TAG_variable
	.long	.Linfo_string12                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	12                              // DW_AT_decl_line
	.long	204                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x94:0xb DW_TAG_variable
	.long	.Linfo_string14                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	13                              // DW_AT_decl_line
	.long	204                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0xa2:0x7 DW_TAG_base_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	8                               // Abbrev [8] 0xa9:0x5 DW_TAG_pointer_type
	.long	174                             // DW_AT_type
	.byte	9                               // Abbrev [9] 0xae:0x5 DW_TAG_const_type
	.long	179                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0xb3:0x7 DW_TAG_base_type
	.long	.Linfo_string6                  // DW_AT_name
	.byte	6                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	10                              // Abbrev [10] 0xba:0xb DW_TAG_typedef
	.long	197                             // DW_AT_type
	.long	.Linfo_string10                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	26                              // DW_AT_decl_line
	.byte	7                               // Abbrev [7] 0xc5:0x7 DW_TAG_base_type
	.long	.Linfo_string9                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	7                               // Abbrev [7] 0xcc:0x7 DW_TAG_base_type
	.long	.Linfo_string13                 // DW_AT_name
	.byte	8                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/stdlib/strncmp.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=153
.Linfo_string3:
	.asciz	"strncmp"                       // string offset=174
.Linfo_string4:
	.asciz	"int"                           // string offset=182
.Linfo_string5:
	.asciz	"string1"                       // string offset=186
.Linfo_string6:
	.asciz	"char"                          // string offset=194
.Linfo_string7:
	.asciz	"string2"                       // string offset=199
.Linfo_string8:
	.asciz	"size"                          // string offset=207
.Linfo_string9:
	.asciz	"unsigned int"                  // string offset=212
.Linfo_string10:
	.asciz	"size_t"                        // string offset=225
.Linfo_string11:
	.asciz	"len"                           // string offset=232
.Linfo_string12:
	.asciz	"c1"                            // string offset=236
.Linfo_string13:
	.asciz	"unsigned char"                 // string offset=239
.Linfo_string14:
	.asciz	"c2"                            // string offset=253
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
