	.text
	.file	"strncpy.c"
	.section	.text.strncpy,"ax",@progbits
	.globl	strncpy                         // -- Begin function strncpy
	.type	strncpy,@function
strncpy:                                // @strncpy
.Lfunc_begin0:
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/strncpy.c"
	.loc	1 10 0                          // uPIMulator_frontend/sdk/stdlib/strncpy.c:10:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: strncpy:destination <- $r0
	//DEBUG_VALUE: strncpy:source <- $r1
	//DEBUG_VALUE: strncpy:size <- $r2
	.cfi_def_cfa_offset -16
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 8, d22
	add r22, r22, 16
	.cfi_offset 15, -16
	.cfi_offset 14, -12
.Ltmp0:
	sd r22, -16, d14
.Ltmp1:
	//DEBUG_VALUE: strncpy:ptr <- $r0
	move r14, r0
.Ltmp2:
	//DEBUG_VALUE: strncpy:each_byte <- 0
	//DEBUG_VALUE: strncpy:c <- undef
	//DEBUG_VALUE: strncpy:ptr <- $r14
	//DEBUG_VALUE: strncpy:size <- $r2
	//DEBUG_VALUE: strncpy:source <- $r1
	//DEBUG_VALUE: strncpy:destination <- $r14
	.loc	1 15 5 prologue_end             // uPIMulator_frontend/sdk/stdlib/strncpy.c:15:5
	jeq r2, 0, .LBB0_6
.Ltmp3:
// %bb.1:
	//DEBUG_VALUE: strncpy:destination <- $r14
	//DEBUG_VALUE: strncpy:ptr <- $r14
	//DEBUG_VALUE: strncpy:size <- $r2
	//DEBUG_VALUE: strncpy:source <- $r1
	//DEBUG_VALUE: strncpy:each_byte <- 0
	.loc	1 0 5 is_stmt 0                 // uPIMulator_frontend/sdk/stdlib/strncpy.c:0:5
	move r3, 0
.Ltmp4:
.LBB0_2:                                // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: strncpy:destination <- $r14
	//DEBUG_VALUE: strncpy:size <- $r2
	add r0, r1, r3
	lbu r0, r0, 0
.Ltmp5:
	//DEBUG_VALUE: strncpy:each_byte <- $r3
	//DEBUG_VALUE: strncpy:ptr <- undef
	//DEBUG_VALUE: strncpy:source <- undef
	.loc	1 16 13 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/strncpy.c:16:13
	jeq r0, 0, .LBB0_3
.Ltmp6:
// %bb.5:                               //   in Loop: Header=BB0_2 Depth=1
	//DEBUG_VALUE: strncpy:destination <- $r14
	//DEBUG_VALUE: strncpy:each_byte <- $r3
	//DEBUG_VALUE: strncpy:size <- $r2
	.loc	1 25 14                         // uPIMulator_frontend/sdk/stdlib/strncpy.c:25:14
	add r4, r14, r3
.Ltmp7:
	.loc	1 15 43                         // uPIMulator_frontend/sdk/stdlib/strncpy.c:15:43
	add r3, r3, 1
.Ltmp8:
	//DEBUG_VALUE: strncpy:each_byte <- $r3
	//DEBUG_VALUE: strncpy:c <- undef
	.loc	1 25 14                         // uPIMulator_frontend/sdk/stdlib/strncpy.c:25:14
	sb r4, 0, r0
.Ltmp9:
	//DEBUG_VALUE: strncpy:c <- undef
	//DEBUG_VALUE: strncpy:ptr <- [DW_OP_plus_uconst 1, DW_OP_stack_value] undef
	//DEBUG_VALUE: strncpy:source <- [DW_OP_plus_uconst 1, DW_OP_stack_value] undef
	.loc	1 15 5                          // uPIMulator_frontend/sdk/stdlib/strncpy.c:15:5
	jneq r2, r3, .LBB0_2
.Ltmp10:
.LBB0_6:
	//DEBUG_VALUE: strncpy:destination <- $r14
	//DEBUG_VALUE: strncpy:size <- $r2
	.loc	1 32 1                          // uPIMulator_frontend/sdk/stdlib/strncpy.c:32:1
	move r0, r14
	ld d14, r22, -16
.Ltmp11:
	ld d22, r22, -8
	jump r23
.Ltmp12:
.LBB0_3:
	//DEBUG_VALUE: strncpy:destination <- $r14
	//DEBUG_VALUE: strncpy:each_byte <- $r3
	//DEBUG_VALUE: strncpy:size <- $r2
	//DEBUG_VALUE: strncpy:ptr <- undef
	//DEBUG_VALUE: strncpy:each_byte <- $r3
	.loc	1 17 13                         // uPIMulator_frontend/sdk/stdlib/strncpy.c:17:13
	jgeu r3, r2, .LBB0_6
.Ltmp13:
// %bb.4:
	//DEBUG_VALUE: strncpy:destination <- $r14
	//DEBUG_VALUE: strncpy:each_byte <- $r3
	//DEBUG_VALUE: strncpy:size <- $r2
	add r0, r14, r3
	sub r2, r2, r3
.Ltmp14:
	.loc	1 0 13 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/strncpy.c:0:13
	move r1, 0
.Ltmp15:
	.loc	1 18 22 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/strncpy.c:18:22
	call r23, memset
.Ltmp16:
	//DEBUG_VALUE: strncpy:each_byte <- [DW_OP_plus_uconst 1, DW_OP_stack_value] undef
	//DEBUG_VALUE: strncpy:ptr <- [DW_OP_plus_uconst 1, DW_OP_stack_value] undef
	.loc	1 32 1                          // uPIMulator_frontend/sdk/stdlib/strncpy.c:32:1
	move r0, r14
	ld d14, r22, -16
.Ltmp17:
	ld d22, r22, -8
	jump r23
.Ltmp18:
.Lfunc_end0:
	.size	strncpy, .Lfunc_end0-strncpy
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.strncpy
	.long	.Lfunc_begin0
	.byte	16
	.section	.text.strncpy,"ax",@progbits
                                        // -- End function
	.file	2 "/root" "uPIMulator_frontend/sdk/stdlib/stddef.h"
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp2-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp11-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	.Ltmp12-.Lfunc_begin0
	.long	.Ltmp17-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp4-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp14-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Ltmp1-.Lfunc_begin0
	.long	.Ltmp2-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp4-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	0
	.long	0
.Ldebug_loc4:
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp4-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp5-.Lfunc_begin0
	.long	.Ltmp10-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp12-.Lfunc_begin0
	.long	.Ltmp16-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.ascii	"\211\202\001"                  // DW_TAG_GNU_call_site
	.byte	0                               // DW_CHILDREN_no
	.ascii	"\223B"                         // DW_AT_GNU_call_site_target
	.byte	24                              // DW_FORM_exprloc
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0xb7 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x73 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string3                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	153                             // DW_AT_type
                                        // DW_AT_external
	.byte	3                               // Abbrev [3] 0x3b:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string5                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
	.long	153                             // DW_AT_type
	.byte	3                               // Abbrev [3] 0x4a:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string6                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
	.long	165                             // DW_AT_type
	.byte	3                               // Abbrev [3] 0x59:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string7                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
	.long	175                             // DW_AT_type
	.byte	4                               // Abbrev [4] 0x68:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string10                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	11                              // DW_AT_decl_line
	.long	153                             // DW_AT_type
	.byte	4                               // Abbrev [4] 0x77:0xf DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	.Linfo_string11                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	13                              // DW_AT_decl_line
	.long	175                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0x86:0xb DW_TAG_variable
	.long	.Linfo_string12                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	12                              // DW_AT_decl_line
	.long	158                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x91:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp16                         // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x99:0x5 DW_TAG_pointer_type
	.long	158                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x9e:0x7 DW_TAG_base_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	6                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	7                               // Abbrev [7] 0xa5:0x5 DW_TAG_pointer_type
	.long	170                             // DW_AT_type
	.byte	9                               // Abbrev [9] 0xaa:0x5 DW_TAG_const_type
	.long	158                             // DW_AT_type
	.byte	10                              // Abbrev [10] 0xaf:0xb DW_TAG_typedef
	.long	186                             // DW_AT_type
	.long	.Linfo_string9                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	26                              // DW_AT_decl_line
	.byte	8                               // Abbrev [8] 0xba:0x7 DW_TAG_base_type
	.long	.Linfo_string8                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/stdlib/strncpy.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=153
.Linfo_string3:
	.asciz	"strncpy"                       // string offset=174
.Linfo_string4:
	.asciz	"char"                          // string offset=182
.Linfo_string5:
	.asciz	"destination"                   // string offset=187
.Linfo_string6:
	.asciz	"source"                        // string offset=199
.Linfo_string7:
	.asciz	"size"                          // string offset=206
.Linfo_string8:
	.asciz	"unsigned int"                  // string offset=211
.Linfo_string9:
	.asciz	"size_t"                        // string offset=224
.Linfo_string10:
	.asciz	"ptr"                           // string offset=231
.Linfo_string11:
	.asciz	"each_byte"                     // string offset=235
.Linfo_string12:
	.asciz	"c"                             // string offset=245
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
