	.text
	.file	"strndup.c"
	.section	.text.strndup,"ax",@progbits
	.globl	strndup                         // -- Begin function strndup
	.type	strndup,@function
strndup:                                // @strndup
.Lfunc_begin0:
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/strndup.c"
	.loc	1 11 0                          // uPIMulator_frontend/sdk/stdlib/strndup.c:11:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: strndup:string <- $r0
	//DEBUG_VALUE: strndup:n <- $r1
	.cfi_def_cfa_offset -24
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 16, d22
	add r22, r22, 24
	.cfi_offset 15, -16
	.cfi_offset 14, -12
	sd r22, -16, d14
	.cfi_offset 17, -24
	.cfi_offset 16, -20
	sd r22, -24, d16
	move r14, r0
	//DEBUG_VALUE: strndup:n <- $r1
.Ltmp0:
	//DEBUG_VALUE: strndup:string <- $r14
	//DEBUG_VALUE: strndup:n <- $r1
	.loc	1 12 21 prologue_end            // uPIMulator_frontend/sdk/stdlib/strndup.c:12:21
	call r23, strnlen
.Ltmp1:
	move r15, r0
.Ltmp2:
	//DEBUG_VALUE: strndup:length <- $r15
	.loc	1 13 39                         // uPIMulator_frontend/sdk/stdlib/strndup.c:13:39
	add r0, r15, 1
	.loc	1 13 20 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/strndup.c:13:20
	call r23, buddy_alloc
.Ltmp3:
	//DEBUG_VALUE: strndup:result <- $r16
	move r16, r0, z, .LBB0_2
.Ltmp4:
// %bb.1:
	//DEBUG_VALUE: strndup:length <- $r15
	//DEBUG_VALUE: strndup:string <- $r14
	//DEBUG_VALUE: strndup:n <- $r1
	.loc	1 16 9 is_stmt 1                // uPIMulator_frontend/sdk/stdlib/strndup.c:16:9
	move r0, r16
	move r1, r14
.Ltmp5:
	move r2, r15
	call r23, memcpy
.Ltmp6:
	.loc	1 17 38                         // uPIMulator_frontend/sdk/stdlib/strndup.c:17:38
	add r0, r16, r15
	sb r0, 1, 0
.Ltmp7:
.LBB0_2:
	//DEBUG_VALUE: strndup:length <- $r15
	//DEBUG_VALUE: strndup:string <- $r14
	.loc	1 20 5                          // uPIMulator_frontend/sdk/stdlib/strndup.c:20:5
	move r0, r16
	ld d16, r22, -24
	ld d14, r22, -16
.Ltmp8:
	ld d22, r22, -8
	jump r23
.Ltmp9:
.Lfunc_end0:
	.size	strndup, .Lfunc_end0-strndup
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.strndup
	.long	.Lfunc_begin0
	.byte	24
	.section	.text.strndup,"ax",@progbits
                                        // -- End function
	.file	2 "/root" "uPIMulator_frontend/sdk/stdlib/stddef.h"
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp8-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp5-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp8-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp4-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	96                              // DW_OP_reg16
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.ascii	"\211\202\001"                  // DW_TAG_GNU_call_site
	.byte	0                               // DW_CHILDREN_no
	.ascii	"\223B"                         // DW_AT_GNU_call_site_target
	.byte	24                              // DW_FORM_exprloc
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0xac DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x1 DW_TAG_pointer_type
	.byte	3                               // Abbrev [3] 0x27:0x5 DW_TAG_pointer_type
	.long	44                              // DW_AT_type
	.byte	4                               // Abbrev [4] 0x2c:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	6                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	5                               // Abbrev [5] 0x33:0x67 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	10                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	39                              // DW_AT_type
                                        // DW_AT_external
	.byte	6                               // Abbrev [6] 0x48:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string5                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	10                              // DW_AT_decl_line
	.long	154                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x57:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string6                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	10                              // DW_AT_decl_line
	.long	164                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0x66:0xf DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string9                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	12                              // DW_AT_decl_line
	.long	164                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0x75:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string10                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	13                              // DW_AT_decl_line
	.long	39                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0x84:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp1                          // DW_AT_low_pc
	.byte	8                               // Abbrev [8] 0x8b:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp3                          // DW_AT_low_pc
	.byte	8                               // Abbrev [8] 0x92:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp6                          // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	3                               // Abbrev [3] 0x9a:0x5 DW_TAG_pointer_type
	.long	159                             // DW_AT_type
	.byte	9                               // Abbrev [9] 0x9f:0x5 DW_TAG_const_type
	.long	44                              // DW_AT_type
	.byte	10                              // Abbrev [10] 0xa4:0xb DW_TAG_typedef
	.long	175                             // DW_AT_type
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	26                              // DW_AT_decl_line
	.byte	4                               // Abbrev [4] 0xaf:0x7 DW_TAG_base_type
	.long	.Linfo_string7                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/stdlib/strndup.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=153
.Linfo_string3:
	.asciz	"char"                          // string offset=174
.Linfo_string4:
	.asciz	"strndup"                       // string offset=179
.Linfo_string5:
	.asciz	"string"                        // string offset=187
.Linfo_string6:
	.asciz	"n"                             // string offset=194
.Linfo_string7:
	.asciz	"unsigned int"                  // string offset=196
.Linfo_string8:
	.asciz	"size_t"                        // string offset=209
.Linfo_string9:
	.asciz	"length"                        // string offset=216
.Linfo_string10:
	.asciz	"result"                        // string offset=223
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
