	.text
	.file	"strspn.c"
	.section	.text.strspn,"ax",@progbits
	.globl	strspn                          // -- Begin function strspn
	.type	strspn,@function
strspn:                                 // @strspn
.Lfunc_begin0:
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/strspn.c"
	.loc	1 19 0                          // uPIMulator_frontend/sdk/stdlib/strspn.c:19:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: strspn:string <- $r0
	//DEBUG_VALUE: strspn:accept <- $r1
	.cfi_def_cfa_offset 0
	move r2, r0
.Ltmp0:
	//DEBUG_VALUE: strspn:prefix_length <- 0
	//DEBUG_VALUE: strspn:string <- $r2
	.loc	1 22 29 prologue_end            // uPIMulator_frontend/sdk/stdlib/strspn.c:22:29
	lbu r4, r2, 0
.Ltmp1:
	//DEBUG_VALUE: strspn:accept <- $r1
	.loc	1 22 5 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/strspn.c:22:5
	jeq r4, 0, .LBB0_1
.Ltmp2:
// %bb.2:
	//DEBUG_VALUE: strspn:string <- $r2
	//DEBUG_VALUE: strspn:accept <- $r1
	//DEBUG_VALUE: strspn:prefix_length <- 0
	.loc	1 0 5                           // uPIMulator_frontend/sdk/stdlib/strspn.c:0:5
	lbs r3, r1, 0
	.loc	1 22 5                          // uPIMulator_frontend/sdk/stdlib/strspn.c:22:5
	add r1, r1, 1
.Ltmp3:
	.loc	1 0 5                           // uPIMulator_frontend/sdk/stdlib/strspn.c:0:5
	move r0, 0, true, .LBB0_3
.Ltmp4:
.LBB0_4:                                //   in Loop: Header=BB0_3 Depth=1
	//DEBUG_VALUE: strspn:string <- $r2
	//DEBUG_VALUE: strspn:prefix_length <- $r0
	.loc	1 22 60                         // uPIMulator_frontend/sdk/stdlib/strspn.c:22:60
	add r0, r0, 1
.Ltmp5:
	//DEBUG_VALUE: strspn:prefix_length <- $r0
	.loc	1 22 29                         // uPIMulator_frontend/sdk/stdlib/strspn.c:22:29
	add r4, r2, r0
	lbu r4, r4, 0
	jeq r4, 0, .LBB0_7
.Ltmp6:
.LBB0_3:                                // =>This Loop Header: Depth=1
                                        //     Child Loop BB0_6 Depth 2
	//DEBUG_VALUE: strspn:string <- $r2
	//DEBUG_VALUE: strspn:prefix_length <- $r0
	//DEBUG_VALUE: accept_index <- 0
	//DEBUG_VALUE: a <- $r3
	.loc	1 29 19 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/strspn.c:29:19
	and r7, r3, 255
	and r8, r4, 255
	move r5, r1
	move r6, r3
.Ltmp7:
	.loc	1 29 17 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/strspn.c:29:17
	jeq r8, r7, .LBB0_4
.Ltmp8:
.LBB0_6:                                //   Parent Loop BB0_3 Depth=1
                                        // =>  This Inner Loop Header: Depth=2
	//DEBUG_VALUE: strspn:string <- $r2
	//DEBUG_VALUE: strspn:prefix_length <- $r0
	//DEBUG_VALUE: accept_index <- undef
	.loc	1 33 19 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/strspn.c:33:19
	and r6, r6, 255
.Ltmp9:
	//DEBUG_VALUE: accept_index <- [DW_OP_plus_uconst 1, DW_OP_stack_value] undef
	.loc	1 33 17 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/strspn.c:33:17
	jeq r6, 0, .LBB0_7
.Ltmp10:
// %bb.5:                               //   in Loop: Header=BB0_6 Depth=2
	//DEBUG_VALUE: strspn:string <- $r2
	//DEBUG_VALUE: strspn:prefix_length <- $r0
	//DEBUG_VALUE: accept_index <- [DW_OP_plus_uconst 1, DW_OP_stack_value] undef
	.loc	1 27 22 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/strspn.c:27:22
	lbu r6, r5, 0
.Ltmp11:
	//DEBUG_VALUE: a <- $r6
	.loc	1 29 19                         // uPIMulator_frontend/sdk/stdlib/strspn.c:29:19
	and r7, r4, 255
.Ltmp12:
	.loc	1 29 17 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/strspn.c:29:17
	add r5, r5, 1
	jneq r7, r6, .LBB0_6
	jump .LBB0_4
.Ltmp13:
.LBB0_7:
	//DEBUG_VALUE: strspn:string <- $r2
	//DEBUG_VALUE: strspn:prefix_length <- $r0
	.loc	1 42 1 is_stmt 1                // uPIMulator_frontend/sdk/stdlib/strspn.c:42:1
	jump r23
.Ltmp14:
.LBB0_1:
	//DEBUG_VALUE: strspn:string <- $r2
	//DEBUG_VALUE: strspn:accept <- $r1
	//DEBUG_VALUE: strspn:prefix_length <- 0
	.loc	1 0 1 is_stmt 0                 // uPIMulator_frontend/sdk/stdlib/strspn.c:0:1
	move r0, 0
	.loc	1 42 1                          // uPIMulator_frontend/sdk/stdlib/strspn.c:42:1
	jump r23
.Ltmp15:
.Lfunc_end0:
	.size	strspn, .Lfunc_end0-strspn
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.strspn
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.strspn,"ax",@progbits
                                        // -- End function
	.file	2 "/root" "uPIMulator_frontend/sdk/stdlib/stddef.h"
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp3-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp4-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp4-.Lfunc_begin0
	.long	.Ltmp14-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Ltmp6-.Lfunc_begin0
	.long	.Ltmp8-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc4:
	.long	.Ltmp6-.Lfunc_begin0
	.long	.Ltmp8-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp11-.Lfunc_begin0
	.long	.Ltmp13-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	86                              // DW_OP_reg6
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0xbf DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x80 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string3                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	18                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	166                             // DW_AT_type
                                        // DW_AT_external
	.byte	3                               // Abbrev [3] 0x3b:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string5                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	18                              // DW_AT_decl_line
	.long	173                             // DW_AT_type
	.byte	3                               // Abbrev [3] 0x4a:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string7                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	18                              // DW_AT_decl_line
	.long	173                             // DW_AT_type
	.byte	4                               // Abbrev [4] 0x59:0xf DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string8                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	20                              // DW_AT_decl_line
	.long	190                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0x68:0x3d DW_TAG_lexical_block
	.long	.Ltmp6                          // DW_AT_low_pc
	.long	.Ltmp13-.Ltmp6                  // DW_AT_high_pc
	.byte	4                               // Abbrev [4] 0x71:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string10                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	25                              // DW_AT_decl_line
	.long	166                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x80:0xb DW_TAG_variable
	.long	.Linfo_string12                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	23                              // DW_AT_decl_line
	.long	183                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0x8b:0x19 DW_TAG_lexical_block
	.long	.Ltmp6                          // DW_AT_low_pc
	.long	.Ltmp13-.Ltmp6                  // DW_AT_high_pc
	.byte	4                               // Abbrev [4] 0x94:0xf DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	.Linfo_string11                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	27                              // DW_AT_decl_line
	.long	183                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0xa6:0x7 DW_TAG_base_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	8                               // Abbrev [8] 0xad:0x5 DW_TAG_pointer_type
	.long	178                             // DW_AT_type
	.byte	9                               // Abbrev [9] 0xb2:0x5 DW_TAG_const_type
	.long	183                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0xb7:0x7 DW_TAG_base_type
	.long	.Linfo_string6                  // DW_AT_name
	.byte	6                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	10                              // Abbrev [10] 0xbe:0xb DW_TAG_typedef
	.long	166                             // DW_AT_type
	.long	.Linfo_string9                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	26                              // DW_AT_decl_line
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/stdlib/strspn.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=152
.Linfo_string3:
	.asciz	"strspn"                        // string offset=173
.Linfo_string4:
	.asciz	"unsigned int"                  // string offset=180
.Linfo_string5:
	.asciz	"string"                        // string offset=193
.Linfo_string6:
	.asciz	"char"                          // string offset=200
.Linfo_string7:
	.asciz	"accept"                        // string offset=205
.Linfo_string8:
	.asciz	"prefix_length"                 // string offset=212
.Linfo_string9:
	.asciz	"size_t"                        // string offset=226
.Linfo_string10:
	.asciz	"accept_index"                  // string offset=233
.Linfo_string11:
	.asciz	"a"                             // string offset=246
.Linfo_string12:
	.asciz	"c"                             // string offset=248
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
