	.text
	.file	"strtok_r.c"
	.section	.text.strtok_r,"ax",@progbits
	.globl	strtok_r                        // -- Begin function strtok_r
	.type	strtok_r,@function
strtok_r:                               // @strtok_r
.Lfunc_begin0:
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/strtok_r.c"
	.loc	1 10 0                          // uPIMulator_frontend/sdk/stdlib/strtok_r.c:10:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: strtok_r:str <- $r0
	//DEBUG_VALUE: strtok_r:delim <- $r1
	//DEBUG_VALUE: strtok_r:saveptr <- $r2
	.cfi_def_cfa_offset -32
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 24, d22
	add r22, r22, 32
	.cfi_offset 15, -16
	.cfi_offset 14, -12
	sd r22, -16, d14
	.cfi_offset 17, -24
	.cfi_offset 16, -20
	sd r22, -24, d16
	.cfi_offset 19, -32
	.cfi_offset 18, -28
	sd r22, -32, d18
	move r14, r2
	move r17, r1
.Ltmp0:
	//DEBUG_VALUE: strtok_r:saveptr <- $r14
	//DEBUG_VALUE: strtok_r:delim <- $r17
	//DEBUG_VALUE: strtok_r:str <- $r15
	move r15, r0, z, .LBB0_5
.Ltmp1:
// %bb.1:
	//DEBUG_VALUE: strtok_r:delim <- $r17
	//DEBUG_VALUE: strtok_r:saveptr <- $r14
	//DEBUG_VALUE: strtok_r:str <- $r15
	.loc	1 17 9 prologue_end             // uPIMulator_frontend/sdk/stdlib/strtok_r.c:17:9
	lbu r0, r15, 0
	move r18, 0
	jneq r0, 0, .LBB0_2
	jump .LBB0_8
.Ltmp2:
.LBB0_5:
	//DEBUG_VALUE: strtok_r:delim <- $r17
	//DEBUG_VALUE: strtok_r:saveptr <- $r14
	.loc	1 14 15                         // uPIMulator_frontend/sdk/stdlib/strtok_r.c:14:15
	lw r15, r14, 0
.Ltmp3:
	//DEBUG_VALUE: strtok_r:str <- $r15
	//DEBUG_VALUE: strtok_r:str <- $r15
	.loc	1 17 9                          // uPIMulator_frontend/sdk/stdlib/strtok_r.c:17:9
	lbu r0, r15, 0
	move r18, 0
.Ltmp4:
	.loc	1 17 9 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/strtok_r.c:17:9
	jeq r0, 0, .LBB0_8
.Ltmp5:
.LBB0_2:
	//DEBUG_VALUE: strtok_r:delim <- $r17
	//DEBUG_VALUE: strtok_r:str <- $r15
	//DEBUG_VALUE: strtok_r:saveptr <- $r14
	.loc	1 22 12 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/strtok_r.c:22:12
	move r0, r15
	move r1, r17
	call r23, strspn
.Ltmp6:
	.loc	1 22 9 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/strtok_r.c:22:9
	add r16, r15, r0
.Ltmp7:
	//DEBUG_VALUE: strtok_r:str <- $r16
	.loc	1 24 9 is_stmt 1                // uPIMulator_frontend/sdk/stdlib/strtok_r.c:24:9
	lbu r0, r16, 0
.Ltmp8:
	.loc	1 24 9 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/strtok_r.c:24:9
	jeq r0, 0, .LBB0_7
.Ltmp9:
// %bb.3:
	//DEBUG_VALUE: strtok_r:delim <- $r17
	//DEBUG_VALUE: strtok_r:str <- $r16
	//DEBUG_VALUE: strtok_r:saveptr <- $r14
	.loc	1 29 17 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/strtok_r.c:29:17
	move r0, r16
	move r1, r17
	call r23, strcspn
.Ltmp10:
	.loc	1 29 15 is_stmt 0               // uPIMulator_frontend/sdk/stdlib/strtok_r.c:29:15
	add r15, r16, r0
.Ltmp11:
	//DEBUG_VALUE: strtok_r:end <- $r15
	.loc	1 30 9 is_stmt 1                // uPIMulator_frontend/sdk/stdlib/strtok_r.c:30:9
	lbu r0, r15, 0
.Ltmp12:
	.loc	1 30 9 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/strtok_r.c:30:9
	jeq r0, 0, .LBB0_9
.Ltmp13:
// %bb.4:
	//DEBUG_VALUE: strtok_r:delim <- $r17
	//DEBUG_VALUE: strtok_r:str <- $r16
	//DEBUG_VALUE: strtok_r:end <- $r15
	//DEBUG_VALUE: strtok_r:saveptr <- $r14
	.loc	1 35 10 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/strtok_r.c:35:10
	sb r15, 0, 0
	.loc	1 36 20                         // uPIMulator_frontend/sdk/stdlib/strtok_r.c:36:20
	add r15, r15, 1, true, .LBB0_9
.Ltmp14:
.LBB0_7:
	//DEBUG_VALUE: strtok_r:delim <- $r17
	//DEBUG_VALUE: strtok_r:str <- $r16
	//DEBUG_VALUE: strtok_r:saveptr <- $r14
	.loc	1 0 20 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/strtok_r.c:0:20
	move r15, r16
.Ltmp15:
.LBB0_8:
	//DEBUG_VALUE: strtok_r:delim <- $r17
	//DEBUG_VALUE: strtok_r:saveptr <- $r14
	move r16, r18
.Ltmp16:
.LBB0_9:
	//DEBUG_VALUE: strtok_r:delim <- $r17
	//DEBUG_VALUE: strtok_r:saveptr <- $r14
	sw r14, 0, r15
	.loc	1 38 1 is_stmt 1                // uPIMulator_frontend/sdk/stdlib/strtok_r.c:38:1
	move r0, r16
	ld d18, r22, -32
	ld d16, r22, -24
.Ltmp17:
	ld d14, r22, -16
.Ltmp18:
	ld d22, r22, -8
	jump r23
.Ltmp19:
.Lfunc_end0:
	.size	strtok_r, .Lfunc_end0-strtok_r
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.strtok_r
	.long	.Lfunc_begin0
	.byte	32
	.section	.text.strtok_r,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp2-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp7-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	.Ltmp7-.Lfunc_begin0
	.long	.Ltmp15-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	96                              // DW_OP_reg16
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp17-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	97                              // DW_OP_reg17
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp18-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Ltmp11-.Lfunc_begin0
	.long	.Ltmp14-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.ascii	"\211\202\001"                  // DW_TAG_GNU_call_site
	.byte	0                               // DW_CHILDREN_no
	.ascii	"\223B"                         // DW_AT_GNU_call_site_target
	.byte	24                              // DW_FORM_exprloc
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x98 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x1 DW_TAG_pointer_type
	.byte	3                               // Abbrev [3] 0x27:0x60 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string3                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	135                             // DW_AT_type
                                        // DW_AT_external
	.byte	4                               // Abbrev [4] 0x3c:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string5                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
	.long	135                             // DW_AT_type
	.byte	4                               // Abbrev [4] 0x4b:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string6                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
	.long	147                             // DW_AT_type
	.byte	4                               // Abbrev [4] 0x5a:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string7                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
	.long	157                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0x69:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string8                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	11                              // DW_AT_decl_line
	.long	135                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x78:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp6                          // DW_AT_low_pc
	.byte	6                               // Abbrev [6] 0x7f:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp10                         // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x87:0x5 DW_TAG_pointer_type
	.long	140                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x8c:0x7 DW_TAG_base_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	6                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	7                               // Abbrev [7] 0x93:0x5 DW_TAG_pointer_type
	.long	152                             // DW_AT_type
	.byte	9                               // Abbrev [9] 0x98:0x5 DW_TAG_const_type
	.long	140                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0x9d:0x5 DW_TAG_pointer_type
	.long	135                             // DW_AT_type
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/stdlib/strtok_r.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=154
.Linfo_string3:
	.asciz	"strtok_r"                      // string offset=175
.Linfo_string4:
	.asciz	"char"                          // string offset=184
.Linfo_string5:
	.asciz	"str"                           // string offset=189
.Linfo_string6:
	.asciz	"delim"                         // string offset=193
.Linfo_string7:
	.asciz	"saveptr"                       // string offset=199
.Linfo_string8:
	.asciz	"end"                           // string offset=207
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
