	.text
	.file	"strupr.c"
	.section	.text.strupr,"ax",@progbits
	.globl	strupr                          // -- Begin function strupr
	.type	strupr,@function
strupr:                                 // @strupr
.Lfunc_begin0:
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/strupr.c"
	.loc	1 10 0                          // uPIMulator_frontend/sdk/stdlib/strupr.c:10:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: strupr:string <- $r0
	//DEBUG_VALUE: strupr:string <- $r0
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: strupr:ptr <- $r0
	//DEBUG_VALUE: strupr:ptr <- $r0
	.loc	1 14 17 prologue_end            // uPIMulator_frontend/sdk/stdlib/strupr.c:14:17
	lbu r1, r0, 0
.Ltmp0:
	//DEBUG_VALUE: strupr:c <- $r1
	.loc	1 14 5 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/strupr.c:14:5
	jeq r1, 0, .LBB0_5
.Ltmp1:
// %bb.1:
	//DEBUG_VALUE: strupr:c <- $r1
	//DEBUG_VALUE: strupr:ptr <- $r0
	//DEBUG_VALUE: strupr:string <- $r0
	add r2, r0, 1, true, .LBB0_2
.Ltmp2:
.LBB0_4:                                //   in Loop: Header=BB0_2 Depth=1
	//DEBUG_VALUE: strupr:ptr <- [DW_OP_constu 1, DW_OP_minus, DW_OP_stack_value] $r2
	//DEBUG_VALUE: strupr:string <- $r0
	.loc	1 15 14 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/strupr.c:15:14
	sb r2, -1, r1
.Ltmp3:
	//DEBUG_VALUE: strupr:ptr <- $r2
	.loc	1 14 17                         // uPIMulator_frontend/sdk/stdlib/strupr.c:14:17
	lbu r1, r2, 0
.Ltmp4:
	//DEBUG_VALUE: strupr:c <- $r1
	.loc	1 14 5 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/strupr.c:14:5
	add r2, r2, 1
.Ltmp5:
	jeq r1, 0, .LBB0_5
.Ltmp6:
.LBB0_2:                                // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: strupr:c <- $r1
	//DEBUG_VALUE: strupr:string <- $r0
	//DEBUG_VALUE: strupr:ptr <- [DW_OP_constu 1, DW_OP_minus, DW_OP_stack_value] $r2
	.loc	1 14 12                         // uPIMulator_frontend/sdk/stdlib/strupr.c:14:12
	extsb r3, r1
.Ltmp7:
	//DEBUG_VALUE: islower:c <- $r3
	//DEBUG_VALUE: toupper:c <- $r3
	.file	2 "/root" "uPIMulator_frontend/sdk/stdlib/ctype.h"
	.loc	2 32 50 is_stmt 1               // uPIMulator_frontend/sdk/stdlib/ctype.h:32:50
	add r3, r3, -97
.Ltmp8:
	.loc	2 171 12                        // uPIMulator_frontend/sdk/stdlib/ctype.h:171:12
	jgtu r3, 25, .LBB0_4
.Ltmp9:
// %bb.3:                               //   in Loop: Header=BB0_2 Depth=1
	//DEBUG_VALUE: strupr:ptr <- [DW_OP_constu 1, DW_OP_minus, DW_OP_stack_value] $r2
	//DEBUG_VALUE: strupr:c <- $r1
	//DEBUG_VALUE: strupr:string <- $r0
	.loc	2 0 12 is_stmt 0                // uPIMulator_frontend/sdk/stdlib/ctype.h:0:12
	add r1, r1, -32, true, .LBB0_4
.Ltmp10:
.LBB0_5:
	//DEBUG_VALUE: strupr:c <- $r1
	//DEBUG_VALUE: strupr:string <- $r0
	.loc	1 19 5 is_stmt 1                // uPIMulator_frontend/sdk/stdlib/strupr.c:19:5
	jump r23
.Ltmp11:
.Lfunc_end0:
	.size	strupr, .Lfunc_end0-strupr
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.strupr
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.strupr,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp2-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp3-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	114                             // DW_OP_breg2
	.byte	127                             // -1
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp5-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp6-.Lfunc_begin0
	.long	.Ltmp10-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	114                             // DW_OP_breg2
	.byte	127                             // -1
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp2-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp4-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Ltmp7-.Lfunc_begin0
	.long	.Ltmp8-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	1                               // DW_CHILDREN_yes
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	11                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	12                              // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0xd2 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x18 DW_TAG_subprogram
	.long	.Linfo_string3                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	32                              // DW_AT_decl_line
	.long	62                              // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	3                               // Abbrev [3] 0x32:0xb DW_TAG_formal_parameter
	.long	.Linfo_string5                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	32                              // DW_AT_decl_line
	.long	62                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	4                               // Abbrev [4] 0x3e:0x7 DW_TAG_base_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	5                               // Abbrev [5] 0x45:0x18 DW_TAG_subprogram
	.long	.Linfo_string6                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	169                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	62                              // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	3                               // Abbrev [3] 0x51:0xb DW_TAG_formal_parameter
	.long	.Linfo_string5                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	169                             // DW_AT_decl_line
	.long	62                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	6                               // Abbrev [6] 0x5d:0x73 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string7                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	208                             // DW_AT_type
                                        // DW_AT_external
	.byte	7                               // Abbrev [7] 0x72:0xd DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	.Linfo_string9                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	9                               // DW_AT_decl_line
	.long	208                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x7f:0xf DW_TAG_variable
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string10                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	11                              // DW_AT_decl_line
	.long	208                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x8e:0xf DW_TAG_variable
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string5                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	12                              // DW_AT_decl_line
	.long	213                             // DW_AT_type
	.byte	9                               // Abbrev [9] 0x9d:0x32 DW_TAG_inlined_subroutine
	.long	69                              // DW_AT_abstract_origin
	.long	.Ltmp7                          // DW_AT_low_pc
	.long	.Ltmp9-.Ltmp7                   // DW_AT_high_pc
	.byte	1                               // DW_AT_call_file
	.byte	15                              // DW_AT_call_line
	.byte	16                              // DW_AT_call_column
	.byte	10                              // Abbrev [10] 0xad:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	81                              // DW_AT_abstract_origin
	.byte	9                               // Abbrev [9] 0xb6:0x18 DW_TAG_inlined_subroutine
	.long	38                              // DW_AT_abstract_origin
	.long	.Ltmp7                          // DW_AT_low_pc
	.long	.Ltmp8-.Ltmp7                   // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	171                             // DW_AT_call_line
	.byte	12                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0xc6:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	83
	.long	50                              // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	12                              // Abbrev [12] 0xd0:0x5 DW_TAG_pointer_type
	.long	213                             // DW_AT_type
	.byte	4                               // Abbrev [4] 0xd5:0x7 DW_TAG_base_type
	.long	.Linfo_string8                  // DW_AT_name
	.byte	6                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/stdlib/strupr.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=152
.Linfo_string3:
	.asciz	"islower"                       // string offset=173
.Linfo_string4:
	.asciz	"int"                           // string offset=181
.Linfo_string5:
	.asciz	"c"                             // string offset=185
.Linfo_string6:
	.asciz	"toupper"                       // string offset=187
.Linfo_string7:
	.asciz	"strupr"                        // string offset=195
.Linfo_string8:
	.asciz	"char"                          // string offset=202
.Linfo_string9:
	.asciz	"string"                        // string offset=207
.Linfo_string10:
	.asciz	"ptr"                           // string offset=214
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
