	.text
	.file	"adddf3.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/stdint.h"
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/fp_lib.h"
	.section	.text.__adddf3,"ax",@progbits
	.globl	__adddf3                        // -- Begin function __adddf3
	.type	__adddf3,@function
__adddf3:                               // @__adddf3
.Lfunc_begin0:
	.file	3 "/root" "uPIMulator_frontend/sdk/syslib/adddf3.c"
	.loc	3 20 0                          // uPIMulator_frontend/sdk/syslib/adddf3.c:20:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __adddf3:a <- $d0
	//DEBUG_VALUE: __adddf3:a <- $d0
	//DEBUG_VALUE: __adddf3:b <- $d2
	//DEBUG_VALUE: __adddf3:b <- $d2
	//DEBUG_VALUE: __addXf3__:a <- $d0
	//DEBUG_VALUE: __addXf3__:a <- $d0
	//DEBUG_VALUE: __addXf3__:b <- $d2
	//DEBUG_VALUE: __addXf3__:b <- $d2
	//DEBUG_VALUE: toRep:x <- $d0
	//DEBUG_VALUE: toRep:x <- $d0
	//DEBUG_VALUE: toRep:x <- undef
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: toRep:rep <- $d0
	//DEBUG_VALUE: toRep:rep <- $d0
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: __addXf3__:bRep <- $d2
	.file	4 "/root" "uPIMulator_frontend/sdk/syslib/fp_add_impl.inc"
	.loc	4 20 29 prologue_end            // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:20:29
	and r7, r1, 4294967295
	and r6, r0, 2147483647
.Ltmp0:
	//DEBUG_VALUE: __addXf3__:aAbs <- $d6
	.loc	4 24 14                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:24:14
	add r5, r7, 4294967295
	addc r4, r6, 4294967295
	move r11, 4294967294
	move r10, 2146435071
.Ltmp1:
	.loc	4 21 29                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:21:29
	and r9, r3, 4294967295
	and r8, r2, 2147483647
.Ltmp2:
	//DEBUG_VALUE: __addXf3__:bAbs <- $d8
	.loc	4 24 46                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:24:46
	sub zero, r5, r11
	subc zero, r4, r10, xgtu, .LBB0_2
.Ltmp3:
// %bb.1:
	//DEBUG_VALUE: __addXf3__:bAbs <- $d8
	//DEBUG_VALUE: __addXf3__:aAbs <- $d6
	//DEBUG_VALUE: __addXf3__:bRep <- $d2
	//DEBUG_VALUE: __addXf3__:b <- $d2
	//DEBUG_VALUE: __adddf3:b <- $d2
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	//DEBUG_VALUE: __addXf3__:a <- $d0
	//DEBUG_VALUE: __adddf3:a <- $d0
	.loc	4 0 46 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:46
	add r5, r9, 4294967295
	addc r4, r8, 4294967295
	move r11, 4294967295
	move r10, 2146435071
	.loc	4 24 46                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:24:46
	sub zero, r5, r11
	subc zero, r4, r10, geu, .LBB0_2
.Ltmp4:
.LBB0_16:
	//DEBUG_VALUE: __addXf3__:bAbs <- $d8
	//DEBUG_VALUE: __addXf3__:aAbs <- $d6
	//DEBUG_VALUE: __addXf3__:bRep <- $d2
	//DEBUG_VALUE: __addXf3__:b <- $d2
	//DEBUG_VALUE: __adddf3:b <- $d2
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	//DEBUG_VALUE: __addXf3__:a <- $d0
	//DEBUG_VALUE: __adddf3:a <- $d0
	.loc	4 53 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:53:9
	sub zero, r9, r7
	subc zero, r8, r6, xleu, .LBB0_18
.Ltmp5:
// %bb.17:
	//DEBUG_VALUE: __addXf3__:bAbs <- $d8
	//DEBUG_VALUE: __addXf3__:aAbs <- $d6
	//DEBUG_VALUE: __addXf3__:bRep <- $d2
	//DEBUG_VALUE: __addXf3__:b <- $d2
	//DEBUG_VALUE: __adddf3:b <- $d2
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	//DEBUG_VALUE: __addXf3__:a <- $d0
	//DEBUG_VALUE: __adddf3:a <- $d0
	movd d4, d0
	movd d0, d2
.Ltmp6:
	.loc	4 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:9
	jump .LBB0_19
.Ltmp7:
.LBB0_2:
	//DEBUG_VALUE: __addXf3__:bAbs <- $d8
	//DEBUG_VALUE: __addXf3__:aAbs <- $d6
	//DEBUG_VALUE: __addXf3__:bRep <- $d2
	//DEBUG_VALUE: __addXf3__:b <- $d2
	//DEBUG_VALUE: __adddf3:b <- $d2
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	//DEBUG_VALUE: __addXf3__:a <- $d0
	//DEBUG_VALUE: __adddf3:a <- $d0
	move r5, 1
	move r4, 2146435072
.Ltmp8:
	.loc	4 27 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:27:13
	sub zero, r7, r5
	subc zero, r6, r4, ltu, .LBB0_4
.Ltmp9:
// %bb.3:
	//DEBUG_VALUE: __addXf3__:bAbs <- $d8
	//DEBUG_VALUE: __addXf3__:aAbs <- $d6
	//DEBUG_VALUE: __addXf3__:bRep <- $d2
	//DEBUG_VALUE: __addXf3__:b <- $d2
	//DEBUG_VALUE: __adddf3:b <- $d2
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	//DEBUG_VALUE: __addXf3__:a <- $d0
	//DEBUG_VALUE: __adddf3:a <- $d0
	//DEBUG_VALUE: toRep:x <- $d0
	//DEBUG_VALUE: toRep:rep <- $d0
	.loc	4 27 52 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:27:52
	or r5, r1, 0
	or r4, r0, 524288
.Ltmp10:
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $d4
	.loc	3 21 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/adddf3.c:21:5
	movd d0, d4
.Ltmp11:
	jump r23
.Ltmp12:
.LBB0_18:
	//DEBUG_VALUE: __addXf3__:bAbs <- $d8
	//DEBUG_VALUE: __addXf3__:aAbs <- $d6
	//DEBUG_VALUE: __addXf3__:bRep <- $d2
	//DEBUG_VALUE: __addXf3__:b <- $d2
	//DEBUG_VALUE: __adddf3:b <- $d2
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	//DEBUG_VALUE: __addXf3__:a <- $d0
	//DEBUG_VALUE: __adddf3:a <- $d0
	.loc	4 53 9                          // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:53:9
	movd d4, d2
.Ltmp13:
.LBB0_19:
	//DEBUG_VALUE: __addXf3__:bAbs <- $d8
	//DEBUG_VALUE: __addXf3__:aAbs <- $d6
	//DEBUG_VALUE: __addXf3__:bRep <- $d2
	//DEBUG_VALUE: __addXf3__:b <- $d2
	//DEBUG_VALUE: __adddf3:b <- $d2
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	//DEBUG_VALUE: __addXf3__:bRep <- $d4
	.loc	4 60 26                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:60:26
	lsr.u d8, r0, 20
.Ltmp14:
	.loc	4 61 26                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:61:26
	lsr.u d2, r4, 20
.Ltmp15:
	.loc	4 61 21 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:61:21
	and r3, r3, 2047
.Ltmp16:
	//DEBUG_VALUE: __addXf3__:bExponent <- $r3
	.loc	4 62 31 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:62:31
	and r7, r1, 4294967295
.Ltmp17:
	and r6, r0, 1048575
.Ltmp18:
	//DEBUG_VALUE: __addXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d4
	//DEBUG_VALUE: __addXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	.loc	4 60 21                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:60:21
	and r2, r9, 2047
.Ltmp19:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	.loc	4 66 9                          // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:66:9
	jeq r2, 0, .LBB0_20
.Ltmp20:
// %bb.27:
	//DEBUG_VALUE: __addXf3__:bExponent <- $r3
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d4
	//DEBUG_VALUE: __addXf3__:bRep <- $d4
	//DEBUG_VALUE: __addXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	.loc	4 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:0
	and r11, r5, 4294967295
	and r10, r4, 1048575
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	jneq r3, 0, .LBB0_35
	jump .LBB0_28
.Ltmp21:
.LBB0_4:
	//DEBUG_VALUE: __addXf3__:bAbs <- $d8
	//DEBUG_VALUE: __addXf3__:aAbs <- $d6
	//DEBUG_VALUE: __addXf3__:bRep <- $d2
	//DEBUG_VALUE: __addXf3__:b <- $d2
	//DEBUG_VALUE: __adddf3:b <- $d2
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	//DEBUG_VALUE: __addXf3__:a <- $d0
	//DEBUG_VALUE: __adddf3:a <- $d0
	.loc	4 29 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:29:13
	sub zero, r9, r5
	subc zero, r8, r4, ltu, .LBB0_6
.Ltmp22:
// %bb.5:
	//DEBUG_VALUE: __addXf3__:bAbs <- $d8
	//DEBUG_VALUE: __addXf3__:aAbs <- $d6
	//DEBUG_VALUE: __addXf3__:bRep <- $d2
	//DEBUG_VALUE: __addXf3__:b <- $d2
	//DEBUG_VALUE: __adddf3:b <- $d2
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	//DEBUG_VALUE: __addXf3__:a <- $d0
	//DEBUG_VALUE: __adddf3:a <- $d0
	//DEBUG_VALUE: toRep:x <- $d2
	//DEBUG_VALUE: toRep:rep <- $d2
	.loc	4 29 52 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:29:52
	or r5, r3, 0
	or r4, r2, 524288
.Ltmp23:
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $d4
	.loc	3 21 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/adddf3.c:21:5
	movd d0, d4
.Ltmp24:
	jump r23
.Ltmp25:
.LBB0_20:
	//DEBUG_VALUE: __addXf3__:bExponent <- $r3
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d4
	//DEBUG_VALUE: __addXf3__:bRep <- $d4
	//DEBUG_VALUE: __addXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	//DEBUG_VALUE: normalize:significand <- undef
	//DEBUG_VALUE: rep_clz:a <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	.loc	2 80 9                          // uPIMulator_frontend/sdk/syslib/fp_lib.h:80:9
	move.u d8, r6
	move.s d10, 0
	jneq r9, r11, .LBB0_22
.Ltmp26:
// %bb.71:
	jneq r8, r10, .LBB0_22
.Ltmp27:
// %bb.72:
// %bb.21:
	//DEBUG_VALUE: __addXf3__:bExponent <- $r3
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d4
	//DEBUG_VALUE: __addXf3__:bRep <- $d4
	//DEBUG_VALUE: __addXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	.loc	2 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_lib.h:0:9
	clz r2, r1
.Ltmp28:
	or r2, r2, 32
.Ltmp29:
	//DEBUG_VALUE: rep_clz:a <- 4503599627370496
	.loc	2 251 45 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_lib.h:251:45
	add r8, r2, -11
.Ltmp30:
	//DEBUG_VALUE: normalize:shift <- $r8
	.loc	2 252 18                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:252:18
	lslx r9, r7, r8, sh32, .LBB0_25
	jump .LBB0_24
.Ltmp31:
.LBB0_25:
	//DEBUG_VALUE: normalize:shift <- $r8
	//DEBUG_VALUE: __addXf3__:bExponent <- $r3
	//DEBUG_VALUE: __addXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d4
	//DEBUG_VALUE: __addXf3__:bRep <- $d4
	//DEBUG_VALUE: __addXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	lsl r6, r7, r8
	move r7, 0
	.loc	2 253 14                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:253:14
	sub r2, 12, r2
.Ltmp32:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	.loc	4 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:0
	and r11, r5, 4294967295
	and r10, r4, 1048575
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	jneq r3, 0, .LBB0_35
	jump .LBB0_28
.Ltmp33:
.LBB0_6:
	//DEBUG_VALUE: __addXf3__:bAbs <- $d8
	//DEBUG_VALUE: __addXf3__:aAbs <- $d6
	//DEBUG_VALUE: __addXf3__:bRep <- $d2
	//DEBUG_VALUE: __addXf3__:b <- $d2
	//DEBUG_VALUE: __adddf3:b <- $d2
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	//DEBUG_VALUE: __addXf3__:a <- $d0
	//DEBUG_VALUE: __adddf3:a <- $d0
	move r5, 0
	move r4, 2146435072
.Ltmp34:
	.loc	4 31 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:31:13
	jneq r7, r5, .LBB0_10
.Ltmp35:
// %bb.73:
	jneq r6, r4, .LBB0_10
// %bb.74:
// %bb.7:
.Ltmp36:
	//DEBUG_VALUE: __addXf3__:bAbs <- $d8
	//DEBUG_VALUE: __addXf3__:aAbs <- $d6
	//DEBUG_VALUE: __addXf3__:bRep <- $d2
	//DEBUG_VALUE: __addXf3__:b <- $d2
	//DEBUG_VALUE: __adddf3:b <- $d2
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	//DEBUG_VALUE: __addXf3__:a <- $d0
	//DEBUG_VALUE: __adddf3:a <- $d0
	//DEBUG_VALUE: toRep:x <- $d0
	//DEBUG_VALUE: toRep:rep <- $d0
	//DEBUG_VALUE: toRep:x <- $d2
	//DEBUG_VALUE: toRep:rep <- $d2
	.loc	4 33 27                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:33:27
	xor r3, r3, r1
.Ltmp37:
	xor r2, r2, r0
	move r5, 0
	move r4, 2147483648
.Ltmp38:
	.loc	4 33 17 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:33:17
	jneq r3, r5, .LBB0_9
.Ltmp39:
// %bb.75:
	jneq r2, r4, .LBB0_9
.Ltmp40:
// %bb.76:
// %bb.8:
	//DEBUG_VALUE: __addXf3__:bAbs <- $d8
	//DEBUG_VALUE: __addXf3__:aAbs <- $d6
	//DEBUG_VALUE: toRep:rep <- $d0
	//DEBUG_VALUE: toRep:x <- $d0
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	//DEBUG_VALUE: __addXf3__:a <- $d0
	//DEBUG_VALUE: __adddf3:a <- $d0
	.loc	4 0 17                          // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:17
	move r1, 0
.Ltmp41:
	move r0, 2146959360
.LBB0_9:
	.loc	3 21 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/adddf3.c:21:5
	jump r23
.LBB0_22:
.Ltmp42:
	//DEBUG_VALUE: __addXf3__:bExponent <- $r3
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d4
	//DEBUG_VALUE: __addXf3__:bRep <- $d4
	//DEBUG_VALUE: __addXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	.loc	3 0 5 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/adddf3.c:0:5
	clz r2, r6
.Ltmp43:
	//DEBUG_VALUE: rep_clz:a <- 4503599627370496
	.loc	2 251 45 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_lib.h:251:45
	add r8, r2, -11
.Ltmp44:
	//DEBUG_VALUE: normalize:shift <- $r8
	.loc	2 252 18                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:252:18
	lslx r9, r7, r8, sh32, .LBB0_25
.Ltmp45:
.LBB0_24:
	//DEBUG_VALUE: normalize:shift <- $r8
	//DEBUG_VALUE: __addXf3__:bExponent <- $r3
	//DEBUG_VALUE: __addXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d4
	//DEBUG_VALUE: __addXf3__:bRep <- $d4
	//DEBUG_VALUE: __addXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	lsl r10, r6, r8
	or r6, r10, r9
	lsl r7, r7, r8
	.loc	2 253 14                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:253:14
	sub r2, 12, r2
.Ltmp46:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	.loc	4 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:0
	and r11, r5, 4294967295
	and r10, r4, 1048575
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	.loc	4 67 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:67:9
	jneq r3, 0, .LBB0_35
.Ltmp47:
.LBB0_28:
	//DEBUG_VALUE: __addXf3__:bExponent <- $r3
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d4
	//DEBUG_VALUE: __addXf3__:bRep <- $d4
	//DEBUG_VALUE: __addXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	//DEBUG_VALUE: normalize:significand <- undef
	//DEBUG_VALUE: rep_clz:a <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d4
	.loc	2 80 9                          // uPIMulator_frontend/sdk/syslib/fp_lib.h:80:9
	move.u d8, r10
	move.s d12, 0
	jneq r9, r13, .LBB0_30
.Ltmp48:
// %bb.77:
	jneq r8, r12, .LBB0_30
.Ltmp49:
// %bb.78:
// %bb.29:
	//DEBUG_VALUE: __addXf3__:bExponent <- $r3
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d4
	//DEBUG_VALUE: __addXf3__:bRep <- $d4
	//DEBUG_VALUE: __addXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	.loc	2 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_lib.h:0:9
	clz r3, r5
.Ltmp50:
	or r3, r3, 32
.Ltmp51:
	//DEBUG_VALUE: rep_clz:a <- 4503599627370496
	.loc	2 251 45 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_lib.h:251:45
	add r8, r3, -11
.Ltmp52:
	//DEBUG_VALUE: normalize:shift <- $r8
	.loc	2 252 18                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:252:18
	lslx r9, r11, r8, sh32, .LBB0_33
	jump .LBB0_32
.Ltmp53:
.LBB0_33:
	//DEBUG_VALUE: normalize:shift <- $r8
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d4
	//DEBUG_VALUE: __addXf3__:bRep <- $d4
	//DEBUG_VALUE: __addXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	lsl r10, r11, r8
	move r11, 0, true, .LBB0_34
.Ltmp54:
.LBB0_30:
	//DEBUG_VALUE: __addXf3__:bExponent <- $r3
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d4
	//DEBUG_VALUE: __addXf3__:bRep <- $d4
	//DEBUG_VALUE: __addXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	.loc	2 0 18 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_lib.h:0:18
	clz r3, r10
.Ltmp55:
	//DEBUG_VALUE: rep_clz:a <- 4503599627370496
	.loc	2 251 45 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_lib.h:251:45
	add r8, r3, -11
.Ltmp56:
	//DEBUG_VALUE: normalize:shift <- $r8
	.loc	2 252 18                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:252:18
	lslx r9, r11, r8, sh32, .LBB0_33
.Ltmp57:
.LBB0_32:
	//DEBUG_VALUE: normalize:shift <- $r8
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d4
	//DEBUG_VALUE: __addXf3__:bRep <- $d4
	//DEBUG_VALUE: __addXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	lsl r12, r10, r8
	or r10, r12, r9
	lsl r11, r11, r8
.Ltmp58:
.LBB0_34:
	//DEBUG_VALUE: normalize:shift <- $r8
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d4
	//DEBUG_VALUE: __addXf3__:bRep <- $d4
	//DEBUG_VALUE: __addXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	.loc	2 253 14                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:253:14
	sub r3, 12, r3
.Ltmp59:
	//DEBUG_VALUE: __addXf3__:bExponent <- $r3
.LBB0_35:
	//DEBUG_VALUE: __addXf3__:bExponent <- $r3
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d4
	//DEBUG_VALUE: __addXf3__:bRep <- $d4
	//DEBUG_VALUE: __addXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	//DEBUG_VALUE: __addXf3__:bExponent <- $r3
	//DEBUG_VALUE: __addXf3__:resultSign <- undef
	.loc	4 72 36                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:72:36
	xor r5, r1, r5
.Ltmp60:
	xor r4, r0, r4
.Ltmp61:
	//DEBUG_VALUE: __addXf3__:subtraction <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] undef
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	.loc	4 78 49                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:78:49
	lslx r8, r7, 3
	lsl_add r8, r8, r6, 3
	lsl r9, r7, 3
.Ltmp62:
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- undef
	.loc	4 79 49                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:79:49
	lslx r6, r11, 3
	lsl_add r6, r6, r10, 3
	lsl r7, r11, 3
	or r7, r7, 0
	or r6, r6, 8388608
.Ltmp63:
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:align <- $r3
	.loc	4 83 42                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:83:42
	sub r3, r2, r3, z, .LBB0_36
.Ltmp64:
// %bb.37:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	.loc	4 0 42 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:42
	move.s d10, 1
.Ltmp65:
	.loc	4 85 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:85:13
	jgtu r3, 63, .LBB0_45
.Ltmp66:
// %bb.38:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	.loc	4 86 60                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:86:60
	sub r12, 64, r3
	.loc	4 86 46 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:86:46
	lslx r10, r7, r12, sh32, .LBB0_40
.Ltmp67:
// %bb.39:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	lsl r11, r6, r12
	or r10, r11, r10
	lsl r11, r7, r12
	move.s d12, 0
	.loc	4 86 33                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:86:33
	sub zero, r11, r13
	subc r10, r10, r12, xnz
.Ltmp68:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] $r10
	.loc	4 87 41 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:87:41
	lsrx r11, r6, r3, sh32, .LBB0_43
	jump .LBB0_42
.Ltmp69:
.LBB0_43:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] $r10
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	lsr.u d12, r6, r3
	jump .LBB0_44
.Ltmp70:
.LBB0_36:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	.loc	4 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:0
	movd d10, d6
.Ltmp71:
.LBB0_45:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	//DEBUG_VALUE: __addXf3__:resultSign <- undef
	move.s d12, -1
	or r7, r9, 0
.Ltmp72:
	or r6, r8, 8388608
.Ltmp73:
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	.loc	4 92 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:92:9
	sub zero, r5, r13
	subc zero, r4, r12, xles, .LBB0_46
.Ltmp74:
.LBB0_54:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	.loc	4 106 22                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:106:22
	add r7, r11, r7
.Ltmp75:
	addc r6, r10, r6
.Ltmp76:
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	.loc	4 110 26                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:110:26
	and r5, r7, 0
	and r4, r6, 16777216
	move.s d8, 0
.Ltmp77:
	.loc	4 110 13 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:110:13
	jneq r5, r9, .LBB0_80
.Ltmp78:
// %bb.79:
	jeq r4, r8, .LBB0_56
.LBB0_80:
// %bb.55:
.Ltmp79:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	.loc	4 111 46 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:111:46
	and r5, r7, 1
	and r4, r6, 0
.Ltmp80:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] undef
	.loc	4 112 41                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:112:41
	lsrx r3, r6, 1
	lsr_add r9, r3, r7, 1
	lsr r8, r6, 1
	.loc	4 112 46 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:112:46
	or r7, r9, r5
.Ltmp81:
	or r6, r8, r4
.Ltmp82:
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	.loc	4 113 23 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:113:23
	add r2, r2, 1
.Ltmp83:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	.loc	4 0 23 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:23
	move r3, 2047
.Ltmp84:
	and r1, r1, 0
.Ltmp85:
	and r0, r0, 2147483648
.Ltmp86:
	//DEBUG_VALUE: __addXf3__:resultSign <- $d0
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	.loc	4 118 9 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:118:9
	jges r2, r3, .LBB0_57
	jump .LBB0_58
.Ltmp87:
.LBB0_40:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	.loc	4 86 46                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:86:46
	lsl r10, r7, r12
	move r11, 0
	move.s d12, 0
	.loc	4 86 33 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:86:33
	sub zero, r11, r13
	subc r10, r10, r12, xnz
.Ltmp88:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] $r10
	.loc	4 87 41 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:87:41
	lsrx r11, r6, r3, sh32, .LBB0_43
.Ltmp89:
.LBB0_42:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] $r10
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	lsr r12, r7, r3
	or r13, r11, r12
	lsr r12, r6, r3
.Ltmp90:
.LBB0_44:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] $r10
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	.loc	4 87 52 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:87:52
	move.u d6, r10
.Ltmp91:
	.loc	4 87 50                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:87:50
	or r11, r13, r7
	or r10, r12, r6
.Ltmp92:
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:resultSign <- undef
	.loc	4 0 50                          // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:50
	move.s d12, -1
.Ltmp93:
	or r7, r9, 0
	or r6, r8, 8388608
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
.Ltmp94:
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	.loc	4 92 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:92:9
	sub zero, r5, r13
	subc zero, r4, r12, xgts, .LBB0_54
.Ltmp95:
.LBB0_46:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	.loc	4 93 22                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:93:22
	sub r7, r7, r11
.Ltmp96:
	subc r6, r6, r10
.Ltmp97:
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	.loc	4 0 22 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:22
	move.s d4, 0
	.loc	4 95 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:95:13
	jneq r7, r5, .LBB0_82
.Ltmp98:
// %bb.81:
	jeq r6, r4, .LBB0_70
.LBB0_82:
// %bb.47:
.Ltmp99:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	.loc	4 99 13                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:99:13
	lsr.u d8, r6, 23
	move.s d4, 0
	jneq r9, r5, .LBB0_56
.Ltmp100:
// %bb.83:
	jneq r8, r4, .LBB0_56
// %bb.84:
// %bb.48:
.Ltmp101:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	//DEBUG_VALUE: rep_clz:a <- $d6
	.loc	2 80 9                          // uPIMulator_frontend/sdk/syslib/fp_lib.h:80:9
	move.u d8, r6
	jneq r9, r5, .LBB0_50
.Ltmp102:
// %bb.85:
	jneq r8, r4, .LBB0_50
.Ltmp103:
// %bb.86:
// %bb.49:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	.loc	2 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_lib.h:0:9
	clz r3, r7
	or r3, r3, 32
.Ltmp104:
	//DEBUG_VALUE: rep_clz:a <- 36028797018963968
	.loc	4 100 53 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:100:53
	add r3, r3, -8
.Ltmp105:
	//DEBUG_VALUE: shift <- $r3
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	.loc	4 101 26                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:101:26
	lslx r4, r7, r3, sh32, .LBB0_53
	jump .LBB0_52
.Ltmp106:
.LBB0_53:
	//DEBUG_VALUE: shift <- $r3
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	lsl r6, r7, r3
.Ltmp107:
	move r7, 0
.Ltmp108:
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	.loc	4 102 23                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:102:23
	sub r2, r2, r3
.Ltmp109:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
.LBB0_56:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	.loc	4 0 23 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:23
	move r3, 2047
	and r1, r1, 0
.Ltmp110:
	and r0, r0, 2147483648
.Ltmp111:
	//DEBUG_VALUE: __addXf3__:resultSign <- $d0
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	.loc	4 118 9 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:118:9
	jlts r2, r3, .LBB0_58
.Ltmp112:
.LBB0_57:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:resultSign <- $d0
	.loc	4 118 57 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:118:57
	or r5, r1, 0
	or r4, r0, 2146435072
.Ltmp113:
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $d4
	.loc	3 21 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/adddf3.c:21:5
	movd d0, d4
.Ltmp114:
	jump r23
.Ltmp115:
.LBB0_10:
	//DEBUG_VALUE: __addXf3__:bAbs <- $d8
	//DEBUG_VALUE: __addXf3__:aAbs <- $d6
	//DEBUG_VALUE: __addXf3__:bRep <- $d2
	//DEBUG_VALUE: __addXf3__:b <- $d2
	//DEBUG_VALUE: __adddf3:b <- $d2
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	//DEBUG_VALUE: __addXf3__:a <- $d0
	//DEBUG_VALUE: __adddf3:a <- $d0
	.loc	4 39 13                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:39:13
	jneq r9, r5, .LBB0_12
.Ltmp116:
// %bb.87:
	jneq r8, r4, .LBB0_12
.Ltmp117:
// %bb.88:
// %bb.11:
	//DEBUG_VALUE: __adddf3:b <- $d2
	//DEBUG_VALUE: __adddf3:a <- $d0
	.loc	4 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:13
	movd d4, d2
	.loc	3 21 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/adddf3.c:21:5
	movd d0, d4
.Ltmp118:
	jump r23
.Ltmp119:
.LBB0_12:
	//DEBUG_VALUE: __addXf3__:bAbs <- $d8
	//DEBUG_VALUE: __addXf3__:aAbs <- $d6
	//DEBUG_VALUE: __addXf3__:bRep <- $d2
	//DEBUG_VALUE: __addXf3__:b <- $d2
	//DEBUG_VALUE: __adddf3:b <- $d2
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	//DEBUG_VALUE: __addXf3__:a <- $d0
	//DEBUG_VALUE: __adddf3:a <- $d0
	.loc	3 0 5 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/adddf3.c:0:5
	move.s d10, 0
.Ltmp120:
	.loc	4 42 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:42:13
	jneq r7, r11, .LBB0_90
.Ltmp121:
// %bb.89:
	jeq r6, r10, .LBB0_13
.LBB0_90:
// %bb.15:
.Ltmp122:
	//DEBUG_VALUE: __addXf3__:bAbs <- $d8
	//DEBUG_VALUE: __addXf3__:aAbs <- $d6
	//DEBUG_VALUE: __addXf3__:bRep <- $d2
	//DEBUG_VALUE: __addXf3__:b <- $d2
	//DEBUG_VALUE: __adddf3:b <- $d2
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	//DEBUG_VALUE: __addXf3__:a <- $d0
	//DEBUG_VALUE: __adddf3:a <- $d0
	.loc	4 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:13
	movd d4, d0
	.loc	4 49 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:49:13
	jneq r9, r11, .LBB0_16
.Ltmp123:
// %bb.91:
	jneq r8, r10, .LBB0_16
// %bb.92:
	jump .LBB0_70
.Ltmp124:
.LBB0_50:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	.loc	4 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:13
	clz r3, r6
.Ltmp125:
	//DEBUG_VALUE: rep_clz:a <- 36028797018963968
	.loc	4 100 53 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:100:53
	add r3, r3, -8
.Ltmp126:
	//DEBUG_VALUE: shift <- $r3
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	.loc	4 101 26                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:101:26
	lslx r4, r7, r3, sh32, .LBB0_53
.Ltmp127:
.LBB0_52:
	//DEBUG_VALUE: shift <- $r3
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	lsl r5, r6, r3
	or r6, r5, r4
.Ltmp128:
	lsl r7, r7, r3
.Ltmp129:
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	.loc	4 102 23                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:102:23
	sub r2, r2, r3
.Ltmp130:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	.loc	4 0 23 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:23
	move r3, 2047
.Ltmp131:
	and r1, r1, 0
.Ltmp132:
	and r0, r0, 2147483648
.Ltmp133:
	//DEBUG_VALUE: __addXf3__:resultSign <- $d0
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	.loc	4 118 9 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:118:9
	jges r2, r3, .LBB0_57
.Ltmp134:
.LBB0_58:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:resultSign <- $d0
	.loc	4 120 9                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:120:9
	jgts r2, 0, .LBB0_66
.Ltmp135:
// %bb.59:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:resultSign <- $d0
	.loc	4 124 56                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:124:56
	add r3, r2, 63
	.loc	4 123 29                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:123:29
	sub r2, 1, r2
.Ltmp136:
	//DEBUG_VALUE: shift <- $r2
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	.loc	4 124 42                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:124:42
	lslx r4, r7, r3, sh32, .LBB0_61
.Ltmp137:
// %bb.60:
	//DEBUG_VALUE: shift <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:resultSign <- $d0
	lsl r5, r6, r3
	or r4, r5, r4
	lsl r5, r7, r3
	move.s d8, 0
	.loc	4 124 29 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:124:29
	sub zero, r5, r9
	subc r3, r4, r8, xnz
.Ltmp138:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] $r3
	.loc	4 125 37 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:125:37
	lsrx r4, r6, r2, sh32, .LBB0_64
	jump .LBB0_63
.Ltmp139:
.LBB0_64:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] $r3
	//DEBUG_VALUE: shift <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:resultSign <- $d0
	lsr.u d4, r6, r2
	jump .LBB0_65
.Ltmp140:
.LBB0_61:
	//DEBUG_VALUE: shift <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:resultSign <- $d0
	.loc	4 124 42                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:124:42
	lsl r4, r7, r3
	move r5, 0
	move.s d8, 0
	.loc	4 124 29 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:124:29
	sub zero, r5, r9
	subc r3, r4, r8, xnz
.Ltmp141:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] $r3
	.loc	4 125 37 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:125:37
	lsrx r4, r6, r2, sh32, .LBB0_64
.Ltmp142:
.LBB0_63:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] $r3
	//DEBUG_VALUE: shift <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:resultSign <- $d0
	lsr r5, r7, r2
	or r5, r4, r5
	lsr r4, r6, r2
.Ltmp143:
.LBB0_65:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] $r3
	//DEBUG_VALUE: shift <- $r2
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:resultSign <- $d0
	.loc	4 125 48 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:125:48
	move.u d2, r3
.Ltmp144:
	.loc	4 125 46                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:125:46
	or r7, r5, r3
.Ltmp145:
	or r6, r4, r2
.Ltmp146:
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	.loc	4 0 46                          // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:46
	move r2, 0
.Ltmp147:
	//DEBUG_VALUE: __addXf3__:aExponent <- 0
.LBB0_66:
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:resultSign <- $d0
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:aExponent <- $r2
	.loc	4 133 33 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:133:33
	lsrx r3, r6, 3
	lsr_add r5, r3, r7, 3
	lsr r4, r6, 3
	.loc	4 133 38 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:133:38
	and r5, r5, 4294967295
	and r4, r4, 1048575
.Ltmp148:
	//DEBUG_VALUE: __addXf3__:result <- $d4
	.loc	4 136 15 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:136:15
	move.s d2, r2
.Ltmp149:
	.loc	4 136 32 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:136:32
	move r9, 0
	lsl r8, r3, 20
.Ltmp150:
	//DEBUG_VALUE: __addXf3__:result <- undef
	.loc	4 136 12                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:136:12
	or r1, r5, r1
.Ltmp151:
	or r0, r4, r0
	.loc	4 137 12 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:137:12
	or r1, r1, r9
	or r0, r0, r8
.Ltmp152:
	//DEBUG_VALUE: __addXf3__:result <- $d0
	.loc	4 0 12 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:12
	move r2, 4
	.loc	4 130 34 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:130:34
	and r3, r7, 7
.Ltmp153:
	//DEBUG_VALUE: __addXf3__:roundGuardSticky <- $r3
	.loc	4 141 26                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:141:26
	sub r2, r3, r2, gtu
.Ltmp154:
	.loc	4 141 9 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:141:9
	move.u d4, r2
	add r1, r1, r5
.Ltmp155:
	addc r0, r0, r4
.Ltmp156:
	//DEBUG_VALUE: __addXf3__:result <- $d0
	.loc	4 142 9 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:142:9
	jneq r3, 4, .LBB0_68
.Ltmp157:
// %bb.67:
	//DEBUG_VALUE: __addXf3__:roundGuardSticky <- $r3
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:result <- $d0
	.loc	4 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:9
	and r3, r1, 1
.Ltmp158:
	and r2, r0, 0
	jump .LBB0_69
.Ltmp159:
.LBB0_68:
	//DEBUG_VALUE: __addXf3__:roundGuardSticky <- $r3
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:result <- $d0
	move.s d2, 0
.Ltmp160:
.LBB0_69:
	//DEBUG_VALUE: __addXf3__:bSignificand <- $d10
	//DEBUG_VALUE: __addXf3__:aSignificand <- $d6
	//DEBUG_VALUE: __addXf3__:result <- $d0
	.loc	4 142 9                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:142:9
	add r5, r3, r1
	addc r4, r2, r0
.Ltmp161:
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $d4
	//DEBUG_VALUE: __addXf3__:result <- $d4
.LBB0_70:
	.loc	3 21 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/adddf3.c:21:5
	movd d0, d4
	jump r23
.LBB0_13:
.Ltmp162:
	//DEBUG_VALUE: __addXf3__:bAbs <- $d8
	//DEBUG_VALUE: __addXf3__:aAbs <- $d6
	//DEBUG_VALUE: __addXf3__:bRep <- $d2
	//DEBUG_VALUE: __addXf3__:b <- $d2
	//DEBUG_VALUE: __adddf3:b <- $d2
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	//DEBUG_VALUE: __addXf3__:a <- $d0
	//DEBUG_VALUE: __adddf3:a <- $d0
	.loc	3 0 5 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/adddf3.c:0:5
	movd d4, d2
.Ltmp163:
	.loc	4 44 17 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:44:17
	jneq r9, r11, .LBB0_70
.Ltmp164:
// %bb.93:
	jneq r8, r10, .LBB0_70
// %bb.94:
// %bb.14:
.Ltmp165:
	//DEBUG_VALUE: __addXf3__:bAbs <- $d8
	//DEBUG_VALUE: __addXf3__:aAbs <- $d6
	//DEBUG_VALUE: __addXf3__:bRep <- $d2
	//DEBUG_VALUE: __addXf3__:b <- $d2
	//DEBUG_VALUE: __adddf3:b <- $d2
	//DEBUG_VALUE: __addXf3__:aRep <- $d0
	//DEBUG_VALUE: __addXf3__:a <- $d0
	//DEBUG_VALUE: __adddf3:a <- $d0
	//DEBUG_VALUE: toRep:x <- $d0
	//DEBUG_VALUE: toRep:rep <- $d0
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: toRep:rep <- undef
	.loc	4 44 48 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:44:48
	and r5, r3, r1
	and r4, r2, r0
.Ltmp166:
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $d4
	.loc	3 21 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/adddf3.c:21:5
	movd d0, d4
.Ltmp167:
	jump r23
.Ltmp168:
.Lfunc_end0:
	.size	__adddf3, .Lfunc_end0-__adddf3
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__adddf3
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.__adddf3,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp6-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp7-.Lfunc_begin0
	.long	.Ltmp11-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp12-.Lfunc_begin0
	.long	.Ltmp13-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp21-.Lfunc_begin0
	.long	.Ltmp24-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp33-.Lfunc_begin0
	.long	.Ltmp35-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp36-.Lfunc_begin0
	.long	.Ltmp39-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp40-.Lfunc_begin0
	.long	.Ltmp41-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp115-.Lfunc_begin0
	.long	.Ltmp116-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp117-.Lfunc_begin0
	.long	.Ltmp118-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp119-.Lfunc_begin0
	.long	.Ltmp121-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp122-.Lfunc_begin0
	.long	.Ltmp123-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp162-.Lfunc_begin0
	.long	.Ltmp164-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp165-.Lfunc_begin0
	.long	.Ltmp167-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp15-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp21-.Lfunc_begin0
	.long	.Ltmp25-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp33-.Lfunc_begin0
	.long	.Ltmp35-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp36-.Lfunc_begin0
	.long	.Ltmp37-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp115-.Lfunc_begin0
	.long	.Ltmp116-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp117-.Lfunc_begin0
	.long	.Ltmp121-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp122-.Lfunc_begin0
	.long	.Ltmp123-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp162-.Lfunc_begin0
	.long	.Ltmp164-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp165-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp6-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp7-.Lfunc_begin0
	.long	.Ltmp11-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp12-.Lfunc_begin0
	.long	.Ltmp13-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp21-.Lfunc_begin0
	.long	.Ltmp24-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp33-.Lfunc_begin0
	.long	.Ltmp35-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp36-.Lfunc_begin0
	.long	.Ltmp39-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp115-.Lfunc_begin0
	.long	.Ltmp116-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp119-.Lfunc_begin0
	.long	.Ltmp121-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp122-.Lfunc_begin0
	.long	.Ltmp123-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp162-.Lfunc_begin0
	.long	.Ltmp164-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp165-.Lfunc_begin0
	.long	.Ltmp167-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp15-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp21-.Lfunc_begin0
	.long	.Ltmp25-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp33-.Lfunc_begin0
	.long	.Ltmp35-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp36-.Lfunc_begin0
	.long	.Ltmp37-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp115-.Lfunc_begin0
	.long	.Ltmp116-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp119-.Lfunc_begin0
	.long	.Ltmp121-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp122-.Lfunc_begin0
	.long	.Ltmp123-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp162-.Lfunc_begin0
	.long	.Ltmp164-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp165-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc4:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp6-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp7-.Lfunc_begin0
	.long	.Ltmp11-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp12-.Lfunc_begin0
	.long	.Ltmp24-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp25-.Lfunc_begin0
	.long	.Ltmp26-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp27-.Lfunc_begin0
	.long	.Ltmp35-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp36-.Lfunc_begin0
	.long	.Ltmp39-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp42-.Lfunc_begin0
	.long	.Ltmp48-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp49-.Lfunc_begin0
	.long	.Ltmp78-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp79-.Lfunc_begin0
	.long	.Ltmp85-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp87-.Lfunc_begin0
	.long	.Ltmp98-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp99-.Lfunc_begin0
	.long	.Ltmp100-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp101-.Lfunc_begin0
	.long	.Ltmp102-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp103-.Lfunc_begin0
	.long	.Ltmp110-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp115-.Lfunc_begin0
	.long	.Ltmp116-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp119-.Lfunc_begin0
	.long	.Ltmp121-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp122-.Lfunc_begin0
	.long	.Ltmp123-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp124-.Lfunc_begin0
	.long	.Ltmp132-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp162-.Lfunc_begin0
	.long	.Ltmp164-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp165-.Lfunc_begin0
	.long	.Ltmp167-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc5:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp13-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp13-.Lfunc_begin0
	.long	.Ltmp21-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp21-.Lfunc_begin0
	.long	.Ltmp25-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp25-.Lfunc_begin0
	.long	.Ltmp26-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp27-.Lfunc_begin0
	.long	.Ltmp33-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp33-.Lfunc_begin0
	.long	.Ltmp35-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp36-.Lfunc_begin0
	.long	.Ltmp37-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp42-.Lfunc_begin0
	.long	.Ltmp48-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp49-.Lfunc_begin0
	.long	.Ltmp60-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp115-.Lfunc_begin0
	.long	.Ltmp116-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp119-.Lfunc_begin0
	.long	.Ltmp121-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp122-.Lfunc_begin0
	.long	.Ltmp123-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp162-.Lfunc_begin0
	.long	.Ltmp164-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp165-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc6:
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp17-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp21-.Lfunc_begin0
	.long	.Ltmp25-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp33-.Lfunc_begin0
	.long	.Ltmp35-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp36-.Lfunc_begin0
	.long	.Ltmp39-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp115-.Lfunc_begin0
	.long	.Ltmp116-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp119-.Lfunc_begin0
	.long	.Ltmp121-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp122-.Lfunc_begin0
	.long	.Ltmp123-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp162-.Lfunc_begin0
	.long	.Ltmp164-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp165-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc7:
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp14-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	89                              // sub-register DW_OP_reg9
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	88                              // sub-register DW_OP_reg8
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp21-.Lfunc_begin0
	.long	.Ltmp25-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	89                              // sub-register DW_OP_reg9
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	88                              // sub-register DW_OP_reg8
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp33-.Lfunc_begin0
	.long	.Ltmp35-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	89                              // sub-register DW_OP_reg9
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	88                              // sub-register DW_OP_reg8
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp36-.Lfunc_begin0
	.long	.Ltmp39-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	89                              // sub-register DW_OP_reg9
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	88                              // sub-register DW_OP_reg8
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp115-.Lfunc_begin0
	.long	.Ltmp116-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	89                              // sub-register DW_OP_reg9
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	88                              // sub-register DW_OP_reg8
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp119-.Lfunc_begin0
	.long	.Ltmp121-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	89                              // sub-register DW_OP_reg9
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	88                              // sub-register DW_OP_reg8
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp122-.Lfunc_begin0
	.long	.Ltmp123-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	89                              // sub-register DW_OP_reg9
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	88                              // sub-register DW_OP_reg8
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp162-.Lfunc_begin0
	.long	.Ltmp164-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	89                              // sub-register DW_OP_reg9
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	88                              // sub-register DW_OP_reg8
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp165-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	89                              // sub-register DW_OP_reg9
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	88                              // sub-register DW_OP_reg8
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc8:
	.long	.Ltmp16-.Lfunc_begin0
	.long	.Ltmp21-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp25-.Lfunc_begin0
	.long	.Ltmp26-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp27-.Lfunc_begin0
	.long	.Ltmp33-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp42-.Lfunc_begin0
	.long	.Ltmp48-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp49-.Lfunc_begin0
	.long	.Ltmp50-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp54-.Lfunc_begin0
	.long	.Ltmp55-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp59-.Lfunc_begin0
	.long	.Ltmp64-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc9:
	.long	.Ltmp62-.Lfunc_begin0
	.long	.Ltmp63-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	91                              // sub-register DW_OP_reg11
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	90                              // sub-register DW_OP_reg10
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp63-.Lfunc_begin0
	.long	.Ltmp72-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp73-.Lfunc_begin0
	.long	.Ltmp78-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	91                              // sub-register DW_OP_reg11
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	90                              // sub-register DW_OP_reg10
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp79-.Lfunc_begin0
	.long	.Ltmp87-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	91                              // sub-register DW_OP_reg11
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	90                              // sub-register DW_OP_reg10
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp87-.Lfunc_begin0
	.long	.Ltmp91-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp92-.Lfunc_begin0
	.long	.Ltmp98-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	91                              // sub-register DW_OP_reg11
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	90                              // sub-register DW_OP_reg10
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp99-.Lfunc_begin0
	.long	.Ltmp100-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	91                              // sub-register DW_OP_reg11
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	90                              // sub-register DW_OP_reg10
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp101-.Lfunc_begin0
	.long	.Ltmp102-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	91                              // sub-register DW_OP_reg11
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	90                              // sub-register DW_OP_reg10
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp103-.Lfunc_begin0
	.long	.Ltmp115-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	91                              // sub-register DW_OP_reg11
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	90                              // sub-register DW_OP_reg10
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp124-.Lfunc_begin0
	.long	.Ltmp161-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	91                              // sub-register DW_OP_reg11
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	90                              // sub-register DW_OP_reg10
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc10:
	.long	.Ltmp61-.Lfunc_begin0
	.long	.Ltmp62-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp73-.Lfunc_begin0
	.long	.Ltmp75-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp76-.Lfunc_begin0
	.long	.Ltmp78-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp79-.Lfunc_begin0
	.long	.Ltmp81-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp82-.Lfunc_begin0
	.long	.Ltmp87-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp94-.Lfunc_begin0
	.long	.Ltmp96-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp97-.Lfunc_begin0
	.long	.Ltmp98-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp99-.Lfunc_begin0
	.long	.Ltmp100-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp101-.Lfunc_begin0
	.long	.Ltmp102-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp103-.Lfunc_begin0
	.long	.Ltmp107-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp108-.Lfunc_begin0
	.long	.Ltmp115-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp124-.Lfunc_begin0
	.long	.Ltmp128-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp129-.Lfunc_begin0
	.long	.Ltmp145-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp146-.Lfunc_begin0
	.long	.Ltmp161-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc11:
	.long	.Ltmp19-.Lfunc_begin0
	.long	.Ltmp21-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp25-.Lfunc_begin0
	.long	.Ltmp26-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp27-.Lfunc_begin0
	.long	.Ltmp28-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp32-.Lfunc_begin0
	.long	.Ltmp33-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp46-.Lfunc_begin0
	.long	.Ltmp48-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp49-.Lfunc_begin0
	.long	.Ltmp78-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp79-.Lfunc_begin0
	.long	.Ltmp98-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp99-.Lfunc_begin0
	.long	.Ltmp100-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp101-.Lfunc_begin0
	.long	.Ltmp102-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp103-.Lfunc_begin0
	.long	.Ltmp115-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp124-.Lfunc_begin0
	.long	.Ltmp136-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp147-.Lfunc_begin0
	.long	.Ltmp149-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc12:
	.long	.Ltmp30-.Lfunc_begin0
	.long	.Ltmp33-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	88                              // DW_OP_reg8
	.long	.Ltmp44-.Lfunc_begin0
	.long	.Ltmp47-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	88                              // DW_OP_reg8
	.long	0
	.long	0
.Ldebug_loc13:
	.long	.Ltmp52-.Lfunc_begin0
	.long	.Ltmp54-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	88                              // DW_OP_reg8
	.long	.Ltmp56-.Lfunc_begin0
	.long	.Ltmp59-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	88                              // DW_OP_reg8
	.long	0
	.long	0
.Ldebug_loc14:
	.long	.Ltmp86-.Lfunc_begin0
	.long	.Ltmp87-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp111-.Lfunc_begin0
	.long	.Ltmp114-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp133-.Lfunc_begin0
	.long	.Ltmp151-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc15:
	.long	.Ltmp63-.Lfunc_begin0
	.long	.Ltmp64-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc16:
	.long	.Ltmp68-.Lfunc_begin0
	.long	.Ltmp70-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	122                             // DW_OP_breg10
	.byte	0                               // 0
	.byte	16                              // DW_OP_constu
	.byte	1                               // 1
	.byte	26                              // DW_OP_and
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp88-.Lfunc_begin0
	.long	.Ltmp92-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	122                             // DW_OP_breg10
	.byte	0                               // 0
	.byte	16                              // DW_OP_constu
	.byte	1                               // 1
	.byte	26                              // DW_OP_and
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc17:
	.long	.Ltmp101-.Lfunc_begin0
	.long	.Ltmp102-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc18:
	.long	.Ltmp105-.Lfunc_begin0
	.long	.Ltmp109-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp126-.Lfunc_begin0
	.long	.Ltmp131-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc19:
	.long	.Ltmp136-.Lfunc_begin0
	.long	.Ltmp144-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc20:
	.long	.Ltmp138-.Lfunc_begin0
	.long	.Ltmp140-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	115                             // DW_OP_breg3
	.byte	0                               // 0
	.byte	16                              // DW_OP_constu
	.byte	1                               // 1
	.byte	26                              // DW_OP_and
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp141-.Lfunc_begin0
	.long	.Ltmp144-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	115                             // DW_OP_breg3
	.byte	0                               // 0
	.byte	16                              // DW_OP_constu
	.byte	1                               // 1
	.byte	26                              // DW_OP_and
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc21:
	.long	.Ltmp148-.Lfunc_begin0
	.long	.Ltmp150-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp152-.Lfunc_begin0
	.long	.Ltmp155-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp156-.Lfunc_begin0
	.long	.Ltmp161-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc22:
	.long	.Ltmp153-.Lfunc_begin0
	.long	.Ltmp158-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp159-.Lfunc_begin0
	.long	.Ltmp160-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	11                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	12                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	1                               // DW_CHILDREN_yes
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	13                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	14                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	15                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	16                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	17                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	1                               // DW_CHILDREN_yes
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	18                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	19                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x33f DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0xb DW_TAG_typedef
	.long	49                              // DW_AT_type
	.long	.Linfo_string5                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	68                              // DW_AT_decl_line
	.byte	2                               // Abbrev [2] 0x31:0xb DW_TAG_typedef
	.long	60                              // DW_AT_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	53                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x3c:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x43:0xfe DW_TAG_subprogram
	.long	.Linfo_string6                  // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	17                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	321                             // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0x4f:0xb DW_TAG_formal_parameter
	.long	.Linfo_string9                  // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	17                              // DW_AT_decl_line
	.long	321                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0x5a:0xb DW_TAG_formal_parameter
	.long	.Linfo_string10                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	17                              // DW_AT_decl_line
	.long	321                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x65:0xb DW_TAG_variable
	.long	.Linfo_string11                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	18                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0x70:0xb DW_TAG_variable
	.long	.Linfo_string12                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	19                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0x7b:0xb DW_TAG_variable
	.long	.Linfo_string13                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	20                              // DW_AT_decl_line
	.long	339                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x86:0xb DW_TAG_variable
	.long	.Linfo_string14                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	21                              // DW_AT_decl_line
	.long	339                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x91:0xb DW_TAG_variable
	.long	.Linfo_string15                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	61                              // DW_AT_decl_line
	.long	344                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x9c:0xb DW_TAG_variable
	.long	.Linfo_string17                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	63                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0xa7:0xb DW_TAG_variable
	.long	.Linfo_string18                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	62                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0xb2:0xb DW_TAG_variable
	.long	.Linfo_string19                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	60                              // DW_AT_decl_line
	.long	344                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xbd:0xb DW_TAG_variable
	.long	.Linfo_string20                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	71                              // DW_AT_decl_line
	.long	339                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xc8:0xb DW_TAG_variable
	.long	.Linfo_string21                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	72                              // DW_AT_decl_line
	.long	351                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xd3:0xb DW_TAG_variable
	.long	.Linfo_string23                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	83                              // DW_AT_decl_line
	.long	363                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xde:0xb DW_TAG_variable
	.long	.Linfo_string25                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	133                             // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0xe9:0xb DW_TAG_variable
	.long	.Linfo_string26                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	130                             // DW_AT_decl_line
	.long	375                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0xf4:0xd DW_TAG_lexical_block
	.byte	6                               // Abbrev [6] 0xf5:0xb DW_TAG_variable
	.long	.Linfo_string27                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	86                              // DW_AT_decl_line
	.long	351                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x101:0xd DW_TAG_lexical_block
	.byte	6                               // Abbrev [6] 0x102:0xb DW_TAG_variable
	.long	.Linfo_string27                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	111                             // DW_AT_decl_line
	.long	351                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x10e:0xd DW_TAG_lexical_block
	.byte	6                               // Abbrev [6] 0x10f:0xb DW_TAG_variable
	.long	.Linfo_string28                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	100                             // DW_AT_decl_line
	.long	375                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x11b:0x18 DW_TAG_lexical_block
	.byte	6                               // Abbrev [6] 0x11c:0xb DW_TAG_variable
	.long	.Linfo_string28                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	123                             // DW_AT_decl_line
	.long	375                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x127:0xb DW_TAG_variable
	.long	.Linfo_string27                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	124                             // DW_AT_decl_line
	.long	351                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x133:0xd DW_TAG_lexical_block
	.byte	6                               // Abbrev [6] 0x134:0xb DW_TAG_variable
	.long	.Linfo_string29                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	54                              // DW_AT_decl_line
	.long	339                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	2                               // Abbrev [2] 0x141:0xb DW_TAG_typedef
	.long	332                             // DW_AT_type
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	70                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x14c:0x7 DW_TAG_base_type
	.long	.Linfo_string7                  // DW_AT_name
	.byte	4                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	8                               // Abbrev [8] 0x153:0x5 DW_TAG_const_type
	.long	38                              // DW_AT_type
	.byte	3                               // Abbrev [3] 0x158:0x7 DW_TAG_base_type
	.long	.Linfo_string16                 // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	8                               // Abbrev [8] 0x15f:0x5 DW_TAG_const_type
	.long	356                             // DW_AT_type
	.byte	3                               // Abbrev [3] 0x164:0x7 DW_TAG_base_type
	.long	.Linfo_string22                 // DW_AT_name
	.byte	2                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	8                               // Abbrev [8] 0x16b:0x5 DW_TAG_const_type
	.long	368                             // DW_AT_type
	.byte	3                               // Abbrev [3] 0x170:0x7 DW_TAG_base_type
	.long	.Linfo_string24                 // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	8                               // Abbrev [8] 0x177:0x5 DW_TAG_const_type
	.long	344                             // DW_AT_type
	.byte	4                               // Abbrev [4] 0x17c:0x18 DW_TAG_subprogram
	.long	.Linfo_string30                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	75                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	344                             // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0x188:0xb DW_TAG_formal_parameter
	.long	.Linfo_string9                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	75                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	4                               // Abbrev [4] 0x194:0x23 DW_TAG_subprogram
	.long	.Linfo_string31                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	249                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	344                             // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0x1a0:0xb DW_TAG_formal_parameter
	.long	.Linfo_string32                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	249                             // DW_AT_decl_line
	.long	439                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x1ab:0xb DW_TAG_variable
	.long	.Linfo_string28                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	251                             // DW_AT_decl_line
	.long	375                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	9                               // Abbrev [9] 0x1b7:0x5 DW_TAG_pointer_type
	.long	38                              // DW_AT_type
	.byte	10                              // Abbrev [10] 0x1bc:0x18d DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string33                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	19                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	321                             // DW_AT_type
                                        // DW_AT_external
	.byte	11                              // Abbrev [11] 0x1d1:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string9                  // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	19                              // DW_AT_decl_line
	.long	332                             // DW_AT_type
	.byte	11                              // Abbrev [11] 0x1e0:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string10                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	19                              // DW_AT_decl_line
	.long	332                             // DW_AT_type
	.byte	12                              // Abbrev [12] 0x1ef:0x159 DW_TAG_inlined_subroutine
	.long	67                              // DW_AT_abstract_origin
	.long	.Ldebug_ranges0                 // DW_AT_ranges
	.byte	3                               // DW_AT_call_file
	.byte	21                              // DW_AT_call_line
	.byte	12                              // DW_AT_call_column
	.byte	13                              // Abbrev [13] 0x1fb:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	79                              // DW_AT_abstract_origin
	.byte	13                              // Abbrev [13] 0x204:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	90                              // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x20d:0x9 DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	101                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x216:0x9 DW_TAG_variable
	.long	.Ldebug_loc5                    // DW_AT_location
	.long	112                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x21f:0x9 DW_TAG_variable
	.long	.Ldebug_loc6                    // DW_AT_location
	.long	123                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x228:0x9 DW_TAG_variable
	.long	.Ldebug_loc7                    // DW_AT_location
	.long	134                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x231:0x9 DW_TAG_variable
	.long	.Ldebug_loc8                    // DW_AT_location
	.long	145                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x23a:0x9 DW_TAG_variable
	.long	.Ldebug_loc9                    // DW_AT_location
	.long	156                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x243:0x9 DW_TAG_variable
	.long	.Ldebug_loc10                   // DW_AT_location
	.long	167                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x24c:0x9 DW_TAG_variable
	.long	.Ldebug_loc11                   // DW_AT_location
	.long	178                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x255:0x9 DW_TAG_variable
	.long	.Ldebug_loc14                   // DW_AT_location
	.long	189                             // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x25e:0x5 DW_TAG_variable
	.long	200                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x263:0x9 DW_TAG_variable
	.long	.Ldebug_loc15                   // DW_AT_location
	.long	211                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x26c:0x9 DW_TAG_variable
	.long	.Ldebug_loc21                   // DW_AT_location
	.long	222                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x275:0x9 DW_TAG_variable
	.long	.Ldebug_loc22                   // DW_AT_location
	.long	233                             // DW_AT_abstract_origin
	.byte	12                              // Abbrev [12] 0x27e:0x31 DW_TAG_inlined_subroutine
	.long	404                             // DW_AT_abstract_origin
	.long	.Ldebug_ranges1                 // DW_AT_ranges
	.byte	4                               // DW_AT_call_file
	.byte	66                              // DW_AT_call_line
	.byte	37                              // DW_AT_call_column
	.byte	16                              // Abbrev [16] 0x28a:0x5 DW_TAG_formal_parameter
	.long	416                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x28f:0x9 DW_TAG_variable
	.long	.Ldebug_loc12                   // DW_AT_location
	.long	427                             // DW_AT_abstract_origin
	.byte	17                              // Abbrev [17] 0x298:0x16 DW_TAG_inlined_subroutine
	.long	380                             // DW_AT_abstract_origin
	.long	.Ltmp25                         // DW_AT_low_pc
	.long	.Ltmp27-.Ltmp25                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	251                             // DW_AT_call_line
	.byte	23                              // DW_AT_call_column
	.byte	16                              // Abbrev [16] 0x2a8:0x5 DW_TAG_formal_parameter
	.long	392                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	17                              // Abbrev [17] 0x2af:0x35 DW_TAG_inlined_subroutine
	.long	404                             // DW_AT_abstract_origin
	.long	.Ltmp47                         // DW_AT_low_pc
	.long	.Ltmp59-.Ltmp47                 // DW_AT_high_pc
	.byte	4                               // DW_AT_call_file
	.byte	67                              // DW_AT_call_line
	.byte	37                              // DW_AT_call_column
	.byte	16                              // Abbrev [16] 0x2bf:0x5 DW_TAG_formal_parameter
	.long	416                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x2c4:0x9 DW_TAG_variable
	.long	.Ldebug_loc13                   // DW_AT_location
	.long	427                             // DW_AT_abstract_origin
	.byte	17                              // Abbrev [17] 0x2cd:0x16 DW_TAG_inlined_subroutine
	.long	380                             // DW_AT_abstract_origin
	.long	.Ltmp47                         // DW_AT_low_pc
	.long	.Ltmp49-.Ltmp47                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	251                             // DW_AT_call_line
	.byte	23                              // DW_AT_call_column
	.byte	16                              // Abbrev [16] 0x2dd:0x5 DW_TAG_formal_parameter
	.long	392                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	18                              // Abbrev [18] 0x2e4:0xf DW_TAG_lexical_block
	.long	.Ldebug_ranges2                 // DW_AT_ranges
	.byte	14                              // Abbrev [14] 0x2e9:0x9 DW_TAG_variable
	.long	.Ldebug_loc16                   // DW_AT_location
	.long	245                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	19                              // Abbrev [19] 0x2f3:0xf DW_TAG_lexical_block
	.long	.Ltmp79                         // DW_AT_low_pc
	.long	.Ltmp84-.Ltmp79                 // DW_AT_high_pc
	.byte	15                              // Abbrev [15] 0x2fc:0x5 DW_TAG_variable
	.long	258                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	18                              // Abbrev [18] 0x302:0x29 DW_TAG_lexical_block
	.long	.Ldebug_ranges3                 // DW_AT_ranges
	.byte	14                              // Abbrev [14] 0x307:0x9 DW_TAG_variable
	.long	.Ldebug_loc18                   // DW_AT_location
	.long	271                             // DW_AT_abstract_origin
	.byte	17                              // Abbrev [17] 0x310:0x1a DW_TAG_inlined_subroutine
	.long	380                             // DW_AT_abstract_origin
	.long	.Ltmp101                        // DW_AT_low_pc
	.long	.Ltmp103-.Ltmp101               // DW_AT_high_pc
	.byte	4                               // DW_AT_call_file
	.byte	100                             // DW_AT_call_line
	.byte	31                              // DW_AT_call_column
	.byte	13                              // Abbrev [13] 0x320:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc17                   // DW_AT_location
	.long	392                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	19                              // Abbrev [19] 0x32b:0x1c DW_TAG_lexical_block
	.long	.Ltmp135                        // DW_AT_low_pc
	.long	.Ltmp147-.Ltmp135               // DW_AT_high_pc
	.byte	14                              // Abbrev [14] 0x334:0x9 DW_TAG_variable
	.long	.Ldebug_loc19                   // DW_AT_location
	.long	284                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x33d:0x9 DW_TAG_variable
	.long	.Ldebug_loc20                   // DW_AT_location
	.long	295                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_ranges,"",@progbits
.Ldebug_ranges0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp10-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.long	.Ltmp23-.Lfunc_begin0
	.long	.Ltmp25-.Lfunc_begin0
	.long	.Ltmp40-.Lfunc_begin0
	.long	.Ltmp43-.Lfunc_begin0
	.long	.Ltmp113-.Lfunc_begin0
	.long	.Ltmp115-.Lfunc_begin0
	.long	.Ltmp117-.Lfunc_begin0
	.long	.Ltmp120-.Lfunc_begin0
	.long	.Ltmp161-.Lfunc_begin0
	.long	.Ltmp163-.Lfunc_begin0
	.long	.Ltmp166-.Lfunc_begin0
	.long	0
	.long	0
.Ldebug_ranges1:
	.long	.Ltmp25-.Lfunc_begin0
	.long	.Ltmp32-.Lfunc_begin0
	.long	.Ltmp43-.Lfunc_begin0
	.long	.Ltmp46-.Lfunc_begin0
	.long	0
	.long	0
.Ldebug_ranges2:
	.long	.Ltmp66-.Lfunc_begin0
	.long	.Ltmp70-.Lfunc_begin0
	.long	.Ltmp87-.Lfunc_begin0
	.long	.Ltmp93-.Lfunc_begin0
	.long	0
	.long	0
.Ldebug_ranges3:
	.long	.Ltmp101-.Lfunc_begin0
	.long	.Ltmp109-.Lfunc_begin0
	.long	.Ltmp125-.Lfunc_begin0
	.long	.Ltmp131-.Lfunc_begin0
	.long	0
	.long	0
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/adddf3.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=152
.Linfo_string3:
	.asciz	"long unsigned int"             // string offset=173
.Linfo_string4:
	.asciz	"uint64_t"                      // string offset=191
.Linfo_string5:
	.asciz	"rep_t"                         // string offset=200
.Linfo_string6:
	.asciz	"__addXf3__"                    // string offset=206
.Linfo_string7:
	.asciz	"double"                        // string offset=217
.Linfo_string8:
	.asciz	"fp_t"                          // string offset=224
.Linfo_string9:
	.asciz	"a"                             // string offset=229
.Linfo_string10:
	.asciz	"b"                             // string offset=231
.Linfo_string11:
	.asciz	"aRep"                          // string offset=233
.Linfo_string12:
	.asciz	"bRep"                          // string offset=238
.Linfo_string13:
	.asciz	"aAbs"                          // string offset=243
.Linfo_string14:
	.asciz	"bAbs"                          // string offset=248
.Linfo_string15:
	.asciz	"bExponent"                     // string offset=253
.Linfo_string16:
	.asciz	"int"                           // string offset=263
.Linfo_string17:
	.asciz	"bSignificand"                  // string offset=267
.Linfo_string18:
	.asciz	"aSignificand"                  // string offset=280
.Linfo_string19:
	.asciz	"aExponent"                     // string offset=293
.Linfo_string20:
	.asciz	"resultSign"                    // string offset=303
.Linfo_string21:
	.asciz	"subtraction"                   // string offset=314
.Linfo_string22:
	.asciz	"_Bool"                         // string offset=326
.Linfo_string23:
	.asciz	"align"                         // string offset=332
.Linfo_string24:
	.asciz	"unsigned int"                  // string offset=338
.Linfo_string25:
	.asciz	"result"                        // string offset=351
.Linfo_string26:
	.asciz	"roundGuardSticky"              // string offset=358
.Linfo_string27:
	.asciz	"sticky"                        // string offset=375
.Linfo_string28:
	.asciz	"shift"                         // string offset=382
.Linfo_string29:
	.asciz	"temp"                          // string offset=388
.Linfo_string30:
	.asciz	"rep_clz"                       // string offset=393
.Linfo_string31:
	.asciz	"normalize"                     // string offset=401
.Linfo_string32:
	.asciz	"significand"                   // string offset=411
.Linfo_string33:
	.asciz	"__adddf3"                      // string offset=423
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
