	.text
	.file	"addsf3.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/stdint.h"
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/fp_lib.h"
	.section	.text.__addsf3,"ax",@progbits
	.globl	__addsf3                        // -- Begin function __addsf3
	.type	__addsf3,@function
__addsf3:                               // @__addsf3
.Lfunc_begin0:
	.file	3 "/root" "uPIMulator_frontend/sdk/syslib/addsf3.c"
	.loc	3 20 0                          // uPIMulator_frontend/sdk/syslib/addsf3.c:20:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __addsf3:a <- $r0
	//DEBUG_VALUE: __addsf3:a <- $r0
	//DEBUG_VALUE: __addsf3:b <- $r1
	//DEBUG_VALUE: __addsf3:b <- $r1
	//DEBUG_VALUE: __addXf3__:a <- $r0
	//DEBUG_VALUE: __addXf3__:a <- $r0
	//DEBUG_VALUE: __addXf3__:b <- $r1
	//DEBUG_VALUE: __addXf3__:b <- $r1
	//DEBUG_VALUE: toRep:x <- $r0
	//DEBUG_VALUE: toRep:x <- $r0
	//DEBUG_VALUE: toRep:x <- undef
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: toRep:rep <- $r0
	//DEBUG_VALUE: toRep:rep <- $r0
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: __addXf3__:bRep <- $r1
	.file	4 "/root" "uPIMulator_frontend/sdk/syslib/fp_add_impl.inc"
	.loc	4 20 29 prologue_end            // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:20:29
	and r3, r0, 2147483647
.Ltmp0:
	//DEBUG_VALUE: __addXf3__:aAbs <- $r3
	.loc	4 24 14                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:24:14
	add r2, r3, -1
	move r5, 2139095038
.Ltmp1:
	.loc	4 21 29                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:21:29
	and r4, r1, 2147483647
.Ltmp2:
	//DEBUG_VALUE: __addXf3__:bAbs <- $r4
	.loc	4 24 46                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:24:46
	jgtu r2, r5, .LBB0_2
.Ltmp3:
// %bb.1:
	//DEBUG_VALUE: __addXf3__:bAbs <- $r4
	//DEBUG_VALUE: __addXf3__:aAbs <- $r3
	//DEBUG_VALUE: __addXf3__:bRep <- $r1
	//DEBUG_VALUE: __addXf3__:b <- $r1
	//DEBUG_VALUE: __addsf3:b <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	//DEBUG_VALUE: __addXf3__:a <- $r0
	//DEBUG_VALUE: __addsf3:a <- $r0
	.loc	4 0 46 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:46
	add r2, r4, -1
	move r5, 2139095039
	.loc	4 24 46                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:24:46
	jgeu r2, r5, .LBB0_2
.Ltmp4:
.LBB0_15:
	//DEBUG_VALUE: __addXf3__:bAbs <- $r4
	//DEBUG_VALUE: __addXf3__:aAbs <- $r3
	//DEBUG_VALUE: __addXf3__:bRep <- $r1
	//DEBUG_VALUE: __addXf3__:b <- $r1
	//DEBUG_VALUE: __addsf3:b <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	//DEBUG_VALUE: __addXf3__:a <- $r0
	//DEBUG_VALUE: __addsf3:a <- $r0
	.loc	4 53 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:53:9
	jleu r4, r3, .LBB0_17
.Ltmp5:
// %bb.16:
	//DEBUG_VALUE: __addXf3__:bAbs <- $r4
	//DEBUG_VALUE: __addXf3__:aAbs <- $r3
	//DEBUG_VALUE: __addXf3__:bRep <- $r1
	//DEBUG_VALUE: __addXf3__:b <- $r1
	//DEBUG_VALUE: __addsf3:b <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	//DEBUG_VALUE: __addXf3__:a <- $r0
	//DEBUG_VALUE: __addsf3:a <- $r0
	move r2, r0
	move r0, r1, true, .LBB0_18
.Ltmp6:
.LBB0_2:
	//DEBUG_VALUE: __addXf3__:bAbs <- $r4
	//DEBUG_VALUE: __addXf3__:aAbs <- $r3
	//DEBUG_VALUE: __addXf3__:bRep <- $r1
	//DEBUG_VALUE: __addXf3__:b <- $r1
	//DEBUG_VALUE: __addsf3:b <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	//DEBUG_VALUE: __addXf3__:a <- $r0
	//DEBUG_VALUE: __addsf3:a <- $r0
	.loc	4 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:9
	move r2, 2139095041
.Ltmp7:
	.loc	4 27 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:27:13
	jltu r3, r2, .LBB0_4
.Ltmp8:
// %bb.3:
	//DEBUG_VALUE: __addXf3__:bAbs <- $r4
	//DEBUG_VALUE: __addXf3__:aAbs <- $r3
	//DEBUG_VALUE: __addXf3__:bRep <- $r1
	//DEBUG_VALUE: __addXf3__:b <- $r1
	//DEBUG_VALUE: __addsf3:b <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	//DEBUG_VALUE: __addXf3__:a <- $r0
	//DEBUG_VALUE: __addsf3:a <- $r0
	//DEBUG_VALUE: toRep:x <- $r0
	//DEBUG_VALUE: toRep:rep <- $r0
	.loc	4 27 52 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:27:52
	or r2, r0, 4194304
.Ltmp9:
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $r2
	.loc	3 21 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/addsf3.c:21:5
	move r0, r2
.Ltmp10:
	jump r23
.Ltmp11:
.LBB0_17:
	//DEBUG_VALUE: __addXf3__:bAbs <- $r4
	//DEBUG_VALUE: __addXf3__:aAbs <- $r3
	//DEBUG_VALUE: __addXf3__:bRep <- $r1
	//DEBUG_VALUE: __addXf3__:b <- $r1
	//DEBUG_VALUE: __addsf3:b <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	//DEBUG_VALUE: __addXf3__:a <- $r0
	//DEBUG_VALUE: __addsf3:a <- $r0
	.loc	4 53 9                          // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:53:9
	move r2, r1
.Ltmp12:
.LBB0_18:
	//DEBUG_VALUE: __addXf3__:bAbs <- $r4
	//DEBUG_VALUE: __addXf3__:aAbs <- $r3
	//DEBUG_VALUE: __addXf3__:bRep <- $r1
	//DEBUG_VALUE: __addXf3__:b <- $r1
	//DEBUG_VALUE: __addsf3:b <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	//DEBUG_VALUE: __addXf3__:bRep <- $r2
	.loc	4 60 26                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:60:26
	lsr r1, r0, 23
.Ltmp13:
	.loc	4 61 26                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:61:26
	lsr r3, r2, 23
.Ltmp14:
	//DEBUG_VALUE: __addXf3__:bExponent <- undef
	.loc	4 62 31                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:62:31
	and r4, r0, 8388607
.Ltmp15:
	//DEBUG_VALUE: __addXf3__:bSignificand <- undef
	//DEBUG_VALUE: __addXf3__:aSignificand <- $r4
	.loc	4 66 9                          // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:66:9
	clz r7, r4
	.loc	4 60 45                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:60:45
	and r1, r1, 255
.Ltmp16:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	.loc	4 66 9                          // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:66:9
	jeq r1, 0, .LBB0_19
.Ltmp17:
// %bb.20:
	//DEBUG_VALUE: __addXf3__:aSignificand <- $r4
	//DEBUG_VALUE: __addXf3__:bRep <- $r2
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	.loc	4 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:9
	move r5, 0
	and r3, r3, 255
.Ltmp18:
	//DEBUG_VALUE: __addXf3__:bExponent <- $r3
	and r6, r2, 8388607
.Ltmp19:
	//DEBUG_VALUE: __addXf3__:bSignificand <- $r6
	.loc	4 66 9                          // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:66:9
	jeq r1, 0, .LBB0_22
.Ltmp20:
.LBB0_23:
	//DEBUG_VALUE: __addXf3__:bSignificand <- $r6
	//DEBUG_VALUE: __addXf3__:aSignificand <- $r4
	//DEBUG_VALUE: __addXf3__:bExponent <- $r3
	//DEBUG_VALUE: __addXf3__:bRep <- $r2
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	.loc	4 67 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:67:9
	clz r7, r6
	jeq r3, 0, .LBB0_24
.Ltmp21:
.LBB0_25:
	//DEBUG_VALUE: __addXf3__:bSignificand <- $r6
	//DEBUG_VALUE: __addXf3__:aSignificand <- $r4
	//DEBUG_VALUE: __addXf3__:bExponent <- $r3
	//DEBUG_VALUE: __addXf3__:bRep <- $r2
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	.loc	4 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:9
	move r8, 0
	lsl r4, r4, r5
.Ltmp22:
	.loc	4 67 9                          // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:67:9
	lsl r5, r6, r8
	jneq r3, 0, .LBB0_28
.Ltmp23:
.LBB0_27:
	//DEBUG_VALUE: __addXf3__:bSignificand <- $r6
	//DEBUG_VALUE: __addXf3__:bExponent <- $r3
	//DEBUG_VALUE: __addXf3__:bRep <- $r2
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	.loc	4 0 9                           // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:9
	sub r3, 9, r7
.Ltmp24:
.LBB0_28:
	//DEBUG_VALUE: __addXf3__:bSignificand <- $r6
	//DEBUG_VALUE: __addXf3__:bRep <- $r2
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	//DEBUG_VALUE: __addXf3__:bExponent <- $r3
	//DEBUG_VALUE: __addXf3__:resultSign <- undef
	.loc	4 72 36 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:72:36
	xor r2, r0, r2
.Ltmp25:
	//DEBUG_VALUE: __addXf3__:subtraction <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] undef
	//DEBUG_VALUE: __addXf3__:aSignificand <- $r4
	.loc	4 78 49                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:78:49
	lsl r4, r4, 3
.Ltmp26:
	//DEBUG_VALUE: __addXf3__:bSignificand <- $r5
	//DEBUG_VALUE: __addXf3__:aSignificand <- undef
	.loc	4 79 49                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:79:49
	lsl r5, r5, 3
.Ltmp27:
	or r5, r5, 67108864
.Ltmp28:
	//DEBUG_VALUE: __addXf3__:bSignificand <- $r5
	//DEBUG_VALUE: __addXf3__:align <- $r6
	.loc	4 83 42                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:83:42
	sub r6, r1, r3, z, .LBB0_29
.Ltmp29:
// %bb.30:
	//DEBUG_VALUE: __addXf3__:bSignificand <- $r5
	//DEBUG_VALUE: __addXf3__:bExponent <- $r3
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	.loc	4 0 42 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:42
	move r3, 1
.Ltmp30:
	.loc	4 85 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:85:13
	jgtu r6, 31, .LBB0_32
.Ltmp31:
// %bb.31:
	//DEBUG_VALUE: __addXf3__:bSignificand <- $r5
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	.loc	4 86 60                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:86:60
	sub r3, 32, r6
	.loc	4 86 46 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:86:46
	lsl r3, r5, r3
	move r7, 0
	.loc	4 86 33                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:86:33
	sub r3, r3, r7, neq
.Ltmp32:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] $r3
	.loc	4 87 41 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:87:41
	lsr r5, r5, r6
.Ltmp33:
	.loc	4 87 50 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:87:50
	or r3, r5, r3
.Ltmp34:
	//DEBUG_VALUE: __addXf3__:bSignificand <- $r3
.LBB0_32:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	//DEBUG_VALUE: __addXf3__:resultSign <- undef
	.loc	4 0 0                           // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:0
	or r4, r4, 67108864
.Ltmp35:
	//DEBUG_VALUE: __addXf3__:bSignificand <- $r3
	//DEBUG_VALUE: __addXf3__:aSignificand <- $r4
	.loc	4 92 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:92:9
	jles r2, -1, .LBB0_33
.Ltmp36:
.LBB0_37:
	//DEBUG_VALUE: __addXf3__:aSignificand <- $r4
	//DEBUG_VALUE: __addXf3__:bSignificand <- $r3
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	.loc	4 106 22                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:106:22
	add r2, r3, r4
.Ltmp37:
	//DEBUG_VALUE: __addXf3__:aSignificand <- $r2
	.loc	4 110 26                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:110:26
	and r3, r2, 134217728
.Ltmp38:
	.loc	4 110 13 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:110:13
	jeq r3, 0, .LBB0_39
.Ltmp39:
// %bb.38:
	//DEBUG_VALUE: __addXf3__:aSignificand <- $r2
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	.loc	4 111 46 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:111:46
	and r3, r2, 1
.Ltmp40:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] undef
	.loc	4 112 41                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:112:41
	lsr r2, r2, 1
.Ltmp41:
	.loc	4 112 46 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:112:46
	or r2, r2, r3
.Ltmp42:
	//DEBUG_VALUE: __addXf3__:aSignificand <- $r2
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	.loc	4 113 23 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:113:23
	add r1, r1, 1, true, .LBB0_39
.Ltmp43:
.LBB0_4:
	//DEBUG_VALUE: __addXf3__:bAbs <- $r4
	//DEBUG_VALUE: __addXf3__:aAbs <- $r3
	//DEBUG_VALUE: __addXf3__:bRep <- $r1
	//DEBUG_VALUE: __addXf3__:b <- $r1
	//DEBUG_VALUE: __addsf3:b <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	//DEBUG_VALUE: __addXf3__:a <- $r0
	//DEBUG_VALUE: __addsf3:a <- $r0
	.loc	4 29 13                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:29:13
	jltu r4, r2, .LBB0_6
.Ltmp44:
// %bb.5:
	//DEBUG_VALUE: __addXf3__:bAbs <- $r4
	//DEBUG_VALUE: __addXf3__:aAbs <- $r3
	//DEBUG_VALUE: __addXf3__:bRep <- $r1
	//DEBUG_VALUE: __addXf3__:b <- $r1
	//DEBUG_VALUE: __addsf3:b <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	//DEBUG_VALUE: __addXf3__:a <- $r0
	//DEBUG_VALUE: __addsf3:a <- $r0
	//DEBUG_VALUE: toRep:x <- $r1
	//DEBUG_VALUE: toRep:rep <- $r1
	.loc	4 29 52 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:29:52
	or r2, r1, 4194304
.Ltmp45:
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $r2
	.loc	3 21 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/addsf3.c:21:5
	move r0, r2
.Ltmp46:
	jump r23
.Ltmp47:
.LBB0_19:
	//DEBUG_VALUE: __addXf3__:aSignificand <- $r4
	//DEBUG_VALUE: __addXf3__:bRep <- $r2
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	.loc	3 0 5 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/addsf3.c:0:5
	add r5, r7, -8
	and r3, r3, 255
.Ltmp48:
	//DEBUG_VALUE: __addXf3__:bExponent <- $r3
	and r6, r2, 8388607
.Ltmp49:
	//DEBUG_VALUE: __addXf3__:bSignificand <- $r6
	.loc	4 66 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:66:9
	jneq r1, 0, .LBB0_23
.Ltmp50:
.LBB0_22:
	//DEBUG_VALUE: __addXf3__:bSignificand <- $r6
	//DEBUG_VALUE: __addXf3__:aSignificand <- $r4
	//DEBUG_VALUE: __addXf3__:bExponent <- $r3
	//DEBUG_VALUE: __addXf3__:bRep <- $r2
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	.loc	4 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:9
	sub r1, 9, r7
.Ltmp51:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	.loc	4 67 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:67:9
	clz r7, r6
	jneq r3, 0, .LBB0_25
.Ltmp52:
.LBB0_24:
	//DEBUG_VALUE: __addXf3__:bSignificand <- $r6
	//DEBUG_VALUE: __addXf3__:aSignificand <- $r4
	//DEBUG_VALUE: __addXf3__:bExponent <- $r3
	//DEBUG_VALUE: __addXf3__:bRep <- $r2
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	.loc	4 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:9
	add r8, r7, -8
	lsl r4, r4, r5
.Ltmp53:
	.loc	4 67 9                          // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:67:9
	lsl r5, r6, r8
	jneq r3, 0, .LBB0_28
	jump .LBB0_27
.Ltmp54:
.LBB0_29:
	//DEBUG_VALUE: __addXf3__:bSignificand <- $r5
	//DEBUG_VALUE: __addXf3__:bExponent <- $r3
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	.loc	4 0 0                           // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:0
	move r3, r5
.Ltmp55:
	//DEBUG_VALUE: __addXf3__:resultSign <- undef
	or r4, r4, 67108864
.Ltmp56:
	//DEBUG_VALUE: __addXf3__:bSignificand <- $r3
	//DEBUG_VALUE: __addXf3__:aSignificand <- $r4
	.loc	4 92 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:92:9
	jgts r2, -1, .LBB0_37
.Ltmp57:
.LBB0_33:
	//DEBUG_VALUE: __addXf3__:aSignificand <- $r4
	//DEBUG_VALUE: __addXf3__:bSignificand <- $r3
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	//DEBUG_VALUE: __addXf3__:aSignificand <- $r2
	.loc	4 93 22                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:93:22
	sub r2, r4, r3, z, .LBB0_34
.Ltmp58:
// %bb.35:
	//DEBUG_VALUE: __addXf3__:bSignificand <- $r3
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	.loc	4 99 13                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:99:13
	lsr r3, r2, 26, nz, .LBB0_39
.Ltmp59:
// %bb.36:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	//DEBUG_VALUE: rep_clz:a <- $r2
	.loc	2 52 12                         // uPIMulator_frontend/sdk/syslib/fp_lib.h:52:12
	clz r3, r2
.Ltmp60:
	//DEBUG_VALUE: rep_clz:a <- 67108864
	.loc	4 100 53                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:100:53
	add r3, r3, -5
.Ltmp61:
	//DEBUG_VALUE: shift <- $r3
	//DEBUG_VALUE: __addXf3__:aSignificand <- $r2
	.loc	4 101 26                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:101:26
	lsl r2, r2, r3
.Ltmp62:
	//DEBUG_VALUE: __addXf3__:aSignificand <- $r2
	.loc	4 102 23                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:102:23
	sub r1, r1, r3
.Ltmp63:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
.LBB0_39:
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	.loc	4 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:0
	and r0, r0, -2147483648
.Ltmp64:
	//DEBUG_VALUE: __addXf3__:resultSign <- $r0
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	.loc	4 118 9 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:118:9
	jlts r1, 255, .LBB0_41
.Ltmp65:
// %bb.40:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	//DEBUG_VALUE: __addXf3__:resultSign <- $r0
	.loc	4 118 57 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:118:57
	or r2, r0, 2139095040
.Ltmp66:
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $r2
	.loc	3 21 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/addsf3.c:21:5
	move r0, r2
.Ltmp67:
	jump r23
.Ltmp68:
.LBB0_41:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	//DEBUG_VALUE: __addXf3__:resultSign <- $r0
	.loc	4 120 9                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:120:9
	jgts r1, 0, .LBB0_43
.Ltmp69:
// %bb.42:
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	//DEBUG_VALUE: __addXf3__:resultSign <- $r0
	.loc	4 123 29                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:123:29
	sub r3, 1, r1
.Ltmp70:
	//DEBUG_VALUE: shift <- $r3
	//DEBUG_VALUE: __addXf3__:aSignificand <- $r2
	.loc	4 124 56                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:124:56
	add r1, r1, 31
.Ltmp71:
	.loc	4 124 42 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:124:42
	lsl r4, r2, r1
	move r1, 0
	.loc	4 124 29                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:124:29
	sub r4, r4, r1, neq
.Ltmp72:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] $r4
	.loc	4 125 37 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:125:37
	lsr r2, r2, r3
.Ltmp73:
	.loc	4 125 46 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:125:46
	or r2, r2, r4
.Ltmp74:
	//DEBUG_VALUE: __addXf3__:aExponent <- 0
	//DEBUG_VALUE: __addXf3__:aSignificand <- $r2
.LBB0_43:
	//DEBUG_VALUE: __addXf3__:resultSign <- $r0
	//DEBUG_VALUE: __addXf3__:aSignificand <- $r2
	//DEBUG_VALUE: __addXf3__:aExponent <- $r1
	.loc	4 133 33 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:133:33
	lsr r3, r2, 3
	.loc	4 133 38 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:133:38
	and r3, r3, 8388607
.Ltmp75:
	//DEBUG_VALUE: __addXf3__:result <- $r3
	.loc	4 136 32 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:136:32
	lsl r1, r1, 23
.Ltmp76:
	//DEBUG_VALUE: __addXf3__:result <- undef
	.loc	4 136 12 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:136:12
	or r0, r1, r0
.Ltmp77:
	.loc	4 137 12 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:137:12
	or r0, r0, r3
.Ltmp78:
	//DEBUG_VALUE: __addXf3__:result <- $r0
	.loc	4 0 12 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:12
	move r1, 4
	.loc	4 130 47 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:130:47
	and r2, r2, 7
.Ltmp79:
	//DEBUG_VALUE: __addXf3__:roundGuardSticky <- $r2
	.loc	4 141 26                        // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:141:26
	sub r1, r2, r1, gtu
.Ltmp80:
	.loc	4 141 9 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:141:9
	add r0, r0, r1
.Ltmp81:
	//DEBUG_VALUE: __addXf3__:result <- $r0
	.loc	4 142 9 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:142:9
	and r1, r0, 1
	jeq r2, 4, .LBB0_45
.Ltmp82:
// %bb.44:
	//DEBUG_VALUE: __addXf3__:roundGuardSticky <- $r2
	//DEBUG_VALUE: __addXf3__:result <- $r0
	.loc	4 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:9
	move r1, 0
.Ltmp83:
.LBB0_45:
	//DEBUG_VALUE: __addXf3__:roundGuardSticky <- $r2
	//DEBUG_VALUE: __addXf3__:result <- $r0
	.loc	4 142 9                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:142:9
	add r2, r1, r0
.Ltmp84:
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $r2
	//DEBUG_VALUE: __addXf3__:result <- $r2
.LBB0_46:
	.loc	3 21 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/addsf3.c:21:5
	move r0, r2
	jump r23
.LBB0_6:
.Ltmp85:
	//DEBUG_VALUE: __addXf3__:bAbs <- $r4
	//DEBUG_VALUE: __addXf3__:aAbs <- $r3
	//DEBUG_VALUE: __addXf3__:bRep <- $r1
	//DEBUG_VALUE: __addXf3__:b <- $r1
	//DEBUG_VALUE: __addsf3:b <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	//DEBUG_VALUE: __addXf3__:a <- $r0
	//DEBUG_VALUE: __addsf3:a <- $r0
	.loc	3 0 5 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/addsf3.c:0:5
	move r2, 2139095040
.Ltmp86:
	.loc	4 31 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:31:13
	jneq r3, r2, .LBB0_9
.Ltmp87:
// %bb.7:
	//DEBUG_VALUE: __addXf3__:bAbs <- $r4
	//DEBUG_VALUE: __addXf3__:aAbs <- $r3
	//DEBUG_VALUE: __addXf3__:bRep <- $r1
	//DEBUG_VALUE: __addXf3__:b <- $r1
	//DEBUG_VALUE: __addsf3:b <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	//DEBUG_VALUE: __addXf3__:a <- $r0
	//DEBUG_VALUE: __addsf3:a <- $r0
	//DEBUG_VALUE: toRep:x <- $r0
	//DEBUG_VALUE: toRep:rep <- $r0
	//DEBUG_VALUE: toRep:x <- $r1
	//DEBUG_VALUE: toRep:rep <- $r1
	.loc	4 33 27                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:33:27
	xor r1, r1, r0
.Ltmp88:
	.loc	4 0 27 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:27
	move r3, -2147483648
.Ltmp89:
	move r2, 2143289344
.Ltmp90:
	.loc	4 33 17                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:33:17
	jeq r1, r3, .LBB0_46
.Ltmp91:
// %bb.8:
	//DEBUG_VALUE: __addsf3:a <- $r0
	.loc	3 21 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/addsf3.c:21:5
	jump r23
.Ltmp92:
.LBB0_34:
	.loc	3 0 5 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/addsf3.c:0:5
	move r2, 0
	.loc	3 21 5                          // uPIMulator_frontend/sdk/syslib/addsf3.c:21:5
	move r0, r2
	jump r23
.LBB0_9:
.Ltmp93:
	//DEBUG_VALUE: __addXf3__:bAbs <- $r4
	//DEBUG_VALUE: __addXf3__:aAbs <- $r3
	//DEBUG_VALUE: __addXf3__:bRep <- $r1
	//DEBUG_VALUE: __addXf3__:b <- $r1
	//DEBUG_VALUE: __addsf3:b <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	//DEBUG_VALUE: __addXf3__:a <- $r0
	//DEBUG_VALUE: __addsf3:a <- $r0
	.loc	4 39 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:39:13
	jneq r4, r2, .LBB0_11
.Ltmp94:
// %bb.10:
	//DEBUG_VALUE: __addsf3:b <- $r1
	//DEBUG_VALUE: __addsf3:a <- $r0
	.loc	4 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:13
	move r2, r1
	.loc	3 21 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/addsf3.c:21:5
	move r0, r2
.Ltmp95:
	jump r23
.Ltmp96:
.LBB0_11:
	//DEBUG_VALUE: __addXf3__:bAbs <- $r4
	//DEBUG_VALUE: __addXf3__:aAbs <- $r3
	//DEBUG_VALUE: __addXf3__:bRep <- $r1
	//DEBUG_VALUE: __addXf3__:b <- $r1
	//DEBUG_VALUE: __addsf3:b <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	//DEBUG_VALUE: __addXf3__:a <- $r0
	//DEBUG_VALUE: __addsf3:a <- $r0
	.loc	4 42 13                         // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:42:13
	jeq r3, 0, .LBB0_12
.Ltmp97:
// %bb.14:
	//DEBUG_VALUE: __addXf3__:bAbs <- $r4
	//DEBUG_VALUE: __addXf3__:aAbs <- $r3
	//DEBUG_VALUE: __addXf3__:bRep <- $r1
	//DEBUG_VALUE: __addXf3__:b <- $r1
	//DEBUG_VALUE: __addsf3:b <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	//DEBUG_VALUE: __addXf3__:a <- $r0
	//DEBUG_VALUE: __addsf3:a <- $r0
	.loc	4 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:13
	move r2, r0
	.loc	4 49 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:49:13
	jneq r4, 0, .LBB0_15
	jump .LBB0_46
.Ltmp98:
.LBB0_12:
	//DEBUG_VALUE: __addXf3__:bAbs <- $r4
	//DEBUG_VALUE: __addXf3__:aAbs <- $r3
	//DEBUG_VALUE: __addXf3__:bRep <- $r1
	//DEBUG_VALUE: __addXf3__:b <- $r1
	//DEBUG_VALUE: __addsf3:b <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	//DEBUG_VALUE: __addXf3__:a <- $r0
	//DEBUG_VALUE: __addsf3:a <- $r0
	.loc	4 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:0:13
	move r2, r1
.Ltmp99:
	.loc	4 44 17 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:44:17
	jneq r4, 0, .LBB0_46
.Ltmp100:
// %bb.13:
	//DEBUG_VALUE: __addXf3__:bAbs <- $r4
	//DEBUG_VALUE: __addXf3__:aAbs <- $r3
	//DEBUG_VALUE: __addXf3__:bRep <- $r1
	//DEBUG_VALUE: __addXf3__:b <- $r1
	//DEBUG_VALUE: __addsf3:b <- $r1
	//DEBUG_VALUE: __addXf3__:aRep <- $r0
	//DEBUG_VALUE: __addXf3__:a <- $r0
	//DEBUG_VALUE: __addsf3:a <- $r0
	//DEBUG_VALUE: toRep:x <- $r0
	//DEBUG_VALUE: toRep:rep <- $r0
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: toRep:rep <- undef
	.loc	4 44 48 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_add_impl.inc:44:48
	and r2, r1, r0
.Ltmp101:
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $r2
	.loc	3 21 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/addsf3.c:21:5
	move r0, r2
.Ltmp102:
	jump r23
.Ltmp103:
.Lfunc_end0:
	.size	__addsf3, .Lfunc_end0-__addsf3
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__addsf3
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.__addsf3,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp10-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp11-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp43-.Lfunc_begin0
	.long	.Ltmp46-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp85-.Lfunc_begin0
	.long	.Ltmp92-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp93-.Lfunc_begin0
	.long	.Ltmp95-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp96-.Lfunc_begin0
	.long	.Ltmp102-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp13-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp43-.Lfunc_begin0
	.long	.Ltmp47-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp85-.Lfunc_begin0
	.long	.Ltmp88-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp93-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp10-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp11-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp43-.Lfunc_begin0
	.long	.Ltmp46-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp85-.Lfunc_begin0
	.long	.Ltmp91-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp93-.Lfunc_begin0
	.long	.Ltmp94-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp96-.Lfunc_begin0
	.long	.Ltmp102-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp13-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp43-.Lfunc_begin0
	.long	.Ltmp47-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp85-.Lfunc_begin0
	.long	.Ltmp88-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp93-.Lfunc_begin0
	.long	.Ltmp94-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp96-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc4:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp10-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp11-.Lfunc_begin0
	.long	.Ltmp46-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp47-.Lfunc_begin0
	.long	.Ltmp64-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp85-.Lfunc_begin0
	.long	.Ltmp91-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp93-.Lfunc_begin0
	.long	.Ltmp94-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp96-.Lfunc_begin0
	.long	.Ltmp102-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc5:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp12-.Lfunc_begin0
	.long	.Ltmp25-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp43-.Lfunc_begin0
	.long	.Ltmp47-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp47-.Lfunc_begin0
	.long	.Ltmp54-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp85-.Lfunc_begin0
	.long	.Ltmp88-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp93-.Lfunc_begin0
	.long	.Ltmp94-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp96-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc6:
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp14-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp43-.Lfunc_begin0
	.long	.Ltmp47-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp85-.Lfunc_begin0
	.long	.Ltmp89-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp93-.Lfunc_begin0
	.long	.Ltmp94-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp96-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc7:
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp15-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp43-.Lfunc_begin0
	.long	.Ltmp47-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp85-.Lfunc_begin0
	.long	.Ltmp91-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp93-.Lfunc_begin0
	.long	.Ltmp94-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp96-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	0
	.long	0
.Ldebug_loc8:
	.long	.Ltmp18-.Lfunc_begin0
	.long	.Ltmp30-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp48-.Lfunc_begin0
	.long	.Ltmp55-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc9:
	.long	.Ltmp19-.Lfunc_begin0
	.long	.Ltmp26-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	86                              // DW_OP_reg6
	.long	.Ltmp26-.Lfunc_begin0
	.long	.Ltmp27-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp28-.Lfunc_begin0
	.long	.Ltmp33-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp35-.Lfunc_begin0
	.long	.Ltmp38-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp49-.Lfunc_begin0
	.long	.Ltmp54-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	86                              // DW_OP_reg6
	.long	.Ltmp54-.Lfunc_begin0
	.long	.Ltmp56-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp56-.Lfunc_begin0
	.long	.Ltmp59-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc10:
	.long	.Ltmp15-.Lfunc_begin0
	.long	.Ltmp22-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp25-.Lfunc_begin0
	.long	.Ltmp26-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp35-.Lfunc_begin0
	.long	.Ltmp37-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp37-.Lfunc_begin0
	.long	.Ltmp41-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp42-.Lfunc_begin0
	.long	.Ltmp43-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp47-.Lfunc_begin0
	.long	.Ltmp53-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp56-.Lfunc_begin0
	.long	.Ltmp57-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp57-.Lfunc_begin0
	.long	.Ltmp58-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp61-.Lfunc_begin0
	.long	.Ltmp63-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp70-.Lfunc_begin0
	.long	.Ltmp73-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp74-.Lfunc_begin0
	.long	.Ltmp79-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc11:
	.long	.Ltmp16-.Lfunc_begin0
	.long	.Ltmp43-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp47-.Lfunc_begin0
	.long	.Ltmp63-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp64-.Lfunc_begin0
	.long	.Ltmp71-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp74-.Lfunc_begin0
	.long	.Ltmp76-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc12:
	.long	.Ltmp64-.Lfunc_begin0
	.long	.Ltmp67-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp68-.Lfunc_begin0
	.long	.Ltmp77-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc13:
	.long	.Ltmp28-.Lfunc_begin0
	.long	.Ltmp29-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	86                              // DW_OP_reg6
	.long	0
	.long	0
.Ldebug_loc14:
	.long	.Ltmp32-.Lfunc_begin0
	.long	.Ltmp34-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	115                             // DW_OP_breg3
	.byte	0                               // 0
	.byte	16                              // DW_OP_constu
	.byte	1                               // 1
	.byte	26                              // DW_OP_and
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc15:
	.long	.Ltmp61-.Lfunc_begin0
	.long	.Ltmp63-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc16:
	.long	.Ltmp70-.Lfunc_begin0
	.long	.Ltmp74-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc17:
	.long	.Ltmp72-.Lfunc_begin0
	.long	.Ltmp74-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	116                             // DW_OP_breg4
	.byte	0                               // 0
	.byte	16                              // DW_OP_constu
	.byte	1                               // 1
	.byte	26                              // DW_OP_and
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc18:
	.long	.Ltmp75-.Lfunc_begin0
	.long	.Ltmp76-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp78-.Lfunc_begin0
	.long	.Ltmp84-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc19:
	.long	.Ltmp79-.Lfunc_begin0
	.long	.Ltmp84-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	11                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	1                               // DW_CHILDREN_yes
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	12                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	13                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	14                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	15                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	16                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	1                               // DW_CHILDREN_yes
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	17                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x2b0 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0xb DW_TAG_typedef
	.long	49                              // DW_AT_type
	.long	.Linfo_string5                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	43                              // DW_AT_decl_line
	.byte	2                               // Abbrev [2] 0x31:0xb DW_TAG_typedef
	.long	60                              // DW_AT_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	48                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x3c:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x43:0xfe DW_TAG_subprogram
	.long	.Linfo_string6                  // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	17                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	321                             // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0x4f:0xb DW_TAG_formal_parameter
	.long	.Linfo_string9                  // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	17                              // DW_AT_decl_line
	.long	321                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0x5a:0xb DW_TAG_formal_parameter
	.long	.Linfo_string10                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	17                              // DW_AT_decl_line
	.long	321                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x65:0xb DW_TAG_variable
	.long	.Linfo_string11                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	18                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0x70:0xb DW_TAG_variable
	.long	.Linfo_string12                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	19                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0x7b:0xb DW_TAG_variable
	.long	.Linfo_string13                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	20                              // DW_AT_decl_line
	.long	339                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x86:0xb DW_TAG_variable
	.long	.Linfo_string14                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	21                              // DW_AT_decl_line
	.long	339                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x91:0xb DW_TAG_variable
	.long	.Linfo_string15                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	61                              // DW_AT_decl_line
	.long	344                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x9c:0xb DW_TAG_variable
	.long	.Linfo_string17                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	63                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0xa7:0xb DW_TAG_variable
	.long	.Linfo_string18                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	62                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0xb2:0xb DW_TAG_variable
	.long	.Linfo_string19                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	60                              // DW_AT_decl_line
	.long	344                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xbd:0xb DW_TAG_variable
	.long	.Linfo_string20                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	71                              // DW_AT_decl_line
	.long	339                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xc8:0xb DW_TAG_variable
	.long	.Linfo_string21                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	72                              // DW_AT_decl_line
	.long	351                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xd3:0xb DW_TAG_variable
	.long	.Linfo_string23                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	83                              // DW_AT_decl_line
	.long	363                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xde:0xb DW_TAG_variable
	.long	.Linfo_string24                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	133                             // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0xe9:0xb DW_TAG_variable
	.long	.Linfo_string25                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	130                             // DW_AT_decl_line
	.long	368                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0xf4:0xd DW_TAG_lexical_block
	.byte	6                               // Abbrev [6] 0xf5:0xb DW_TAG_variable
	.long	.Linfo_string26                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	86                              // DW_AT_decl_line
	.long	351                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x101:0xd DW_TAG_lexical_block
	.byte	6                               // Abbrev [6] 0x102:0xb DW_TAG_variable
	.long	.Linfo_string26                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	111                             // DW_AT_decl_line
	.long	351                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x10e:0xd DW_TAG_lexical_block
	.byte	6                               // Abbrev [6] 0x10f:0xb DW_TAG_variable
	.long	.Linfo_string27                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	100                             // DW_AT_decl_line
	.long	368                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x11b:0x18 DW_TAG_lexical_block
	.byte	6                               // Abbrev [6] 0x11c:0xb DW_TAG_variable
	.long	.Linfo_string27                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	123                             // DW_AT_decl_line
	.long	368                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x127:0xb DW_TAG_variable
	.long	.Linfo_string26                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	124                             // DW_AT_decl_line
	.long	351                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x133:0xd DW_TAG_lexical_block
	.byte	6                               // Abbrev [6] 0x134:0xb DW_TAG_variable
	.long	.Linfo_string28                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	54                              // DW_AT_decl_line
	.long	339                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	2                               // Abbrev [2] 0x141:0xb DW_TAG_typedef
	.long	332                             // DW_AT_type
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	45                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x14c:0x7 DW_TAG_base_type
	.long	.Linfo_string7                  // DW_AT_name
	.byte	4                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	8                               // Abbrev [8] 0x153:0x5 DW_TAG_const_type
	.long	38                              // DW_AT_type
	.byte	3                               // Abbrev [3] 0x158:0x7 DW_TAG_base_type
	.long	.Linfo_string16                 // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	8                               // Abbrev [8] 0x15f:0x5 DW_TAG_const_type
	.long	356                             // DW_AT_type
	.byte	3                               // Abbrev [3] 0x164:0x7 DW_TAG_base_type
	.long	.Linfo_string22                 // DW_AT_name
	.byte	2                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	8                               // Abbrev [8] 0x16b:0x5 DW_TAG_const_type
	.long	60                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0x170:0x5 DW_TAG_const_type
	.long	344                             // DW_AT_type
	.byte	4                               // Abbrev [4] 0x175:0x18 DW_TAG_subprogram
	.long	.Linfo_string29                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	50                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	344                             // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0x181:0xb DW_TAG_formal_parameter
	.long	.Linfo_string9                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	50                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	9                               // Abbrev [9] 0x18d:0x12d DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string30                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	19                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	321                             // DW_AT_type
                                        // DW_AT_external
	.byte	10                              // Abbrev [10] 0x1a2:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string9                  // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	19                              // DW_AT_decl_line
	.long	332                             // DW_AT_type
	.byte	10                              // Abbrev [10] 0x1b1:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string10                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	19                              // DW_AT_decl_line
	.long	332                             // DW_AT_type
	.byte	11                              // Abbrev [11] 0x1c0:0xf9 DW_TAG_inlined_subroutine
	.long	67                              // DW_AT_abstract_origin
	.long	.Ldebug_ranges0                 // DW_AT_ranges
	.byte	3                               // DW_AT_call_file
	.byte	21                              // DW_AT_call_line
	.byte	12                              // DW_AT_call_column
	.byte	12                              // Abbrev [12] 0x1cc:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	79                              // DW_AT_abstract_origin
	.byte	12                              // Abbrev [12] 0x1d5:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	90                              // DW_AT_abstract_origin
	.byte	13                              // Abbrev [13] 0x1de:0x9 DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	101                             // DW_AT_abstract_origin
	.byte	13                              // Abbrev [13] 0x1e7:0x9 DW_TAG_variable
	.long	.Ldebug_loc5                    // DW_AT_location
	.long	112                             // DW_AT_abstract_origin
	.byte	13                              // Abbrev [13] 0x1f0:0x9 DW_TAG_variable
	.long	.Ldebug_loc6                    // DW_AT_location
	.long	123                             // DW_AT_abstract_origin
	.byte	13                              // Abbrev [13] 0x1f9:0x9 DW_TAG_variable
	.long	.Ldebug_loc7                    // DW_AT_location
	.long	134                             // DW_AT_abstract_origin
	.byte	13                              // Abbrev [13] 0x202:0x9 DW_TAG_variable
	.long	.Ldebug_loc8                    // DW_AT_location
	.long	145                             // DW_AT_abstract_origin
	.byte	13                              // Abbrev [13] 0x20b:0x9 DW_TAG_variable
	.long	.Ldebug_loc9                    // DW_AT_location
	.long	156                             // DW_AT_abstract_origin
	.byte	13                              // Abbrev [13] 0x214:0x9 DW_TAG_variable
	.long	.Ldebug_loc10                   // DW_AT_location
	.long	167                             // DW_AT_abstract_origin
	.byte	13                              // Abbrev [13] 0x21d:0x9 DW_TAG_variable
	.long	.Ldebug_loc11                   // DW_AT_location
	.long	178                             // DW_AT_abstract_origin
	.byte	13                              // Abbrev [13] 0x226:0x9 DW_TAG_variable
	.long	.Ldebug_loc12                   // DW_AT_location
	.long	189                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x22f:0x5 DW_TAG_variable
	.long	200                             // DW_AT_abstract_origin
	.byte	13                              // Abbrev [13] 0x234:0x9 DW_TAG_variable
	.long	.Ldebug_loc13                   // DW_AT_location
	.long	211                             // DW_AT_abstract_origin
	.byte	13                              // Abbrev [13] 0x23d:0x9 DW_TAG_variable
	.long	.Ldebug_loc18                   // DW_AT_location
	.long	222                             // DW_AT_abstract_origin
	.byte	13                              // Abbrev [13] 0x246:0x9 DW_TAG_variable
	.long	.Ldebug_loc19                   // DW_AT_location
	.long	233                             // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x24f:0x13 DW_TAG_lexical_block
	.long	.Ltmp31                         // DW_AT_low_pc
	.long	.Ltmp34-.Ltmp31                 // DW_AT_high_pc
	.byte	13                              // Abbrev [13] 0x258:0x9 DW_TAG_variable
	.long	.Ldebug_loc14                   // DW_AT_location
	.long	245                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	15                              // Abbrev [15] 0x262:0xf DW_TAG_lexical_block
	.long	.Ltmp39                         // DW_AT_low_pc
	.long	.Ltmp43-.Ltmp39                 // DW_AT_high_pc
	.byte	14                              // Abbrev [14] 0x26b:0x5 DW_TAG_variable
	.long	258                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	15                              // Abbrev [15] 0x271:0x2b DW_TAG_lexical_block
	.long	.Ltmp59                         // DW_AT_low_pc
	.long	.Ltmp63-.Ltmp59                 // DW_AT_high_pc
	.byte	13                              // Abbrev [13] 0x27a:0x9 DW_TAG_variable
	.long	.Ldebug_loc15                   // DW_AT_location
	.long	271                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x283:0x18 DW_TAG_inlined_subroutine
	.long	373                             // DW_AT_abstract_origin
	.long	.Ltmp59                         // DW_AT_low_pc
	.long	.Ltmp60-.Ltmp59                 // DW_AT_high_pc
	.byte	4                               // DW_AT_call_file
	.byte	100                             // DW_AT_call_line
	.byte	31                              // DW_AT_call_column
	.byte	17                              // Abbrev [17] 0x293:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	82
	.long	385                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	15                              // Abbrev [15] 0x29c:0x1c DW_TAG_lexical_block
	.long	.Ltmp69                         // DW_AT_low_pc
	.long	.Ltmp74-.Ltmp69                 // DW_AT_high_pc
	.byte	13                              // Abbrev [13] 0x2a5:0x9 DW_TAG_variable
	.long	.Ldebug_loc16                   // DW_AT_location
	.long	284                             // DW_AT_abstract_origin
	.byte	13                              // Abbrev [13] 0x2ae:0x9 DW_TAG_variable
	.long	.Ldebug_loc17                   // DW_AT_location
	.long	295                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_ranges,"",@progbits
.Ldebug_ranges0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp9-.Lfunc_begin0
	.long	.Ltmp11-.Lfunc_begin0
	.long	.Ltmp45-.Lfunc_begin0
	.long	.Ltmp49-.Lfunc_begin0
	.long	.Ltmp66-.Lfunc_begin0
	.long	.Ltmp68-.Lfunc_begin0
	.long	.Ltmp84-.Lfunc_begin0
	.long	.Ltmp86-.Lfunc_begin0
	.long	.Ltmp91-.Lfunc_begin0
	.long	.Ltmp93-.Lfunc_begin0
	.long	.Ltmp94-.Lfunc_begin0
	.long	.Ltmp96-.Lfunc_begin0
	.long	.Ltmp101-.Lfunc_begin0
	.long	0
	.long	0
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/addsf3.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=152
.Linfo_string3:
	.asciz	"unsigned int"                  // string offset=173
.Linfo_string4:
	.asciz	"uint32_t"                      // string offset=186
.Linfo_string5:
	.asciz	"rep_t"                         // string offset=195
.Linfo_string6:
	.asciz	"__addXf3__"                    // string offset=201
.Linfo_string7:
	.asciz	"float"                         // string offset=212
.Linfo_string8:
	.asciz	"fp_t"                          // string offset=218
.Linfo_string9:
	.asciz	"a"                             // string offset=223
.Linfo_string10:
	.asciz	"b"                             // string offset=225
.Linfo_string11:
	.asciz	"aRep"                          // string offset=227
.Linfo_string12:
	.asciz	"bRep"                          // string offset=232
.Linfo_string13:
	.asciz	"aAbs"                          // string offset=237
.Linfo_string14:
	.asciz	"bAbs"                          // string offset=242
.Linfo_string15:
	.asciz	"bExponent"                     // string offset=247
.Linfo_string16:
	.asciz	"int"                           // string offset=257
.Linfo_string17:
	.asciz	"bSignificand"                  // string offset=261
.Linfo_string18:
	.asciz	"aSignificand"                  // string offset=274
.Linfo_string19:
	.asciz	"aExponent"                     // string offset=287
.Linfo_string20:
	.asciz	"resultSign"                    // string offset=297
.Linfo_string21:
	.asciz	"subtraction"                   // string offset=308
.Linfo_string22:
	.asciz	"_Bool"                         // string offset=320
.Linfo_string23:
	.asciz	"align"                         // string offset=326
.Linfo_string24:
	.asciz	"result"                        // string offset=332
.Linfo_string25:
	.asciz	"roundGuardSticky"              // string offset=339
.Linfo_string26:
	.asciz	"sticky"                        // string offset=356
.Linfo_string27:
	.asciz	"shift"                         // string offset=363
.Linfo_string28:
	.asciz	"temp"                          // string offset=369
.Linfo_string29:
	.asciz	"rep_clz"                       // string offset=374
.Linfo_string30:
	.asciz	"__addsf3"                      // string offset=382
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
