	.text
	.file	"buddy_alloc.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/stdint.h"
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/buddy_alloc.c"
	.section	.text.safe_buddy_alloc,"ax",@progbits
	.globl	safe_buddy_alloc                // -- Begin function safe_buddy_alloc
	.type	safe_buddy_alloc,@function
safe_buddy_alloc:                       // @safe_buddy_alloc
.Lfunc_begin0:
	.loc	2 66 0                          // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:66:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: safe_buddy_alloc:size <- $r0
	.cfi_def_cfa_offset 0
	.cfi_offset 15, 0
	.cfi_offset 14, 4
	sd r22, 0, d14
	lw r1, zero, __BUDDY_SIZE_OF_HEAP__
	//DEBUG_VALUE: safe_buddy_alloc:size <- $r0
.Ltmp0:
	.loc	2 67 21 prologue_end            // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:67:21
	add r2, r0, -1
	jgeu r2, r1, .LBB0_4
.Ltmp1:
// %bb.1:
	//DEBUG_VALUE: safe_buddy_alloc:size <- $r0
	//DEBUG_VALUE: next_power_of_2:x <- $r0
	.loc	2 39 36                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:39:36
	clz r2, r0
	.loc	2 39 34 is_stmt 0               // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:39:34
	add r1, r2, -31
.Ltmp2:
	//DEBUG_VALUE: next_power_of_2:power_of_2 <- [DW_OP_constu 31, DW_OP_xor, DW_OP_stack_value] $r2
	.loc	2 41 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:41:9
	cao r0, r0
.Ltmp3:
	.loc	2 41 9 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:41:9
	jneq r0, 1, .LBB0_5
.Ltmp4:
// %bb.2:
	//DEBUG_VALUE: next_power_of_2:power_of_2 <- undef
	//DEBUG_VALUE: safe_buddy_alloc:power_of_2 <- undef
	.loc	2 78 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:78:24
	lbu r3, zero, __BUDDY_MAX_POWER__
.Ltmp5:
	.loc	2 84 25                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:84:25
	lbu r2, zero, __BUDDY_NUMBER_OF_LEVELS__
.Ltmp6:
	.loc	2 78 44                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:78:44
	add r0, r1, r3
.Ltmp7:
	//DEBUG_VALUE: safe_buddy_alloc:blocks_level <- $r0
	.loc	2 84 9                          // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:84:9
	jges r0, r2, .LBB0_6
.Ltmp8:
.LBB0_3:
	//DEBUG_VALUE: safe_buddy_alloc:blocks_level <- $r0
	//DEBUG_VALUE: safe_buddy_alloc:blocks_level <- $r0
	//DEBUG_VALUE: blocks_level_current <- $r0
	.loc	2 89 5                          // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:89:5
	jges r0, 0, .LBB0_7
	jump .LBB0_33
.Ltmp9:
.LBB0_4:
	//DEBUG_VALUE: safe_buddy_alloc:size <- $r0
	.loc	2 0 5 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:5
	move r0, 28
.Ltmp10:
	sw id4, __errno, r0
	move r0, 0
	.loc	2 238 1 is_stmt 1               // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:238:1
	ld d14, r22, 0
	jump r23
.LBB0_5:
	.loc	2 0 1 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:1
	or r1, r2, -32
	//DEBUG_VALUE: next_power_of_2:power_of_2 <- undef
.Ltmp11:
	//DEBUG_VALUE: safe_buddy_alloc:power_of_2 <- undef
	.loc	2 78 24 is_stmt 1               // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:78:24
	lbu r3, zero, __BUDDY_MAX_POWER__
.Ltmp12:
	.loc	2 84 25                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:84:25
	lbu r2, zero, __BUDDY_NUMBER_OF_LEVELS__
.Ltmp13:
	.loc	2 78 44                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:78:44
	add r0, r1, r3
.Ltmp14:
	//DEBUG_VALUE: safe_buddy_alloc:blocks_level <- $r0
	.loc	2 84 9                          // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:84:9
	jlts r0, r2, .LBB0_3
.Ltmp15:
.LBB0_6:
	//DEBUG_VALUE: safe_buddy_alloc:blocks_level <- $r0
	//DEBUG_VALUE: safe_buddy_alloc:blocks_level <- $r0
	//DEBUG_VALUE: blocks_level_current <- $r0
	.loc	2 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:9
	add r0, r2, -1, mi, .LBB0_33
.Ltmp16:
.LBB0_7:
	lw r2, zero, __buddy_blocks
	lw r1, zero, __buddy_heap_start
	sub r3, r3, r0
.Ltmp17:
	.loc	2 89 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:89:5
	add r4, r0, 1
	move r5, r0, true, .LBB0_12
.LBB0_8:                                //   in Loop: Header=BB0_12 Depth=1
.Ltmp18:
	//DEBUG_VALUE: blocks_level_current <- $r5
	.loc	2 89 14 is_stmt 0               // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:89:14
	move r9, r0
.Ltmp19:
.LBB0_9:                                //   in Loop: Header=BB0_12 Depth=1
	.loc	2 0 14                          // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:14
	move r8, r7
.Ltmp20:
	//DEBUG_VALUE: blocks_level_current <- $r9
	move r5, r9
.Ltmp21:
	//DEBUG_VALUE: blocks_level_current <- $r5
	jgts r6, -1, .LBB0_34
.Ltmp22:
.LBB0_11:                               //   in Loop: Header=BB0_12 Depth=1
	//DEBUG_VALUE: blocks_level_current <- $r5
	move r6, r5
.Ltmp23:
	.loc	2 89 78                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:89:78
	add r5, r6, -1
.Ltmp24:
	//DEBUG_VALUE: blocks_level_current <- $r5
	.loc	2 89 5                          // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:89:5
	jles r6, 0, .LBB0_33
.Ltmp25:
.LBB0_12:                               // =>This Loop Header: Depth=1
                                        //     Child Loop BB0_17 Depth 2
                                        //     Child Loop BB0_28 Depth 2
	//DEBUG_VALUE: blocks_level_current <- $r5
	.loc	2 91 41 is_stmt 1               // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:91:41
	lsl r7, one, r5
.Ltmp26:
	//DEBUG_VALUE: initial_number_of_current_bitfield <- 0
	//DEBUG_VALUE: index_in_level <- $r7
	.loc	2 100 9                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:100:9
	jgeu r5, 5, .LBB0_14
.Ltmp27:
// %bb.13:                              //   in Loop: Header=BB0_12 Depth=1
	//DEBUG_VALUE: index_in_level <- $r7
	//DEBUG_VALUE: blocks_level_current <- $r5
	//DEBUG_VALUE: initial_number_of_current_bitfield <- 0
	lsl r6, r5, 2
	lw r12, r6, .Lswitch.table.safe_buddy_alloc
	move r10, 0, true, .LBB0_16
.Ltmp28:
.LBB0_14:                               //   in Loop: Header=BB0_12 Depth=1
	//DEBUG_VALUE: index_in_level <- $r7
	//DEBUG_VALUE: blocks_level_current <- $r5
	//DEBUG_VALUE: initial_number_of_current_bitfield <- 0
	//DEBUG_VALUE: blocks_level_current <- $r5
	//DEBUG_VALUE: index_in_level <- $r7
	//DEBUG_VALUE: initial_number_of_current_bitfield <- undef
	//DEBUG_VALUE: number_of_current_bitfield <- undef
	//DEBUG_VALUE: loaded_case_mask <- -1
	.loc	2 122 9                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:122:9
	jles r7, 31, .LBB0_11
.Ltmp29:
// %bb.15:                              //   in Loop: Header=BB0_12 Depth=1
	//DEBUG_VALUE: index_in_level <- $r7
	//DEBUG_VALUE: blocks_level_current <- $r5
	//DEBUG_VALUE: loaded_case_mask <- -1
	.loc	2 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:9
	asr r6, r7, 5
	add r10, r6, -1
.Ltmp30:
	//DEBUG_VALUE: number_of_current_bitfield <- $r10
	//DEBUG_VALUE: initial_number_of_current_bitfield <- $r10
	move r12, -1
.Ltmp31:
.LBB0_16:                               //   in Loop: Header=BB0_12 Depth=1
	//DEBUG_VALUE: index_in_level <- $r7
	//DEBUG_VALUE: blocks_level_current <- $r5
	asr r9, r7, 5
	.loc	2 122 9                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:122:9
	lsl_add r13, r2, r9, 2
	add r8, r7, -1
.Ltmp32:
.LBB0_17:                               //   Parent Loop BB0_12 Depth=1
                                        // =>  This Inner Loop Header: Depth=2
	//DEBUG_VALUE: blocks_level_current <- $r5
	.loc	2 0 9                           // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:9
	move r6, r10
.Ltmp33:
	//DEBUG_VALUE: initial_loaded_case_address <- undef
	//DEBUG_VALUE: real_index <- $r9
	//DEBUG_VALUE: number_of_current_bitfield <- $r6
	//DEBUG_VALUE: index_in_level <- [DW_OP_plus_uconst 1, DW_OP_stack_value] $r8
	//DEBUG_VALUE: blocks_level_current <- $r5
	.loc	2 136 40 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:136:40
	lsl_add r10, r13, r6, 2
	lw r10, r10, 0
	.loc	2 136 69 is_stmt 0              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:136:69
	and r11, r10, r12
.Ltmp34:
	//DEBUG_VALUE: loaded_case <- $r11
	.loc	2 142 67 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:142:67
	lsl r14, r11, 1
	.loc	2 142 73 is_stmt 0              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:142:73
	xor r14, r14, r11
	.loc	2 142 88                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:142:88
	and r14, r14, -1431655766
.Ltmp35:
	//DEBUG_VALUE: lz_before_first_pair_tmp <- $r14
	.loc	2 144 17 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:144:17
	jneq r14, 0, .LBB0_19
.Ltmp36:
// %bb.18:                              //   in Loop: Header=BB0_17 Depth=2
	//DEBUG_VALUE: index_in_level <- [DW_OP_plus_uconst 1, DW_OP_stack_value] $r8
	//DEBUG_VALUE: number_of_current_bitfield <- $r6
	//DEBUG_VALUE: blocks_level_current <- $r5
	.loc	2 123 14                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:123:14
	add r10, r6, -1
.Ltmp37:
	//DEBUG_VALUE: number_of_current_bitfield <- $r10
	//DEBUG_VALUE: index_in_level <- [DW_OP_constu 31, DW_OP_minus, DW_OP_stack_value] $r8
	//DEBUG_VALUE: blocks_level_current <- $r5
	.loc	2 122 110                       // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:122:110
	add r8, r8, -32
.Ltmp38:
	.loc	2 122 9 is_stmt 0               // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:122:9
	jgts r6, 0, .LBB0_17
	jump .LBB0_11
.Ltmp39:
.LBB0_19:                               //   in Loop: Header=BB0_12 Depth=1
	//DEBUG_VALUE: lz_before_first_pair_tmp <- $r14
	//DEBUG_VALUE: loaded_case <- $r11
	//DEBUG_VALUE: real_index <- $r9
	//DEBUG_VALUE: index_in_level <- [DW_OP_plus_uconst 1, DW_OP_stack_value] $r8
	//DEBUG_VALUE: number_of_current_bitfield <- $r6
	//DEBUG_VALUE: blocks_level_current <- $r5
	//DEBUG_VALUE: index_in_level <- undef
	//DEBUG_VALUE: lz_before_first_pair <- undef
	.loc	2 152 21 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:152:21
	jlts r5, 5, .LBB0_21
.Ltmp40:
// %bb.20:                              //   in Loop: Header=BB0_12 Depth=1
	//DEBUG_VALUE: lz_before_first_pair_tmp <- $r14
	//DEBUG_VALUE: loaded_case <- $r11
	//DEBUG_VALUE: real_index <- $r9
	//DEBUG_VALUE: number_of_current_bitfield <- $r6
	//DEBUG_VALUE: blocks_level_current <- $r5
	.loc	2 0 21 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:21
	move r7, 0
.Ltmp41:
.LBB0_21:                               //   in Loop: Header=BB0_12 Depth=1
	//DEBUG_VALUE: lz_before_first_pair_tmp <- $r14
	//DEBUG_VALUE: loaded_case <- $r11
	//DEBUG_VALUE: real_index <- $r9
	//DEBUG_VALUE: number_of_current_bitfield <- $r6
	//DEBUG_VALUE: blocks_level_current <- $r5
	clz r12, r14
.Ltmp42:
	//DEBUG_VALUE: lz_before_first_pair <- $r12
	//DEBUG_VALUE: index_in_level <- undef
	.loc	2 156 55 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:156:55
	sub r13, r7, r12
	add r13, r13, r8
	lsl r13, one, r13
.Ltmp43:
	//DEBUG_VALUE: highlight_target_bit <- $r13
	.loc	2 161 21                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:161:21
	jges r5, 4, .LBB0_23
.Ltmp44:
// %bb.22:                              //   in Loop: Header=BB0_12 Depth=1
	//DEBUG_VALUE: lz_before_first_pair_tmp <- $r14
	//DEBUG_VALUE: highlight_target_bit <- $r13
	//DEBUG_VALUE: lz_before_first_pair <- $r12
	//DEBUG_VALUE: loaded_case <- $r11
	//DEBUG_VALUE: real_index <- $r9
	//DEBUG_VALUE: number_of_current_bitfield <- $r6
	//DEBUG_VALUE: blocks_level_current <- $r5
	.loc	2 0 21 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:21
	move r14, -2
	lsl r14, r14, r5
	add r14, r14, 32, true, .LBB0_24
.Ltmp45:
.LBB0_23:                               //   in Loop: Header=BB0_12 Depth=1
	//DEBUG_VALUE: lz_before_first_pair_tmp <- $r14
	//DEBUG_VALUE: highlight_target_bit <- $r13
	//DEBUG_VALUE: lz_before_first_pair <- $r12
	//DEBUG_VALUE: loaded_case <- $r11
	//DEBUG_VALUE: real_index <- $r9
	//DEBUG_VALUE: number_of_current_bitfield <- $r6
	//DEBUG_VALUE: blocks_level_current <- $r5
	move r14, 0
.Ltmp46:
.LBB0_24:                               //   in Loop: Header=BB0_12 Depth=1
	//DEBUG_VALUE: highlight_target_bit <- $r13
	//DEBUG_VALUE: lz_before_first_pair <- $r12
	//DEBUG_VALUE: loaded_case <- $r11
	//DEBUG_VALUE: real_index <- $r9
	//DEBUG_VALUE: number_of_current_bitfield <- $r6
	//DEBUG_VALUE: blocks_level_current <- $r5
	lsl_add r9, r2, r9, 2
.Ltmp47:
	.loc	2 161 21                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:161:21
	lsl r13, r13, r14
.Ltmp48:
	//DEBUG_VALUE: highlight_target_bit <- $r13
	.loc	2 172 43 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:172:43
	and r11, r13, r11
.Ltmp49:
	//DEBUG_VALUE: loaded_case <- $r11
	.loc	2 0 43 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:43
	move r14, 0
.Ltmp50:
	.loc	2 174 33 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:174:33
	sub r11, r11, r14, eq
.Ltmp51:
	.loc	2 174 21 is_stmt 0              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:174:21
	sub r7, r7, r11
	sub r7, r7, r12
	add r7, r7, r8
	lsr r8, r13, r11
.Ltmp52:
	//DEBUG_VALUE: highlight_target_bit <- $r8
	//DEBUG_VALUE: loaded_case <- $r10
	//DEBUG_VALUE: index_in_level <- undef
	.loc	2 183 29 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:183:29
	sub r8, r10, r8
.Ltmp53:
	//DEBUG_VALUE: loaded_case <- $r8
	.loc	2 184 46                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:184:46
	lsl_add r9, r9, r6, 2
	sw r9, 0, r8
	.loc	2 190 21                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:190:21
	jeq r0, r5, .LBB0_8
.Ltmp54:
// %bb.25:                              //   in Loop: Header=BB0_12 Depth=1
	//DEBUG_VALUE: lz_before_first_pair <- $r12
	//DEBUG_VALUE: loaded_case <- $r8
	//DEBUG_VALUE: number_of_current_bitfield <- $r6
	//DEBUG_VALUE: blocks_level_current <- $r5
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:0
	add r9, r5, 1
.Ltmp55:
	//DEBUG_VALUE: index_in_level <- undef
	//DEBUG_VALUE: blocks_level_current <- $r9
	.loc	2 198 17 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:198:17
	jlts r5, r0, .LBB0_28
	jump .LBB0_9
.Ltmp56:
.LBB0_31:                               //   in Loop: Header=BB0_28 Depth=2
	//DEBUG_VALUE: lz_before_first_pair <- $r12
	//DEBUG_VALUE: index_in_level <- $r8
	//DEBUG_VALUE: number_of_current_bitfield <- $r6
	//DEBUG_VALUE: real_index <- 0
	//DEBUG_VALUE: blocks_level_clamped <- [DW_OP_constu 4, DW_OP_minus, DW_OP_stack_value] undef
	.loc	2 217 40                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:217:40
	add r11, r5, -4
	lsl r11, one, r11
.Ltmp57:
	//DEBUG_VALUE: real_index <- $r11
	.loc	2 218 63                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:218:63
	lsr r7, r7, 4
	and r7, r7, 134217727
.Ltmp58:
	//DEBUG_VALUE: blocks_level_clamped <- $r7
	.loc	2 219 36                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:219:36
	add r11, r11, r7
.Ltmp59:
	//DEBUG_VALUE: real_index <- $r11
.LBB0_27:                               //   in Loop: Header=BB0_28 Depth=2
	//DEBUG_VALUE: lz_before_first_pair <- $r12
	//DEBUG_VALUE: index_in_level <- $r8
	//DEBUG_VALUE: number_of_current_bitfield <- $r6
	.loc	2 221 35                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:221:35
	lsl_add r7, r2, r11, 2
	lw r11, r7, 0
.Ltmp60:
	//DEBUG_VALUE: loaded_case <- $r11
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:0
	lsl r9, r10, r9
.Ltmp61:
	//DEBUG_VALUE: real_index <- undef
	.loc	2 224 62 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:224:62
	add r9, r11, r9
.Ltmp62:
	.loc	2 198 45                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:198:45
	add r5, r5, 1
.Ltmp63:
	.loc	2 224 48                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:224:48
	sw r7, 0, r9
	//DEBUG_VALUE: index_in_level <- $r8
.Ltmp64:
	//DEBUG_VALUE: blocks_level_current <- [DW_OP_plus_uconst 2, DW_OP_stack_value] $r5
	.loc	2 0 48 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:48
	move r7, r8
.Ltmp65:
	.loc	2 198 17 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:198:17
	jeq r0, r5, .LBB0_32
.Ltmp66:
.LBB0_28:                               //   Parent Loop BB0_12 Depth=1
                                        // =>  This Inner Loop Header: Depth=2
	//DEBUG_VALUE: lz_before_first_pair <- $r12
	//DEBUG_VALUE: number_of_current_bitfield <- $r6
	//DEBUG_VALUE: index_in_level <- undef
	//DEBUG_VALUE: highlight_target_bit <- undef
	//DEBUG_VALUE: blocks_level_clamped <- [DW_OP_constu 3, DW_OP_minus, DW_OP_stack_value] undef
	.loc	2 207 25                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:207:25
	jges r5, 3, .LBB0_30
.Ltmp67:
// %bb.29:                              //   in Loop: Header=BB0_28 Depth=2
	//DEBUG_VALUE: lz_before_first_pair <- $r12
	//DEBUG_VALUE: number_of_current_bitfield <- $r6
	.loc	2 0 25 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:25
	add r8, r5, 1
	move r9, -2
	lsl r8, r9, r8
	add r9, r8, 32
	lsl r8, r7, 1
.Ltmp68:
	//DEBUG_VALUE: index_in_level <- $r8
	lsl r10, lneg, r8
	move r11, 0
.Ltmp69:
	//DEBUG_VALUE: real_index <- 0
	//DEBUG_VALUE: blocks_level_clamped <- [DW_OP_constu 4, DW_OP_minus, DW_OP_stack_value] undef
	.loc	2 216 25 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:216:25
	jlts r5, 4, .LBB0_27
	jump .LBB0_31
.Ltmp70:
.LBB0_30:                               //   in Loop: Header=BB0_28 Depth=2
	//DEBUG_VALUE: lz_before_first_pair <- $r12
	//DEBUG_VALUE: number_of_current_bitfield <- $r6
	.loc	2 0 25 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:25
	move r9, 0
	lsl r8, r7, 1
.Ltmp71:
	//DEBUG_VALUE: index_in_level <- $r8
	lsl r10, lneg, r8
	move r11, 0
.Ltmp72:
	//DEBUG_VALUE: real_index <- 0
	//DEBUG_VALUE: blocks_level_clamped <- [DW_OP_constu 4, DW_OP_minus, DW_OP_stack_value] undef
	.loc	2 216 25                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:216:25
	jlts r5, 4, .LBB0_27
	jump .LBB0_31
.Ltmp73:
.LBB0_32:                               //   in Loop: Header=BB0_12 Depth=1
	//DEBUG_VALUE: blocks_level_current <- [DW_OP_plus_uconst 2, DW_OP_stack_value] $r5
	.loc	2 89 14 is_stmt 1               // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:89:14
	move r9, r4
.Ltmp74:
	//DEBUG_VALUE: blocks_level_current <- $r9
	.loc	2 0 14 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:14
	move r5, r9
.Ltmp75:
	//DEBUG_VALUE: blocks_level_current <- $r5
	jles r6, -1, .LBB0_11
.Ltmp76:
.LBB0_34:
	//DEBUG_VALUE: blocks_level_current <- $r5
	lsl r0, r8, r3
	add r0, r1, r0
.Ltmp77:
	.loc	2 238 1 is_stmt 1               // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:238:1
	ld d14, r22, 0
	jump r23
.Ltmp78:
.LBB0_33:
	.loc	2 0 1 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:1
	move r0, 49
	sw id4, __errno, r0
	move r0, 0
	.loc	2 238 1                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:238:1
	ld d14, r22, 0
	jump r23
.Ltmp79:
.Lfunc_end0:
	.size	safe_buddy_alloc, .Lfunc_end0-safe_buddy_alloc
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.safe_buddy_alloc
	.long	.Lfunc_begin0
	.byte	8
	.section	.text.safe_buddy_alloc,"ax",@progbits
                                        // -- End function
	.section	.text.buddy_search_for_pointer,"ax",@progbits
	.globl	buddy_search_for_pointer        // -- Begin function buddy_search_for_pointer
	.type	buddy_search_for_pointer,@function
buddy_search_for_pointer:               // @buddy_search_for_pointer
.Lfunc_begin1:
	.loc	2 249 0 is_stmt 1               // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:249:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: buddy_search_for_pointer:pointer <- $r0
	//DEBUG_VALUE: buddy_search_for_pointer:pointer <- $r0
	//DEBUG_VALUE: buddy_search_for_pointer:context <- $r1
	//DEBUG_VALUE: buddy_search_for_pointer:context <- $r1
	.cfi_def_cfa_offset 0
	.loc	2 252 35 prologue_end           // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:252:35
	and r2, r0, 7, nz, .LBB1_3
.Ltmp80:
// %bb.1:
	//DEBUG_VALUE: buddy_search_for_pointer:context <- $r1
	//DEBUG_VALUE: buddy_search_for_pointer:pointer <- $r0
	.loc	2 0 35 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:35
	lw r2, zero, __buddy_heap_start
	.loc	2 252 46                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:252:46
	jgtu r2, r0, .LBB1_3
.Ltmp81:
// %bb.2:
	//DEBUG_VALUE: buddy_search_for_pointer:context <- $r1
	//DEBUG_VALUE: buddy_search_for_pointer:pointer <- $r0
	.loc	2 253 45 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:253:45
	lw r3, zero, __BUDDY_SIZE_OF_HEAP__
	.loc	2 253 43 is_stmt 0              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:253:43
	add r3, r2, r3
	.loc	2 253 68                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:253:68
	add r3, r3, -1
.Ltmp82:
	.loc	2 252 9 is_stmt 1               // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:252:9
	jgeu r3, r0, .LBB1_4
.Ltmp83:
.LBB1_3:
	//DEBUG_VALUE: buddy_search_for_pointer:context <- $r1
	.loc	2 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:9
	move r0, 28
	sw id4, __errno, r0
	move r0, -1
	.loc	2 325 1 is_stmt 1               // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:325:1
	jump r23
.Ltmp84:
.LBB1_4:
	//DEBUG_VALUE: buddy_search_for_pointer:context <- $r1
	//DEBUG_VALUE: buddy_search_for_pointer:pointer <- $r0
	.loc	2 262 33                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:262:33
	lbu r4, zero, __BUDDY_NUMBER_OF_LEVELS__
.Ltmp85:
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- [DW_OP_constu 1, DW_OP_minus, DW_OP_stack_value] $r4
	.loc	2 0 33 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:33
	lw r3, zero, __buddy_blocks
	.loc	2 260 44 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:260:44
	sub r0, r0, r2
.Ltmp86:
	.loc	2 260 66 is_stmt 0              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:260:66
	asr r0, r0, 4
.Ltmp87:
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r0
	.loc	2 264 5 is_stmt 1               // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:264:5
	add r2, r4, -1
.Ltmp88:
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- $r2
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r0
	.loc	2 267 47                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:267:47
	lsl r4, one, r0
.Ltmp89:
	//DEBUG_VALUE: highlight_target_bit <- $r4
	.loc	2 270 14                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:270:14
	clz r5, r4
	.loc	2 270 56 is_stmt 0              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:270:56
	and r5, r5, 1, z, .LBB1_6
.Ltmp90:
.LBB1_7:
	//DEBUG_VALUE: highlight_target_bit <- $r4
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- $r2
	//DEBUG_VALUE: buddy_search_for_pointer:context <- $r1
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r0
	.loc	2 0 56                          // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:56
	lsl r5, r4, 1
.Ltmp91:
	//DEBUG_VALUE: highlight_buddy_bit <- $r5
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 1, DW_OP_constu 5, DW_OP_minus, DW_OP_stack_value] $r2
	.loc	2 282 34 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:282:34
	add r6, r2, -4, mi, .LBB1_9
.Ltmp92:
.LBB1_10:
	//DEBUG_VALUE: highlight_buddy_bit <- $r5
	//DEBUG_VALUE: highlight_target_bit <- $r4
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 1, DW_OP_constu 5, DW_OP_minus, DW_OP_stack_value] $r2
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- $r2
	//DEBUG_VALUE: buddy_search_for_pointer:context <- $r1
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r0
	.loc	2 0 34 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:34
	move r6, 0
.Ltmp93:
	//DEBUG_VALUE: highlight_target_bit <- undef
	//DEBUG_VALUE: highlight_buddy_bit <- undef
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 1, DW_OP_constu 6, DW_OP_minus, DW_OP_stack_value] $r2
	//DEBUG_VALUE: real_index <- 0
	.loc	2 297 13 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:297:13
	add r7, r2, -5, mi, .LBB1_12
.Ltmp94:
.LBB1_13:
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 1, DW_OP_constu 6, DW_OP_minus, DW_OP_stack_value] $r2
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- $r2
	//DEBUG_VALUE: buddy_search_for_pointer:context <- $r1
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r0
	//DEBUG_VALUE: real_index <- 0
	.loc	2 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:13
	lsl r7, one, r7
	lsr_add r7, r7, r0, 5
	lsl r8, r4, r6
.Ltmp95:
	//DEBUG_VALUE: highlight_target_bit <- $r8
	lsl r4, r5, r6
.Ltmp96:
	//DEBUG_VALUE: loaded_case <- undef
	//DEBUG_VALUE: real_index <- $r7
	//DEBUG_VALUE: highlight_buddy_bit <- $r4
	jneq r2, 0, .LBB1_15
	jump .LBB1_16
.Ltmp97:
.LBB1_6:
	//DEBUG_VALUE: highlight_target_bit <- $r4
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- $r2
	//DEBUG_VALUE: buddy_search_for_pointer:context <- $r1
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r0
	lsr r5, r4, 1
.Ltmp98:
	//DEBUG_VALUE: highlight_buddy_bit <- $r5
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 1, DW_OP_constu 5, DW_OP_minus, DW_OP_stack_value] $r2
	.loc	2 282 34 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:282:34
	add r6, r2, -4, pl, .LBB1_10
.Ltmp99:
.LBB1_9:
	//DEBUG_VALUE: highlight_buddy_bit <- $r5
	//DEBUG_VALUE: highlight_target_bit <- $r4
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 1, DW_OP_constu 5, DW_OP_minus, DW_OP_stack_value] $r2
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- $r2
	//DEBUG_VALUE: buddy_search_for_pointer:context <- $r1
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r0
	.loc	2 0 34 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:34
	move r6, -2
	lsl r6, r6, r2
	add r6, r6, 32
.Ltmp100:
	//DEBUG_VALUE: highlight_target_bit <- undef
	//DEBUG_VALUE: highlight_buddy_bit <- undef
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 1, DW_OP_constu 6, DW_OP_minus, DW_OP_stack_value] $r2
	//DEBUG_VALUE: real_index <- 0
	.loc	2 297 13 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:297:13
	add r7, r2, -5, pl, .LBB1_13
.Ltmp101:
.LBB1_12:
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 1, DW_OP_constu 6, DW_OP_minus, DW_OP_stack_value] $r2
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- $r2
	//DEBUG_VALUE: buddy_search_for_pointer:context <- $r1
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r0
	//DEBUG_VALUE: real_index <- 0
	.loc	2 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:13
	move r7, 0
	lsl r8, r4, r6
.Ltmp102:
	//DEBUG_VALUE: highlight_target_bit <- $r8
	lsl r4, r5, r6
.Ltmp103:
	//DEBUG_VALUE: loaded_case <- undef
	//DEBUG_VALUE: real_index <- $r7
	//DEBUG_VALUE: highlight_buddy_bit <- $r4
	.loc	2 307 57 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:307:57
	jeq r2, 0, .LBB1_16
.Ltmp104:
.LBB1_15:
	//DEBUG_VALUE: highlight_target_bit <- $r8
	//DEBUG_VALUE: real_index <- $r7
	//DEBUG_VALUE: highlight_buddy_bit <- $r4
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 1, DW_OP_constu 6, DW_OP_minus, DW_OP_stack_value] $r2
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- $r2
	//DEBUG_VALUE: buddy_search_for_pointer:context <- $r1
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r0
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:0
	lsl_add r5, r3, r7, 2
	lw r5, r5, 0
.Ltmp105:
	//DEBUG_VALUE: loaded_case <- $r5
	and r6, r8, r5, z, .LBB1_16
.Ltmp106:
// %bb.18:
	//DEBUG_VALUE: highlight_target_bit <- $r8
	//DEBUG_VALUE: real_index <- $r7
	//DEBUG_VALUE: loaded_case <- $r5
	//DEBUG_VALUE: highlight_buddy_bit <- $r4
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 1, DW_OP_constu 6, DW_OP_minus, DW_OP_stack_value] $r2
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- $r2
	//DEBUG_VALUE: buddy_search_for_pointer:context <- $r1
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r0
	.loc	2 316 26 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:316:26
	and r4, r4, r5, z, .LBB1_3
.Ltmp107:
// %bb.19:
	//DEBUG_VALUE: highlight_target_bit <- $r8
	//DEBUG_VALUE: real_index <- $r7
	//DEBUG_VALUE: loaded_case <- $r5
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 1, DW_OP_constu 6, DW_OP_minus, DW_OP_stack_value] $r2
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- $r2
	//DEBUG_VALUE: buddy_search_for_pointer:context <- $r1
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r0
	.loc	2 322 41                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:322:41
	lsr r0, r0, 1
.Ltmp108:
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r0
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- [DW_OP_constu 1, DW_OP_minus, DW_OP_stack_value] $r2
	.loc	2 0 41 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:41
	add r2, r2, -1
.Ltmp109:
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- $r2
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r0
	.loc	2 267 47 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:267:47
	lsl r4, one, r0
.Ltmp110:
	//DEBUG_VALUE: highlight_target_bit <- $r4
	.loc	2 270 14                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:270:14
	clz r5, r4
.Ltmp111:
	.loc	2 270 56 is_stmt 0              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:270:56
	and r5, r5, 1
.Ltmp112:
	.loc	2 270 13                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:270:13
	jneq r5, 0, .LBB1_7
	jump .LBB1_6
.Ltmp113:
.LBB1_16:
	//DEBUG_VALUE: highlight_target_bit <- $r8
	//DEBUG_VALUE: real_index <- $r7
	//DEBUG_VALUE: highlight_buddy_bit <- $r4
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 1, DW_OP_constu 6, DW_OP_minus, DW_OP_stack_value] $r2
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- $r2
	//DEBUG_VALUE: buddy_search_for_pointer:context <- $r1
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r0
	.loc	2 308 35 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:308:35
	sw r1, 0, r2
	.loc	2 309 33                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:309:33
	sw r1, 4, r7
	.loc	2 310 43                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:310:43
	sw r1, 8, r8
	.loc	2 311 42                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:311:42
	sw r1, 12, r4
.Ltmp114:
	.loc	2 325 1                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:325:1
	jump r23
.Ltmp115:
.Lfunc_end1:
	.size	buddy_search_for_pointer, .Lfunc_end1-buddy_search_for_pointer
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.buddy_search_for_pointer
	.long	.Lfunc_begin1
	.byte	0
	.section	.text.buddy_search_for_pointer,"ax",@progbits
                                        // -- End function
	.section	.text.safe_buddy_free,"ax",@progbits
	.globl	safe_buddy_free                 // -- Begin function safe_buddy_free
	.type	safe_buddy_free,@function
safe_buddy_free:                        // @safe_buddy_free
.Lfunc_begin2:
	.loc	2 392 0                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:392:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: safe_buddy_free:pointer <- $r0
	//DEBUG_VALUE: safe_buddy_free:pointer <- $r0
	//DEBUG_VALUE: buddy_search_for_pointer:pointer <- $r0
	//DEBUG_VALUE: buddy_search_for_pointer:pointer <- $r0
	//DEBUG_VALUE: buddy_search_for_pointer:context <- undef
	.cfi_def_cfa_offset 0
	.loc	2 252 35 prologue_end           // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:252:35
	and r1, r0, 7, nz, .LBB2_3
.Ltmp116:
// %bb.1:
	//DEBUG_VALUE: buddy_search_for_pointer:pointer <- $r0
	//DEBUG_VALUE: safe_buddy_free:pointer <- $r0
	.loc	2 0 35 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:35
	lw r2, zero, __buddy_heap_start
	.loc	2 252 46                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:252:46
	jgtu r2, r0, .LBB2_3
.Ltmp117:
// %bb.2:
	//DEBUG_VALUE: buddy_search_for_pointer:pointer <- $r0
	//DEBUG_VALUE: safe_buddy_free:pointer <- $r0
	.loc	2 253 45 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:253:45
	lw r1, zero, __BUDDY_SIZE_OF_HEAP__
	.loc	2 253 43 is_stmt 0              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:253:43
	add r1, r2, r1
	.loc	2 253 68                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:253:68
	add r1, r1, -1
.Ltmp118:
	.loc	2 252 9 is_stmt 1               // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:252:9
	jgeu r1, r0, .LBB2_4
.Ltmp119:
.LBB2_3:
	.loc	2 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:9
	move r0, 28
	sw id4, __errno, r0
.Ltmp120:
	.loc	2 401 1 is_stmt 1               // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:401:1
	jump r23
.LBB2_4:
.Ltmp121:
	//DEBUG_VALUE: buddy_search_for_pointer:pointer <- $r0
	//DEBUG_VALUE: safe_buddy_free:pointer <- $r0
	.loc	2 262 33                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:262:33
	lbu r3, zero, __BUDDY_NUMBER_OF_LEVELS__
.Ltmp122:
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- [DW_OP_constu 1, DW_OP_minus, DW_OP_stack_value] $r3
	.loc	2 0 33 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:33
	lw r1, zero, __buddy_blocks
	.loc	2 260 44 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:260:44
	sub r0, r0, r2
.Ltmp123:
	.loc	2 260 66 is_stmt 0              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:260:66
	asr r2, r0, 4
.Ltmp124:
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r2
	.loc	2 264 5 is_stmt 1               // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:264:5
	add r0, r3, -2
.Ltmp125:
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- [DW_OP_plus_uconst 1, DW_OP_stack_value] $r0
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r2
	.loc	2 267 47                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:267:47
	lsl r3, one, r2
.Ltmp126:
	//DEBUG_VALUE: highlight_target_bit <- $r3
	.loc	2 270 14                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:270:14
	clz r4, r3
	.loc	2 270 56 is_stmt 0              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:270:56
	and r4, r4, 1, z, .LBB2_6
.Ltmp127:
.LBB2_7:
	//DEBUG_VALUE: highlight_target_bit <- $r3
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r2
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- [DW_OP_plus_uconst 1, DW_OP_stack_value] $r0
	.loc	2 0 56                          // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:56
	lsl r5, r3, 1
.Ltmp128:
	//DEBUG_VALUE: highlight_buddy_bit <- $r5
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 2, DW_OP_constu 5, DW_OP_minus, DW_OP_stack_value] $r0
	.loc	2 282 34 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:282:34
	add r4, r0, -3, mi, .LBB2_9
.Ltmp129:
.LBB2_10:
	//DEBUG_VALUE: highlight_buddy_bit <- $r5
	//DEBUG_VALUE: highlight_target_bit <- $r3
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r2
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 2, DW_OP_constu 5, DW_OP_minus, DW_OP_stack_value] $r0
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- [DW_OP_plus_uconst 1, DW_OP_stack_value] $r0
	.loc	2 0 34 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:34
	move r6, 0
.Ltmp130:
	//DEBUG_VALUE: highlight_target_bit <- undef
	//DEBUG_VALUE: highlight_buddy_bit <- undef
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 2, DW_OP_constu 6, DW_OP_minus, DW_OP_stack_value] $r0
	//DEBUG_VALUE: real_index <- 0
	.loc	2 297 13 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:297:13
	add r4, r0, -4, mi, .LBB2_12
.Ltmp131:
.LBB2_13:
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r2
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 2, DW_OP_constu 6, DW_OP_minus, DW_OP_stack_value] $r0
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- [DW_OP_plus_uconst 1, DW_OP_stack_value] $r0
	//DEBUG_VALUE: real_index <- 0
	.loc	2 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:13
	lsl r4, one, r4
	lsr_add r7, r4, r2, 5, true, .LBB2_14
.Ltmp132:
.LBB2_6:
	//DEBUG_VALUE: highlight_target_bit <- $r3
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r2
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- [DW_OP_plus_uconst 1, DW_OP_stack_value] $r0
	lsr r5, r3, 1
.Ltmp133:
	//DEBUG_VALUE: highlight_buddy_bit <- $r5
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 2, DW_OP_constu 5, DW_OP_minus, DW_OP_stack_value] $r0
	.loc	2 282 34 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:282:34
	add r4, r0, -3, pl, .LBB2_10
.Ltmp134:
.LBB2_9:
	//DEBUG_VALUE: highlight_buddy_bit <- $r5
	//DEBUG_VALUE: highlight_target_bit <- $r3
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r2
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 2, DW_OP_constu 5, DW_OP_minus, DW_OP_stack_value] $r0
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- [DW_OP_plus_uconst 1, DW_OP_stack_value] $r0
	.loc	2 0 34 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:34
	add r4, r0, 1
	move r6, -2
	lsl r4, r6, r4
	add r6, r4, 32
.Ltmp135:
	//DEBUG_VALUE: highlight_target_bit <- undef
	//DEBUG_VALUE: highlight_buddy_bit <- undef
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 2, DW_OP_constu 6, DW_OP_minus, DW_OP_stack_value] $r0
	//DEBUG_VALUE: real_index <- 0
	.loc	2 297 13 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:297:13
	add r4, r0, -4, pl, .LBB2_13
.Ltmp136:
.LBB2_12:
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r2
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 2, DW_OP_constu 6, DW_OP_minus, DW_OP_stack_value] $r0
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- [DW_OP_plus_uconst 1, DW_OP_stack_value] $r0
	//DEBUG_VALUE: real_index <- 0
	.loc	2 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:13
	move r7, 0
.Ltmp137:
.LBB2_14:
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r2
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 2, DW_OP_constu 6, DW_OP_minus, DW_OP_stack_value] $r0
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- [DW_OP_plus_uconst 1, DW_OP_stack_value] $r0
	//DEBUG_VALUE: real_index <- 0
	.loc	2 303 36 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:303:36
	lsl_add r4, r1, r7, 2
	lw r8, r4, 0
.Ltmp138:
	//DEBUG_VALUE: loaded_case <- $r8
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:0
	lsl r4, r3, r6
.Ltmp139:
	//DEBUG_VALUE: highlight_target_bit <- $r4
	lsl r5, r5, r6
.Ltmp140:
	//DEBUG_VALUE: real_index <- $r7
	//DEBUG_VALUE: highlight_buddy_bit <- $r5
	.loc	2 307 57 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:307:57
	jeq r0, -1, .LBB2_18
.Ltmp141:
// %bb.15:
	//DEBUG_VALUE: loaded_case <- $r8
	//DEBUG_VALUE: real_index <- $r7
	//DEBUG_VALUE: highlight_buddy_bit <- $r5
	//DEBUG_VALUE: highlight_target_bit <- $r4
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r2
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 2, DW_OP_constu 6, DW_OP_minus, DW_OP_stack_value] $r0
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- [DW_OP_plus_uconst 1, DW_OP_stack_value] $r0
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:0
	and r3, r4, r8, z, .LBB2_18
.Ltmp142:
// %bb.16:
	//DEBUG_VALUE: loaded_case <- $r8
	//DEBUG_VALUE: real_index <- $r7
	//DEBUG_VALUE: highlight_buddy_bit <- $r5
	//DEBUG_VALUE: highlight_target_bit <- $r4
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r2
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 2, DW_OP_constu 6, DW_OP_minus, DW_OP_stack_value] $r0
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- [DW_OP_plus_uconst 1, DW_OP_stack_value] $r0
	.loc	2 316 26 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:316:26
	and r3, r5, r8, z, .LBB2_3
.Ltmp143:
// %bb.17:
	//DEBUG_VALUE: loaded_case <- $r8
	//DEBUG_VALUE: real_index <- $r7
	//DEBUG_VALUE: highlight_buddy_bit <- $r5
	//DEBUG_VALUE: highlight_target_bit <- $r4
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r2
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_plus_uconst 2, DW_OP_constu 6, DW_OP_minus, DW_OP_stack_value] $r0
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- [DW_OP_plus_uconst 1, DW_OP_stack_value] $r0
	.loc	2 322 41                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:322:41
	lsr r2, r2, 1
.Ltmp144:
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r2
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- [DW_OP_plus_uconst 1, DW_OP_constu 1, DW_OP_minus, DW_OP_stack_value] $r0
	.loc	2 0 41 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:41
	add r0, r0, -1
.Ltmp145:
	//DEBUG_VALUE: buddy_search_for_pointer:target_level <- [DW_OP_plus_uconst 1, DW_OP_stack_value] $r0
	//DEBUG_VALUE: buddy_search_for_pointer:index_in_level <- $r2
	.loc	2 267 47 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:267:47
	lsl r3, one, r2
.Ltmp146:
	//DEBUG_VALUE: highlight_target_bit <- $r3
	.loc	2 270 14                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:270:14
	clz r4, r3
	.loc	2 270 56 is_stmt 0              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:270:56
	and r4, r4, 1
.Ltmp147:
	.loc	2 270 13                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:270:13
	jneq r4, 0, .LBB2_7
	jump .LBB2_6
.Ltmp148:
.LBB2_18:
	//DEBUG_VALUE: safe_buddy_free:context <- [DW_OP_constu 1, DW_OP_minus, DW_OP_stack_value, DW_OP_LLVM_fragment 0 32] undef
	//DEBUG_VALUE: safe_buddy_free:context <- [DW_OP_LLVM_fragment 32 32] $r7
	//DEBUG_VALUE: safe_buddy_free:context <- [DW_OP_LLVM_fragment 64 32] $r4
	//DEBUG_VALUE: safe_buddy_free:context <- [DW_OP_LLVM_fragment 96 32] $r5
	//DEBUG_VALUE: safe_buddy_free:index <- $r2
	.loc	2 397 9 is_stmt 1               // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:397:9
	jeq r2, -1, .LBB2_32
.Ltmp149:
// %bb.19:
	//DEBUG_VALUE: safe_buddy_free:context <- [DW_OP_LLVM_fragment 32 32] $r7
	//DEBUG_VALUE: safe_buddy_free:context <- [DW_OP_LLVM_fragment 96 32] $r5
	//DEBUG_VALUE: safe_buddy_free:context <- [DW_OP_LLVM_fragment 64 32] $r4
	//DEBUG_VALUE: safe_buddy_free:index <- $r2
	.loc	2 303 36                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:303:36
	lsl_add r3, r1, r7, 2
.Ltmp150:
	.loc	2 398 44                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:398:44
	or r6, r8, r4
	sw r3, 0, r6
.Ltmp151:
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:current_level_freeing <- [DW_OP_constu 1, DW_OP_minus, DW_OP_stack_value] undef
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:highlight_target_bit <- undef
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:highlight_buddy_bit <- undef
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:index <- $r2
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:loaded_case <- undef
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:real_index <- undef
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:context <- undef
	.loc	2 336 5                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:336:5
	jneq r0, -1, .LBB2_20
.Ltmp152:
.LBB2_32:
	.loc	2 401 1                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:401:1
	jump r23
.LBB2_30:                               //   in Loop: Header=BB2_20 Depth=1
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:index <- $r3
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:current_level_freeing <- $r0
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:real_index <- 0
	.loc	2 0 1 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:1
	lsl r7, one, r7
	lsr_add r2, r7, r2, 6
.LBB2_31:                               //   in Loop: Header=BB2_20 Depth=1
.Ltmp153:
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:index <- $r3
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:current_level_freeing <- $r0
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:real_index <- 0
	.loc	2 385 23 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:385:23
	lsl_add r2, r1, r2, 2
	lw r7, r2, 0
.Ltmp154:
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:0
	lsl r4, r4, r6
.Ltmp155:
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:highlight_target_bit <- $r4
	lsl r5, r5, r6
.Ltmp156:
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:highlight_buddy_bit <- $r5
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:real_index <- undef
	.loc	2 385 50                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:385:50
	or r6, r7, r4
.Ltmp157:
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:loaded_case <- $r6
	.loc	2 386 36 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:386:36
	sw r2, 0, r6
	move r2, r3
.Ltmp158:
	.loc	2 336 34                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:336:34
	add r0, r0, -1
.Ltmp159:
	.loc	2 336 5 is_stmt 0               // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:336:5
	jeq r0, -1, .LBB2_32
.Ltmp160:
.LBB2_20:                               // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:loaded_case <- $r6
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:index <- $r2
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:highlight_buddy_bit <- $r5
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:highlight_target_bit <- $r4
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:current_level_freeing <- undef
	.loc	2 338 73 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:338:73
	and r3, r5, r6, z, .LBB2_32
.Ltmp161:
// %bb.21:                              //   in Loop: Header=BB2_20 Depth=1
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:loaded_case <- $r6
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:highlight_buddy_bit <- $r5
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:highlight_target_bit <- $r4
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:index <- $r2
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:0
	and r3, r4, r6, z, .LBB2_32
.Ltmp162:
// %bb.22:                              //   in Loop: Header=BB2_20 Depth=1
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:loaded_case <- $r6
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:highlight_buddy_bit <- $r5
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:highlight_target_bit <- $r4
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:index <- $r2
	.loc	2 343 23 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:343:23
	lsr r3, r2, 1
.Ltmp163:
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:current_level_freeing <- $r0
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:index <- $r3
	.loc	2 349 34                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:349:34
	lsl r4, one, r3
.Ltmp164:
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:highlight_target_bit <- $r4
	.loc	2 351 14                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:351:14
	clz r5, r4
.Ltmp165:
	.loc	2 351 56 is_stmt 0              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:351:56
	and r5, r5, 1, z, .LBB2_23
.Ltmp166:
// %bb.24:                              //   in Loop: Header=BB2_20 Depth=1
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:loaded_case <- $r6
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:highlight_target_bit <- $r4
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:index <- $r3
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:current_level_freeing <- $r0
	.loc	2 0 56                          // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:56
	lsl r5, r4, 1
.Ltmp167:
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:highlight_buddy_bit <- $r5
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_constu 5, DW_OP_minus, DW_OP_stack_value] undef
	.loc	2 362 34 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:362:34
	add r6, r0, -4, mi, .LBB2_26
.Ltmp168:
.LBB2_27:                               //   in Loop: Header=BB2_20 Depth=1
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:highlight_buddy_bit <- $r5
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:highlight_target_bit <- $r4
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:index <- $r3
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:current_level_freeing <- $r0
	.loc	2 0 34 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:34
	move r6, 0
.Ltmp169:
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:real_index <- 0
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:highlight_buddy_bit <- undef
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:highlight_target_bit <- undef
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_constu 6, DW_OP_minus, DW_OP_stack_value] undef
	.loc	2 379 13 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:379:13
	add r7, r0, -5
	jges r7, 0, .LBB2_30
	jump .LBB2_29
.Ltmp170:
.LBB2_23:                               //   in Loop: Header=BB2_20 Depth=1
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:loaded_case <- $r6
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:highlight_target_bit <- $r4
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:index <- $r3
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:current_level_freeing <- $r0
	.loc	2 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:13
	lsr r5, r4, 1
.Ltmp171:
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:highlight_buddy_bit <- $r5
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_constu 5, DW_OP_minus, DW_OP_stack_value] undef
	.loc	2 362 34 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:362:34
	add r6, r0, -4, pl, .LBB2_27
.Ltmp172:
.LBB2_26:                               //   in Loop: Header=BB2_20 Depth=1
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:highlight_buddy_bit <- $r5
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:highlight_target_bit <- $r4
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:index <- $r3
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:current_level_freeing <- $r0
	.loc	2 0 34 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:34
	move r6, -2
	lsl r6, r6, r0
	add r6, r6, 32
.Ltmp173:
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:real_index <- 0
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:highlight_buddy_bit <- undef
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:highlight_target_bit <- undef
	//DEBUG_VALUE: target_level_clamped <- [DW_OP_constu 6, DW_OP_minus, DW_OP_stack_value] undef
	.loc	2 379 13 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:379:13
	add r7, r0, -5, pl, .LBB2_30
.Ltmp174:
.LBB2_29:                               //   in Loop: Header=BB2_20 Depth=1
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:index <- $r3
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:current_level_freeing <- $r0
	//DEBUG_VALUE: buddy_free_fusion_of_blocks:real_index <- 0
	.loc	2 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:0:13
	move r2, 0, true, .LBB2_31
.Lfunc_end2:
	.size	safe_buddy_free, .Lfunc_end2-safe_buddy_free
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.safe_buddy_free
	.long	.Lfunc_begin2
	.byte	0
	.section	.text.safe_buddy_free,"ax",@progbits
                                        // -- End function
	.section	.text.buddy_alloc,"ax",@progbits
	.globl	buddy_alloc                     // -- Begin function buddy_alloc
	.type	buddy_alloc,@function
buddy_alloc:                            // @buddy_alloc
.Lfunc_begin3:
	.loc	2 406 0 is_stmt 1               // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:406:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: buddy_alloc:size <- $r0
	.cfi_def_cfa_offset -8
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 0, d22
	add r22, r22, 8
.Ltmp175:
	.loc	2 407 5 prologue_end            // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:407:5
	// inline asm
.Ltmp176:
	acquire zero, __atomic_bit___buddy_lock, nz, .Ltmp176
	// inline asm
	//DEBUG_VALUE: buddy_alloc:size <- $r0
	//DEBUG_VALUE: buddy_alloc:size <- $r0
	.loc	2 408 20                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:408:20
	call r23, safe_buddy_alloc
.Ltmp177:
	.loc	2 409 5                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:409:5
	// inline asm
.Ltmp178:
	release zero, __atomic_bit___buddy_lock, nz, .Ltmp178+1
	// inline asm
.Ltmp179:
	//DEBUG_VALUE: buddy_alloc:result <- $r0
	.loc	2 410 5                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:410:5
	ld d22, r22, -8
	jump r23
.Ltmp180:
.Lfunc_end3:
	.size	buddy_alloc, .Lfunc_end3-buddy_alloc
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.buddy_alloc
	.long	.Lfunc_begin3
	.byte	8
	.section	.text.buddy_alloc,"ax",@progbits
                                        // -- End function
	.section	.text.buddy_free,"ax",@progbits
	.globl	buddy_free                      // -- Begin function buddy_free
	.type	buddy_free,@function
buddy_free:                             // @buddy_free
.Lfunc_begin4:
	.loc	2 416 0                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:416:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: buddy_free:pointer <- $r0
	.cfi_def_cfa_offset -8
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 0, d22
	add r22, r22, 8
.Ltmp181:
	.loc	2 417 5 prologue_end            // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:417:5
	// inline asm
.Ltmp182:
	acquire zero, __atomic_bit___buddy_lock, nz, .Ltmp182
	// inline asm
	//DEBUG_VALUE: buddy_free:pointer <- $r0
	//DEBUG_VALUE: buddy_free:pointer <- $r0
	.loc	2 418 5                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:418:5
	call r23, safe_buddy_free
.Ltmp183:
	.loc	2 419 5                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:419:5
	// inline asm
.Ltmp184:
	release zero, __atomic_bit___buddy_lock, nz, .Ltmp184+1
	// inline asm
	.loc	2 420 1                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:420:1
	ld d22, r22, -8
	jump r23
.Ltmp185:
.Lfunc_end4:
	.size	buddy_free, .Lfunc_end4-buddy_free
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.buddy_free
	.long	.Lfunc_begin4
	.byte	8
	.section	.text.buddy_free,"ax",@progbits
                                        // -- End function
	.section	.text.buddy_init,"ax",@progbits
	.globl	buddy_init                      // -- Begin function buddy_init
	.type	buddy_init,@function
buddy_init:                             // @buddy_init
.Lfunc_begin5:
	.loc	2 439 0                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:439:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: buddy_init:size_of_heap <- $r0
	.cfi_def_cfa_offset -16
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 8, d22
	add r22, r22, 16
	.cfi_offset 15, -16
	.cfi_offset 14, -12
.Ltmp186:
	sd r22, -16, d14
	.loc	2 440 9 prologue_end            // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:440:9
	lbu r1, zero, __buddy_init_done
.Ltmp187:
	//DEBUG_VALUE: buddy_init:size_of_heap <- $r0
	.loc	2 440 9 is_stmt 0               // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:440:9
	jnz r1, .LBB5_2
.Ltmp188:
// %bb.1:
	//DEBUG_VALUE: buddy_init:size_of_heap <- $r0
	.loc	2 441 9 is_stmt 1               // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:441:9
	// inline asm
.Ltmp189:
	release zero, __atomic_bit___buddy_lock, nz, .Ltmp189+1
	// inline asm
	.loc	2 443 32                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:443:32
	sw zero, __BUDDY_SIZE_OF_HEAP__, r0
	.loc	2 445 35                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:445:35
	clz r1, r0
.Ltmp190:
	//DEBUG_VALUE: power_of_2 <- $r1
	.loc	2 446 31                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:446:31
	xor r2, r1, 31
	.loc	2 446 29 is_stmt 0              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:446:29
	sb zero, __BUDDY_MAX_POWER__, r2
	.loc	2 448 58 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:448:58
	sub r1, 28, r1
.Ltmp191:
	.loc	2 448 36 is_stmt 0              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:448:36
	sb zero, __BUDDY_NUMBER_OF_LEVELS__, r1
	.loc	2 450 54 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:450:54
	and r1, r1, 255
	.loc	2 450 81 is_stmt 0              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:450:81
	add r1, r1, -5
	move r2, 4
	.loc	2 450 87                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:450:87
	lsl r14, r2, r1
.Ltmp192:
	//DEBUG_VALUE: blocks_in_buddy_blocks <- $r14
	.loc	2 451 49 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:451:49
	add r0, r14, r0
.Ltmp193:
	.loc	2 451 26 is_stmt 0              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:451:26
	call r23, mem_alloc
.Ltmp194:
	.loc	2 451 24                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:451:24
	sw zero, __buddy_blocks, r0
	.loc	2 453 45 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:453:45
	add r1, r0, r14
	.loc	2 453 28 is_stmt 0              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:453:28
	sw zero, __buddy_heap_start, r1
	move r1, 2147483647
	.loc	2 455 27 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:455:27
	sw r0, 0, r1
	.loc	2 456 17                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:456:17
	add r0, r0, 4
	.loc	2 456 65 is_stmt 0              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:456:65
	add r2, r14, -4
	move r1, 255
	.loc	2 456 9                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:456:9
	call r23, memset
.Ltmp195:
	.loc	2 457 27 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:457:27
	move r0, __buddy_init_done
	sb r0, 0, 1
.Ltmp196:
.LBB5_2:
	.loc	2 459 1                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:459:1
	ld d14, r22, -16
	ld d22, r22, -8
	jump r23
.Ltmp197:
.Lfunc_end5:
	.size	buddy_init, .Lfunc_end5-buddy_init
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.buddy_init
	.long	.Lfunc_begin5
	.byte	16
	.section	.text.buddy_init,"ax",@progbits
                                        // -- End function
	.section	.text.buddy_reset,"ax",@progbits
	.globl	buddy_reset                     // -- Begin function buddy_reset
	.type	buddy_reset,@function
buddy_reset:                            // @buddy_reset
.Lfunc_begin6:
	.loc	2 464 0                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:464:0
	.cfi_startproc
// %bb.0:
	.cfi_def_cfa_offset -8
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 0, d22
	add r22, r22, 8
.Ltmp198:
	.loc	2 465 5 prologue_end            // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:465:5
	// inline asm
.Ltmp199:
	acquire zero, __atomic_bit___buddy_lock, nz, .Ltmp199
	// inline asm
	.loc	2 467 5                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:467:5
	lw r0, zero, __buddy_blocks
	move r1, 2147483647
	.loc	2 467 23 is_stmt 0              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:467:23
	sw r0, 0, r1
	.loc	2 470 17 is_stmt 1              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:470:17
	lbu r1, zero, __BUDDY_NUMBER_OF_LEVELS__
	.loc	2 468 13                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:468:13
	add r0, r0, 4
	.loc	2 470 44                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:470:44
	add r1, r1, -5
	move r2, 4
	.loc	2 470 50 is_stmt 0              // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:470:50
	lsl r1, r2, r1
	.loc	2 470 56                        // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:470:56
	add r2, r1, -4
	move r1, 255
	.loc	2 468 5 is_stmt 1               // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:468:5
	call r23, memset
.Ltmp200:
	.loc	2 472 5                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:472:5
	// inline asm
.Ltmp201:
	release zero, __atomic_bit___buddy_lock, nz, .Ltmp201+1
	// inline asm
	.loc	2 473 1                         // uPIMulator_frontend/sdk/syslib/buddy_alloc.c:473:1
	ld d22, r22, -8
	jump r23
.Ltmp202:
.Lfunc_end6:
	.size	buddy_reset, .Lfunc_end6-buddy_reset
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.buddy_reset
	.long	.Lfunc_begin6
	.byte	8
	.section	.text.buddy_reset,"ax",@progbits
                                        // -- End function
	.type	__BUDDY_SIZE_OF_HEAP__,@object  // @__BUDDY_SIZE_OF_HEAP__
	.section	.bss.__BUDDY_SIZE_OF_HEAP__,"aw",@nobits
	.p2align	2
__BUDDY_SIZE_OF_HEAP__:
	.long	0                               // 0x0
	.size	__BUDDY_SIZE_OF_HEAP__, 4

	.type	__BUDDY_MAX_POWER__,@object     // @__BUDDY_MAX_POWER__
	.section	.bss.__BUDDY_MAX_POWER__,"aw",@nobits
	.p2align	2
__BUDDY_MAX_POWER__:
	.byte	0                               // 0x0
	.size	__BUDDY_MAX_POWER__, 1

	.type	__BUDDY_NUMBER_OF_LEVELS__,@object // @__BUDDY_NUMBER_OF_LEVELS__
	.section	.bss.__BUDDY_NUMBER_OF_LEVELS__,"aw",@nobits
	.p2align	2
__BUDDY_NUMBER_OF_LEVELS__:
	.byte	0                               // 0x0
	.size	__BUDDY_NUMBER_OF_LEVELS__, 1

	.type	__buddy_blocks,@object          // @__buddy_blocks
	.section	.bss.__buddy_blocks,"aw",@nobits
	.p2align	2
__buddy_blocks:
	.long	0
	.size	__buddy_blocks, 4

	.type	__buddy_heap_start,@object      // @__buddy_heap_start
	.section	.bss.__buddy_heap_start,"aw",@nobits
	.p2align	2
__buddy_heap_start:
	.long	0
	.size	__buddy_heap_start, 4

	.type	__atomic_bit___buddy_lock,@object // @__atomic_bit___buddy_lock
	.section	.atomic,"aw",@progbits
	.globl	__atomic_bit___buddy_lock
__atomic_bit___buddy_lock:
	.byte	0                               // 0x0
	.size	__atomic_bit___buddy_lock, 1

	.type	__buddy_init_done,@object       // @__buddy_init_done
	.section	.bss.__buddy_init_done,"aw",@nobits
	.p2align	2
__buddy_init_done:
	.byte	0                               // 0x0
	.size	__buddy_init_done, 1

	.type	.Lswitch.table.safe_buddy_alloc,@object // @switch.table.safe_buddy_alloc
	.section	.rodata..Lswitch.table.safe_buddy_alloc,"a",@progbits
	.p2align	2
.Lswitch.table.safe_buddy_alloc:
	.long	1073741824                      // 0x40000000
	.long	805306368                       // 0x30000000
	.long	251658240                       // 0xf000000
	.long	16711680                        // 0xff0000
	.long	65535                           // 0xffff
	.size	.Lswitch.table.safe_buddy_alloc, 20

	.file	3 "/root" "uPIMulator_frontend/sdk/stdlib/stddef.h"
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp3-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp9-.Lfunc_begin0
	.long	.Ltmp10-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc1:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp1-.Lfunc_begin0
	.long	.Ltmp3-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc2:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp4-.Lfunc_begin0
	.short	5                               // Loc expr size
	.byte	114                             // DW_OP_breg2
	.byte	0                               // 0
	.byte	79                              // DW_OP_lit31
	.byte	39                              // DW_OP_xor
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc3:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp7-.Lfunc_begin0
	.long	.Ltmp9-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Ltmp16-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc4:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp8-.Lfunc_begin0
	.long	.Ltmp9-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp18-.Lfunc_begin0
	.long	.Ltmp19-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp20-.Lfunc_begin0
	.long	.Ltmp21-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	89                              // DW_OP_reg9
	.long	.Ltmp21-.Lfunc_begin0
	.long	.Ltmp55-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp55-.Lfunc_begin0
	.long	.Ltmp56-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	89                              // DW_OP_reg9
	.long	.Ltmp64-.Lfunc_begin0
	.long	.Ltmp66-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	117                             // DW_OP_breg5
	.byte	2                               // 2
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp73-.Lfunc_begin0
	.long	.Ltmp74-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	117                             // DW_OP_breg5
	.byte	2                               // 2
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp74-.Lfunc_begin0
	.long	.Ltmp75-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	89                              // DW_OP_reg9
	.long	.Ltmp75-.Lfunc_begin0
	.long	.Ltmp78-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	0
	.long	0
.Ldebug_loc5:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp26-.Lfunc_begin0
	.long	.Ltmp28-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp30-.Lfunc_begin0
	.long	.Ltmp31-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	90                              // DW_OP_reg10
	.long	0
	.long	0
.Ldebug_loc6:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp26-.Lfunc_begin0
	.long	.Ltmp32-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	87                              // DW_OP_reg7
	.long	.Ltmp33-.Lfunc_begin0
	.long	.Ltmp37-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	120                             // DW_OP_breg8
	.byte	1                               // 1
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp37-.Lfunc_begin0
	.long	.Ltmp38-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	120                             // DW_OP_breg8
	.byte	97                              // -31
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp56-.Lfunc_begin0
	.long	.Ltmp66-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	88                              // DW_OP_reg8
	.long	.Ltmp68-.Lfunc_begin0
	.long	.Ltmp70-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	88                              // DW_OP_reg8
	.long	.Ltmp71-.Lfunc_begin0
	.long	.Ltmp73-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	88                              // DW_OP_reg8
	.long	0
	.long	0
.Ldebug_loc7:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp30-.Lfunc_begin0
	.long	.Ltmp31-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	90                              // DW_OP_reg10
	.long	.Ltmp33-.Lfunc_begin0
	.long	.Ltmp37-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	86                              // DW_OP_reg6
	.long	.Ltmp37-.Lfunc_begin0
	.long	.Ltmp39-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	90                              // DW_OP_reg10
	.long	.Ltmp39-.Lfunc_begin0
	.long	.Ltmp40-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	86                              // DW_OP_reg6
	.long	.Ltmp41-.Lfunc_begin0
	.long	.Ltmp44-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	86                              // DW_OP_reg6
	.long	.Ltmp46-.Lfunc_begin0
	.long	.Ltmp73-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	86                              // DW_OP_reg6
	.long	0
	.long	0
.Ldebug_loc8:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp28-.Lfunc_begin0
	.long	.Ltmp31-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	32                              // DW_OP_not
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc9:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp33-.Lfunc_begin0
	.long	.Ltmp36-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	89                              // DW_OP_reg9
	.long	.Ltmp39-.Lfunc_begin0
	.long	.Ltmp40-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	89                              // DW_OP_reg9
	.long	.Ltmp41-.Lfunc_begin0
	.long	.Ltmp44-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	89                              // DW_OP_reg9
	.long	0
	.long	0
.Ldebug_loc10:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp34-.Lfunc_begin0
	.long	.Ltmp36-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	91                              // DW_OP_reg11
	.long	.Ltmp39-.Lfunc_begin0
	.long	.Ltmp40-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	91                              // DW_OP_reg11
	.long	.Ltmp41-.Lfunc_begin0
	.long	.Ltmp44-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	91                              // DW_OP_reg11
	.long	.Ltmp46-.Lfunc_begin0
	.long	.Ltmp51-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	91                              // DW_OP_reg11
	.long	.Ltmp52-.Lfunc_begin0
	.long	.Ltmp53-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	90                              // DW_OP_reg10
	.long	.Ltmp53-.Lfunc_begin0
	.long	.Ltmp56-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	88                              // DW_OP_reg8
	.long	.Ltmp60-.Lfunc_begin0
	.long	.Ltmp66-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	91                              // DW_OP_reg11
	.long	0
	.long	0
.Ldebug_loc11:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp35-.Lfunc_begin0
	.long	.Ltmp36-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	.Ltmp39-.Lfunc_begin0
	.long	.Ltmp40-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	.Ltmp41-.Lfunc_begin0
	.long	.Ltmp44-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	0
	.long	0
.Ldebug_loc12:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp42-.Lfunc_begin0
	.long	.Ltmp44-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	92                              // DW_OP_reg12
	.long	.Ltmp46-.Lfunc_begin0
	.long	.Ltmp73-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	92                              // DW_OP_reg12
	.long	0
	.long	0
.Ldebug_loc13:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp43-.Lfunc_begin0
	.long	.Ltmp44-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	93                              // DW_OP_reg13
	.long	.Ltmp46-.Lfunc_begin0
	.long	.Ltmp52-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	93                              // DW_OP_reg13
	.long	.Ltmp52-.Lfunc_begin0
	.long	.Ltmp53-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	88                              // DW_OP_reg8
	.long	0
	.long	0
.Ldebug_loc14:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp56-.Lfunc_begin0
	.long	.Ltmp57-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp57-.Lfunc_begin0
	.long	.Ltmp59-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	91                              // DW_OP_reg11
	.long	.Ltmp69-.Lfunc_begin0
	.long	.Ltmp70-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp72-.Lfunc_begin0
	.long	.Ltmp73-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc15:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp58-.Lfunc_begin0
	.long	.Ltmp59-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	87                              // DW_OP_reg7
	.long	0
	.long	0
.Ldebug_loc16:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Lfunc_begin1-.Lfunc_begin1
	.long	.Ltmp83-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp84-.Lfunc_begin1
	.long	.Ltmp86-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc17:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp85-.Lfunc_begin1
	.long	.Ltmp88-.Lfunc_begin1
	.short	3                               // Loc expr size
	.byte	116                             // DW_OP_breg4
	.byte	127                             // -1
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp88-.Lfunc_begin1
	.long	.Ltmp108-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp108-.Lfunc_begin1
	.long	.Ltmp109-.Lfunc_begin1
	.short	3                               // Loc expr size
	.byte	114                             // DW_OP_breg2
	.byte	127                             // -1
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp109-.Lfunc_begin1
	.long	.Lfunc_end1-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc18:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp87-.Lfunc_begin1
	.long	.Lfunc_end1-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc19:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp89-.Lfunc_begin1
	.long	.Ltmp93-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp95-.Lfunc_begin1
	.long	.Ltmp97-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	88                              // DW_OP_reg8
	.long	.Ltmp97-.Lfunc_begin1
	.long	.Ltmp100-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp102-.Lfunc_begin1
	.long	.Ltmp110-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	88                              // DW_OP_reg8
	.long	.Ltmp110-.Lfunc_begin1
	.long	.Ltmp113-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp113-.Lfunc_begin1
	.long	.Lfunc_end1-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	88                              // DW_OP_reg8
	.long	0
	.long	0
.Ldebug_loc20:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp91-.Lfunc_begin1
	.long	.Ltmp93-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp96-.Lfunc_begin1
	.long	.Ltmp97-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp98-.Lfunc_begin1
	.long	.Ltmp100-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp103-.Lfunc_begin1
	.long	.Ltmp107-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp113-.Lfunc_begin1
	.long	.Lfunc_end1-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	0
	.long	0
.Ldebug_loc21:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp91-.Lfunc_begin1
	.long	.Ltmp93-.Lfunc_begin1
	.short	5                               // Loc expr size
	.byte	114                             // DW_OP_breg2
	.byte	1                               // 1
	.byte	53                              // DW_OP_lit5
	.byte	28                              // DW_OP_minus
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp93-.Lfunc_begin1
	.long	.Ltmp97-.Lfunc_begin1
	.short	5                               // Loc expr size
	.byte	114                             // DW_OP_breg2
	.byte	1                               // 1
	.byte	54                              // DW_OP_lit6
	.byte	28                              // DW_OP_minus
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp98-.Lfunc_begin1
	.long	.Ltmp100-.Lfunc_begin1
	.short	5                               // Loc expr size
	.byte	114                             // DW_OP_breg2
	.byte	1                               // 1
	.byte	53                              // DW_OP_lit5
	.byte	28                              // DW_OP_minus
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp100-.Lfunc_begin1
	.long	.Ltmp109-.Lfunc_begin1
	.short	5                               // Loc expr size
	.byte	114                             // DW_OP_breg2
	.byte	1                               // 1
	.byte	54                              // DW_OP_lit6
	.byte	28                              // DW_OP_minus
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp113-.Lfunc_begin1
	.long	.Lfunc_end1-.Lfunc_begin1
	.short	5                               // Loc expr size
	.byte	114                             // DW_OP_breg2
	.byte	1                               // 1
	.byte	54                              // DW_OP_lit6
	.byte	28                              // DW_OP_minus
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc22:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp93-.Lfunc_begin1
	.long	.Ltmp96-.Lfunc_begin1
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp96-.Lfunc_begin1
	.long	.Ltmp97-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	87                              // DW_OP_reg7
	.long	.Ltmp100-.Lfunc_begin1
	.long	.Ltmp103-.Lfunc_begin1
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp103-.Lfunc_begin1
	.long	.Lfunc_end1-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	87                              // DW_OP_reg7
	.long	0
	.long	0
.Ldebug_loc23:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp105-.Lfunc_begin1
	.long	.Ltmp111-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	0
	.long	0
.Ldebug_loc24:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Lfunc_begin2-.Lfunc_begin2
	.long	.Ltmp119-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp121-.Lfunc_begin2
	.long	.Ltmp123-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc25:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Lfunc_begin2-.Lfunc_begin2
	.long	.Ltmp119-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp121-.Lfunc_begin2
	.long	.Ltmp123-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc26:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp122-.Lfunc_begin2
	.long	.Ltmp125-.Lfunc_begin2
	.short	3                               // Loc expr size
	.byte	115                             // DW_OP_breg3
	.byte	127                             // -1
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp125-.Lfunc_begin2
	.long	.Ltmp144-.Lfunc_begin2
	.short	3                               // Loc expr size
	.byte	112                             // DW_OP_breg0
	.byte	1                               // 1
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp144-.Lfunc_begin2
	.long	.Ltmp145-.Lfunc_begin2
	.short	5                               // Loc expr size
	.byte	112                             // DW_OP_breg0
	.byte	1                               // 1
	.byte	49                              // DW_OP_lit1
	.byte	28                              // DW_OP_minus
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp145-.Lfunc_begin2
	.long	.Ltmp148-.Lfunc_begin2
	.short	3                               // Loc expr size
	.byte	112                             // DW_OP_breg0
	.byte	1                               // 1
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc27:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp124-.Lfunc_begin2
	.long	.Ltmp148-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc28:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp126-.Lfunc_begin2
	.long	.Ltmp130-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp132-.Lfunc_begin2
	.long	.Ltmp135-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp139-.Lfunc_begin2
	.long	.Ltmp146-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp146-.Lfunc_begin2
	.long	.Ltmp148-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc29:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp128-.Lfunc_begin2
	.long	.Ltmp130-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp133-.Lfunc_begin2
	.long	.Ltmp135-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp140-.Lfunc_begin2
	.long	.Ltmp148-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	0
	.long	0
.Ldebug_loc30:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp128-.Lfunc_begin2
	.long	.Ltmp130-.Lfunc_begin2
	.short	5                               // Loc expr size
	.byte	112                             // DW_OP_breg0
	.byte	2                               // 2
	.byte	53                              // DW_OP_lit5
	.byte	28                              // DW_OP_minus
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp130-.Lfunc_begin2
	.long	.Ltmp132-.Lfunc_begin2
	.short	5                               // Loc expr size
	.byte	112                             // DW_OP_breg0
	.byte	2                               // 2
	.byte	54                              // DW_OP_lit6
	.byte	28                              // DW_OP_minus
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp133-.Lfunc_begin2
	.long	.Ltmp135-.Lfunc_begin2
	.short	5                               // Loc expr size
	.byte	112                             // DW_OP_breg0
	.byte	2                               // 2
	.byte	53                              // DW_OP_lit5
	.byte	28                              // DW_OP_minus
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp135-.Lfunc_begin2
	.long	.Ltmp145-.Lfunc_begin2
	.short	5                               // Loc expr size
	.byte	112                             // DW_OP_breg0
	.byte	2                               // 2
	.byte	54                              // DW_OP_lit6
	.byte	28                              // DW_OP_minus
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc31:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp130-.Lfunc_begin2
	.long	.Ltmp132-.Lfunc_begin2
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp135-.Lfunc_begin2
	.long	.Ltmp140-.Lfunc_begin2
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp140-.Lfunc_begin2
	.long	.Ltmp148-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	87                              // DW_OP_reg7
	.long	0
	.long	0
.Ldebug_loc32:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp138-.Lfunc_begin2
	.long	.Ltmp148-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	88                              // DW_OP_reg8
	.long	0
	.long	0
.Ldebug_loc33:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp148-.Lfunc_begin2
	.long	.Ltmp152-.Lfunc_begin2
	.short	11                              // Loc expr size
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	87                              // DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	85                              // DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc34:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp148-.Lfunc_begin2
	.long	.Ltmp152-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc35:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp153-.Lfunc_begin2
	.long	.Ltmp159-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp163-.Lfunc_begin2
	.long	.Ltmp174-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc36:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp155-.Lfunc_begin2
	.long	.Ltmp169-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp170-.Lfunc_begin2
	.long	.Ltmp173-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	0
	.long	0
.Ldebug_loc37:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp156-.Lfunc_begin2
	.long	.Ltmp165-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp167-.Lfunc_begin2
	.long	.Ltmp169-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp171-.Lfunc_begin2
	.long	.Ltmp173-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	0
	.long	0
.Ldebug_loc38:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp151-.Lfunc_begin2
	.long	.Ltmp152-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp153-.Lfunc_begin2
	.long	.Ltmp160-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp160-.Lfunc_begin2
	.long	.Ltmp163-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp163-.Lfunc_begin2
	.long	.Ltmp174-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc39:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp157-.Lfunc_begin2
	.long	.Ltmp168-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	86                              // DW_OP_reg6
	.long	.Ltmp170-.Lfunc_begin2
	.long	.Ltmp172-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	86                              // DW_OP_reg6
	.long	0
	.long	0
.Ldebug_loc40:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp153-.Lfunc_begin2
	.long	.Ltmp156-.Lfunc_begin2
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp169-.Lfunc_begin2
	.long	.Ltmp170-.Lfunc_begin2
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp173-.Lfunc_begin2
	.long	.Ltmp174-.Lfunc_begin2
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc41:
	.long	-1
	.long	.Lfunc_begin3                   //   base address
	.long	.Ltmp179-.Lfunc_begin3
	.long	.Lfunc_end3-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc42:
	.long	-1
	.long	.Lfunc_begin5                   //   base address
	.long	.Lfunc_begin5-.Lfunc_begin5
	.long	.Ltmp193-.Lfunc_begin5
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc43:
	.long	-1
	.long	.Lfunc_begin5                   //   base address
	.long	.Ltmp190-.Lfunc_begin5
	.long	.Ltmp191-.Lfunc_begin5
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc44:
	.long	-1
	.long	.Lfunc_begin5                   //   base address
	.long	.Ltmp192-.Lfunc_begin5
	.long	.Ltmp196-.Lfunc_begin5
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	11                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	12                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	13                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	14                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	1                               // DW_CHILDREN_yes
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	15                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	16                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	17                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	18                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	19                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	20                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	21                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	22                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	5                               // DW_FORM_data2
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	23                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	24                              // Abbreviation Code
	.byte	19                              // DW_TAG_structure_type
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	25                              // Abbreviation Code
	.byte	13                              // DW_TAG_member
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	56                              // DW_AT_data_member_location
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	26                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	5                               // DW_FORM_data2
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	27                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	5                               // DW_FORM_data2
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	28                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	5                               // DW_FORM_data2
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	29                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	5                               // DW_FORM_data2
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	30                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	5                               // DW_FORM_data2
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	31                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	1                               // DW_CHILDREN_yes
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	5                               // DW_FORM_data2
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	32                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	33                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	34                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	5                               // DW_FORM_data2
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	35                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	5                               // DW_FORM_data2
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	36                              // Abbreviation Code
	.ascii	"\211\202\001"                  // DW_TAG_GNU_call_site
	.byte	0                               // DW_CHILDREN_no
	.ascii	"\223B"                         // DW_AT_GNU_call_site_target
	.byte	24                              // DW_FORM_exprloc
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x5bc DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	0                               // DW_AT_low_pc
	.long	.Ldebug_ranges10                // DW_AT_ranges
	.byte	2                               // Abbrev [2] 0x26:0x11 DW_TAG_variable
	.long	.Linfo_string3                  // DW_AT_name
	.long	55                              // DW_AT_type
                                        // DW_AT_external
	.byte	2                               // DW_AT_decl_file
	.byte	25                              // DW_AT_decl_line
	.byte	5                               // DW_AT_location
	.byte	3
	.long	__atomic_bit___buddy_lock
	.byte	3                               // Abbrev [3] 0x37:0xb DW_TAG_typedef
	.long	66                              // DW_AT_type
	.long	.Linfo_string5                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	40                              // DW_AT_decl_line
	.byte	4                               // Abbrev [4] 0x42:0x7 DW_TAG_base_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	8                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	5                               // Abbrev [5] 0x49:0x11 DW_TAG_variable
	.long	.Linfo_string6                  // DW_AT_name
	.long	90                              // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	21                              // DW_AT_decl_line
	.byte	5                               // DW_AT_location
	.byte	3
	.long	__BUDDY_SIZE_OF_HEAP__
	.byte	4                               // Abbrev [4] 0x5a:0x7 DW_TAG_base_type
	.long	.Linfo_string7                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	5                               // Abbrev [5] 0x61:0x11 DW_TAG_variable
	.long	.Linfo_string8                  // DW_AT_name
	.long	66                              // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
	.byte	5                               // DW_AT_location
	.byte	3
	.long	__BUDDY_MAX_POWER__
	.byte	5                               // Abbrev [5] 0x72:0x11 DW_TAG_variable
	.long	.Linfo_string9                  // DW_AT_name
	.long	66                              // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	23                              // DW_AT_decl_line
	.byte	5                               // DW_AT_location
	.byte	3
	.long	__BUDDY_NUMBER_OF_LEVELS__
	.byte	5                               // Abbrev [5] 0x83:0x11 DW_TAG_variable
	.long	.Linfo_string10                 // DW_AT_name
	.long	148                             // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	19                              // DW_AT_decl_line
	.byte	5                               // DW_AT_location
	.byte	3
	.long	__buddy_blocks
	.byte	6                               // Abbrev [6] 0x94:0x5 DW_TAG_pointer_type
	.long	153                             // DW_AT_type
	.byte	4                               // Abbrev [4] 0x99:0x7 DW_TAG_base_type
	.long	.Linfo_string11                 // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	5                               // Abbrev [5] 0xa0:0x11 DW_TAG_variable
	.long	.Linfo_string12                 // DW_AT_name
	.long	177                             // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	20                              // DW_AT_decl_line
	.byte	5                               // DW_AT_location
	.byte	3
	.long	__buddy_heap_start
	.byte	7                               // Abbrev [7] 0xb1:0x1 DW_TAG_pointer_type
	.byte	5                               // Abbrev [5] 0xb2:0x18 DW_TAG_variable
	.long	.Linfo_string13                 // DW_AT_name
	.long	66                              // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	18                              // DW_AT_decl_line
	.byte	12                              // DW_AT_location
	.byte	3
	.long	__buddy_init_done
	.byte	148
	.byte	1
	.byte	49
	.byte	30
	.byte	48
	.byte	34
	.byte	159
	.byte	6                               // Abbrev [6] 0xca:0x5 DW_TAG_pointer_type
	.long	90                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0xcf:0x23 DW_TAG_subprogram
	.long	.Linfo_string14                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	31                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	90                              // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	9                               // Abbrev [9] 0xdb:0xb DW_TAG_formal_parameter
	.long	.Linfo_string15                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	31                              // DW_AT_decl_line
	.long	153                             // DW_AT_type
	.byte	10                              // Abbrev [10] 0xe6:0xb DW_TAG_variable
	.long	.Linfo_string16                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	39                              // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	11                              // Abbrev [11] 0xf2:0x145 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string33                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	65                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	177                             // DW_AT_type
                                        // DW_AT_external
	.byte	12                              // Abbrev [12] 0x107:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string39                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	65                              // DW_AT_decl_line
	.long	1467                            // DW_AT_type
	.byte	10                              // Abbrev [10] 0x116:0xb DW_TAG_variable
	.long	.Linfo_string16                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	77                              // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	13                              // Abbrev [13] 0x121:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string41                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	78                              // DW_AT_decl_line
	.long	153                             // DW_AT_type
	.byte	14                              // Abbrev [14] 0x130:0x23 DW_TAG_inlined_subroutine
	.long	207                             // DW_AT_abstract_origin
	.long	.Ltmp1                          // DW_AT_low_pc
	.long	.Ltmp4-.Ltmp1                   // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	77                              // DW_AT_call_line
	.byte	31                              // DW_AT_call_column
	.byte	15                              // Abbrev [15] 0x140:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	219                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x149:0x9 DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	230                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	17                              // Abbrev [17] 0x153:0xe3 DW_TAG_lexical_block
	.long	.Ldebug_ranges5                 // DW_AT_ranges
	.byte	13                              // Abbrev [13] 0x158:0xf DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	.Linfo_string42                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	89                              // DW_AT_decl_line
	.long	153                             // DW_AT_type
	.byte	17                              // Abbrev [17] 0x167:0xce DW_TAG_lexical_block
	.long	.Ldebug_ranges4                 // DW_AT_ranges
	.byte	13                              // Abbrev [13] 0x16c:0xf DW_TAG_variable
	.long	.Ldebug_loc5                    // DW_AT_location
	.long	.Linfo_string43                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	97                              // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	13                              // Abbrev [13] 0x17b:0xf DW_TAG_variable
	.long	.Ldebug_loc6                    // DW_AT_location
	.long	.Linfo_string26                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	91                              // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	13                              // Abbrev [13] 0x18a:0xf DW_TAG_variable
	.long	.Ldebug_loc8                    // DW_AT_location
	.long	.Linfo_string45                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	98                              // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	17                              // Abbrev [17] 0x199:0x9b DW_TAG_lexical_block
	.long	.Ldebug_ranges3                 // DW_AT_ranges
	.byte	13                              // Abbrev [13] 0x19e:0xf DW_TAG_variable
	.long	.Ldebug_loc7                    // DW_AT_location
	.long	.Linfo_string44                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	122                             // DW_AT_decl_line
	.long	153                             // DW_AT_type
	.byte	17                              // Abbrev [17] 0x1ad:0x86 DW_TAG_lexical_block
	.long	.Ldebug_ranges2                 // DW_AT_ranges
	.byte	10                              // Abbrev [10] 0x1b2:0xb DW_TAG_variable
	.long	.Linfo_string46                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	129                             // DW_AT_decl_line
	.long	202                             // DW_AT_type
	.byte	13                              // Abbrev [13] 0x1bd:0xf DW_TAG_variable
	.long	.Ldebug_loc9                    // DW_AT_location
	.long	.Linfo_string21                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	127                             // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	13                              // Abbrev [13] 0x1cc:0xf DW_TAG_variable
	.long	.Ldebug_loc10                   // DW_AT_location
	.long	.Linfo_string28                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	136                             // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	13                              // Abbrev [13] 0x1db:0xf DW_TAG_variable
	.long	.Ldebug_loc11                   // DW_AT_location
	.long	.Linfo_string47                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	142                             // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	17                              // Abbrev [17] 0x1ea:0x48 DW_TAG_lexical_block
	.long	.Ldebug_ranges1                 // DW_AT_ranges
	.byte	13                              // Abbrev [13] 0x1ef:0xf DW_TAG_variable
	.long	.Ldebug_loc12                   // DW_AT_location
	.long	.Linfo_string48                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	145                             // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	13                              // Abbrev [13] 0x1fe:0xf DW_TAG_variable
	.long	.Ldebug_loc13                   // DW_AT_location
	.long	.Linfo_string22                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	156                             // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	17                              // Abbrev [17] 0x20d:0x24 DW_TAG_lexical_block
	.long	.Ldebug_ranges0                 // DW_AT_ranges
	.byte	13                              // Abbrev [13] 0x212:0xf DW_TAG_variable
	.long	.Ldebug_loc14                   // DW_AT_location
	.long	.Linfo_string21                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	214                             // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	13                              // Abbrev [13] 0x221:0xf DW_TAG_variable
	.long	.Ldebug_loc15                   // DW_AT_location
	.long	.Linfo_string49                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	205                             // DW_AT_decl_line
	.long	153                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	18                              // Abbrev [18] 0x237:0x69 DW_TAG_subprogram
	.long	.Lfunc_begin1                   // DW_AT_low_pc
	.long	.Lfunc_end1-.Lfunc_begin1       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	672                             // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x246:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc16                   // DW_AT_location
	.long	684                             // DW_AT_abstract_origin
	.byte	19                              // Abbrev [19] 0x24f:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	695                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x256:0x9 DW_TAG_variable
	.long	.Ldebug_loc17                   // DW_AT_location
	.long	706                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x25f:0x9 DW_TAG_variable
	.long	.Ldebug_loc18                   // DW_AT_location
	.long	718                             // DW_AT_abstract_origin
	.byte	20                              // Abbrev [20] 0x268:0x37 DW_TAG_lexical_block
	.long	.Ltmp88                         // DW_AT_low_pc
	.long	.Ltmp114-.Ltmp88                // DW_AT_high_pc
	.byte	16                              // Abbrev [16] 0x271:0x9 DW_TAG_variable
	.long	.Ldebug_loc19                   // DW_AT_location
	.long	731                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x27a:0x9 DW_TAG_variable
	.long	.Ldebug_loc20                   // DW_AT_location
	.long	743                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x283:0x9 DW_TAG_variable
	.long	.Ldebug_loc21                   // DW_AT_location
	.long	755                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x28c:0x9 DW_TAG_variable
	.long	.Ldebug_loc22                   // DW_AT_location
	.long	767                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x295:0x9 DW_TAG_variable
	.long	.Ldebug_loc23                   // DW_AT_location
	.long	779                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	21                              // Abbrev [21] 0x2a0:0x87 DW_TAG_subprogram
	.long	.Linfo_string17                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	248                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	153                             // DW_AT_type
                                        // DW_AT_external
	.byte	1                               // DW_AT_inline
	.byte	9                               // Abbrev [9] 0x2ac:0xb DW_TAG_formal_parameter
	.long	.Linfo_string18                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	248                             // DW_AT_decl_line
	.long	177                             // DW_AT_type
	.byte	9                               // Abbrev [9] 0x2b7:0xb DW_TAG_formal_parameter
	.long	.Linfo_string19                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	248                             // DW_AT_decl_line
	.long	807                             // DW_AT_type
	.byte	22                              // Abbrev [22] 0x2c2:0xc DW_TAG_variable
	.long	.Linfo_string20                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	262                             // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	22                              // Abbrev [22] 0x2ce:0xc DW_TAG_variable
	.long	.Linfo_string26                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	260                             // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	23                              // Abbrev [23] 0x2da:0x4c DW_TAG_lexical_block
	.byte	22                              // Abbrev [22] 0x2db:0xc DW_TAG_variable
	.long	.Linfo_string22                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	267                             // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	22                              // Abbrev [22] 0x2e7:0xc DW_TAG_variable
	.long	.Linfo_string23                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	268                             // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	22                              // Abbrev [22] 0x2f3:0xc DW_TAG_variable
	.long	.Linfo_string27                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	280                             // DW_AT_decl_line
	.long	153                             // DW_AT_type
	.byte	22                              // Abbrev [22] 0x2ff:0xc DW_TAG_variable
	.long	.Linfo_string21                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	294                             // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	22                              // Abbrev [22] 0x30b:0xc DW_TAG_variable
	.long	.Linfo_string28                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	303                             // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	23                              // Abbrev [23] 0x317:0xe DW_TAG_lexical_block
	.byte	22                              // Abbrev [22] 0x318:0xc DW_TAG_variable
	.long	.Linfo_string29                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	285                             // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	3                               // Abbrev [3] 0x327:0xb DW_TAG_typedef
	.long	818                             // DW_AT_type
	.long	.Linfo_string25                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	245                             // DW_AT_decl_line
	.byte	6                               // Abbrev [6] 0x332:0x5 DW_TAG_pointer_type
	.long	823                             // DW_AT_type
	.byte	24                              // Abbrev [24] 0x337:0x39 DW_TAG_structure_type
	.long	.Linfo_string24                 // DW_AT_name
	.byte	16                              // DW_AT_byte_size
	.byte	2                               // DW_AT_decl_file
	.byte	240                             // DW_AT_decl_line
	.byte	25                              // Abbrev [25] 0x33f:0xc DW_TAG_member
	.long	.Linfo_string20                 // DW_AT_name
	.long	90                              // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	241                             // DW_AT_decl_line
	.byte	0                               // DW_AT_data_member_location
	.byte	25                              // Abbrev [25] 0x34b:0xc DW_TAG_member
	.long	.Linfo_string21                 // DW_AT_name
	.long	90                              // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	242                             // DW_AT_decl_line
	.byte	4                               // DW_AT_data_member_location
	.byte	25                              // Abbrev [25] 0x357:0xc DW_TAG_member
	.long	.Linfo_string22                 // DW_AT_name
	.long	90                              // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	243                             // DW_AT_decl_line
	.byte	8                               // DW_AT_data_member_location
	.byte	25                              // Abbrev [25] 0x363:0xc DW_TAG_member
	.long	.Linfo_string23                 // DW_AT_name
	.long	90                              // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	244                             // DW_AT_decl_line
	.byte	12                              // DW_AT_data_member_location
	.byte	0                               // End Of Children Mark
	.byte	26                              // Abbrev [26] 0x370:0x7a DW_TAG_subprogram
	.long	.Linfo_string30                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	328                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.byte	1                               // DW_AT_inline
	.byte	27                              // Abbrev [27] 0x379:0xc DW_TAG_formal_parameter
	.long	.Linfo_string31                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	328                             // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	27                              // Abbrev [27] 0x385:0xc DW_TAG_formal_parameter
	.long	.Linfo_string19                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	328                             // DW_AT_decl_line
	.long	807                             // DW_AT_type
	.byte	22                              // Abbrev [22] 0x391:0xc DW_TAG_variable
	.long	.Linfo_string32                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	331                             // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	22                              // Abbrev [22] 0x39d:0xc DW_TAG_variable
	.long	.Linfo_string22                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	332                             // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	22                              // Abbrev [22] 0x3a9:0xc DW_TAG_variable
	.long	.Linfo_string23                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	333                             // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	22                              // Abbrev [22] 0x3b5:0xc DW_TAG_variable
	.long	.Linfo_string28                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	334                             // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	22                              // Abbrev [22] 0x3c1:0xc DW_TAG_variable
	.long	.Linfo_string21                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	330                             // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	23                              // Abbrev [23] 0x3cd:0x1c DW_TAG_lexical_block
	.byte	22                              // Abbrev [22] 0x3ce:0xc DW_TAG_variable
	.long	.Linfo_string27                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	360                             // DW_AT_decl_line
	.long	153                             // DW_AT_type
	.byte	23                              // Abbrev [23] 0x3da:0xe DW_TAG_lexical_block
	.byte	22                              // Abbrev [22] 0x3db:0xc DW_TAG_variable
	.long	.Linfo_string29                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	365                             // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	28                              // Abbrev [28] 0x3ea:0xf8 DW_TAG_subprogram
	.long	.Lfunc_begin2                   // DW_AT_low_pc
	.long	.Lfunc_end2-.Lfunc_begin2       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string34                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	391                             // DW_AT_decl_line
                                        // DW_AT_prototyped
                                        // DW_AT_external
	.byte	29                              // Abbrev [29] 0x3fc:0x10 DW_TAG_formal_parameter
	.long	.Ldebug_loc24                   // DW_AT_location
	.long	.Linfo_string18                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	391                             // DW_AT_decl_line
	.long	177                             // DW_AT_type
	.byte	30                              // Abbrev [30] 0x40c:0x10 DW_TAG_variable
	.long	.Ldebug_loc33                   // DW_AT_location
	.long	.Linfo_string19                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	393                             // DW_AT_decl_line
	.long	823                             // DW_AT_type
	.byte	30                              // Abbrev [30] 0x41c:0x10 DW_TAG_variable
	.long	.Ldebug_loc34                   // DW_AT_location
	.long	.Linfo_string31                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	395                             // DW_AT_decl_line
	.long	153                             // DW_AT_type
	.byte	31                              // Abbrev [31] 0x42c:0x61 DW_TAG_inlined_subroutine
	.long	672                             // DW_AT_abstract_origin
	.long	.Ldebug_ranges6                 // DW_AT_ranges
	.byte	2                               // DW_AT_call_file
	.short	395                             // DW_AT_call_line
	.byte	17                              // DW_AT_call_column
	.byte	15                              // Abbrev [15] 0x439:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc25                   // DW_AT_location
	.long	684                             // DW_AT_abstract_origin
	.byte	32                              // Abbrev [32] 0x442:0x5 DW_TAG_formal_parameter
	.long	695                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x447:0x9 DW_TAG_variable
	.long	.Ldebug_loc26                   // DW_AT_location
	.long	706                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x450:0x9 DW_TAG_variable
	.long	.Ldebug_loc27                   // DW_AT_location
	.long	718                             // DW_AT_abstract_origin
	.byte	17                              // Abbrev [17] 0x459:0x33 DW_TAG_lexical_block
	.long	.Ldebug_ranges7                 // DW_AT_ranges
	.byte	16                              // Abbrev [16] 0x45e:0x9 DW_TAG_variable
	.long	.Ldebug_loc28                   // DW_AT_location
	.long	731                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x467:0x9 DW_TAG_variable
	.long	.Ldebug_loc29                   // DW_AT_location
	.long	743                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x470:0x9 DW_TAG_variable
	.long	.Ldebug_loc30                   // DW_AT_location
	.long	755                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x479:0x9 DW_TAG_variable
	.long	.Ldebug_loc31                   // DW_AT_location
	.long	767                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x482:0x9 DW_TAG_variable
	.long	.Ldebug_loc32                   // DW_AT_location
	.long	779                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	31                              // Abbrev [31] 0x48d:0x54 DW_TAG_inlined_subroutine
	.long	880                             // DW_AT_abstract_origin
	.long	.Ldebug_ranges8                 // DW_AT_ranges
	.byte	2                               // DW_AT_call_file
	.short	399                             // DW_AT_call_line
	.byte	9                               // DW_AT_call_column
	.byte	15                              // Abbrev [15] 0x49a:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc38                   // DW_AT_location
	.long	889                             // DW_AT_abstract_origin
	.byte	32                              // Abbrev [32] 0x4a3:0x5 DW_TAG_formal_parameter
	.long	901                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x4a8:0x9 DW_TAG_variable
	.long	.Ldebug_loc35                   // DW_AT_location
	.long	913                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x4b1:0x9 DW_TAG_variable
	.long	.Ldebug_loc36                   // DW_AT_location
	.long	925                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x4ba:0x9 DW_TAG_variable
	.long	.Ldebug_loc37                   // DW_AT_location
	.long	937                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x4c3:0x9 DW_TAG_variable
	.long	.Ldebug_loc39                   // DW_AT_location
	.long	949                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x4cc:0x9 DW_TAG_variable
	.long	.Ldebug_loc40                   // DW_AT_location
	.long	961                             // DW_AT_abstract_origin
	.byte	17                              // Abbrev [17] 0x4d5:0xb DW_TAG_lexical_block
	.long	.Ldebug_ranges9                 // DW_AT_ranges
	.byte	33                              // Abbrev [33] 0x4da:0x5 DW_TAG_variable
	.long	974                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	34                              // Abbrev [34] 0x4e2:0x3c DW_TAG_subprogram
	.long	.Lfunc_begin3                   // DW_AT_low_pc
	.long	.Lfunc_end3-.Lfunc_begin3       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string35                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	405                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	177                             // DW_AT_type
                                        // DW_AT_external
	.byte	35                              // Abbrev [35] 0x4f8:0xe DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	.Linfo_string39                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	405                             // DW_AT_decl_line
	.long	1467                            // DW_AT_type
	.byte	30                              // Abbrev [30] 0x506:0x10 DW_TAG_variable
	.long	.Ldebug_loc41                   // DW_AT_location
	.long	.Linfo_string50                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	408                             // DW_AT_decl_line
	.long	177                             // DW_AT_type
	.byte	36                              // Abbrev [36] 0x516:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp177                        // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	28                              // Abbrev [28] 0x51e:0x28 DW_TAG_subprogram
	.long	.Lfunc_begin4                   // DW_AT_low_pc
	.long	.Lfunc_end4-.Lfunc_begin4       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string36                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	415                             // DW_AT_decl_line
                                        // DW_AT_prototyped
                                        // DW_AT_external
	.byte	35                              // Abbrev [35] 0x530:0xe DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	.Linfo_string18                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	415                             // DW_AT_decl_line
	.long	177                             // DW_AT_type
	.byte	36                              // Abbrev [36] 0x53e:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp183                        // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	28                              // Abbrev [28] 0x546:0x5b DW_TAG_subprogram
	.long	.Lfunc_begin5                   // DW_AT_low_pc
	.long	.Lfunc_end5-.Lfunc_begin5       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string37                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	438                             // DW_AT_decl_line
                                        // DW_AT_prototyped
                                        // DW_AT_external
	.byte	29                              // Abbrev [29] 0x558:0x10 DW_TAG_formal_parameter
	.long	.Ldebug_loc42                   // DW_AT_location
	.long	.Linfo_string51                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	438                             // DW_AT_decl_line
	.long	1467                            // DW_AT_type
	.byte	20                              // Abbrev [20] 0x568:0x2a DW_TAG_lexical_block
	.long	.Ltmp188                        // DW_AT_low_pc
	.long	.Ltmp196-.Ltmp188               // DW_AT_high_pc
	.byte	30                              // Abbrev [30] 0x571:0x10 DW_TAG_variable
	.long	.Ldebug_loc43                   // DW_AT_location
	.long	.Linfo_string16                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	445                             // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	30                              // Abbrev [30] 0x581:0x10 DW_TAG_variable
	.long	.Ldebug_loc44                   // DW_AT_location
	.long	.Linfo_string52                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	450                             // DW_AT_decl_line
	.long	90                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	36                              // Abbrev [36] 0x592:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp194                        // DW_AT_low_pc
	.byte	36                              // Abbrev [36] 0x599:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp195                        // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	28                              // Abbrev [28] 0x5a1:0x1a DW_TAG_subprogram
	.long	.Lfunc_begin6                   // DW_AT_low_pc
	.long	.Lfunc_end6-.Lfunc_begin6       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string38                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	463                             // DW_AT_decl_line
                                        // DW_AT_prototyped
                                        // DW_AT_external
	.byte	36                              // Abbrev [36] 0x5b3:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp200                        // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	3                               // Abbrev [3] 0x5bb:0xb DW_TAG_typedef
	.long	90                              // DW_AT_type
	.long	.Linfo_string40                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	26                              // DW_AT_decl_line
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_ranges,"",@progbits
.Ldebug_ranges0:
	.long	.Ltmp56
	.long	.Ltmp62
	.long	.Ltmp63
	.long	.Ltmp65
	.long	.Ltmp66
	.long	.Ltmp73
	.long	0
	.long	0
.Ldebug_ranges1:
	.long	.Ltmp39
	.long	.Ltmp40
	.long	.Ltmp42
	.long	.Ltmp44
	.long	.Ltmp47
	.long	.Ltmp73
	.long	.Ltmp76
	.long	.Ltmp77
	.long	0
	.long	0
.Ldebug_ranges2:
	.long	.Ltmp33
	.long	.Ltmp36
	.long	.Ltmp39
	.long	.Ltmp40
	.long	.Ltmp42
	.long	.Ltmp44
	.long	.Ltmp47
	.long	.Ltmp73
	.long	.Ltmp76
	.long	.Ltmp77
	.long	0
	.long	0
.Ldebug_ranges3:
	.long	.Ltmp28
	.long	.Ltmp40
	.long	.Ltmp42
	.long	.Ltmp44
	.long	.Ltmp47
	.long	.Ltmp73
	.long	.Ltmp76
	.long	.Ltmp77
	.long	0
	.long	0
.Ldebug_ranges4:
	.long	.Ltmp25
	.long	.Ltmp73
	.long	.Ltmp76
	.long	.Ltmp77
	.long	0
	.long	0
.Ldebug_ranges5:
	.long	.Ltmp8
	.long	.Ltmp9
	.long	.Ltmp17
	.long	.Ltmp77
	.long	0
	.long	0
.Ldebug_ranges6:
	.long	.Lfunc_begin2
	.long	.Ltmp120
	.long	.Ltmp121
	.long	.Ltmp148
	.long	.Ltmp149
	.long	.Ltmp150
	.long	0
	.long	0
.Ldebug_ranges7:
	.long	.Ltmp125
	.long	.Ltmp148
	.long	.Ltmp149
	.long	.Ltmp150
	.long	0
	.long	0
.Ldebug_ranges8:
	.long	.Ltmp151
	.long	.Ltmp152
	.long	.Ltmp153
	.long	.Ltmp174
	.long	0
	.long	0
.Ldebug_ranges9:
	.long	.Ltmp153
	.long	.Ltmp154
	.long	.Ltmp156
	.long	.Ltmp158
	.long	.Ltmp160
	.long	.Ltmp174
	.long	0
	.long	0
.Ldebug_ranges10:
	.long	.Lfunc_begin0
	.long	.Lfunc_end0
	.long	.Lfunc_begin1
	.long	.Lfunc_end1
	.long	.Lfunc_begin2
	.long	.Lfunc_end2
	.long	.Lfunc_begin3
	.long	.Lfunc_end3
	.long	.Lfunc_begin4
	.long	.Lfunc_end4
	.long	.Lfunc_begin5
	.long	.Lfunc_end5
	.long	.Lfunc_begin6
	.long	.Lfunc_end6
	.long	0
	.long	0
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/buddy_alloc.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=157
.Linfo_string3:
	.asciz	"__atomic_bit___buddy_lock"     // string offset=178
.Linfo_string4:
	.asciz	"unsigned char"                 // string offset=204
.Linfo_string5:
	.asciz	"uint8_t"                       // string offset=218
.Linfo_string6:
	.asciz	"__BUDDY_SIZE_OF_HEAP__"        // string offset=226
.Linfo_string7:
	.asciz	"unsigned int"                  // string offset=249
.Linfo_string8:
	.asciz	"__BUDDY_MAX_POWER__"           // string offset=262
.Linfo_string9:
	.asciz	"__BUDDY_NUMBER_OF_LEVELS__"    // string offset=282
.Linfo_string10:
	.asciz	"__buddy_blocks"                // string offset=309
.Linfo_string11:
	.asciz	"int"                           // string offset=324
.Linfo_string12:
	.asciz	"__buddy_heap_start"            // string offset=328
.Linfo_string13:
	.asciz	"__buddy_init_done"             // string offset=347
.Linfo_string14:
	.asciz	"next_power_of_2"               // string offset=365
.Linfo_string15:
	.asciz	"x"                             // string offset=381
.Linfo_string16:
	.asciz	"power_of_2"                    // string offset=383
.Linfo_string17:
	.asciz	"buddy_search_for_pointer"      // string offset=394
.Linfo_string18:
	.asciz	"pointer"                       // string offset=419
.Linfo_string19:
	.asciz	"context"                       // string offset=427
.Linfo_string20:
	.asciz	"target_level"                  // string offset=435
.Linfo_string21:
	.asciz	"real_index"                    // string offset=448
.Linfo_string22:
	.asciz	"highlight_target_bit"          // string offset=459
.Linfo_string23:
	.asciz	"highlight_buddy_bit"           // string offset=480
.Linfo_string24:
	.asciz	"_buddy_search_context_t"       // string offset=500
.Linfo_string25:
	.asciz	"buddy_search_context_t"        // string offset=524
.Linfo_string26:
	.asciz	"index_in_level"                // string offset=547
.Linfo_string27:
	.asciz	"target_level_clamped"          // string offset=562
.Linfo_string28:
	.asciz	"loaded_case"                   // string offset=583
.Linfo_string29:
	.asciz	"offset"                        // string offset=595
.Linfo_string30:
	.asciz	"buddy_free_fusion_of_blocks"   // string offset=602
.Linfo_string31:
	.asciz	"index"                         // string offset=630
.Linfo_string32:
	.asciz	"current_level_freeing"         // string offset=636
.Linfo_string33:
	.asciz	"safe_buddy_alloc"              // string offset=658
.Linfo_string34:
	.asciz	"safe_buddy_free"               // string offset=675
.Linfo_string35:
	.asciz	"buddy_alloc"                   // string offset=691
.Linfo_string36:
	.asciz	"buddy_free"                    // string offset=703
.Linfo_string37:
	.asciz	"buddy_init"                    // string offset=714
.Linfo_string38:
	.asciz	"buddy_reset"                   // string offset=725
.Linfo_string39:
	.asciz	"size"                          // string offset=737
.Linfo_string40:
	.asciz	"size_t"                        // string offset=742
.Linfo_string41:
	.asciz	"blocks_level"                  // string offset=749
.Linfo_string42:
	.asciz	"blocks_level_current"          // string offset=762
.Linfo_string43:
	.asciz	"initial_number_of_current_bitfield" // string offset=783
.Linfo_string44:
	.asciz	"number_of_current_bitfield"    // string offset=818
.Linfo_string45:
	.asciz	"loaded_case_mask"              // string offset=845
.Linfo_string46:
	.asciz	"initial_loaded_case_address"   // string offset=862
.Linfo_string47:
	.asciz	"lz_before_first_pair_tmp"      // string offset=890
.Linfo_string48:
	.asciz	"lz_before_first_pair"          // string offset=915
.Linfo_string49:
	.asciz	"blocks_level_clamped"          // string offset=936
.Linfo_string50:
	.asciz	"result"                        // string offset=957
.Linfo_string51:
	.asciz	"size_of_heap"                  // string offset=964
.Linfo_string52:
	.asciz	"blocks_in_buddy_blocks"        // string offset=977
	.addrsig
	.addrsig_sym __atomic_bit___buddy_lock
	.section	.debug_line,"",@progbits
.Lline_table_start0:
