	.text
	.file	"buddy_realloc.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/stddef.h"
	.section	.text.buddy_realloc,"ax",@progbits
	.globl	buddy_realloc                   // -- Begin function buddy_realloc
	.type	buddy_realloc,@function
buddy_realloc:                          // @buddy_realloc
.Lfunc_begin0:
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/buddy_realloc.c"
	.loc	2 51 0                          // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:51:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: buddy_realloc:ptr <- $r0
	//DEBUG_VALUE: buddy_realloc:size <- $r1
	.cfi_def_cfa_offset -40
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 32, d22
	add r22, r22, 40
	.cfi_offset 15, -32
	.cfi_offset 14, -28
.Ltmp0:
	sd r22, -32, d14
	.cfi_offset 17, -40
	.cfi_offset 16, -36
	sd r22, -40, d16
	.loc	2 52 5 prologue_end             // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:52:5
	// inline asm
.Ltmp1:
	acquire zero, __atomic_bit___buddy_lock, nz, .Ltmp1
	// inline asm
.Ltmp2:
	//DEBUG_VALUE: buddy_realloc:result <- undef
	.loc	2 0 5 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:0:5
	move r15, r1
.Ltmp3:
	//DEBUG_VALUE: buddy_realloc:size <- $r15
	//DEBUG_VALUE: buddy_realloc:ptr <- $r14
	move r14, r0, z, .LBB0_1
.Ltmp4:
// %bb.2:
	//DEBUG_VALUE: buddy_realloc:size <- $r15
	.loc	2 60 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:60:9
	jeq r15, 0, .LBB0_3
.Ltmp5:
// %bb.4:
	//DEBUG_VALUE: buddy_realloc:size <- $r15
	.loc	2 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:0:9
	add r1, r22, -24
.Ltmp6:
	//DEBUG_VALUE: buddy_sizeofblock:pointer <- $r14
	.loc	2 39 17 is_stmt 1               // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:39:17
	move r0, r14
	call r23, buddy_search_for_pointer
.Ltmp7:
	//DEBUG_VALUE: buddy_sizeofblock:index <- $r0
	.loc	2 41 9                          // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:41:9
	sub r1, 12, r0
	lsl r1, one, r1
	jeq r0, -1, .LBB0_5
.Ltmp8:
// %bb.6:
	//DEBUG_VALUE: buddy_realloc:size <- $r15
	//DEBUG_VALUE: buddy_sizeofblock:pointer <- $r14
	//DEBUG_VALUE: buddy_sizeofblock:index <- $r0
	move r2, r1
.Ltmp9:
	//DEBUG_VALUE: buddy_realloc:size_block <- $r2
	.loc	2 68 9                          // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:68:9
	jeq r0, -1, .LBB0_8
.Ltmp10:
.LBB0_9:
	//DEBUG_VALUE: buddy_realloc:size <- $r15
	//DEBUG_VALUE: buddy_realloc:size_block <- $r2
	.loc	2 73 29                         // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:73:29
	lsr r0, r2, 1
.Ltmp11:
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:0:0
	move r16, r15
	.loc	2 73 9                          // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:73:9
	jgeu r0, r15, .LBB0_12
.Ltmp12:
// %bb.10:
	//DEBUG_VALUE: buddy_realloc:size <- $r15
	//DEBUG_VALUE: buddy_realloc:size_block <- $r2
	.loc	2 0 0                           // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:0:0
	move r16, r1
.Ltmp13:
	.loc	2 75 16 is_stmt 1               // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:75:16
	jgeu r2, r15, .LBB0_11
.Ltmp14:
.LBB0_12:
	//DEBUG_VALUE: buddy_realloc:size <- $r15
	//DEBUG_VALUE: buddy_realloc:size_block <- $r2
	//DEBUG_VALUE: buddy_realloc:size_block <- $r16
	.loc	2 80 5                          // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:80:5
	move r0, r14
	call r23, safe_buddy_free
.Ltmp15:
	.loc	2 81 14                         // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:81:14
	move r0, r15
	call r23, safe_buddy_alloc
.Ltmp16:
	move r15, r0
.Ltmp17:
	//DEBUG_VALUE: buddy_realloc:result <- $r15
	.loc	2 82 5                          // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:82:5
	move r1, r14
	move r2, r16
	call r23, memcpy
.Ltmp18:
	.loc	2 84 5                          // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:84:5
	// inline asm
.Ltmp19:
	release zero, __atomic_bit___buddy_lock, nz, .Ltmp19+1
	// inline asm
.Ltmp20:
	//DEBUG_VALUE: buddy_realloc:result <- $r14
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:0:0
	move r14, r15, true, .LBB0_13
.Ltmp21:
.LBB0_1:
	//DEBUG_VALUE: buddy_realloc:size <- $r15
	.loc	2 55 18 is_stmt 1               // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:55:18
	move r0, r15
	call r23, safe_buddy_alloc
.Ltmp22:
	.loc	2 56 9                          // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:56:9
	// inline asm
.Ltmp23:
	release zero, __atomic_bit___buddy_lock, nz, .Ltmp23+1
	// inline asm
.Ltmp24:
	//DEBUG_VALUE: buddy_realloc:result <- $r14
	.loc	2 55 18                         // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:55:18
	move r14, r0, true, .LBB0_13
.Ltmp25:
.LBB0_3:
	//DEBUG_VALUE: buddy_realloc:size <- $r15
	.loc	2 61 9                          // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:61:9
	move r0, r14
	call r23, safe_buddy_free
.Ltmp26:
	.loc	2 62 9                          // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:62:9
	// inline asm
.Ltmp27:
	release zero, __atomic_bit___buddy_lock, nz, .Ltmp27+1
	// inline asm
	jump .LBB0_13
.Ltmp28:
.LBB0_5:
	//DEBUG_VALUE: buddy_realloc:size <- $r15
	.loc	2 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:0:9
	move r2, -1
.Ltmp29:
	//DEBUG_VALUE: buddy_realloc:size_block <- $r2
	.loc	2 68 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:68:9
	jneq r0, -1, .LBB0_9
.Ltmp30:
.LBB0_8:
	//DEBUG_VALUE: buddy_realloc:size <- $r15
	//DEBUG_VALUE: buddy_realloc:size_block <- $r2
	.loc	2 69 9                          // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:69:9
	// inline asm
.Ltmp31:
	release zero, __atomic_bit___buddy_lock, nz, .Ltmp31+1
	// inline asm
	move r14, 0, true, .LBB0_13
.Ltmp32:
.LBB0_11:
	//DEBUG_VALUE: buddy_realloc:size <- $r15
	//DEBUG_VALUE: buddy_realloc:size_block <- $r2
	.loc	2 76 9                          // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:76:9
	// inline asm
.Ltmp33:
	release zero, __atomic_bit___buddy_lock, nz, .Ltmp33+1
	// inline asm
.Ltmp34:
.LBB0_13:
	.loc	2 86 1                          // uPIMulator_frontend/sdk/syslib/buddy_realloc.c:86:1
	move r0, r14
	ld d16, r22, -40
	ld d14, r22, -32
	ld d22, r22, -8
	jump r23
.Ltmp35:
.Lfunc_end0:
	.size	buddy_realloc, .Lfunc_end0-buddy_realloc
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.buddy_realloc
	.long	.Lfunc_begin0
	.byte	40
	.section	.text.buddy_realloc,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp3-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp4-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp3-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp17-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	.Ltmp21-.Lfunc_begin0
	.long	.Ltmp34-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Ltmp17-.Lfunc_begin0
	.long	.Ltmp20-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	.Ltmp20-.Lfunc_begin0
	.long	.Ltmp21-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	.Ltmp24-.Lfunc_begin0
	.long	.Ltmp25-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Ltmp7-.Lfunc_begin0
	.long	.Ltmp10-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc4:
	.long	.Ltmp9-.Lfunc_begin0
	.long	.Ltmp14-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Ltmp21-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	96                              // DW_OP_reg16
	.long	.Ltmp29-.Lfunc_begin0
	.long	.Ltmp34-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	19                              // DW_TAG_structure_type
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	13                              // DW_TAG_member
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	56                              // DW_AT_data_member_location
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	11                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	12                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	13                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	1                               // DW_CHILDREN_yes
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	14                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	15                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	16                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	17                              // Abbreviation Code
	.ascii	"\211\202\001"                  // DW_TAG_GNU_call_site
	.byte	0                               // DW_CHILDREN_no
	.ascii	"\223B"                         // DW_AT_GNU_call_site_target
	.byte	24                              // DW_FORM_exprloc
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x142 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x1 DW_TAG_pointer_type
	.byte	3                               // Abbrev [3] 0x27:0xb DW_TAG_typedef
	.long	50                              // DW_AT_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	26                              // DW_AT_decl_line
	.byte	4                               // Abbrev [4] 0x32:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	5                               // Abbrev [5] 0x39:0x2e DW_TAG_subprogram
	.long	.Linfo_string5                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	33                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	103                             // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	6                               // Abbrev [6] 0x45:0xb DW_TAG_formal_parameter
	.long	.Linfo_string7                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	33                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	7                               // Abbrev [7] 0x50:0xb DW_TAG_variable
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	38                              // DW_AT_decl_line
	.long	110                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0x5b:0xb DW_TAG_variable
	.long	.Linfo_string14                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	39                              // DW_AT_decl_line
	.long	103                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	4                               // Abbrev [4] 0x67:0x7 DW_TAG_base_type
	.long	.Linfo_string6                  // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	8                               // Abbrev [8] 0x6e:0x39 DW_TAG_structure_type
	.long	.Linfo_string13                 // DW_AT_name
	.byte	16                              // DW_AT_byte_size
	.byte	2                               // DW_AT_decl_file
	.byte	18                              // DW_AT_decl_line
	.byte	9                               // Abbrev [9] 0x76:0xc DW_TAG_member
	.long	.Linfo_string9                  // DW_AT_name
	.long	50                              // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	19                              // DW_AT_decl_line
	.byte	0                               // DW_AT_data_member_location
	.byte	9                               // Abbrev [9] 0x82:0xc DW_TAG_member
	.long	.Linfo_string10                 // DW_AT_name
	.long	50                              // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	20                              // DW_AT_decl_line
	.byte	4                               // DW_AT_data_member_location
	.byte	9                               // Abbrev [9] 0x8e:0xc DW_TAG_member
	.long	.Linfo_string11                 // DW_AT_name
	.long	50                              // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	21                              // DW_AT_decl_line
	.byte	8                               // DW_AT_data_member_location
	.byte	9                               // Abbrev [9] 0x9a:0xc DW_TAG_member
	.long	.Linfo_string12                 // DW_AT_name
	.long	50                              // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
	.byte	12                              // DW_AT_data_member_location
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0xa7:0xa5 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string15                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	50                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	38                              // DW_AT_type
                                        // DW_AT_external
	.byte	11                              // Abbrev [11] 0xbc:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string16                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	50                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	11                              // Abbrev [11] 0xcb:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string17                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	50                              // DW_AT_decl_line
	.long	39                              // DW_AT_type
	.byte	12                              // Abbrev [12] 0xda:0xf DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string18                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	53                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	12                              // Abbrev [12] 0xe9:0xf DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	.Linfo_string19                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	66                              // DW_AT_decl_line
	.long	39                              // DW_AT_type
	.byte	13                              // Abbrev [13] 0xf8:0x29 DW_TAG_inlined_subroutine
	.long	57                              // DW_AT_abstract_origin
	.long	.Ltmp6                          // DW_AT_low_pc
	.long	.Ltmp9-.Ltmp6                   // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	66                              // DW_AT_call_line
	.byte	25                              // DW_AT_call_column
	.byte	14                              // Abbrev [14] 0x108:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	94
	.long	69                              // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x10f:0x8 DW_TAG_variable
	.byte	2                               // DW_AT_location
	.byte	145
	.byte	104
	.long	80                              // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x117:0x9 DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	91                              // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	17                              // Abbrev [17] 0x121:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp7                          // DW_AT_low_pc
	.byte	17                              // Abbrev [17] 0x128:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp15                         // DW_AT_low_pc
	.byte	17                              // Abbrev [17] 0x12f:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp16                         // DW_AT_low_pc
	.byte	17                              // Abbrev [17] 0x136:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp18                         // DW_AT_low_pc
	.byte	17                              // Abbrev [17] 0x13d:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp22                         // DW_AT_low_pc
	.byte	17                              // Abbrev [17] 0x144:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp26                         // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/buddy_realloc.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=159
.Linfo_string3:
	.asciz	"unsigned int"                  // string offset=180
.Linfo_string4:
	.asciz	"size_t"                        // string offset=193
.Linfo_string5:
	.asciz	"buddy_sizeofblock"             // string offset=200
.Linfo_string6:
	.asciz	"int"                           // string offset=218
.Linfo_string7:
	.asciz	"pointer"                       // string offset=222
.Linfo_string8:
	.asciz	"dummy"                         // string offset=230
.Linfo_string9:
	.asciz	"target_level"                  // string offset=236
.Linfo_string10:
	.asciz	"real_index"                    // string offset=249
.Linfo_string11:
	.asciz	"highlight_target_bit"          // string offset=260
.Linfo_string12:
	.asciz	"highlight_buddy_bit"           // string offset=281
.Linfo_string13:
	.asciz	"_buddy_search_context_t"       // string offset=301
.Linfo_string14:
	.asciz	"index"                         // string offset=325
.Linfo_string15:
	.asciz	"buddy_realloc"                 // string offset=331
.Linfo_string16:
	.asciz	"ptr"                           // string offset=345
.Linfo_string17:
	.asciz	"size"                          // string offset=349
.Linfo_string18:
	.asciz	"result"                        // string offset=354
.Linfo_string19:
	.asciz	"size_block"                    // string offset=361
	.addrsig
	.addrsig_sym __atomic_bit___buddy_lock
	.section	.debug_line,"",@progbits
.Lline_table_start0:
