	.text
	.file	"comparesf2.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/syslib/comparesf2.c"
	.section	.text.__lesf2,"ax",@progbits
	.globl	__lesf2                         // -- Begin function __lesf2
	.type	__lesf2,@function
__lesf2:                                // @__lesf2
.Lfunc_begin0:
	.loc	1 47 0                          // uPIMulator_frontend/sdk/syslib/comparesf2.c:47:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: toRep:x <- $r0
	//DEBUG_VALUE: toRep:x <- $r0
	//DEBUG_VALUE: toRep:x <- undef
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: toRep:rep <- $r0
	//DEBUG_VALUE: toRep:rep <- $r0
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	.loc	1 51 29 prologue_end            // uPIMulator_frontend/sdk/syslib/comparesf2.c:51:29
	and r3, r0, 2147483647
.Ltmp0:
	//DEBUG_VALUE: __lesf2:bAbs <- undef
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	.loc	1 0 29 is_stmt 0                // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:29
	move r5, 2139095040
	move r2, 1
.Ltmp1:
	.loc	1 55 23 is_stmt 1               // uPIMulator_frontend/sdk/syslib/comparesf2.c:55:23
	jgtu r3, r5, .LBB0_9
.Ltmp2:
// %bb.1:
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	.loc	1 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:0
	and r4, r1, 2147483647
.Ltmp3:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	.loc	1 55 23                         // uPIMulator_frontend/sdk/syslib/comparesf2.c:55:23
	jgtu r4, r5, .LBB0_9
.Ltmp4:
// %bb.2:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	.loc	1 59 15 is_stmt 1               // uPIMulator_frontend/sdk/syslib/comparesf2.c:59:15
	or r2, r4, r3, z, .LBB0_3
.Ltmp5:
// %bb.4:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	.loc	1 64 15                         // uPIMulator_frontend/sdk/syslib/comparesf2.c:64:15
	and r2, r1, r0, mi, .LBB0_7
.Ltmp6:
// %bb.5:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	.loc	1 0 15 is_stmt 0                // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:15
	move r2, -1
.Ltmp7:
	.loc	1 65 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/comparesf2.c:65:13
	jlts r0, r1, .LBB0_9
.Ltmp8:
// %bb.6:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	.loc	1 67 23                         // uPIMulator_frontend/sdk/syslib/comparesf2.c:67:23
	sub r0, r0, r1, neq
.Ltmp9:
	.loc	1 67 18 is_stmt 0               // uPIMulator_frontend/sdk/syslib/comparesf2.c:67:18
	jump r23
.Ltmp10:
.LBB0_3:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	.loc	1 0 18                          // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:18
	move r2, 0
	.loc	1 85 1 is_stmt 1                // uPIMulator_frontend/sdk/syslib/comparesf2.c:85:1
	move r0, r2
.Ltmp11:
	jump r23
.Ltmp12:
.LBB0_7:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	.loc	1 0 1 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:1
	move r2, -1
.Ltmp13:
	.loc	1 78 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/comparesf2.c:78:13
	jgts r0, r1, .LBB0_9
.Ltmp14:
// %bb.8:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	.loc	1 80 23                         // uPIMulator_frontend/sdk/syslib/comparesf2.c:80:23
	sub r2, r0, r1, neq
.Ltmp15:
.LBB0_9:
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	.loc	1 85 1                          // uPIMulator_frontend/sdk/syslib/comparesf2.c:85:1
	move r0, r2
.Ltmp16:
	jump r23
.Ltmp17:
.Lfunc_end0:
	.size	__lesf2, .Lfunc_end0-__lesf2
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__lesf2
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.__lesf2,"ax",@progbits
                                        // -- End function
	.section	.text.__gesf2,"ax",@progbits
	.globl	__gesf2                         // -- Begin function __gesf2
	.type	__gesf2,@function
__gesf2:                                // @__gesf2
.Lfunc_begin1:
	.loc	1 101 0                         // uPIMulator_frontend/sdk/syslib/comparesf2.c:101:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __gesf2:a <- $r0
	//DEBUG_VALUE: __gesf2:b <- $r1
	//DEBUG_VALUE: toRep:x <- $r0
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: toRep:rep <- $r0
	move r2, r0
.Ltmp18:
	//DEBUG_VALUE: __gesf2:bInt <- $r1
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: __gesf2:aInt <- $r2
	//DEBUG_VALUE: toRep:rep <- $r2
	//DEBUG_VALUE: toRep:x <- $r2
	//DEBUG_VALUE: __gesf2:b <- $r1
	//DEBUG_VALUE: __gesf2:a <- $r2
	.loc	1 105 29 prologue_end           // uPIMulator_frontend/sdk/syslib/comparesf2.c:105:29
	and r3, r2, 2147483647
.Ltmp19:
	//DEBUG_VALUE: __gesf2:bAbs <- undef
	//DEBUG_VALUE: __gesf2:aAbs <- $r3
	.loc	1 0 29 is_stmt 0                // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:29
	move r4, 2139095040
	move r0, -1
.Ltmp20:
	.loc	1 108 23 is_stmt 1              // uPIMulator_frontend/sdk/syslib/comparesf2.c:108:23
	jgtu r3, r4, .LBB1_9
.Ltmp21:
// %bb.1:
	//DEBUG_VALUE: __gesf2:aAbs <- $r3
	//DEBUG_VALUE: __gesf2:a <- $r2
	//DEBUG_VALUE: __gesf2:aInt <- $r2
	//DEBUG_VALUE: __gesf2:bInt <- $r1
	//DEBUG_VALUE: __gesf2:b <- $r1
	.loc	1 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:0
	and r5, r1, 2147483647
.Ltmp22:
	//DEBUG_VALUE: __gesf2:bAbs <- $r5
	.loc	1 108 23                        // uPIMulator_frontend/sdk/syslib/comparesf2.c:108:23
	jgtu r5, r4, .LBB1_9
.Ltmp23:
// %bb.2:
	//DEBUG_VALUE: __gesf2:bAbs <- $r5
	//DEBUG_VALUE: __gesf2:aAbs <- $r3
	//DEBUG_VALUE: __gesf2:a <- $r2
	//DEBUG_VALUE: __gesf2:aInt <- $r2
	//DEBUG_VALUE: __gesf2:bInt <- $r1
	//DEBUG_VALUE: __gesf2:b <- $r1
	.loc	1 110 15 is_stmt 1              // uPIMulator_frontend/sdk/syslib/comparesf2.c:110:15
	or r3, r5, r3, z, .LBB1_3
.Ltmp24:
// %bb.4:
	//DEBUG_VALUE: __gesf2:bAbs <- $r5
	//DEBUG_VALUE: __gesf2:a <- $r2
	//DEBUG_VALUE: __gesf2:aInt <- $r2
	//DEBUG_VALUE: __gesf2:bInt <- $r1
	//DEBUG_VALUE: __gesf2:b <- $r1
	.loc	1 112 15                        // uPIMulator_frontend/sdk/syslib/comparesf2.c:112:15
	and r3, r1, r2, mi, .LBB1_7
.Ltmp25:
// %bb.5:
	//DEBUG_VALUE: __gesf2:bAbs <- $r5
	//DEBUG_VALUE: __gesf2:a <- $r2
	//DEBUG_VALUE: __gesf2:aInt <- $r2
	//DEBUG_VALUE: __gesf2:bInt <- $r1
	//DEBUG_VALUE: __gesf2:b <- $r1
	.loc	1 113 13                        // uPIMulator_frontend/sdk/syslib/comparesf2.c:113:13
	jlts r2, r1, .LBB1_9
.Ltmp26:
// %bb.6:
	//DEBUG_VALUE: __gesf2:bAbs <- $r5
	//DEBUG_VALUE: __gesf2:a <- $r2
	//DEBUG_VALUE: __gesf2:aInt <- $r2
	//DEBUG_VALUE: __gesf2:bInt <- $r1
	//DEBUG_VALUE: __gesf2:b <- $r1
	.loc	1 115 23                        // uPIMulator_frontend/sdk/syslib/comparesf2.c:115:23
	sub r0, r2, r1, neq
.Ltmp27:
	.loc	1 115 18 is_stmt 0              // uPIMulator_frontend/sdk/syslib/comparesf2.c:115:18
	jump r23
.Ltmp28:
.LBB1_3:
	//DEBUG_VALUE: __gesf2:bAbs <- $r5
	//DEBUG_VALUE: __gesf2:a <- $r2
	//DEBUG_VALUE: __gesf2:aInt <- $r2
	//DEBUG_VALUE: __gesf2:bInt <- $r1
	//DEBUG_VALUE: __gesf2:b <- $r1
	.loc	1 0 18                          // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:18
	move r0, 0
	.loc	1 127 1 is_stmt 1               // uPIMulator_frontend/sdk/syslib/comparesf2.c:127:1
	jump r23
.Ltmp29:
.LBB1_7:
	//DEBUG_VALUE: __gesf2:bAbs <- $r5
	//DEBUG_VALUE: __gesf2:a <- $r2
	//DEBUG_VALUE: __gesf2:aInt <- $r2
	//DEBUG_VALUE: __gesf2:bInt <- $r1
	//DEBUG_VALUE: __gesf2:b <- $r1
	.loc	1 120 13                        // uPIMulator_frontend/sdk/syslib/comparesf2.c:120:13
	jgts r2, r1, .LBB1_9
.Ltmp30:
// %bb.8:
	//DEBUG_VALUE: __gesf2:bAbs <- $r5
	//DEBUG_VALUE: __gesf2:a <- $r2
	//DEBUG_VALUE: __gesf2:aInt <- $r2
	//DEBUG_VALUE: __gesf2:bInt <- $r1
	//DEBUG_VALUE: __gesf2:b <- $r1
	.loc	1 122 23                        // uPIMulator_frontend/sdk/syslib/comparesf2.c:122:23
	sub r0, r2, r1, neq
.Ltmp31:
.LBB1_9:
	//DEBUG_VALUE: __gesf2:a <- $r2
	//DEBUG_VALUE: __gesf2:aInt <- $r2
	//DEBUG_VALUE: __gesf2:bInt <- $r1
	//DEBUG_VALUE: __gesf2:b <- $r1
	.loc	1 127 1                         // uPIMulator_frontend/sdk/syslib/comparesf2.c:127:1
	jump r23
.Ltmp32:
.Lfunc_end1:
	.size	__gesf2, .Lfunc_end1-__gesf2
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__gesf2
	.long	.Lfunc_begin1
	.byte	0
	.section	.text.__gesf2,"ax",@progbits
                                        // -- End function
	.section	.text.__unordsf2,"ax",@progbits
	.globl	__unordsf2                      // -- Begin function __unordsf2
	.type	__unordsf2,@function
__unordsf2:                             // @__unordsf2
.Lfunc_begin2:
	.loc	1 131 0                         // uPIMulator_frontend/sdk/syslib/comparesf2.c:131:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __unordsf2:a <- $r0
	//DEBUG_VALUE: __unordsf2:a <- $r0
	//DEBUG_VALUE: __unordsf2:b <- $r1
	//DEBUG_VALUE: __unordsf2:b <- $r1
	//DEBUG_VALUE: toRep:x <- $r0
	//DEBUG_VALUE: toRep:x <- $r0
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: toRep:rep <- $r0
	//DEBUG_VALUE: toRep:rep <- $r0
	.loc	1 132 33 prologue_end           // uPIMulator_frontend/sdk/syslib/comparesf2.c:132:33
	and r0, r0, 2147483647
.Ltmp33:
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: __unordsf2:aAbs <- $r0
	.loc	1 133 33                        // uPIMulator_frontend/sdk/syslib/comparesf2.c:133:33
	and r1, r1, 2147483647
.Ltmp34:
	//DEBUG_VALUE: __unordsf2:bAbs <- $r1
	.loc	1 0 33 is_stmt 0                // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:33
	move r2, 2139095040
	.loc	1 134 17 is_stmt 1              // uPIMulator_frontend/sdk/syslib/comparesf2.c:134:17
	sub r0, r0, r2, gtu
.Ltmp35:
	.loc	1 134 26 is_stmt 0              // uPIMulator_frontend/sdk/syslib/comparesf2.c:134:26
	sub r1, r1, r2, gtu
.Ltmp36:
	or r0, r0, r1
	.loc	1 134 5                         // uPIMulator_frontend/sdk/syslib/comparesf2.c:134:5
	jump r23
.Ltmp37:
.Lfunc_end2:
	.size	__unordsf2, .Lfunc_end2-__unordsf2
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__unordsf2
	.long	.Lfunc_begin2
	.byte	0
	.section	.text.__unordsf2,"ax",@progbits
                                        // -- End function
	.section	.text.__eqsf2,"ax",@progbits
	.globl	__eqsf2                         // -- Begin function __eqsf2
	.type	__eqsf2,@function
__eqsf2:                                // @__eqsf2
.Lfunc_begin3:
	.loc	1 141 0 is_stmt 1               // uPIMulator_frontend/sdk/syslib/comparesf2.c:141:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __eqsf2:a <- $r0
	//DEBUG_VALUE: __eqsf2:a <- $r0
	//DEBUG_VALUE: __eqsf2:b <- $r1
	//DEBUG_VALUE: __eqsf2:b <- $r1
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: toRep:x <- $r0
	//DEBUG_VALUE: toRep:x <- $r0
	//DEBUG_VALUE: toRep:x <- undef
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: toRep:rep <- $r0
	//DEBUG_VALUE: toRep:rep <- $r0
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	.loc	1 51 29 prologue_end            // uPIMulator_frontend/sdk/syslib/comparesf2.c:51:29
	and r3, r0, 2147483647
.Ltmp38:
	//DEBUG_VALUE: __lesf2:bAbs <- undef
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	.loc	1 0 29 is_stmt 0                // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:29
	move r5, 2139095040
	move r2, 1
.Ltmp39:
	.loc	1 55 23 is_stmt 1               // uPIMulator_frontend/sdk/syslib/comparesf2.c:55:23
	jgtu r3, r5, .LBB3_8
.Ltmp40:
// %bb.1:
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __eqsf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __eqsf2:a <- $r0
	.loc	1 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:0
	and r4, r1, 2147483647
.Ltmp41:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	.loc	1 55 23                         // uPIMulator_frontend/sdk/syslib/comparesf2.c:55:23
	jgtu r4, r5, .LBB3_8
.Ltmp42:
// %bb.2:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __eqsf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __eqsf2:a <- $r0
	.loc	1 59 15 is_stmt 1               // uPIMulator_frontend/sdk/syslib/comparesf2.c:59:15
	or r2, r4, r3, z, .LBB3_3
.Ltmp43:
// %bb.4:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __eqsf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __eqsf2:a <- $r0
	.loc	1 64 15                         // uPIMulator_frontend/sdk/syslib/comparesf2.c:64:15
	and r2, r1, r0, mi, .LBB3_6
.Ltmp44:
// %bb.5:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __eqsf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __eqsf2:a <- $r0
	.loc	1 0 15 is_stmt 0                // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:15
	move r2, -1
.Ltmp45:
	.loc	1 65 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/comparesf2.c:65:13
	jlts r0, r1, .LBB3_8
.Ltmp46:
.LBB3_7:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __eqsf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __eqsf2:a <- $r0
	.loc	1 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:0
	sub r2, r0, r1, neq
.Ltmp47:
.LBB3_8:
	//DEBUG_VALUE: __eqsf2:b <- $r1
	//DEBUG_VALUE: __eqsf2:a <- $r0
	.loc	1 142 5 is_stmt 1               // uPIMulator_frontend/sdk/syslib/comparesf2.c:142:5
	move r0, r2
.Ltmp48:
	jump r23
.Ltmp49:
.LBB3_3:
	//DEBUG_VALUE: __eqsf2:b <- $r1
	//DEBUG_VALUE: __eqsf2:a <- $r0
	.loc	1 0 5 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:5
	move r2, 0
	.loc	1 142 5                         // uPIMulator_frontend/sdk/syslib/comparesf2.c:142:5
	move r0, r2
.Ltmp50:
	jump r23
.Ltmp51:
.LBB3_6:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __eqsf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __eqsf2:a <- $r0
	.loc	1 0 5                           // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:5
	move r2, -1
.Ltmp52:
	.loc	1 78 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/comparesf2.c:78:13
	jles r0, r1, .LBB3_7
	jump .LBB3_8
.Ltmp53:
.Lfunc_end3:
	.size	__eqsf2, .Lfunc_end3-__eqsf2
	.cfi_endproc
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/fp_lib.h"
	.file	3 "/root" "uPIMulator_frontend/sdk/stdlib/stdint.h"
	.section	.stack_sizes,"o",@progbits,.text.__eqsf2
	.long	.Lfunc_begin3
	.byte	0
	.section	.text.__eqsf2,"ax",@progbits
                                        // -- End function
	.section	.text.__ltsf2,"ax",@progbits
	.globl	__ltsf2                         // -- Begin function __ltsf2
	.type	__ltsf2,@function
__ltsf2:                                // @__ltsf2
.Lfunc_begin4:
	.loc	1 147 0                         // uPIMulator_frontend/sdk/syslib/comparesf2.c:147:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __ltsf2:a <- $r0
	//DEBUG_VALUE: __ltsf2:a <- $r0
	//DEBUG_VALUE: __ltsf2:b <- $r1
	//DEBUG_VALUE: __ltsf2:b <- $r1
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: toRep:x <- $r0
	//DEBUG_VALUE: toRep:x <- $r0
	//DEBUG_VALUE: toRep:x <- undef
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: toRep:rep <- $r0
	//DEBUG_VALUE: toRep:rep <- $r0
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	.loc	1 51 29 prologue_end            // uPIMulator_frontend/sdk/syslib/comparesf2.c:51:29
	and r3, r0, 2147483647
.Ltmp54:
	//DEBUG_VALUE: __lesf2:bAbs <- undef
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	.loc	1 0 29 is_stmt 0                // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:29
	move r5, 2139095040
	move r2, 1
.Ltmp55:
	.loc	1 55 23 is_stmt 1               // uPIMulator_frontend/sdk/syslib/comparesf2.c:55:23
	jgtu r3, r5, .LBB4_8
.Ltmp56:
// %bb.1:
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __ltsf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __ltsf2:a <- $r0
	.loc	1 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:0
	and r4, r1, 2147483647
.Ltmp57:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	.loc	1 55 23                         // uPIMulator_frontend/sdk/syslib/comparesf2.c:55:23
	jgtu r4, r5, .LBB4_8
.Ltmp58:
// %bb.2:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __ltsf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __ltsf2:a <- $r0
	.loc	1 59 15 is_stmt 1               // uPIMulator_frontend/sdk/syslib/comparesf2.c:59:15
	or r2, r4, r3, z, .LBB4_3
.Ltmp59:
// %bb.4:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __ltsf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __ltsf2:a <- $r0
	.loc	1 64 15                         // uPIMulator_frontend/sdk/syslib/comparesf2.c:64:15
	and r2, r1, r0, mi, .LBB4_6
.Ltmp60:
// %bb.5:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __ltsf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __ltsf2:a <- $r0
	.loc	1 0 15 is_stmt 0                // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:15
	move r2, -1
.Ltmp61:
	.loc	1 65 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/comparesf2.c:65:13
	jlts r0, r1, .LBB4_8
.Ltmp62:
.LBB4_7:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __ltsf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __ltsf2:a <- $r0
	.loc	1 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:0
	sub r2, r0, r1, neq
.Ltmp63:
.LBB4_8:
	//DEBUG_VALUE: __ltsf2:b <- $r1
	//DEBUG_VALUE: __ltsf2:a <- $r0
	.loc	1 148 5 is_stmt 1               // uPIMulator_frontend/sdk/syslib/comparesf2.c:148:5
	move r0, r2
.Ltmp64:
	jump r23
.Ltmp65:
.LBB4_3:
	//DEBUG_VALUE: __ltsf2:b <- $r1
	//DEBUG_VALUE: __ltsf2:a <- $r0
	.loc	1 0 5 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:5
	move r2, 0
	.loc	1 148 5                         // uPIMulator_frontend/sdk/syslib/comparesf2.c:148:5
	move r0, r2
.Ltmp66:
	jump r23
.Ltmp67:
.LBB4_6:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __ltsf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __ltsf2:a <- $r0
	.loc	1 0 5                           // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:5
	move r2, -1
.Ltmp68:
	.loc	1 78 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/comparesf2.c:78:13
	jles r0, r1, .LBB4_7
	jump .LBB4_8
.Ltmp69:
.Lfunc_end4:
	.size	__ltsf2, .Lfunc_end4-__ltsf2
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__ltsf2
	.long	.Lfunc_begin4
	.byte	0
	.section	.text.__ltsf2,"ax",@progbits
                                        // -- End function
	.section	.text.__nesf2,"ax",@progbits
	.globl	__nesf2                         // -- Begin function __nesf2
	.type	__nesf2,@function
__nesf2:                                // @__nesf2
.Lfunc_begin5:
	.loc	1 153 0                         // uPIMulator_frontend/sdk/syslib/comparesf2.c:153:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __nesf2:a <- $r0
	//DEBUG_VALUE: __nesf2:a <- $r0
	//DEBUG_VALUE: __nesf2:b <- $r1
	//DEBUG_VALUE: __nesf2:b <- $r1
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: toRep:x <- $r0
	//DEBUG_VALUE: toRep:x <- $r0
	//DEBUG_VALUE: toRep:x <- undef
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: toRep:rep <- $r0
	//DEBUG_VALUE: toRep:rep <- $r0
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	.loc	1 51 29 prologue_end            // uPIMulator_frontend/sdk/syslib/comparesf2.c:51:29
	and r3, r0, 2147483647
.Ltmp70:
	//DEBUG_VALUE: __lesf2:bAbs <- undef
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	.loc	1 0 29 is_stmt 0                // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:29
	move r5, 2139095040
	move r2, 1
.Ltmp71:
	.loc	1 55 23 is_stmt 1               // uPIMulator_frontend/sdk/syslib/comparesf2.c:55:23
	jgtu r3, r5, .LBB5_8
.Ltmp72:
// %bb.1:
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __nesf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __nesf2:a <- $r0
	.loc	1 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:0
	and r4, r1, 2147483647
.Ltmp73:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	.loc	1 55 23                         // uPIMulator_frontend/sdk/syslib/comparesf2.c:55:23
	jgtu r4, r5, .LBB5_8
.Ltmp74:
// %bb.2:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __nesf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __nesf2:a <- $r0
	.loc	1 59 15 is_stmt 1               // uPIMulator_frontend/sdk/syslib/comparesf2.c:59:15
	or r2, r4, r3, z, .LBB5_3
.Ltmp75:
// %bb.4:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __nesf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __nesf2:a <- $r0
	.loc	1 64 15                         // uPIMulator_frontend/sdk/syslib/comparesf2.c:64:15
	and r2, r1, r0, mi, .LBB5_6
.Ltmp76:
// %bb.5:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __nesf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __nesf2:a <- $r0
	.loc	1 0 15 is_stmt 0                // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:15
	move r2, -1
.Ltmp77:
	.loc	1 65 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/comparesf2.c:65:13
	jlts r0, r1, .LBB5_8
.Ltmp78:
.LBB5_7:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __nesf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __nesf2:a <- $r0
	.loc	1 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:0
	sub r2, r0, r1, neq
.Ltmp79:
.LBB5_8:
	//DEBUG_VALUE: __nesf2:b <- $r1
	//DEBUG_VALUE: __nesf2:a <- $r0
	.loc	1 154 5 is_stmt 1               // uPIMulator_frontend/sdk/syslib/comparesf2.c:154:5
	move r0, r2
.Ltmp80:
	jump r23
.Ltmp81:
.LBB5_3:
	//DEBUG_VALUE: __nesf2:b <- $r1
	//DEBUG_VALUE: __nesf2:a <- $r0
	.loc	1 0 5 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:5
	move r2, 0
	.loc	1 154 5                         // uPIMulator_frontend/sdk/syslib/comparesf2.c:154:5
	move r0, r2
.Ltmp82:
	jump r23
.Ltmp83:
.LBB5_6:
	//DEBUG_VALUE: __lesf2:bAbs <- $r4
	//DEBUG_VALUE: __lesf2:aAbs <- $r3
	//DEBUG_VALUE: __lesf2:bInt <- $r1
	//DEBUG_VALUE: __lesf2:b <- $r1
	//DEBUG_VALUE: __nesf2:b <- $r1
	//DEBUG_VALUE: __lesf2:aInt <- $r0
	//DEBUG_VALUE: __lesf2:a <- $r0
	//DEBUG_VALUE: __nesf2:a <- $r0
	.loc	1 0 5                           // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:5
	move r2, -1
.Ltmp84:
	.loc	1 78 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/comparesf2.c:78:13
	jles r0, r1, .LBB5_7
	jump .LBB5_8
.Ltmp85:
.Lfunc_end5:
	.size	__nesf2, .Lfunc_end5-__nesf2
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__nesf2
	.long	.Lfunc_begin5
	.byte	0
	.section	.text.__nesf2,"ax",@progbits
                                        // -- End function
	.section	.text.__gtsf2,"ax",@progbits
	.globl	__gtsf2                         // -- Begin function __gtsf2
	.type	__gtsf2,@function
__gtsf2:                                // @__gtsf2
.Lfunc_begin6:
	.loc	1 159 0                         // uPIMulator_frontend/sdk/syslib/comparesf2.c:159:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __gtsf2:a <- $r0
	//DEBUG_VALUE: __gtsf2:b <- $r1
	//DEBUG_VALUE: __gesf2:a <- $r0
	//DEBUG_VALUE: __gesf2:b <- $r1
	//DEBUG_VALUE: toRep:x <- $r0
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: toRep:rep <- $r0
	move r2, r0
.Ltmp86:
	//DEBUG_VALUE: __gesf2:bInt <- $r1
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: __gesf2:aInt <- $r2
	//DEBUG_VALUE: toRep:rep <- $r2
	//DEBUG_VALUE: toRep:x <- $r2
	//DEBUG_VALUE: __gesf2:b <- $r1
	//DEBUG_VALUE: __gesf2:a <- $r2
	//DEBUG_VALUE: __gtsf2:b <- $r1
	//DEBUG_VALUE: __gtsf2:a <- $r2
	.loc	1 105 29 prologue_end           // uPIMulator_frontend/sdk/syslib/comparesf2.c:105:29
	and r3, r2, 2147483647
.Ltmp87:
	//DEBUG_VALUE: __gesf2:bAbs <- undef
	//DEBUG_VALUE: __gesf2:aAbs <- $r3
	.loc	1 0 29 is_stmt 0                // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:29
	move r4, 2139095040
	move r0, -1
.Ltmp88:
	.loc	1 108 23 is_stmt 1              // uPIMulator_frontend/sdk/syslib/comparesf2.c:108:23
	jgtu r3, r4, .LBB6_8
.Ltmp89:
// %bb.1:
	//DEBUG_VALUE: __gesf2:aAbs <- $r3
	//DEBUG_VALUE: __gtsf2:a <- $r2
	//DEBUG_VALUE: __gesf2:a <- $r2
	//DEBUG_VALUE: __gesf2:aInt <- $r2
	//DEBUG_VALUE: __gesf2:bInt <- $r1
	//DEBUG_VALUE: __gesf2:b <- $r1
	//DEBUG_VALUE: __gtsf2:b <- $r1
	.loc	1 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:0
	and r5, r1, 2147483647
.Ltmp90:
	//DEBUG_VALUE: __gesf2:bAbs <- $r5
	.loc	1 108 23                        // uPIMulator_frontend/sdk/syslib/comparesf2.c:108:23
	jgtu r5, r4, .LBB6_8
.Ltmp91:
// %bb.2:
	//DEBUG_VALUE: __gesf2:bAbs <- $r5
	//DEBUG_VALUE: __gesf2:aAbs <- $r3
	//DEBUG_VALUE: __gtsf2:a <- $r2
	//DEBUG_VALUE: __gesf2:a <- $r2
	//DEBUG_VALUE: __gesf2:aInt <- $r2
	//DEBUG_VALUE: __gesf2:bInt <- $r1
	//DEBUG_VALUE: __gesf2:b <- $r1
	//DEBUG_VALUE: __gtsf2:b <- $r1
	.loc	1 110 15 is_stmt 1              // uPIMulator_frontend/sdk/syslib/comparesf2.c:110:15
	or r3, r5, r3, z, .LBB6_3
.Ltmp92:
// %bb.4:
	//DEBUG_VALUE: __gesf2:bAbs <- $r5
	//DEBUG_VALUE: __gtsf2:a <- $r2
	//DEBUG_VALUE: __gesf2:a <- $r2
	//DEBUG_VALUE: __gesf2:aInt <- $r2
	//DEBUG_VALUE: __gesf2:bInt <- $r1
	//DEBUG_VALUE: __gesf2:b <- $r1
	//DEBUG_VALUE: __gtsf2:b <- $r1
	.loc	1 112 15                        // uPIMulator_frontend/sdk/syslib/comparesf2.c:112:15
	and r3, r1, r2, mi, .LBB6_6
.Ltmp93:
// %bb.5:
	//DEBUG_VALUE: __gesf2:bAbs <- $r5
	//DEBUG_VALUE: __gtsf2:a <- $r2
	//DEBUG_VALUE: __gesf2:a <- $r2
	//DEBUG_VALUE: __gesf2:aInt <- $r2
	//DEBUG_VALUE: __gesf2:bInt <- $r1
	//DEBUG_VALUE: __gesf2:b <- $r1
	//DEBUG_VALUE: __gtsf2:b <- $r1
	.loc	1 113 13                        // uPIMulator_frontend/sdk/syslib/comparesf2.c:113:13
	jlts r2, r1, .LBB6_8
.Ltmp94:
.LBB6_7:
	//DEBUG_VALUE: __gesf2:bAbs <- $r5
	//DEBUG_VALUE: __gtsf2:a <- $r2
	//DEBUG_VALUE: __gesf2:a <- $r2
	//DEBUG_VALUE: __gesf2:aInt <- $r2
	//DEBUG_VALUE: __gesf2:bInt <- $r1
	//DEBUG_VALUE: __gesf2:b <- $r1
	//DEBUG_VALUE: __gtsf2:b <- $r1
	.loc	1 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:0
	sub r0, r2, r1, neq
.Ltmp95:
.LBB6_8:
	//DEBUG_VALUE: __gtsf2:a <- $r2
	//DEBUG_VALUE: __gtsf2:b <- $r1
	.loc	1 160 5 is_stmt 1               // uPIMulator_frontend/sdk/syslib/comparesf2.c:160:5
	jump r23
.Ltmp96:
.LBB6_3:
	//DEBUG_VALUE: __gtsf2:a <- $r2
	//DEBUG_VALUE: __gtsf2:b <- $r1
	.loc	1 0 5 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/comparesf2.c:0:5
	move r0, 0
	.loc	1 160 5                         // uPIMulator_frontend/sdk/syslib/comparesf2.c:160:5
	jump r23
.Ltmp97:
.LBB6_6:
	//DEBUG_VALUE: __gesf2:bAbs <- $r5
	//DEBUG_VALUE: __gtsf2:a <- $r2
	//DEBUG_VALUE: __gesf2:a <- $r2
	//DEBUG_VALUE: __gesf2:aInt <- $r2
	//DEBUG_VALUE: __gesf2:bInt <- $r1
	//DEBUG_VALUE: __gesf2:b <- $r1
	//DEBUG_VALUE: __gtsf2:b <- $r1
	.loc	1 120 13 is_stmt 1              // uPIMulator_frontend/sdk/syslib/comparesf2.c:120:13
	jles r2, r1, .LBB6_7
	jump .LBB6_8
.Ltmp98:
.Lfunc_end6:
	.size	__gtsf2, .Lfunc_end6-__gtsf2
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__gtsf2
	.long	.Lfunc_begin6
	.byte	0
	.section	.text.__gtsf2,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp9-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp10-.Lfunc_begin0
	.long	.Ltmp11-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp12-.Lfunc_begin0
	.long	.Ltmp16-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc1:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp9-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp10-.Lfunc_begin0
	.long	.Ltmp11-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp12-.Lfunc_begin0
	.long	.Ltmp16-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc2:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp15-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	0
	.long	0
.Ldebug_loc3:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc4:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Lfunc_begin1-.Lfunc_begin1
	.long	.Ltmp18-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp18-.Lfunc_begin1
	.long	.Lfunc_end1-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc5:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp22-.Lfunc_begin1
	.long	.Ltmp31-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	0
	.long	0
.Ldebug_loc6:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp19-.Lfunc_begin1
	.long	.Ltmp24-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc7:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Lfunc_begin2-.Lfunc_begin2
	.long	.Ltmp33-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc8:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Lfunc_begin2-.Lfunc_begin2
	.long	.Ltmp34-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc9:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp33-.Lfunc_begin2
	.long	.Ltmp35-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc10:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp34-.Lfunc_begin2
	.long	.Ltmp36-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc11:
	.long	-1
	.long	.Lfunc_begin3                   //   base address
	.long	.Lfunc_begin3-.Lfunc_begin3
	.long	.Ltmp48-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp49-.Lfunc_begin3
	.long	.Ltmp50-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp51-.Lfunc_begin3
	.long	.Lfunc_end3-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc12:
	.long	-1
	.long	.Lfunc_begin3                   //   base address
	.long	.Lfunc_begin3-.Lfunc_begin3
	.long	.Ltmp47-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp51-.Lfunc_begin3
	.long	.Lfunc_end3-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc13:
	.long	-1
	.long	.Lfunc_begin3                   //   base address
	.long	.Lfunc_begin3-.Lfunc_begin3
	.long	.Ltmp47-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp51-.Lfunc_begin3
	.long	.Lfunc_end3-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc14:
	.long	-1
	.long	.Lfunc_begin3                   //   base address
	.long	.Lfunc_begin3-.Lfunc_begin3
	.long	.Ltmp47-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp51-.Lfunc_begin3
	.long	.Lfunc_end3-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc15:
	.long	-1
	.long	.Lfunc_begin3                   //   base address
	.long	.Lfunc_begin3-.Lfunc_begin3
	.long	.Ltmp47-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp51-.Lfunc_begin3
	.long	.Lfunc_end3-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc16:
	.long	-1
	.long	.Lfunc_begin3                   //   base address
	.long	.Ltmp41-.Lfunc_begin3
	.long	.Ltmp47-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp51-.Lfunc_begin3
	.long	.Lfunc_end3-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	0
	.long	0
.Ldebug_loc17:
	.long	-1
	.long	.Lfunc_begin3                   //   base address
	.long	.Ltmp38-.Lfunc_begin3
	.long	.Ltmp47-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp51-.Lfunc_begin3
	.long	.Lfunc_end3-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc18:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Lfunc_begin4-.Lfunc_begin4
	.long	.Ltmp64-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp65-.Lfunc_begin4
	.long	.Ltmp66-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp67-.Lfunc_begin4
	.long	.Lfunc_end4-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc19:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Lfunc_begin4-.Lfunc_begin4
	.long	.Ltmp63-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp67-.Lfunc_begin4
	.long	.Lfunc_end4-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc20:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Lfunc_begin4-.Lfunc_begin4
	.long	.Ltmp63-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp67-.Lfunc_begin4
	.long	.Lfunc_end4-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc21:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Lfunc_begin4-.Lfunc_begin4
	.long	.Ltmp63-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp67-.Lfunc_begin4
	.long	.Lfunc_end4-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc22:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Lfunc_begin4-.Lfunc_begin4
	.long	.Ltmp63-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp67-.Lfunc_begin4
	.long	.Lfunc_end4-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc23:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Ltmp57-.Lfunc_begin4
	.long	.Ltmp63-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp67-.Lfunc_begin4
	.long	.Lfunc_end4-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	0
	.long	0
.Ldebug_loc24:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Ltmp54-.Lfunc_begin4
	.long	.Ltmp63-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp67-.Lfunc_begin4
	.long	.Lfunc_end4-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc25:
	.long	-1
	.long	.Lfunc_begin5                   //   base address
	.long	.Lfunc_begin5-.Lfunc_begin5
	.long	.Ltmp80-.Lfunc_begin5
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp81-.Lfunc_begin5
	.long	.Ltmp82-.Lfunc_begin5
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp83-.Lfunc_begin5
	.long	.Lfunc_end5-.Lfunc_begin5
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc26:
	.long	-1
	.long	.Lfunc_begin5                   //   base address
	.long	.Lfunc_begin5-.Lfunc_begin5
	.long	.Ltmp79-.Lfunc_begin5
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp83-.Lfunc_begin5
	.long	.Lfunc_end5-.Lfunc_begin5
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc27:
	.long	-1
	.long	.Lfunc_begin5                   //   base address
	.long	.Lfunc_begin5-.Lfunc_begin5
	.long	.Ltmp79-.Lfunc_begin5
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp83-.Lfunc_begin5
	.long	.Lfunc_end5-.Lfunc_begin5
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc28:
	.long	-1
	.long	.Lfunc_begin5                   //   base address
	.long	.Lfunc_begin5-.Lfunc_begin5
	.long	.Ltmp79-.Lfunc_begin5
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp83-.Lfunc_begin5
	.long	.Lfunc_end5-.Lfunc_begin5
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc29:
	.long	-1
	.long	.Lfunc_begin5                   //   base address
	.long	.Lfunc_begin5-.Lfunc_begin5
	.long	.Ltmp79-.Lfunc_begin5
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp83-.Lfunc_begin5
	.long	.Lfunc_end5-.Lfunc_begin5
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc30:
	.long	-1
	.long	.Lfunc_begin5                   //   base address
	.long	.Ltmp73-.Lfunc_begin5
	.long	.Ltmp79-.Lfunc_begin5
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp83-.Lfunc_begin5
	.long	.Lfunc_end5-.Lfunc_begin5
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	0
	.long	0
.Ldebug_loc31:
	.long	-1
	.long	.Lfunc_begin5                   //   base address
	.long	.Ltmp70-.Lfunc_begin5
	.long	.Ltmp79-.Lfunc_begin5
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp83-.Lfunc_begin5
	.long	.Lfunc_end5-.Lfunc_begin5
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc32:
	.long	-1
	.long	.Lfunc_begin6                   //   base address
	.long	.Lfunc_begin6-.Lfunc_begin6
	.long	.Ltmp86-.Lfunc_begin6
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp86-.Lfunc_begin6
	.long	.Lfunc_end6-.Lfunc_begin6
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc33:
	.long	-1
	.long	.Lfunc_begin6                   //   base address
	.long	.Ltmp86-.Lfunc_begin6
	.long	.Ltmp95-.Lfunc_begin6
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp97-.Lfunc_begin6
	.long	.Lfunc_end6-.Lfunc_begin6
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc34:
	.long	-1
	.long	.Lfunc_begin6                   //   base address
	.long	.Lfunc_begin6-.Lfunc_begin6
	.long	.Ltmp95-.Lfunc_begin6
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp97-.Lfunc_begin6
	.long	.Lfunc_end6-.Lfunc_begin6
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc35:
	.long	-1
	.long	.Lfunc_begin6                   //   base address
	.long	.Ltmp86-.Lfunc_begin6
	.long	.Ltmp95-.Lfunc_begin6
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp97-.Lfunc_begin6
	.long	.Lfunc_end6-.Lfunc_begin6
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc36:
	.long	-1
	.long	.Lfunc_begin6                   //   base address
	.long	.Ltmp86-.Lfunc_begin6
	.long	.Ltmp95-.Lfunc_begin6
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp97-.Lfunc_begin6
	.long	.Lfunc_end6-.Lfunc_begin6
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc37:
	.long	-1
	.long	.Lfunc_begin6                   //   base address
	.long	.Ltmp90-.Lfunc_begin6
	.long	.Ltmp95-.Lfunc_begin6
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp97-.Lfunc_begin6
	.long	.Lfunc_end6-.Lfunc_begin6
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	0
	.long	0
.Ldebug_loc38:
	.long	-1
	.long	.Lfunc_begin6                   //   base address
	.long	.Ltmp87-.Lfunc_begin6
	.long	.Ltmp92-.Lfunc_begin6
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	4                               // DW_TAG_enumeration_type
	.byte	1                               // DW_CHILDREN_yes
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	40                              // DW_TAG_enumerator
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	28                              // DW_AT_const_value
	.byte	13                              // DW_FORM_sdata
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	11                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	12                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	13                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	14                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	15                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	16                              // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	17                              // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	18                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	19                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	1                               // DW_CHILDREN_yes
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x402 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	0                               // DW_AT_low_pc
	.long	.Ldebug_ranges4                 // DW_AT_ranges
	.byte	2                               // Abbrev [2] 0x26:0x25 DW_TAG_enumeration_type
	.long	75                              // DW_AT_type
	.long	.Linfo_string8                  // DW_AT_name
	.byte	4                               // DW_AT_byte_size
	.byte	1                               // DW_AT_decl_file
	.byte	43                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x32:0x6 DW_TAG_enumerator
	.long	.Linfo_string4                  // DW_AT_name
	.byte	127                             // DW_AT_const_value
	.byte	3                               // Abbrev [3] 0x38:0x6 DW_TAG_enumerator
	.long	.Linfo_string5                  // DW_AT_name
	.byte	0                               // DW_AT_const_value
	.byte	3                               // Abbrev [3] 0x3e:0x6 DW_TAG_enumerator
	.long	.Linfo_string6                  // DW_AT_name
	.byte	1                               // DW_AT_const_value
	.byte	3                               // Abbrev [3] 0x44:0x6 DW_TAG_enumerator
	.long	.Linfo_string7                  // DW_AT_name
	.byte	1                               // DW_AT_const_value
	.byte	0                               // End Of Children Mark
	.byte	4                               // Abbrev [4] 0x4b:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	2                               // Abbrev [2] 0x52:0x25 DW_TAG_enumeration_type
	.long	75                              // DW_AT_type
	.long	.Linfo_string13                 // DW_AT_name
	.byte	4                               // DW_AT_byte_size
	.byte	1                               // DW_AT_decl_file
	.byte	92                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x5e:0x6 DW_TAG_enumerator
	.long	.Linfo_string9                  // DW_AT_name
	.byte	127                             // DW_AT_const_value
	.byte	3                               // Abbrev [3] 0x64:0x6 DW_TAG_enumerator
	.long	.Linfo_string10                 // DW_AT_name
	.byte	0                               // DW_AT_const_value
	.byte	3                               // Abbrev [3] 0x6a:0x6 DW_TAG_enumerator
	.long	.Linfo_string11                 // DW_AT_name
	.byte	1                               // DW_AT_const_value
	.byte	3                               // Abbrev [3] 0x70:0x6 DW_TAG_enumerator
	.long	.Linfo_string12                 // DW_AT_name
	.byte	127                             // DW_AT_const_value
	.byte	0                               // End Of Children Mark
	.byte	5                               // Abbrev [5] 0x77:0x42 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	331                             // DW_AT_abstract_origin
	.byte	6                               // Abbrev [6] 0x86:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	343                             // DW_AT_abstract_origin
	.byte	7                               // Abbrev [7] 0x8f:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	354                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x96:0x9 DW_TAG_variable
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	365                             // DW_AT_abstract_origin
	.byte	9                               // Abbrev [9] 0x9f:0x7 DW_TAG_variable
	.byte	1                               // DW_AT_location
	.byte	81
	.long	376                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0xa6:0x9 DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	387                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0xaf:0x9 DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	398                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	5                               // Abbrev [5] 0xb9:0x40 DW_TAG_subprogram
	.long	.Lfunc_begin1                   // DW_AT_low_pc
	.long	.Lfunc_end1-.Lfunc_begin1       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	840                             // DW_AT_abstract_origin
	.byte	6                               // Abbrev [6] 0xc8:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	852                             // DW_AT_abstract_origin
	.byte	7                               // Abbrev [7] 0xd1:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	863                             // DW_AT_abstract_origin
	.byte	9                               // Abbrev [9] 0xd8:0x7 DW_TAG_variable
	.byte	1                               // DW_AT_location
	.byte	81
	.long	874                             // DW_AT_abstract_origin
	.byte	9                               // Abbrev [9] 0xdf:0x7 DW_TAG_variable
	.byte	1                               // DW_AT_location
	.byte	82
	.long	885                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0xe6:0x9 DW_TAG_variable
	.long	.Ldebug_loc5                    // DW_AT_location
	.long	896                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0xef:0x9 DW_TAG_variable
	.long	.Ldebug_loc6                    // DW_AT_location
	.long	907                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0xf9:0x52 DW_TAG_subprogram
	.long	.Lfunc_begin2                   // DW_AT_low_pc
	.long	.Lfunc_end2-.Lfunc_begin2       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string29                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	130                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	75                              // DW_AT_type
                                        // DW_AT_external
	.byte	11                              // Abbrev [11] 0x10e:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc7                    // DW_AT_location
	.long	.Linfo_string15                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	130                             // DW_AT_decl_line
	.long	410                             // DW_AT_type
	.byte	11                              // Abbrev [11] 0x11d:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc8                    // DW_AT_location
	.long	.Linfo_string18                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	130                             // DW_AT_decl_line
	.long	410                             // DW_AT_type
	.byte	12                              // Abbrev [12] 0x12c:0xf DW_TAG_variable
	.long	.Ldebug_loc9                    // DW_AT_location
	.long	.Linfo_string27                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	132                             // DW_AT_decl_line
	.long	455                             // DW_AT_type
	.byte	12                              // Abbrev [12] 0x13b:0xf DW_TAG_variable
	.long	.Ldebug_loc10                   // DW_AT_location
	.long	.Linfo_string23                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	133                             // DW_AT_decl_line
	.long	455                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	13                              // Abbrev [13] 0x14b:0x4f DW_TAG_subprogram
	.long	.Linfo_string14                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	46                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	38                              // DW_AT_type
                                        // DW_AT_external
	.byte	1                               // DW_AT_inline
	.byte	14                              // Abbrev [14] 0x157:0xb DW_TAG_formal_parameter
	.long	.Linfo_string15                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	46                              // DW_AT_decl_line
	.long	410                             // DW_AT_type
	.byte	14                              // Abbrev [14] 0x162:0xb DW_TAG_formal_parameter
	.long	.Linfo_string18                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	46                              // DW_AT_decl_line
	.long	410                             // DW_AT_type
	.byte	15                              // Abbrev [15] 0x16d:0xb DW_TAG_variable
	.long	.Linfo_string19                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	49                              // DW_AT_decl_line
	.long	428                             // DW_AT_type
	.byte	15                              // Abbrev [15] 0x178:0xb DW_TAG_variable
	.long	.Linfo_string22                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	50                              // DW_AT_decl_line
	.long	428                             // DW_AT_type
	.byte	15                              // Abbrev [15] 0x183:0xb DW_TAG_variable
	.long	.Linfo_string23                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	52                              // DW_AT_decl_line
	.long	455                             // DW_AT_type
	.byte	15                              // Abbrev [15] 0x18e:0xb DW_TAG_variable
	.long	.Linfo_string27                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	51                              // DW_AT_decl_line
	.long	455                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	16                              // Abbrev [16] 0x19a:0xb DW_TAG_typedef
	.long	421                             // DW_AT_type
	.long	.Linfo_string17                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	45                              // DW_AT_decl_line
	.byte	4                               // Abbrev [4] 0x1a5:0x7 DW_TAG_base_type
	.long	.Linfo_string16                 // DW_AT_name
	.byte	4                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	17                              // Abbrev [17] 0x1ac:0x5 DW_TAG_const_type
	.long	433                             // DW_AT_type
	.byte	16                              // Abbrev [16] 0x1b1:0xb DW_TAG_typedef
	.long	444                             // DW_AT_type
	.long	.Linfo_string21                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	44                              // DW_AT_decl_line
	.byte	16                              // Abbrev [16] 0x1bc:0xb DW_TAG_typedef
	.long	75                              // DW_AT_type
	.long	.Linfo_string20                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	29                              // DW_AT_decl_line
	.byte	17                              // Abbrev [17] 0x1c7:0x5 DW_TAG_const_type
	.long	460                             // DW_AT_type
	.byte	16                              // Abbrev [16] 0x1cc:0xb DW_TAG_typedef
	.long	471                             // DW_AT_type
	.long	.Linfo_string26                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	43                              // DW_AT_decl_line
	.byte	16                              // Abbrev [16] 0x1d7:0xb DW_TAG_typedef
	.long	482                             // DW_AT_type
	.long	.Linfo_string25                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	48                              // DW_AT_decl_line
	.byte	4                               // Abbrev [4] 0x1e2:0x7 DW_TAG_base_type
	.long	.Linfo_string24                 // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	10                              // Abbrev [10] 0x1e9:0x75 DW_TAG_subprogram
	.long	.Lfunc_begin3                   // DW_AT_low_pc
	.long	.Lfunc_end3-.Lfunc_begin3       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string30                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	140                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	38                              // DW_AT_type
                                        // DW_AT_external
	.byte	11                              // Abbrev [11] 0x1fe:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc11                   // DW_AT_location
	.long	.Linfo_string15                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	140                             // DW_AT_decl_line
	.long	410                             // DW_AT_type
	.byte	18                              // Abbrev [18] 0x20d:0xd DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	.Linfo_string18                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	140                             // DW_AT_decl_line
	.long	410                             // DW_AT_type
	.byte	19                              // Abbrev [19] 0x21a:0x43 DW_TAG_inlined_subroutine
	.long	331                             // DW_AT_abstract_origin
	.long	.Ldebug_ranges0                 // DW_AT_ranges
	.byte	1                               // DW_AT_call_file
	.byte	142                             // DW_AT_call_line
	.byte	12                              // DW_AT_call_column
	.byte	6                               // Abbrev [6] 0x226:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc12                   // DW_AT_location
	.long	343                             // DW_AT_abstract_origin
	.byte	6                               // Abbrev [6] 0x22f:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc13                   // DW_AT_location
	.long	354                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x238:0x9 DW_TAG_variable
	.long	.Ldebug_loc14                   // DW_AT_location
	.long	365                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x241:0x9 DW_TAG_variable
	.long	.Ldebug_loc15                   // DW_AT_location
	.long	376                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x24a:0x9 DW_TAG_variable
	.long	.Ldebug_loc16                   // DW_AT_location
	.long	387                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x253:0x9 DW_TAG_variable
	.long	.Ldebug_loc17                   // DW_AT_location
	.long	398                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x25e:0x75 DW_TAG_subprogram
	.long	.Lfunc_begin4                   // DW_AT_low_pc
	.long	.Lfunc_end4-.Lfunc_begin4       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string31                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	146                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	38                              // DW_AT_type
                                        // DW_AT_external
	.byte	11                              // Abbrev [11] 0x273:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc18                   // DW_AT_location
	.long	.Linfo_string15                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	146                             // DW_AT_decl_line
	.long	410                             // DW_AT_type
	.byte	18                              // Abbrev [18] 0x282:0xd DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	.Linfo_string18                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	146                             // DW_AT_decl_line
	.long	410                             // DW_AT_type
	.byte	19                              // Abbrev [19] 0x28f:0x43 DW_TAG_inlined_subroutine
	.long	331                             // DW_AT_abstract_origin
	.long	.Ldebug_ranges1                 // DW_AT_ranges
	.byte	1                               // DW_AT_call_file
	.byte	148                             // DW_AT_call_line
	.byte	12                              // DW_AT_call_column
	.byte	6                               // Abbrev [6] 0x29b:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc19                   // DW_AT_location
	.long	343                             // DW_AT_abstract_origin
	.byte	6                               // Abbrev [6] 0x2a4:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc20                   // DW_AT_location
	.long	354                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x2ad:0x9 DW_TAG_variable
	.long	.Ldebug_loc21                   // DW_AT_location
	.long	365                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x2b6:0x9 DW_TAG_variable
	.long	.Ldebug_loc22                   // DW_AT_location
	.long	376                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x2bf:0x9 DW_TAG_variable
	.long	.Ldebug_loc23                   // DW_AT_location
	.long	387                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x2c8:0x9 DW_TAG_variable
	.long	.Ldebug_loc24                   // DW_AT_location
	.long	398                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x2d3:0x75 DW_TAG_subprogram
	.long	.Lfunc_begin5                   // DW_AT_low_pc
	.long	.Lfunc_end5-.Lfunc_begin5       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string32                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	152                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	38                              // DW_AT_type
                                        // DW_AT_external
	.byte	11                              // Abbrev [11] 0x2e8:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc25                   // DW_AT_location
	.long	.Linfo_string15                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	152                             // DW_AT_decl_line
	.long	410                             // DW_AT_type
	.byte	18                              // Abbrev [18] 0x2f7:0xd DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	.Linfo_string18                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	152                             // DW_AT_decl_line
	.long	410                             // DW_AT_type
	.byte	19                              // Abbrev [19] 0x304:0x43 DW_TAG_inlined_subroutine
	.long	331                             // DW_AT_abstract_origin
	.long	.Ldebug_ranges2                 // DW_AT_ranges
	.byte	1                               // DW_AT_call_file
	.byte	154                             // DW_AT_call_line
	.byte	12                              // DW_AT_call_column
	.byte	6                               // Abbrev [6] 0x310:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc26                   // DW_AT_location
	.long	343                             // DW_AT_abstract_origin
	.byte	6                               // Abbrev [6] 0x319:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc27                   // DW_AT_location
	.long	354                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x322:0x9 DW_TAG_variable
	.long	.Ldebug_loc28                   // DW_AT_location
	.long	365                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x32b:0x9 DW_TAG_variable
	.long	.Ldebug_loc29                   // DW_AT_location
	.long	376                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x334:0x9 DW_TAG_variable
	.long	.Ldebug_loc30                   // DW_AT_location
	.long	387                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x33d:0x9 DW_TAG_variable
	.long	.Ldebug_loc31                   // DW_AT_location
	.long	398                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	13                              // Abbrev [13] 0x348:0x4f DW_TAG_subprogram
	.long	.Linfo_string28                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	100                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	82                              // DW_AT_type
                                        // DW_AT_external
	.byte	1                               // DW_AT_inline
	.byte	14                              // Abbrev [14] 0x354:0xb DW_TAG_formal_parameter
	.long	.Linfo_string15                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	100                             // DW_AT_decl_line
	.long	410                             // DW_AT_type
	.byte	14                              // Abbrev [14] 0x35f:0xb DW_TAG_formal_parameter
	.long	.Linfo_string18                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	100                             // DW_AT_decl_line
	.long	410                             // DW_AT_type
	.byte	15                              // Abbrev [15] 0x36a:0xb DW_TAG_variable
	.long	.Linfo_string22                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	104                             // DW_AT_decl_line
	.long	428                             // DW_AT_type
	.byte	15                              // Abbrev [15] 0x375:0xb DW_TAG_variable
	.long	.Linfo_string19                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	103                             // DW_AT_decl_line
	.long	428                             // DW_AT_type
	.byte	15                              // Abbrev [15] 0x380:0xb DW_TAG_variable
	.long	.Linfo_string23                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	106                             // DW_AT_decl_line
	.long	455                             // DW_AT_type
	.byte	15                              // Abbrev [15] 0x38b:0xb DW_TAG_variable
	.long	.Linfo_string27                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	105                             // DW_AT_decl_line
	.long	455                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x397:0x75 DW_TAG_subprogram
	.long	.Lfunc_begin6                   // DW_AT_low_pc
	.long	.Lfunc_end6-.Lfunc_begin6       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string33                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	158                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	82                              // DW_AT_type
                                        // DW_AT_external
	.byte	11                              // Abbrev [11] 0x3ac:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc32                   // DW_AT_location
	.long	.Linfo_string15                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	158                             // DW_AT_decl_line
	.long	410                             // DW_AT_type
	.byte	18                              // Abbrev [18] 0x3bb:0xd DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	.Linfo_string18                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	158                             // DW_AT_decl_line
	.long	410                             // DW_AT_type
	.byte	19                              // Abbrev [19] 0x3c8:0x43 DW_TAG_inlined_subroutine
	.long	840                             // DW_AT_abstract_origin
	.long	.Ldebug_ranges3                 // DW_AT_ranges
	.byte	1                               // DW_AT_call_file
	.byte	160                             // DW_AT_call_line
	.byte	12                              // DW_AT_call_column
	.byte	6                               // Abbrev [6] 0x3d4:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc33                   // DW_AT_location
	.long	852                             // DW_AT_abstract_origin
	.byte	6                               // Abbrev [6] 0x3dd:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc34                   // DW_AT_location
	.long	863                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x3e6:0x9 DW_TAG_variable
	.long	.Ldebug_loc35                   // DW_AT_location
	.long	874                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x3ef:0x9 DW_TAG_variable
	.long	.Ldebug_loc36                   // DW_AT_location
	.long	885                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x3f8:0x9 DW_TAG_variable
	.long	.Ldebug_loc37                   // DW_AT_location
	.long	896                             // DW_AT_abstract_origin
	.byte	8                               // Abbrev [8] 0x401:0x9 DW_TAG_variable
	.long	.Ldebug_loc38                   // DW_AT_location
	.long	907                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_ranges,"",@progbits
.Ldebug_ranges0:
	.long	.Lfunc_begin3
	.long	.Ltmp47
	.long	.Ltmp52
	.long	.Ltmp53
	.long	0
	.long	0
.Ldebug_ranges1:
	.long	.Lfunc_begin4
	.long	.Ltmp63
	.long	.Ltmp68
	.long	.Ltmp69
	.long	0
	.long	0
.Ldebug_ranges2:
	.long	.Lfunc_begin5
	.long	.Ltmp79
	.long	.Ltmp84
	.long	.Ltmp85
	.long	0
	.long	0
.Ldebug_ranges3:
	.long	.Ltmp86
	.long	.Ltmp95
	.long	.Ltmp97
	.long	.Ltmp98
	.long	0
	.long	0
.Ldebug_ranges4:
	.long	.Lfunc_begin0
	.long	.Lfunc_end0
	.long	.Lfunc_begin1
	.long	.Lfunc_end1
	.long	.Lfunc_begin2
	.long	.Lfunc_end2
	.long	.Lfunc_begin3
	.long	.Lfunc_end3
	.long	.Lfunc_begin4
	.long	.Lfunc_end4
	.long	.Lfunc_begin5
	.long	.Lfunc_end5
	.long	.Lfunc_begin6
	.long	.Lfunc_end6
	.long	0
	.long	0
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/comparesf2.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=156
.Linfo_string3:
	.asciz	"int"                           // string offset=177
.Linfo_string4:
	.asciz	"LE_LESS"                       // string offset=181
.Linfo_string5:
	.asciz	"LE_EQUAL"                      // string offset=189
.Linfo_string6:
	.asciz	"LE_GREATER"                    // string offset=198
.Linfo_string7:
	.asciz	"LE_UNORDERED"                  // string offset=209
.Linfo_string8:
	.asciz	"LE_RESULT"                     // string offset=222
.Linfo_string9:
	.asciz	"GE_LESS"                       // string offset=232
.Linfo_string10:
	.asciz	"GE_EQUAL"                      // string offset=240
.Linfo_string11:
	.asciz	"GE_GREATER"                    // string offset=249
.Linfo_string12:
	.asciz	"GE_UNORDERED"                  // string offset=260
.Linfo_string13:
	.asciz	"GE_RESULT"                     // string offset=273
.Linfo_string14:
	.asciz	"__lesf2"                       // string offset=283
.Linfo_string15:
	.asciz	"a"                             // string offset=291
.Linfo_string16:
	.asciz	"float"                         // string offset=293
.Linfo_string17:
	.asciz	"fp_t"                          // string offset=299
.Linfo_string18:
	.asciz	"b"                             // string offset=304
.Linfo_string19:
	.asciz	"aInt"                          // string offset=306
.Linfo_string20:
	.asciz	"int32_t"                       // string offset=311
.Linfo_string21:
	.asciz	"srep_t"                        // string offset=319
.Linfo_string22:
	.asciz	"bInt"                          // string offset=326
.Linfo_string23:
	.asciz	"bAbs"                          // string offset=331
.Linfo_string24:
	.asciz	"unsigned int"                  // string offset=336
.Linfo_string25:
	.asciz	"uint32_t"                      // string offset=349
.Linfo_string26:
	.asciz	"rep_t"                         // string offset=358
.Linfo_string27:
	.asciz	"aAbs"                          // string offset=364
.Linfo_string28:
	.asciz	"__gesf2"                       // string offset=369
.Linfo_string29:
	.asciz	"__unordsf2"                    // string offset=377
.Linfo_string30:
	.asciz	"__eqsf2"                       // string offset=388
.Linfo_string31:
	.asciz	"__ltsf2"                       // string offset=396
.Linfo_string32:
	.asciz	"__nesf2"                       // string offset=404
.Linfo_string33:
	.asciz	"__gtsf2"                       // string offset=412
	.globl	__cmpsf2
	.type	__cmpsf2,@function
.set __cmpsf2, __lesf2
	.addrsig
	.addrsig_sym __lesf2
	.section	.debug_line,"",@progbits
.Lline_table_start0:
