	.text
	.file	"ctzsi2.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/syslib/int_types.h"
	.section	.text.__ctzsi2,"ax",@progbits
	.globl	__ctzsi2                        // -- Begin function __ctzsi2
	.type	__ctzsi2,@function
__ctzsi2:                               // @__ctzsi2
.Lfunc_begin0:
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/ctzsi2.c"
	.loc	2 23 0                          // uPIMulator_frontend/sdk/syslib/ctzsi2.c:23:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __ctzsi2:a <- $r0
	//DEBUG_VALUE: __ctzsi2:a <- $r0
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: __ctzsi2:x <- $r0
	//DEBUG_VALUE: __ctzsi2:x <- $r0
	.loc	2 25 20 prologue_end            // uPIMulator_frontend/sdk/syslib/ctzsi2.c:25:20
	and r1, r0, 65535
	.loc	2 25 40 is_stmt 0               // uPIMulator_frontend/sdk/syslib/ctzsi2.c:25:40
	jeq r1, 0, .LBB0_1
.Ltmp0:
// %bb.2:
	//DEBUG_VALUE: __ctzsi2:x <- $r0
	//DEBUG_VALUE: __ctzsi2:a <- $r0
	.loc	2 0 40                          // uPIMulator_frontend/sdk/syslib/ctzsi2.c:0:40
	move r1, 0
.Ltmp1:
	//DEBUG_VALUE: __ctzsi2:t <- $r1
	.loc	2 26 7 is_stmt 1                // uPIMulator_frontend/sdk/syslib/ctzsi2.c:26:7
	lsr r0, r0, r1
.Ltmp2:
	//DEBUG_VALUE: __ctzsi2:r <- $r1
	//DEBUG_VALUE: __ctzsi2:x <- $r0
	.loc	2 29 13                         // uPIMulator_frontend/sdk/syslib/ctzsi2.c:29:13
	and r2, r0, 255
	.loc	2 29 29 is_stmt 0               // uPIMulator_frontend/sdk/syslib/ctzsi2.c:29:29
	jeq r2, 0, .LBB0_4
.Ltmp3:
.LBB0_5:
	//DEBUG_VALUE: __ctzsi2:r <- $r1
	//DEBUG_VALUE: __ctzsi2:t <- $r1
	//DEBUG_VALUE: __ctzsi2:x <- $r0
	.loc	2 0 29                          // uPIMulator_frontend/sdk/syslib/ctzsi2.c:0:29
	move r2, 0
.Ltmp4:
	//DEBUG_VALUE: __ctzsi2:t <- $r2
	.loc	2 30 7 is_stmt 1                // uPIMulator_frontend/sdk/syslib/ctzsi2.c:30:7
	lsr r0, r0, r2
.Ltmp5:
	//DEBUG_VALUE: __ctzsi2:x <- $r0
	.loc	2 31 7                          // uPIMulator_frontend/sdk/syslib/ctzsi2.c:31:7
	or r1, r2, r1
.Ltmp6:
	//DEBUG_VALUE: __ctzsi2:r <- $r1
	.loc	2 33 13                         // uPIMulator_frontend/sdk/syslib/ctzsi2.c:33:13
	and r2, r0, 15, z, .LBB0_7
.Ltmp7:
.LBB0_8:
	//DEBUG_VALUE: __ctzsi2:r <- $r1
	//DEBUG_VALUE: __ctzsi2:x <- $r0
	.loc	2 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/ctzsi2.c:0:13
	move r2, 0
.Ltmp8:
	//DEBUG_VALUE: __ctzsi2:t <- $r2
	.loc	2 34 7 is_stmt 1                // uPIMulator_frontend/sdk/syslib/ctzsi2.c:34:7
	lsr r0, r0, r2
.Ltmp9:
	//DEBUG_VALUE: __ctzsi2:x <- $r0
	.loc	2 35 7                          // uPIMulator_frontend/sdk/syslib/ctzsi2.c:35:7
	or r1, r1, r2
.Ltmp10:
	//DEBUG_VALUE: __ctzsi2:r <- $r1
	.loc	2 37 13                         // uPIMulator_frontend/sdk/syslib/ctzsi2.c:37:13
	and r2, r0, 3, z, .LBB0_10
.Ltmp11:
.LBB0_11:
	//DEBUG_VALUE: __ctzsi2:r <- $r1
	//DEBUG_VALUE: __ctzsi2:x <- $r0
	.loc	2 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/ctzsi2.c:0:13
	move r2, 0, true, .LBB0_12
.Ltmp12:
.LBB0_1:
	//DEBUG_VALUE: __ctzsi2:x <- $r0
	//DEBUG_VALUE: __ctzsi2:a <- $r0
	move r1, 16
.Ltmp13:
	//DEBUG_VALUE: __ctzsi2:t <- $r1
	.loc	2 26 7 is_stmt 1                // uPIMulator_frontend/sdk/syslib/ctzsi2.c:26:7
	lsr r0, r0, r1
.Ltmp14:
	//DEBUG_VALUE: __ctzsi2:r <- $r1
	//DEBUG_VALUE: __ctzsi2:x <- $r0
	.loc	2 29 13                         // uPIMulator_frontend/sdk/syslib/ctzsi2.c:29:13
	and r2, r0, 255
	.loc	2 29 29 is_stmt 0               // uPIMulator_frontend/sdk/syslib/ctzsi2.c:29:29
	jneq r2, 0, .LBB0_5
.Ltmp15:
.LBB0_4:
	//DEBUG_VALUE: __ctzsi2:r <- $r1
	//DEBUG_VALUE: __ctzsi2:t <- $r1
	//DEBUG_VALUE: __ctzsi2:x <- $r0
	.loc	2 0 29                          // uPIMulator_frontend/sdk/syslib/ctzsi2.c:0:29
	move r2, 8
.Ltmp16:
	//DEBUG_VALUE: __ctzsi2:t <- $r2
	.loc	2 30 7 is_stmt 1                // uPIMulator_frontend/sdk/syslib/ctzsi2.c:30:7
	lsr r0, r0, r2
.Ltmp17:
	//DEBUG_VALUE: __ctzsi2:x <- $r0
	.loc	2 31 7                          // uPIMulator_frontend/sdk/syslib/ctzsi2.c:31:7
	or r1, r2, r1
.Ltmp18:
	//DEBUG_VALUE: __ctzsi2:r <- $r1
	.loc	2 33 13                         // uPIMulator_frontend/sdk/syslib/ctzsi2.c:33:13
	and r2, r0, 15, nz, .LBB0_8
.Ltmp19:
.LBB0_7:
	//DEBUG_VALUE: __ctzsi2:r <- $r1
	//DEBUG_VALUE: __ctzsi2:x <- $r0
	.loc	2 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/ctzsi2.c:0:13
	move r2, 4
.Ltmp20:
	//DEBUG_VALUE: __ctzsi2:t <- $r2
	.loc	2 34 7 is_stmt 1                // uPIMulator_frontend/sdk/syslib/ctzsi2.c:34:7
	lsr r0, r0, r2
.Ltmp21:
	//DEBUG_VALUE: __ctzsi2:x <- $r0
	.loc	2 35 7                          // uPIMulator_frontend/sdk/syslib/ctzsi2.c:35:7
	or r1, r1, r2
.Ltmp22:
	//DEBUG_VALUE: __ctzsi2:r <- $r1
	.loc	2 37 13                         // uPIMulator_frontend/sdk/syslib/ctzsi2.c:37:13
	and r2, r0, 3, nz, .LBB0_11
.Ltmp23:
.LBB0_10:
	//DEBUG_VALUE: __ctzsi2:r <- $r1
	//DEBUG_VALUE: __ctzsi2:x <- $r0
	.loc	2 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/ctzsi2.c:0:13
	move r2, 2
.Ltmp24:
.LBB0_12:
	//DEBUG_VALUE: __ctzsi2:r <- $r1
	//DEBUG_VALUE: __ctzsi2:x <- $r0
	//DEBUG_VALUE: __ctzsi2:t <- $r2
	.loc	2 38 7 is_stmt 1                // uPIMulator_frontend/sdk/syslib/ctzsi2.c:38:7
	lsr r0, r0, r2
.Ltmp25:
	//DEBUG_VALUE: __ctzsi2:x <- [DW_OP_constu 2, DW_OP_and, DW_OP_stack_value] $r0
	.loc	2 40 7                          // uPIMulator_frontend/sdk/syslib/ctzsi2.c:40:7
	or r1, r1, r2
.Ltmp26:
	//DEBUG_VALUE: __ctzsi2:r <- $r1
	.loc	2 56 25                         // uPIMulator_frontend/sdk/syslib/ctzsi2.c:56:25
	lsr r2, r0, 1
.Ltmp27:
	and r2, r2, 1
	.loc	2 56 20 is_stmt 0               // uPIMulator_frontend/sdk/syslib/ctzsi2.c:56:20
	sub r2, 2, r2
	.loc	2 56 44                         // uPIMulator_frontend/sdk/syslib/ctzsi2.c:56:44
	or r0, r0, -2
.Ltmp28:
	add r0, r0, 1
	.loc	2 56 32                         // uPIMulator_frontend/sdk/syslib/ctzsi2.c:56:32
	and r0, r2, r0
	.loc	2 56 14                         // uPIMulator_frontend/sdk/syslib/ctzsi2.c:56:14
	add r0, r1, r0
	.loc	2 56 5                          // uPIMulator_frontend/sdk/syslib/ctzsi2.c:56:5
	jump r23
.Ltmp29:
.Lfunc_end0:
	.size	__ctzsi2, .Lfunc_end0-__ctzsi2
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__ctzsi2
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.__ctzsi2,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp2-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp12-.Lfunc_begin0
	.long	.Ltmp14-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp25-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp25-.Lfunc_begin0
	.long	.Ltmp28-.Lfunc_begin0
	.short	5                               // Loc expr size
	.byte	112                             // DW_OP_breg0
	.byte	0                               // 0
	.byte	50                              // DW_OP_lit2
	.byte	26                              // DW_OP_and
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Ltmp1-.Lfunc_begin0
	.long	.Ltmp4-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp4-.Lfunc_begin0
	.long	.Ltmp7-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp8-.Lfunc_begin0
	.long	.Ltmp11-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp13-.Lfunc_begin0
	.long	.Ltmp16-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp16-.Lfunc_begin0
	.long	.Ltmp19-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp20-.Lfunc_begin0
	.long	.Ltmp23-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp24-.Lfunc_begin0
	.long	.Ltmp27-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x92 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0xb DW_TAG_typedef
	.long	49                              // DW_AT_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	28                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x31:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x38:0x52 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string5                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	138                             // DW_AT_type
                                        // DW_AT_external
	.byte	5                               // Abbrev [5] 0x4d:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
	.long	138                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x5c:0xf DW_TAG_variable
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string9                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	24                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0x6b:0xf DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string10                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	25                              // DW_AT_decl_line
	.long	138                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x7a:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string11                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	27                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	2                               // Abbrev [2] 0x8a:0xb DW_TAG_typedef
	.long	149                             // DW_AT_type
	.long	.Linfo_string7                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	27                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x95:0x7 DW_TAG_base_type
	.long	.Linfo_string6                  // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/ctzsi2.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=152
.Linfo_string3:
	.asciz	"unsigned int"                  // string offset=173
.Linfo_string4:
	.asciz	"su_int"                        // string offset=186
.Linfo_string5:
	.asciz	"__ctzsi2"                      // string offset=193
.Linfo_string6:
	.asciz	"int"                           // string offset=202
.Linfo_string7:
	.asciz	"si_int"                        // string offset=206
.Linfo_string8:
	.asciz	"a"                             // string offset=213
.Linfo_string9:
	.asciz	"x"                             // string offset=215
.Linfo_string10:
	.asciz	"t"                             // string offset=217
.Linfo_string11:
	.asciz	"r"                             // string offset=219
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
