	.text
	.file	"defs.c"
	.section	.text.check_stack,"ax",@progbits
	.globl	check_stack                     // -- Begin function check_stack
	.type	check_stack,@function
check_stack:                            // @check_stack
.Lfunc_begin0:
	.file	1 "/root" "uPIMulator_frontend/sdk/syslib/defs.c"
	.loc	1 12 0                          // uPIMulator_frontend/sdk/syslib/defs.c:12:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: check_stack:tid <- undef
	.loc	1 17 36 prologue_end            // uPIMulator_frontend/sdk/syslib/defs.c:17:36
	move r0, __sys_thread_stack_table_ptr
	add r0, id8, r0
	lw r0, r0, 4
.Ltmp0:
	//DEBUG_VALUE: check_stack:stack_base <- $r0
	.loc	1 18 36                         // uPIMulator_frontend/sdk/syslib/defs.c:18:36
	lw r1, id8, __sys_thread_stack_table_ptr
.Ltmp1:
	//DEBUG_VALUE: check_stack:stack_size <- $r1
	.loc	1 19 36                         // uPIMulator_frontend/sdk/syslib/defs.c:19:36
	add r0, r1, r0
.Ltmp2:
	//DEBUG_VALUE: check_stack:stack_limit <- $r0
	.loc	1 20 5                          // uPIMulator_frontend/sdk/syslib/defs.c:20:5
	// inline asm
	sub r0, r0, r22
	// inline asm
.Ltmp3:
	//DEBUG_VALUE: check_stack:remaining <- $r0
	.loc	1 22 5                          // uPIMulator_frontend/sdk/syslib/defs.c:22:5
	jump r23
.Ltmp4:
.Lfunc_end0:
	.size	check_stack, .Lfunc_end0-check_stack
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.check_stack
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.check_stack,"ax",@progbits
                                        // -- End function
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/sysdef.h"
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp2-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Ltmp1-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp3-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x92 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	3                               // Abbrev [3] 0x2d:0x5d DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	11                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
                                        // DW_AT_external
	.byte	4                               // Abbrev [4] 0x42:0xb DW_TAG_variable
	.long	.Linfo_string5                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	15                              // DW_AT_decl_line
	.long	138                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0x4d:0xf DW_TAG_variable
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string8                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	13                              // DW_AT_decl_line
	.long	149                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0x5c:0xf DW_TAG_variable
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string9                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	13                              // DW_AT_decl_line
	.long	149                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0x6b:0xf DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string10                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	14                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	5                               // Abbrev [5] 0x7a:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string11                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	14                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	6                               // Abbrev [6] 0x8a:0xb DW_TAG_typedef
	.long	149                             // DW_AT_type
	.long	.Linfo_string7                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	18                              // DW_AT_decl_line
	.byte	2                               // Abbrev [2] 0x95:0x7 DW_TAG_base_type
	.long	.Linfo_string6                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/defs.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=150
.Linfo_string3:
	.asciz	"int"                           // string offset=171
.Linfo_string4:
	.asciz	"check_stack"                   // string offset=175
.Linfo_string5:
	.asciz	"tid"                           // string offset=187
.Linfo_string6:
	.asciz	"unsigned int"                  // string offset=191
.Linfo_string7:
	.asciz	"thread_id_t"                   // string offset=204
.Linfo_string8:
	.asciz	"stack_base"                    // string offset=216
.Linfo_string9:
	.asciz	"stack_size"                    // string offset=227
.Linfo_string10:
	.asciz	"stack_limit"                   // string offset=238
.Linfo_string11:
	.asciz	"remaining"                     // string offset=250
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
