	.text
	.file	"divdf3.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/stdint.h"
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/fp_lib.h"
	.section	.text.__divdf3,"ax",@progbits
	.globl	__divdf3                        // -- Begin function __divdf3
	.type	__divdf3,@function
__divdf3:                               // @__divdf3
.Lfunc_begin0:
	.file	3 "/root" "uPIMulator_frontend/sdk/syslib/divdf3.c"
	.loc	3 24 0                          // uPIMulator_frontend/sdk/syslib/divdf3.c:24:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __divdf3:a <- $d0
	//DEBUG_VALUE: __divdf3:a <- $d0
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: toRep:x <- $d0
	//DEBUG_VALUE: toRep:x <- $d0
	.cfi_def_cfa_offset -96
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 88, d22
	add r22, r22, 96
	.cfi_offset 15, -72
	.cfi_offset 14, -68
.Ltmp0:
	sd r22, -72, d14
	.cfi_offset 17, -80
	.cfi_offset 16, -76
	sd r22, -80, d16
	.cfi_offset 19, -88
	.cfi_offset 18, -84
	sd r22, -88, d18
	.cfi_offset 21, -96
	.cfi_offset 20, -92
	sd r22, -96, d20
	//DEBUG_VALUE: toRep:rep <- $d0
	//DEBUG_VALUE: toRep:rep <- $d0
.Ltmp1:
	.loc	3 26 45 prologue_end            // uPIMulator_frontend/sdk/syslib/divdf3.c:26:45
	lsr.u d4, r0, 20
	.loc	3 26 36 is_stmt 0               // uPIMulator_frontend/sdk/syslib/divdf3.c:26:36
	and r4, r5, 2047
.Ltmp2:
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	.loc	3 27 45 is_stmt 1               // uPIMulator_frontend/sdk/syslib/divdf3.c:27:45
	lsr.u d6, r2, 20
	.loc	3 27 36 is_stmt 0               // uPIMulator_frontend/sdk/syslib/divdf3.c:27:36
	and r5, r7, 2047
.Ltmp3:
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	.loc	3 28 42 is_stmt 1               // uPIMulator_frontend/sdk/syslib/divdf3.c:28:42
	xor r7, r3, r1
	xor r6, r2, r0
	.loc	3 28 54 is_stmt 0               // uPIMulator_frontend/sdk/syslib/divdf3.c:28:54
	and r17, r7, 0
	and r16, r6, 2147483648
.Ltmp4:
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	.loc	3 30 35 is_stmt 1               // uPIMulator_frontend/sdk/syslib/divdf3.c:30:35
	and r19, r1, 4294967295
	and r18, r0, 1048575
.Ltmp5:
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	.loc	3 31 35                         // uPIMulator_frontend/sdk/syslib/divdf3.c:31:35
	and r15, r3, 4294967295
	and r14, r2, 1048575
.Ltmp6:
	//DEBUG_VALUE: __divdf3:scale <- 0
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	.loc	3 35 19                         // uPIMulator_frontend/sdk/syslib/divdf3.c:35:19
	add r6, r4, -1
	.loc	3 35 44 is_stmt 0               // uPIMulator_frontend/sdk/syslib/divdf3.c:35:44
	lsr r6, r6, 1
	jgtu r6, 1022, .LBB0_7
.Ltmp7:
// %bb.1:
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __divdf3:a <- $d0
	//DEBUG_VALUE: __divdf3:scale <- 0
	.loc	3 0 44                          // uPIMulator_frontend/sdk/syslib/divdf3.c:0:44
	add r7, r5, -1
	move r6, 0
	.loc	3 35 44                         // uPIMulator_frontend/sdk/syslib/divdf3.c:35:44
	lsr r7, r7, 1
	jgeu r7, 1023, .LBB0_7
.Ltmp8:
// %bb.2:
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __divdf3:a <- $d0
	//DEBUG_VALUE: __divdf3:scale <- 0
	sd r22, -24, d18
	sd r22, -16, d16
.Ltmp9:
.LBB0_3:
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 24, DW_OP_minus, DW_OP_deref_size 8, DW_OP_constu 4503599627370496, DW_OP_or, DW_OP_stack_value] $r22
	//DEBUG_VALUE: __divdf3:bSignificand <- $d14
	//DEBUG_VALUE: __divdf3:scale <- $r6
	.loc	3 85 18 is_stmt 1               // uPIMulator_frontend/sdk/syslib/divdf3.c:85:18
	or r3, r15, 0
	or r2, r14, 1048576
.Ltmp10:
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370496, DW_OP_or, DW_OP_stack_value] $d14
	.loc	3 86 38                         // uPIMulator_frontend/sdk/syslib/divdf3.c:86:38
	sub r0, r4, r5
	.loc	3 86 50 is_stmt 0               // uPIMulator_frontend/sdk/syslib/divdf3.c:86:50
	add r0, r6, r0
.Ltmp11:
	//DEBUG_VALUE: __divdf3:quotientExponent <- $r0
	sw r22, -56, r0
.Ltmp12:
	//DEBUG_VALUE: __divdf3:quotientExponent <- [DW_OP_constu 56, DW_OP_minus] [$r22+0]
	.loc	3 92 40 is_stmt 1               // uPIMulator_frontend/sdk/syslib/divdf3.c:92:40
	lsrx r0, r2, 21
	lsr_add r1, r0, r3, 21
	sd r22, -64, d2
	lsr r0, r2, 21
.Ltmp13:
	//DEBUG_VALUE: __divdf3:q31b <- $r1
	.loc	3 93 45                         // uPIMulator_frontend/sdk/syslib/divdf3.c:93:45
	sub r2, 1963258675, r1
.Ltmp14:
	//DEBUG_VALUE: __divdf3:recip32 <- $r2
	.loc	3 103 22                        // uPIMulator_frontend/sdk/syslib/divdf3.c:103:22
	move.u d20, r2
	.loc	3 103 42 is_stmt 0              // uPIMulator_frontend/sdk/syslib/divdf3.c:103:42
	and r19, r1, 4294967295
	and r18, r0, 0
	.loc	3 103 40                        // uPIMulator_frontend/sdk/syslib/divdf3.c:103:40
	movd d0, d18
.Ltmp15:
	movd d2, d20
.Ltmp16:
	call r23, __muldi3
.Ltmp17:
	.loc	3 103 20                        // uPIMulator_frontend/sdk/syslib/divdf3.c:103:20
	neg r0, r0
.Ltmp18:
	//DEBUG_VALUE: __divdf3:correction32 <- $r0
	.loc	3 104 35 is_stmt 1              // uPIMulator_frontend/sdk/syslib/divdf3.c:104:35
	move.u d0, r0
.Ltmp19:
	.loc	3 104 33 is_stmt 0              // uPIMulator_frontend/sdk/syslib/divdf3.c:104:33
	movd d2, d20
	call r23, __muldi3
.Ltmp20:
	.loc	3 104 48                        // uPIMulator_frontend/sdk/syslib/divdf3.c:104:48
	lsrx r2, r0, 31
	lsr_add r3, r2, r1, 31
	lsr r2, r0, 31
.Ltmp21:
	//DEBUG_VALUE: __divdf3:recip32 <- [DW_OP_LLVM_convert 64 7, DW_OP_LLVM_convert 32 7, DW_OP_stack_value] $d2
	.loc	3 105 22 is_stmt 1              // uPIMulator_frontend/sdk/syslib/divdf3.c:105:22
	and r21, r3, 4294967295
	and r20, r2, 0
	.loc	3 105 40 is_stmt 0              // uPIMulator_frontend/sdk/syslib/divdf3.c:105:40
	movd d0, d20
	movd d2, d18
.Ltmp22:
	call r23, __muldi3
.Ltmp23:
	.loc	3 105 20                        // uPIMulator_frontend/sdk/syslib/divdf3.c:105:20
	neg r0, r0
.Ltmp24:
	//DEBUG_VALUE: __divdf3:correction32 <- $r0
	.loc	3 106 35 is_stmt 1              // uPIMulator_frontend/sdk/syslib/divdf3.c:106:35
	move.u d2, r0
	.loc	3 106 33 is_stmt 0              // uPIMulator_frontend/sdk/syslib/divdf3.c:106:33
	movd d0, d20
.Ltmp25:
	call r23, __muldi3
.Ltmp26:
	.loc	3 106 48                        // uPIMulator_frontend/sdk/syslib/divdf3.c:106:48
	lsrx r2, r0, 31
	lsr_add r3, r2, r1, 31
	lsr r2, r0, 31
.Ltmp27:
	//DEBUG_VALUE: __divdf3:recip32 <- [DW_OP_LLVM_convert 64 7, DW_OP_LLVM_convert 32 7, DW_OP_stack_value] $d2
	.loc	3 107 22 is_stmt 1              // uPIMulator_frontend/sdk/syslib/divdf3.c:107:22
	and r21, r3, 4294967295
	and r20, r2, 0
	.loc	3 107 40 is_stmt 0              // uPIMulator_frontend/sdk/syslib/divdf3.c:107:40
	movd d0, d20
	movd d2, d18
.Ltmp28:
	call r23, __muldi3
.Ltmp29:
	.loc	3 107 20                        // uPIMulator_frontend/sdk/syslib/divdf3.c:107:20
	neg r0, r0
.Ltmp30:
	//DEBUG_VALUE: __divdf3:correction32 <- $r0
	.loc	3 108 35 is_stmt 1              // uPIMulator_frontend/sdk/syslib/divdf3.c:108:35
	move.u d2, r0
	.loc	3 108 33 is_stmt 0              // uPIMulator_frontend/sdk/syslib/divdf3.c:108:33
	movd d0, d20
.Ltmp31:
	call r23, __muldi3
.Ltmp32:
	.loc	3 108 48                        // uPIMulator_frontend/sdk/syslib/divdf3.c:108:48
	lsrx r2, r0, 31
	lsr_add r3, r2, r1, 31
	lsr r2, r0, 31
.Ltmp33:
	//DEBUG_VALUE: __divdf3:recip32 <- $r3
	.loc	3 114 12 is_stmt 1              // uPIMulator_frontend/sdk/syslib/divdf3.c:114:12
	add r0, r3, -1
.Ltmp34:
	//DEBUG_VALUE: __divdf3:recip32 <- $r0
	.loc	3 118 29                        // uPIMulator_frontend/sdk/syslib/divdf3.c:118:29
	lsl r14, r15, 11
.Ltmp35:
	//DEBUG_VALUE: __divdf3:q63blo <- $r14
	.loc	3 120 20                        // uPIMulator_frontend/sdk/syslib/divdf3.c:120:20
	move.u d20, r0
	.loc	3 120 38 is_stmt 0              // uPIMulator_frontend/sdk/syslib/divdf3.c:120:38
	movd d0, d18
.Ltmp36:
	movd d2, d20
	call r23, __muldi3
.Ltmp37:
	movd d18, d0
	.loc	3 120 68                        // uPIMulator_frontend/sdk/syslib/divdf3.c:120:68
	move.u d2, r14
	.loc	3 120 66                        // uPIMulator_frontend/sdk/syslib/divdf3.c:120:66
	movd d0, d20
	call r23, __muldi3
.Ltmp38:
	.loc	3 120 75                        // uPIMulator_frontend/sdk/syslib/divdf3.c:120:75
	move.u d0, r0
	.loc	3 120 45                        // uPIMulator_frontend/sdk/syslib/divdf3.c:120:45
	add r1, r19, r1
	addc r0, r18, r0
	move.s d2, 0
	sd r22, -48, d2
	.loc	3 120 18                        // uPIMulator_frontend/sdk/syslib/divdf3.c:120:18
	sub r15, r3, r1
	subc r14, r2, r0
.Ltmp39:
	//DEBUG_VALUE: __divdf3:correction <- $d14
	.loc	3 121 31 is_stmt 1              // uPIMulator_frontend/sdk/syslib/divdf3.c:121:31
	move.u d0, r14
.Ltmp40:
	//DEBUG_VALUE: __divdf3:cLo <- [DW_OP_LLVM_convert 64 7, DW_OP_LLVM_convert 32 7, DW_OP_stack_value] $d14
	//DEBUG_VALUE: __divdf3:cHi <- [DW_OP_LLVM_convert 64 7, DW_OP_LLVM_convert 32 7, DW_OP_stack_value] $d0
	.loc	3 123 36                        // uPIMulator_frontend/sdk/syslib/divdf3.c:123:36
	movd d2, d20
	call r23, __muldi3
.Ltmp41:
	movd d18, d0
	.loc	3 123 65 is_stmt 0              // uPIMulator_frontend/sdk/syslib/divdf3.c:123:65
	and r1, r15, 4294967295
.Ltmp42:
	and r0, r14, 0
	.loc	3 123 63                        // uPIMulator_frontend/sdk/syslib/divdf3.c:123:63
	movd d2, d20
	call r23, __muldi3
.Ltmp43:
	.loc	3 123 69                        // uPIMulator_frontend/sdk/syslib/divdf3.c:123:69
	move.u d0, r0
.Ltmp44:
	//DEBUG_VALUE: __divdf3:reciprocal <- undef
	.loc	3 123 42                        // uPIMulator_frontend/sdk/syslib/divdf3.c:123:42
	add r1, r19, r1
	addc r0, r18, r0
	.loc	3 130 16 is_stmt 1              // uPIMulator_frontend/sdk/syslib/divdf3.c:130:16
	add r15, r1, 4294967294
.Ltmp45:
	addc r14, r0, 4294967295
.Ltmp46:
	//DEBUG_VALUE: __divdf3:reciprocal <- $d14
	.loc	3 0 16 is_stmt 0                // uPIMulator_frontend/sdk/syslib/divdf3.c:0:16
	ld d16, r22, -24
.Ltmp47:
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 4503599627370496, DW_OP_or, DW_OP_stack_value] $d16
	.loc	3 145 31 is_stmt 1              // uPIMulator_frontend/sdk/syslib/divdf3.c:145:31
	lslx r0, r17, 2
	lsl_add r0, r0, r16, 2
	lsl r1, r17, 2
.Ltmp48:
	//DEBUG_VALUE: wideMultiply:b <- $d14
	//DEBUG_VALUE: wideMultiply:lo <- undef
	//DEBUG_VALUE: wideMultiply:hi <- undef
	//DEBUG_VALUE: wideMultiply:a <- [DW_OP_constu 2, DW_OP_shl, DW_OP_stack_value] $d16
	.loc	2 97 28                         // uPIMulator_frontend/sdk/syslib/fp_lib.h:97:28
	and r19, r1, 4294967292
	and r18, r0, 0
	.loc	2 97 40 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_lib.h:97:40
	and r21, r15, 4294967295
	and r20, r14, 0
	.loc	2 97 38                         // uPIMulator_frontend/sdk/syslib/fp_lib.h:97:38
	movd d0, d20
	movd d2, d18
	call r23, __muldi3
.Ltmp49:
	sd r22, -40, d0
.Ltmp50:
	//DEBUG_VALUE: wideMultiply:r0 <- [DW_OP_constu 40, DW_OP_minus, DW_OP_deref_size 8, DW_OP_constu 4294967295, DW_OP_and, DW_OP_stack_value] $r22
	//DEBUG_VALUE: wideMultiply:plolo <- [DW_OP_constu 40, DW_OP_minus] [$r22+0]
	.loc	2 98 40 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_lib.h:98:40
	move.u d0, r14
	sd r22, -32, d0
	.loc	2 98 38 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_lib.h:98:38
	movd d2, d18
	call r23, __muldi3
.Ltmp51:
	movd d18, d0
.Ltmp52:
	//DEBUG_VALUE: wideMultiply:plohi <- $d18
	.loc	2 99 28 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_lib.h:99:28
	lsrx r0, r16, 30
	lsr_add r1, r0, r17, 30
	lsr r0, r16, 30
	and r1, r1, 4290772991
	and r0, r0, 0
	or r15, r1, 4194304
.Ltmp53:
	or r14, r0, 0
	.loc	2 99 38 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_lib.h:99:38
	movd d0, d20
	movd d2, d14
	call r23, __muldi3
.Ltmp54:
	movd d20, d0
.Ltmp55:
	//DEBUG_VALUE: wideMultiply:philo <- $d20
	.loc	2 100 38 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_lib.h:100:38
	ld d0, r22, -32
	movd d2, d14
	call r23, __muldi3
.Ltmp56:
	//DEBUG_VALUE: wideMultiply:phihi <- $d0
	.loc	2 103 25                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:103:25
	ld d2, r22, -40
.Ltmp57:
	//DEBUG_VALUE: wideMultiply:r0 <- [DW_OP_constu 4294967295, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: wideMultiply:plolo <- $d2
	move.u d2, r2
.Ltmp58:
	.loc	2 103 41 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_lib.h:103:41
	and r5, r19, 4294967292
.Ltmp59:
	and r4, r18, 0
.Ltmp60:
	.loc	2 103 39                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:103:39
	add r3, r3, r5
	addc r2, r2, r4
	.loc	2 103 57                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:103:57
	and r5, r21, 4294967295
	and r4, r20, 0
	.loc	2 103 55                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:103:55
	add r3, r3, r5
	addc r2, r2, r4
.Ltmp61:
	//DEBUG_VALUE: wideMultiply:r1 <- $d2
	.loc	2 106 11 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_lib.h:106:11
	move.u d4, r18
	.loc	2 106 27 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_lib.h:106:27
	move.u d6, r20
.Ltmp62:
	.loc	2 106 43                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:106:43
	move.u d2, r2
.Ltmp63:
	.loc	2 106 25                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:106:25
	add r1, r7, r1
.Ltmp64:
	addc r0, r6, r0
	.loc	2 106 41                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:106:41
	add r1, r1, r5
	addc r0, r0, r4
	.loc	2 106 54                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:106:54
	add r19, r1, r3
.Ltmp65:
	addc r18, r0, r2
.Ltmp66:
	//DEBUG_VALUE: __divdf3:quotient <- $d18
	.loc	3 161 9 is_stmt 1               // uPIMulator_frontend/sdk/syslib/divdf3.c:161:9
	lsr.u d0, r18, 21
	ld d2, r22, -48
	jneq r1, r3, .LBB0_9
.Ltmp67:
// %bb.40:
	jneq r0, r2, .LBB0_9
// %bb.41:
// %bb.4:
.Ltmp68:
	//DEBUG_VALUE: __divdf3:quotientExponent <- [DW_OP_constu 56, DW_OP_minus] [$r22+0]
	//DEBUG_VALUE: __divdf3:quotient <- $d18
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 4503599627370496, DW_OP_or, DW_OP_stack_value] $d16
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 4503599627370496, DW_OP_or, DW_OP_stack_value] $d16
	.loc	3 162 34                        // uPIMulator_frontend/sdk/syslib/divdf3.c:162:34
	move r15, 0
	lsl r14, r17, 21
.Ltmp69:
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 64, DW_OP_minus] [$r22+0]
	.loc	3 162 52 is_stmt 0              // uPIMulator_frontend/sdk/syslib/divdf3.c:162:52
	movd d0, d18
	ld d16, r22, -64
.Ltmp70:
	//DEBUG_VALUE: __divdf3:bSignificand <- $d16
	movd d2, d16
	call r23, __muldi3
.Ltmp71:
	.loc	3 162 41                        // uPIMulator_frontend/sdk/syslib/divdf3.c:162:41
	sub r1, r15, r1
	subc r0, r14, r0
.Ltmp72:
	//DEBUG_VALUE: __divdf3:residual <- $d0
	.loc	3 0 41                          // uPIMulator_frontend/sdk/syslib/divdf3.c:0:41
	lw r3, r22, -56
	.loc	3 163 25 is_stmt 1              // uPIMulator_frontend/sdk/syslib/divdf3.c:163:25
	add r3, r3, -1
.Ltmp73:
	//DEBUG_VALUE: __divdf3:quotientExponent <- $r3
	//DEBUG_VALUE: __divdf3:quotientExponent <- $r3
	//DEBUG_VALUE: __divdf3:bSignificand <- $d16
	//DEBUG_VALUE: __divdf3:quotientExponent <- $r3
	//DEBUG_VALUE: __divdf3:residual <- $d0
	//DEBUG_VALUE: __divdf3:writtenExponent <- undef
	.loc	3 0 25 is_stmt 0                // uPIMulator_frontend/sdk/syslib/divdf3.c:0:25
	move r2, 1024
.Ltmp74:
	.loc	3 171 9 is_stmt 1               // uPIMulator_frontend/sdk/syslib/divdf3.c:171:9
	jges r3, r2, .LBB0_10
.Ltmp75:
.LBB0_5:
	//DEBUG_VALUE: __divdf3:quotientExponent <- $r3
	//DEBUG_VALUE: __divdf3:quotient <- $d18
	//DEBUG_VALUE: __divdf3:bSignificand <- $d16
	//DEBUG_VALUE: __divdf3:residual <- $d0
	//DEBUG_VALUE: __divdf3:writtenExponent <- undef
	.loc	3 176 14                        // uPIMulator_frontend/sdk/syslib/divdf3.c:176:14
	jgts r3, -1023, .LBB0_13
.Ltmp76:
// %bb.6:
	//DEBUG_VALUE: __divdf3:quotientExponent <- $r3
	//DEBUG_VALUE: __divdf3:quotient <- $d18
	//DEBUG_VALUE: __divdf3:bSignificand <- $d16
	//DEBUG_VALUE: __divdf3:residual <- $d0
	//DEBUG_VALUE: fromRep:x <- [DW_OP_constu 16, DW_OP_minus] [$r22+0]
	//DEBUG_VALUE: fromRep:rep <- undef
	.loc	3 0 14 is_stmt 0                // uPIMulator_frontend/sdk/syslib/divdf3.c:0:14
	ld d16, r22, -16
.Ltmp77:
	//DEBUG_VALUE: fromRep:x <- $d16
	jump .LBB0_24
.Ltmp78:
.LBB0_7:
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __divdf3:a <- $d0
	//DEBUG_VALUE: __divdf3:scale <- 0
	.loc	3 37 37 is_stmt 1               // uPIMulator_frontend/sdk/syslib/divdf3.c:37:37
	and r7, r1, 4294967295
	and r6, r0, 2147483647
.Ltmp79:
	//DEBUG_VALUE: bAbs <- undef
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: aAbs <- $d6
	.loc	3 0 37 is_stmt 0                // uPIMulator_frontend/sdk/syslib/divdf3.c:0:37
	move r11, 1
	move r10, 2146435072
.Ltmp80:
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	.loc	3 41 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/divdf3.c:41:13
	sub zero, r7, r11
	subc zero, r6, r10, ltu, .LBB0_11
.Ltmp81:
// %bb.8:
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: aAbs <- $d6
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __divdf3:a <- $d0
	//DEBUG_VALUE: __divdf3:scale <- 0
	.loc	3 42 37                         // uPIMulator_frontend/sdk/syslib/divdf3.c:42:37
	or r17, r1, 0
.Ltmp82:
	or r16, r0, 524288
.Ltmp83:
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $d16
	.loc	3 0 37 is_stmt 0                // uPIMulator_frontend/sdk/syslib/divdf3.c:0:37
	jump .LBB0_24
.Ltmp84:
.LBB0_9:
	//DEBUG_VALUE: __divdf3:quotientExponent <- [DW_OP_constu 56, DW_OP_minus] [$r22+0]
	//DEBUG_VALUE: __divdf3:quotient <- $d18
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 4503599627370496, DW_OP_or, DW_OP_stack_value] $d16
	.loc	3 165 18 is_stmt 1              // uPIMulator_frontend/sdk/syslib/divdf3.c:165:18
	lsrx r0, r18, 1
	lsr_add r19, r0, r19, 1
.Ltmp85:
	lsr r18, r18, 1
.Ltmp86:
	//DEBUG_VALUE: __divdf3:quotient <- $d18
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 4503599627370496, DW_OP_or, DW_OP_stack_value] $d16
	.loc	3 166 34                        // uPIMulator_frontend/sdk/syslib/divdf3.c:166:34
	move r15, 0
	lsl r14, r17, 20
.Ltmp87:
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 64, DW_OP_minus] [$r22+0]
	.loc	3 166 52 is_stmt 0              // uPIMulator_frontend/sdk/syslib/divdf3.c:166:52
	movd d0, d18
	ld d16, r22, -64
.Ltmp88:
	//DEBUG_VALUE: __divdf3:bSignificand <- $d16
	movd d2, d16
	call r23, __muldi3
.Ltmp89:
	.loc	3 166 41                        // uPIMulator_frontend/sdk/syslib/divdf3.c:166:41
	sub r1, r15, r1
	subc r0, r14, r0
.Ltmp90:
	//DEBUG_VALUE: __divdf3:residual <- $d0
	//DEBUG_VALUE: __divdf3:bSignificand <- $d16
	.loc	3 0 41                          // uPIMulator_frontend/sdk/syslib/divdf3.c:0:41
	lw r3, r22, -56
.Ltmp91:
	//DEBUG_VALUE: __divdf3:quotientExponent <- $r3
	//DEBUG_VALUE: __divdf3:residual <- $d0
	//DEBUG_VALUE: __divdf3:writtenExponent <- undef
	move r2, 1024
.Ltmp92:
	.loc	3 171 9 is_stmt 1               // uPIMulator_frontend/sdk/syslib/divdf3.c:171:9
	jlts r3, r2, .LBB0_5
.Ltmp93:
.LBB0_10:
	//DEBUG_VALUE: __divdf3:quotientExponent <- $r3
	//DEBUG_VALUE: __divdf3:quotient <- $d18
	//DEBUG_VALUE: __divdf3:bSignificand <- $d16
	//DEBUG_VALUE: __divdf3:residual <- $d0
	.loc	3 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/divdf3.c:0:9
	ld d16, r22, -16
.Ltmp94:
.LBB0_23:
	or r17, r17, 0
	or r16, r16, 2146435072
.Ltmp95:
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $d16
	jump .LBB0_24
.Ltmp96:
.LBB0_11:
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: aAbs <- $d6
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __divdf3:a <- $d0
	//DEBUG_VALUE: __divdf3:scale <- 0
	and r9, r3, 4294967295
	and r8, r2, 2147483647
.Ltmp97:
	//DEBUG_VALUE: bAbs <- $d8
	.loc	3 44 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/divdf3.c:44:13
	sub zero, r9, r11
	subc zero, r8, r10, ltu, .LBB0_14
.Ltmp98:
// %bb.12:
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: bAbs <- $d8
	//DEBUG_VALUE: aAbs <- $d6
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __divdf3:a <- $d0
	//DEBUG_VALUE: __divdf3:scale <- 0
	.loc	3 45 37                         // uPIMulator_frontend/sdk/syslib/divdf3.c:45:37
	or r17, r3, 0
.Ltmp99:
	or r16, r2, 524288
.Ltmp100:
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $d16
	.loc	3 0 37 is_stmt 0                // uPIMulator_frontend/sdk/syslib/divdf3.c:0:37
	jump .LBB0_24
.Ltmp101:
.LBB0_13:
	//DEBUG_VALUE: __divdf3:quotientExponent <- $r3
	//DEBUG_VALUE: __divdf3:quotient <- $d18
	//DEBUG_VALUE: __divdf3:bSignificand <- $d16
	//DEBUG_VALUE: __divdf3:residual <- $d0
	add r2, r3, 1023
.Ltmp102:
	//DEBUG_VALUE: __divdf3:writtenExponent <- $r2
	.loc	3 183 38 is_stmt 1              // uPIMulator_frontend/sdk/syslib/divdf3.c:183:38
	lslx r3, r1, 1
.Ltmp103:
	lsl_add r4, r3, r0, 1
	lsl r5, r1, 1
	//DEBUG_VALUE: __divdf3:bSignificand <- $d16
	.loc	3 183 44 is_stmt 0              // uPIMulator_frontend/sdk/syslib/divdf3.c:183:44
	sub zero, r5, r17
	subc r0, r4, r16, xgtu
.Ltmp104:
	//DEBUG_VALUE: round <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __divdf3:quotient <- $d18
	.loc	3 185 36 is_stmt 1              // uPIMulator_frontend/sdk/syslib/divdf3.c:185:36
	and r5, r19, 4294967295
	and r4, r18, 1048575
.Ltmp105:
	//DEBUG_VALUE: absResult <- $d4
	.loc	3 187 22                        // uPIMulator_frontend/sdk/syslib/divdf3.c:187:22
	move.s d2, r2
.Ltmp106:
	.loc	3 187 45 is_stmt 0              // uPIMulator_frontend/sdk/syslib/divdf3.c:187:45
	move r7, 0
	lsl r6, r3, 20
.Ltmp107:
	//DEBUG_VALUE: absResult <- undef
	.loc	3 189 22 is_stmt 1              // uPIMulator_frontend/sdk/syslib/divdf3.c:189:22
	move.u d0, r0
.Ltmp108:
	.loc	3 187 19                        // uPIMulator_frontend/sdk/syslib/divdf3.c:187:19
	add r1, r5, r1
	addc r0, r4, r0
	.loc	3 189 19                        // uPIMulator_frontend/sdk/syslib/divdf3.c:189:19
	add r1, r1, r7
	addc r0, r0, r6
.Ltmp109:
	//DEBUG_VALUE: absResult <- $d0
	.loc	3 0 19 is_stmt 0                // uPIMulator_frontend/sdk/syslib/divdf3.c:0:19
	ld d16, r22, -16
.Ltmp110:
	.loc	3 191 49 is_stmt 1              // uPIMulator_frontend/sdk/syslib/divdf3.c:191:49
	or r17, r1, r17
	or r16, r0, r16
.Ltmp111:
	//DEBUG_VALUE: result <- undef
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $d16
	.loc	3 0 49 is_stmt 0                // uPIMulator_frontend/sdk/syslib/divdf3.c:0:49
	jump .LBB0_24
.Ltmp112:
.LBB0_14:
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: bAbs <- $d8
	//DEBUG_VALUE: aAbs <- $d6
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __divdf3:a <- $d0
	//DEBUG_VALUE: __divdf3:scale <- 0
	move r11, 0
	move r10, 2146435072
.Ltmp113:
	.loc	3 47 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/divdf3.c:47:13
	jneq r7, r11, .LBB0_17
.Ltmp114:
// %bb.42:
	jneq r6, r10, .LBB0_17
// %bb.43:
// %bb.15:
.Ltmp115:
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: bAbs <- $d8
	//DEBUG_VALUE: aAbs <- $d6
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __divdf3:a <- $d0
	//DEBUG_VALUE: __divdf3:scale <- 0
	.loc	3 49 17                         // uPIMulator_frontend/sdk/syslib/divdf3.c:49:17
	jneq r9, r11, .LBB0_23
.Ltmp116:
// %bb.44:
	jneq r8, r10, .LBB0_23
.Ltmp117:
// %bb.45:
.LBB0_16:
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: bAbs <- $d8
	//DEBUG_VALUE: aAbs <- $d6
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __divdf3:a <- $d0
	//DEBUG_VALUE: __divdf3:scale <- 0
	.loc	3 0 17 is_stmt 0                // uPIMulator_frontend/sdk/syslib/divdf3.c:0:17
	move r17, 0
.Ltmp118:
	move r16, 2146959360
	jump .LBB0_24
.Ltmp119:
.LBB0_17:
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: bAbs <- $d8
	//DEBUG_VALUE: aAbs <- $d6
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __divdf3:a <- $d0
	//DEBUG_VALUE: __divdf3:scale <- 0
	.loc	3 57 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/divdf3.c:57:13
	jneq r9, r11, .LBB0_18
.Ltmp120:
// %bb.46:
	jneq r8, r10, .LBB0_18
.Ltmp121:
// %bb.47:
.LBB0_24:
	.loc	3 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/divdf3.c:0:0
	movd d0, d16
	ld d20, r22, -96
	ld d18, r22, -88
	ld d16, r22, -80
	ld d14, r22, -72
	ld d22, r22, -8
	jump r23
.LBB0_18:
.Ltmp122:
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: bAbs <- $d8
	//DEBUG_VALUE: aAbs <- $d6
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __divdf3:a <- $d0
	//DEBUG_VALUE: __divdf3:scale <- 0
	move.s d10, 0
.Ltmp123:
	.loc	3 60 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/divdf3.c:60:13
	jneq r7, r11, .LBB0_49
.Ltmp124:
// %bb.48:
	jeq r6, r10, .LBB0_25
.LBB0_49:
// %bb.19:
.Ltmp125:
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: bAbs <- $d8
	//DEBUG_VALUE: aAbs <- $d6
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __divdf3:a <- $d0
	//DEBUG_VALUE: __divdf3:scale <- 0
	.loc	3 69 13                         // uPIMulator_frontend/sdk/syslib/divdf3.c:69:13
	jneq r9, r11, .LBB0_51
.Ltmp126:
// %bb.50:
	jeq r8, r10, .LBB0_23
.LBB0_51:
// %bb.20:
.Ltmp127:
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: bAbs <- $d8
	//DEBUG_VALUE: aAbs <- $d6
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __divdf3:a <- $d0
	//DEBUG_VALUE: __divdf3:scale <- 0
	.loc	3 75 13                         // uPIMulator_frontend/sdk/syslib/divdf3.c:75:13
	lsr.u d12, r6, 20
	move.s d10, 0
	move r6, 0
.Ltmp128:
	jneq r13, r11, .LBB0_32
.Ltmp129:
// %bb.52:
	jneq r12, r10, .LBB0_32
// %bb.53:
// %bb.21:
.Ltmp130:
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: bAbs <- $d8
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __divdf3:a <- $d0
	//DEBUG_VALUE: __divdf3:scale <- 0
	//DEBUG_VALUE: normalize:significand <- undef
	//DEBUG_VALUE: rep_clz:a <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	.loc	2 80 9                          // uPIMulator_frontend/sdk/syslib/fp_lib.h:80:9
	move.u d6, r18
	jneq r7, r11, .LBB0_27
.Ltmp131:
// %bb.54:
	jneq r6, r10, .LBB0_27
.Ltmp132:
// %bb.55:
// %bb.22:
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: bAbs <- $d8
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: rep_clz:a <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __divdf3:a <- $d0
	//DEBUG_VALUE: __divdf3:scale <- 0
	.loc	2 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_lib.h:0:9
	clz r0, r1
.Ltmp133:
	or r0, r0, 32, true, .LBB0_28
.Ltmp134:
.LBB0_25:
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: bAbs <- $d8
	//DEBUG_VALUE: aAbs <- $d6
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __divdf3:a <- $d0
	//DEBUG_VALUE: __divdf3:scale <- 0
	jneq r9, r11, .LBB0_24
.Ltmp135:
// %bb.56:
	jneq r8, r10, .LBB0_24
// %bb.57:
	jump .LBB0_16
.LBB0_27:
.Ltmp136:
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: bAbs <- $d8
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: rep_clz:a <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __divdf3:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __divdf3:a <- $d0
	//DEBUG_VALUE: __divdf3:scale <- 0
	clz r0, r18
.Ltmp137:
.LBB0_28:
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: bAbs <- $d8
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: __divdf3:scale <- 0
	//DEBUG_VALUE: rep_clz:a <- 4503599627370496
	.loc	2 251 45 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_lib.h:251:45
	add r1, r0, -11
.Ltmp138:
	//DEBUG_VALUE: normalize:shift <- $r1
	.loc	2 252 18                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:252:18
	lslx r6, r19, r1, sh32, .LBB0_30
.Ltmp139:
// %bb.29:
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: normalize:shift <- $r1
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: bAbs <- $d8
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: __divdf3:scale <- 0
	lsl r7, r18, r1
	or r18, r7, r6
	lsl r19, r19, r1, true, .LBB0_31
.Ltmp140:
.LBB0_30:
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: normalize:shift <- $r1
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: bAbs <- $d8
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: __divdf3:scale <- 0
	lsl r18, r19, r1
	move r19, 0
.Ltmp141:
.LBB0_31:
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: normalize:shift <- $r1
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: bAbs <- $d8
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: __divdf3:scale <- 0
	.loc	2 253 14                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:253:14
	sub r6, 12, r0
.Ltmp142:
	//DEBUG_VALUE: __divdf3:scale <- $r6
.LBB0_32:
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: bAbs <- $d8
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: __divdf3:scale <- $r6
	.loc	3 77 13                         // uPIMulator_frontend/sdk/syslib/divdf3.c:77:13
	lsr.u d0, r8, 20
	sd r22, -16, d16
	sd r22, -24, d18
	jneq r1, r11, .LBB0_3
.Ltmp143:
// %bb.58:
	jneq r0, r10, .LBB0_3
// %bb.59:
// %bb.33:
.Ltmp144:
	//DEBUG_VALUE: __divdf3:scale <- $r6
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: bAbs <- $d8
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: normalize:significand <- undef
	//DEBUG_VALUE: rep_clz:a <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	.loc	2 80 9                          // uPIMulator_frontend/sdk/syslib/fp_lib.h:80:9
	move.u d0, r14
	move.s d8, 0
.Ltmp145:
	jneq r1, r9, .LBB0_35
.Ltmp146:
// %bb.60:
	jneq r0, r8, .LBB0_35
.Ltmp147:
// %bb.61:
// %bb.34:
	//DEBUG_VALUE: __divdf3:scale <- $r6
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: rep_clz:a <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	.loc	2 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_lib.h:0:9
	clz r0, r3
	or r0, r0, 32, true, .LBB0_36
.Ltmp148:
.LBB0_35:
	//DEBUG_VALUE: __divdf3:scale <- $r6
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: rep_clz:a <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	clz r0, r14
.Ltmp149:
.LBB0_36:
	//DEBUG_VALUE: __divdf3:scale <- $r6
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	//DEBUG_VALUE: __divdf3:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __divdf3:b <- $d2
	//DEBUG_VALUE: rep_clz:a <- 4503599627370496
	.loc	2 251 45 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_lib.h:251:45
	add r1, r0, -11
.Ltmp150:
	//DEBUG_VALUE: normalize:shift <- $r1
	.loc	2 252 18                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:252:18
	lslx r2, r15, r1, sh32, .LBB0_38
.Ltmp151:
// %bb.37:
	//DEBUG_VALUE: __divdf3:scale <- $r6
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: normalize:shift <- $r1
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	lsl r3, r14, r1
	or r14, r3, r2
	lsl r15, r15, r1, true, .LBB0_39
.Ltmp152:
.LBB0_38:
	//DEBUG_VALUE: __divdf3:scale <- $r6
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: normalize:shift <- $r1
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	lsl r14, r15, r1
	move r15, 0
.Ltmp153:
.LBB0_39:
	//DEBUG_VALUE: __divdf3:scale <- $r6
	//DEBUG_VALUE: __divdf3:bExponent <- $r5
	//DEBUG_VALUE: __divdf3:aExponent <- $r4
	//DEBUG_VALUE: normalize:shift <- $r1
	//DEBUG_VALUE: __divdf3:quotientSign <- $d16
	.loc	2 253 14                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:253:14
	add r0, r0, r6
.Ltmp154:
	//DEBUG_VALUE: __divdf3:scale <- $r6
	.loc	3 78 19                         // uPIMulator_frontend/sdk/syslib/divdf3.c:78:19
	add r6, r0, -12, true, .LBB0_3
.Ltmp155:
.Lfunc_end0:
	.size	__divdf3, .Lfunc_end0-__divdf3
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__divdf3
	.long	.Lfunc_begin0
	.byte	96
	.section	.text.__divdf3,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp9-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp78-.Lfunc_begin0
	.long	.Ltmp84-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp96-.Lfunc_begin0
	.long	.Ltmp101-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp112-.Lfunc_begin0
	.long	.Ltmp114-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp115-.Lfunc_begin0
	.long	.Ltmp116-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp117-.Lfunc_begin0
	.long	.Ltmp120-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp122-.Lfunc_begin0
	.long	.Ltmp124-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp125-.Lfunc_begin0
	.long	.Ltmp126-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp127-.Lfunc_begin0
	.long	.Ltmp129-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp130-.Lfunc_begin0
	.long	.Ltmp131-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp132-.Lfunc_begin0
	.long	.Ltmp133-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp134-.Lfunc_begin0
	.long	.Ltmp135-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp136-.Lfunc_begin0
	.long	.Ltmp137-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp9-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp78-.Lfunc_begin0
	.long	.Ltmp84-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp96-.Lfunc_begin0
	.long	.Ltmp101-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp112-.Lfunc_begin0
	.long	.Ltmp114-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp115-.Lfunc_begin0
	.long	.Ltmp116-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp117-.Lfunc_begin0
	.long	.Ltmp120-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp122-.Lfunc_begin0
	.long	.Ltmp124-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp125-.Lfunc_begin0
	.long	.Ltmp126-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp127-.Lfunc_begin0
	.long	.Ltmp129-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp130-.Lfunc_begin0
	.long	.Ltmp131-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp132-.Lfunc_begin0
	.long	.Ltmp135-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp136-.Lfunc_begin0
	.long	.Ltmp143-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp144-.Lfunc_begin0
	.long	.Ltmp146-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp147-.Lfunc_begin0
	.long	.Ltmp151-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp60-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp78-.Lfunc_begin0
	.long	.Ltmp84-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp96-.Lfunc_begin0
	.long	.Ltmp101-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp112-.Lfunc_begin0
	.long	.Ltmp114-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp115-.Lfunc_begin0
	.long	.Ltmp116-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp117-.Lfunc_begin0
	.long	.Ltmp120-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp122-.Lfunc_begin0
	.long	.Ltmp124-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp125-.Lfunc_begin0
	.long	.Ltmp126-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp127-.Lfunc_begin0
	.long	.Ltmp129-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp130-.Lfunc_begin0
	.long	.Ltmp131-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp132-.Lfunc_begin0
	.long	.Ltmp135-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp136-.Lfunc_begin0
	.long	.Ltmp143-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp144-.Lfunc_begin0
	.long	.Ltmp146-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp147-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp59-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp78-.Lfunc_begin0
	.long	.Ltmp84-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp96-.Lfunc_begin0
	.long	.Ltmp101-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp112-.Lfunc_begin0
	.long	.Ltmp114-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp115-.Lfunc_begin0
	.long	.Ltmp116-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp117-.Lfunc_begin0
	.long	.Ltmp120-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp122-.Lfunc_begin0
	.long	.Ltmp124-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp125-.Lfunc_begin0
	.long	.Ltmp126-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp127-.Lfunc_begin0
	.long	.Ltmp129-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp130-.Lfunc_begin0
	.long	.Ltmp131-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp132-.Lfunc_begin0
	.long	.Ltmp135-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp136-.Lfunc_begin0
	.long	.Ltmp143-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp144-.Lfunc_begin0
	.long	.Ltmp146-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp147-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	0
	.long	0
.Ldebug_loc4:
	.long	.Ltmp4-.Lfunc_begin0
	.long	.Ltmp47-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	97                              // sub-register DW_OP_reg17
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	96                              // sub-register DW_OP_reg16
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp78-.Lfunc_begin0
	.long	.Ltmp82-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	97                              // sub-register DW_OP_reg17
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	96                              // sub-register DW_OP_reg16
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp96-.Lfunc_begin0
	.long	.Ltmp99-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	97                              // sub-register DW_OP_reg17
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	96                              // sub-register DW_OP_reg16
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp112-.Lfunc_begin0
	.long	.Ltmp114-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	97                              // sub-register DW_OP_reg17
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	96                              // sub-register DW_OP_reg16
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp115-.Lfunc_begin0
	.long	.Ltmp116-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	97                              // sub-register DW_OP_reg17
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	96                              // sub-register DW_OP_reg16
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp117-.Lfunc_begin0
	.long	.Ltmp118-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	97                              // sub-register DW_OP_reg17
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	96                              // sub-register DW_OP_reg16
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp119-.Lfunc_begin0
	.long	.Ltmp120-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	97                              // sub-register DW_OP_reg17
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	96                              // sub-register DW_OP_reg16
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp122-.Lfunc_begin0
	.long	.Ltmp124-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	97                              // sub-register DW_OP_reg17
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	96                              // sub-register DW_OP_reg16
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp125-.Lfunc_begin0
	.long	.Ltmp126-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	97                              // sub-register DW_OP_reg17
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	96                              // sub-register DW_OP_reg16
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp127-.Lfunc_begin0
	.long	.Ltmp129-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	97                              // sub-register DW_OP_reg17
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	96                              // sub-register DW_OP_reg16
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp130-.Lfunc_begin0
	.long	.Ltmp131-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	97                              // sub-register DW_OP_reg17
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	96                              // sub-register DW_OP_reg16
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp132-.Lfunc_begin0
	.long	.Ltmp135-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	97                              // sub-register DW_OP_reg17
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	96                              // sub-register DW_OP_reg16
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp136-.Lfunc_begin0
	.long	.Ltmp143-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	97                              // sub-register DW_OP_reg17
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	96                              // sub-register DW_OP_reg16
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp144-.Lfunc_begin0
	.long	.Ltmp146-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	97                              // sub-register DW_OP_reg17
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	96                              // sub-register DW_OP_reg16
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp147-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	97                              // sub-register DW_OP_reg17
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	96                              // sub-register DW_OP_reg16
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc5:
	.long	.Ltmp9-.Lfunc_begin0
	.long	.Ltmp47-.Lfunc_begin0
	.short	15                              // Loc expr size
	.byte	134                             // DW_OP_breg22
	.byte	104                             // -24
	.byte	148                             // DW_OP_deref_size
	.byte	8                               // 
	.byte	16                              // DW_OP_constu
	.byte	128                             // 4503599627370496
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	8                               // 
	.byte	33                              // DW_OP_or
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc6:
	.long	.Ltmp6-.Lfunc_begin0
	.long	.Ltmp9-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp9-.Lfunc_begin0
	.long	.Ltmp62-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	86                              // DW_OP_reg6
	.long	.Ltmp78-.Lfunc_begin0
	.long	.Ltmp84-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp96-.Lfunc_begin0
	.long	.Ltmp101-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp112-.Lfunc_begin0
	.long	.Ltmp114-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp115-.Lfunc_begin0
	.long	.Ltmp116-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp117-.Lfunc_begin0
	.long	.Ltmp120-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp122-.Lfunc_begin0
	.long	.Ltmp124-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp125-.Lfunc_begin0
	.long	.Ltmp126-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp127-.Lfunc_begin0
	.long	.Ltmp129-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp130-.Lfunc_begin0
	.long	.Ltmp131-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp132-.Lfunc_begin0
	.long	.Ltmp135-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp136-.Lfunc_begin0
	.long	.Ltmp142-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp142-.Lfunc_begin0
	.long	.Ltmp143-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	86                              // DW_OP_reg6
	.long	.Ltmp144-.Lfunc_begin0
	.long	.Ltmp146-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	86                              // DW_OP_reg6
	.long	.Ltmp147-.Lfunc_begin0
	.long	.Ltmp155-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	86                              // DW_OP_reg6
	.long	0
	.long	0
.Ldebug_loc7:
	.long	.Ltmp9-.Lfunc_begin0
	.long	.Ltmp10-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	95                              // sub-register DW_OP_reg15
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	94                              // sub-register DW_OP_reg14
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp69-.Lfunc_begin0
	.long	.Ltmp70-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	134                             // DW_OP_breg22
	.byte	64                              // -64
	.long	.Ltmp70-.Lfunc_begin0
	.long	.Ltmp77-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	97                              // sub-register DW_OP_reg17
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	96                              // sub-register DW_OP_reg16
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp87-.Lfunc_begin0
	.long	.Ltmp88-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	134                             // DW_OP_breg22
	.byte	64                              // -64
	.long	.Ltmp88-.Lfunc_begin0
	.long	.Ltmp94-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	97                              // sub-register DW_OP_reg17
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	96                              // sub-register DW_OP_reg16
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp101-.Lfunc_begin0
	.long	.Ltmp110-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	97                              // sub-register DW_OP_reg17
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	96                              // sub-register DW_OP_reg16
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc8:
	.long	.Ltmp11-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp12-.Lfunc_begin0
	.long	.Ltmp67-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	134                             // DW_OP_breg22
	.byte	72                              // -56
	.long	.Ltmp68-.Lfunc_begin0
	.long	.Ltmp73-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	134                             // DW_OP_breg22
	.byte	72                              // -56
	.long	.Ltmp73-.Lfunc_begin0
	.long	.Ltmp78-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp84-.Lfunc_begin0
	.long	.Ltmp91-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	134                             // DW_OP_breg22
	.byte	72                              // -56
	.long	.Ltmp91-.Lfunc_begin0
	.long	.Ltmp94-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp101-.Lfunc_begin0
	.long	.Ltmp103-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc9:
	.long	.Ltmp13-.Lfunc_begin0
	.long	.Ltmp15-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc10:
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Ltmp16-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp33-.Lfunc_begin0
	.long	.Ltmp34-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp34-.Lfunc_begin0
	.long	.Ltmp36-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc11:
	.long	.Ltmp18-.Lfunc_begin0
	.long	.Ltmp19-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp24-.Lfunc_begin0
	.long	.Ltmp25-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp30-.Lfunc_begin0
	.long	.Ltmp31-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc12:
	.long	.Ltmp35-.Lfunc_begin0
	.long	.Ltmp39-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	0
	.long	0
.Ldebug_loc13:
	.long	.Ltmp39-.Lfunc_begin0
	.long	.Ltmp45-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	95                              // sub-register DW_OP_reg15
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	94                              // sub-register DW_OP_reg14
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc14:
	.long	.Ltmp46-.Lfunc_begin0
	.long	.Ltmp53-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	95                              // sub-register DW_OP_reg15
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	94                              // sub-register DW_OP_reg14
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc15:
	.long	.Ltmp48-.Lfunc_begin0
	.long	.Ltmp53-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	95                              // sub-register DW_OP_reg15
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	94                              // sub-register DW_OP_reg14
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc16:
	.long	.Ltmp50-.Lfunc_begin0
	.long	.Ltmp57-.Lfunc_begin0
	.short	12                              // Loc expr size
	.byte	134                             // DW_OP_breg22
	.byte	88                              // -40
	.byte	148                             // DW_OP_deref_size
	.byte	8                               // 
	.byte	16                              // DW_OP_constu
	.byte	255                             // 4294967295
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	15                              // 
	.byte	26                              // DW_OP_and
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc17:
	.long	.Ltmp50-.Lfunc_begin0
	.long	.Ltmp57-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	134                             // DW_OP_breg22
	.byte	88                              // -40
	.long	.Ltmp57-.Lfunc_begin0
	.long	.Ltmp58-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc18:
	.long	.Ltmp52-.Lfunc_begin0
	.long	.Ltmp65-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	99                              // sub-register DW_OP_reg19
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	98                              // sub-register DW_OP_reg18
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc19:
	.long	.Ltmp55-.Lfunc_begin0
	.long	.Ltmp67-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	101                             // sub-register DW_OP_reg21
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	100                             // sub-register DW_OP_reg20
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc20:
	.long	.Ltmp56-.Lfunc_begin0
	.long	.Ltmp64-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc21:
	.long	.Ltmp61-.Lfunc_begin0
	.long	.Ltmp63-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc22:
	.long	.Ltmp66-.Lfunc_begin0
	.long	.Ltmp67-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	99                              // sub-register DW_OP_reg19
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	98                              // sub-register DW_OP_reg18
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp68-.Lfunc_begin0
	.long	.Ltmp78-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	99                              // sub-register DW_OP_reg19
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	98                              // sub-register DW_OP_reg18
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp84-.Lfunc_begin0
	.long	.Ltmp85-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	99                              // sub-register DW_OP_reg19
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	98                              // sub-register DW_OP_reg18
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp86-.Lfunc_begin0
	.long	.Ltmp94-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	99                              // sub-register DW_OP_reg19
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	98                              // sub-register DW_OP_reg18
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp101-.Lfunc_begin0
	.long	.Ltmp112-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	99                              // sub-register DW_OP_reg19
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	98                              // sub-register DW_OP_reg18
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc23:
	.long	.Ltmp72-.Lfunc_begin0
	.long	.Ltmp78-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp90-.Lfunc_begin0
	.long	.Ltmp94-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp101-.Lfunc_begin0
	.long	.Ltmp104-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc24:
	.long	.Ltmp102-.Lfunc_begin0
	.long	.Ltmp106-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc25:
	.long	.Ltmp97-.Lfunc_begin0
	.long	.Ltmp101-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	89                              // sub-register DW_OP_reg9
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	88                              // sub-register DW_OP_reg8
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp112-.Lfunc_begin0
	.long	.Ltmp114-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	89                              // sub-register DW_OP_reg9
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	88                              // sub-register DW_OP_reg8
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp115-.Lfunc_begin0
	.long	.Ltmp116-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	89                              // sub-register DW_OP_reg9
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	88                              // sub-register DW_OP_reg8
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp117-.Lfunc_begin0
	.long	.Ltmp120-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	89                              // sub-register DW_OP_reg9
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	88                              // sub-register DW_OP_reg8
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp122-.Lfunc_begin0
	.long	.Ltmp124-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	89                              // sub-register DW_OP_reg9
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	88                              // sub-register DW_OP_reg8
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp125-.Lfunc_begin0
	.long	.Ltmp126-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	89                              // sub-register DW_OP_reg9
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	88                              // sub-register DW_OP_reg8
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp127-.Lfunc_begin0
	.long	.Ltmp129-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	89                              // sub-register DW_OP_reg9
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	88                              // sub-register DW_OP_reg8
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp130-.Lfunc_begin0
	.long	.Ltmp131-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	89                              // sub-register DW_OP_reg9
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	88                              // sub-register DW_OP_reg8
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp132-.Lfunc_begin0
	.long	.Ltmp135-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	89                              // sub-register DW_OP_reg9
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	88                              // sub-register DW_OP_reg8
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp136-.Lfunc_begin0
	.long	.Ltmp143-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	89                              // sub-register DW_OP_reg9
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	88                              // sub-register DW_OP_reg8
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp144-.Lfunc_begin0
	.long	.Ltmp145-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	89                              // sub-register DW_OP_reg9
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	88                              // sub-register DW_OP_reg8
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc26:
	.long	.Ltmp79-.Lfunc_begin0
	.long	.Ltmp84-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp96-.Lfunc_begin0
	.long	.Ltmp101-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp112-.Lfunc_begin0
	.long	.Ltmp114-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp115-.Lfunc_begin0
	.long	.Ltmp116-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp117-.Lfunc_begin0
	.long	.Ltmp120-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp122-.Lfunc_begin0
	.long	.Ltmp124-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp125-.Lfunc_begin0
	.long	.Ltmp126-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp127-.Lfunc_begin0
	.long	.Ltmp128-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp134-.Lfunc_begin0
	.long	.Ltmp135-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc27:
	.long	.Ltmp104-.Lfunc_begin0
	.long	.Ltmp108-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	112                             // DW_OP_breg0
	.byte	0                               // 0
	.byte	16                              // DW_OP_constu
	.byte	1                               // 1
	.byte	26                              // DW_OP_and
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc28:
	.long	.Ltmp105-.Lfunc_begin0
	.long	.Ltmp107-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp109-.Lfunc_begin0
	.long	.Ltmp112-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc29:
	.long	.Ltmp138-.Lfunc_begin0
	.long	.Ltmp142-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc30:
	.long	.Ltmp150-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	23                              // DW_TAG_union_type
	.byte	1                               // DW_CHILDREN_yes
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	13                              // DW_TAG_member
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	56                              // DW_AT_data_member_location
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	11                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	12                              // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	13                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	14                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	15                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	16                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	1                               // DW_CHILDREN_yes
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	17                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	18                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	19                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	20                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	21                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	22                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	23                              // Abbreviation Code
	.ascii	"\211\202\001"                  // DW_TAG_GNU_call_site
	.byte	0                               // DW_CHILDREN_no
	.ascii	"\223B"                         // DW_AT_GNU_call_site_target
	.byte	24                              // DW_FORM_exprloc
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x47e DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0xb DW_TAG_typedef
	.long	49                              // DW_AT_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	53                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x31:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	2                               // Abbrev [2] 0x38:0xb DW_TAG_typedef
	.long	38                              // DW_AT_type
	.long	.Linfo_string5                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	68                              // DW_AT_decl_line
	.byte	4                               // Abbrev [4] 0x43:0x23 DW_TAG_subprogram
	.long	.Linfo_string6                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	229                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	56                              // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0x4f:0xb DW_TAG_formal_parameter
	.long	.Linfo_string7                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	229                             // DW_AT_decl_line
	.long	102                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x5a:0xb DW_TAG_variable
	.long	.Linfo_string10                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	234                             // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	2                               // Abbrev [2] 0x66:0xb DW_TAG_typedef
	.long	113                             // DW_AT_type
	.long	.Linfo_string9                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	70                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x71:0x7 DW_TAG_base_type
	.long	.Linfo_string8                  // DW_AT_name
	.byte	4                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	7                               // Abbrev [7] 0x78:0x5 DW_TAG_const_type
	.long	126                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x7d:0x1f DW_TAG_subprogram
	.byte	9                               // Abbrev [9] 0x7e:0x1d DW_TAG_union_type
	.byte	8                               // DW_AT_byte_size
	.byte	2                               // DW_AT_decl_file
	.byte	231                             // DW_AT_decl_line
	.byte	10                              // Abbrev [10] 0x82:0xc DW_TAG_member
	.long	.Linfo_string11                 // DW_AT_name
	.long	102                             // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	232                             // DW_AT_decl_line
	.byte	0                               // DW_AT_data_member_location
	.byte	10                              // Abbrev [10] 0x8e:0xc DW_TAG_member
	.long	.Linfo_string12                 // DW_AT_name
	.long	56                              // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	233                             // DW_AT_decl_line
	.byte	0                               // DW_AT_data_member_location
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	11                              // Abbrev [11] 0x9c:0x77 DW_TAG_subprogram
	.long	.Linfo_string13                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	94                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0xa4:0xb DW_TAG_formal_parameter
	.long	.Linfo_string14                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	94                              // DW_AT_decl_line
	.long	56                              // DW_AT_type
	.byte	5                               // Abbrev [5] 0xaf:0xb DW_TAG_formal_parameter
	.long	.Linfo_string15                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	94                              // DW_AT_decl_line
	.long	56                              // DW_AT_type
	.byte	5                               // Abbrev [5] 0xba:0xb DW_TAG_formal_parameter
	.long	.Linfo_string16                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	94                              // DW_AT_decl_line
	.long	275                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0xc5:0xb DW_TAG_formal_parameter
	.long	.Linfo_string17                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	94                              // DW_AT_decl_line
	.long	275                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xd0:0xb DW_TAG_variable
	.long	.Linfo_string18                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	102                             // DW_AT_decl_line
	.long	280                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xdb:0xb DW_TAG_variable
	.long	.Linfo_string19                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	97                              // DW_AT_decl_line
	.long	280                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xe6:0xb DW_TAG_variable
	.long	.Linfo_string20                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	98                              // DW_AT_decl_line
	.long	280                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xf1:0xb DW_TAG_variable
	.long	.Linfo_string21                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	99                              // DW_AT_decl_line
	.long	280                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xfc:0xb DW_TAG_variable
	.long	.Linfo_string22                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	100                             // DW_AT_decl_line
	.long	280                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x107:0xb DW_TAG_variable
	.long	.Linfo_string23                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	103                             // DW_AT_decl_line
	.long	280                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	12                              // Abbrev [12] 0x113:0x5 DW_TAG_pointer_type
	.long	56                              // DW_AT_type
	.byte	7                               // Abbrev [7] 0x118:0x5 DW_TAG_const_type
	.long	38                              // DW_AT_type
	.byte	4                               // Abbrev [4] 0x11d:0x18 DW_TAG_subprogram
	.long	.Linfo_string24                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	75                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	309                             // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0x129:0xb DW_TAG_formal_parameter
	.long	.Linfo_string14                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	75                              // DW_AT_decl_line
	.long	56                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	3                               // Abbrev [3] 0x135:0x7 DW_TAG_base_type
	.long	.Linfo_string25                 // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x13c:0x23 DW_TAG_subprogram
	.long	.Linfo_string26                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	249                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	309                             // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0x148:0xb DW_TAG_formal_parameter
	.long	.Linfo_string27                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	249                             // DW_AT_decl_line
	.long	275                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x153:0xb DW_TAG_variable
	.long	.Linfo_string28                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	251                             // DW_AT_decl_line
	.long	351                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x15f:0x5 DW_TAG_const_type
	.long	309                             // DW_AT_type
	.byte	13                              // Abbrev [13] 0x164:0x2f2 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string29                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	23                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	102                             // DW_AT_type
                                        // DW_AT_external
	.byte	14                              // Abbrev [14] 0x179:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string14                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	23                              // DW_AT_decl_line
	.long	102                             // DW_AT_type
	.byte	14                              // Abbrev [14] 0x188:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string15                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	23                              // DW_AT_decl_line
	.long	102                             // DW_AT_type
	.byte	15                              // Abbrev [15] 0x197:0xf DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string30                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	26                              // DW_AT_decl_line
	.long	1110                            // DW_AT_type
	.byte	15                              // Abbrev [15] 0x1a6:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string32                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	27                              // DW_AT_decl_line
	.long	1110                            // DW_AT_type
	.byte	15                              // Abbrev [15] 0x1b5:0xf DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	.Linfo_string33                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	28                              // DW_AT_decl_line
	.long	1122                            // DW_AT_type
	.byte	15                              // Abbrev [15] 0x1c4:0xf DW_TAG_variable
	.long	.Ldebug_loc5                    // DW_AT_location
	.long	.Linfo_string34                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	30                              // DW_AT_decl_line
	.long	56                              // DW_AT_type
	.byte	15                              // Abbrev [15] 0x1d3:0xf DW_TAG_variable
	.long	.Ldebug_loc6                    // DW_AT_location
	.long	.Linfo_string35                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	32                              // DW_AT_decl_line
	.long	309                             // DW_AT_type
	.byte	15                              // Abbrev [15] 0x1e2:0xf DW_TAG_variable
	.long	.Ldebug_loc7                    // DW_AT_location
	.long	.Linfo_string36                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	31                              // DW_AT_decl_line
	.long	56                              // DW_AT_type
	.byte	15                              // Abbrev [15] 0x1f1:0xf DW_TAG_variable
	.long	.Ldebug_loc8                    // DW_AT_location
	.long	.Linfo_string37                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	86                              // DW_AT_decl_line
	.long	309                             // DW_AT_type
	.byte	15                              // Abbrev [15] 0x200:0xf DW_TAG_variable
	.long	.Ldebug_loc9                    // DW_AT_location
	.long	.Linfo_string38                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	92                              // DW_AT_decl_line
	.long	1127                            // DW_AT_type
	.byte	15                              // Abbrev [15] 0x20f:0xf DW_TAG_variable
	.long	.Ldebug_loc10                   // DW_AT_location
	.long	.Linfo_string40                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	93                              // DW_AT_decl_line
	.long	1132                            // DW_AT_type
	.byte	15                              // Abbrev [15] 0x21e:0xf DW_TAG_variable
	.long	.Ldebug_loc11                   // DW_AT_location
	.long	.Linfo_string41                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	102                             // DW_AT_decl_line
	.long	1132                            // DW_AT_type
	.byte	15                              // Abbrev [15] 0x22d:0xf DW_TAG_variable
	.long	.Ldebug_loc12                   // DW_AT_location
	.long	.Linfo_string42                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	118                             // DW_AT_decl_line
	.long	1127                            // DW_AT_type
	.byte	15                              // Abbrev [15] 0x23c:0xf DW_TAG_variable
	.long	.Ldebug_loc13                   // DW_AT_location
	.long	.Linfo_string43                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	119                             // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0x24b:0xb DW_TAG_variable
	.long	.Linfo_string44                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	122                             // DW_AT_decl_line
	.long	1132                            // DW_AT_type
	.byte	6                               // Abbrev [6] 0x256:0xb DW_TAG_variable
	.long	.Linfo_string45                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	121                             // DW_AT_decl_line
	.long	1132                            // DW_AT_type
	.byte	15                              // Abbrev [15] 0x261:0xf DW_TAG_variable
	.long	.Ldebug_loc14                   // DW_AT_location
	.long	.Linfo_string46                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	119                             // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	15                              // Abbrev [15] 0x270:0xf DW_TAG_variable
	.long	.Ldebug_loc22                   // DW_AT_location
	.long	.Linfo_string47                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	144                             // DW_AT_decl_line
	.long	56                              // DW_AT_type
	.byte	15                              // Abbrev [15] 0x27f:0xf DW_TAG_variable
	.long	.Ldebug_loc23                   // DW_AT_location
	.long	.Linfo_string48                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	160                             // DW_AT_decl_line
	.long	56                              // DW_AT_type
	.byte	15                              // Abbrev [15] 0x28e:0xf DW_TAG_variable
	.long	.Ldebug_loc24                   // DW_AT_location
	.long	.Linfo_string49                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	169                             // DW_AT_decl_line
	.long	351                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x29d:0xb DW_TAG_variable
	.long	.Linfo_string56                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	144                             // DW_AT_decl_line
	.long	56                              // DW_AT_type
	.byte	16                              // Abbrev [16] 0x2a8:0x1d DW_TAG_inlined_subroutine
	.long	67                              // DW_AT_abstract_origin
	.long	.Ltmp0                          // DW_AT_low_pc
	.long	.Ltmp1-.Ltmp0                   // DW_AT_high_pc
	.byte	3                               // DW_AT_call_file
	.byte	26                              // DW_AT_call_line
	.byte	36                              // DW_AT_call_column
	.byte	17                              // Abbrev [17] 0x2b8:0xc DW_TAG_formal_parameter
	.byte	6                               // DW_AT_location
	.byte	81
	.byte	147
	.byte	4
	.byte	80
	.byte	147
	.byte	4
	.long	79                              // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	18                              // Abbrev [18] 0x2c5:0x8e DW_TAG_lexical_block
	.long	.Ldebug_ranges0                 // DW_AT_ranges
	.byte	15                              // Abbrev [15] 0x2ca:0xf DW_TAG_variable
	.long	.Ldebug_loc25                   // DW_AT_location
	.long	.Linfo_string50                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	38                              // DW_AT_decl_line
	.long	1122                            // DW_AT_type
	.byte	15                              // Abbrev [15] 0x2d9:0xf DW_TAG_variable
	.long	.Ldebug_loc26                   // DW_AT_location
	.long	.Linfo_string51                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	37                              // DW_AT_decl_line
	.long	1122                            // DW_AT_type
	.byte	16                              // Abbrev [16] 0x2e8:0x35 DW_TAG_inlined_subroutine
	.long	316                             // DW_AT_abstract_origin
	.long	.Ltmp130                        // DW_AT_low_pc
	.long	.Ltmp142-.Ltmp130               // DW_AT_high_pc
	.byte	3                               // DW_AT_call_file
	.byte	76                              // DW_AT_call_line
	.byte	22                              // DW_AT_call_column
	.byte	19                              // Abbrev [19] 0x2f8:0x5 DW_TAG_formal_parameter
	.long	328                             // DW_AT_abstract_origin
	.byte	20                              // Abbrev [20] 0x2fd:0x9 DW_TAG_variable
	.long	.Ldebug_loc29                   // DW_AT_location
	.long	339                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x306:0x16 DW_TAG_inlined_subroutine
	.long	285                             // DW_AT_abstract_origin
	.long	.Ltmp130                        // DW_AT_low_pc
	.long	.Ltmp132-.Ltmp130               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	251                             // DW_AT_call_line
	.byte	23                              // DW_AT_call_column
	.byte	19                              // Abbrev [19] 0x316:0x5 DW_TAG_formal_parameter
	.long	297                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	16                              // Abbrev [16] 0x31d:0x35 DW_TAG_inlined_subroutine
	.long	316                             // DW_AT_abstract_origin
	.long	.Ltmp144                        // DW_AT_low_pc
	.long	.Ltmp154-.Ltmp144               // DW_AT_high_pc
	.byte	3                               // DW_AT_call_file
	.byte	78                              // DW_AT_call_line
	.byte	22                              // DW_AT_call_column
	.byte	19                              // Abbrev [19] 0x32d:0x5 DW_TAG_formal_parameter
	.long	328                             // DW_AT_abstract_origin
	.byte	20                              // Abbrev [20] 0x332:0x9 DW_TAG_variable
	.long	.Ldebug_loc30                   // DW_AT_location
	.long	339                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x33b:0x16 DW_TAG_inlined_subroutine
	.long	285                             // DW_AT_abstract_origin
	.long	.Ltmp144                        // DW_AT_low_pc
	.long	.Ltmp147-.Ltmp144               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	251                             // DW_AT_call_line
	.byte	23                              // DW_AT_call_column
	.byte	19                              // Abbrev [19] 0x34b:0x5 DW_TAG_formal_parameter
	.long	297                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	16                              // Abbrev [16] 0x353:0x5f DW_TAG_inlined_subroutine
	.long	156                             // DW_AT_abstract_origin
	.long	.Ltmp48                         // DW_AT_low_pc
	.long	.Ltmp66-.Ltmp48                 // DW_AT_high_pc
	.byte	3                               // DW_AT_call_file
	.byte	145                             // DW_AT_call_line
	.byte	5                               // DW_AT_call_column
	.byte	19                              // Abbrev [19] 0x363:0x5 DW_TAG_formal_parameter
	.long	164                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x368:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc15                   // DW_AT_location
	.long	175                             // DW_AT_abstract_origin
	.byte	19                              // Abbrev [19] 0x371:0x5 DW_TAG_formal_parameter
	.long	186                             // DW_AT_abstract_origin
	.byte	19                              // Abbrev [19] 0x376:0x5 DW_TAG_formal_parameter
	.long	197                             // DW_AT_abstract_origin
	.byte	20                              // Abbrev [20] 0x37b:0x9 DW_TAG_variable
	.long	.Ldebug_loc16                   // DW_AT_location
	.long	208                             // DW_AT_abstract_origin
	.byte	20                              // Abbrev [20] 0x384:0x9 DW_TAG_variable
	.long	.Ldebug_loc17                   // DW_AT_location
	.long	219                             // DW_AT_abstract_origin
	.byte	20                              // Abbrev [20] 0x38d:0x9 DW_TAG_variable
	.long	.Ldebug_loc18                   // DW_AT_location
	.long	230                             // DW_AT_abstract_origin
	.byte	20                              // Abbrev [20] 0x396:0x9 DW_TAG_variable
	.long	.Ldebug_loc19                   // DW_AT_location
	.long	241                             // DW_AT_abstract_origin
	.byte	20                              // Abbrev [20] 0x39f:0x9 DW_TAG_variable
	.long	.Ldebug_loc20                   // DW_AT_location
	.long	252                             // DW_AT_abstract_origin
	.byte	20                              // Abbrev [20] 0x3a8:0x9 DW_TAG_variable
	.long	.Ldebug_loc21                   // DW_AT_location
	.long	263                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x3b2:0x33 DW_TAG_lexical_block
	.long	.Ltmp102                        // DW_AT_low_pc
	.long	.Ltmp112-.Ltmp102               // DW_AT_high_pc
	.byte	15                              // Abbrev [15] 0x3bb:0xf DW_TAG_variable
	.long	.Ldebug_loc27                   // DW_AT_location
	.long	.Linfo_string52                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	183                             // DW_AT_decl_line
	.long	1143                            // DW_AT_type
	.byte	15                              // Abbrev [15] 0x3ca:0xf DW_TAG_variable
	.long	.Ldebug_loc28                   // DW_AT_location
	.long	.Linfo_string54                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	185                             // DW_AT_decl_line
	.long	56                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0x3d9:0xb DW_TAG_variable
	.long	.Linfo_string55                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	191                             // DW_AT_decl_line
	.long	1155                            // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	23                              // Abbrev [23] 0x3e5:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp17                         // DW_AT_low_pc
	.byte	23                              // Abbrev [23] 0x3ec:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp20                         // DW_AT_low_pc
	.byte	23                              // Abbrev [23] 0x3f3:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp23                         // DW_AT_low_pc
	.byte	23                              // Abbrev [23] 0x3fa:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp26                         // DW_AT_low_pc
	.byte	23                              // Abbrev [23] 0x401:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp29                         // DW_AT_low_pc
	.byte	23                              // Abbrev [23] 0x408:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp32                         // DW_AT_low_pc
	.byte	23                              // Abbrev [23] 0x40f:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp37                         // DW_AT_low_pc
	.byte	23                              // Abbrev [23] 0x416:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp38                         // DW_AT_low_pc
	.byte	23                              // Abbrev [23] 0x41d:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp41                         // DW_AT_low_pc
	.byte	23                              // Abbrev [23] 0x424:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp43                         // DW_AT_low_pc
	.byte	23                              // Abbrev [23] 0x42b:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp49                         // DW_AT_low_pc
	.byte	23                              // Abbrev [23] 0x432:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp51                         // DW_AT_low_pc
	.byte	23                              // Abbrev [23] 0x439:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp54                         // DW_AT_low_pc
	.byte	23                              // Abbrev [23] 0x440:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp56                         // DW_AT_low_pc
	.byte	23                              // Abbrev [23] 0x447:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp71                         // DW_AT_low_pc
	.byte	23                              // Abbrev [23] 0x44e:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp89                         // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x456:0x5 DW_TAG_const_type
	.long	1115                            // DW_AT_type
	.byte	3                               // Abbrev [3] 0x45b:0x7 DW_TAG_base_type
	.long	.Linfo_string31                 // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	7                               // Abbrev [7] 0x462:0x5 DW_TAG_const_type
	.long	56                              // DW_AT_type
	.byte	7                               // Abbrev [7] 0x467:0x5 DW_TAG_const_type
	.long	1132                            // DW_AT_type
	.byte	2                               // Abbrev [2] 0x46c:0xb DW_TAG_typedef
	.long	1115                            // DW_AT_type
	.long	.Linfo_string39                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	48                              // DW_AT_decl_line
	.byte	7                               // Abbrev [7] 0x477:0x5 DW_TAG_const_type
	.long	1148                            // DW_AT_type
	.byte	3                               // Abbrev [3] 0x47c:0x7 DW_TAG_base_type
	.long	.Linfo_string53                 // DW_AT_name
	.byte	2                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	7                               // Abbrev [7] 0x483:0x5 DW_TAG_const_type
	.long	113                             // DW_AT_type
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_ranges,"",@progbits
.Ldebug_ranges0:
	.long	.Ltmp78-.Lfunc_begin0
	.long	.Ltmp84-.Lfunc_begin0
	.long	.Ltmp96-.Lfunc_begin0
	.long	.Ltmp101-.Lfunc_begin0
	.long	.Ltmp113-.Lfunc_begin0
	.long	.Ltmp121-.Lfunc_begin0
	.long	.Ltmp123-.Lfunc_begin0
	.long	.Ltmp155-.Lfunc_begin0
	.long	0
	.long	0
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/divdf3.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=152
.Linfo_string3:
	.asciz	"long unsigned int"             // string offset=173
.Linfo_string4:
	.asciz	"uint64_t"                      // string offset=191
.Linfo_string5:
	.asciz	"rep_t"                         // string offset=200
.Linfo_string6:
	.asciz	"toRep"                         // string offset=206
.Linfo_string7:
	.asciz	"x"                             // string offset=212
.Linfo_string8:
	.asciz	"double"                        // string offset=214
.Linfo_string9:
	.asciz	"fp_t"                          // string offset=221
.Linfo_string10:
	.asciz	"rep"                           // string offset=226
.Linfo_string11:
	.asciz	"f"                             // string offset=230
.Linfo_string12:
	.asciz	"i"                             // string offset=232
.Linfo_string13:
	.asciz	"wideMultiply"                  // string offset=234
.Linfo_string14:
	.asciz	"a"                             // string offset=247
.Linfo_string15:
	.asciz	"b"                             // string offset=249
.Linfo_string16:
	.asciz	"hi"                            // string offset=251
.Linfo_string17:
	.asciz	"lo"                            // string offset=254
.Linfo_string18:
	.asciz	"r0"                            // string offset=257
.Linfo_string19:
	.asciz	"plolo"                         // string offset=260
.Linfo_string20:
	.asciz	"plohi"                         // string offset=266
.Linfo_string21:
	.asciz	"philo"                         // string offset=272
.Linfo_string22:
	.asciz	"phihi"                         // string offset=278
.Linfo_string23:
	.asciz	"r1"                            // string offset=284
.Linfo_string24:
	.asciz	"rep_clz"                       // string offset=287
.Linfo_string25:
	.asciz	"int"                           // string offset=295
.Linfo_string26:
	.asciz	"normalize"                     // string offset=299
.Linfo_string27:
	.asciz	"significand"                   // string offset=309
.Linfo_string28:
	.asciz	"shift"                         // string offset=321
.Linfo_string29:
	.asciz	"__divdf3"                      // string offset=327
.Linfo_string30:
	.asciz	"aExponent"                     // string offset=336
.Linfo_string31:
	.asciz	"unsigned int"                  // string offset=346
.Linfo_string32:
	.asciz	"bExponent"                     // string offset=359
.Linfo_string33:
	.asciz	"quotientSign"                  // string offset=369
.Linfo_string34:
	.asciz	"aSignificand"                  // string offset=382
.Linfo_string35:
	.asciz	"scale"                         // string offset=395
.Linfo_string36:
	.asciz	"bSignificand"                  // string offset=401
.Linfo_string37:
	.asciz	"quotientExponent"              // string offset=414
.Linfo_string38:
	.asciz	"q31b"                          // string offset=431
.Linfo_string39:
	.asciz	"uint32_t"                      // string offset=436
.Linfo_string40:
	.asciz	"recip32"                       // string offset=445
.Linfo_string41:
	.asciz	"correction32"                  // string offset=453
.Linfo_string42:
	.asciz	"q63blo"                        // string offset=466
.Linfo_string43:
	.asciz	"correction"                    // string offset=473
.Linfo_string44:
	.asciz	"cLo"                           // string offset=484
.Linfo_string45:
	.asciz	"cHi"                           // string offset=488
.Linfo_string46:
	.asciz	"reciprocal"                    // string offset=492
.Linfo_string47:
	.asciz	"quotient"                      // string offset=503
.Linfo_string48:
	.asciz	"residual"                      // string offset=512
.Linfo_string49:
	.asciz	"writtenExponent"               // string offset=521
.Linfo_string50:
	.asciz	"bAbs"                          // string offset=537
.Linfo_string51:
	.asciz	"aAbs"                          // string offset=542
.Linfo_string52:
	.asciz	"round"                         // string offset=547
.Linfo_string53:
	.asciz	"_Bool"                         // string offset=553
.Linfo_string54:
	.asciz	"absResult"                     // string offset=559
.Linfo_string55:
	.asciz	"result"                        // string offset=569
.Linfo_string56:
	.asciz	"quotientLo"                    // string offset=576
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
