	.text
	.file	"extendsfdf2.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/syslib/fp_extend.h"
	.file	2 "/root" "uPIMulator_frontend/sdk/stdlib/stdint.h"
	.section	.text.__extendsfdf2,"ax",@progbits
	.globl	__extendsfdf2                   // -- Begin function __extendsfdf2
	.type	__extendsfdf2,@function
__extendsfdf2:                          // @__extendsfdf2
.Lfunc_begin0:
	.file	3 "/root" "uPIMulator_frontend/sdk/syslib/extendsfdf2.c"
	.loc	3 17 0                          // uPIMulator_frontend/sdk/syslib/extendsfdf2.c:17:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __extendsfdf2:a <- $r0
	//DEBUG_VALUE: __extendsfdf2:a <- $r0
	//DEBUG_VALUE: __extendXfYf2__:a <- $r0
	//DEBUG_VALUE: __extendXfYf2__:a <- $r0
	//DEBUG_VALUE: srcToRep:x <- $r0
	//DEBUG_VALUE: srcToRep:x <- $r0
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: srcToRep:rep <- $r0
	//DEBUG_VALUE: srcToRep:rep <- $r0
	//DEBUG_VALUE: __extendXfYf2__:srcBits <- 32
	//DEBUG_VALUE: __extendXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __extendXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __extendXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __extendXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __extendXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __extendXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __extendXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __extendXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __extendXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __extendXfYf2__:dstBits <- 64
	//DEBUG_VALUE: __extendXfYf2__:dstExpBits <- 11
	//DEBUG_VALUE: __extendXfYf2__:dstInfExp <- 2047
	//DEBUG_VALUE: __extendXfYf2__:dstExpBias <- 1023
	//DEBUG_VALUE: __extendXfYf2__:dstMinNormal <- 4503599627370496
	//DEBUG_VALUE: __extendXfYf2__:aRep <- $r0
	.file	4 "/root" "uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc"
	.loc	4 65 33 prologue_end            // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:65:33
	and r2, r0, 2147483647
.Ltmp0:
	//DEBUG_VALUE: __extendXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __extendXfYf2__:aAbs <- $r2
	.loc	4 71 26                         // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:71:26
	add r1, r2, -8388608
.Ltmp1:
	.loc	4 71 9 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:71:9
	lsr r1, r1, 24
	jgtu r1, 126, .LBB0_2
.Ltmp2:
// %bb.1:
	//DEBUG_VALUE: __extendXfYf2__:aAbs <- $r2
	//DEBUG_VALUE: __extendXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __extendXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __extendXfYf2__:a <- $r0
	//DEBUG_VALUE: __extendsfdf2:a <- $r0
	//DEBUG_VALUE: __extendXfYf2__:dstMinNormal <- 4503599627370496
	//DEBUG_VALUE: __extendXfYf2__:dstExpBias <- 1023
	//DEBUG_VALUE: __extendXfYf2__:dstInfExp <- 2047
	//DEBUG_VALUE: __extendXfYf2__:dstExpBits <- 11
	//DEBUG_VALUE: __extendXfYf2__:dstBits <- 64
	//DEBUG_VALUE: __extendXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __extendXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __extendXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __extendXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __extendXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __extendXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __extendXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __extendXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __extendXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __extendXfYf2__:srcBits <- 32
	.loc	4 75 21 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:75:21
	move.u d2, r2
.Ltmp3:
	.loc	4 75 37 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:75:37
	lslx r1, r3, 29
	lsl_add r4, r1, r2, 29
	lsl r5, r3, 29
.Ltmp4:
	//DEBUG_VALUE: __extendXfYf2__:absResult <- $d4
	.loc	4 76 19 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:76:19
	add r3, r5, 0
	addc r2, r4, 939524096
.Ltmp5:
	//DEBUG_VALUE: __extendXfYf2__:absResult <- $d2
	.loc	4 0 19 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:0:19
	jump .LBB0_10
.Ltmp6:
.LBB0_2:
	//DEBUG_VALUE: __extendXfYf2__:aAbs <- $r2
	//DEBUG_VALUE: __extendXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __extendXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __extendXfYf2__:a <- $r0
	//DEBUG_VALUE: __extendsfdf2:a <- $r0
	//DEBUG_VALUE: __extendXfYf2__:dstMinNormal <- 4503599627370496
	//DEBUG_VALUE: __extendXfYf2__:dstExpBias <- 1023
	//DEBUG_VALUE: __extendXfYf2__:dstInfExp <- 2047
	//DEBUG_VALUE: __extendXfYf2__:dstExpBits <- 11
	//DEBUG_VALUE: __extendXfYf2__:dstBits <- 64
	//DEBUG_VALUE: __extendXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __extendXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __extendXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __extendXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __extendXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __extendXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __extendXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __extendXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __extendXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __extendXfYf2__:srcBits <- 32
	.loc	4 79 14 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:79:14
	lsr r1, r2, 23
	jltu r1, 255, .LBB0_4
.Ltmp7:
// %bb.3:
	//DEBUG_VALUE: __extendXfYf2__:aAbs <- $r2
	//DEBUG_VALUE: __extendXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __extendXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __extendXfYf2__:a <- $r0
	//DEBUG_VALUE: __extendsfdf2:a <- $r0
	//DEBUG_VALUE: __extendXfYf2__:dstMinNormal <- 4503599627370496
	//DEBUG_VALUE: __extendXfYf2__:dstExpBias <- 1023
	//DEBUG_VALUE: __extendXfYf2__:dstInfExp <- 2047
	//DEBUG_VALUE: __extendXfYf2__:dstExpBits <- 11
	//DEBUG_VALUE: __extendXfYf2__:dstBits <- 64
	//DEBUG_VALUE: __extendXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __extendXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __extendXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __extendXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __extendXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __extendXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __extendXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __extendXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __extendXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __extendXfYf2__:srcBits <- 32
	//DEBUG_VALUE: __extendXfYf2__:absResult <- [DW_OP_constu 4194304, DW_OP_and, DW_OP_LLVM_convert 32 7, DW_OP_LLVM_convert 64 7, DW_OP_constu 29, DW_OP_shl, DW_OP_constu 9218868437227405312, DW_OP_or, DW_OP_stack_value] $r0
	.loc	4 86 19                         // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:86:19
	move.u d2, r0
.Ltmp8:
	lslx r1, r3, 29
	lsl_add r4, r1, r2, 29
	lsl r5, r3, 29
	or r3, r5, 0
	or r2, r4, 2146435072
.Ltmp9:
	//DEBUG_VALUE: __extendXfYf2__:absResult <- $d2
	.loc	4 0 19 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:0:19
	jump .LBB0_10
.Ltmp10:
.LBB0_4:
	//DEBUG_VALUE: __extendXfYf2__:aAbs <- $r2
	//DEBUG_VALUE: __extendXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __extendXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __extendXfYf2__:a <- $r0
	//DEBUG_VALUE: __extendsfdf2:a <- $r0
	//DEBUG_VALUE: __extendXfYf2__:dstMinNormal <- 4503599627370496
	//DEBUG_VALUE: __extendXfYf2__:dstExpBias <- 1023
	//DEBUG_VALUE: __extendXfYf2__:dstInfExp <- 2047
	//DEBUG_VALUE: __extendXfYf2__:dstExpBits <- 11
	//DEBUG_VALUE: __extendXfYf2__:dstBits <- 64
	//DEBUG_VALUE: __extendXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __extendXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __extendXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __extendXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __extendXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __extendXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __extendXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __extendXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __extendXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __extendXfYf2__:srcBits <- 32
	.loc	4 89 14 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:89:14
	jeq r2, 0, .LBB0_5
.Ltmp11:
// %bb.6:
	//DEBUG_VALUE: __extendXfYf2__:aAbs <- $r2
	//DEBUG_VALUE: __extendXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __extendXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __extendXfYf2__:a <- $r0
	//DEBUG_VALUE: __extendsfdf2:a <- $r0
	//DEBUG_VALUE: __extendXfYf2__:dstMinNormal <- 4503599627370496
	//DEBUG_VALUE: __extendXfYf2__:dstExpBias <- 1023
	//DEBUG_VALUE: __extendXfYf2__:dstInfExp <- 2047
	//DEBUG_VALUE: __extendXfYf2__:dstExpBits <- 11
	//DEBUG_VALUE: __extendXfYf2__:dstBits <- 64
	//DEBUG_VALUE: __extendXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __extendXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __extendXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __extendXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __extendXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __extendXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __extendXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __extendXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __extendXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __extendXfYf2__:srcBits <- 32
	.loc	4 93 27                         // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:93:27
	clz r1, r2
.Ltmp12:
	//DEBUG_VALUE: scale <- [DW_OP_constu 8, DW_OP_minus, DW_OP_stack_value] $r1
	.loc	4 94 21                         // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:94:21
	move.u d4, r2
	.loc	4 94 65 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:94:65
	add r6, r1, 21
	.loc	4 94 37                         // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:94:37
	lslx r2, r5, r6, sh32, .LBB0_8
.Ltmp13:
// %bb.7:
	//DEBUG_VALUE: scale <- [DW_OP_constu 8, DW_OP_minus, DW_OP_stack_value] $r1
	//DEBUG_VALUE: __extendXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __extendXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __extendXfYf2__:a <- $r0
	//DEBUG_VALUE: __extendsfdf2:a <- $r0
	//DEBUG_VALUE: __extendXfYf2__:dstMinNormal <- 4503599627370496
	//DEBUG_VALUE: __extendXfYf2__:dstExpBias <- 1023
	//DEBUG_VALUE: __extendXfYf2__:dstInfExp <- 2047
	//DEBUG_VALUE: __extendXfYf2__:dstExpBits <- 11
	//DEBUG_VALUE: __extendXfYf2__:dstBits <- 64
	//DEBUG_VALUE: __extendXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __extendXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __extendXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __extendXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __extendXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __extendXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __extendXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __extendXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __extendXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __extendXfYf2__:srcBits <- 32
	lsl r3, r4, r6
	or r2, r3, r2
	lsl r3, r5, r6, true, .LBB0_9
.Ltmp14:
.LBB0_5:
	//DEBUG_VALUE: __extendXfYf2__:aAbs <- $r2
	//DEBUG_VALUE: __extendXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __extendXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __extendXfYf2__:a <- $r0
	//DEBUG_VALUE: __extendsfdf2:a <- $r0
	//DEBUG_VALUE: __extendXfYf2__:dstMinNormal <- 4503599627370496
	//DEBUG_VALUE: __extendXfYf2__:dstExpBias <- 1023
	//DEBUG_VALUE: __extendXfYf2__:dstInfExp <- 2047
	//DEBUG_VALUE: __extendXfYf2__:dstExpBits <- 11
	//DEBUG_VALUE: __extendXfYf2__:dstBits <- 64
	//DEBUG_VALUE: __extendXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __extendXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __extendXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __extendXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __extendXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __extendXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __extendXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __extendXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __extendXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __extendXfYf2__:srcBits <- 32
	.loc	4 0 37                          // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:0:37
	move.s d2, 0
.Ltmp15:
	jump .LBB0_10
.Ltmp16:
.LBB0_8:
	//DEBUG_VALUE: scale <- [DW_OP_constu 8, DW_OP_minus, DW_OP_stack_value] $r1
	//DEBUG_VALUE: __extendXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __extendXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __extendXfYf2__:a <- $r0
	//DEBUG_VALUE: __extendsfdf2:a <- $r0
	//DEBUG_VALUE: __extendXfYf2__:dstMinNormal <- 4503599627370496
	//DEBUG_VALUE: __extendXfYf2__:dstExpBias <- 1023
	//DEBUG_VALUE: __extendXfYf2__:dstInfExp <- 2047
	//DEBUG_VALUE: __extendXfYf2__:dstExpBits <- 11
	//DEBUG_VALUE: __extendXfYf2__:dstBits <- 64
	//DEBUG_VALUE: __extendXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __extendXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __extendXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __extendXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __extendXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __extendXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __extendXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __extendXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __extendXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __extendXfYf2__:srcBits <- 32
	.loc	4 94 37                         // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:94:37
	lsl r2, r5, r6
	move r3, 0
.Ltmp17:
.LBB0_9:
	//DEBUG_VALUE: scale <- [DW_OP_constu 8, DW_OP_minus, DW_OP_stack_value] $r1
	//DEBUG_VALUE: __extendXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __extendXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __extendXfYf2__:a <- $r0
	//DEBUG_VALUE: __extendsfdf2:a <- $r0
	//DEBUG_VALUE: __extendXfYf2__:dstMinNormal <- 4503599627370496
	//DEBUG_VALUE: __extendXfYf2__:dstExpBias <- 1023
	//DEBUG_VALUE: __extendXfYf2__:dstInfExp <- 2047
	//DEBUG_VALUE: __extendXfYf2__:dstExpBits <- 11
	//DEBUG_VALUE: __extendXfYf2__:dstBits <- 64
	//DEBUG_VALUE: __extendXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __extendXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __extendXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __extendXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __extendXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __extendXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __extendXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __extendXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __extendXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __extendXfYf2__:srcBits <- 32
	//DEBUG_VALUE: __extendXfYf2__:absResult <- $d2
	.loc	4 95 19 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:95:19
	xor r3, r3, 0
.Ltmp18:
	xor r2, r2, 1048576
.Ltmp19:
	//DEBUG_VALUE: __extendXfYf2__:absResult <- $d2
	.loc	4 96 68                         // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:96:68
	sub r1, 905, r1
.Ltmp20:
	//DEBUG_VALUE: resultExponent <- $r1
	.loc	4 97 22                         // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:97:22
	move.s d4, r1
	.loc	4 97 48 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:97:48
	move r7, 0
	lsl r6, r5, 20
	.loc	4 97 19                         // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:97:19
	or r3, r3, r7
.Ltmp21:
	or r2, r2, r6
.Ltmp22:
	//DEBUG_VALUE: __extendXfYf2__:absResult <- $d2
.LBB0_10:
	//DEBUG_VALUE: __extendXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __extendXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __extendXfYf2__:a <- $r0
	//DEBUG_VALUE: __extendsfdf2:a <- $r0
	//DEBUG_VALUE: __extendXfYf2__:dstMinNormal <- 4503599627370496
	//DEBUG_VALUE: __extendXfYf2__:dstExpBias <- 1023
	//DEBUG_VALUE: __extendXfYf2__:dstInfExp <- 2047
	//DEBUG_VALUE: __extendXfYf2__:dstExpBits <- 11
	//DEBUG_VALUE: __extendXfYf2__:dstBits <- 64
	//DEBUG_VALUE: __extendXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __extendXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __extendXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __extendXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __extendXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __extendXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __extendXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __extendXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __extendXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __extendXfYf2__:srcBits <- 32
	.loc	4 66 33 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:66:33
	and r0, r0, -2147483648
.Ltmp23:
	//DEBUG_VALUE: __extendXfYf2__:absResult <- $d2
	//DEBUG_VALUE: __extendXfYf2__:sign <- $r0
	.loc	4 106 42                        // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:106:42
	move.s d0, r0
.Ltmp24:
	.loc	4 106 58 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:106:58
	move r5, 0
	move r4, r1
	.loc	4 106 40                        // uPIMulator_frontend/sdk/syslib/fp_extend_impl.inc:106:40
	or r1, r3, r5
	or r0, r2, r4
.Ltmp25:
	//DEBUG_VALUE: dstFromRep:rep <- undef
	//DEBUG_VALUE: dstFromRep:x <- $d0
	//DEBUG_VALUE: __extendXfYf2__:result <- $d0
	.loc	3 18 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/extendsfdf2.c:18:5
	jump r23
.Ltmp26:
.Lfunc_end0:
	.size	__extendsfdf2, .Lfunc_end0-__extendsfdf2
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__extendsfdf2
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.__extendsfdf2,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp23-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp23-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp23-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp23-.Lfunc_begin0
	.short	15                              // Loc expr size
	.byte	112                             // DW_OP_breg0
	.byte	0                               // 0
	.byte	16                              // DW_OP_constu
	.byte	128                             // 18446744071562067968
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	248                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	1                               // 
	.byte	26                              // DW_OP_and
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp23-.Lfunc_begin0
	.long	.Ltmp24-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc4:
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp3-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp6-.Lfunc_begin0
	.long	.Ltmp8-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp10-.Lfunc_begin0
	.long	.Ltmp13-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Ltmp15-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc5:
	.long	.Ltmp4-.Lfunc_begin0
	.long	.Ltmp5-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp5-.Lfunc_begin0
	.long	.Ltmp6-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp7-.Lfunc_begin0
	.long	.Ltmp9-.Lfunc_begin0
	.short	29                              // Loc expr size
	.byte	112                             // DW_OP_breg0
	.byte	0                               // 0
	.byte	16                              // DW_OP_constu
	.byte	128                             // 4194304
	.byte	128                             // 
	.byte	128                             // 
	.byte	2                               // 
	.byte	26                              // DW_OP_and
	.byte	16                              // DW_OP_constu
	.byte	255                             // 4294967295
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	15                              // 
	.byte	26                              // DW_OP_and
	.byte	77                              // DW_OP_lit29
	.byte	36                              // DW_OP_shl
	.byte	16                              // DW_OP_constu
	.byte	128                             // 9218868437227405312
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	248                             // 
	.byte	127                             // 
	.byte	33                              // DW_OP_or
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp9-.Lfunc_begin0
	.long	.Ltmp10-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp17-.Lfunc_begin0
	.long	.Ltmp18-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp19-.Lfunc_begin0
	.long	.Ltmp21-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp23-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc6:
	.long	.Ltmp12-.Lfunc_begin0
	.long	.Ltmp14-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	113                             // DW_OP_breg1
	.byte	120                             // -8
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp16-.Lfunc_begin0
	.long	.Ltmp20-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	113                             // DW_OP_breg1
	.byte	120                             // -8
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc7:
	.long	.Ltmp20-.Lfunc_begin0
	.long	.Ltmp22-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	28                              // DW_AT_const_value
	.byte	15                              // DW_FORM_udata
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	11                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	12                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	1                               // DW_CHILDREN_yes
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	13                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	14                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	28                              // DW_AT_const_value
	.byte	13                              // DW_FORM_sdata
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	15                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	28                              // DW_AT_const_value
	.byte	15                              // DW_FORM_udata
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	16                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	17                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x2b3 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0xc DW_TAG_variable
	.long	.Linfo_string3                  // DW_AT_name
	.long	50                              // DW_AT_type
	.byte	1                               // DW_AT_decl_file
	.byte	23                              // DW_AT_decl_line
	.byte	23                              // DW_AT_const_value
	.byte	3                               // Abbrev [3] 0x32:0x5 DW_TAG_const_type
	.long	55                              // DW_AT_type
	.byte	4                               // Abbrev [4] 0x37:0x7 DW_TAG_base_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	2                               // Abbrev [2] 0x3e:0xc DW_TAG_variable
	.long	.Linfo_string5                  // DW_AT_name
	.long	50                              // DW_AT_type
	.byte	1                               // DW_AT_decl_file
	.byte	65                              // DW_AT_decl_line
	.byte	52                              // DW_AT_const_value
	.byte	5                               // Abbrev [5] 0x4a:0xb DW_TAG_typedef
	.long	85                              // DW_AT_type
	.long	.Linfo_string8                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	21                              // DW_AT_decl_line
	.byte	5                               // Abbrev [5] 0x55:0xb DW_TAG_typedef
	.long	96                              // DW_AT_type
	.long	.Linfo_string7                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	48                              // DW_AT_decl_line
	.byte	4                               // Abbrev [4] 0x60:0x7 DW_TAG_base_type
	.long	.Linfo_string6                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	5                               // Abbrev [5] 0x67:0xb DW_TAG_typedef
	.long	114                             // DW_AT_type
	.long	.Linfo_string11                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	63                              // DW_AT_decl_line
	.byte	5                               // Abbrev [5] 0x72:0xb DW_TAG_typedef
	.long	125                             // DW_AT_type
	.long	.Linfo_string10                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	53                              // DW_AT_decl_line
	.byte	4                               // Abbrev [4] 0x7d:0x7 DW_TAG_base_type
	.long	.Linfo_string9                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	6                               // Abbrev [6] 0x84:0x10c DW_TAG_subprogram
	.long	.Linfo_string12                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	41                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	400                             // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	7                               // Abbrev [7] 0x90:0xb DW_TAG_formal_parameter
	.long	.Linfo_string15                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	41                              // DW_AT_decl_line
	.long	418                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x9b:0xb DW_TAG_variable
	.long	.Linfo_string18                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	44                              // DW_AT_decl_line
	.long	50                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0xa6:0xb DW_TAG_variable
	.long	.Linfo_string19                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	45                              // DW_AT_decl_line
	.long	50                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0xb1:0xb DW_TAG_variable
	.long	.Linfo_string20                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	46                              // DW_AT_decl_line
	.long	50                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0xbc:0xb DW_TAG_variable
	.long	.Linfo_string21                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	47                              // DW_AT_decl_line
	.long	50                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0xc7:0xb DW_TAG_variable
	.long	.Linfo_string22                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	49                              // DW_AT_decl_line
	.long	436                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0xd2:0xb DW_TAG_variable
	.long	.Linfo_string23                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	50                              // DW_AT_decl_line
	.long	436                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0xdd:0xb DW_TAG_variable
	.long	.Linfo_string24                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	51                              // DW_AT_decl_line
	.long	436                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0xe8:0xb DW_TAG_variable
	.long	.Linfo_string25                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	52                              // DW_AT_decl_line
	.long	436                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0xf3:0xb DW_TAG_variable
	.long	.Linfo_string26                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	53                              // DW_AT_decl_line
	.long	436                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0xfe:0xb DW_TAG_variable
	.long	.Linfo_string27                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	54                              // DW_AT_decl_line
	.long	436                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x109:0xb DW_TAG_variable
	.long	.Linfo_string28                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	56                              // DW_AT_decl_line
	.long	50                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0x114:0xb DW_TAG_variable
	.long	.Linfo_string29                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	57                              // DW_AT_decl_line
	.long	50                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0x11f:0xb DW_TAG_variable
	.long	.Linfo_string30                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	58                              // DW_AT_decl_line
	.long	50                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0x12a:0xb DW_TAG_variable
	.long	.Linfo_string31                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	59                              // DW_AT_decl_line
	.long	50                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0x135:0xb DW_TAG_variable
	.long	.Linfo_string32                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	61                              // DW_AT_decl_line
	.long	441                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x140:0xb DW_TAG_variable
	.long	.Linfo_string33                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	64                              // DW_AT_decl_line
	.long	436                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x14b:0xb DW_TAG_variable
	.long	.Linfo_string34                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	66                              // DW_AT_decl_line
	.long	436                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x156:0xb DW_TAG_variable
	.long	.Linfo_string35                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	65                              // DW_AT_decl_line
	.long	436                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x161:0xb DW_TAG_variable
	.long	.Linfo_string36                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	67                              // DW_AT_decl_line
	.long	103                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x16c:0xb DW_TAG_variable
	.long	.Linfo_string37                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	106                             // DW_AT_decl_line
	.long	441                             // DW_AT_type
	.byte	9                               // Abbrev [9] 0x177:0x18 DW_TAG_lexical_block
	.byte	8                               // Abbrev [8] 0x178:0xb DW_TAG_variable
	.long	.Linfo_string38                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	93                              // DW_AT_decl_line
	.long	50                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0x183:0xb DW_TAG_variable
	.long	.Linfo_string39                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	96                              // DW_AT_decl_line
	.long	50                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	5                               // Abbrev [5] 0x190:0xb DW_TAG_typedef
	.long	411                             // DW_AT_type
	.long	.Linfo_string14                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	62                              // DW_AT_decl_line
	.byte	4                               // Abbrev [4] 0x19b:0x7 DW_TAG_base_type
	.long	.Linfo_string13                 // DW_AT_name
	.byte	4                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	5                               // Abbrev [5] 0x1a2:0xb DW_TAG_typedef
	.long	429                             // DW_AT_type
	.long	.Linfo_string17                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	20                              // DW_AT_decl_line
	.byte	4                               // Abbrev [4] 0x1ad:0x7 DW_TAG_base_type
	.long	.Linfo_string16                 // DW_AT_name
	.byte	4                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	3                               // Abbrev [3] 0x1b4:0x5 DW_TAG_const_type
	.long	74                              // DW_AT_type
	.byte	3                               // Abbrev [3] 0x1b9:0x5 DW_TAG_const_type
	.long	103                             // DW_AT_type
	.byte	10                              // Abbrev [10] 0x1be:0xff DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string40                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	16                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	411                             // DW_AT_type
                                        // DW_AT_external
	.byte	11                              // Abbrev [11] 0x1d3:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string15                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	16                              // DW_AT_decl_line
	.long	429                             // DW_AT_type
	.byte	12                              // Abbrev [12] 0x1e2:0xda DW_TAG_inlined_subroutine
	.long	132                             // DW_AT_abstract_origin
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Ltmp25-.Lfunc_begin0           // DW_AT_high_pc
	.byte	3                               // DW_AT_call_file
	.byte	18                              // DW_AT_call_line
	.byte	12                              // DW_AT_call_column
	.byte	13                              // Abbrev [13] 0x1f2:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	144                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x1fb:0x6 DW_TAG_variable
	.byte	32                              // DW_AT_const_value
	.long	155                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x201:0x6 DW_TAG_variable
	.byte	8                               // DW_AT_const_value
	.long	166                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x207:0x7 DW_TAG_variable
	.ascii	"\377\001"                      // DW_AT_const_value
	.long	177                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x20e:0x7 DW_TAG_variable
	.asciz	"\377"                          // DW_AT_const_value
	.long	188                             // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x215:0x9 DW_TAG_variable
	.ascii	"\200\200\200\004"              // DW_AT_const_value
	.long	199                             // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x21e:0xa DW_TAG_variable
	.ascii	"\200\200\200\374\007"          // DW_AT_const_value
	.long	210                             // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x228:0xf DW_TAG_variable
	.ascii	"\200\200\200\200\370\377\377\377\377\001" // DW_AT_const_value
	.long	221                             // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x237:0xa DW_TAG_variable
	.ascii	"\377\377\377\377\007"          // DW_AT_const_value
	.long	232                             // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x241:0x9 DW_TAG_variable
	.ascii	"\200\200\200\002"              // DW_AT_const_value
	.long	243                             // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x24a:0x9 DW_TAG_variable
	.ascii	"\377\377\377\001"              // DW_AT_const_value
	.long	254                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x253:0x7 DW_TAG_variable
	.asciz	"\300"                          // DW_AT_const_value
	.long	265                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x25a:0x6 DW_TAG_variable
	.byte	11                              // DW_AT_const_value
	.long	276                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x260:0x7 DW_TAG_variable
	.ascii	"\377\017"                      // DW_AT_const_value
	.long	287                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x267:0x7 DW_TAG_variable
	.ascii	"\377\007"                      // DW_AT_const_value
	.long	298                             // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x26e:0xd DW_TAG_variable
	.ascii	"\200\200\200\200\200\200\200\b" // DW_AT_const_value
	.long	309                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x27b:0x9 DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	320                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x284:0x9 DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	331                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x28d:0x9 DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	342                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x296:0x9 DW_TAG_variable
	.long	.Ldebug_loc5                    // DW_AT_location
	.long	353                             // DW_AT_abstract_origin
	.byte	17                              // Abbrev [17] 0x29f:0x1c DW_TAG_lexical_block
	.long	.Ltmp11                         // DW_AT_low_pc
	.long	.Ltmp22-.Ltmp11                 // DW_AT_high_pc
	.byte	16                              // Abbrev [16] 0x2a8:0x9 DW_TAG_variable
	.long	.Ldebug_loc6                    // DW_AT_location
	.long	376                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x2b1:0x9 DW_TAG_variable
	.long	.Ldebug_loc7                    // DW_AT_location
	.long	387                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/extendsfdf2.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=157
.Linfo_string3:
	.asciz	"srcSigBits"                    // string offset=178
.Linfo_string4:
	.asciz	"int"                           // string offset=189
.Linfo_string5:
	.asciz	"dstSigBits"                    // string offset=193
.Linfo_string6:
	.asciz	"unsigned int"                  // string offset=204
.Linfo_string7:
	.asciz	"uint32_t"                      // string offset=217
.Linfo_string8:
	.asciz	"src_rep_t"                     // string offset=226
.Linfo_string9:
	.asciz	"long unsigned int"             // string offset=236
.Linfo_string10:
	.asciz	"uint64_t"                      // string offset=254
.Linfo_string11:
	.asciz	"dst_rep_t"                     // string offset=263
.Linfo_string12:
	.asciz	"__extendXfYf2__"               // string offset=273
.Linfo_string13:
	.asciz	"double"                        // string offset=289
.Linfo_string14:
	.asciz	"dst_t"                         // string offset=296
.Linfo_string15:
	.asciz	"a"                             // string offset=302
.Linfo_string16:
	.asciz	"float"                         // string offset=304
.Linfo_string17:
	.asciz	"src_t"                         // string offset=310
.Linfo_string18:
	.asciz	"srcBits"                       // string offset=316
.Linfo_string19:
	.asciz	"srcExpBits"                    // string offset=324
.Linfo_string20:
	.asciz	"srcInfExp"                     // string offset=335
.Linfo_string21:
	.asciz	"srcExpBias"                    // string offset=345
.Linfo_string22:
	.asciz	"srcMinNormal"                  // string offset=356
.Linfo_string23:
	.asciz	"srcInfinity"                   // string offset=369
.Linfo_string24:
	.asciz	"srcSignMask"                   // string offset=381
.Linfo_string25:
	.asciz	"srcAbsMask"                    // string offset=393
.Linfo_string26:
	.asciz	"srcQNaN"                       // string offset=404
.Linfo_string27:
	.asciz	"srcNaNCode"                    // string offset=412
.Linfo_string28:
	.asciz	"dstBits"                       // string offset=423
.Linfo_string29:
	.asciz	"dstExpBits"                    // string offset=431
.Linfo_string30:
	.asciz	"dstInfExp"                     // string offset=442
.Linfo_string31:
	.asciz	"dstExpBias"                    // string offset=452
.Linfo_string32:
	.asciz	"dstMinNormal"                  // string offset=463
.Linfo_string33:
	.asciz	"aRep"                          // string offset=476
.Linfo_string34:
	.asciz	"sign"                          // string offset=481
.Linfo_string35:
	.asciz	"aAbs"                          // string offset=486
.Linfo_string36:
	.asciz	"absResult"                     // string offset=491
.Linfo_string37:
	.asciz	"result"                        // string offset=501
.Linfo_string38:
	.asciz	"scale"                         // string offset=508
.Linfo_string39:
	.asciz	"resultExponent"                // string offset=514
.Linfo_string40:
	.asciz	"__extendsfdf2"                 // string offset=529
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
