	.text
	.file	"fixsfdi.c"
	.section	.text.__fixsfdi,"ax",@progbits
	.globl	__fixsfdi                       // -- Begin function __fixsfdi
	.type	__fixsfdi,@function
__fixsfdi:                              // @__fixsfdi
.Lfunc_begin0:
	.file	1 "/root" "uPIMulator_frontend/sdk/syslib/fixsfdi.c"
	.loc	1 24 0                          // uPIMulator_frontend/sdk/syslib/fixsfdi.c:24:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __fixsfdi:a <- $r0
	.cfi_def_cfa_offset -16
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 8, d22
	add r22, r22, 16
	.cfi_offset 15, -16
	.cfi_offset 14, -12
	sd r22, -16, d14
	move r14, r0
	move r1, 0
.Ltmp0:
	//DEBUG_VALUE: __fixsfdi:a <- $r14
	.loc	1 25 11 prologue_end            // uPIMulator_frontend/sdk/syslib/fixsfdi.c:25:11
	call r23, __ltsf2
.Ltmp1:
	.loc	1 25 9 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fixsfdi.c:25:9
	jgts r0, -1, .LBB0_2
.Ltmp2:
// %bb.1:
	//DEBUG_VALUE: __fixsfdi:a <- $r14
	.loc	1 26 17 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fixsfdi.c:26:17
	xor r0, r14, -2147483648
	call r23, __fixunssfdi
.Ltmp3:
	.loc	1 0 17 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fixsfdi.c:0:17
	move.s d2, 0
	.loc	1 26 16                         // uPIMulator_frontend/sdk/syslib/fixsfdi.c:26:16
	sub r1, r3, r1
	subc r0, r2, r0
.Ltmp4:
	.loc	1 29 1 is_stmt 1                // uPIMulator_frontend/sdk/syslib/fixsfdi.c:29:1
	ld d14, r22, -16
.Ltmp5:
	ld d22, r22, -8
	jump r23
.LBB0_2:
.Ltmp6:
	//DEBUG_VALUE: __fixsfdi:a <- $r14
	.loc	1 28 12                         // uPIMulator_frontend/sdk/syslib/fixsfdi.c:28:12
	move r0, r14
	call r23, __fixunssfdi
.Ltmp7:
	.loc	1 29 1                          // uPIMulator_frontend/sdk/syslib/fixsfdi.c:29:1
	ld d14, r22, -16
.Ltmp8:
	ld d22, r22, -8
	jump r23
.Ltmp9:
.Lfunc_end0:
	.size	__fixsfdi, .Lfunc_end0-__fixsfdi
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__fixsfdi
	.long	.Lfunc_begin0
	.byte	16
	.section	.text.__fixsfdi,"ax",@progbits
                                        // -- End function
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/int_types.h"
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp5-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	.Ltmp6-.Lfunc_begin0
	.long	.Ltmp8-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.ascii	"\211\202\001"                  // DW_TAG_GNU_call_site
	.byte	0                               // DW_CHILDREN_no
	.ascii	"\223B"                         // DW_AT_GNU_call_site_target
	.byte	24                              // DW_FORM_exprloc
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x6f DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x3a DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string3                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	23                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	96                              // DW_AT_type
                                        // DW_AT_external
	.byte	3                               // Abbrev [3] 0x3b:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string6                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	23                              // DW_AT_decl_line
	.long	114                             // DW_AT_type
	.byte	4                               // Abbrev [4] 0x4a:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp1                          // DW_AT_low_pc
	.byte	4                               // Abbrev [4] 0x51:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp3                          // DW_AT_low_pc
	.byte	4                               // Abbrev [4] 0x58:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp7                          // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	5                               // Abbrev [5] 0x60:0xb DW_TAG_typedef
	.long	107                             // DW_AT_type
	.long	.Linfo_string5                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	30                              // DW_AT_decl_line
	.byte	6                               // Abbrev [6] 0x6b:0x7 DW_TAG_base_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	6                               // Abbrev [6] 0x72:0x7 DW_TAG_base_type
	.long	.Linfo_string7                  // DW_AT_name
	.byte	4                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/fixsfdi.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=153
.Linfo_string3:
	.asciz	"__fixsfdi"                     // string offset=174
.Linfo_string4:
	.asciz	"long long int"                 // string offset=184
.Linfo_string5:
	.asciz	"di_int"                        // string offset=198
.Linfo_string6:
	.asciz	"a"                             // string offset=205
.Linfo_string7:
	.asciz	"float"                         // string offset=207
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
