	.text
	.file	"fixsfsi.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/syslib/int_types.h"
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/fixsfsi.c"
	.section	.text.__fixsfsi,"ax",@progbits
	.globl	__fixsfsi                       // -- Begin function __fixsfsi
	.type	__fixsfsi,@function
__fixsfsi:                              // @__fixsfsi
.Lfunc_begin0:
	.loc	2 19 0                          // uPIMulator_frontend/sdk/syslib/fixsfsi.c:19:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __fixsfsi:a <- $r0
	//DEBUG_VALUE: __fixint:a <- $r0
	//DEBUG_VALUE: toRep:x <- $r0
	//DEBUG_VALUE: toRep:x <- $r0
	.cfi_def_cfa_offset -8
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 0, d22
	add r22, r22, 8
.Ltmp0:
	//DEBUG_VALUE: toRep:rep <- $r0
	//DEBUG_VALUE: toRep:rep <- $r0
	move r1, 1
.Ltmp1:
	//DEBUG_VALUE: __fixint:aAbs <- [DW_OP_constu 2139095040, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __fixint:aRep <- $r0
	//DEBUG_VALUE: __fixint:fixint_min <- -2147483648
	//DEBUG_VALUE: __fixint:fixint_max <- 2147483647
	//DEBUG_VALUE: __fixint:a <- $r0
	//DEBUG_VALUE: __fixsfsi:a <- $r0
	.file	3 "/root" "uPIMulator_frontend/sdk/syslib/fp_fixint_impl.inc"
	.loc	3 23 27 prologue_end            // uPIMulator_frontend/sdk/syslib/fp_fixint_impl.inc:23:27
	jles r0, -1, .LBB0_1
.Ltmp2:
// %bb.2:
	//DEBUG_VALUE: __fixint:aRep <- $r0
	//DEBUG_VALUE: __fixint:aAbs <- [DW_OP_constu 2139095040, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __fixint:a <- $r0
	//DEBUG_VALUE: __fixsfsi:a <- $r0
	//DEBUG_VALUE: __fixint:fixint_max <- 2147483647
	//DEBUG_VALUE: __fixint:fixint_min <- -2147483648
	//DEBUG_VALUE: __fixint:sign <- $r1
	.loc	3 24 32                         // uPIMulator_frontend/sdk/syslib/fp_fixint_impl.inc:24:32
	lsr r3, r0, 23
	move r2, 0
	and r3, r3, 255
.Ltmp3:
	//DEBUG_VALUE: __fixint:significand <- undef
	//DEBUG_VALUE: __fixint:exponent <- [DW_OP_constu 127, DW_OP_minus, DW_OP_stack_value] $r3
	.loc	3 28 9                          // uPIMulator_frontend/sdk/syslib/fp_fixint_impl.inc:28:9
	jgeu r3, 127, .LBB0_3
.Ltmp4:
.LBB0_10:
	//DEBUG_VALUE: __fixsfsi:a <- $r0
	.loc	2 20 5                          // uPIMulator_frontend/sdk/syslib/fixsfsi.c:20:5
	move r0, r2
.Ltmp5:
	ld d22, r22, -8
	jump r23
.LBB0_1:
.Ltmp6:
	//DEBUG_VALUE: __fixint:aRep <- $r0
	//DEBUG_VALUE: __fixint:aAbs <- [DW_OP_constu 2139095040, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __fixint:a <- $r0
	//DEBUG_VALUE: __fixsfsi:a <- $r0
	//DEBUG_VALUE: __fixint:fixint_max <- 2147483647
	//DEBUG_VALUE: __fixint:fixint_min <- -2147483648
	.loc	2 0 5 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fixsfsi.c:0:5
	move r1, -1
.Ltmp7:
	//DEBUG_VALUE: __fixint:sign <- $r1
	.loc	3 24 32 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_fixint_impl.inc:24:32
	lsr r3, r0, 23
	move r2, 0
	and r3, r3, 255
.Ltmp8:
	//DEBUG_VALUE: __fixint:significand <- undef
	//DEBUG_VALUE: __fixint:exponent <- [DW_OP_constu 127, DW_OP_minus, DW_OP_stack_value] $r3
	.loc	3 28 9                          // uPIMulator_frontend/sdk/syslib/fp_fixint_impl.inc:28:9
	jltu r3, 127, .LBB0_10
.Ltmp9:
.LBB0_3:
	//DEBUG_VALUE: __fixint:exponent <- [DW_OP_constu 127, DW_OP_minus, DW_OP_stack_value] $r3
	//DEBUG_VALUE: __fixint:sign <- $r1
	//DEBUG_VALUE: __fixint:aRep <- $r0
	//DEBUG_VALUE: __fixint:aAbs <- [DW_OP_constu 2139095040, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __fixint:a <- $r0
	//DEBUG_VALUE: __fixsfsi:a <- $r0
	//DEBUG_VALUE: __fixint:fixint_max <- 2147483647
	//DEBUG_VALUE: __fixint:fixint_min <- -2147483648
	//DEBUG_VALUE: __fixint:significand <- undef
	.loc	3 24 52                         // uPIMulator_frontend/sdk/syslib/fp_fixint_impl.inc:24:52
	add r2, r3, -127
	.loc	3 32 9                          // uPIMulator_frontend/sdk/syslib/fp_fixint_impl.inc:32:9
	jltu r2, 32, .LBB0_6
.Ltmp10:
// %bb.4:
	//DEBUG_VALUE: __fixint:exponent <- [DW_OP_constu 127, DW_OP_minus, DW_OP_stack_value] $r3
	//DEBUG_VALUE: __fixint:sign <- $r1
	//DEBUG_VALUE: __fixint:aRep <- $r0
	//DEBUG_VALUE: __fixint:aAbs <- [DW_OP_constu 2139095040, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __fixint:a <- $r0
	//DEBUG_VALUE: __fixsfsi:a <- $r0
	//DEBUG_VALUE: __fixint:fixint_max <- 2147483647
	//DEBUG_VALUE: __fixint:fixint_min <- -2147483648
	.loc	3 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_fixint_impl.inc:0:9
	move r2, 2147483647
.Ltmp11:
	.loc	3 33 16 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_fixint_impl.inc:33:16
	jgts r0, -1, .LBB0_10
.Ltmp12:
// %bb.5:
	//DEBUG_VALUE: __fixsfsi:a <- $r0
	.loc	3 0 16 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_fixint_impl.inc:0:16
	move r2, -2147483648
	.loc	2 20 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/fixsfsi.c:20:5
	move r0, r2
.Ltmp13:
	ld d22, r22, -8
	jump r23
.LBB0_6:
.Ltmp14:
	//DEBUG_VALUE: __fixint:exponent <- [DW_OP_constu 127, DW_OP_minus, DW_OP_stack_value] $r3
	//DEBUG_VALUE: __fixint:sign <- $r1
	//DEBUG_VALUE: __fixint:aRep <- $r0
	//DEBUG_VALUE: __fixint:aAbs <- [DW_OP_constu 2139095040, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __fixint:a <- $r0
	//DEBUG_VALUE: __fixsfsi:a <- $r0
	//DEBUG_VALUE: __fixint:fixint_max <- 2147483647
	//DEBUG_VALUE: __fixint:fixint_min <- -2147483648
	.loc	3 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_fixint_impl.inc:0:0
	and r0, r0, 8388607
.Ltmp15:
	or r0, r0, 8388608
.Ltmp16:
	//DEBUG_VALUE: __fixint:significand <- $r0
	.loc	3 37 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/fp_fixint_impl.inc:37:9
	jgtu r3, 149, .LBB0_8
.Ltmp17:
// %bb.7:
	//DEBUG_VALUE: __fixint:exponent <- [DW_OP_constu 127, DW_OP_minus, DW_OP_stack_value] $r3
	//DEBUG_VALUE: __fixint:sign <- $r1
	//DEBUG_VALUE: __fixint:significand <- $r0
	//DEBUG_VALUE: __fixint:fixint_max <- 2147483647
	//DEBUG_VALUE: __fixint:fixint_min <- -2147483648
	.loc	3 38 56                         // uPIMulator_frontend/sdk/syslib/fp_fixint_impl.inc:38:56
	sub r2, 150, r3
	.loc	3 38 36 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_fixint_impl.inc:38:36
	lsr r0, r0, r2, true, .LBB0_9
.Ltmp18:
.LBB0_8:
	//DEBUG_VALUE: __fixint:exponent <- [DW_OP_constu 127, DW_OP_minus, DW_OP_stack_value] $r3
	//DEBUG_VALUE: __fixint:sign <- $r1
	//DEBUG_VALUE: __fixint:significand <- $r0
	//DEBUG_VALUE: __fixint:fixint_max <- 2147483647
	//DEBUG_VALUE: __fixint:fixint_min <- -2147483648
	.loc	3 40 59 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_fixint_impl.inc:40:59
	add r2, r3, -150
	.loc	3 40 46 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_fixint_impl.inc:40:46
	lsl r0, r0, r2
.Ltmp19:
.LBB0_9:
	//DEBUG_VALUE: __fixint:exponent <- [DW_OP_constu 127, DW_OP_minus, DW_OP_stack_value] $r3
	//DEBUG_VALUE: __fixint:sign <- $r1
	//DEBUG_VALUE: __fixint:fixint_max <- 2147483647
	//DEBUG_VALUE: __fixint:fixint_min <- -2147483648
	.loc	3 0 0                           // uPIMulator_frontend/sdk/syslib/fp_fixint_impl.inc:0:0
	call r23, __mulsi3
.Ltmp20:
	move r2, r0
.Ltmp21:
	.loc	2 20 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/fixsfsi.c:20:5
	move r0, r2
	ld d22, r22, -8
	jump r23
.Ltmp22:
.Lfunc_end0:
	.size	__fixsfsi, .Lfunc_end0-__fixsfsi
	.cfi_endproc
	.file	4 "/root" "uPIMulator_frontend/sdk/syslib/fp_lib.h"
	.file	5 "/root" "uPIMulator_frontend/sdk/stdlib/stdint.h"
	.section	.stack_sizes,"o",@progbits,.text.__fixsfsi
	.long	.Lfunc_begin0
	.byte	8
	.section	.text.__fixsfsi,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp5-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp6-.Lfunc_begin0
	.long	.Ltmp13-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Ltmp15-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp4-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp6-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Ltmp15-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Ltmp1-.Lfunc_begin0
	.long	.Ltmp4-.Lfunc_begin0
	.short	10                              // Loc expr size
	.byte	112                             // DW_OP_breg0
	.byte	0                               // 0
	.byte	16                              // DW_OP_constu
	.byte	128                             // 2139095040
	.byte	128                             // 
	.byte	128                             // 
	.byte	252                             // 
	.byte	7                               // 
	.byte	26                              // DW_OP_and
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp6-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.short	10                              // Loc expr size
	.byte	112                             // DW_OP_breg0
	.byte	0                               // 0
	.byte	16                              // DW_OP_constu
	.byte	128                             // 2139095040
	.byte	128                             // 
	.byte	128                             // 
	.byte	252                             // 
	.byte	7                               // 
	.byte	26                              // DW_OP_and
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Ltmp15-.Lfunc_begin0
	.short	10                              // Loc expr size
	.byte	112                             // DW_OP_breg0
	.byte	0                               // 0
	.byte	16                              // DW_OP_constu
	.byte	128                             // 2139095040
	.byte	128                             // 
	.byte	128                             // 
	.byte	252                             // 
	.byte	7                               // 
	.byte	26                              // DW_OP_and
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Ltmp1-.Lfunc_begin0
	.long	.Ltmp4-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp6-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Ltmp15-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc4:
	.long	.Ltmp1-.Lfunc_begin0
	.long	.Ltmp4-.Lfunc_begin0
	.short	12                              // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	128                             // 18446744071562067968
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	248                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	1                               // 
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp6-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.short	12                              // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	128                             // 18446744071562067968
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	248                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	1                               // 
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	12                              // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	128                             // 18446744071562067968
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	248                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	1                               // 
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc5:
	.long	.Ltmp1-.Lfunc_begin0
	.long	.Ltmp4-.Lfunc_begin0
	.short	7                               // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	255                             // 2147483647
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	7                               // 
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp6-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.short	7                               // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	255                             // 2147483647
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	7                               // 
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	7                               // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	255                             // 2147483647
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	7                               // 
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc6:
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp4-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp7-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc7:
	.long	.Ltmp16-.Lfunc_begin0
	.long	.Ltmp19-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc8:
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp4-.Lfunc_begin0
	.short	4                               // Loc expr size
	.byte	115                             // DW_OP_breg3
	.byte	129                             // -127
	.byte	127                             // 
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp8-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.short	4                               // Loc expr size
	.byte	115                             // DW_OP_breg3
	.byte	129                             // -127
	.byte	127                             // 
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	4                               // Loc expr size
	.byte	115                             // DW_OP_breg3
	.byte	129                             // -127
	.byte	127                             // 
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	1                               // DW_CHILDREN_yes
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	11                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	12                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	13                              // Abbreviation Code
	.ascii	"\211\202\001"                  // DW_TAG_GNU_call_site
	.byte	0                               // DW_CHILDREN_no
	.ascii	"\223B"                         // DW_AT_GNU_call_site_target
	.byte	24                              // DW_FORM_exprloc
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x173 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0xb DW_TAG_typedef
	.long	49                              // DW_AT_type
	.long	.Linfo_string5                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	13                              // DW_AT_decl_line
	.byte	2                               // Abbrev [2] 0x31:0xb DW_TAG_typedef
	.long	60                              // DW_AT_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	27                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x3c:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	2                               // Abbrev [2] 0x43:0xb DW_TAG_typedef
	.long	78                              // DW_AT_type
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	14                              // DW_AT_decl_line
	.byte	2                               // Abbrev [2] 0x4e:0xb DW_TAG_typedef
	.long	89                              // DW_AT_type
	.long	.Linfo_string7                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	28                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x59:0x7 DW_TAG_base_type
	.long	.Linfo_string6                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x60:0x65 DW_TAG_subprogram
	.long	.Linfo_string9                  // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	17                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	38                              // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0x6c:0xb DW_TAG_formal_parameter
	.long	.Linfo_string10                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	17                              // DW_AT_decl_line
	.long	197                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x77:0xb DW_TAG_variable
	.long	.Linfo_string13                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
	.long	215                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x82:0xb DW_TAG_variable
	.long	.Linfo_string16                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	21                              // DW_AT_decl_line
	.long	215                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x8d:0xb DW_TAG_variable
	.long	.Linfo_string17                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	19                              // DW_AT_decl_line
	.long	242                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x98:0xb DW_TAG_variable
	.long	.Linfo_string18                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	18                              // DW_AT_decl_line
	.long	242                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xa3:0xb DW_TAG_variable
	.long	.Linfo_string19                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	23                              // DW_AT_decl_line
	.long	242                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xae:0xb DW_TAG_variable
	.long	.Linfo_string20                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	25                              // DW_AT_decl_line
	.long	215                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xb9:0xb DW_TAG_variable
	.long	.Linfo_string21                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	24                              // DW_AT_decl_line
	.long	247                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	2                               // Abbrev [2] 0xc5:0xb DW_TAG_typedef
	.long	208                             // DW_AT_type
	.long	.Linfo_string12                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	45                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0xd0:0x7 DW_TAG_base_type
	.long	.Linfo_string11                 // DW_AT_name
	.byte	4                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	7                               // Abbrev [7] 0xd7:0x5 DW_TAG_const_type
	.long	220                             // DW_AT_type
	.byte	2                               // Abbrev [2] 0xdc:0xb DW_TAG_typedef
	.long	231                             // DW_AT_type
	.long	.Linfo_string15                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	43                              // DW_AT_decl_line
	.byte	2                               // Abbrev [2] 0xe7:0xb DW_TAG_typedef
	.long	89                              // DW_AT_type
	.long	.Linfo_string14                 // DW_AT_name
	.byte	5                               // DW_AT_decl_file
	.byte	48                              // DW_AT_decl_line
	.byte	7                               // Abbrev [7] 0xf2:0x5 DW_TAG_const_type
	.long	38                              // DW_AT_type
	.byte	7                               // Abbrev [7] 0xf7:0x5 DW_TAG_const_type
	.long	60                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0xfc:0x81 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string22                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	18                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	49                              // DW_AT_type
                                        // DW_AT_external
	.byte	9                               // Abbrev [9] 0x111:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string10                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	18                              // DW_AT_decl_line
	.long	197                             // DW_AT_type
	.byte	10                              // Abbrev [10] 0x120:0x55 DW_TAG_inlined_subroutine
	.long	96                              // DW_AT_abstract_origin
	.long	.Ldebug_ranges0                 // DW_AT_ranges
	.byte	2                               // DW_AT_call_file
	.byte	20                              // DW_AT_call_line
	.byte	12                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x12c:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	108                             // DW_AT_abstract_origin
	.byte	12                              // Abbrev [12] 0x135:0x9 DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	119                             // DW_AT_abstract_origin
	.byte	12                              // Abbrev [12] 0x13e:0x9 DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	130                             // DW_AT_abstract_origin
	.byte	12                              // Abbrev [12] 0x147:0x9 DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	141                             // DW_AT_abstract_origin
	.byte	12                              // Abbrev [12] 0x150:0x9 DW_TAG_variable
	.long	.Ldebug_loc5                    // DW_AT_location
	.long	152                             // DW_AT_abstract_origin
	.byte	12                              // Abbrev [12] 0x159:0x9 DW_TAG_variable
	.long	.Ldebug_loc6                    // DW_AT_location
	.long	163                             // DW_AT_abstract_origin
	.byte	12                              // Abbrev [12] 0x162:0x9 DW_TAG_variable
	.long	.Ldebug_loc7                    // DW_AT_location
	.long	174                             // DW_AT_abstract_origin
	.byte	12                              // Abbrev [12] 0x16b:0x9 DW_TAG_variable
	.long	.Ldebug_loc8                    // DW_AT_location
	.long	185                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	13                              // Abbrev [13] 0x175:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp20                         // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_ranges,"",@progbits
.Ldebug_ranges0:
	.long	.Ltmp1-.Lfunc_begin0
	.long	.Ltmp4-.Lfunc_begin0
	.long	.Ltmp7-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Ltmp21-.Lfunc_begin0
	.long	0
	.long	0
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/fixsfsi.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=153
.Linfo_string3:
	.asciz	"int"                           // string offset=174
.Linfo_string4:
	.asciz	"si_int"                        // string offset=178
.Linfo_string5:
	.asciz	"fixint_t"                      // string offset=185
.Linfo_string6:
	.asciz	"unsigned int"                  // string offset=194
.Linfo_string7:
	.asciz	"su_int"                        // string offset=207
.Linfo_string8:
	.asciz	"fixuint_t"                     // string offset=214
.Linfo_string9:
	.asciz	"__fixint"                      // string offset=224
.Linfo_string10:
	.asciz	"a"                             // string offset=233
.Linfo_string11:
	.asciz	"float"                         // string offset=235
.Linfo_string12:
	.asciz	"fp_t"                          // string offset=241
.Linfo_string13:
	.asciz	"aAbs"                          // string offset=246
.Linfo_string14:
	.asciz	"uint32_t"                      // string offset=251
.Linfo_string15:
	.asciz	"rep_t"                         // string offset=260
.Linfo_string16:
	.asciz	"aRep"                          // string offset=266
.Linfo_string17:
	.asciz	"fixint_min"                    // string offset=271
.Linfo_string18:
	.asciz	"fixint_max"                    // string offset=282
.Linfo_string19:
	.asciz	"sign"                          // string offset=293
.Linfo_string20:
	.asciz	"significand"                   // string offset=298
.Linfo_string21:
	.asciz	"exponent"                      // string offset=310
.Linfo_string22:
	.asciz	"__fixsfsi"                     // string offset=319
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
