	.text
	.file	"fixunsdfdi.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/syslib/int_types.h"
	.section	.text.__fixunsdfdi,"ax",@progbits
	.globl	__fixunsdfdi                    // -- Begin function __fixunsdfdi
	.type	__fixunsdfdi,@function
__fixunsdfdi:                           // @__fixunsdfdi
.Lfunc_begin0:
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/fixunsdfdi.c"
	.loc	2 21 0                          // uPIMulator_frontend/sdk/syslib/fixunsdfdi.c:21:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __fixunsdfdi:a <- $d0
	.cfi_def_cfa_offset -24
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 16, d22
	add r22, r22, 24
	.cfi_offset 15, -16
	.cfi_offset 14, -12
	sd r22, -16, d14
	.cfi_offset 17, -24
	.cfi_offset 16, -20
	sd r22, -24, d16
	movd d14, d0
	move.s d16, 0
.Ltmp0:
	//DEBUG_VALUE: __fixunsdfdi:a <- $d14
	.loc	2 22 11 prologue_end            // uPIMulator_frontend/sdk/syslib/fixunsdfdi.c:22:11
	movd d2, d16
	call r23, __ledf2
.Ltmp1:
	.loc	2 22 9 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fixunsdfdi.c:22:9
	jlts r0, 1, .LBB0_2
.Ltmp2:
// %bb.1:
	//DEBUG_VALUE: __fixunsdfdi:a <- $d14
	.loc	2 0 9                           // uPIMulator_frontend/sdk/syslib/fixunsdfdi.c:0:9
	move r3, 0
	move r2, 1039138816
	.loc	2 24 21 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fixunsdfdi.c:24:21
	movd d0, d14
	call r23, __muldf3
.Ltmp3:
	.loc	2 24 19 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fixunsdfdi.c:24:19
	call r23, __fixunsdfsi
.Ltmp4:
	move r16, r0
.Ltmp5:
	//DEBUG_VALUE: __fixunsdfdi:high <- $r16
	.loc	2 25 22 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fixunsdfdi.c:25:22
	call r23, __floatunsidf
.Ltmp6:
	.loc	2 0 22 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fixunsdfdi.c:0:22
	move r3, 0
	move r2, 3253731328
	.loc	2 25 35                         // uPIMulator_frontend/sdk/syslib/fixunsdfdi.c:25:35
	call r23, __muldf3
.Ltmp7:
	movd d2, d0
	.loc	2 25 20                         // uPIMulator_frontend/sdk/syslib/fixunsdfdi.c:25:20
	movd d0, d14
	call r23, __adddf3
.Ltmp8:
	.loc	2 25 18                         // uPIMulator_frontend/sdk/syslib/fixunsdfdi.c:25:18
	call r23, __fixunsdfsi
.Ltmp9:
	//DEBUG_VALUE: __fixunsdfdi:low <- $r0
	.loc	2 26 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fixunsdfdi.c:26:13
	move.s d2, r16
	.loc	2 26 26 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fixunsdfdi.c:26:26
	move r5, 0
	move r4, r3
	.loc	2 26 35                         // uPIMulator_frontend/sdk/syslib/fixunsdfdi.c:26:35
	move.u d0, r0
.Ltmp10:
	.loc	2 26 33                         // uPIMulator_frontend/sdk/syslib/fixunsdfdi.c:26:33
	or r17, r5, r1
	or r16, r4, r0
.Ltmp11:
.LBB0_2:
	//DEBUG_VALUE: __fixunsdfdi:a <- $d14
	.loc	2 27 1 is_stmt 1                // uPIMulator_frontend/sdk/syslib/fixunsdfdi.c:27:1
	movd d0, d16
	ld d16, r22, -24
	ld d14, r22, -16
.Ltmp12:
	ld d22, r22, -8
	jump r23
.Ltmp13:
.Lfunc_end0:
	.size	__fixunsdfdi, .Lfunc_end0-__fixunsdfdi
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__fixunsdfdi
	.long	.Lfunc_begin0
	.byte	24
	.section	.text.__fixunsdfdi,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp0-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	95                              // sub-register DW_OP_reg15
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	94                              // sub-register DW_OP_reg14
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Ltmp5-.Lfunc_begin0
	.long	.Ltmp11-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	96                              // DW_OP_reg16
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Ltmp9-.Lfunc_begin0
	.long	.Ltmp10-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.ascii	"\211\202\001"                  // DW_TAG_GNU_call_site
	.byte	0                               // DW_CHILDREN_no
	.ascii	"\223B"                         // DW_AT_GNU_call_site_target
	.byte	24                              // DW_FORM_exprloc
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0xbb DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	4                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	3                               // Abbrev [3] 0x2d:0xb DW_TAG_typedef
	.long	56                              // DW_AT_type
	.long	.Linfo_string5                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	31                              // DW_AT_decl_line
	.byte	2                               // Abbrev [2] 0x38:0x7 DW_TAG_base_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x3f:0x74 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string6                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	20                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	45                              // DW_AT_type
                                        // DW_AT_external
	.byte	5                               // Abbrev [5] 0x54:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string7                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	20                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0x63:0xf DW_TAG_variable
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	24                              // DW_AT_decl_line
	.long	179                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x72:0xf DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string11                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	25                              // DW_AT_decl_line
	.long	179                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0x81:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp1                          // DW_AT_low_pc
	.byte	7                               // Abbrev [7] 0x88:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp3                          // DW_AT_low_pc
	.byte	7                               // Abbrev [7] 0x8f:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp4                          // DW_AT_low_pc
	.byte	7                               // Abbrev [7] 0x96:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp6                          // DW_AT_low_pc
	.byte	7                               // Abbrev [7] 0x9d:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp7                          // DW_AT_low_pc
	.byte	7                               // Abbrev [7] 0xa4:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp8                          // DW_AT_low_pc
	.byte	7                               // Abbrev [7] 0xab:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp9                          // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	3                               // Abbrev [3] 0xb3:0xb DW_TAG_typedef
	.long	190                             // DW_AT_type
	.long	.Linfo_string10                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	28                              // DW_AT_decl_line
	.byte	2                               // Abbrev [2] 0xbe:0x7 DW_TAG_base_type
	.long	.Linfo_string9                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/fixunsdfdi.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=156
.Linfo_string3:
	.asciz	"double"                        // string offset=177
.Linfo_string4:
	.asciz	"long long unsigned int"        // string offset=184
.Linfo_string5:
	.asciz	"du_int"                        // string offset=207
.Linfo_string6:
	.asciz	"__fixunsdfdi"                  // string offset=214
.Linfo_string7:
	.asciz	"a"                             // string offset=227
.Linfo_string8:
	.asciz	"high"                          // string offset=229
.Linfo_string9:
	.asciz	"unsigned int"                  // string offset=234
.Linfo_string10:
	.asciz	"su_int"                        // string offset=247
.Linfo_string11:
	.asciz	"low"                           // string offset=254
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
