	.text
	.file	"floatsidf.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/stdint.h"
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/fp_lib.h"
	.section	.text.__floatsidf,"ax",@progbits
	.globl	__floatsidf                     // -- Begin function __floatsidf
	.type	__floatsidf,@function
__floatsidf:                            // @__floatsidf
.Lfunc_begin0:
	.file	3 "/root" "uPIMulator_frontend/sdk/syslib/floatsidf.c"
	.loc	3 23 0                          // uPIMulator_frontend/sdk/syslib/floatsidf.c:23:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __floatsidf:a <- $r0
	//DEBUG_VALUE: __floatsidf:a <- $r0
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: __floatsidf:aWidth <- 32
	.loc	3 28 9 prologue_end             // uPIMulator_frontend/sdk/syslib/floatsidf.c:28:9
	jeq r0, 0, .LBB0_1
.Ltmp0:
// %bb.2:
	//DEBUG_VALUE: __floatsidf:a <- $r0
	//DEBUG_VALUE: __floatsidf:aWidth <- 32
	//DEBUG_VALUE: __floatsidf:sign <- 0
	.loc	3 33 9                          // uPIMulator_frontend/sdk/syslib/floatsidf.c:33:9
	and r1, r0, -2147483648
	move.s d4, r1
	move r3, 0
	asr r1, r0, 31
	add r0, r0, r1
.Ltmp1:
	xor r6, r0, r1
.Ltmp2:
	//DEBUG_VALUE: __floatsidf:sign <- $d2
	//DEBUG_VALUE: __floatsidf:a <- $r6
	.loc	3 39 41                         // uPIMulator_frontend/sdk/syslib/floatsidf.c:39:41
	clz r0, r6
.Ltmp3:
	//DEBUG_VALUE: __floatsidf:exponent <- [DW_OP_constu 31, DW_OP_xor, DW_OP_stack_value] $r0
	.loc	3 45 39                         // uPIMulator_frontend/sdk/syslib/floatsidf.c:45:39
	add r1, r0, 21
.Ltmp4:
	//DEBUG_VALUE: __floatsidf:shift <- $r1
	.loc	3 46 14                         // uPIMulator_frontend/sdk/syslib/floatsidf.c:46:14
	move.u d6, r6
.Ltmp5:
	.loc	3 33 9                          // uPIMulator_frontend/sdk/syslib/floatsidf.c:33:9
	move r2, r5
.Ltmp6:
	.loc	3 46 37                         // uPIMulator_frontend/sdk/syslib/floatsidf.c:46:37
	lslx r4, r7, r1, sh32, .LBB0_4
.Ltmp7:
// %bb.3:
	//DEBUG_VALUE: __floatsidf:shift <- $r1
	//DEBUG_VALUE: __floatsidf:exponent <- [DW_OP_constu 31, DW_OP_xor, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __floatsidf:aWidth <- 32
	lsl r5, r6, r1
	or r4, r5, r4
	lsl r5, r7, r1, true, .LBB0_5
.Ltmp8:
.LBB0_1:
	//DEBUG_VALUE: __floatsidf:a <- $r0
	//DEBUG_VALUE: __floatsidf:aWidth <- 32
	.loc	3 0 37 is_stmt 0                // uPIMulator_frontend/sdk/syslib/floatsidf.c:0:37
	move.s d0, 0
.Ltmp9:
	.loc	3 52 1 is_stmt 1                // uPIMulator_frontend/sdk/syslib/floatsidf.c:52:1
	jump r23
.Ltmp10:
.LBB0_4:
	//DEBUG_VALUE: __floatsidf:shift <- $r1
	//DEBUG_VALUE: __floatsidf:exponent <- [DW_OP_constu 31, DW_OP_xor, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __floatsidf:aWidth <- 32
	.loc	3 46 37                         // uPIMulator_frontend/sdk/syslib/floatsidf.c:46:37
	lsl r1, r7, r1
.Ltmp11:
	movd d4, d2
	move r4, r1
.Ltmp12:
.LBB0_5:
	//DEBUG_VALUE: __floatsidf:exponent <- [DW_OP_constu 31, DW_OP_xor, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __floatsidf:aWidth <- 32
	.loc	3 46 46 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatsidf.c:46:46
	xor r5, r5, 0
	xor r4, r4, 1048576
.Ltmp13:
	//DEBUG_VALUE: __floatsidf:result <- $d4
	.loc	3 49 32 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatsidf.c:49:32
	sub r0, 1054, r0
.Ltmp14:
	.loc	3 49 15 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatsidf.c:49:15
	move.s d0, r0
	.loc	3 49 48                         // uPIMulator_frontend/sdk/syslib/floatsidf.c:49:48
	move r7, 0
	lsl r6, r1, 20
	.loc	3 49 12                         // uPIMulator_frontend/sdk/syslib/floatsidf.c:49:12
	add r1, r5, r7
	addc r0, r4, r6
.Ltmp15:
	//DEBUG_VALUE: __floatsidf:result <- $d0
	.loc	3 51 27 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatsidf.c:51:27
	or r1, r1, r3
.Ltmp16:
	or r0, r0, r2
.Ltmp17:
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $d0
	.loc	3 52 1                          // uPIMulator_frontend/sdk/syslib/floatsidf.c:52:1
	jump r23
.Ltmp18:
.Lfunc_end0:
	.size	__floatsidf, .Lfunc_end0-__floatsidf
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__floatsidf
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.__floatsidf,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp1-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp5-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	86                              // DW_OP_reg6
	.long	.Ltmp8-.Lfunc_begin0
	.long	.Ltmp9-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp2-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp6-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp8-.Lfunc_begin0
	.short	5                               // Loc expr size
	.byte	112                             // DW_OP_breg0
	.byte	0                               // 0
	.byte	79                              // DW_OP_lit31
	.byte	39                              // DW_OP_xor
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp10-.Lfunc_begin0
	.long	.Ltmp14-.Lfunc_begin0
	.short	5                               // Loc expr size
	.byte	112                             // DW_OP_breg0
	.byte	0                               // 0
	.byte	79                              // DW_OP_lit31
	.byte	39                              // DW_OP_xor
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Ltmp4-.Lfunc_begin0
	.long	.Ltmp8-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp10-.Lfunc_begin0
	.long	.Ltmp11-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc4:
	.long	.Ltmp13-.Lfunc_begin0
	.long	.Ltmp15-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp15-.Lfunc_begin0
	.long	.Ltmp16-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	28                              // DW_AT_const_value
	.byte	13                              // DW_FORM_sdata
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0xcb DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0xb DW_TAG_typedef
	.long	49                              // DW_AT_type
	.long	.Linfo_string5                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	68                              // DW_AT_decl_line
	.byte	2                               // Abbrev [2] 0x31:0xb DW_TAG_typedef
	.long	60                              // DW_AT_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	53                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x3c:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	3                               // Abbrev [3] 0x43:0x7 DW_TAG_base_type
	.long	.Linfo_string6                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x4a:0x6d DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string7                  // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	183                             // DW_AT_type
                                        // DW_AT_external
	.byte	5                               // Abbrev [5] 0x5f:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string10                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
	.long	201                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x6e:0xc DW_TAG_variable
	.byte	32                              // DW_AT_const_value
	.long	.Linfo_string12                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	25                              // DW_AT_decl_line
	.long	208                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0x7a:0xf DW_TAG_variable
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string13                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	32                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	7                               // Abbrev [7] 0x89:0xf DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string14                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	39                              // DW_AT_decl_line
	.long	208                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0x98:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string15                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	45                              // DW_AT_decl_line
	.long	208                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0xa7:0xf DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	.Linfo_string16                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	40                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	2                               // Abbrev [2] 0xb7:0xb DW_TAG_typedef
	.long	194                             // DW_AT_type
	.long	.Linfo_string9                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	70                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0xc2:0x7 DW_TAG_base_type
	.long	.Linfo_string8                  // DW_AT_name
	.byte	4                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	3                               // Abbrev [3] 0xc9:0x7 DW_TAG_base_type
	.long	.Linfo_string11                 // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	8                               // Abbrev [8] 0xd0:0x5 DW_TAG_const_type
	.long	201                             // DW_AT_type
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/floatsidf.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=155
.Linfo_string3:
	.asciz	"long unsigned int"             // string offset=176
.Linfo_string4:
	.asciz	"uint64_t"                      // string offset=194
.Linfo_string5:
	.asciz	"rep_t"                         // string offset=203
.Linfo_string6:
	.asciz	"unsigned int"                  // string offset=209
.Linfo_string7:
	.asciz	"__floatsidf"                   // string offset=222
.Linfo_string8:
	.asciz	"double"                        // string offset=234
.Linfo_string9:
	.asciz	"fp_t"                          // string offset=241
.Linfo_string10:
	.asciz	"a"                             // string offset=246
.Linfo_string11:
	.asciz	"int"                           // string offset=248
.Linfo_string12:
	.asciz	"aWidth"                        // string offset=252
.Linfo_string13:
	.asciz	"sign"                          // string offset=259
.Linfo_string14:
	.asciz	"exponent"                      // string offset=264
.Linfo_string15:
	.asciz	"shift"                         // string offset=273
.Linfo_string16:
	.asciz	"result"                        // string offset=279
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
