	.text
	.file	"floatdisf.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/syslib/int_types.h"
	.section	.text.__floatdisf,"ax",@progbits
	.globl	__floatdisf                     // -- Begin function __floatdisf
	.type	__floatdisf,@function
__floatdisf:                            // @__floatdisf
.Lfunc_begin0:
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/floatdisf.c"
	.loc	2 27 0                          // uPIMulator_frontend/sdk/syslib/floatdisf.c:27:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __floatdisf:a <- $d0
	.cfi_def_cfa_offset 0
	move.s d2, 0
	//DEBUG_VALUE: __floatdisf:a <- $d0
.Ltmp0:
	.loc	2 28 9 prologue_end             // uPIMulator_frontend/sdk/syslib/floatdisf.c:28:9
	jneq r1, r3, .LBB0_23
.Ltmp1:
// %bb.22:
	jeq r0, r2, .LBB0_1
.LBB0_23:
// %bb.2:
.Ltmp2:
	//DEBUG_VALUE: __floatdisf:a <- $d0
	//DEBUG_VALUE: __floatdisf:N <- 64
	.loc	2 31 24                         // uPIMulator_frontend/sdk/syslib/floatdisf.c:31:24
	asr.s d2, r0, 31
.Ltmp3:
	//DEBUG_VALUE: __floatdisf:s <- $d2
	.loc	2 32 12                         // uPIMulator_frontend/sdk/syslib/floatdisf.c:32:12
	xor r1, r3, r1
.Ltmp4:
	xor r0, r2, r0
	.loc	2 32 17 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatdisf.c:32:17
	sub r5, r1, r3
	subc r4, r0, r2
.Ltmp5:
	//DEBUG_VALUE: __floatdisf:a <- $d4
	.loc	2 33 18 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatdisf.c:33:18
	clz.u d6, r4, nmax, .LBB0_4
.Ltmp6:
// %bb.3:
	//DEBUG_VALUE: __floatdisf:a <- $d4
	//DEBUG_VALUE: __floatdisf:s <- $d2
	//DEBUG_VALUE: __floatdisf:N <- 64
	clz r0, r5
	add r7, r0, 32
.Ltmp7:
.LBB0_4:
	//DEBUG_VALUE: __floatdisf:a <- $d4
	//DEBUG_VALUE: __floatdisf:s <- $d2
	//DEBUG_VALUE: __floatdisf:N <- 64
	//DEBUG_VALUE: __floatdisf:sd <- undef
	.loc	2 34 16                         // uPIMulator_frontend/sdk/syslib/floatdisf.c:34:16
	xor r0, r7, 63
.Ltmp8:
	//DEBUG_VALUE: __floatdisf:e <- $r0
	.loc	2 35 9                          // uPIMulator_frontend/sdk/syslib/floatdisf.c:35:9
	jgtu r7, 39, .LBB0_17
.Ltmp9:
// %bb.5:
	//DEBUG_VALUE: __floatdisf:e <- $r0
	//DEBUG_VALUE: __floatdisf:a <- $d4
	//DEBUG_VALUE: __floatdisf:s <- $d2
	//DEBUG_VALUE: __floatdisf:N <- 64
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/floatdisf.c:0:0
	sub r1, 64, r7
.Ltmp10:
	//DEBUG_VALUE: __floatdisf:sd <- $r1
	.loc	2 44 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/floatdisf.c:44:9
	jeq r1, 26, .LBB0_15
.Ltmp11:
// %bb.6:
	//DEBUG_VALUE: __floatdisf:sd <- $r1
	//DEBUG_VALUE: __floatdisf:e <- $r0
	//DEBUG_VALUE: __floatdisf:a <- $d4
	//DEBUG_VALUE: __floatdisf:s <- $d2
	//DEBUG_VALUE: __floatdisf:N <- 64
	jneq r1, 25, .LBB0_8
.Ltmp12:
// %bb.7:
	//DEBUG_VALUE: __floatdisf:sd <- $r1
	//DEBUG_VALUE: __floatdisf:e <- $r0
	//DEBUG_VALUE: __floatdisf:a <- $d4
	//DEBUG_VALUE: __floatdisf:s <- $d2
	//DEBUG_VALUE: __floatdisf:N <- 64
	.loc	2 46 19                         // uPIMulator_frontend/sdk/syslib/floatdisf.c:46:19
	lslx r6, r5, 1
	lsl_add r4, r6, r4, 1
.Ltmp13:
	//DEBUG_VALUE: __floatdisf:a <- $d4
	lsl r5, r5, 1, true, .LBB0_15
.Ltmp14:
.LBB0_1:
	//DEBUG_VALUE: __floatdisf:a <- $d0
	.loc	2 0 19 is_stmt 0                // uPIMulator_frontend/sdk/syslib/floatdisf.c:0:19
	move r0, 0
.Ltmp15:
	.loc	2 72 1 is_stmt 1                // uPIMulator_frontend/sdk/syslib/floatdisf.c:72:1
	jump r23
.LBB0_17:
.Ltmp16:
	//DEBUG_VALUE: __floatdisf:e <- $r0
	//DEBUG_VALUE: __floatdisf:a <- $d4
	//DEBUG_VALUE: __floatdisf:s <- $d2
	//DEBUG_VALUE: __floatdisf:N <- 64
	.loc	2 64 29                         // uPIMulator_frontend/sdk/syslib/floatdisf.c:64:29
	add r1, r7, -40
	.loc	2 64 11 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatdisf.c:64:11
	lslx r6, r5, r1, sh32, .LBB0_19
.Ltmp17:
// %bb.18:
	//DEBUG_VALUE: __floatdisf:e <- $r0
	//DEBUG_VALUE: __floatdisf:a <- $d4
	//DEBUG_VALUE: __floatdisf:s <- $d2
	//DEBUG_VALUE: __floatdisf:N <- 64
	lsl r7, r4, r1
	or r6, r7, r6
.Ltmp18:
	//DEBUG_VALUE: __floatdisf:a <- $d6
	lsl r7, r5, r1, true, .LBB0_20
.Ltmp19:
.LBB0_19:
	//DEBUG_VALUE: __floatdisf:e <- $r0
	//DEBUG_VALUE: __floatdisf:a <- $d4
	//DEBUG_VALUE: __floatdisf:s <- $d2
	//DEBUG_VALUE: __floatdisf:N <- 64
	lsl r6, r5, r1
.Ltmp20:
	//DEBUG_VALUE: __floatdisf:a <- $d6
	move r7, 0, true, .LBB0_20
.Ltmp21:
.LBB0_8:
	//DEBUG_VALUE: __floatdisf:sd <- $r1
	//DEBUG_VALUE: __floatdisf:e <- $r0
	//DEBUG_VALUE: __floatdisf:a <- $d4
	//DEBUG_VALUE: __floatdisf:s <- $d2
	//DEBUG_VALUE: __floatdisf:N <- 64
	.loc	2 51 39 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatdisf.c:51:39
	sub r10, 38, r7
	.loc	2 51 32 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatdisf.c:51:32
	lsrx r8, r4, r10, sh32, .LBB0_10
.Ltmp22:
// %bb.9:
	//DEBUG_VALUE: __floatdisf:sd <- $r1
	//DEBUG_VALUE: __floatdisf:e <- $r0
	//DEBUG_VALUE: __floatdisf:a <- $d4
	//DEBUG_VALUE: __floatdisf:s <- $d2
	//DEBUG_VALUE: __floatdisf:N <- 64
	lsr r9, r5, r10
	or r9, r8, r9
	lsr r8, r4, r10
	.loc	2 51 111                        // uPIMulator_frontend/sdk/syslib/floatdisf.c:51:111
	add r10, r7, 26
	.loc	2 51 119                        // uPIMulator_frontend/sdk/syslib/floatdisf.c:51:119
	lslx r6, r5, r10, sh32, .LBB0_13
	jump .LBB0_12
.Ltmp23:
.LBB0_13:
	//DEBUG_VALUE: __floatdisf:sd <- $r1
	//DEBUG_VALUE: __floatdisf:e <- $r0
	//DEBUG_VALUE: __floatdisf:a <- $d4
	//DEBUG_VALUE: __floatdisf:s <- $d2
	//DEBUG_VALUE: __floatdisf:N <- 64
	lsl r6, r5, r10
	move r7, 0, true, .LBB0_14
.Ltmp24:
.LBB0_10:
	//DEBUG_VALUE: __floatdisf:sd <- $r1
	//DEBUG_VALUE: __floatdisf:e <- $r0
	//DEBUG_VALUE: __floatdisf:a <- $d4
	//DEBUG_VALUE: __floatdisf:s <- $d2
	//DEBUG_VALUE: __floatdisf:N <- 64
	.loc	2 51 32                         // uPIMulator_frontend/sdk/syslib/floatdisf.c:51:32
	lsr.u d8, r4, r10
	.loc	2 51 111                        // uPIMulator_frontend/sdk/syslib/floatdisf.c:51:111
	add r10, r7, 26
	.loc	2 51 119                        // uPIMulator_frontend/sdk/syslib/floatdisf.c:51:119
	lslx r6, r5, r10, sh32, .LBB0_13
.Ltmp25:
.LBB0_12:
	//DEBUG_VALUE: __floatdisf:sd <- $r1
	//DEBUG_VALUE: __floatdisf:e <- $r0
	//DEBUG_VALUE: __floatdisf:a <- $d4
	//DEBUG_VALUE: __floatdisf:s <- $d2
	//DEBUG_VALUE: __floatdisf:N <- 64
	lsl r7, r4, r10
	or r6, r7, r6
	lsl r7, r5, r10
.Ltmp26:
.LBB0_14:
	//DEBUG_VALUE: __floatdisf:sd <- $r1
	//DEBUG_VALUE: __floatdisf:e <- $r0
	//DEBUG_VALUE: __floatdisf:a <- $d4
	//DEBUG_VALUE: __floatdisf:s <- $d2
	//DEBUG_VALUE: __floatdisf:N <- 64
	.loc	2 0 119                         // uPIMulator_frontend/sdk/syslib/floatdisf.c:0:119
	move.s d4, 0
.Ltmp27:
	.loc	2 51 119                        // uPIMulator_frontend/sdk/syslib/floatdisf.c:51:119
	sub zero, r7, r5
	subc r4, r6, r4, xnz
	.loc	2 51 64                         // uPIMulator_frontend/sdk/syslib/floatdisf.c:51:64
	move.u d4, r4
	.loc	2 51 62                         // uPIMulator_frontend/sdk/syslib/floatdisf.c:51:62
	or r5, r9, r5
	or r4, r8, r4
.Ltmp28:
	//DEBUG_VALUE: __floatdisf:a <- $d4
.LBB0_15:
	//DEBUG_VALUE: __floatdisf:sd <- $r1
	//DEBUG_VALUE: __floatdisf:e <- $r0
	//DEBUG_VALUE: __floatdisf:s <- $d2
	//DEBUG_VALUE: __floatdisf:N <- 64
	//DEBUG_VALUE: __floatdisf:a <- $d4
	.loc	2 54 22 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatdisf.c:54:22
	lsrx r6, r4, 2
	lsr_add r7, r6, r5, 2
	lsr r6, r4, 2
	.loc	2 54 14 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatdisf.c:54:14
	and r7, r7, 1
	and r6, r6, 0
	.loc	2 54 11                         // uPIMulator_frontend/sdk/syslib/floatdisf.c:54:11
	or r5, r7, r5
.Ltmp29:
	or r4, r6, r4
.Ltmp30:
	//DEBUG_VALUE: __floatdisf:a <- $d4
	.loc	2 55 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/floatdisf.c:55:9
	add r5, r5, 1
.Ltmp31:
	addc r4, r4, 0
.Ltmp32:
	//DEBUG_VALUE: __floatdisf:a <- $d4
	.loc	2 56 11                         // uPIMulator_frontend/sdk/syslib/floatdisf.c:56:11
	lsrx r6, r4, 2
	lsr_add r7, r6, r5, 2
.Ltmp33:
	.loc	2 58 15                         // uPIMulator_frontend/sdk/syslib/floatdisf.c:58:15
	and r9, r5, 67108864
	and r8, r4, 0
	move.s d10, 0
.Ltmp34:
	.loc	2 56 11                         // uPIMulator_frontend/sdk/syslib/floatdisf.c:56:11
	asr r6, r4, 2
.Ltmp35:
	//DEBUG_VALUE: __floatdisf:a <- $d6
	.loc	2 58 13                         // uPIMulator_frontend/sdk/syslib/floatdisf.c:58:13
	jneq r9, r11, .LBB0_25
.Ltmp36:
// %bb.24:
	jeq r8, r10, .LBB0_20
.LBB0_25:
// %bb.16:
.Ltmp37:
	//DEBUG_VALUE: __floatdisf:sd <- $r1
	//DEBUG_VALUE: __floatdisf:e <- $r0
	//DEBUG_VALUE: __floatdisf:a <- $d6
	//DEBUG_VALUE: __floatdisf:s <- $d2
	//DEBUG_VALUE: __floatdisf:N <- 64
	.loc	2 59 15                         // uPIMulator_frontend/sdk/syslib/floatdisf.c:59:15
	lsrx r0, r6, 1
.Ltmp38:
	lsr_add r7, r0, r7, 1
.Ltmp39:
	lsr r6, r6, 1
.Ltmp40:
	//DEBUG_VALUE: __floatdisf:e <- $r1
	//DEBUG_VALUE: __floatdisf:a <- [DW_OP_constu 1, DW_OP_shra, DW_OP_stack_value] $d6
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/floatdisf.c:0:0
	move r0, r1
.Ltmp41:
	//DEBUG_VALUE: __floatdisf:e <- $r0
.LBB0_20:
	//DEBUG_VALUE: __floatdisf:e <- $r0
	//DEBUG_VALUE: __floatdisf:s <- $d2
	//DEBUG_VALUE: __floatdisf:N <- 64
	//DEBUG_VALUE: __floatdisf:a <- undef
	//DEBUG_VALUE: __floatdisf:e <- $r0
	.loc	2 68 23 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatdisf.c:68:23
	and r1, r3, -2147483648
	move r2, 1065353216
.Ltmp42:
	.loc	2 69 20                         // uPIMulator_frontend/sdk/syslib/floatdisf.c:69:20
	lsl_add r0, r2, r0, 23
.Ltmp43:
	.loc	2 70 20                         // uPIMulator_frontend/sdk/syslib/floatdisf.c:70:20
	and r2, r7, 8388607
	.loc	2 68 37                         // uPIMulator_frontend/sdk/syslib/floatdisf.c:68:37
	or r1, r2, r1
	.loc	2 69 27                         // uPIMulator_frontend/sdk/syslib/floatdisf.c:69:27
	or r0, r1, r0
.Ltmp44:
	//DEBUG_VALUE: __floatdisf:fb <- $r0
	.loc	2 72 1                          // uPIMulator_frontend/sdk/syslib/floatdisf.c:72:1
	jump r23
.Ltmp45:
.Lfunc_end0:
	.size	__floatdisf, .Lfunc_end0-__floatdisf
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__floatdisf
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.__floatdisf,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp1-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp4-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp5-.Lfunc_begin0
	.long	.Ltmp14-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Ltmp15-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp16-.Lfunc_begin0
	.long	.Ltmp18-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp18-.Lfunc_begin0
	.long	.Ltmp19-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp19-.Lfunc_begin0
	.long	.Ltmp20-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp20-.Lfunc_begin0
	.long	.Ltmp21-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp21-.Lfunc_begin0
	.long	.Ltmp27-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp28-.Lfunc_begin0
	.long	.Ltmp29-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp30-.Lfunc_begin0
	.long	.Ltmp31-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp32-.Lfunc_begin0
	.long	.Ltmp35-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp35-.Lfunc_begin0
	.long	.Ltmp36-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp37-.Lfunc_begin0
	.long	.Ltmp39-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp14-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	64                              // 64
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp16-.Lfunc_begin0
	.long	.Ltmp36-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	64                              // 64
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp37-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	64                              // 64
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp14-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp16-.Lfunc_begin0
	.long	.Ltmp36-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp37-.Lfunc_begin0
	.long	.Ltmp42-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Ltmp10-.Lfunc_begin0
	.long	.Ltmp14-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp21-.Lfunc_begin0
	.long	.Ltmp36-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp37-.Lfunc_begin0
	.long	.Ltmp41-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc4:
	.long	.Ltmp8-.Lfunc_begin0
	.long	.Ltmp14-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp16-.Lfunc_begin0
	.long	.Ltmp36-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp37-.Lfunc_begin0
	.long	.Ltmp38-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp40-.Lfunc_begin0
	.long	.Ltmp41-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp41-.Lfunc_begin0
	.long	.Ltmp43-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc5:
	.long	.Ltmp44-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	23                              // DW_TAG_union_type
	.byte	1                               // DW_CHILDREN_yes
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	13                              // DW_TAG_member
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	56                              // DW_AT_data_member_location
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x102 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0xb DW_TAG_typedef
	.long	49                              // DW_AT_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	31                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x31:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	2                               // Abbrev [2] 0x38:0xb DW_TAG_typedef
	.long	67                              // DW_AT_type
	.long	.Linfo_string6                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	28                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x43:0x7 DW_TAG_base_type
	.long	.Linfo_string5                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x4a:0x70 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string7                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	26                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	186                             // DW_AT_type
                                        // DW_AT_external
	.byte	5                               // Abbrev [5] 0x5f:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string9                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	26                              // DW_AT_decl_line
	.long	193                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x6e:0xf DW_TAG_variable
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string12                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	30                              // DW_AT_decl_line
	.long	211                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x7d:0xf DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string13                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	31                              // DW_AT_decl_line
	.long	216                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x8c:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string14                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	33                              // DW_AT_decl_line
	.long	221                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x9b:0xf DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	.Linfo_string16                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	34                              // DW_AT_decl_line
	.long	221                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xaa:0xf DW_TAG_variable
	.long	.Ldebug_loc5                    // DW_AT_location
	.long	.Linfo_string17                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	67                              // DW_AT_decl_line
	.long	228                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	3                               // Abbrev [3] 0xba:0x7 DW_TAG_base_type
	.long	.Linfo_string8                  // DW_AT_name
	.byte	4                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	2                               // Abbrev [2] 0xc1:0xb DW_TAG_typedef
	.long	204                             // DW_AT_type
	.long	.Linfo_string11                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	30                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0xcc:0x7 DW_TAG_base_type
	.long	.Linfo_string10                 // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	7                               // Abbrev [7] 0xd3:0x5 DW_TAG_const_type
	.long	67                              // DW_AT_type
	.byte	7                               // Abbrev [7] 0xd8:0x5 DW_TAG_const_type
	.long	193                             // DW_AT_type
	.byte	3                               // Abbrev [3] 0xdd:0x7 DW_TAG_base_type
	.long	.Linfo_string15                 // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	2                               // Abbrev [2] 0xe4:0xb DW_TAG_typedef
	.long	239                             // DW_AT_type
	.long	.Linfo_string20                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	116                             // DW_AT_decl_line
	.byte	8                               // Abbrev [8] 0xef:0x1d DW_TAG_union_type
	.byte	4                               // DW_AT_byte_size
	.byte	1                               // DW_AT_decl_file
	.byte	113                             // DW_AT_decl_line
	.byte	9                               // Abbrev [9] 0xf3:0xc DW_TAG_member
	.long	.Linfo_string18                 // DW_AT_name
	.long	56                              // DW_AT_type
	.byte	1                               // DW_AT_decl_file
	.byte	114                             // DW_AT_decl_line
	.byte	0                               // DW_AT_data_member_location
	.byte	9                               // Abbrev [9] 0xff:0xc DW_TAG_member
	.long	.Linfo_string19                 // DW_AT_name
	.long	186                             // DW_AT_type
	.byte	1                               // DW_AT_decl_file
	.byte	115                             // DW_AT_decl_line
	.byte	0                               // DW_AT_data_member_location
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/floatdisf.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=155
.Linfo_string3:
	.asciz	"long long unsigned int"        // string offset=176
.Linfo_string4:
	.asciz	"du_int"                        // string offset=199
.Linfo_string5:
	.asciz	"unsigned int"                  // string offset=206
.Linfo_string6:
	.asciz	"su_int"                        // string offset=219
.Linfo_string7:
	.asciz	"__floatdisf"                   // string offset=226
.Linfo_string8:
	.asciz	"float"                         // string offset=238
.Linfo_string9:
	.asciz	"a"                             // string offset=244
.Linfo_string10:
	.asciz	"long long int"                 // string offset=246
.Linfo_string11:
	.asciz	"di_int"                        // string offset=260
.Linfo_string12:
	.asciz	"N"                             // string offset=267
.Linfo_string13:
	.asciz	"s"                             // string offset=269
.Linfo_string14:
	.asciz	"sd"                            // string offset=271
.Linfo_string15:
	.asciz	"int"                           // string offset=274
.Linfo_string16:
	.asciz	"e"                             // string offset=278
.Linfo_string17:
	.asciz	"fb"                            // string offset=280
.Linfo_string18:
	.asciz	"u"                             // string offset=283
.Linfo_string19:
	.asciz	"f"                             // string offset=285
.Linfo_string20:
	.asciz	"float_bits"                    // string offset=287
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
