	.text
	.file	"floatunsisf.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/stdint.h"
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/fp_lib.h"
	.section	.text.__floatunsisf,"ax",@progbits
	.globl	__floatunsisf                   // -- Begin function __floatunsisf
	.type	__floatunsisf,@function
__floatunsisf:                          // @__floatunsisf
.Lfunc_begin0:
	.file	3 "/root" "uPIMulator_frontend/sdk/syslib/floatunsisf.c"
	.loc	3 23 0                          // uPIMulator_frontend/sdk/syslib/floatunsisf.c:23:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __floatunsisf:a <- $r0
	//DEBUG_VALUE: __floatunsisf:a <- $r0
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: __floatunsisf:aWidth <- 32
	.loc	3 28 9 prologue_end             // uPIMulator_frontend/sdk/syslib/floatunsisf.c:28:9
	jeq r0, 0, .LBB0_1
.Ltmp0:
// %bb.2:
	//DEBUG_VALUE: __floatunsisf:a <- $r0
	//DEBUG_VALUE: __floatunsisf:aWidth <- 32
	.loc	3 32 41                         // uPIMulator_frontend/sdk/syslib/floatunsisf.c:32:41
	clz r1, r0
	.loc	3 32 39 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatunsisf.c:32:39
	xor r2, r1, 31
.Ltmp1:
	//DEBUG_VALUE: __floatunsisf:exponent <- $r2
	.loc	3 36 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/floatunsisf.c:36:9
	jgtu r2, 23, .LBB0_4
.Ltmp2:
// %bb.3:
	//DEBUG_VALUE: __floatunsisf:exponent <- $r2
	//DEBUG_VALUE: __floatunsisf:a <- $r0
	//DEBUG_VALUE: __floatunsisf:aWidth <- 32
	.loc	3 37 43                         // uPIMulator_frontend/sdk/syslib/floatunsisf.c:37:43
	sub r2, 23, r2
.Ltmp3:
	//DEBUG_VALUE: shift <- $r2
	.loc	3 38 27                         // uPIMulator_frontend/sdk/syslib/floatunsisf.c:38:27
	lsl r0, r0, r2
.Ltmp4:
	.loc	3 38 36 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatunsisf.c:38:36
	xor r0, r0, 8388608
.Ltmp5:
	//DEBUG_VALUE: __floatunsisf:result <- $r0
	//DEBUG_VALUE: __floatunsisf:result <- $r0
	.loc	3 50 48 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatunsisf.c:50:48
	lsl_sub r0, r0, r1, 23
.Ltmp6:
	.loc	3 50 12 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatunsisf.c:50:12
	add r0, r0, 1325400064
.Ltmp7:
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $r0
	//DEBUG_VALUE: __floatunsisf:result <- $r0
	.loc	3 52 1 is_stmt 1                // uPIMulator_frontend/sdk/syslib/floatunsisf.c:52:1
	jump r23
.Ltmp8:
.LBB0_1:
	//DEBUG_VALUE: __floatunsisf:a <- $r0
	//DEBUG_VALUE: __floatunsisf:aWidth <- 32
	.loc	3 0 1 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/floatunsisf.c:0:1
	move r0, 0
.Ltmp9:
	.loc	3 52 1                          // uPIMulator_frontend/sdk/syslib/floatunsisf.c:52:1
	jump r23
.Ltmp10:
.LBB0_4:
	//DEBUG_VALUE: __floatunsisf:exponent <- $r2
	//DEBUG_VALUE: __floatunsisf:a <- $r0
	//DEBUG_VALUE: __floatunsisf:aWidth <- 32
	.loc	3 40 36 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatunsisf.c:40:36
	sub r2, 8, r1
.Ltmp11:
	//DEBUG_VALUE: shift <- $r2
	.loc	3 41 27                         // uPIMulator_frontend/sdk/syslib/floatunsisf.c:41:27
	lsr r2, r0, r2
.Ltmp12:
	.loc	3 41 36 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatunsisf.c:41:36
	xor r2, r2, 8388608
.Ltmp13:
	//DEBUG_VALUE: __floatunsisf:result <- $r2
	.loc	3 42 46 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatunsisf.c:42:46
	add r3, r1, 24
	.loc	3 42 32 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatunsisf.c:42:32
	lsl r3, r0, r3
.Ltmp14:
	//DEBUG_VALUE: round <- $r3
	.loc	3 0 32                          // uPIMulator_frontend/sdk/syslib/floatunsisf.c:0:32
	move r4, -2147483648
.Ltmp15:
	.loc	3 43 19 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatunsisf.c:43:19
	sub r0, r3, r4, gtu
.Ltmp16:
	.loc	3 43 13 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatunsisf.c:43:13
	add r0, r2, r0
.Ltmp17:
	//DEBUG_VALUE: __floatunsisf:result <- $r0
	.loc	3 45 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatunsisf.c:45:13
	and r2, r0, 1
	jeq r3, r4, .LBB0_6
.Ltmp18:
// %bb.5:
	//DEBUG_VALUE: round <- $r3
	//DEBUG_VALUE: __floatunsisf:result <- $r0
	//DEBUG_VALUE: __floatunsisf:aWidth <- 32
	.loc	3 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/floatunsisf.c:0:13
	move r2, 0
.Ltmp19:
.LBB0_6:
	//DEBUG_VALUE: round <- $r3
	//DEBUG_VALUE: __floatunsisf:result <- $r0
	//DEBUG_VALUE: __floatunsisf:aWidth <- 32
	.loc	3 45 13                         // uPIMulator_frontend/sdk/syslib/floatunsisf.c:45:13
	add r0, r2, r0
.Ltmp20:
	//DEBUG_VALUE: __floatunsisf:result <- $r0
	.loc	3 50 48 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatunsisf.c:50:48
	lsl_sub r0, r0, r1, 23
.Ltmp21:
	.loc	3 50 12 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatunsisf.c:50:12
	add r0, r0, 1325400064
.Ltmp22:
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $r0
	//DEBUG_VALUE: __floatunsisf:result <- $r0
	.loc	3 52 1 is_stmt 1                // uPIMulator_frontend/sdk/syslib/floatunsisf.c:52:1
	jump r23
.Ltmp23:
.Lfunc_end0:
	.size	__floatunsisf, .Lfunc_end0-__floatunsisf
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__floatunsisf
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.__floatunsisf,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp4-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp8-.Lfunc_begin0
	.long	.Ltmp9-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp10-.Lfunc_begin0
	.long	.Ltmp16-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Ltmp1-.Lfunc_begin0
	.long	.Ltmp3-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp10-.Lfunc_begin0
	.long	.Ltmp11-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp8-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Ltmp5-.Lfunc_begin0
	.long	.Ltmp6-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp7-.Lfunc_begin0
	.long	.Ltmp8-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp13-.Lfunc_begin0
	.long	.Ltmp17-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp17-.Lfunc_begin0
	.long	.Ltmp21-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp22-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc4:
	.long	.Ltmp11-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc5:
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	28                              // DW_AT_const_value
	.byte	13                              // DW_FORM_sdata
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0xe7 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0xb DW_TAG_typedef
	.long	49                              // DW_AT_type
	.long	.Linfo_string5                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	43                              // DW_AT_decl_line
	.byte	2                               // Abbrev [2] 0x31:0xb DW_TAG_typedef
	.long	60                              // DW_AT_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	48                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x3c:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x43:0x90 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string6                  // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	211                             // DW_AT_type
                                        // DW_AT_external
	.byte	5                               // Abbrev [5] 0x58:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string9                  // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
	.long	60                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0x67:0xc DW_TAG_variable
	.byte	32                              // DW_AT_const_value
	.long	.Linfo_string10                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	25                              // DW_AT_decl_line
	.long	229                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0x73:0xf DW_TAG_variable
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string12                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	32                              // DW_AT_decl_line
	.long	229                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0x82:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string14                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	33                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0x91:0x19 DW_TAG_lexical_block
	.long	.Ltmp2                          // DW_AT_low_pc
	.long	.Ltmp5-.Ltmp2                   // DW_AT_high_pc
	.byte	7                               // Abbrev [7] 0x9a:0xf DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string13                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	37                              // DW_AT_decl_line
	.long	229                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	8                               // Abbrev [8] 0xaa:0x28 DW_TAG_lexical_block
	.long	.Ltmp10                         // DW_AT_low_pc
	.long	.Ltmp20-.Ltmp10                 // DW_AT_high_pc
	.byte	7                               // Abbrev [7] 0xb3:0xf DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	.Linfo_string13                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	40                              // DW_AT_decl_line
	.long	229                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0xc2:0xf DW_TAG_variable
	.long	.Ldebug_loc5                    // DW_AT_location
	.long	.Linfo_string15                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	42                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	2                               // Abbrev [2] 0xd3:0xb DW_TAG_typedef
	.long	222                             // DW_AT_type
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	45                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0xde:0x7 DW_TAG_base_type
	.long	.Linfo_string7                  // DW_AT_name
	.byte	4                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	9                               // Abbrev [9] 0xe5:0x5 DW_TAG_const_type
	.long	234                             // DW_AT_type
	.byte	3                               // Abbrev [3] 0xea:0x7 DW_TAG_base_type
	.long	.Linfo_string11                 // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/floatunsisf.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=157
.Linfo_string3:
	.asciz	"unsigned int"                  // string offset=178
.Linfo_string4:
	.asciz	"uint32_t"                      // string offset=191
.Linfo_string5:
	.asciz	"rep_t"                         // string offset=200
.Linfo_string6:
	.asciz	"__floatunsisf"                 // string offset=206
.Linfo_string7:
	.asciz	"float"                         // string offset=220
.Linfo_string8:
	.asciz	"fp_t"                          // string offset=226
.Linfo_string9:
	.asciz	"a"                             // string offset=231
.Linfo_string10:
	.asciz	"aWidth"                        // string offset=233
.Linfo_string11:
	.asciz	"int"                           // string offset=240
.Linfo_string12:
	.asciz	"exponent"                      // string offset=244
.Linfo_string13:
	.asciz	"shift"                         // string offset=253
.Linfo_string14:
	.asciz	"result"                        // string offset=259
.Linfo_string15:
	.asciz	"round"                         // string offset=266
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
