	.text
	.file	"floatundisf.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/syslib/int_types.h"
	.section	.text.__floatundisf,"ax",@progbits
	.globl	__floatundisf                   // -- Begin function __floatundisf
	.type	__floatundisf,@function
__floatundisf:                          // @__floatundisf
.Lfunc_begin0:
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/floatundisf.c"
	.loc	2 27 0                          // uPIMulator_frontend/sdk/syslib/floatundisf.c:27:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __floatundisf:a <- $d0
	.cfi_def_cfa_offset 0
	move.s d2, 0
	//DEBUG_VALUE: __floatundisf:a <- $d0
.Ltmp0:
	.loc	2 28 9 prologue_end             // uPIMulator_frontend/sdk/syslib/floatundisf.c:28:9
	jneq r1, r3, .LBB0_24
.Ltmp1:
// %bb.23:
	jeq r0, r2, .LBB0_1
.LBB0_24:
// %bb.2:
.Ltmp2:
	//DEBUG_VALUE: __floatundisf:a <- $d0
	//DEBUG_VALUE: __floatundisf:N <- 64
	.loc	2 31 18                         // uPIMulator_frontend/sdk/syslib/floatundisf.c:31:18
	clz.u d4, r0, nmax, .LBB0_4
.Ltmp3:
// %bb.3:
	//DEBUG_VALUE: __floatundisf:a <- $d0
	//DEBUG_VALUE: __floatundisf:N <- 64
	clz r2, r1
	add r5, r2, 32
.Ltmp4:
.LBB0_4:
	//DEBUG_VALUE: __floatundisf:a <- $d0
	//DEBUG_VALUE: __floatundisf:N <- 64
	//DEBUG_VALUE: __floatundisf:sd <- undef
	.loc	2 32 16                         // uPIMulator_frontend/sdk/syslib/floatundisf.c:32:16
	xor r2, r5, 63
.Ltmp5:
	//DEBUG_VALUE: __floatundisf:e <- $r2
	.loc	2 33 9                          // uPIMulator_frontend/sdk/syslib/floatundisf.c:33:9
	jgtu r5, 39, .LBB0_18
.Ltmp6:
// %bb.5:
	//DEBUG_VALUE: __floatundisf:e <- $r2
	//DEBUG_VALUE: __floatundisf:a <- $d0
	//DEBUG_VALUE: __floatundisf:N <- 64
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/floatundisf.c:0:0
	sub r3, 64, r5
.Ltmp7:
	//DEBUG_VALUE: __floatundisf:sd <- $r3
	.loc	2 42 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/floatundisf.c:42:9
	jeq r3, 26, .LBB0_15
.Ltmp8:
// %bb.6:
	//DEBUG_VALUE: __floatundisf:sd <- $r3
	//DEBUG_VALUE: __floatundisf:e <- $r2
	//DEBUG_VALUE: __floatundisf:a <- $d0
	//DEBUG_VALUE: __floatundisf:N <- 64
	jneq r3, 25, .LBB0_8
.Ltmp9:
// %bb.7:
	//DEBUG_VALUE: __floatundisf:sd <- $r3
	//DEBUG_VALUE: __floatundisf:e <- $r2
	//DEBUG_VALUE: __floatundisf:a <- $d0
	//DEBUG_VALUE: __floatundisf:N <- 64
	.loc	2 44 19                         // uPIMulator_frontend/sdk/syslib/floatundisf.c:44:19
	lslx r4, r1, 1
	lsl_add r0, r4, r0, 1
.Ltmp10:
	//DEBUG_VALUE: __floatundisf:a <- $d0
	lsl r1, r1, 1, true, .LBB0_15
.Ltmp11:
.LBB0_1:
	//DEBUG_VALUE: __floatundisf:a <- $d0
	.loc	2 0 19 is_stmt 0                // uPIMulator_frontend/sdk/syslib/floatundisf.c:0:19
	move r0, 0
.Ltmp12:
	.loc	2 69 1 is_stmt 1                // uPIMulator_frontend/sdk/syslib/floatundisf.c:69:1
	jump r23
.LBB0_18:
.Ltmp13:
	//DEBUG_VALUE: __floatundisf:e <- $r2
	//DEBUG_VALUE: __floatundisf:a <- $d0
	//DEBUG_VALUE: __floatundisf:N <- 64
	.loc	2 62 29                         // uPIMulator_frontend/sdk/syslib/floatundisf.c:62:29
	add r3, r5, -40
	.loc	2 62 11 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatundisf.c:62:11
	lslx r4, r1, r3, sh32, .LBB0_20
.Ltmp14:
// %bb.19:
	//DEBUG_VALUE: __floatundisf:e <- $r2
	//DEBUG_VALUE: __floatundisf:a <- $d0
	//DEBUG_VALUE: __floatundisf:N <- 64
	lsl r5, r0, r3
	or r4, r5, r4
	lsl r5, r1, r3
.Ltmp15:
	//DEBUG_VALUE: __floatundisf:a <- $d4
	//DEBUG_VALUE: __floatundisf:a <- undef
	//DEBUG_VALUE: __floatundisf:e <- $r2
	.loc	2 67 20 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatundisf.c:67:20
	and r0, r5, 8388607
	.loc	2 66 23                         // uPIMulator_frontend/sdk/syslib/floatundisf.c:66:23
	lsl_add r0, r0, r2, 23
	.loc	2 66 30 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatundisf.c:66:30
	add r0, r0, 1065353216
.Ltmp16:
	//DEBUG_VALUE: __floatundisf:fb <- $r0
	.loc	2 69 1 is_stmt 1                // uPIMulator_frontend/sdk/syslib/floatundisf.c:69:1
	jump r23
.Ltmp17:
.LBB0_20:
	//DEBUG_VALUE: __floatundisf:e <- $r2
	//DEBUG_VALUE: __floatundisf:a <- $d0
	//DEBUG_VALUE: __floatundisf:N <- 64
	.loc	2 62 11                         // uPIMulator_frontend/sdk/syslib/floatundisf.c:62:11
	lsl r4, r1, r3
	move r5, 0
.Ltmp18:
	//DEBUG_VALUE: __floatundisf:a <- $d4
	//DEBUG_VALUE: __floatundisf:a <- undef
	//DEBUG_VALUE: __floatundisf:e <- $r2
	.loc	2 67 20                         // uPIMulator_frontend/sdk/syslib/floatundisf.c:67:20
	and r0, r5, 8388607
	.loc	2 66 23                         // uPIMulator_frontend/sdk/syslib/floatundisf.c:66:23
	lsl_add r0, r0, r2, 23
	.loc	2 66 30 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatundisf.c:66:30
	add r0, r0, 1065353216
.Ltmp19:
	//DEBUG_VALUE: __floatundisf:fb <- $r0
	.loc	2 69 1 is_stmt 1                // uPIMulator_frontend/sdk/syslib/floatundisf.c:69:1
	jump r23
.Ltmp20:
.LBB0_8:
	//DEBUG_VALUE: __floatundisf:sd <- $r3
	//DEBUG_VALUE: __floatundisf:e <- $r2
	//DEBUG_VALUE: __floatundisf:a <- $d0
	//DEBUG_VALUE: __floatundisf:N <- 64
	.loc	2 49 31                         // uPIMulator_frontend/sdk/syslib/floatundisf.c:49:31
	sub r8, 38, r5
	.loc	2 49 24 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatundisf.c:49:24
	lsrx r6, r0, r8, sh32, .LBB0_10
.Ltmp21:
// %bb.9:
	//DEBUG_VALUE: __floatundisf:sd <- $r3
	//DEBUG_VALUE: __floatundisf:e <- $r2
	//DEBUG_VALUE: __floatundisf:a <- $d0
	//DEBUG_VALUE: __floatundisf:N <- 64
	lsr r7, r1, r8
	or r7, r6, r7
	lsr r6, r0, r8
	.loc	2 49 103                        // uPIMulator_frontend/sdk/syslib/floatundisf.c:49:103
	add r8, r5, 26
	.loc	2 49 111                        // uPIMulator_frontend/sdk/syslib/floatundisf.c:49:111
	lslx r4, r1, r8, sh32, .LBB0_13
	jump .LBB0_12
.Ltmp22:
.LBB0_13:
	//DEBUG_VALUE: __floatundisf:sd <- $r3
	//DEBUG_VALUE: __floatundisf:e <- $r2
	//DEBUG_VALUE: __floatundisf:a <- $d0
	//DEBUG_VALUE: __floatundisf:N <- 64
	lsl r4, r1, r8
	move r5, 0, true, .LBB0_14
.Ltmp23:
.LBB0_10:
	//DEBUG_VALUE: __floatundisf:sd <- $r3
	//DEBUG_VALUE: __floatundisf:e <- $r2
	//DEBUG_VALUE: __floatundisf:a <- $d0
	//DEBUG_VALUE: __floatundisf:N <- 64
	.loc	2 49 24                         // uPIMulator_frontend/sdk/syslib/floatundisf.c:49:24
	lsr.u d6, r0, r8
	.loc	2 49 103                        // uPIMulator_frontend/sdk/syslib/floatundisf.c:49:103
	add r8, r5, 26
	.loc	2 49 111                        // uPIMulator_frontend/sdk/syslib/floatundisf.c:49:111
	lslx r4, r1, r8, sh32, .LBB0_13
.Ltmp24:
.LBB0_12:
	//DEBUG_VALUE: __floatundisf:sd <- $r3
	//DEBUG_VALUE: __floatundisf:e <- $r2
	//DEBUG_VALUE: __floatundisf:a <- $d0
	//DEBUG_VALUE: __floatundisf:N <- 64
	lsl r5, r0, r8
	or r4, r5, r4
	lsl r5, r1, r8
.Ltmp25:
.LBB0_14:
	//DEBUG_VALUE: __floatundisf:sd <- $r3
	//DEBUG_VALUE: __floatundisf:e <- $r2
	//DEBUG_VALUE: __floatundisf:a <- $d0
	//DEBUG_VALUE: __floatundisf:N <- 64
	.loc	2 0 111                         // uPIMulator_frontend/sdk/syslib/floatundisf.c:0:111
	move.s d0, 0
.Ltmp26:
	.loc	2 49 111                        // uPIMulator_frontend/sdk/syslib/floatundisf.c:49:111
	sub zero, r5, r1
	subc r0, r4, r0, xnz
	.loc	2 49 56                         // uPIMulator_frontend/sdk/syslib/floatundisf.c:49:56
	move.u d0, r0
	.loc	2 49 54                         // uPIMulator_frontend/sdk/syslib/floatundisf.c:49:54
	or r1, r7, r1
	or r0, r6, r0
.Ltmp27:
	//DEBUG_VALUE: __floatundisf:a <- $d0
.LBB0_15:
	//DEBUG_VALUE: __floatundisf:sd <- $r3
	//DEBUG_VALUE: __floatundisf:e <- $r2
	//DEBUG_VALUE: __floatundisf:N <- 64
	//DEBUG_VALUE: __floatundisf:a <- $d0
	.loc	2 52 22 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatundisf.c:52:22
	lsrx r4, r0, 2
	lsr_add r5, r4, r1, 2
	lsr r4, r0, 2
	.loc	2 52 14 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatundisf.c:52:14
	and r5, r5, 1
	and r4, r4, 0
	.loc	2 52 11                         // uPIMulator_frontend/sdk/syslib/floatundisf.c:52:11
	or r1, r5, r1
.Ltmp28:
	or r0, r4, r0
.Ltmp29:
	//DEBUG_VALUE: __floatundisf:a <- $d0
	.loc	2 53 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/floatundisf.c:53:9
	add r1, r1, 1
.Ltmp30:
	addc r0, r0, 0
.Ltmp31:
	//DEBUG_VALUE: __floatundisf:a <- undef
	.loc	2 56 15                         // uPIMulator_frontend/sdk/syslib/floatundisf.c:56:15
	and r5, r1, 67108864
	and r4, r0, 0
	move.s d6, 0
.Ltmp32:
	.loc	2 56 13 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatundisf.c:56:13
	jneq r5, r7, .LBB0_17
.Ltmp33:
// %bb.25:
	jneq r4, r6, .LBB0_17
.Ltmp34:
// %bb.26:
// %bb.16:
	//DEBUG_VALUE: __floatundisf:sd <- $r3
	//DEBUG_VALUE: __floatundisf:e <- $r2
	//DEBUG_VALUE: __floatundisf:N <- 64
	.loc	2 0 13                          // uPIMulator_frontend/sdk/syslib/floatundisf.c:0:13
	lsrx r3, r0, 2
.Ltmp35:
	lsr_add r5, r3, r1, 2
	lsr r4, r0, 2
.Ltmp36:
	//DEBUG_VALUE: __floatundisf:a <- $d4
	//DEBUG_VALUE: __floatundisf:a <- undef
	//DEBUG_VALUE: __floatundisf:e <- $r2
	.loc	2 67 20 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatundisf.c:67:20
	and r0, r5, 8388607
	.loc	2 66 23                         // uPIMulator_frontend/sdk/syslib/floatundisf.c:66:23
	lsl_add r0, r0, r2, 23
	.loc	2 66 30 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatundisf.c:66:30
	add r0, r0, 1065353216
.Ltmp37:
	//DEBUG_VALUE: __floatundisf:fb <- $r0
	.loc	2 69 1 is_stmt 1                // uPIMulator_frontend/sdk/syslib/floatundisf.c:69:1
	jump r23
.Ltmp38:
.LBB0_17:
	//DEBUG_VALUE: __floatundisf:sd <- $r3
	//DEBUG_VALUE: __floatundisf:e <- $r2
	//DEBUG_VALUE: __floatundisf:N <- 64
	.loc	2 57 15                         // uPIMulator_frontend/sdk/syslib/floatundisf.c:57:15
	lsrx r2, r0, 3
.Ltmp39:
	lsr_add r5, r2, r1, 3
	lsr r4, r0, 3
.Ltmp40:
	//DEBUG_VALUE: __floatundisf:e <- $r3
	//DEBUG_VALUE: __floatundisf:a <- $d4
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/floatundisf.c:0:0
	move r2, r3
.Ltmp41:
	//DEBUG_VALUE: __floatundisf:e <- $r2
	//DEBUG_VALUE: __floatundisf:a <- undef
	//DEBUG_VALUE: __floatundisf:e <- $r2
	.loc	2 67 20 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatundisf.c:67:20
	and r0, r5, 8388607
	.loc	2 66 23                         // uPIMulator_frontend/sdk/syslib/floatundisf.c:66:23
	lsl_add r0, r0, r2, 23
	.loc	2 66 30 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatundisf.c:66:30
	add r0, r0, 1065353216
.Ltmp42:
	//DEBUG_VALUE: __floatundisf:fb <- $r0
	.loc	2 69 1 is_stmt 1                // uPIMulator_frontend/sdk/syslib/floatundisf.c:69:1
	jump r23
.Ltmp43:
.Lfunc_end0:
	.size	__floatundisf, .Lfunc_end0-__floatundisf
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__floatundisf
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.__floatundisf,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp1-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp13-.Lfunc_begin0
	.long	.Ltmp15-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp17-.Lfunc_begin0
	.long	.Ltmp18-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp20-.Lfunc_begin0
	.long	.Ltmp26-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp27-.Lfunc_begin0
	.long	.Ltmp28-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp29-.Lfunc_begin0
	.long	.Ltmp30-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp40-.Lfunc_begin0
	.long	.Ltmp41-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp11-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	64                              // 64
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp13-.Lfunc_begin0
	.long	.Ltmp33-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	64                              // 64
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp34-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	64                              // 64
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Ltmp7-.Lfunc_begin0
	.long	.Ltmp11-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp20-.Lfunc_begin0
	.long	.Ltmp33-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp34-.Lfunc_begin0
	.long	.Ltmp35-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp38-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Ltmp5-.Lfunc_begin0
	.long	.Ltmp11-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp13-.Lfunc_begin0
	.long	.Ltmp33-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp34-.Lfunc_begin0
	.long	.Ltmp39-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp40-.Lfunc_begin0
	.long	.Ltmp41-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp41-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc4:
	.long	.Ltmp16-.Lfunc_begin0
	.long	.Ltmp17-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp19-.Lfunc_begin0
	.long	.Ltmp20-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp37-.Lfunc_begin0
	.long	.Ltmp38-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp42-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	23                              // DW_TAG_union_type
	.byte	1                               // DW_CHILDREN_yes
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	13                              // DW_TAG_member
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	56                              // DW_AT_data_member_location
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0xdc DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0xb DW_TAG_typedef
	.long	49                              // DW_AT_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	31                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x31:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	2                               // Abbrev [2] 0x38:0xb DW_TAG_typedef
	.long	67                              // DW_AT_type
	.long	.Linfo_string6                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	28                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x43:0x7 DW_TAG_base_type
	.long	.Linfo_string5                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x4a:0x61 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string7                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	26                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	171                             // DW_AT_type
                                        // DW_AT_external
	.byte	5                               // Abbrev [5] 0x5f:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string9                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	26                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0x6e:0xf DW_TAG_variable
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string10                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	30                              // DW_AT_decl_line
	.long	178                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x7d:0xf DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string11                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	31                              // DW_AT_decl_line
	.long	183                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x8c:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string13                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	32                              // DW_AT_decl_line
	.long	183                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x9b:0xf DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	.Linfo_string14                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	65                              // DW_AT_decl_line
	.long	190                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	3                               // Abbrev [3] 0xab:0x7 DW_TAG_base_type
	.long	.Linfo_string8                  // DW_AT_name
	.byte	4                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	7                               // Abbrev [7] 0xb2:0x5 DW_TAG_const_type
	.long	67                              // DW_AT_type
	.byte	3                               // Abbrev [3] 0xb7:0x7 DW_TAG_base_type
	.long	.Linfo_string12                 // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	2                               // Abbrev [2] 0xbe:0xb DW_TAG_typedef
	.long	201                             // DW_AT_type
	.long	.Linfo_string17                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	116                             // DW_AT_decl_line
	.byte	8                               // Abbrev [8] 0xc9:0x1d DW_TAG_union_type
	.byte	4                               // DW_AT_byte_size
	.byte	1                               // DW_AT_decl_file
	.byte	113                             // DW_AT_decl_line
	.byte	9                               // Abbrev [9] 0xcd:0xc DW_TAG_member
	.long	.Linfo_string15                 // DW_AT_name
	.long	56                              // DW_AT_type
	.byte	1                               // DW_AT_decl_file
	.byte	114                             // DW_AT_decl_line
	.byte	0                               // DW_AT_data_member_location
	.byte	9                               // Abbrev [9] 0xd9:0xc DW_TAG_member
	.long	.Linfo_string16                 // DW_AT_name
	.long	171                             // DW_AT_type
	.byte	1                               // DW_AT_decl_file
	.byte	115                             // DW_AT_decl_line
	.byte	0                               // DW_AT_data_member_location
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/floatundisf.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=157
.Linfo_string3:
	.asciz	"long long unsigned int"        // string offset=178
.Linfo_string4:
	.asciz	"du_int"                        // string offset=201
.Linfo_string5:
	.asciz	"unsigned int"                  // string offset=208
.Linfo_string6:
	.asciz	"su_int"                        // string offset=221
.Linfo_string7:
	.asciz	"__floatundisf"                 // string offset=228
.Linfo_string8:
	.asciz	"float"                         // string offset=242
.Linfo_string9:
	.asciz	"a"                             // string offset=248
.Linfo_string10:
	.asciz	"N"                             // string offset=250
.Linfo_string11:
	.asciz	"sd"                            // string offset=252
.Linfo_string12:
	.asciz	"int"                           // string offset=255
.Linfo_string13:
	.asciz	"e"                             // string offset=259
.Linfo_string14:
	.asciz	"fb"                            // string offset=261
.Linfo_string15:
	.asciz	"u"                             // string offset=264
.Linfo_string16:
	.asciz	"f"                             // string offset=266
.Linfo_string17:
	.asciz	"float_bits"                    // string offset=268
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
