	.text
	.file	"floatsisf.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/stdint.h"
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/fp_lib.h"
	.section	.text.__floatsisf,"ax",@progbits
	.globl	__floatsisf                     // -- Begin function __floatsisf
	.type	__floatsisf,@function
__floatsisf:                            // @__floatsisf
.Lfunc_begin0:
	.file	3 "/root" "uPIMulator_frontend/sdk/syslib/floatsisf.c"
	.loc	3 23 0                          // uPIMulator_frontend/sdk/syslib/floatsisf.c:23:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __floatsisf:a <- $r0
	//DEBUG_VALUE: __floatsisf:a <- $r0
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: __floatsisf:aWidth <- 32
	.loc	3 28 9 prologue_end             // uPIMulator_frontend/sdk/syslib/floatsisf.c:28:9
	jeq r0, 0, .LBB0_1
.Ltmp0:
// %bb.2:
	//DEBUG_VALUE: __floatsisf:a <- $r0
	//DEBUG_VALUE: __floatsisf:aWidth <- 32
	//DEBUG_VALUE: __floatsisf:sign <- 0
	.loc	3 33 9                          // uPIMulator_frontend/sdk/syslib/floatsisf.c:33:9
	and r1, r0, -2147483648
	asr r2, r0, 31
	add r0, r0, r2
.Ltmp1:
	xor r2, r0, r2
.Ltmp2:
	//DEBUG_VALUE: __floatsisf:sign <- $r1
	//DEBUG_VALUE: __floatsisf:a <- $r2
	.loc	3 39 41                         // uPIMulator_frontend/sdk/syslib/floatsisf.c:39:41
	clz r0, r2
	.loc	3 39 39 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatsisf.c:39:39
	xor r3, r0, 31
.Ltmp3:
	//DEBUG_VALUE: __floatsisf:exponent <- $r3
	.loc	3 43 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/floatsisf.c:43:9
	jgtu r3, 23, .LBB0_4
.Ltmp4:
// %bb.3:
	//DEBUG_VALUE: __floatsisf:exponent <- $r3
	//DEBUG_VALUE: __floatsisf:a <- $r2
	//DEBUG_VALUE: __floatsisf:sign <- $r1
	//DEBUG_VALUE: __floatsisf:aWidth <- 32
	.loc	3 44 43                         // uPIMulator_frontend/sdk/syslib/floatsisf.c:44:43
	sub r3, 23, r3
.Ltmp5:
	//DEBUG_VALUE: shift <- $r3
	.loc	3 45 27                         // uPIMulator_frontend/sdk/syslib/floatsisf.c:45:27
	lsl r2, r2, r3
.Ltmp6:
	.loc	3 45 36 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatsisf.c:45:36
	xor r2, r2, 8388608
.Ltmp7:
	//DEBUG_VALUE: __floatsisf:result <- $r2
	//DEBUG_VALUE: __floatsisf:result <- $r2
	.loc	3 57 48 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatsisf.c:57:48
	lsl_sub r0, r2, r0, 23
	.loc	3 57 12 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatsisf.c:57:12
	add r0, r0, 1325400064
.Ltmp8:
	//DEBUG_VALUE: __floatsisf:result <- $r0
	.loc	3 59 27 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatsisf.c:59:27
	or r0, r0, r1
.Ltmp9:
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $r0
	.loc	3 60 1                          // uPIMulator_frontend/sdk/syslib/floatsisf.c:60:1
	jump r23
.Ltmp10:
.LBB0_1:
	//DEBUG_VALUE: __floatsisf:a <- $r0
	//DEBUG_VALUE: __floatsisf:aWidth <- 32
	.loc	3 0 1 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/floatsisf.c:0:1
	move r0, 0
.Ltmp11:
	.loc	3 60 1                          // uPIMulator_frontend/sdk/syslib/floatsisf.c:60:1
	jump r23
.Ltmp12:
.LBB0_4:
	//DEBUG_VALUE: __floatsisf:exponent <- $r3
	//DEBUG_VALUE: __floatsisf:a <- $r2
	//DEBUG_VALUE: __floatsisf:sign <- $r1
	//DEBUG_VALUE: __floatsisf:aWidth <- 32
	.loc	3 47 36 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatsisf.c:47:36
	sub r3, 8, r0
.Ltmp13:
	//DEBUG_VALUE: shift <- $r3
	.loc	3 48 27                         // uPIMulator_frontend/sdk/syslib/floatsisf.c:48:27
	lsr r3, r2, r3
.Ltmp14:
	.loc	3 48 36 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatsisf.c:48:36
	xor r3, r3, 8388608
.Ltmp15:
	//DEBUG_VALUE: __floatsisf:result <- $r3
	.loc	3 49 46 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatsisf.c:49:46
	add r4, r0, 24
	.loc	3 49 32 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatsisf.c:49:32
	lsl r4, r2, r4
.Ltmp16:
	//DEBUG_VALUE: round <- $r4
	.loc	3 0 32                          // uPIMulator_frontend/sdk/syslib/floatsisf.c:0:32
	move r5, -2147483648
.Ltmp17:
	.loc	3 50 19 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatsisf.c:50:19
	sub r2, r4, r5, gtu
.Ltmp18:
	.loc	3 50 13 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatsisf.c:50:13
	add r2, r3, r2
.Ltmp19:
	//DEBUG_VALUE: __floatsisf:result <- $r2
	.loc	3 52 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatsisf.c:52:13
	and r3, r2, 1
	jeq r4, r5, .LBB0_6
.Ltmp20:
// %bb.5:
	//DEBUG_VALUE: round <- $r4
	//DEBUG_VALUE: __floatsisf:result <- $r2
	//DEBUG_VALUE: __floatsisf:sign <- $r1
	//DEBUG_VALUE: __floatsisf:aWidth <- 32
	.loc	3 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/floatsisf.c:0:13
	move r3, 0
.Ltmp21:
.LBB0_6:
	//DEBUG_VALUE: round <- $r4
	//DEBUG_VALUE: __floatsisf:result <- $r2
	//DEBUG_VALUE: __floatsisf:sign <- $r1
	//DEBUG_VALUE: __floatsisf:aWidth <- 32
	.loc	3 52 13                         // uPIMulator_frontend/sdk/syslib/floatsisf.c:52:13
	add r2, r3, r2
.Ltmp22:
	//DEBUG_VALUE: __floatsisf:result <- $r2
	.loc	3 57 48 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatsisf.c:57:48
	lsl_sub r0, r2, r0, 23
	.loc	3 57 12 is_stmt 0               // uPIMulator_frontend/sdk/syslib/floatsisf.c:57:12
	add r0, r0, 1325400064
.Ltmp23:
	//DEBUG_VALUE: __floatsisf:result <- $r0
	.loc	3 59 27 is_stmt 1               // uPIMulator_frontend/sdk/syslib/floatsisf.c:59:27
	or r0, r0, r1
.Ltmp24:
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $r0
	.loc	3 60 1                          // uPIMulator_frontend/sdk/syslib/floatsisf.c:60:1
	jump r23
.Ltmp25:
.Lfunc_end0:
	.size	__floatsisf, .Lfunc_end0-__floatsisf
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__floatsisf
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.__floatsisf,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp1-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp6-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp10-.Lfunc_begin0
	.long	.Ltmp11-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp12-.Lfunc_begin0
	.long	.Ltmp18-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp2-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp10-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp12-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp5-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp12-.Lfunc_begin0
	.long	.Ltmp13-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Ltmp5-.Lfunc_begin0
	.long	.Ltmp10-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc4:
	.long	.Ltmp7-.Lfunc_begin0
	.long	.Ltmp8-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp8-.Lfunc_begin0
	.long	.Ltmp9-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp15-.Lfunc_begin0
	.long	.Ltmp19-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp19-.Lfunc_begin0
	.long	.Ltmp23-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp23-.Lfunc_begin0
	.long	.Ltmp24-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc5:
	.long	.Ltmp13-.Lfunc_begin0
	.long	.Ltmp14-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc6:
	.long	.Ltmp16-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	28                              // DW_AT_const_value
	.byte	13                              // DW_FORM_sdata
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0xf6 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0xb DW_TAG_typedef
	.long	49                              // DW_AT_type
	.long	.Linfo_string5                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	43                              // DW_AT_decl_line
	.byte	2                               // Abbrev [2] 0x31:0xb DW_TAG_typedef
	.long	60                              // DW_AT_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	48                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x3c:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x43:0x9f DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string6                  // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	226                             // DW_AT_type
                                        // DW_AT_external
	.byte	5                               // Abbrev [5] 0x58:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string9                  // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
	.long	244                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x67:0xc DW_TAG_variable
	.byte	32                              // DW_AT_const_value
	.long	.Linfo_string11                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	25                              // DW_AT_decl_line
	.long	251                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0x73:0xf DW_TAG_variable
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string12                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	32                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	7                               // Abbrev [7] 0x82:0xf DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string13                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	39                              // DW_AT_decl_line
	.long	251                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0x91:0xf DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	.Linfo_string15                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	40                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0xa0:0x19 DW_TAG_lexical_block
	.long	.Ltmp4                          // DW_AT_low_pc
	.long	.Ltmp7-.Ltmp4                   // DW_AT_high_pc
	.byte	7                               // Abbrev [7] 0xa9:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string14                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	44                              // DW_AT_decl_line
	.long	251                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	8                               // Abbrev [8] 0xb9:0x28 DW_TAG_lexical_block
	.long	.Ltmp12                         // DW_AT_low_pc
	.long	.Ltmp22-.Ltmp12                 // DW_AT_high_pc
	.byte	7                               // Abbrev [7] 0xc2:0xf DW_TAG_variable
	.long	.Ldebug_loc5                    // DW_AT_location
	.long	.Linfo_string14                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	47                              // DW_AT_decl_line
	.long	251                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0xd1:0xf DW_TAG_variable
	.long	.Ldebug_loc6                    // DW_AT_location
	.long	.Linfo_string16                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	49                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	2                               // Abbrev [2] 0xe2:0xb DW_TAG_typedef
	.long	237                             // DW_AT_type
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	45                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0xed:0x7 DW_TAG_base_type
	.long	.Linfo_string7                  // DW_AT_name
	.byte	4                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	3                               // Abbrev [3] 0xf4:0x7 DW_TAG_base_type
	.long	.Linfo_string10                 // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	9                               // Abbrev [9] 0xfb:0x5 DW_TAG_const_type
	.long	244                             // DW_AT_type
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/floatsisf.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=155
.Linfo_string3:
	.asciz	"unsigned int"                  // string offset=176
.Linfo_string4:
	.asciz	"uint32_t"                      // string offset=189
.Linfo_string5:
	.asciz	"rep_t"                         // string offset=198
.Linfo_string6:
	.asciz	"__floatsisf"                   // string offset=204
.Linfo_string7:
	.asciz	"float"                         // string offset=216
.Linfo_string8:
	.asciz	"fp_t"                          // string offset=222
.Linfo_string9:
	.asciz	"a"                             // string offset=227
.Linfo_string10:
	.asciz	"int"                           // string offset=229
.Linfo_string11:
	.asciz	"aWidth"                        // string offset=233
.Linfo_string12:
	.asciz	"sign"                          // string offset=240
.Linfo_string13:
	.asciz	"exponent"                      // string offset=245
.Linfo_string14:
	.asciz	"shift"                         // string offset=254
.Linfo_string15:
	.asciz	"result"                        // string offset=260
.Linfo_string16:
	.asciz	"round"                         // string offset=267
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
