	.text
	.file	"fsb_allocator.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/stdint.h"
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/fsb_allocator.c"
	.file	3 "/root" "uPIMulator_frontend/sdk/syslib/fsb_allocator.h"
	.section	.text.fsb_alloc,"ax",@progbits
	.globl	fsb_alloc                       // -- Begin function fsb_alloc
	.type	fsb_alloc,@function
fsb_alloc:                              // @fsb_alloc
.Lfunc_begin0:
	.loc	2 18 0                          // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:18:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: fsb_alloc:block_size <- $r0
	//DEBUG_VALUE: fsb_alloc:nb_of_blocks <- $r1
	.cfi_def_cfa_offset -16
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 8, d22
	add r22, r22, 16
	.cfi_offset 15, -16
	.cfi_offset 14, -12
	sd r22, -16, d14
	move r15, r1
.Ltmp0:
	//DEBUG_VALUE: fsb_alloc:nb_of_blocks <- $r15
	//DEBUG_VALUE: fsb_alloc:block_size <- $r0
	.loc	2 19 9 prologue_end             // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:19:9
	jgeu r0, -7, .LBB0_9
.Ltmp1:
// %bb.1:
	//DEBUG_VALUE: fsb_alloc:nb_of_blocks <- $r15
	//DEBUG_VALUE: fsb_alloc:block_size <- $r0
	.loc	2 24 18                         // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:24:18
	jeq r0, 0, .LBB0_2
.Ltmp2:
// %bb.3:
	//DEBUG_VALUE: fsb_alloc:nb_of_blocks <- $r15
	//DEBUG_VALUE: fsb_alloc:block_size <- $r0
	.loc	2 0 18 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:0:18
	add r0, r0, 7
.Ltmp3:
	and r14, r0, -8, true, .LBB0_4
.Ltmp4:
.LBB0_2:
	//DEBUG_VALUE: fsb_alloc:nb_of_blocks <- $r15
	//DEBUG_VALUE: fsb_alloc:block_size <- $r0
	move r14, 8
.Ltmp5:
.LBB0_4:
	//DEBUG_VALUE: fsb_alloc:nb_of_blocks <- $r15
	//DEBUG_VALUE: fsb_alloc:block_size <- $r14
	.loc	2 26 56 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:26:56
	move r0, r14
	move r1, r15
	call r23, __mulsi3
.Ltmp6:
	.loc	2 26 71 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:26:71
	or r0, r0, 4
.Ltmp7:
	//DEBUG_VALUE: fsb_alloc:memory_space_to_allocate <- $r0
	.loc	2 27 20 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:27:20
	call r23, mem_alloc
.Ltmp8:
	//DEBUG_VALUE: fsb_alloc:first_block <- $r0
	//DEBUG_VALUE: fsb_alloc:memory <- $r0
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:0:0
	move r2, r0
.Ltmp9:
	//DEBUG_VALUE: each_block <- 0
	.loc	2 31 65 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:31:65
	add r1, r15, -1, z, .LBB0_8
.Ltmp10:
// %bb.5:
	//DEBUG_VALUE: fsb_alloc:nb_of_blocks <- $r15
	//DEBUG_VALUE: fsb_alloc:block_size <- $r14
	//DEBUG_VALUE: fsb_alloc:memory <- $r0
	//DEBUG_VALUE: fsb_alloc:first_block <- $r0
	//DEBUG_VALUE: fsb_alloc:memory_space_to_allocate <- $r0
	//DEBUG_VALUE: each_block <- 0
	.loc	2 31 5 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:31:5
	add r3, r14, r0
	move r2, 0
.Ltmp11:
.LBB0_6:                                // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: fsb_alloc:nb_of_blocks <- $r15
	//DEBUG_VALUE: fsb_alloc:block_size <- $r14
	//DEBUG_VALUE: fsb_alloc:first_block <- $r0
	//DEBUG_VALUE: fsb_alloc:memory_space_to_allocate <- $r0
	//DEBUG_VALUE: fsb_alloc:memory <- undef
	//DEBUG_VALUE: each_block <- undef
	//DEBUG_VALUE: next_block_address <- undef
	.loc	2 33 11 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:33:11
	add r4, r3, r2
	.loc	2 33 35 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:33:35
	add r5, r0, r2
	sw r5, 0, r4
.Ltmp12:
	//DEBUG_VALUE: each_block <- [DW_OP_plus_uconst 1, DW_OP_stack_value] undef
	//DEBUG_VALUE: fsb_alloc:memory <- undef
	.loc	2 31 50 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:31:50
	add r2, r2, r14
	add r1, r1, -1, nz, .LBB0_6
.Ltmp13:
// %bb.7:
	//DEBUG_VALUE: fsb_alloc:nb_of_blocks <- $r15
	//DEBUG_VALUE: fsb_alloc:block_size <- $r14
	//DEBUG_VALUE: fsb_alloc:first_block <- $r0
	//DEBUG_VALUE: fsb_alloc:memory_space_to_allocate <- $r0
	.loc	2 29 32                         // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:29:32
	add r2, r0, r2
.Ltmp14:
.LBB0_8:
	//DEBUG_VALUE: fsb_alloc:nb_of_blocks <- $r15
	//DEBUG_VALUE: fsb_alloc:block_size <- $r14
	//DEBUG_VALUE: fsb_alloc:first_block <- $r0
	//DEBUG_VALUE: fsb_alloc:memory_space_to_allocate <- $r0
	//DEBUG_VALUE: fsb_alloc:first_block <- $r0
	.loc	2 37 31                         // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:37:31
	sw r2, 0, 0
	.loc	2 38 12                         // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:38:12
	add r1, r2, r14
.Ltmp15:
	//DEBUG_VALUE: fsb_alloc:free_ptr <- $r1
	//DEBUG_VALUE: fsb_alloc:memory <- $r1
	.loc	2 41 33                         // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:41:33
	sw r1, 0, r0
	.loc	2 43 5                          // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:43:5
	move r0, r1
.Ltmp16:
	ld d14, r22, -16
.Ltmp17:
	ld d22, r22, -8
	jump r23
.Ltmp18:
.LBB0_9:
	//DEBUG_VALUE: fsb_alloc:nb_of_blocks <- $r15
	//DEBUG_VALUE: fsb_alloc:block_size <- $r0
	.loc	2 20 9                          // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:20:9
	// inline asm
	fault 1
	// inline asm
.Ltmp19:
.Lfunc_end0:
	.size	fsb_alloc, .Lfunc_end0-fsb_alloc
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.fsb_alloc
	.long	.Lfunc_begin0
	.byte	16
	.section	.text.fsb_alloc,"ax",@progbits
                                        // -- End function
	.section	.text.fsb_get,"ax",@progbits
	.globl	fsb_get                         // -- Begin function fsb_get
	.type	fsb_get,@function
fsb_get:                                // @fsb_get
.Lfunc_begin1:
	.loc	2 49 0                          // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:49:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: fsb_get:allocator <- $r0
	.cfi_def_cfa_offset 0
	.loc	2 51 5 prologue_end             // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:51:5
	// inline asm
.Ltmp20:
	acquire zero, __atomic_bit___fsb_lock, nz, .Ltmp20
	// inline asm
	move r1, r0
.Ltmp21:
	//DEBUG_VALUE: fsb_get:allocator <- $r1
	.loc	2 52 5                          // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:52:5
	// inline asm
	lw r0, r1, 0
	// inline asm
.Ltmp22:
	//DEBUG_VALUE: fsb_get:result <- $r0
	.loc	2 54 9                          // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:54:9
	jeq r0, 0, .LBB1_1
.Ltmp23:
// %bb.2:
	//DEBUG_VALUE: fsb_get:allocator <- $r1
	//DEBUG_VALUE: fsb_get:result <- $r0
	.loc	2 59 18                         // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:59:18
	lw r2, r0, 0
.Ltmp24:
	//DEBUG_VALUE: fsb_get:next <- $r2
	.loc	2 61 5                          // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:61:5
	// inline asm
	sw r1, 0, r2
	// inline asm
	.loc	2 62 5                          // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:62:5
	// inline asm
.Ltmp25:
	release zero, __atomic_bit___fsb_lock, nz, .Ltmp25+1
	// inline asm
	.loc	2 65 1                          // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:65:1
	jump r23
.Ltmp26:
.LBB1_1:
	//DEBUG_VALUE: fsb_get:allocator <- $r1
	//DEBUG_VALUE: fsb_get:result <- $r0
	.loc	2 55 9                          // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:55:9
	// inline asm
.Ltmp27:
	release zero, __atomic_bit___fsb_lock, nz, .Ltmp27+1
	// inline asm
	move r0, 0
.Ltmp28:
	.loc	2 65 1                          // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:65:1
	jump r23
.Ltmp29:
.Lfunc_end1:
	.size	fsb_get, .Lfunc_end1-fsb_get
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.fsb_get
	.long	.Lfunc_begin1
	.byte	0
	.section	.text.fsb_get,"ax",@progbits
                                        // -- End function
	.section	.text.fsb_free,"ax",@progbits
	.globl	fsb_free                        // -- Begin function fsb_free
	.type	fsb_free,@function
fsb_free:                               // @fsb_free
.Lfunc_begin2:
	.loc	2 70 0                          // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:70:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: fsb_free:allocator <- $r0
	//DEBUG_VALUE: fsb_free:allocator <- $r0
	//DEBUG_VALUE: fsb_free:ptr <- $r1
	//DEBUG_VALUE: fsb_free:ptr <- $r1
	.cfi_def_cfa_offset 0
	.loc	2 72 5 prologue_end             // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:72:5
	// inline asm
.Ltmp30:
	acquire zero, __atomic_bit___fsb_lock, nz, .Ltmp30
	// inline asm
	.loc	2 73 5                          // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:73:5
	// inline asm
	lw r2, r0, 0
	// inline asm
.Ltmp31:
	//DEBUG_VALUE: fsb_free:next_free <- $r2
	.loc	2 75 21                         // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:75:21
	sw r1, 0, r2
	.loc	2 77 5                          // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:77:5
	// inline asm
	sw r0, 0, r1
	// inline asm
	.loc	2 78 5                          // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:78:5
	// inline asm
.Ltmp32:
	release zero, __atomic_bit___fsb_lock, nz, .Ltmp32+1
	// inline asm
	.loc	2 79 1                          // uPIMulator_frontend/sdk/syslib/fsb_allocator.c:79:1
	jump r23
.Ltmp33:
.Lfunc_end2:
	.size	fsb_free, .Lfunc_end2-fsb_free
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.fsb_free
	.long	.Lfunc_begin2
	.byte	0
	.section	.text.fsb_free,"ax",@progbits
                                        // -- End function
	.type	__atomic_bit___fsb_lock,@object // @__atomic_bit___fsb_lock
	.section	.atomic,"aw",@progbits
	.globl	__atomic_bit___fsb_lock
__atomic_bit___fsb_lock:
	.byte	0                               // 0x0
	.size	__atomic_bit___fsb_lock, 1

	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp3-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp4-.Lfunc_begin0
	.long	.Ltmp5-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp5-.Lfunc_begin0
	.long	.Ltmp17-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	.Ltmp18-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc1:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp17-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	.Ltmp18-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	0
	.long	0
.Ldebug_loc2:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp7-.Lfunc_begin0
	.long	.Ltmp16-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc3:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp8-.Lfunc_begin0
	.long	.Ltmp16-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc4:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp8-.Lfunc_begin0
	.long	.Ltmp11-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp15-.Lfunc_begin0
	.long	.Ltmp18-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc5:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp9-.Lfunc_begin0
	.long	.Ltmp11-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc6:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp15-.Lfunc_begin0
	.long	.Ltmp18-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc7:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Lfunc_begin1-.Lfunc_begin1
	.long	.Ltmp21-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp21-.Lfunc_begin1
	.long	.Lfunc_end1-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc8:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp22-.Lfunc_begin1
	.long	.Ltmp28-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc9:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp24-.Lfunc_begin1
	.long	.Ltmp26-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc10:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp31-.Lfunc_begin2
	.long	.Lfunc_end2-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	11                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	12                              // Abbreviation Code
	.ascii	"\211\202\001"                  // DW_TAG_GNU_call_site
	.byte	0                               // DW_CHILDREN_no
	.ascii	"\223B"                         // DW_AT_GNU_call_site_target
	.byte	24                              // DW_FORM_exprloc
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	13                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	14                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x186 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	0                               // DW_AT_low_pc
	.long	.Ldebug_ranges0                 // DW_AT_ranges
	.byte	2                               // Abbrev [2] 0x26:0x11 DW_TAG_variable
	.long	.Linfo_string3                  // DW_AT_name
	.long	55                              // DW_AT_type
                                        // DW_AT_external
	.byte	2                               // DW_AT_decl_file
	.byte	13                              // DW_AT_decl_line
	.byte	5                               // DW_AT_location
	.byte	3
	.long	__atomic_bit___fsb_lock
	.byte	3                               // Abbrev [3] 0x37:0xb DW_TAG_typedef
	.long	66                              // DW_AT_type
	.long	.Linfo_string5                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	40                              // DW_AT_decl_line
	.byte	4                               // Abbrev [4] 0x42:0x7 DW_TAG_base_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	8                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x49:0x7 DW_TAG_base_type
	.long	.Linfo_string6                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	5                               // Abbrev [5] 0x50:0x5 DW_TAG_pointer_type
	.long	73                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0x55:0x1 DW_TAG_pointer_type
	.byte	3                               // Abbrev [3] 0x56:0xb DW_TAG_typedef
	.long	97                              // DW_AT_type
	.long	.Linfo_string7                  // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	27                              // DW_AT_decl_line
	.byte	5                               // Abbrev [5] 0x61:0x5 DW_TAG_pointer_type
	.long	85                              // DW_AT_type
	.byte	7                               // Abbrev [7] 0x66:0xac DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	17                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	86                              // DW_AT_type
                                        // DW_AT_external
	.byte	8                               // Abbrev [8] 0x7b:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string11                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	17                              // DW_AT_decl_line
	.long	73                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0x8a:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string12                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	17                              // DW_AT_decl_line
	.long	73                              // DW_AT_type
	.byte	9                               // Abbrev [9] 0x99:0xf DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string13                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	26                              // DW_AT_decl_line
	.long	73                              // DW_AT_type
	.byte	9                               // Abbrev [9] 0xa8:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string14                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	29                              // DW_AT_decl_line
	.long	73                              // DW_AT_type
	.byte	9                               // Abbrev [9] 0xb7:0xf DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	.Linfo_string15                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	27                              // DW_AT_decl_line
	.long	85                              // DW_AT_type
	.byte	9                               // Abbrev [9] 0xc6:0xf DW_TAG_variable
	.long	.Ldebug_loc6                    // DW_AT_location
	.long	.Linfo_string18                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	40                              // DW_AT_decl_line
	.long	85                              // DW_AT_type
	.byte	10                              // Abbrev [10] 0xd5:0x2e DW_TAG_lexical_block
	.long	.Ltmp9                          // DW_AT_low_pc
	.long	.Ltmp13-.Ltmp9                  // DW_AT_high_pc
	.byte	9                               // Abbrev [9] 0xde:0xf DW_TAG_variable
	.long	.Ldebug_loc5                    // DW_AT_location
	.long	.Linfo_string16                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	31                              // DW_AT_decl_line
	.long	73                              // DW_AT_type
	.byte	10                              // Abbrev [10] 0xed:0x15 DW_TAG_lexical_block
	.long	.Ltmp11                         // DW_AT_low_pc
	.long	.Ltmp12-.Ltmp11                 // DW_AT_high_pc
	.byte	11                              // Abbrev [11] 0xf6:0xb DW_TAG_variable
	.long	.Linfo_string17                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	32                              // DW_AT_decl_line
	.long	73                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	12                              // Abbrev [12] 0x103:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp6                          // DW_AT_low_pc
	.byte	12                              // Abbrev [12] 0x10a:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp8                          // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x112:0x43 DW_TAG_subprogram
	.long	.Lfunc_begin1                   // DW_AT_low_pc
	.long	.Lfunc_end1-.Lfunc_begin1       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string9                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	48                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	85                              // DW_AT_type
                                        // DW_AT_external
	.byte	8                               // Abbrev [8] 0x127:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc7                    // DW_AT_location
	.long	.Linfo_string19                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	48                              // DW_AT_decl_line
	.long	86                              // DW_AT_type
	.byte	9                               // Abbrev [9] 0x136:0xf DW_TAG_variable
	.long	.Ldebug_loc8                    // DW_AT_location
	.long	.Linfo_string20                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	50                              // DW_AT_decl_line
	.long	97                              // DW_AT_type
	.byte	9                               // Abbrev [9] 0x145:0xf DW_TAG_variable
	.long	.Ldebug_loc9                    // DW_AT_location
	.long	.Linfo_string21                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	59                              // DW_AT_decl_line
	.long	85                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	13                              // Abbrev [13] 0x155:0x3b DW_TAG_subprogram
	.long	.Lfunc_begin2                   // DW_AT_low_pc
	.long	.Lfunc_end2-.Lfunc_begin2       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string10                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	69                              // DW_AT_decl_line
                                        // DW_AT_prototyped
                                        // DW_AT_external
	.byte	14                              // Abbrev [14] 0x166:0xd DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	.Linfo_string19                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	69                              // DW_AT_decl_line
	.long	86                              // DW_AT_type
	.byte	14                              // Abbrev [14] 0x173:0xd DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	.Linfo_string22                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	69                              // DW_AT_decl_line
	.long	85                              // DW_AT_type
	.byte	9                               // Abbrev [9] 0x180:0xf DW_TAG_variable
	.long	.Ldebug_loc10                   // DW_AT_location
	.long	.Linfo_string23                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	71                              // DW_AT_decl_line
	.long	85                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_ranges,"",@progbits
.Ldebug_ranges0:
	.long	.Lfunc_begin0
	.long	.Lfunc_end0
	.long	.Lfunc_begin1
	.long	.Lfunc_end1
	.long	.Lfunc_begin2
	.long	.Lfunc_end2
	.long	0
	.long	0
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/fsb_allocator.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=159
.Linfo_string3:
	.asciz	"__atomic_bit___fsb_lock"       // string offset=180
.Linfo_string4:
	.asciz	"unsigned char"                 // string offset=204
.Linfo_string5:
	.asciz	"uint8_t"                       // string offset=218
.Linfo_string6:
	.asciz	"unsigned int"                  // string offset=226
.Linfo_string7:
	.asciz	"fsb_allocator_t"               // string offset=239
.Linfo_string8:
	.asciz	"fsb_alloc"                     // string offset=255
.Linfo_string9:
	.asciz	"fsb_get"                       // string offset=265
.Linfo_string10:
	.asciz	"fsb_free"                      // string offset=273
.Linfo_string11:
	.asciz	"block_size"                    // string offset=282
.Linfo_string12:
	.asciz	"nb_of_blocks"                  // string offset=293
.Linfo_string13:
	.asciz	"memory_space_to_allocate"      // string offset=306
.Linfo_string14:
	.asciz	"first_block"                   // string offset=331
.Linfo_string15:
	.asciz	"memory"                        // string offset=343
.Linfo_string16:
	.asciz	"each_block"                    // string offset=350
.Linfo_string17:
	.asciz	"next_block_address"            // string offset=361
.Linfo_string18:
	.asciz	"free_ptr"                      // string offset=380
.Linfo_string19:
	.asciz	"allocator"                     // string offset=389
.Linfo_string20:
	.asciz	"result"                        // string offset=399
.Linfo_string21:
	.asciz	"next"                          // string offset=406
.Linfo_string22:
	.asciz	"ptr"                           // string offset=411
.Linfo_string23:
	.asciz	"next_free"                     // string offset=415
	.addrsig
	.addrsig_sym __atomic_bit___fsb_lock
	.section	.debug_line,"",@progbits
.Lline_table_start0:
