	.text
	.file	"handshake.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/syslib/handshake.c"
	.file	2 "/root" "uPIMulator_frontend/sdk/stdlib/stdint.h"
	.section	.text.handshake_notify,"ax",@progbits
	.globl	handshake_notify                // -- Begin function handshake_notify
	.type	handshake_notify,@function
handshake_notify:                       // @handshake_notify
.Lfunc_begin0:
	.loc	1 21 0                          // uPIMulator_frontend/sdk/syslib/handshake.c:21:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	.cfi_def_cfa_offset 0
	.loc	1 24 5 prologue_end             // uPIMulator_frontend/sdk/syslib/handshake.c:24:5
	move r0, __atomic_start_addr
	move r1, __atomic_bit___handshake
	sub r0, r1, r0
	add r0, id, r0
	// inline asm
.Ltmp0:
	acquire r0, 0, nz, .Ltmp0
	// inline asm
	.loc	1 25 12                         // uPIMulator_frontend/sdk/syslib/handshake.c:25:12
	lbu r2, id, __handshake_array
.Ltmp1:
	//DEBUG_VALUE: handshake_notify:info <- $r2
	.file	3 "/root" "uPIMulator_frontend/sdk/syslib/defs.h"
	.loc	3 35 12                         // uPIMulator_frontend/sdk/syslib/defs.h:35:12
	move r1, id
.Ltmp2:
	//DEBUG_VALUE: handshake_notify:tid <- $r1
	.loc	1 27 9                          // uPIMulator_frontend/sdk/syslib/handshake.c:27:9
	jeq r2, 255, .LBB0_1
.Ltmp3:
// %bb.2:
	//DEBUG_VALUE: handshake_notify:info <- $r2
	//DEBUG_VALUE: handshake_notify:tid <- $r1
	.loc	1 32 9                          // uPIMulator_frontend/sdk/syslib/handshake.c:32:9
	// inline asm
.Ltmp4:
	resume r2, 0, nz, .Ltmp4+0
	// inline asm
	move r2, 255
.Ltmp5:
	.loc	1 33 32                         // uPIMulator_frontend/sdk/syslib/handshake.c:33:32
	sb r1, __handshake_array, r2
	.loc	1 34 9                          // uPIMulator_frontend/sdk/syslib/handshake.c:34:9
	// inline asm
.Ltmp6:
	release r0, 0, nz, .Ltmp6+1
	// inline asm
.Ltmp7:
	.loc	1 36 1                          // uPIMulator_frontend/sdk/syslib/handshake.c:36:1
	jump r23
.Ltmp8:
.LBB0_1:
	//DEBUG_VALUE: handshake_notify:info <- $r2
	//DEBUG_VALUE: handshake_notify:tid <- $r1
	.loc	1 28 32                         // uPIMulator_frontend/sdk/syslib/handshake.c:28:32
	sb r1, __handshake_array, r1
	.loc	1 29 9                          // uPIMulator_frontend/sdk/syslib/handshake.c:29:9
	// inline asm
.Ltmp9:
	release r0, 0, nz, .Ltmp9+1
	// inline asm
	.loc	1 30 9                          // uPIMulator_frontend/sdk/syslib/handshake.c:30:9
	// inline asm
	stop false, 0x0
	// inline asm
.Ltmp10:
	.loc	1 36 1                          // uPIMulator_frontend/sdk/syslib/handshake.c:36:1
	jump r23
.Ltmp11:
.Lfunc_end0:
	.size	handshake_notify, .Lfunc_end0-handshake_notify
	.cfi_endproc
	.file	4 "/root" "uPIMulator_frontend/sdk/syslib/sysdef.h"
	.section	.stack_sizes,"o",@progbits,.text.handshake_notify
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.handshake_notify,"ax",@progbits
                                        // -- End function
	.section	.text.handshake_wait_for,"ax",@progbits
	.globl	handshake_wait_for              // -- Begin function handshake_wait_for
	.type	handshake_wait_for,@function
handshake_wait_for:                     // @handshake_wait_for
.Lfunc_begin1:
	.loc	1 40 0                          // uPIMulator_frontend/sdk/syslib/handshake.c:40:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: handshake_wait_for:notifier <- $r0
	//DEBUG_VALUE: handshake_wait_for:notifier <- $r0
	.cfi_def_cfa_offset 0
	.loc	1 45 5 prologue_end             // uPIMulator_frontend/sdk/syslib/handshake.c:45:5
	and r0, r0, 255
.Ltmp12:
	move r1, __atomic_start_addr
	move r2, __atomic_bit___handshake
	sub r1, r2, r1
	add r1, r0, r1
	// inline asm
.Ltmp13:
	acquire r1, 0, nz, .Ltmp13
	// inline asm
	.loc	1 46 26                         // uPIMulator_frontend/sdk/syslib/handshake.c:46:26
	lbu r3, r0, __handshake_array
.Ltmp14:
	//DEBUG_VALUE: handshake_wait_for:info <- $r3
	.loc	3 35 12                         // uPIMulator_frontend/sdk/syslib/defs.h:35:12
	move r2, id
.Ltmp15:
	//DEBUG_VALUE: handshake_wait_for:thread <- undef
	//DEBUG_VALUE: handshake_wait_for:tid <- $r2
	.loc	1 48 9                          // uPIMulator_frontend/sdk/syslib/handshake.c:48:9
	jeq r3, 255, .LBB1_1
.Ltmp16:
// %bb.2:
	//DEBUG_VALUE: handshake_wait_for:info <- $r3
	//DEBUG_VALUE: handshake_wait_for:tid <- $r2
	.loc	1 53 13                         // uPIMulator_frontend/sdk/syslib/handshake.c:53:13
	jneq r3, r0, .LBB1_3
.Ltmp17:
// %bb.4:
	//DEBUG_VALUE: handshake_wait_for:info <- $r3
	//DEBUG_VALUE: handshake_wait_for:tid <- $r2
	.loc	1 58 13                         // uPIMulator_frontend/sdk/syslib/handshake.c:58:13
	// inline asm
.Ltmp18:
	resume r3, 0, nz, .Ltmp18+0
	// inline asm
	move r2, 255
.Ltmp19:
	.loc	1 59 39                         // uPIMulator_frontend/sdk/syslib/handshake.c:59:39
	sb r0, __handshake_array, r2
.Ltmp20:
	.loc	1 62 9                          // uPIMulator_frontend/sdk/syslib/handshake.c:62:9
	// inline asm
.Ltmp21:
	release r1, 0, nz, .Ltmp21+1
	// inline asm
	move r0, 0
.Ltmp22:
	.loc	1 66 1                          // uPIMulator_frontend/sdk/syslib/handshake.c:66:1
	jump r23
.Ltmp23:
.LBB1_1:
	//DEBUG_VALUE: handshake_wait_for:info <- $r3
	//DEBUG_VALUE: handshake_wait_for:tid <- $r2
	.loc	1 49 35                         // uPIMulator_frontend/sdk/syslib/handshake.c:49:35
	sb r0, __handshake_array, r2
	.loc	1 50 9                          // uPIMulator_frontend/sdk/syslib/handshake.c:50:9
	// inline asm
.Ltmp24:
	release r1, 0, nz, .Ltmp24+1
	// inline asm
	.loc	1 51 9                          // uPIMulator_frontend/sdk/syslib/handshake.c:51:9
	// inline asm
	stop false, 0x0
	// inline asm
	move r0, 0
.Ltmp25:
	.loc	1 66 1                          // uPIMulator_frontend/sdk/syslib/handshake.c:66:1
	jump r23
.Ltmp26:
.LBB1_3:
	//DEBUG_VALUE: handshake_wait_for:info <- $r3
	//DEBUG_VALUE: handshake_wait_for:tid <- $r2
	.loc	1 54 13                         // uPIMulator_frontend/sdk/syslib/handshake.c:54:13
	lsl r2, r2, 2
.Ltmp27:
	.loc	1 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/handshake.c:0:13
	move r0, 7
	.loc	1 54 19                         // uPIMulator_frontend/sdk/syslib/handshake.c:54:19
	sw r2, __errno, r0
	.loc	1 55 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/handshake.c:55:13
	// inline asm
.Ltmp28:
	release r1, 0, nz, .Ltmp28+1
	// inline asm
.Ltmp29:
	.loc	1 66 1                          // uPIMulator_frontend/sdk/syslib/handshake.c:66:1
	jump r23
.Ltmp30:
.Lfunc_end1:
	.size	handshake_wait_for, .Lfunc_end1-handshake_wait_for
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.handshake_wait_for
	.long	.Lfunc_begin1
	.byte	0
	.section	.text.handshake_wait_for,"ax",@progbits
                                        // -- End function
	.type	__handshake_array,@object       // @__handshake_array
	.section	.data.__handshake_array,"aw",@progbits
	.globl	__handshake_array
__handshake_array:
	.zero	24,255
	.size	__handshake_array, 24

	.type	__atomic_bit___handshake,@object // @__atomic_bit___handshake
	.section	.atomic,"aw",@progbits
	.globl	__atomic_bit___handshake
__atomic_bit___handshake:
	.zero	24
	.size	__atomic_bit___handshake, 24

	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp1-.Lfunc_begin0
	.long	.Ltmp5-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp8-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc1:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc2:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Lfunc_begin1-.Lfunc_begin1
	.long	.Ltmp12-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc3:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp14-.Lfunc_begin1
	.long	.Lfunc_end1-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc4:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp15-.Lfunc_begin1
	.long	.Ltmp19-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp23-.Lfunc_begin1
	.long	.Ltmp27-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	1                               // DW_TAG_array_type
	.byte	1                               // DW_CHILDREN_yes
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	33                              // DW_TAG_subrange_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	55                              // DW_AT_count
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	11                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	0                               // DW_CHILDREN_no
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	12                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	13                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	14                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x13d DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	0                               // DW_AT_low_pc
	.long	.Ldebug_ranges0                 // DW_AT_ranges
	.byte	2                               // Abbrev [2] 0x26:0x11 DW_TAG_variable
	.long	.Linfo_string3                  // DW_AT_name
	.long	55                              // DW_AT_type
                                        // DW_AT_external
	.byte	1                               // DW_AT_decl_file
	.byte	12                              // DW_AT_decl_line
	.byte	5                               // DW_AT_location
	.byte	3
	.long	__handshake_array
	.byte	3                               // Abbrev [3] 0x37:0xc DW_TAG_array_type
	.long	67                              // DW_AT_type
	.byte	4                               // Abbrev [4] 0x3c:0x6 DW_TAG_subrange_type
	.long	74                              // DW_AT_type
	.byte	24                              // DW_AT_count
	.byte	0                               // End Of Children Mark
	.byte	5                               // Abbrev [5] 0x43:0x7 DW_TAG_base_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	8                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	6                               // Abbrev [6] 0x4a:0x7 DW_TAG_base_type
	.long	.Linfo_string5                  // DW_AT_name
	.byte	8                               // DW_AT_byte_size
	.byte	7                               // DW_AT_encoding
	.byte	2                               // Abbrev [2] 0x51:0x11 DW_TAG_variable
	.long	.Linfo_string6                  // DW_AT_name
	.long	98                              // DW_AT_type
                                        // DW_AT_external
	.byte	1                               // DW_AT_decl_file
	.byte	14                              // DW_AT_decl_line
	.byte	5                               // DW_AT_location
	.byte	3
	.long	__atomic_bit___handshake
	.byte	3                               // Abbrev [3] 0x62:0xc DW_TAG_array_type
	.long	110                             // DW_AT_type
	.byte	4                               // Abbrev [4] 0x67:0x6 DW_TAG_subrange_type
	.long	74                              // DW_AT_type
	.byte	24                              // DW_AT_count
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x6e:0xb DW_TAG_typedef
	.long	67                              // DW_AT_type
	.long	.Linfo_string7                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	40                              // DW_AT_decl_line
	.byte	8                               // Abbrev [8] 0x79:0xc DW_TAG_subprogram
	.long	.Linfo_string8                  // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	33                              // DW_AT_decl_line
	.long	133                             // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	7                               // Abbrev [7] 0x85:0xb DW_TAG_typedef
	.long	144                             // DW_AT_type
	.long	.Linfo_string10                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	27                              // DW_AT_decl_line
	.byte	5                               // Abbrev [5] 0x90:0x7 DW_TAG_base_type
	.long	.Linfo_string9                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	9                               // Abbrev [9] 0x97:0x40 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string11                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	20                              // DW_AT_decl_line
                                        // DW_AT_prototyped
                                        // DW_AT_external
	.byte	10                              // Abbrev [10] 0xa8:0xf DW_TAG_variable
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string14                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	23                              // DW_AT_decl_line
	.long	67                              // DW_AT_type
	.byte	10                              // Abbrev [10] 0xb7:0xf DW_TAG_variable
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string15                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
	.long	316                             // DW_AT_type
	.byte	11                              // Abbrev [11] 0xc6:0x10 DW_TAG_inlined_subroutine
	.long	121                             // DW_AT_abstract_origin
	.long	.Ltmp1                          // DW_AT_low_pc
	.long	.Ltmp2-.Ltmp1                   // DW_AT_high_pc
	.byte	1                               // DW_AT_call_file
	.byte	22                              // DW_AT_call_line
	.byte	23                              // DW_AT_call_column
	.byte	0                               // End Of Children Mark
	.byte	12                              // Abbrev [12] 0xd7:0x5e DW_TAG_subprogram
	.long	.Lfunc_begin1                   // DW_AT_low_pc
	.long	.Lfunc_end1-.Lfunc_begin1       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string12                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	39                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	309                             // DW_AT_type
                                        // DW_AT_external
	.byte	13                              // Abbrev [13] 0xec:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string17                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	39                              // DW_AT_decl_line
	.long	144                             // DW_AT_type
	.byte	10                              // Abbrev [10] 0xfb:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string14                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	46                              // DW_AT_decl_line
	.long	67                              // DW_AT_type
	.byte	14                              // Abbrev [14] 0x10a:0xb DW_TAG_variable
	.long	.Linfo_string18                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	43                              // DW_AT_decl_line
	.long	67                              // DW_AT_type
	.byte	10                              // Abbrev [10] 0x115:0xf DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	.Linfo_string15                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	41                              // DW_AT_decl_line
	.long	316                             // DW_AT_type
	.byte	11                              // Abbrev [11] 0x124:0x10 DW_TAG_inlined_subroutine
	.long	121                             // DW_AT_abstract_origin
	.long	.Ltmp14                         // DW_AT_low_pc
	.long	.Ltmp15-.Ltmp14                 // DW_AT_high_pc
	.byte	1                               // DW_AT_call_file
	.byte	41                              // DW_AT_call_line
	.byte	23                              // DW_AT_call_column
	.byte	0                               // End Of Children Mark
	.byte	5                               // Abbrev [5] 0x135:0x7 DW_TAG_base_type
	.long	.Linfo_string13                 // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	7                               // Abbrev [7] 0x13c:0xb DW_TAG_typedef
	.long	144                             // DW_AT_type
	.long	.Linfo_string16                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	18                              // DW_AT_decl_line
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_ranges,"",@progbits
.Ldebug_ranges0:
	.long	.Lfunc_begin0
	.long	.Lfunc_end0
	.long	.Lfunc_begin1
	.long	.Lfunc_end1
	.long	0
	.long	0
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/handshake.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=155
.Linfo_string3:
	.asciz	"__handshake_array"             // string offset=176
.Linfo_string4:
	.asciz	"unsigned char"                 // string offset=194
.Linfo_string5:
	.asciz	"__ARRAY_SIZE_TYPE__"           // string offset=208
.Linfo_string6:
	.asciz	"__atomic_bit___handshake"      // string offset=228
.Linfo_string7:
	.asciz	"uint8_t"                       // string offset=253
.Linfo_string8:
	.asciz	"me"                            // string offset=261
.Linfo_string9:
	.asciz	"unsigned int"                  // string offset=264
.Linfo_string10:
	.asciz	"sysname_t"                     // string offset=277
.Linfo_string11:
	.asciz	"handshake_notify"              // string offset=287
.Linfo_string12:
	.asciz	"handshake_wait_for"            // string offset=304
.Linfo_string13:
	.asciz	"int"                           // string offset=323
.Linfo_string14:
	.asciz	"info"                          // string offset=327
.Linfo_string15:
	.asciz	"tid"                           // string offset=332
.Linfo_string16:
	.asciz	"thread_id_t"                   // string offset=336
.Linfo_string17:
	.asciz	"notifier"                      // string offset=348
.Linfo_string18:
	.asciz	"thread"                        // string offset=357
	.addrsig
	.addrsig_sym __atomic_bit___handshake
	.addrsig_sym __atomic_start_addr
	.section	.debug_line,"",@progbits
.Lline_table_start0:
