	.text
	.file	"listener.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/stdint.h"
	.section	.text.__sys_internal_listener_loop,"ax",@progbits
	.globl	__sys_internal_listener_loop    // -- Begin function __sys_internal_listener_loop
	.type	__sys_internal_listener_loop,@function
__sys_internal_listener_loop:           // @__sys_internal_listener_loop
.Lfunc_begin0:
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/listener.c"
	.loc	2 47 0                          // uPIMulator_frontend/sdk/syslib/listener.c:47:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __sys_internal_listener_loop:request <- $r0
	//DEBUG_VALUE: __sys_internal_listener_loop:request_size <- $r1
	.cfi_def_cfa_offset -32
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 24, d22
	add r22, r22, 32
	.cfi_offset 15, -16
	.cfi_offset 14, -12
.Ltmp0:
	sd r22, -16, d14
	.cfi_offset 17, -24
	.cfi_offset 16, -20
	sd r22, -24, d16
	.cfi_offset 19, -32
	.cfi_offset 18, -28
	sd r22, -32, d18
	.loc	2 30 27 prologue_end            // uPIMulator_frontend/sdk/syslib/listener.c:30:27
	lhu r2, id4, __sys_fifo_table_ptr
	.loc	2 30 12 is_stmt 0               // uPIMulator_frontend/sdk/syslib/listener.c:30:12
	lw r14, r2, 0
.Ltmp1:
	//DEBUG_VALUE: fifo_sys_fetch_info:fid <- 0
	//DEBUG_VALUE: __sys_internal_listener_loop:self_fifo_info <- $r14
	.loc	2 23 12 is_stmt 1               // uPIMulator_frontend/sdk/syslib/listener.c:23:12
	lw r15, zero, __sys_fifo_sys_table
.Ltmp2:
	//DEBUG_VALUE: __sys_internal_listener_loop:from_host_fifo_info <- $r15
	move r2, __sys_fifo_sys_table
.Ltmp3:
	//DEBUG_VALUE: fifo_sys_fetch_info:fid <- 1
	.loc	2 23 12 is_stmt 0               // uPIMulator_frontend/sdk/syslib/listener.c:23:12
	lw r16, r2, 4
.Ltmp4:
	//DEBUG_VALUE: __sys_internal_listener_loop:to_host_fifo_info <- $r16
	.loc	2 0 12                          // uPIMulator_frontend/sdk/syslib/listener.c:0:12
	move r17, r1
.Ltmp5:
	//DEBUG_VALUE: __sys_internal_listener_loop:request_size <- $r17
	move r18, r0
.Ltmp6:
	//DEBUG_VALUE: __sys_internal_listener_loop:request <- $r18
	.file	3 "/root" "uPIMulator_frontend/sdk/syslib/defs.h"
	.loc	3 35 12 is_stmt 1               // uPIMulator_frontend/sdk/syslib/defs.h:35:12
	move r19, id
.Ltmp7:
	//DEBUG_VALUE: fifo_fetch_info:recipient <- $r19
	//DEBUG_VALUE: __sys_internal_listener_loop:id <- $r19
.LBB0_1:                                // =>This Loop Header: Depth=1
                                        //     Child Loop BB0_2 Depth 2
	//DEBUG_VALUE: __sys_internal_listener_loop:id <- $r19
	//DEBUG_VALUE: __sys_internal_listener_loop:request <- $r18
	//DEBUG_VALUE: __sys_internal_listener_loop:request_size <- $r17
	//DEBUG_VALUE: __sys_internal_listener_loop:to_host_fifo_info <- $r16
	//DEBUG_VALUE: __sys_internal_listener_loop:from_host_fifo_info <- $r15
	//DEBUG_VALUE: __sys_internal_listener_loop:self_fifo_info <- $r14
	.loc	2 58 13                         // uPIMulator_frontend/sdk/syslib/listener.c:58:13
	move r0, r14
	move r1, r18
	move r2, r17
	call r23, fetch_request
.Ltmp8:
	.loc	2 58 13 is_stmt 0               // uPIMulator_frontend/sdk/syslib/listener.c:58:13
	jeq r0, 0, .LBB0_4
.Ltmp9:
.LBB0_2:                                //   Parent Loop BB0_1 Depth=1
                                        // =>  This Inner Loop Header: Depth=2
	//DEBUG_VALUE: __sys_internal_listener_loop:id <- $r19
	//DEBUG_VALUE: __sys_internal_listener_loop:request <- $r18
	//DEBUG_VALUE: __sys_internal_listener_loop:request_size <- $r17
	//DEBUG_VALUE: __sys_internal_listener_loop:to_host_fifo_info <- $r16
	//DEBUG_VALUE: __sys_internal_listener_loop:from_host_fifo_info <- $r15
	//DEBUG_VALUE: __sys_internal_listener_loop:self_fifo_info <- $r14
	.loc	2 59 20 is_stmt 1               // uPIMulator_frontend/sdk/syslib/listener.c:59:20
	move r0, r16
	move r1, r17
	call r23, fifo_is_full
.Ltmp10:
	.loc	2 59 13 is_stmt 0               // uPIMulator_frontend/sdk/syslib/listener.c:59:13
	jnz r0, .LBB0_2
.Ltmp11:
// %bb.3:                               //   in Loop: Header=BB0_1 Depth=1
	//DEBUG_VALUE: __sys_internal_listener_loop:id <- $r19
	//DEBUG_VALUE: __sys_internal_listener_loop:request <- $r18
	//DEBUG_VALUE: __sys_internal_listener_loop:request_size <- $r17
	//DEBUG_VALUE: __sys_internal_listener_loop:to_host_fifo_info <- $r16
	//DEBUG_VALUE: __sys_internal_listener_loop:from_host_fifo_info <- $r15
	//DEBUG_VALUE: __sys_internal_listener_loop:self_fifo_info <- $r14
	.loc	2 64 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/listener.c:64:13
	move r0, r16
	move r1, r18
	move r2, r17
	call r23, fifo_produce
.Ltmp12:
.LBB0_4:                                //   in Loop: Header=BB0_1 Depth=1
	//DEBUG_VALUE: __sys_internal_listener_loop:id <- $r19
	//DEBUG_VALUE: __sys_internal_listener_loop:request <- $r18
	//DEBUG_VALUE: __sys_internal_listener_loop:request_size <- $r17
	//DEBUG_VALUE: __sys_internal_listener_loop:to_host_fifo_info <- $r16
	//DEBUG_VALUE: __sys_internal_listener_loop:from_host_fifo_info <- $r15
	//DEBUG_VALUE: __sys_internal_listener_loop:self_fifo_info <- $r14
	.loc	2 66 13                         // uPIMulator_frontend/sdk/syslib/listener.c:66:13
	move r0, r15
	move r1, r18
	move r2, r17
	call r23, fetch_request
.Ltmp13:
	.loc	2 66 13 is_stmt 0               // uPIMulator_frontend/sdk/syslib/listener.c:66:13
	jeq r0, 0, .LBB0_1
.Ltmp14:
// %bb.5:                               //   in Loop: Header=BB0_1 Depth=1
	//DEBUG_VALUE: __sys_internal_listener_loop:id <- $r19
	//DEBUG_VALUE: __sys_internal_listener_loop:request <- $r18
	//DEBUG_VALUE: __sys_internal_listener_loop:request_size <- $r17
	//DEBUG_VALUE: __sys_internal_listener_loop:to_host_fifo_info <- $r16
	//DEBUG_VALUE: __sys_internal_listener_loop:from_host_fifo_info <- $r15
	//DEBUG_VALUE: __sys_internal_listener_loop:self_fifo_info <- $r14
	.loc	2 67 51 is_stmt 1               // uPIMulator_frontend/sdk/syslib/listener.c:67:51
	lw r1, r18, 0
.Ltmp15:
	//DEBUG_VALUE: fetch_recipient:id <- $r1
	.loc	2 36 15                         // uPIMulator_frontend/sdk/syslib/listener.c:36:15
	lsr r0, r1, 24
.Ltmp16:
	//DEBUG_VALUE: recipient <- $r0
	.loc	2 70 17                         // uPIMulator_frontend/sdk/syslib/listener.c:70:17
	jeq r0, r19, .LBB0_7
.Ltmp17:
// %bb.6:                               //   in Loop: Header=BB0_1 Depth=1
	//DEBUG_VALUE: __sys_internal_listener_loop:id <- $r19
	//DEBUG_VALUE: __sys_internal_listener_loop:request <- $r18
	//DEBUG_VALUE: __sys_internal_listener_loop:request_size <- $r17
	//DEBUG_VALUE: __sys_internal_listener_loop:to_host_fifo_info <- $r16
	//DEBUG_VALUE: __sys_internal_listener_loop:from_host_fifo_info <- $r15
	//DEBUG_VALUE: __sys_internal_listener_loop:self_fifo_info <- $r14
	//DEBUG_VALUE: recipient <- $r0
	//DEBUG_VALUE: fetch_request_id:id <- $r1
	.loc	2 42 15                         // uPIMulator_frontend/sdk/syslib/listener.c:42:15
	and r1, r1, 16777215
.Ltmp18:
	.loc	2 73 24                         // uPIMulator_frontend/sdk/syslib/listener.c:73:24
	sw r18, 0, r1
	.loc	2 76 13                         // uPIMulator_frontend/sdk/syslib/listener.c:76:13
	move r1, r18
	move r2, r17
	call r23, internal_actor_send
.Ltmp19:
	.loc	2 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/listener.c:0:13
	jump .LBB0_1
.Ltmp20:
.LBB0_7:
	//DEBUG_VALUE: __sys_internal_listener_loop:id <- $r19
	//DEBUG_VALUE: __sys_internal_listener_loop:request <- $r18
	//DEBUG_VALUE: __sys_internal_listener_loop:request_size <- $r17
	//DEBUG_VALUE: __sys_internal_listener_loop:to_host_fifo_info <- $r16
	//DEBUG_VALUE: __sys_internal_listener_loop:from_host_fifo_info <- $r15
	//DEBUG_VALUE: __sys_internal_listener_loop:self_fifo_info <- $r14
	.loc	2 82 1 is_stmt 1                // uPIMulator_frontend/sdk/syslib/listener.c:82:1
	ld d18, r22, -32
.Ltmp21:
	ld d16, r22, -24
.Ltmp22:
	ld d14, r22, -16
.Ltmp23:
	ld d22, r22, -8
	jump r23
.Ltmp24:
.Lfunc_end0:
	.size	__sys_internal_listener_loop, .Lfunc_end0-__sys_internal_listener_loop
	.cfi_endproc
	.file	4 "/root" "uPIMulator_frontend/sdk/syslib/sysdef.h"
	.section	.stack_sizes,"o",@progbits,.text.__sys_internal_listener_loop
	.long	.Lfunc_begin0
	.byte	32
	.section	.text.__sys_internal_listener_loop,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp6-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp6-.Lfunc_begin0
	.long	.Ltmp21-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	98                              // DW_OP_reg18
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp5-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp5-.Lfunc_begin0
	.long	.Ltmp22-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	97                              // DW_OP_reg17
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Ltmp1-.Lfunc_begin0
	.long	.Ltmp23-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp23-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	0
	.long	0
.Ldebug_loc4:
	.long	.Ltmp4-.Lfunc_begin0
	.long	.Ltmp22-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	96                              // DW_OP_reg16
	.long	0
	.long	0
.Ldebug_loc5:
	.long	.Ltmp7-.Lfunc_begin0
	.long	.Ltmp21-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	99                              // DW_OP_reg19
	.long	0
	.long	0
.Ldebug_loc6:
	.long	.Ltmp16-.Lfunc_begin0
	.long	.Ltmp20-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	11                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	0                               // DW_CHILDREN_no
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	12                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	1                               // DW_CHILDREN_yes
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	13                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	28                              // DW_AT_const_value
	.byte	15                              // DW_FORM_udata
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	14                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	15                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	16                              // Abbreviation Code
	.ascii	"\211\202\001"                  // DW_TAG_GNU_call_site
	.byte	0                               // DW_CHILDREN_no
	.ascii	"\223B"                         // DW_AT_GNU_call_site_target
	.byte	24                              // DW_FORM_exprloc
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x1d0 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x5 DW_TAG_pointer_type
	.long	43                              // DW_AT_type
	.byte	3                               // Abbrev [3] 0x2b:0xb DW_TAG_typedef
	.long	54                              // DW_AT_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	48                              // DW_AT_decl_line
	.byte	4                               // Abbrev [4] 0x36:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	5                               // Abbrev [5] 0x3d:0x18 DW_TAG_subprogram
	.long	.Linfo_string5                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	27                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	43                              // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	6                               // Abbrev [6] 0x49:0xb DW_TAG_formal_parameter
	.long	.Linfo_string6                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	27                              // DW_AT_decl_line
	.long	85                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	3                               // Abbrev [3] 0x55:0xb DW_TAG_typedef
	.long	54                              // DW_AT_type
	.long	.Linfo_string7                  // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	27                              // DW_AT_decl_line
	.byte	5                               // Abbrev [5] 0x60:0x18 DW_TAG_subprogram
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	20                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	43                              // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	6                               // Abbrev [6] 0x6c:0xb DW_TAG_formal_parameter
	.long	.Linfo_string9                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	20                              // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x78:0xc DW_TAG_subprogram
	.long	.Linfo_string10                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	33                              // DW_AT_decl_line
	.long	85                              // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0x84:0x18 DW_TAG_subprogram
	.long	.Linfo_string11                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	34                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	85                              // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	6                               // Abbrev [6] 0x90:0xb DW_TAG_formal_parameter
	.long	.Linfo_string12                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	34                              // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	5                               // Abbrev [5] 0x9c:0x18 DW_TAG_subprogram
	.long	.Linfo_string13                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	40                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	85                              // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	6                               // Abbrev [6] 0xa8:0xb DW_TAG_formal_parameter
	.long	.Linfo_string12                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	40                              // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	8                               // Abbrev [8] 0xb4:0x126 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string14                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	46                              // DW_AT_decl_line
                                        // DW_AT_prototyped
                                        // DW_AT_external
	.byte	9                               // Abbrev [9] 0xc5:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string15                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	46                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	9                               // Abbrev [9] 0xd4:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string16                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	46                              // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	10                              // Abbrev [10] 0xe3:0xf DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string17                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	49                              // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	10                              // Abbrev [10] 0xf2:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string18                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	50                              // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	10                              // Abbrev [10] 0x101:0xf DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	.Linfo_string19                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	51                              // DW_AT_decl_line
	.long	43                              // DW_AT_type
	.byte	10                              // Abbrev [10] 0x110:0xf DW_TAG_variable
	.long	.Ldebug_loc5                    // DW_AT_location
	.long	.Linfo_string12                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	48                              // DW_AT_decl_line
	.long	85                              // DW_AT_type
	.byte	11                              // Abbrev [11] 0x11f:0x10 DW_TAG_inlined_subroutine
	.long	61                              // DW_AT_abstract_origin
	.long	.Ltmp0                          // DW_AT_low_pc
	.long	.Ltmp1-.Ltmp0                   // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	53                              // DW_AT_call_line
	.byte	22                              // DW_AT_call_column
	.byte	12                              // Abbrev [12] 0x12f:0x17 DW_TAG_inlined_subroutine
	.long	96                              // DW_AT_abstract_origin
	.long	.Ltmp1                          // DW_AT_low_pc
	.long	.Ltmp3-.Ltmp1                   // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	54                              // DW_AT_call_line
	.byte	27                              // DW_AT_call_column
	.byte	13                              // Abbrev [13] 0x13f:0x6 DW_TAG_formal_parameter
	.byte	0                               // DW_AT_const_value
	.long	108                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	12                              // Abbrev [12] 0x146:0x17 DW_TAG_inlined_subroutine
	.long	96                              // DW_AT_abstract_origin
	.long	.Ltmp3                          // DW_AT_low_pc
	.long	.Ltmp6-.Ltmp3                   // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	55                              // DW_AT_call_line
	.byte	25                              // DW_AT_call_column
	.byte	13                              // Abbrev [13] 0x156:0x6 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_const_value
	.long	108                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	11                              // Abbrev [11] 0x15d:0x10 DW_TAG_inlined_subroutine
	.long	120                             // DW_AT_abstract_origin
	.long	.Ltmp6                          // DW_AT_low_pc
	.long	.Ltmp7-.Ltmp6                   // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	48                              // DW_AT_call_line
	.byte	20                              // DW_AT_call_column
	.byte	14                              // Abbrev [14] 0x16d:0x49 DW_TAG_lexical_block
	.long	.Ltmp14                         // DW_AT_low_pc
	.long	.Ltmp20-.Ltmp14                 // DW_AT_high_pc
	.byte	10                              // Abbrev [10] 0x176:0xf DW_TAG_variable
	.long	.Ldebug_loc6                    // DW_AT_location
	.long	.Linfo_string6                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	67                              // DW_AT_decl_line
	.long	85                              // DW_AT_type
	.byte	12                              // Abbrev [12] 0x185:0x18 DW_TAG_inlined_subroutine
	.long	132                             // DW_AT_abstract_origin
	.long	.Ltmp15                         // DW_AT_low_pc
	.long	.Ltmp16-.Ltmp15                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	67                              // DW_AT_call_line
	.byte	35                              // DW_AT_call_column
	.byte	15                              // Abbrev [15] 0x195:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	144                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	12                              // Abbrev [12] 0x19d:0x18 DW_TAG_inlined_subroutine
	.long	156                             // DW_AT_abstract_origin
	.long	.Ltmp17                         // DW_AT_low_pc
	.long	.Ltmp18-.Ltmp17                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	73                              // DW_AT_call_line
	.byte	26                              // DW_AT_call_column
	.byte	15                              // Abbrev [15] 0x1ad:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	168                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	16                              // Abbrev [16] 0x1b6:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp8                          // DW_AT_low_pc
	.byte	16                              // Abbrev [16] 0x1bd:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp10                         // DW_AT_low_pc
	.byte	16                              // Abbrev [16] 0x1c4:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp12                         // DW_AT_low_pc
	.byte	16                              // Abbrev [16] 0x1cb:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp13                         // DW_AT_low_pc
	.byte	16                              // Abbrev [16] 0x1d2:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp19                         // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/listener.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=154
.Linfo_string3:
	.asciz	"unsigned int"                  // string offset=175
.Linfo_string4:
	.asciz	"uint32_t"                      // string offset=188
.Linfo_string5:
	.asciz	"fifo_fetch_info"               // string offset=197
.Linfo_string6:
	.asciz	"recipient"                     // string offset=213
.Linfo_string7:
	.asciz	"sysname_t"                     // string offset=223
.Linfo_string8:
	.asciz	"fifo_sys_fetch_info"           // string offset=233
.Linfo_string9:
	.asciz	"fid"                           // string offset=253
.Linfo_string10:
	.asciz	"me"                            // string offset=257
.Linfo_string11:
	.asciz	"fetch_recipient"               // string offset=260
.Linfo_string12:
	.asciz	"id"                            // string offset=276
.Linfo_string13:
	.asciz	"fetch_request_id"              // string offset=279
.Linfo_string14:
	.asciz	"__sys_internal_listener_loop"  // string offset=296
.Linfo_string15:
	.asciz	"request"                       // string offset=325
.Linfo_string16:
	.asciz	"request_size"                  // string offset=333
.Linfo_string17:
	.asciz	"self_fifo_info"                // string offset=346
.Linfo_string18:
	.asciz	"from_host_fifo_info"           // string offset=361
.Linfo_string19:
	.asciz	"to_host_fifo_info"             // string offset=381
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
