	.text
	.file	"moddi3.c"
	.section	.text.__moddi3,"ax",@progbits
	.globl	__moddi3                        // -- Begin function __moddi3
	.type	__moddi3,@function
__moddi3:                               // @__moddi3
.Lfunc_begin0:
	.file	1 "/root" "uPIMulator_frontend/sdk/syslib/moddi3.c"
	.loc	1 17 0                          // uPIMulator_frontend/sdk/syslib/moddi3.c:17:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __moddi3:dividend <- $d0
	//DEBUG_VALUE: __moddi3:divider <- $d2
	.cfi_def_cfa_offset -16
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 8, d22
	add r22, r22, 16
	.cfi_offset 15, -16
	.cfi_offset 14, -12
	sd r22, -16, d14
	move.s d4, 0
	//DEBUG_VALUE: __moddi3:divider <- $d2
	//DEBUG_VALUE: __moddi3:dividend <- $d0
.Ltmp0:
	.loc	1 18 9 prologue_end             // uPIMulator_frontend/sdk/syslib/moddi3.c:18:9
	sub zero, r1, r5
	subc zero, r0, r4, lts, .LBB0_4
.Ltmp1:
// %bb.1:
	//DEBUG_VALUE: __moddi3:divider <- $d2
	//DEBUG_VALUE: __moddi3:dividend <- $d0
	.loc	1 19 13                         // uPIMulator_frontend/sdk/syslib/moddi3.c:19:13
	sub zero, r3, r5
	subc zero, r2, r4, ges, .LBB0_2
.Ltmp2:
// %bb.3:
	//DEBUG_VALUE: __moddi3:divider <- $d2
	//DEBUG_VALUE: __moddi3:dividend <- $d0
	.loc	1 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/moddi3.c:0:13
	move.s d4, 0
.Ltmp3:
	.loc	1 22 39 is_stmt 1               // uPIMulator_frontend/sdk/syslib/moddi3.c:22:39
	sub r3, r5, r3
.Ltmp4:
	subc r2, r4, r2
.Ltmp5:
.LBB0_2:
	//DEBUG_VALUE: __moddi3:dividend <- $d0
	.loc	1 0 39 is_stmt 0                // uPIMulator_frontend/sdk/syslib/moddi3.c:0:39
	move r4, 1
	call r23, __udiv64
.Ltmp6:
	.loc	1 31 1 is_stmt 1                // uPIMulator_frontend/sdk/syslib/moddi3.c:31:1
	ld d14, r22, -16
	ld d22, r22, -8
	jump r23
.Ltmp7:
.LBB0_4:
	//DEBUG_VALUE: __moddi3:divider <- $d2
	//DEBUG_VALUE: __moddi3:dividend <- $d0
	.loc	1 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/moddi3.c:0:0
	sub r1, r5, r1
.Ltmp8:
	subc r0, r4, r0
.Ltmp9:
	.loc	1 24 16 is_stmt 1               // uPIMulator_frontend/sdk/syslib/moddi3.c:24:16
	sub zero, r3, r5
	subc zero, r2, r4, lts, .LBB0_6
.Ltmp10:
// %bb.5:
	//DEBUG_VALUE: __moddi3:divider <- $d2
	.loc	1 0 16 is_stmt 0                // uPIMulator_frontend/sdk/syslib/moddi3.c:0:16
	move r4, 1
.Ltmp11:
	.loc	1 26 17 is_stmt 1               // uPIMulator_frontend/sdk/syslib/moddi3.c:26:17
	call r23, __udiv64
.Ltmp12:
	.loc	1 0 17 is_stmt 0                // uPIMulator_frontend/sdk/syslib/moddi3.c:0:17
	move.s d2, 0
.Ltmp13:
	.loc	1 26 16                         // uPIMulator_frontend/sdk/syslib/moddi3.c:26:16
	sub r1, r3, r1
	subc r0, r2, r0
.Ltmp14:
	.loc	1 31 1 is_stmt 1                // uPIMulator_frontend/sdk/syslib/moddi3.c:31:1
	ld d14, r22, -16
	ld d22, r22, -8
	jump r23
.LBB0_6:
.Ltmp15:
	//DEBUG_VALUE: __moddi3:divider <- $d2
	.loc	1 0 1 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/moddi3.c:0:1
	move.s d14, 0
.Ltmp16:
	.loc	1 29 37 is_stmt 1               // uPIMulator_frontend/sdk/syslib/moddi3.c:29:37
	sub r3, r15, r3
.Ltmp17:
	subc r2, r14, r2
	move r4, 1
	.loc	1 29 17 is_stmt 0               // uPIMulator_frontend/sdk/syslib/moddi3.c:29:17
	call r23, __udiv64
.Ltmp18:
	.loc	1 29 16                         // uPIMulator_frontend/sdk/syslib/moddi3.c:29:16
	sub r1, r15, r1
	subc r0, r14, r0
.Ltmp19:
	.loc	1 31 1 is_stmt 1                // uPIMulator_frontend/sdk/syslib/moddi3.c:31:1
	ld d14, r22, -16
	ld d22, r22, -8
	jump r23
.Ltmp20:
.Lfunc_end0:
	.size	__moddi3, .Lfunc_end0-__moddi3
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__moddi3
	.long	.Lfunc_begin0
	.byte	16
	.section	.text.__moddi3,"ax",@progbits
                                        // -- End function
	.file	2 "/root" "uPIMulator_frontend/sdk/stdlib/stdint.h"
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp8-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp4-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp7-.Lfunc_begin0
	.long	.Ltmp13-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp15-.Lfunc_begin0
	.long	.Ltmp17-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.ascii	"\211\202\001"                  // DW_TAG_GNU_call_site
	.byte	0                               // DW_CHILDREN_no
	.ascii	"\223B"                         // DW_AT_GNU_call_site_target
	.byte	24                              // DW_FORM_exprloc
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x77 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x49 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string3                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	16                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	111                             // DW_AT_type
                                        // DW_AT_external
	.byte	3                               // Abbrev [3] 0x3b:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string6                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	16                              // DW_AT_decl_line
	.long	111                             // DW_AT_type
	.byte	3                               // Abbrev [3] 0x4a:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string7                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	16                              // DW_AT_decl_line
	.long	111                             // DW_AT_type
	.byte	4                               // Abbrev [4] 0x59:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp6                          // DW_AT_low_pc
	.byte	4                               // Abbrev [4] 0x60:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp12                         // DW_AT_low_pc
	.byte	4                               // Abbrev [4] 0x67:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp18                         // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	5                               // Abbrev [5] 0x6f:0xb DW_TAG_typedef
	.long	122                             // DW_AT_type
	.long	.Linfo_string5                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	33                              // DW_AT_decl_line
	.byte	6                               // Abbrev [6] 0x7a:0x7 DW_TAG_base_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/moddi3.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=152
.Linfo_string3:
	.asciz	"__moddi3"                      // string offset=173
.Linfo_string4:
	.asciz	"long long int"                 // string offset=182
.Linfo_string5:
	.asciz	"int64_t"                       // string offset=196
.Linfo_string6:
	.asciz	"dividend"                      // string offset=204
.Linfo_string7:
	.asciz	"divider"                       // string offset=213
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
