	.text
	.file	"mul64.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/stdint.h"
	.section	.text.__muldi3,"ax",@progbits
	.globl	__muldi3                        // -- Begin function __muldi3
	.type	__muldi3,@function
__muldi3:                               // @__muldi3
.Lfunc_begin0:
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/mul64.c"
	.loc	2 133 0                         // uPIMulator_frontend/sdk/syslib/mul64.c:133:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __muldi3:x <- $d0
	//DEBUG_VALUE: __muldi3:x <- $d0
	//DEBUG_VALUE: __muldi3:y <- $d2
	//DEBUG_VALUE: __muldi3:y <- $d2
	//DEBUG_VALUE: _mul00:a <- $r1
	//DEBUG_VALUE: _mul00:b <- $r3
	.cfi_def_cfa_offset 0
	.cfi_offset 15, 8
	.cfi_offset 14, 12
	sd r22, 8, d14
	.cfi_offset 17, 0
	.cfi_offset 16, 4
	sd r22, 0, d16
.Ltmp0:
	//DEBUG_VALUE: __muldi3:xl <- $r1
	//DEBUG_VALUE: __muldi3:xh <- $r0
	//DEBUG_VALUE: __muldi3:yl <- $r3
	//DEBUG_VALUE: __muldi3:yh <- $r2
	.loc	2 40 5 prologue_end             // uPIMulator_frontend/sdk/syslib/mul64.c:40:5
	// inline asm
	mul_ul_ul r4, r1, r3
	// inline asm
.Ltmp1:
	//DEBUG_VALUE: _mul00:r <- $r4
	.loc	2 144 10                        // uPIMulator_frontend/sdk/syslib/mul64.c:144:10
	and r4, r4, 65535
.Ltmp2:
	//DEBUG_VALUE: _mul01:b <- $r3
	//DEBUG_VALUE: _mul01:a <- $r1
	//DEBUG_VALUE: __muldi3:rl <- [DW_OP_LLVM_convert 32 7, DW_OP_LLVM_convert 64 7, DW_OP_stack_value] $r4
	//DEBUG_VALUE: __muldi3:p0 <- [DW_OP_LLVM_convert 32 7, DW_OP_LLVM_convert 64 7, DW_OP_stack_value] $r4
	.loc	2 52 5                          // uPIMulator_frontend/sdk/syslib/mul64.c:52:5
	// inline asm
	mul_ul_uh r5, r1, r3
	// inline asm
.Ltmp3:
	//DEBUG_VALUE: _mul01:r <- $r5
	.loc	2 145 10                        // uPIMulator_frontend/sdk/syslib/mul64.c:145:10
	and r5, r5, 65535
.Ltmp4:
	//DEBUG_VALUE: _mul01:b <- $r1
	//DEBUG_VALUE: _mul01:a <- $r3
	.loc	2 52 5                          // uPIMulator_frontend/sdk/syslib/mul64.c:52:5
	// inline asm
	mul_ul_uh r6, r3, r1
	// inline asm
.Ltmp5:
	//DEBUG_VALUE: _mul01:r <- $r6
	.loc	2 145 28                        // uPIMulator_frontend/sdk/syslib/mul64.c:145:28
	and r6, r6, 65535
	.loc	2 145 26 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:145:26
	add r5, r6, r5
.Ltmp6:
	//DEBUG_VALUE: __muldi3:p1 <- $r5
	.loc	2 146 8 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mul64.c:146:8
	lsl_add r4, r4, r5, 8
.Ltmp7:
	move.u d6, r4
.Ltmp8:
	//DEBUG_VALUE: __muldi3:rl <- $d6
	.loc	2 147 10                        // uPIMulator_frontend/sdk/syslib/mul64.c:147:10
	lsr r4, r3, 16
.Ltmp9:
	//DEBUG_VALUE: _mul00:a <- $r1
	//DEBUG_VALUE: _mul00:b <- $r4
	.loc	2 40 5                          // uPIMulator_frontend/sdk/syslib/mul64.c:40:5
	// inline asm
	mul_ul_ul r5, r1, r4
	// inline asm
.Ltmp10:
	//DEBUG_VALUE: _mul00:r <- $r5
	.loc	2 147 10                        // uPIMulator_frontend/sdk/syslib/mul64.c:147:10
	and r8, r5, 65535
	.loc	2 147 28 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:147:28
	lsr r5, r1, 16
.Ltmp11:
	//DEBUG_VALUE: _mul00:a <- $r3
	//DEBUG_VALUE: _mul00:b <- $r5
	.loc	2 40 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/mul64.c:40:5
	// inline asm
	mul_ul_ul r9, r3, r5
	// inline asm
.Ltmp12:
	//DEBUG_VALUE: _mul00:r <- $r9
	.loc	2 147 28                        // uPIMulator_frontend/sdk/syslib/mul64.c:147:28
	and r9, r9, 65535
	.loc	2 147 26 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:147:26
	add r8, r9, r8
.Ltmp13:
	//DEBUG_VALUE: _mul11:b <- $r3
	//DEBUG_VALUE: _mul11:a <- $r1
	.loc	2 67 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/mul64.c:67:5
	// inline asm
	mul_uh_uh r9, r1, r3
	// inline asm
.Ltmp14:
	//DEBUG_VALUE: _mul11:r <- $r9
	.loc	2 147 46                        // uPIMulator_frontend/sdk/syslib/mul64.c:147:46
	and r9, r9, 65535
	.loc	2 147 44 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:147:44
	add r8, r8, r9
.Ltmp15:
	//DEBUG_VALUE: __muldi3:p2 <- $r8
	.loc	2 148 12 is_stmt 1              // uPIMulator_frontend/sdk/syslib/mul64.c:148:12
	move.u d8, r8
.Ltmp16:
	.loc	2 148 25 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:148:25
	lslx r10, r9, 16
	lsl_add r10, r10, r8, 16
	lsl r11, r9, 16
	.loc	2 148 8                         // uPIMulator_frontend/sdk/syslib/mul64.c:148:8
	add r7, r11, r7
.Ltmp17:
	addc r6, r10, r6
.Ltmp18:
	//DEBUG_VALUE: _mul01:b <- $r4
	//DEBUG_VALUE: _mul01:a <- $r1
	//DEBUG_VALUE: __muldi3:rl <- $d6
	.loc	2 52 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/mul64.c:52:5
	// inline asm
	mul_ul_uh r8, r1, r4
	// inline asm
.Ltmp19:
	//DEBUG_VALUE: _mul01:r <- $r8
	.loc	2 149 10                        // uPIMulator_frontend/sdk/syslib/mul64.c:149:10
	and r8, r8, 65535
.Ltmp20:
	//DEBUG_VALUE: _mul01:b <- $r5
	//DEBUG_VALUE: _mul01:a <- $r3
	.loc	2 52 5                          // uPIMulator_frontend/sdk/syslib/mul64.c:52:5
	// inline asm
	mul_ul_uh r9, r3, r5
	// inline asm
.Ltmp21:
	//DEBUG_VALUE: _mul01:r <- $r9
	.loc	2 149 28                        // uPIMulator_frontend/sdk/syslib/mul64.c:149:28
	and r9, r9, 65535
	.loc	2 149 26 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:149:26
	add r8, r9, r8
.Ltmp22:
	//DEBUG_VALUE: _mul12:r <- $r4
	//DEBUG_VALUE: _mul12:b <- $r3
	//DEBUG_VALUE: _mul12:a <- $r1
	.loc	2 79 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/mul64.c:79:5
	// inline asm
	mul_uh_ul r9, r1, r4
	// inline asm
.Ltmp23:
	//DEBUG_VALUE: _mul12:r <- $r9
	.loc	2 149 46                        // uPIMulator_frontend/sdk/syslib/mul64.c:149:46
	and r9, r9, 65535
.Ltmp24:
	.loc	2 149 44 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:149:44
	add r8, r8, r9
.Ltmp25:
	//DEBUG_VALUE: _mul12:r <- $r5
	//DEBUG_VALUE: _mul12:b <- $r1
	//DEBUG_VALUE: _mul12:a <- $r3
	.loc	2 79 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/mul64.c:79:5
	// inline asm
	mul_uh_ul r9, r3, r5
	// inline asm
.Ltmp26:
	//DEBUG_VALUE: _mul12:r <- $r9
	.loc	2 149 64                        // uPIMulator_frontend/sdk/syslib/mul64.c:149:64
	and r9, r9, 65535
.Ltmp27:
	.loc	2 149 62 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:149:62
	add r8, r8, r9
.Ltmp28:
	//DEBUG_VALUE: __muldi3:p3 <- $r8
	.loc	2 150 12 is_stmt 1              // uPIMulator_frontend/sdk/syslib/mul64.c:150:12
	move.u d10, r8
	.loc	2 150 25 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:150:25
	lslx r8, r11, 24
.Ltmp29:
	lsl_add r8, r8, r10, 24
	lsl r9, r11, 24
.Ltmp30:
	.loc	2 40 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/mul64.c:40:5
	// inline asm
	mul_ul_ul r10, r1, r2
	// inline asm
.Ltmp31:
	//DEBUG_VALUE: _mul00:r <- $r10
	.loc	2 151 10                        // uPIMulator_frontend/sdk/syslib/mul64.c:151:10
	and r10, r10, 65535
.Ltmp32:
	//DEBUG_VALUE: _mul00:b <- $r0
	//DEBUG_VALUE: _mul00:a <- $r3
	.loc	2 40 5                          // uPIMulator_frontend/sdk/syslib/mul64.c:40:5
	// inline asm
	mul_ul_ul r11, r3, r0
	// inline asm
.Ltmp33:
	//DEBUG_VALUE: _mul00:r <- $r11
	.loc	2 151 28                        // uPIMulator_frontend/sdk/syslib/mul64.c:151:28
	and r11, r11, 65535
	.loc	2 151 26 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:151:26
	add r10, r11, r10
.Ltmp34:
	//DEBUG_VALUE: _mul11:b <- $r4
	//DEBUG_VALUE: _mul11:a <- $r1
	.loc	2 67 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/mul64.c:67:5
	// inline asm
	mul_uh_uh r11, r1, r4
	// inline asm
.Ltmp35:
	//DEBUG_VALUE: _mul11:r <- $r11
	.loc	2 151 46                        // uPIMulator_frontend/sdk/syslib/mul64.c:151:46
	and r11, r11, 65535
	.loc	2 151 44 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:151:44
	add r10, r10, r11
.Ltmp36:
	//DEBUG_VALUE: _mul11:b <- $r5
	//DEBUG_VALUE: _mul11:a <- $r3
	.loc	2 67 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/mul64.c:67:5
	// inline asm
	mul_uh_uh r11, r3, r5
	// inline asm
.Ltmp37:
	//DEBUG_VALUE: _mul11:r <- $r11
	.loc	2 151 64                        // uPIMulator_frontend/sdk/syslib/mul64.c:151:64
	and r11, r11, 65535
	.loc	2 151 62 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:151:62
	add r10, r10, r11
.Ltmp38:
	//DEBUG_VALUE: _mul00:b <- $r4
	//DEBUG_VALUE: _mul00:a <- $r5
	.loc	2 40 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/mul64.c:40:5
	// inline asm
	mul_ul_ul r11, r5, r4
	// inline asm
.Ltmp39:
	//DEBUG_VALUE: _mul00:r <- $r11
	.loc	2 151 82                        // uPIMulator_frontend/sdk/syslib/mul64.c:151:82
	and r11, r11, 65535
	.loc	2 151 80 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:151:80
	add r10, r10, r11
.Ltmp40:
	//DEBUG_VALUE: _mul01:b <- $r2
	//DEBUG_VALUE: _mul01:a <- $r1
	//DEBUG_VALUE: __muldi3:rh <- $r10
	//DEBUG_VALUE: __muldi3:p4 <- $r10
	.loc	2 52 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/mul64.c:52:5
	// inline asm
	mul_ul_uh r11, r1, r2
	// inline asm
.Ltmp41:
	//DEBUG_VALUE: _mul01:r <- $r11
	.loc	2 153 10                        // uPIMulator_frontend/sdk/syslib/mul64.c:153:10
	and r11, r11, 65535
.Ltmp42:
	//DEBUG_VALUE: _mul01:b <- $r0
	//DEBUG_VALUE: _mul01:a <- $r3
	.loc	2 52 5                          // uPIMulator_frontend/sdk/syslib/mul64.c:52:5
	// inline asm
	mul_ul_uh r12, r3, r0
	// inline asm
.Ltmp43:
	//DEBUG_VALUE: _mul01:r <- $r12
	.loc	2 153 28                        // uPIMulator_frontend/sdk/syslib/mul64.c:153:28
	and r12, r12, 65535
	.loc	2 153 26 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:153:26
	add r11, r12, r11
.Ltmp44:
	//DEBUG_VALUE: _mul01:b <- $r1
	//DEBUG_VALUE: _mul01:a <- $r2
	.loc	2 52 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/mul64.c:52:5
	// inline asm
	mul_ul_uh r12, r2, r1
	// inline asm
.Ltmp45:
	//DEBUG_VALUE: _mul01:r <- $r12
	.loc	2 153 46                        // uPIMulator_frontend/sdk/syslib/mul64.c:153:46
	and r12, r12, 65535
	.loc	2 153 44 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:153:44
	add r11, r11, r12
.Ltmp46:
	//DEBUG_VALUE: _mul01:b <- $r3
	//DEBUG_VALUE: _mul01:a <- $r0
	.loc	2 52 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/mul64.c:52:5
	// inline asm
	mul_ul_uh r12, r0, r3
	// inline asm
.Ltmp47:
	//DEBUG_VALUE: _mul01:r <- $r12
	.loc	2 153 64                        // uPIMulator_frontend/sdk/syslib/mul64.c:153:64
	and r12, r12, 65535
	.loc	2 153 62 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:153:62
	add r11, r11, r12
.Ltmp48:
	//DEBUG_VALUE: _mul01:b <- $r4
	//DEBUG_VALUE: _mul01:a <- $r5
	.loc	2 52 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/mul64.c:52:5
	// inline asm
	mul_ul_uh r12, r5, r4
	// inline asm
.Ltmp49:
	//DEBUG_VALUE: _mul01:r <- $r12
	.loc	2 153 82                        // uPIMulator_frontend/sdk/syslib/mul64.c:153:82
	and r12, r12, 65535
	.loc	2 153 80 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:153:80
	add r11, r11, r12
.Ltmp50:
	//DEBUG_VALUE: _mul01:b <- $r5
	//DEBUG_VALUE: _mul01:a <- $r4
	.loc	2 52 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/mul64.c:52:5
	// inline asm
	mul_ul_uh r12, r4, r5
	// inline asm
.Ltmp51:
	//DEBUG_VALUE: _mul01:r <- $r12
	.loc	2 153 100                       // uPIMulator_frontend/sdk/syslib/mul64.c:153:100
	and r12, r12, 65535
	.loc	2 153 98 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:153:98
	add r11, r11, r12
.Ltmp52:
	//DEBUG_VALUE: __muldi3:p5 <- $r11
	.loc	2 154 8 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mul64.c:154:8
	lsl_add r10, r10, r11, 8
.Ltmp53:
	//DEBUG_VALUE: __muldi3:rh <- $r10
	.loc	2 155 10                        // uPIMulator_frontend/sdk/syslib/mul64.c:155:10
	lsr.u d12, r2, 16
.Ltmp54:
	//DEBUG_VALUE: _mul00:a <- $r1
	//DEBUG_VALUE: _mul00:b <- $r13
	.loc	2 40 5                          // uPIMulator_frontend/sdk/syslib/mul64.c:40:5
	// inline asm
	mul_ul_ul r11, r1, r13
	// inline asm
.Ltmp55:
	//DEBUG_VALUE: _mul00:r <- $r11
	.loc	2 155 10                        // uPIMulator_frontend/sdk/syslib/mul64.c:155:10
	and r11, r11, 65535
	.loc	2 155 28 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:155:28
	lsr.u d14, r0, 16
.Ltmp56:
	//DEBUG_VALUE: _mul00:a <- $r3
	//DEBUG_VALUE: _mul00:b <- $r15
	.loc	2 40 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/mul64.c:40:5
	// inline asm
	mul_ul_ul r16, r3, r15
	// inline asm
.Ltmp57:
	//DEBUG_VALUE: _mul00:r <- $r16
	.loc	2 155 28                        // uPIMulator_frontend/sdk/syslib/mul64.c:155:28
	and r16, r16, 65535
	.loc	2 155 26 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:155:26
	add r11, r16, r11
.Ltmp58:
	//DEBUG_VALUE: _mul11:b <- $r2
	//DEBUG_VALUE: _mul11:a <- $r1
	.loc	2 67 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/mul64.c:67:5
	// inline asm
	mul_uh_uh r16, r1, r2
	// inline asm
.Ltmp59:
	//DEBUG_VALUE: _mul11:r <- $r16
	.loc	2 155 46                        // uPIMulator_frontend/sdk/syslib/mul64.c:155:46
	and r16, r16, 65535
	.loc	2 155 44 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:155:44
	add r11, r11, r16
.Ltmp60:
	//DEBUG_VALUE: _mul11:b <- $r0
	//DEBUG_VALUE: _mul11:a <- $r3
	.loc	2 67 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/mul64.c:67:5
	// inline asm
	mul_uh_uh r16, r3, r0
	// inline asm
.Ltmp61:
	//DEBUG_VALUE: _mul11:r <- $r16
	.loc	2 155 62                        // uPIMulator_frontend/sdk/syslib/mul64.c:155:62
	add r11, r11, r16
.Ltmp62:
	//DEBUG_VALUE: _mul00:b <- $r5
	//DEBUG_VALUE: _mul00:a <- $r2
	.loc	2 40 5                          // uPIMulator_frontend/sdk/syslib/mul64.c:40:5
	// inline asm
	mul_ul_ul r16, r2, r5
	// inline asm
.Ltmp63:
	//DEBUG_VALUE: _mul00:r <- $r16
	.loc	2 155 80                        // uPIMulator_frontend/sdk/syslib/mul64.c:155:80
	add r11, r11, r16
.Ltmp64:
	//DEBUG_VALUE: _mul00:b <- $r4
	//DEBUG_VALUE: _mul00:a <- $r0
	.loc	2 40 5                          // uPIMulator_frontend/sdk/syslib/mul64.c:40:5
	// inline asm
	mul_ul_ul r16, r0, r4
	// inline asm
.Ltmp65:
	//DEBUG_VALUE: _mul00:r <- $r16
	.loc	2 155 98                        // uPIMulator_frontend/sdk/syslib/mul64.c:155:98
	add r11, r11, r16
.Ltmp66:
	//DEBUG_VALUE: _mul11:b <- $r4
	//DEBUG_VALUE: _mul11:a <- $r5
	.loc	2 67 5                          // uPIMulator_frontend/sdk/syslib/mul64.c:67:5
	// inline asm
	mul_uh_uh r16, r5, r4
	// inline asm
.Ltmp67:
	//DEBUG_VALUE: _mul11:r <- $r16
	.loc	2 156 9                         // uPIMulator_frontend/sdk/syslib/mul64.c:156:9
	add r11, r11, r16
.Ltmp68:
	//DEBUG_VALUE: __muldi3:p6 <- undef
	.loc	2 157 8                         // uPIMulator_frontend/sdk/syslib/mul64.c:157:8
	lsl_add r10, r10, r11, 16
.Ltmp69:
	//DEBUG_VALUE: _mul01:b <- $r13
	//DEBUG_VALUE: _mul01:a <- $r1
	//DEBUG_VALUE: __muldi3:rh <- $r10
	.loc	2 52 5                          // uPIMulator_frontend/sdk/syslib/mul64.c:52:5
	// inline asm
	mul_ul_uh r11, r1, r13
	// inline asm
.Ltmp70:
	//DEBUG_VALUE: _mul01:r <- $r11
	.loc	2 158 10                        // uPIMulator_frontend/sdk/syslib/mul64.c:158:10
	and r11, r11, 65535
.Ltmp71:
	//DEBUG_VALUE: _mul01:b <- $r15
	//DEBUG_VALUE: _mul01:a <- $r3
	.loc	2 52 5                          // uPIMulator_frontend/sdk/syslib/mul64.c:52:5
	// inline asm
	mul_ul_uh r16, r3, r15
	// inline asm
.Ltmp72:
	//DEBUG_VALUE: _mul01:r <- $r16
	.loc	2 158 28                        // uPIMulator_frontend/sdk/syslib/mul64.c:158:28
	and r16, r16, 65535
	.loc	2 158 26 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:158:26
	add r11, r16, r11
.Ltmp73:
	//DEBUG_VALUE: _mul12:r <- $r13
	//DEBUG_VALUE: _mul12:b <- $r2
	//DEBUG_VALUE: _mul12:a <- $r1
	.loc	2 79 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/mul64.c:79:5
	// inline asm
	mul_uh_ul r12, r1, r13
	// inline asm
.Ltmp74:
	//DEBUG_VALUE: _mul12:r <- $r12
	.loc	2 158 46                        // uPIMulator_frontend/sdk/syslib/mul64.c:158:46
	and r12, r12, 65535
.Ltmp75:
	.loc	2 158 44 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:158:44
	add r11, r11, r12
.Ltmp76:
	//DEBUG_VALUE: _mul12:r <- $r15
	//DEBUG_VALUE: _mul12:b <- $r0
	//DEBUG_VALUE: _mul12:a <- $r3
	.loc	2 79 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/mul64.c:79:5
	// inline asm
	mul_uh_ul r12, r3, r15
	// inline asm
.Ltmp77:
	//DEBUG_VALUE: _mul12:r <- $r12
	.loc	2 158 64                        // uPIMulator_frontend/sdk/syslib/mul64.c:158:64
	and r12, r12, 65535
.Ltmp78:
	.loc	2 158 62 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:158:62
	add r11, r11, r12
.Ltmp79:
	//DEBUG_VALUE: _mul12:r <- $r5
	//DEBUG_VALUE: _mul12:b <- $r1
	//DEBUG_VALUE: _mul12:a <- $r2
	.loc	2 79 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/mul64.c:79:5
	// inline asm
	mul_uh_ul r12, r2, r5
	// inline asm
.Ltmp80:
	//DEBUG_VALUE: _mul12:r <- $r12
	.loc	2 158 80                        // uPIMulator_frontend/sdk/syslib/mul64.c:158:80
	add r11, r11, r12
.Ltmp81:
	//DEBUG_VALUE: _mul12:r <- $r4
	//DEBUG_VALUE: _mul12:b <- $r3
	//DEBUG_VALUE: _mul12:a <- $r0
	.loc	2 79 5                          // uPIMulator_frontend/sdk/syslib/mul64.c:79:5
	// inline asm
	mul_uh_ul r12, r0, r4
	// inline asm
.Ltmp82:
	//DEBUG_VALUE: _mul12:r <- $r12
	.loc	2 158 98                        // uPIMulator_frontend/sdk/syslib/mul64.c:158:98
	add r11, r11, r12
.Ltmp83:
	//DEBUG_VALUE: _mul01:b <- $r5
	//DEBUG_VALUE: _mul01:a <- $r2
	.loc	2 52 5                          // uPIMulator_frontend/sdk/syslib/mul64.c:52:5
	// inline asm
	mul_ul_uh r2, r2, r5
	// inline asm
.Ltmp84:
	//DEBUG_VALUE: _mul01:r <- $r2
	.loc	2 159 9                         // uPIMulator_frontend/sdk/syslib/mul64.c:159:9
	add r2, r11, r2
.Ltmp85:
	//DEBUG_VALUE: _mul01:b <- $r4
	//DEBUG_VALUE: _mul01:a <- $r0
	.loc	2 52 5                          // uPIMulator_frontend/sdk/syslib/mul64.c:52:5
	// inline asm
	mul_ul_uh r0, r0, r4
	// inline asm
.Ltmp86:
	//DEBUG_VALUE: _mul01:r <- $r0
	.loc	2 159 27                        // uPIMulator_frontend/sdk/syslib/mul64.c:159:27
	add r0, r2, r0
.Ltmp87:
	//DEBUG_VALUE: __muldi3:p7 <- undef
	.loc	2 160 8                         // uPIMulator_frontend/sdk/syslib/mul64.c:160:8
	lsl_add r0, r10, r0, 24
.Ltmp88:
	//DEBUG_VALUE: __muldi3:rh <- $r0
	.loc	2 162 19                        // uPIMulator_frontend/sdk/syslib/mul64.c:162:19
	move.s d0, r0
.Ltmp89:
	.loc	2 162 33 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:162:33
	move r3, 0
.Ltmp90:
	.loc	2 150 8 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mul64.c:150:8
	add r5, r7, r9
.Ltmp91:
	addc r4, r6, r8
.Ltmp92:
	//DEBUG_VALUE: _mul00:b <- undef
	//DEBUG_VALUE: _mul00:a <- undef
	//DEBUG_VALUE: __muldi3:rl <- $d4
	.loc	2 162 33                        // uPIMulator_frontend/sdk/syslib/mul64.c:162:33
	move r2, r1
	.loc	2 162 15 is_stmt 0              // uPIMulator_frontend/sdk/syslib/mul64.c:162:15
	add r1, r5, r3
	addc r0, r4, r2
	.loc	2 162 5                         // uPIMulator_frontend/sdk/syslib/mul64.c:162:5
	ld d16, r22, 0
	ld d14, r22, 8
.Ltmp93:
	jump r23
.Ltmp94:
.Lfunc_end0:
	.size	__muldi3, .Lfunc_end0-__muldi3
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__muldi3
	.long	.Lfunc_begin0
	.byte	16
	.section	.text.__muldi3,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp86-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp84-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp89-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp86-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc4:
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp90-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc5:
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp84-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc6:
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp7-.Lfunc_begin0
	.short	10                              // Loc expr size
	.byte	116                             // DW_OP_breg4
	.byte	0                               // 0
	.byte	16                              // DW_OP_constu
	.byte	255                             // 4294967295
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	15                              // 
	.byte	26                              // DW_OP_and
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp8-.Lfunc_begin0
	.long	.Ltmp17-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp18-.Lfunc_begin0
	.long	.Ltmp92-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp92-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc7:
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp7-.Lfunc_begin0
	.short	10                              // Loc expr size
	.byte	116                             // DW_OP_breg4
	.byte	0                               // 0
	.byte	16                              // DW_OP_constu
	.byte	255                             // 4294967295
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	15                              // 
	.byte	26                              // DW_OP_and
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc8:
	.long	.Ltmp6-.Lfunc_begin0
	.long	.Ltmp10-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	0
	.long	0
.Ldebug_loc9:
	.long	.Ltmp15-.Lfunc_begin0
	.long	.Ltmp16-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	88                              // DW_OP_reg8
	.long	0
	.long	0
.Ldebug_loc10:
	.long	.Ltmp22-.Lfunc_begin0
	.long	.Ltmp23-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp23-.Lfunc_begin0
	.long	.Ltmp24-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	89                              // DW_OP_reg9
	.long	0
	.long	0
.Ldebug_loc11:
	.long	.Ltmp25-.Lfunc_begin0
	.long	.Ltmp26-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp26-.Lfunc_begin0
	.long	.Ltmp27-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	89                              // DW_OP_reg9
	.long	0
	.long	0
.Ldebug_loc12:
	.long	.Ltmp28-.Lfunc_begin0
	.long	.Ltmp29-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	88                              // DW_OP_reg8
	.long	0
	.long	0
.Ldebug_loc13:
	.long	.Ltmp40-.Lfunc_begin0
	.long	.Ltmp88-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	90                              // DW_OP_reg10
	.long	.Ltmp88-.Lfunc_begin0
	.long	.Ltmp89-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc14:
	.long	.Ltmp40-.Lfunc_begin0
	.long	.Ltmp53-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	90                              // DW_OP_reg10
	.long	0
	.long	0
.Ldebug_loc15:
	.long	.Ltmp52-.Lfunc_begin0
	.long	.Ltmp55-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	91                              // DW_OP_reg11
	.long	0
	.long	0
.Ldebug_loc16:
	.long	.Ltmp73-.Lfunc_begin0
	.long	.Ltmp74-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	93                              // DW_OP_reg13
	.long	.Ltmp74-.Lfunc_begin0
	.long	.Ltmp75-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	92                              // DW_OP_reg12
	.long	0
	.long	0
.Ldebug_loc17:
	.long	.Ltmp76-.Lfunc_begin0
	.long	.Ltmp77-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	.Ltmp77-.Lfunc_begin0
	.long	.Ltmp78-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	92                              // DW_OP_reg12
	.long	0
	.long	0
.Ldebug_loc18:
	.long	.Ltmp79-.Lfunc_begin0
	.long	.Ltmp80-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp80-.Lfunc_begin0
	.long	.Ltmp82-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	92                              // DW_OP_reg12
	.long	0
	.long	0
.Ldebug_loc19:
	.long	.Ltmp81-.Lfunc_begin0
	.long	.Ltmp82-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp82-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	92                              // DW_OP_reg12
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	1                               // DW_CHILDREN_yes
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	11                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	12                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	13                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	0                               // DW_CHILDREN_no
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x68b DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0xb DW_TAG_typedef
	.long	49                              // DW_AT_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	53                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x31:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x38:0x2e DW_TAG_subprogram
	.long	.Linfo_string5                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	34                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	102                             // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0x44:0xb DW_TAG_formal_parameter
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	34                              // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0x4f:0xb DW_TAG_formal_parameter
	.long	.Linfo_string11                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	34                              // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x5a:0xb DW_TAG_variable
	.long	.Linfo_string12                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	39                              // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	2                               // Abbrev [2] 0x66:0xb DW_TAG_typedef
	.long	113                             // DW_AT_type
	.long	.Linfo_string7                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	44                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x71:0x7 DW_TAG_base_type
	.long	.Linfo_string6                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	2                               // DW_AT_byte_size
	.byte	2                               // Abbrev [2] 0x78:0xb DW_TAG_typedef
	.long	131                             // DW_AT_type
	.long	.Linfo_string10                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	48                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x83:0x7 DW_TAG_base_type
	.long	.Linfo_string9                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x8a:0x2e DW_TAG_subprogram
	.long	.Linfo_string13                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	46                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	102                             // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0x96:0xb DW_TAG_formal_parameter
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	46                              // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0xa1:0xb DW_TAG_formal_parameter
	.long	.Linfo_string11                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	46                              // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xac:0xb DW_TAG_variable
	.long	.Linfo_string12                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	51                              // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	4                               // Abbrev [4] 0xb8:0x2e DW_TAG_subprogram
	.long	.Linfo_string14                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	61                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	102                             // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0xc4:0xb DW_TAG_formal_parameter
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	61                              // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0xcf:0xb DW_TAG_formal_parameter
	.long	.Linfo_string11                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	61                              // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xda:0xb DW_TAG_variable
	.long	.Linfo_string12                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	66                              // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	4                               // Abbrev [4] 0xe6:0x2e DW_TAG_subprogram
	.long	.Linfo_string15                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	73                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	102                             // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0xf2:0xb DW_TAG_formal_parameter
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	73                              // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0xfd:0xb DW_TAG_formal_parameter
	.long	.Linfo_string11                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	73                              // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x108:0xb DW_TAG_variable
	.long	.Linfo_string12                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	78                              // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x114:0x581 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string16                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	132                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	38                              // DW_AT_type
                                        // DW_AT_external
	.byte	8                               // Abbrev [8] 0x129:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string17                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	132                             // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0x138:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string18                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	132                             // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	9                               // Abbrev [9] 0x147:0xf DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string19                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	134                             // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	9                               // Abbrev [9] 0x156:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string20                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	135                             // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	9                               // Abbrev [9] 0x165:0xf DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	.Linfo_string21                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	136                             // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	9                               // Abbrev [9] 0x174:0xf DW_TAG_variable
	.long	.Ldebug_loc5                    // DW_AT_location
	.long	.Linfo_string22                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	137                             // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	9                               // Abbrev [9] 0x183:0xf DW_TAG_variable
	.long	.Ldebug_loc6                    // DW_AT_location
	.long	.Linfo_string23                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	141                             // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	9                               // Abbrev [9] 0x192:0xf DW_TAG_variable
	.long	.Ldebug_loc7                    // DW_AT_location
	.long	.Linfo_string24                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	140                             // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	9                               // Abbrev [9] 0x1a1:0xf DW_TAG_variable
	.long	.Ldebug_loc8                    // DW_AT_location
	.long	.Linfo_string25                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	140                             // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	9                               // Abbrev [9] 0x1b0:0xf DW_TAG_variable
	.long	.Ldebug_loc9                    // DW_AT_location
	.long	.Linfo_string26                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	140                             // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	9                               // Abbrev [9] 0x1bf:0xf DW_TAG_variable
	.long	.Ldebug_loc12                   // DW_AT_location
	.long	.Linfo_string27                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	140                             // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	9                               // Abbrev [9] 0x1ce:0xf DW_TAG_variable
	.long	.Ldebug_loc13                   // DW_AT_location
	.long	.Linfo_string28                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	140                             // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	9                               // Abbrev [9] 0x1dd:0xf DW_TAG_variable
	.long	.Ldebug_loc14                   // DW_AT_location
	.long	.Linfo_string29                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	140                             // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	9                               // Abbrev [9] 0x1ec:0xf DW_TAG_variable
	.long	.Ldebug_loc15                   // DW_AT_location
	.long	.Linfo_string30                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	140                             // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x1fb:0xb DW_TAG_variable
	.long	.Linfo_string31                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	140                             // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x206:0xb DW_TAG_variable
	.long	.Linfo_string32                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	140                             // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	10                              // Abbrev [10] 0x211:0x1f DW_TAG_inlined_subroutine
	.long	56                              // DW_AT_abstract_origin
	.long	.Ltmp0                          // DW_AT_low_pc
	.long	.Ltmp1-.Ltmp0                   // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	143                             // DW_AT_call_line
	.byte	10                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x221:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	68                              // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x228:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	83
	.long	79                              // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x230:0x1f DW_TAG_inlined_subroutine
	.long	138                             // DW_AT_abstract_origin
	.long	.Ltmp2                          // DW_AT_low_pc
	.long	.Ltmp3-.Ltmp2                   // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	145                             // DW_AT_call_line
	.byte	10                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x240:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	150                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x247:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	83
	.long	161                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x24f:0x1f DW_TAG_inlined_subroutine
	.long	138                             // DW_AT_abstract_origin
	.long	.Ltmp4                          // DW_AT_low_pc
	.long	.Ltmp5-.Ltmp4                   // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	145                             // DW_AT_call_line
	.byte	28                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x25f:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	83
	.long	150                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x266:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	161                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x26e:0x1f DW_TAG_inlined_subroutine
	.long	56                              // DW_AT_abstract_origin
	.long	.Ltmp9                          // DW_AT_low_pc
	.long	.Ltmp10-.Ltmp9                  // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	147                             // DW_AT_call_line
	.byte	10                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x27e:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	68                              // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x285:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	84
	.long	79                              // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x28d:0x1f DW_TAG_inlined_subroutine
	.long	56                              // DW_AT_abstract_origin
	.long	.Ltmp11                         // DW_AT_low_pc
	.long	.Ltmp12-.Ltmp11                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	147                             // DW_AT_call_line
	.byte	28                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x29d:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	83
	.long	68                              // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x2a4:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	85
	.long	79                              // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x2ac:0x1f DW_TAG_inlined_subroutine
	.long	184                             // DW_AT_abstract_origin
	.long	.Ltmp13                         // DW_AT_low_pc
	.long	.Ltmp14-.Ltmp13                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	147                             // DW_AT_call_line
	.byte	46                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x2bc:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	196                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x2c3:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	83
	.long	207                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x2cb:0x1f DW_TAG_inlined_subroutine
	.long	138                             // DW_AT_abstract_origin
	.long	.Ltmp18                         // DW_AT_low_pc
	.long	.Ltmp19-.Ltmp18                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	149                             // DW_AT_call_line
	.byte	10                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x2db:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	150                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x2e2:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	84
	.long	161                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x2ea:0x1f DW_TAG_inlined_subroutine
	.long	138                             // DW_AT_abstract_origin
	.long	.Ltmp20                         // DW_AT_low_pc
	.long	.Ltmp21-.Ltmp20                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	149                             // DW_AT_call_line
	.byte	28                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x2fa:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	83
	.long	150                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x301:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	85
	.long	161                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x309:0x28 DW_TAG_inlined_subroutine
	.long	230                             // DW_AT_abstract_origin
	.long	.Ltmp22                         // DW_AT_low_pc
	.long	.Ltmp23-.Ltmp22                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	149                             // DW_AT_call_line
	.byte	46                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x319:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	242                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x320:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	83
	.long	253                             // DW_AT_abstract_origin
	.byte	12                              // Abbrev [12] 0x327:0x9 DW_TAG_variable
	.long	.Ldebug_loc10                   // DW_AT_location
	.long	264                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x331:0x28 DW_TAG_inlined_subroutine
	.long	230                             // DW_AT_abstract_origin
	.long	.Ltmp25                         // DW_AT_low_pc
	.long	.Ltmp26-.Ltmp25                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	149                             // DW_AT_call_line
	.byte	64                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x341:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	83
	.long	242                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x348:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	253                             // DW_AT_abstract_origin
	.byte	12                              // Abbrev [12] 0x34f:0x9 DW_TAG_variable
	.long	.Ldebug_loc11                   // DW_AT_location
	.long	264                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	13                              // Abbrev [13] 0x359:0x10 DW_TAG_inlined_subroutine
	.long	56                              // DW_AT_abstract_origin
	.long	.Ltmp30                         // DW_AT_low_pc
	.long	.Ltmp31-.Ltmp30                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	151                             // DW_AT_call_line
	.byte	10                              // DW_AT_call_column
	.byte	10                              // Abbrev [10] 0x369:0x1f DW_TAG_inlined_subroutine
	.long	56                              // DW_AT_abstract_origin
	.long	.Ltmp32                         // DW_AT_low_pc
	.long	.Ltmp33-.Ltmp32                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	151                             // DW_AT_call_line
	.byte	28                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x379:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	83
	.long	68                              // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x380:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	79                              // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x388:0x1f DW_TAG_inlined_subroutine
	.long	184                             // DW_AT_abstract_origin
	.long	.Ltmp34                         // DW_AT_low_pc
	.long	.Ltmp35-.Ltmp34                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	151                             // DW_AT_call_line
	.byte	46                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x398:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	196                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x39f:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	84
	.long	207                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x3a7:0x1f DW_TAG_inlined_subroutine
	.long	184                             // DW_AT_abstract_origin
	.long	.Ltmp36                         // DW_AT_low_pc
	.long	.Ltmp37-.Ltmp36                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	151                             // DW_AT_call_line
	.byte	64                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x3b7:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	83
	.long	196                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x3be:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	85
	.long	207                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x3c6:0x1f DW_TAG_inlined_subroutine
	.long	56                              // DW_AT_abstract_origin
	.long	.Ltmp38                         // DW_AT_low_pc
	.long	.Ltmp39-.Ltmp38                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	151                             // DW_AT_call_line
	.byte	82                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x3d6:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	85
	.long	68                              // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x3dd:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	84
	.long	79                              // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x3e5:0x1f DW_TAG_inlined_subroutine
	.long	138                             // DW_AT_abstract_origin
	.long	.Ltmp40                         // DW_AT_low_pc
	.long	.Ltmp41-.Ltmp40                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	153                             // DW_AT_call_line
	.byte	10                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x3f5:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	150                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x3fc:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	82
	.long	161                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x404:0x1f DW_TAG_inlined_subroutine
	.long	138                             // DW_AT_abstract_origin
	.long	.Ltmp42                         // DW_AT_low_pc
	.long	.Ltmp43-.Ltmp42                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	153                             // DW_AT_call_line
	.byte	28                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x414:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	83
	.long	150                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x41b:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	161                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x423:0x1f DW_TAG_inlined_subroutine
	.long	138                             // DW_AT_abstract_origin
	.long	.Ltmp44                         // DW_AT_low_pc
	.long	.Ltmp45-.Ltmp44                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	153                             // DW_AT_call_line
	.byte	46                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x433:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	82
	.long	150                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x43a:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	161                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x442:0x1f DW_TAG_inlined_subroutine
	.long	138                             // DW_AT_abstract_origin
	.long	.Ltmp46                         // DW_AT_low_pc
	.long	.Ltmp47-.Ltmp46                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	153                             // DW_AT_call_line
	.byte	64                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x452:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	150                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x459:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	83
	.long	161                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x461:0x1f DW_TAG_inlined_subroutine
	.long	138                             // DW_AT_abstract_origin
	.long	.Ltmp48                         // DW_AT_low_pc
	.long	.Ltmp49-.Ltmp48                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	153                             // DW_AT_call_line
	.byte	82                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x471:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	85
	.long	150                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x478:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	84
	.long	161                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x480:0x1f DW_TAG_inlined_subroutine
	.long	138                             // DW_AT_abstract_origin
	.long	.Ltmp50                         // DW_AT_low_pc
	.long	.Ltmp51-.Ltmp50                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	153                             // DW_AT_call_line
	.byte	100                             // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x490:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	84
	.long	150                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x497:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	85
	.long	161                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x49f:0x1f DW_TAG_inlined_subroutine
	.long	56                              // DW_AT_abstract_origin
	.long	.Ltmp54                         // DW_AT_low_pc
	.long	.Ltmp55-.Ltmp54                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	155                             // DW_AT_call_line
	.byte	10                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x4af:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	68                              // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x4b6:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	93
	.long	79                              // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x4be:0x1f DW_TAG_inlined_subroutine
	.long	56                              // DW_AT_abstract_origin
	.long	.Ltmp56                         // DW_AT_low_pc
	.long	.Ltmp57-.Ltmp56                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	155                             // DW_AT_call_line
	.byte	28                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x4ce:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	83
	.long	68                              // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x4d5:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	95
	.long	79                              // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x4dd:0x1f DW_TAG_inlined_subroutine
	.long	184                             // DW_AT_abstract_origin
	.long	.Ltmp58                         // DW_AT_low_pc
	.long	.Ltmp59-.Ltmp58                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	155                             // DW_AT_call_line
	.byte	46                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x4ed:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	196                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x4f4:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	82
	.long	207                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x4fc:0x1f DW_TAG_inlined_subroutine
	.long	184                             // DW_AT_abstract_origin
	.long	.Ltmp60                         // DW_AT_low_pc
	.long	.Ltmp61-.Ltmp60                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	155                             // DW_AT_call_line
	.byte	64                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x50c:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	83
	.long	196                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x513:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	207                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x51b:0x1f DW_TAG_inlined_subroutine
	.long	56                              // DW_AT_abstract_origin
	.long	.Ltmp62                         // DW_AT_low_pc
	.long	.Ltmp63-.Ltmp62                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	155                             // DW_AT_call_line
	.byte	82                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x52b:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	82
	.long	68                              // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x532:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	85
	.long	79                              // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x53a:0x1f DW_TAG_inlined_subroutine
	.long	56                              // DW_AT_abstract_origin
	.long	.Ltmp64                         // DW_AT_low_pc
	.long	.Ltmp65-.Ltmp64                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	155                             // DW_AT_call_line
	.byte	100                             // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x54a:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	68                              // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x551:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	84
	.long	79                              // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x559:0x1f DW_TAG_inlined_subroutine
	.long	184                             // DW_AT_abstract_origin
	.long	.Ltmp66                         // DW_AT_low_pc
	.long	.Ltmp67-.Ltmp66                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	156                             // DW_AT_call_line
	.byte	11                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x569:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	85
	.long	196                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x570:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	84
	.long	207                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x578:0x1f DW_TAG_inlined_subroutine
	.long	138                             // DW_AT_abstract_origin
	.long	.Ltmp69                         // DW_AT_low_pc
	.long	.Ltmp70-.Ltmp69                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	158                             // DW_AT_call_line
	.byte	10                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x588:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	150                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x58f:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	93
	.long	161                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x597:0x1f DW_TAG_inlined_subroutine
	.long	138                             // DW_AT_abstract_origin
	.long	.Ltmp71                         // DW_AT_low_pc
	.long	.Ltmp72-.Ltmp71                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	158                             // DW_AT_call_line
	.byte	28                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x5a7:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	83
	.long	150                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x5ae:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	95
	.long	161                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x5b6:0x28 DW_TAG_inlined_subroutine
	.long	230                             // DW_AT_abstract_origin
	.long	.Ltmp73                         // DW_AT_low_pc
	.long	.Ltmp74-.Ltmp73                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	158                             // DW_AT_call_line
	.byte	46                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x5c6:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	242                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x5cd:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	82
	.long	253                             // DW_AT_abstract_origin
	.byte	12                              // Abbrev [12] 0x5d4:0x9 DW_TAG_variable
	.long	.Ldebug_loc16                   // DW_AT_location
	.long	264                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x5de:0x28 DW_TAG_inlined_subroutine
	.long	230                             // DW_AT_abstract_origin
	.long	.Ltmp76                         // DW_AT_low_pc
	.long	.Ltmp77-.Ltmp76                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	158                             // DW_AT_call_line
	.byte	64                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x5ee:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	83
	.long	242                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x5f5:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	253                             // DW_AT_abstract_origin
	.byte	12                              // Abbrev [12] 0x5fc:0x9 DW_TAG_variable
	.long	.Ldebug_loc17                   // DW_AT_location
	.long	264                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x606:0x28 DW_TAG_inlined_subroutine
	.long	230                             // DW_AT_abstract_origin
	.long	.Ltmp79                         // DW_AT_low_pc
	.long	.Ltmp80-.Ltmp79                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	158                             // DW_AT_call_line
	.byte	82                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x616:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	82
	.long	242                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x61d:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	253                             // DW_AT_abstract_origin
	.byte	12                              // Abbrev [12] 0x624:0x9 DW_TAG_variable
	.long	.Ldebug_loc18                   // DW_AT_location
	.long	264                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x62e:0x28 DW_TAG_inlined_subroutine
	.long	230                             // DW_AT_abstract_origin
	.long	.Ltmp81                         // DW_AT_low_pc
	.long	.Ltmp82-.Ltmp81                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	158                             // DW_AT_call_line
	.byte	100                             // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x63e:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	242                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x645:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	83
	.long	253                             // DW_AT_abstract_origin
	.byte	12                              // Abbrev [12] 0x64c:0x9 DW_TAG_variable
	.long	.Ldebug_loc19                   // DW_AT_location
	.long	264                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x656:0x1f DW_TAG_inlined_subroutine
	.long	138                             // DW_AT_abstract_origin
	.long	.Ltmp83                         // DW_AT_low_pc
	.long	.Ltmp84-.Ltmp83                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	159                             // DW_AT_call_line
	.byte	11                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x666:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	82
	.long	150                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x66d:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	85
	.long	161                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x675:0x1f DW_TAG_inlined_subroutine
	.long	138                             // DW_AT_abstract_origin
	.long	.Ltmp85                         // DW_AT_low_pc
	.long	.Ltmp86-.Ltmp85                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	159                             // DW_AT_call_line
	.byte	29                              // DW_AT_call_column
	.byte	11                              // Abbrev [11] 0x685:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	150                             // DW_AT_abstract_origin
	.byte	11                              // Abbrev [11] 0x68c:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	84
	.long	161                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/mul64.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=151
.Linfo_string3:
	.asciz	"long unsigned int"             // string offset=172
.Linfo_string4:
	.asciz	"uint64_t"                      // string offset=190
.Linfo_string5:
	.asciz	"_mul00"                        // string offset=199
.Linfo_string6:
	.asciz	"unsigned short"                // string offset=206
.Linfo_string7:
	.asciz	"uint16_t"                      // string offset=221
.Linfo_string8:
	.asciz	"a"                             // string offset=230
.Linfo_string9:
	.asciz	"unsigned int"                  // string offset=232
.Linfo_string10:
	.asciz	"uint32_t"                      // string offset=245
.Linfo_string11:
	.asciz	"b"                             // string offset=254
.Linfo_string12:
	.asciz	"r"                             // string offset=256
.Linfo_string13:
	.asciz	"_mul01"                        // string offset=258
.Linfo_string14:
	.asciz	"_mul11"                        // string offset=265
.Linfo_string15:
	.asciz	"_mul12"                        // string offset=272
.Linfo_string16:
	.asciz	"__muldi3"                      // string offset=279
.Linfo_string17:
	.asciz	"x"                             // string offset=288
.Linfo_string18:
	.asciz	"y"                             // string offset=290
.Linfo_string19:
	.asciz	"xl"                            // string offset=292
.Linfo_string20:
	.asciz	"xh"                            // string offset=295
.Linfo_string21:
	.asciz	"yl"                            // string offset=298
.Linfo_string22:
	.asciz	"yh"                            // string offset=301
.Linfo_string23:
	.asciz	"rl"                            // string offset=304
.Linfo_string24:
	.asciz	"p0"                            // string offset=307
.Linfo_string25:
	.asciz	"p1"                            // string offset=310
.Linfo_string26:
	.asciz	"p2"                            // string offset=313
.Linfo_string27:
	.asciz	"p3"                            // string offset=316
.Linfo_string28:
	.asciz	"rh"                            // string offset=319
.Linfo_string29:
	.asciz	"p4"                            // string offset=322
.Linfo_string30:
	.asciz	"p5"                            // string offset=325
.Linfo_string31:
	.asciz	"p6"                            // string offset=328
.Linfo_string32:
	.asciz	"p7"                            // string offset=331
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
