	.text
	.file	"muldf3.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/stdint.h"
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/fp_lib.h"
	.section	.text.__muldf3,"ax",@progbits
	.globl	__muldf3                        // -- Begin function __muldf3
	.type	__muldf3,@function
__muldf3:                               // @__muldf3
.Lfunc_begin0:
	.file	3 "/root" "uPIMulator_frontend/sdk/syslib/muldf3.c"
	.loc	3 20 0                          // uPIMulator_frontend/sdk/syslib/muldf3.c:20:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __muldf3:a <- $d0
	//DEBUG_VALUE: __muldf3:a <- $d0
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: __mulXf3__:a <- $d0
	//DEBUG_VALUE: __mulXf3__:a <- $d0
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: toRep:x <- $d0
	//DEBUG_VALUE: toRep:x <- $d0
	.cfi_def_cfa_offset -72
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 64, d22
	add r22, r22, 72
	.cfi_offset 15, -48
	.cfi_offset 14, -44
.Ltmp0:
	sd r22, -48, d14
	.cfi_offset 17, -56
	.cfi_offset 16, -52
	sd r22, -56, d16
	.cfi_offset 19, -64
	.cfi_offset 18, -60
	sd r22, -64, d18
	.cfi_offset 21, -72
	.cfi_offset 20, -68
	sd r22, -72, d20
	//DEBUG_VALUE: toRep:rep <- $d0
	//DEBUG_VALUE: toRep:rep <- $d0
.Ltmp1:
	.file	4 "/root" "uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc"
	.loc	4 18 45 prologue_end            // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:18:45
	lsr.u d4, r0, 20
	.loc	4 18 36 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:18:36
	and r10, r5, 2047
.Ltmp2:
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	.loc	4 19 45 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:19:45
	lsr.u d4, r2, 20
	.loc	4 19 36 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:19:36
	and r11, r5, 2047
.Ltmp3:
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	.loc	4 20 41 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:20:41
	xor r5, r3, r1
	xor r4, r2, r0
	.loc	4 20 53 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:20:53
	and r13, r5, 0
	and r12, r4, 2147483648
.Ltmp4:
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	.loc	4 22 35 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:22:35
	and r21, r1, 4294967295
	and r20, r0, 1048575
.Ltmp5:
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: __mulXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	.loc	4 23 35                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:23:35
	and r15, r3, 4294967295
	and r14, r2, 1048575
.Ltmp6:
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	.loc	4 27 18                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:27:18
	add r4, r10, -1
	.loc	4 27 40 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:27:40
	lsr r4, r4, 1
	jgtu r4, 1022, .LBB0_9
.Ltmp7:
// %bb.1:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: __mulXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __mulXf3__:a <- $d0
	//DEBUG_VALUE: __muldf3:a <- $d0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 0 40                          // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:40
	add r4, r11, -1
	move r5, 0
	.loc	4 27 40                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:27:40
	lsr r4, r4, 1
	jgeu r4, 1023, .LBB0_9
.Ltmp8:
// %bb.2:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: __mulXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __mulXf3__:a <- $d0
	//DEBUG_VALUE: __muldf3:a <- $d0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	sw r22, -16, r5
	sw r22, -20, r11
	sw r22, -24, r10
	sd r22, -32, d12
.Ltmp9:
.LBB0_3:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: __mulXf3__:aSignificand <- [DW_OP_constu 4503599627370496, DW_OP_or, DW_OP_stack_value] $d20
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370496, DW_OP_or, DW_OP_stack_value] $d14
	//DEBUG_VALUE: __mulXf3__:scale <- [DW_OP_constu 16, DW_OP_minus] [$r22+0]
	.loc	4 75 45 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:75:45
	lslx r0, r15, 11
	lsl_add r0, r0, r14, 11
	lsl r1, r15, 11
.Ltmp10:
	//DEBUG_VALUE: wideMultiply:lo <- undef
	//DEBUG_VALUE: wideMultiply:hi <- undef
	//DEBUG_VALUE: wideMultiply:a <- [DW_OP_constu 4503599627370496, DW_OP_or, DW_OP_stack_value] $d20
	//DEBUG_VALUE: wideMultiply:b <- [DW_OP_constu 9223372036854775808, DW_OP_or, DW_OP_stack_value] $d0
	.loc	2 97 28                         // uPIMulator_frontend/sdk/syslib/fp_lib.h:97:28
	and r17, r21, 4294967295
	and r16, r20, 0
	.loc	2 97 40 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_lib.h:97:40
	and r19, r1, 4294965248
	and r18, r0, 0
	.loc	2 97 38                         // uPIMulator_frontend/sdk/syslib/fp_lib.h:97:38
	movd d0, d18
.Ltmp11:
	movd d2, d16
	call r23, __muldi3
.Ltmp12:
	sd r22, -40, d0
.Ltmp13:
	//DEBUG_VALUE: wideMultiply:plolo <- [DW_OP_constu 40, DW_OP_minus] [$r22+0]
	.loc	2 98 40 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_lib.h:98:40
	lsrx r0, r14, 21
	lsr_add r1, r0, r15, 21
	lsr r0, r14, 21
	and r1, r1, 2147483647
	and r0, r0, 0
	or r15, r1, 2147483648
.Ltmp14:
	or r14, r0, 0
	.loc	2 98 38 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_lib.h:98:38
	movd d0, d14
	movd d2, d16
	call r23, __muldi3
.Ltmp15:
	movd d16, d0
.Ltmp16:
	//DEBUG_VALUE: wideMultiply:plohi <- $d16
	.loc	2 99 28 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_lib.h:99:28
	move.u d0, r20
	or r21, r1, 1048576
.Ltmp17:
	or r20, r0, 0
	.loc	2 99 38 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_lib.h:99:38
	movd d0, d18
	movd d2, d20
	call r23, __muldi3
.Ltmp18:
	movd d18, d0
.Ltmp19:
	//DEBUG_VALUE: wideMultiply:philo <- $d18
	.loc	2 100 38 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_lib.h:100:38
	movd d0, d14
	movd d2, d20
	call r23, __muldi3
.Ltmp20:
	//DEBUG_VALUE: wideMultiply:phihi <- $d0
	.loc	2 0 38 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_lib.h:0:38
	ld d8, r22, -40
.Ltmp21:
	//DEBUG_VALUE: wideMultiply:plolo <- $d8
	.loc	2 103 25 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_lib.h:103:25
	move.u d2, r8
	.loc	2 103 41 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_lib.h:103:41
	and r5, r17, 4294967295
	and r4, r16, 0
	.loc	2 103 57                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:103:57
	and r7, r19, 4294965248
	and r6, r18, 0
	.loc	2 103 39                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:103:39
	add r3, r7, r3
	addc r2, r6, r2
	.loc	2 103 55                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:103:55
	add r5, r3, r5
	addc r4, r2, r4
.Ltmp22:
	//DEBUG_VALUE: wideMultiply:r1 <- $d4
	.loc	2 104 20 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_lib.h:104:20
	move r7, 0
	.loc	2 102 25                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:102:25
	and r3, r9, 4294965248
	and r2, r8, 0
.Ltmp23:
	//DEBUG_VALUE: wideMultiply:r0 <- $d2
	.loc	2 104 20                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:104:20
	move r6, r5
	.loc	2 104 14 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_lib.h:104:14
	or r3, r7, r3
.Ltmp24:
	or r2, r6, r2
	.loc	2 106 11 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_lib.h:106:11
	move.u d8, r16
.Ltmp25:
	.loc	2 106 27 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_lib.h:106:27
	move.u d10, r18
.Ltmp26:
	.loc	2 106 43                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:106:43
	move.u d4, r4
.Ltmp27:
	.loc	2 106 25                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:106:25
	add r1, r11, r1
.Ltmp28:
	addc r0, r10, r0
	.loc	2 106 41                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:106:41
	add r1, r1, r9
	addc r0, r0, r8
	.loc	2 106 54                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:106:54
	add r1, r1, r5
	addc r0, r0, r4
.Ltmp29:
	.loc	4 78 37 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:78:37
	lw r4, r22, -24
	lw r5, r22, -20
	add r4, r4, r5
	.loc	4 78 49 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:78:49
	lw r5, r22, -16
.Ltmp30:
	//DEBUG_VALUE: __mulXf3__:scale <- $r5
	add r4, r4, r5
.Ltmp31:
	.loc	4 81 19 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:81:19
	and r9, r1, 0
	and r8, r0, 1048576
	move.s d10, 0
.Ltmp32:
	.loc	4 78 64                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:78:64
	add r5, r4, -1023
.Ltmp33:
	//DEBUG_VALUE: __mulXf3__:productHi <- $d0
	//DEBUG_VALUE: __mulXf3__:productExponent <- $r5
	.loc	4 81 9                          // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:81:9
	jneq r9, r11, .LBB0_11
.Ltmp34:
// %bb.55:
	jneq r8, r10, .LBB0_11
// %bb.56:
// %bb.4:
.Ltmp35:
	//DEBUG_VALUE: __mulXf3__:productExponent <- $r5
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: __mulXf3__:productHi <- $d0
	//DEBUG_VALUE: wideLeftShift:hi <- undef
	//DEBUG_VALUE: wideLeftShift:lo <- undef
	//DEBUG_VALUE: wideLeftShift:count <- 1
	.loc	2 259 24                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:259:24
	lsr.u d6, r6, 31
	lslx r4, r1, 1
	lsl_add r8, r4, r0, 1
	lsl r9, r1, 1
	or r1, r9, r7
.Ltmp36:
	or r0, r8, r6
	.loc	2 260 15                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:260:15
	lslx r4, r3, 1
	lsl_add r2, r4, r2, 1
	lsl r3, r3, 1
	ld d12, r22, -32
.Ltmp37:
	//DEBUG_VALUE: __mulXf3__:productExponent <- $r5
	.loc	2 0 15 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_lib.h:0:15
	move r4, 2047
.Ltmp38:
	.loc	4 85 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:85:9
	jges r5, r4, .LBB0_17
	jump .LBB0_5
.Ltmp39:
.LBB0_9:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: __mulXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __mulXf3__:a <- $d0
	//DEBUG_VALUE: __muldf3:a <- $d0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 29 37                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:29:37
	and r7, r1, 4294967295
	and r6, r0, 2147483647
.Ltmp40:
	//DEBUG_VALUE: bAbs <- undef
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: aAbs <- $d6
	.loc	4 0 37 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:37
	move r9, 1
	move r8, 2146435072
.Ltmp41:
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	.loc	4 33 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:33:13
	sub zero, r7, r9
	subc zero, r6, r8, ltu, .LBB0_13
.Ltmp42:
// %bb.10:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: aAbs <- $d6
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: __mulXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __mulXf3__:a <- $d0
	//DEBUG_VALUE: __muldf3:a <- $d0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 33 52 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:33:52
	or r13, r1, 0
.Ltmp43:
	or r12, r0, 524288
.Ltmp44:
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $d12
	.loc	4 0 52                          // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:52
	jump .LBB0_40
.Ltmp45:
.LBB0_11:
	//DEBUG_VALUE: __mulXf3__:productExponent <- $r5
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: __mulXf3__:productHi <- $d0
	.loc	4 81 49 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:81:49
	add r5, r5, 1
.Ltmp46:
	//DEBUG_VALUE: __mulXf3__:productExponent <- $r5
	.loc	4 0 49 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:49
	ld d12, r22, -32
.Ltmp47:
	//DEBUG_VALUE: __mulXf3__:productExponent <- $r5
	move r4, 2047
.Ltmp48:
	.loc	4 85 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:85:9
	jges r5, r4, .LBB0_17
.Ltmp49:
.LBB0_5:
	//DEBUG_VALUE: __mulXf3__:productExponent <- $r5
	.loc	4 87 9                          // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:87:9
	jles r5, 0, .LBB0_20
.Ltmp50:
// %bb.6:
	//DEBUG_VALUE: __mulXf3__:productExponent <- $r5
	//DEBUG_VALUE: __mulXf3__:productHi <- $d0
	.loc	4 103 19                        // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:103:19
	and r1, r1, 4294967295
.Ltmp51:
	and r0, r0, 1048575
	.loc	4 104 22                        // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:104:22
	move.s d4, r5
.Ltmp52:
	.loc	4 104 45 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:104:45
	move r7, 0
	lsl r6, r5, 20
	.loc	4 104 19                        // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:104:19
	or r7, r7, r1
	or r6, r6, r0
.Ltmp53:
	//DEBUG_VALUE: __mulXf3__:productHi <- $d6
.LBB0_7:
	//DEBUG_VALUE: __mulXf3__:productHi <- $d6
	.loc	4 0 19                          // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:19
	move r1, 1
	move r0, 2147483648
.Ltmp54:
	//DEBUG_VALUE: __mulXf3__:productLo <- $d2
	//DEBUG_VALUE: __mulXf3__:productHi <- undef
	.loc	4 108 15 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:108:15
	or r13, r7, r13
	or r12, r6, r12
	.loc	4 113 9                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:113:9
	sub zero, r3, r1
	subc zero, r2, r0, ltu, .LBB0_18
.Ltmp55:
// %bb.8:
	//DEBUG_VALUE: __mulXf3__:productLo <- $d2
	.loc	4 113 39 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:113:39
	add r13, r13, 1
	addc r12, r12, 0
.Ltmp56:
	//DEBUG_VALUE: __mulXf3__:productLo <- undef
	//DEBUG_VALUE: __mulXf3__:productHi <- $d12
	//DEBUG_VALUE: fromRep:x <- $d12
	//DEBUG_VALUE: fromRep:rep <- undef
	.loc	4 0 39                          // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:39
	jump .LBB0_40
.Ltmp57:
.LBB0_13:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: aAbs <- $d6
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: __mulXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __mulXf3__:a <- $d0
	//DEBUG_VALUE: __muldf3:a <- $d0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	and r5, r3, 4294967295
	and r4, r2, 2147483647
.Ltmp58:
	//DEBUG_VALUE: bAbs <- $d4
	.loc	4 35 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:35:13
	sub zero, r5, r9
	subc zero, r4, r8, ltu, .LBB0_15
.Ltmp59:
// %bb.14:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: aAbs <- $d6
	//DEBUG_VALUE: bAbs <- $d4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: __mulXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __mulXf3__:a <- $d0
	//DEBUG_VALUE: __muldf3:a <- $d0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 35 52 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:35:52
	or r13, r3, 0
.Ltmp60:
	or r12, r2, 524288
.Ltmp61:
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $d12
	.loc	4 0 52                          // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:52
	jump .LBB0_40
.Ltmp62:
.LBB0_15:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: aAbs <- $d6
	//DEBUG_VALUE: bAbs <- $d4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: __mulXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __mulXf3__:a <- $d0
	//DEBUG_VALUE: __muldf3:a <- $d0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	move r9, 0
	move r8, 2146435072
	.loc	4 37 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:37:13
	jneq r7, r9, .LBB0_26
.Ltmp63:
// %bb.57:
	jneq r6, r8, .LBB0_26
// %bb.58:
// %bb.16:
.Ltmp64:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: aAbs <- $d6
	//DEBUG_VALUE: bAbs <- $d4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: __mulXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __mulXf3__:a <- $d0
	//DEBUG_VALUE: __muldf3:a <- $d0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:13
	move.s d0, 0
.Ltmp65:
	.loc	4 39 17 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:39:17
	jneq r5, r1, .LBB0_60
.Ltmp66:
// %bb.59:
	jeq r4, r0, .LBB0_39
.Ltmp67:
.LBB0_60:
.LBB0_17:
	.loc	4 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:0
	or r13, r13, 0
	or r12, r12, 2146435072
.Ltmp68:
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $d12
.LBB0_40:
	.loc	3 21 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/muldf3.c:21:5
	movd d0, d12
	ld d20, r22, -72
	ld d18, r22, -64
	ld d16, r22, -56
	ld d14, r22, -48
	ld d22, r22, -8
	jump r23
.LBB0_18:
.Ltmp69:
	//DEBUG_VALUE: __mulXf3__:productLo <- $d2
	//DEBUG_VALUE: __mulXf3__:productLo <- $d2
	.loc	3 0 5 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/muldf3.c:0:5
	move r1, 0
	move r0, 2147483648
.Ltmp70:
	.loc	4 114 9 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:114:9
	jneq r3, r1, .LBB0_40
.Ltmp71:
// %bb.61:
	jneq r2, r0, .LBB0_40
// %bb.62:
// %bb.19:
.Ltmp72:
	//DEBUG_VALUE: __mulXf3__:productLo <- $d2
	//DEBUG_VALUE: __mulXf3__:productHi <- undef
	.loc	4 114 54 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:114:54
	and r1, r7, 1
	and r0, r6, 0
	.loc	4 114 41                        // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:114:41
	add r13, r13, r1
	addc r12, r12, r0
.Ltmp73:
	//DEBUG_VALUE: __mulXf3__:productHi <- $d12
	//DEBUG_VALUE: fromRep:x <- $d12
	//DEBUG_VALUE: fromRep:rep <- undef
	.loc	4 0 41                          // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:41
	jump .LBB0_40
.Ltmp74:
.LBB0_20:
	//DEBUG_VALUE: __mulXf3__:productExponent <- $r5
	.loc	4 94 45 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:94:45
	sub r4, 1, r5
.Ltmp75:
	//DEBUG_VALUE: shift <- $r4
	.loc	4 95 13                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:95:13
	jgeu r4, 64, .LBB0_40
.Ltmp76:
// %bb.21:
	//DEBUG_VALUE: __mulXf3__:productExponent <- $r5
	//DEBUG_VALUE: shift <- $r4
	//DEBUG_VALUE: wideRightShiftWithSticky:hi <- undef
	//DEBUG_VALUE: wideRightShiftWithSticky:lo <- undef
	//DEBUG_VALUE: wideRightShiftWithSticky:count <- $r4
	.loc	2 267 47                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:267:47
	add r5, r5, 63
.Ltmp77:
	.loc	2 267 33 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_lib.h:267:33
	lslx r6, r3, r5, sh32, .LBB0_34
.Ltmp78:
// %bb.22:
	//DEBUG_VALUE: wideRightShiftWithSticky:count <- $r4
	//DEBUG_VALUE: shift <- $r4
	lsl r7, r2, r5
	or r6, r7, r6
	lsl r7, r3, r5
	move.s d10, 0
.Ltmp79:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] undef
	.loc	2 268 19 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_lib.h:268:19
	lslx r8, r1, r5, sh32, .LBB0_23
	jump .LBB0_35
.Ltmp80:
.LBB0_23:
	//DEBUG_VALUE: wideRightShiftWithSticky:count <- $r4
	//DEBUG_VALUE: shift <- $r4
	lsl r8, r1, r5
	move r9, 0
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_lib.h:0:0
	sub zero, r7, r11
	subc r5, r6, r10, xnz
.Ltmp81:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] $r5
	.loc	2 268 48                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:268:48
	lsrx r6, r2, r4, sh32, .LBB0_24
	jump .LBB0_36
.Ltmp82:
.LBB0_24:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] $r5
	//DEBUG_VALUE: wideRightShiftWithSticky:count <- $r4
	//DEBUG_VALUE: shift <- $r4
	lsr.u d6, r2, r4
	.loc	2 268 42                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:268:42
	or r3, r9, r7
	or r2, r8, r6
	.loc	2 268 59                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:268:59
	move.u d6, r5
	.loc	2 268 57                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:268:57
	or r3, r3, r7
	or r2, r2, r6
	.loc	2 269 19 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_lib.h:269:19
	lsrx r5, r0, r4, sh32, .LBB0_25
	jump .LBB0_37
.Ltmp83:
.LBB0_25:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] $r5
	//DEBUG_VALUE: wideRightShiftWithSticky:count <- $r4
	//DEBUG_VALUE: shift <- $r4
	lsr.u d6, r0, r4
	jump .LBB0_7
.Ltmp84:
.LBB0_26:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: aAbs <- $d6
	//DEBUG_VALUE: bAbs <- $d4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: __mulXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __mulXf3__:a <- $d0
	//DEBUG_VALUE: __muldf3:a <- $d0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 44 13                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:44:13
	jneq r5, r9, .LBB0_29
.Ltmp85:
// %bb.63:
	jneq r4, r8, .LBB0_29
// %bb.64:
// %bb.27:
.Ltmp86:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: aAbs <- $d6
	//DEBUG_VALUE: bAbs <- $d4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: __mulXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __mulXf3__:a <- $d0
	//DEBUG_VALUE: __muldf3:a <- $d0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:13
	move.s d0, 0
.Ltmp87:
	.loc	4 46 17 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:46:17
	jneq r7, r1, .LBB0_17
.Ltmp88:
// %bb.65:
	jneq r6, r0, .LBB0_17
.Ltmp89:
// %bb.66:
.LBB0_39:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: aAbs <- $d6
	//DEBUG_VALUE: bAbs <- $d4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 0 17 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:17
	move r13, 0
.Ltmp90:
	move r12, 2146959360
	jump .LBB0_40
.Ltmp91:
.LBB0_29:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: aAbs <- $d6
	//DEBUG_VALUE: bAbs <- $d4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: __mulXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __mulXf3__:a <- $d0
	//DEBUG_VALUE: __muldf3:a <- $d0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	move.s d8, 0
	.loc	4 52 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:52:13
	jneq r7, r9, .LBB0_68
.Ltmp92:
// %bb.67:
	jeq r6, r8, .LBB0_40
.LBB0_68:
// %bb.30:
.Ltmp93:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: aAbs <- $d6
	//DEBUG_VALUE: bAbs <- $d4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: __mulXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __mulXf3__:a <- $d0
	//DEBUG_VALUE: __muldf3:a <- $d0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 54 13                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:54:13
	jneq r5, r9, .LBB0_70
.Ltmp94:
// %bb.69:
	jeq r4, r8, .LBB0_40
.LBB0_70:
// %bb.31:
.Ltmp95:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: aAbs <- $d6
	//DEBUG_VALUE: bAbs <- $d4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: __mulXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __mulXf3__:a <- $d0
	//DEBUG_VALUE: __muldf3:a <- $d0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 59 13                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:59:13
	lsr.u d8, r6, 20
	move.s d6, 0
.Ltmp96:
	.loc	4 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:13
	move r16, 0
	sd r22, -32, d12
	.loc	4 59 13                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:59:13
	jneq r9, r7, .LBB0_46
.Ltmp97:
// %bb.71:
	jneq r8, r6, .LBB0_46
// %bb.72:
// %bb.32:
.Ltmp98:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: bAbs <- $d4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: __mulXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __mulXf3__:a <- $d0
	//DEBUG_VALUE: __muldf3:a <- $d0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	//DEBUG_VALUE: normalize:significand <- undef
	//DEBUG_VALUE: rep_clz:a <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	.loc	2 80 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/fp_lib.h:80:9
	move.u d8, r20
	jneq r9, r7, .LBB0_41
.Ltmp99:
// %bb.73:
	jneq r8, r6, .LBB0_41
.Ltmp100:
// %bb.74:
// %bb.33:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: bAbs <- $d4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: rep_clz:a <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __mulXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __mulXf3__:a <- $d0
	//DEBUG_VALUE: __muldf3:a <- $d0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	2 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_lib.h:0:9
	clz r0, r1
.Ltmp101:
	or r0, r0, 32, true, .LBB0_42
.Ltmp102:
.LBB0_34:
	//DEBUG_VALUE: wideRightShiftWithSticky:count <- $r4
	//DEBUG_VALUE: shift <- $r4
	.loc	2 267 33 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_lib.h:267:33
	lsl r6, r3, r5
	move r7, 0
	move.s d10, 0
.Ltmp103:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] undef
	.loc	2 268 19                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:268:19
	lslx r8, r1, r5, sh32, .LBB0_23
.Ltmp104:
.LBB0_35:
	//DEBUG_VALUE: wideRightShiftWithSticky:count <- $r4
	//DEBUG_VALUE: shift <- $r4
	lsl r9, r0, r5
	or r8, r9, r8
	lsl r9, r1, r5
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_lib.h:0:0
	sub zero, r7, r11
	subc r5, r6, r10, xnz
.Ltmp105:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] $r5
	.loc	2 268 48                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:268:48
	lsrx r6, r2, r4, sh32, .LBB0_24
.Ltmp106:
.LBB0_36:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] $r5
	//DEBUG_VALUE: wideRightShiftWithSticky:count <- $r4
	//DEBUG_VALUE: shift <- $r4
	lsr r7, r3, r4
	or r7, r6, r7
	lsr r6, r2, r4
	.loc	2 268 42                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:268:42
	or r3, r9, r7
	or r2, r8, r6
	.loc	2 268 59                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:268:59
	move.u d6, r5
	.loc	2 268 57                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:268:57
	or r3, r3, r7
	or r2, r2, r6
	.loc	2 269 19 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_lib.h:269:19
	lsrx r5, r0, r4, sh32, .LBB0_25
.Ltmp107:
.LBB0_37:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] $r5
	//DEBUG_VALUE: wideRightShiftWithSticky:count <- $r4
	//DEBUG_VALUE: shift <- $r4
	lsr r6, r1, r4
	or r7, r5, r6
	lsr r6, r0, r4, true, .LBB0_7
.Ltmp108:
.LBB0_41:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: bAbs <- $d4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: rep_clz:a <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __mulXf3__:aSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d0
	//DEBUG_VALUE: __mulXf3__:a <- $d0
	//DEBUG_VALUE: __muldf3:a <- $d0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	2 0 19 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_lib.h:0:19
	clz r0, r20
.Ltmp109:
.LBB0_42:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: bAbs <- $d4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	//DEBUG_VALUE: rep_clz:a <- 4503599627370496
	.loc	2 251 45 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_lib.h:251:45
	add r1, r0, -11
.Ltmp110:
	//DEBUG_VALUE: normalize:shift <- $r1
	.loc	2 252 18                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:252:18
	lslx r8, r21, r1, sh32, .LBB0_44
.Ltmp111:
// %bb.43:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: normalize:shift <- $r1
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: bAbs <- $d4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	lsl r9, r20, r1
	or r20, r9, r8
	lsl r21, r21, r1, true, .LBB0_45
.Ltmp112:
.LBB0_44:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: normalize:shift <- $r1
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: bAbs <- $d4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	lsl r20, r21, r1
	move r21, 0
.Ltmp113:
.LBB0_45:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: normalize:shift <- $r1
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: bAbs <- $d4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	2 253 14                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:253:14
	sub r16, 12, r0
.Ltmp114:
	//DEBUG_VALUE: __mulXf3__:scale <- $r16
.LBB0_46:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: bAbs <- $d4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: __mulXf3__:scale <- $r16
	.loc	4 60 13                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:60:13
	lsr.u d0, r4, 20
	sw r22, -24, r10
	sw r22, -20, r11
	jneq r1, r7, .LBB0_49
.Ltmp115:
// %bb.75:
	jneq r0, r6, .LBB0_49
// %bb.76:
// %bb.47:
.Ltmp116:
	//DEBUG_VALUE: __mulXf3__:scale <- $r16
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: bAbs <- $d4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: normalize:significand <- undef
	//DEBUG_VALUE: rep_clz:a <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	.loc	2 80 9                          // uPIMulator_frontend/sdk/syslib/fp_lib.h:80:9
	move.u d0, r14
	move.s d4, 0
.Ltmp117:
	jneq r1, r5, .LBB0_50
.Ltmp118:
// %bb.77:
	jneq r0, r4, .LBB0_50
.Ltmp119:
// %bb.78:
// %bb.48:
	//DEBUG_VALUE: __mulXf3__:scale <- $r16
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: rep_clz:a <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	.loc	2 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_lib.h:0:9
	clz r0, r3
	or r0, r0, 32, true, .LBB0_51
.Ltmp120:
.LBB0_49:
	//DEBUG_VALUE: __mulXf3__:scale <- $r16
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: bAbs <- $d4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	sw r22, -16, r16
	jump .LBB0_3
.Ltmp121:
.LBB0_50:
	//DEBUG_VALUE: __mulXf3__:scale <- $r16
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: rep_clz:a <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	clz r0, r14
.Ltmp122:
.LBB0_51:
	//DEBUG_VALUE: __mulXf3__:scale <- $r16
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 4503599627370495, DW_OP_and, DW_OP_stack_value] $d2
	//DEBUG_VALUE: __mulXf3__:b <- $d2
	//DEBUG_VALUE: __muldf3:b <- $d2
	//DEBUG_VALUE: rep_clz:a <- 4503599627370496
	.loc	2 251 45 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_lib.h:251:45
	add r1, r0, -11
.Ltmp123:
	//DEBUG_VALUE: normalize:shift <- $r1
	.loc	2 252 18                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:252:18
	lslx r2, r15, r1, sh32, .LBB0_53
.Ltmp124:
// %bb.52:
	//DEBUG_VALUE: __mulXf3__:scale <- $r16
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: normalize:shift <- $r1
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	lsl r3, r14, r1
	or r14, r3, r2
	lsl r15, r15, r1, true, .LBB0_54
.Ltmp125:
.LBB0_53:
	//DEBUG_VALUE: __mulXf3__:scale <- $r16
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: normalize:shift <- $r1
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	lsl r14, r15, r1
	move r15, 0
.Ltmp126:
.LBB0_54:
	//DEBUG_VALUE: __mulXf3__:scale <- $r16
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r11
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r10
	//DEBUG_VALUE: __mulXf3__:productSign <- $d12
	.loc	4 60 39                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:60:39
	sub r0, r16, r0
	add r0, r0, 12
.Ltmp127:
	//DEBUG_VALUE: __mulXf3__:scale <- $r0
	sw r22, -16, r0
.Ltmp128:
	//DEBUG_VALUE: __mulXf3__:scale <- [DW_OP_constu 16, DW_OP_minus] [$r22+0]
	.loc	4 0 39 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:39
	jump .LBB0_3
.Ltmp129:
.Lfunc_end0:
	.size	__muldf3, .Lfunc_end0-__muldf3
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__muldf3
	.long	.Lfunc_begin0
	.byte	72
	.section	.text.__muldf3,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp9-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp39-.Lfunc_begin0
	.long	.Ltmp45-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp57-.Lfunc_begin0
	.long	.Ltmp63-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp64-.Lfunc_begin0
	.long	.Ltmp65-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp84-.Lfunc_begin0
	.long	.Ltmp85-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp86-.Lfunc_begin0
	.long	.Ltmp87-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp91-.Lfunc_begin0
	.long	.Ltmp92-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp93-.Lfunc_begin0
	.long	.Ltmp94-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp95-.Lfunc_begin0
	.long	.Ltmp97-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp98-.Lfunc_begin0
	.long	.Ltmp99-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp100-.Lfunc_begin0
	.long	.Ltmp101-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp108-.Lfunc_begin0
	.long	.Ltmp109-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp9-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp39-.Lfunc_begin0
	.long	.Ltmp45-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp57-.Lfunc_begin0
	.long	.Ltmp63-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp64-.Lfunc_begin0
	.long	.Ltmp66-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp84-.Lfunc_begin0
	.long	.Ltmp85-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp86-.Lfunc_begin0
	.long	.Ltmp88-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp89-.Lfunc_begin0
	.long	.Ltmp92-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp93-.Lfunc_begin0
	.long	.Ltmp94-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp95-.Lfunc_begin0
	.long	.Ltmp97-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp98-.Lfunc_begin0
	.long	.Ltmp99-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp100-.Lfunc_begin0
	.long	.Ltmp102-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp108-.Lfunc_begin0
	.long	.Ltmp115-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp116-.Lfunc_begin0
	.long	.Ltmp118-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp119-.Lfunc_begin0
	.long	.Ltmp124-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp9-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp39-.Lfunc_begin0
	.long	.Ltmp45-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp57-.Lfunc_begin0
	.long	.Ltmp63-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp64-.Lfunc_begin0
	.long	.Ltmp65-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp84-.Lfunc_begin0
	.long	.Ltmp85-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp86-.Lfunc_begin0
	.long	.Ltmp87-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp91-.Lfunc_begin0
	.long	.Ltmp92-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp93-.Lfunc_begin0
	.long	.Ltmp94-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp95-.Lfunc_begin0
	.long	.Ltmp97-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp98-.Lfunc_begin0
	.long	.Ltmp99-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp100-.Lfunc_begin0
	.long	.Ltmp101-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp108-.Lfunc_begin0
	.long	.Ltmp109-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp9-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp39-.Lfunc_begin0
	.long	.Ltmp45-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp57-.Lfunc_begin0
	.long	.Ltmp63-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp64-.Lfunc_begin0
	.long	.Ltmp66-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp84-.Lfunc_begin0
	.long	.Ltmp85-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp86-.Lfunc_begin0
	.long	.Ltmp88-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp89-.Lfunc_begin0
	.long	.Ltmp92-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp93-.Lfunc_begin0
	.long	.Ltmp94-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp95-.Lfunc_begin0
	.long	.Ltmp97-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp98-.Lfunc_begin0
	.long	.Ltmp99-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp100-.Lfunc_begin0
	.long	.Ltmp102-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp108-.Lfunc_begin0
	.long	.Ltmp115-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp116-.Lfunc_begin0
	.long	.Ltmp118-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp119-.Lfunc_begin0
	.long	.Ltmp124-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc4:
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp26-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	90                              // DW_OP_reg10
	.long	.Ltmp39-.Lfunc_begin0
	.long	.Ltmp45-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	90                              // DW_OP_reg10
	.long	.Ltmp57-.Lfunc_begin0
	.long	.Ltmp63-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	90                              // DW_OP_reg10
	.long	.Ltmp64-.Lfunc_begin0
	.long	.Ltmp66-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	90                              // DW_OP_reg10
	.long	.Ltmp84-.Lfunc_begin0
	.long	.Ltmp85-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	90                              // DW_OP_reg10
	.long	.Ltmp86-.Lfunc_begin0
	.long	.Ltmp88-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	90                              // DW_OP_reg10
	.long	.Ltmp89-.Lfunc_begin0
	.long	.Ltmp92-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	90                              // DW_OP_reg10
	.long	.Ltmp93-.Lfunc_begin0
	.long	.Ltmp94-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	90                              // DW_OP_reg10
	.long	.Ltmp95-.Lfunc_begin0
	.long	.Ltmp97-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	90                              // DW_OP_reg10
	.long	.Ltmp98-.Lfunc_begin0
	.long	.Ltmp99-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	90                              // DW_OP_reg10
	.long	.Ltmp100-.Lfunc_begin0
	.long	.Ltmp102-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	90                              // DW_OP_reg10
	.long	.Ltmp108-.Lfunc_begin0
	.long	.Ltmp115-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	90                              // DW_OP_reg10
	.long	.Ltmp116-.Lfunc_begin0
	.long	.Ltmp118-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	90                              // DW_OP_reg10
	.long	.Ltmp119-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	90                              // DW_OP_reg10
	.long	0
	.long	0
.Ldebug_loc5:
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp26-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	91                              // DW_OP_reg11
	.long	.Ltmp39-.Lfunc_begin0
	.long	.Ltmp45-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	91                              // DW_OP_reg11
	.long	.Ltmp57-.Lfunc_begin0
	.long	.Ltmp63-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	91                              // DW_OP_reg11
	.long	.Ltmp64-.Lfunc_begin0
	.long	.Ltmp66-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	91                              // DW_OP_reg11
	.long	.Ltmp84-.Lfunc_begin0
	.long	.Ltmp85-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	91                              // DW_OP_reg11
	.long	.Ltmp86-.Lfunc_begin0
	.long	.Ltmp88-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	91                              // DW_OP_reg11
	.long	.Ltmp89-.Lfunc_begin0
	.long	.Ltmp92-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	91                              // DW_OP_reg11
	.long	.Ltmp93-.Lfunc_begin0
	.long	.Ltmp94-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	91                              // DW_OP_reg11
	.long	.Ltmp95-.Lfunc_begin0
	.long	.Ltmp97-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	91                              // DW_OP_reg11
	.long	.Ltmp98-.Lfunc_begin0
	.long	.Ltmp99-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	91                              // DW_OP_reg11
	.long	.Ltmp100-.Lfunc_begin0
	.long	.Ltmp102-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	91                              // DW_OP_reg11
	.long	.Ltmp108-.Lfunc_begin0
	.long	.Ltmp115-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	91                              // DW_OP_reg11
	.long	.Ltmp116-.Lfunc_begin0
	.long	.Ltmp118-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	91                              // DW_OP_reg11
	.long	.Ltmp119-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	91                              // DW_OP_reg11
	.long	0
	.long	0
.Ldebug_loc6:
	.long	.Ltmp4-.Lfunc_begin0
	.long	.Ltmp34-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	93                              // sub-register DW_OP_reg13
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	92                              // sub-register DW_OP_reg12
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp35-.Lfunc_begin0
	.long	.Ltmp37-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	93                              // sub-register DW_OP_reg13
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	92                              // sub-register DW_OP_reg12
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp39-.Lfunc_begin0
	.long	.Ltmp43-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	93                              // sub-register DW_OP_reg13
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	92                              // sub-register DW_OP_reg12
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp45-.Lfunc_begin0
	.long	.Ltmp47-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	93                              // sub-register DW_OP_reg13
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	92                              // sub-register DW_OP_reg12
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp57-.Lfunc_begin0
	.long	.Ltmp60-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	93                              // sub-register DW_OP_reg13
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	92                              // sub-register DW_OP_reg12
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp62-.Lfunc_begin0
	.long	.Ltmp63-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	93                              // sub-register DW_OP_reg13
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	92                              // sub-register DW_OP_reg12
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp64-.Lfunc_begin0
	.long	.Ltmp66-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	93                              // sub-register DW_OP_reg13
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	92                              // sub-register DW_OP_reg12
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp84-.Lfunc_begin0
	.long	.Ltmp85-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	93                              // sub-register DW_OP_reg13
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	92                              // sub-register DW_OP_reg12
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp86-.Lfunc_begin0
	.long	.Ltmp88-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	93                              // sub-register DW_OP_reg13
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	92                              // sub-register DW_OP_reg12
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp89-.Lfunc_begin0
	.long	.Ltmp90-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	93                              // sub-register DW_OP_reg13
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	92                              // sub-register DW_OP_reg12
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp91-.Lfunc_begin0
	.long	.Ltmp92-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	93                              // sub-register DW_OP_reg13
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	92                              // sub-register DW_OP_reg12
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp93-.Lfunc_begin0
	.long	.Ltmp94-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	93                              // sub-register DW_OP_reg13
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	92                              // sub-register DW_OP_reg12
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp95-.Lfunc_begin0
	.long	.Ltmp97-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	93                              // sub-register DW_OP_reg13
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	92                              // sub-register DW_OP_reg12
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp98-.Lfunc_begin0
	.long	.Ltmp99-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	93                              // sub-register DW_OP_reg13
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	92                              // sub-register DW_OP_reg12
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp100-.Lfunc_begin0
	.long	.Ltmp102-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	93                              // sub-register DW_OP_reg13
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	92                              // sub-register DW_OP_reg12
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp108-.Lfunc_begin0
	.long	.Ltmp115-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	93                              // sub-register DW_OP_reg13
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	92                              // sub-register DW_OP_reg12
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp116-.Lfunc_begin0
	.long	.Ltmp118-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	93                              // sub-register DW_OP_reg13
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	92                              // sub-register DW_OP_reg12
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp119-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	93                              // sub-register DW_OP_reg13
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	92                              // sub-register DW_OP_reg12
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc7:
	.long	.Ltmp6-.Lfunc_begin0
	.long	.Ltmp9-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp9-.Lfunc_begin0
	.long	.Ltmp30-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	134                             // DW_OP_breg22
	.byte	112                             // -16
	.long	.Ltmp30-.Lfunc_begin0
	.long	.Ltmp33-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp39-.Lfunc_begin0
	.long	.Ltmp45-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp57-.Lfunc_begin0
	.long	.Ltmp63-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp64-.Lfunc_begin0
	.long	.Ltmp66-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp84-.Lfunc_begin0
	.long	.Ltmp85-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp86-.Lfunc_begin0
	.long	.Ltmp88-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp89-.Lfunc_begin0
	.long	.Ltmp92-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp93-.Lfunc_begin0
	.long	.Ltmp94-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp95-.Lfunc_begin0
	.long	.Ltmp97-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp98-.Lfunc_begin0
	.long	.Ltmp99-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp100-.Lfunc_begin0
	.long	.Ltmp102-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp108-.Lfunc_begin0
	.long	.Ltmp114-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp114-.Lfunc_begin0
	.long	.Ltmp115-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	96                              // DW_OP_reg16
	.long	.Ltmp116-.Lfunc_begin0
	.long	.Ltmp118-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	96                              // DW_OP_reg16
	.long	.Ltmp119-.Lfunc_begin0
	.long	.Ltmp127-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	96                              // DW_OP_reg16
	.long	.Ltmp127-.Lfunc_begin0
	.long	.Ltmp128-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp128-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	134                             // DW_OP_breg22
	.byte	112                             // -16
	.long	0
	.long	0
.Ldebug_loc8:
	.long	.Ltmp13-.Lfunc_begin0
	.long	.Ltmp21-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	134                             // DW_OP_breg22
	.byte	88                              // -40
	.long	.Ltmp21-.Lfunc_begin0
	.long	.Ltmp25-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	89                              // sub-register DW_OP_reg9
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	88                              // sub-register DW_OP_reg8
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc9:
	.long	.Ltmp16-.Lfunc_begin0
	.long	.Ltmp34-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	97                              // sub-register DW_OP_reg17
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	96                              // sub-register DW_OP_reg16
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc10:
	.long	.Ltmp19-.Lfunc_begin0
	.long	.Ltmp34-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	99                              // sub-register DW_OP_reg19
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	98                              // sub-register DW_OP_reg18
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc11:
	.long	.Ltmp20-.Lfunc_begin0
	.long	.Ltmp28-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc12:
	.long	.Ltmp22-.Lfunc_begin0
	.long	.Ltmp27-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc13:
	.long	.Ltmp23-.Lfunc_begin0
	.long	.Ltmp24-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc14:
	.long	.Ltmp33-.Lfunc_begin0
	.long	.Ltmp34-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp35-.Lfunc_begin0
	.long	.Ltmp36-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp45-.Lfunc_begin0
	.long	.Ltmp49-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp50-.Lfunc_begin0
	.long	.Ltmp51-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp53-.Lfunc_begin0
	.long	.Ltmp54-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp56-.Lfunc_begin0
	.long	.Ltmp57-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	93                              // sub-register DW_OP_reg13
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	92                              // sub-register DW_OP_reg12
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp73-.Lfunc_begin0
	.long	.Ltmp74-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	93                              // sub-register DW_OP_reg13
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	92                              // sub-register DW_OP_reg12
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc15:
	.long	.Ltmp33-.Lfunc_begin0
	.long	.Ltmp34-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp35-.Lfunc_begin0
	.long	.Ltmp39-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp45-.Lfunc_begin0
	.long	.Ltmp52-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	.Ltmp74-.Lfunc_begin0
	.long	.Ltmp77-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	85                              // DW_OP_reg5
	.long	0
	.long	0
.Ldebug_loc16:
	.long	.Ltmp58-.Lfunc_begin0
	.long	.Ltmp63-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp64-.Lfunc_begin0
	.long	.Ltmp66-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp84-.Lfunc_begin0
	.long	.Ltmp85-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp86-.Lfunc_begin0
	.long	.Ltmp88-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp89-.Lfunc_begin0
	.long	.Ltmp92-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp93-.Lfunc_begin0
	.long	.Ltmp94-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp95-.Lfunc_begin0
	.long	.Ltmp97-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp98-.Lfunc_begin0
	.long	.Ltmp99-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp109-.Lfunc_begin0
	.long	.Ltmp115-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp116-.Lfunc_begin0
	.long	.Ltmp117-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp120-.Lfunc_begin0
	.long	.Ltmp121-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc17:
	.long	.Ltmp40-.Lfunc_begin0
	.long	.Ltmp45-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp57-.Lfunc_begin0
	.long	.Ltmp63-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp64-.Lfunc_begin0
	.long	.Ltmp66-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp84-.Lfunc_begin0
	.long	.Ltmp85-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp86-.Lfunc_begin0
	.long	.Ltmp88-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp89-.Lfunc_begin0
	.long	.Ltmp92-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp93-.Lfunc_begin0
	.long	.Ltmp94-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp95-.Lfunc_begin0
	.long	.Ltmp96-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	87                              // sub-register DW_OP_reg7
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	86                              // sub-register DW_OP_reg6
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc18:
	.long	.Ltmp54-.Lfunc_begin0
	.long	.Ltmp56-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp69-.Lfunc_begin0
	.long	.Ltmp71-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp72-.Lfunc_begin0
	.long	.Ltmp74-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc19:
	.long	.Ltmp75-.Lfunc_begin0
	.long	.Ltmp84-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp102-.Lfunc_begin0
	.long	.Ltmp108-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	0
	.long	0
.Ldebug_loc20:
	.long	.Ltmp76-.Lfunc_begin0
	.long	.Ltmp84-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp102-.Lfunc_begin0
	.long	.Ltmp108-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	0
	.long	0
.Ldebug_loc21:
	.long	.Ltmp81-.Lfunc_begin0
	.long	.Ltmp84-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	117                             // DW_OP_breg5
	.byte	0                               // 0
	.byte	16                              // DW_OP_constu
	.byte	1                               // 1
	.byte	26                              // DW_OP_and
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp105-.Lfunc_begin0
	.long	.Ltmp108-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	117                             // DW_OP_breg5
	.byte	0                               // 0
	.byte	16                              // DW_OP_constu
	.byte	1                               // 1
	.byte	26                              // DW_OP_and
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc22:
	.long	.Ltmp110-.Lfunc_begin0
	.long	.Ltmp114-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc23:
	.long	.Ltmp123-.Lfunc_begin0
	.long	.Ltmp126-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	23                              // DW_TAG_union_type
	.byte	1                               // DW_CHILDREN_yes
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	13                              // DW_TAG_member
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	56                              // DW_AT_data_member_location
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	11                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	12                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	13                              // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	14                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	5                               // DW_FORM_data2
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	15                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	5                               // DW_FORM_data2
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	16                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	5                               // DW_FORM_data2
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	17                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	18                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	19                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	1                               // DW_CHILDREN_yes
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	20                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	21                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	22                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	23                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	1                               // DW_CHILDREN_yes
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	24                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	25                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	26                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	27                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	28                              // DW_AT_const_value
	.byte	13                              // DW_FORM_sdata
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	28                              // Abbreviation Code
	.ascii	"\211\202\001"                  // DW_TAG_GNU_call_site
	.byte	0                               // DW_CHILDREN_no
	.ascii	"\223B"                         // DW_AT_GNU_call_site_target
	.byte	24                              // DW_FORM_exprloc
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x4b5 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	3                               // Abbrev [3] 0x2d:0xb DW_TAG_typedef
	.long	56                              // DW_AT_type
	.long	.Linfo_string6                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	68                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x38:0xb DW_TAG_typedef
	.long	67                              // DW_AT_type
	.long	.Linfo_string5                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	53                              // DW_AT_decl_line
	.byte	2                               // Abbrev [2] 0x43:0x7 DW_TAG_base_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x4a:0x23 DW_TAG_subprogram
	.long	.Linfo_string7                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	229                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	45                              // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0x56:0xb DW_TAG_formal_parameter
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	229                             // DW_AT_decl_line
	.long	109                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x61:0xb DW_TAG_variable
	.long	.Linfo_string11                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	234                             // DW_AT_decl_line
	.long	127                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	3                               // Abbrev [3] 0x6d:0xb DW_TAG_typedef
	.long	120                             // DW_AT_type
	.long	.Linfo_string10                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	70                              // DW_AT_decl_line
	.byte	2                               // Abbrev [2] 0x78:0x7 DW_TAG_base_type
	.long	.Linfo_string9                  // DW_AT_name
	.byte	4                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	7                               // Abbrev [7] 0x7f:0x5 DW_TAG_const_type
	.long	133                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x84:0x1f DW_TAG_subprogram
	.byte	9                               // Abbrev [9] 0x85:0x1d DW_TAG_union_type
	.byte	8                               // DW_AT_byte_size
	.byte	2                               // DW_AT_decl_file
	.byte	231                             // DW_AT_decl_line
	.byte	10                              // Abbrev [10] 0x89:0xc DW_TAG_member
	.long	.Linfo_string12                 // DW_AT_name
	.long	109                             // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	232                             // DW_AT_decl_line
	.byte	0                               // DW_AT_data_member_location
	.byte	10                              // Abbrev [10] 0x95:0xc DW_TAG_member
	.long	.Linfo_string13                 // DW_AT_name
	.long	45                              // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	233                             // DW_AT_decl_line
	.byte	0                               // DW_AT_data_member_location
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	4                               // Abbrev [4] 0xa3:0xab DW_TAG_subprogram
	.long	.Linfo_string14                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	17                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	109                             // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0xaf:0xb DW_TAG_formal_parameter
	.long	.Linfo_string15                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	17                              // DW_AT_decl_line
	.long	109                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0xba:0xb DW_TAG_formal_parameter
	.long	.Linfo_string16                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	17                              // DW_AT_decl_line
	.long	109                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xc5:0xb DW_TAG_variable
	.long	.Linfo_string17                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	18                              // DW_AT_decl_line
	.long	334                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xd0:0xb DW_TAG_variable
	.long	.Linfo_string18                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	19                              // DW_AT_decl_line
	.long	334                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xdb:0xb DW_TAG_variable
	.long	.Linfo_string19                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	20                              // DW_AT_decl_line
	.long	339                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xe6:0xb DW_TAG_variable
	.long	.Linfo_string20                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0xf1:0xb DW_TAG_variable
	.long	.Linfo_string21                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	24                              // DW_AT_decl_line
	.long	344                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xfc:0xb DW_TAG_variable
	.long	.Linfo_string23                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	23                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0x107:0xb DW_TAG_variable
	.long	.Linfo_string24                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	74                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0x112:0xb DW_TAG_variable
	.long	.Linfo_string25                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	78                              // DW_AT_decl_line
	.long	344                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x11d:0xb DW_TAG_variable
	.long	.Linfo_string26                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	74                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	11                              // Abbrev [11] 0x128:0x18 DW_TAG_lexical_block
	.byte	6                               // Abbrev [6] 0x129:0xb DW_TAG_variable
	.long	.Linfo_string27                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	30                              // DW_AT_decl_line
	.long	339                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x134:0xb DW_TAG_variable
	.long	.Linfo_string28                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	29                              // DW_AT_decl_line
	.long	339                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	11                              // Abbrev [11] 0x140:0xd DW_TAG_lexical_block
	.byte	6                               // Abbrev [6] 0x141:0xb DW_TAG_variable
	.long	.Linfo_string29                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	94                              // DW_AT_decl_line
	.long	334                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x14e:0x5 DW_TAG_const_type
	.long	38                              // DW_AT_type
	.byte	7                               // Abbrev [7] 0x153:0x5 DW_TAG_const_type
	.long	45                              // DW_AT_type
	.byte	2                               // Abbrev [2] 0x158:0x7 DW_TAG_base_type
	.long	.Linfo_string22                 // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	12                              // Abbrev [12] 0x15f:0x77 DW_TAG_subprogram
	.long	.Linfo_string30                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	94                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0x167:0xb DW_TAG_formal_parameter
	.long	.Linfo_string15                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	94                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	5                               // Abbrev [5] 0x172:0xb DW_TAG_formal_parameter
	.long	.Linfo_string16                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	94                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	5                               // Abbrev [5] 0x17d:0xb DW_TAG_formal_parameter
	.long	.Linfo_string31                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	94                              // DW_AT_decl_line
	.long	470                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0x188:0xb DW_TAG_formal_parameter
	.long	.Linfo_string32                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	94                              // DW_AT_decl_line
	.long	470                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x193:0xb DW_TAG_variable
	.long	.Linfo_string33                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	97                              // DW_AT_decl_line
	.long	475                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x19e:0xb DW_TAG_variable
	.long	.Linfo_string34                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	98                              // DW_AT_decl_line
	.long	475                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x1a9:0xb DW_TAG_variable
	.long	.Linfo_string35                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	99                              // DW_AT_decl_line
	.long	475                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x1b4:0xb DW_TAG_variable
	.long	.Linfo_string36                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	100                             // DW_AT_decl_line
	.long	475                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x1bf:0xb DW_TAG_variable
	.long	.Linfo_string37                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	103                             // DW_AT_decl_line
	.long	475                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x1ca:0xb DW_TAG_variable
	.long	.Linfo_string38                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	102                             // DW_AT_decl_line
	.long	475                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	13                              // Abbrev [13] 0x1d6:0x5 DW_TAG_pointer_type
	.long	45                              // DW_AT_type
	.byte	7                               // Abbrev [7] 0x1db:0x5 DW_TAG_const_type
	.long	56                              // DW_AT_type
	.byte	14                              // Abbrev [14] 0x1e0:0x2e DW_TAG_subprogram
	.long	.Linfo_string39                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	257                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.byte	1                               // DW_AT_inline
	.byte	15                              // Abbrev [15] 0x1e9:0xc DW_TAG_formal_parameter
	.long	.Linfo_string31                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	257                             // DW_AT_decl_line
	.long	470                             // DW_AT_type
	.byte	15                              // Abbrev [15] 0x1f5:0xc DW_TAG_formal_parameter
	.long	.Linfo_string32                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	257                             // DW_AT_decl_line
	.long	470                             // DW_AT_type
	.byte	15                              // Abbrev [15] 0x201:0xc DW_TAG_formal_parameter
	.long	.Linfo_string40                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	257                             // DW_AT_decl_line
	.long	344                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	14                              // Abbrev [14] 0x20e:0x58 DW_TAG_subprogram
	.long	.Linfo_string41                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	264                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.byte	1                               // DW_AT_inline
	.byte	15                              // Abbrev [15] 0x217:0xc DW_TAG_formal_parameter
	.long	.Linfo_string31                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	264                             // DW_AT_decl_line
	.long	470                             // DW_AT_type
	.byte	15                              // Abbrev [15] 0x223:0xc DW_TAG_formal_parameter
	.long	.Linfo_string32                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	264                             // DW_AT_decl_line
	.long	470                             // DW_AT_type
	.byte	15                              // Abbrev [15] 0x22f:0xc DW_TAG_formal_parameter
	.long	.Linfo_string40                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	264                             // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	11                              // Abbrev [11] 0x23b:0xe DW_TAG_lexical_block
	.byte	16                              // Abbrev [16] 0x23c:0xc DW_TAG_variable
	.long	.Linfo_string42                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	267                             // DW_AT_decl_line
	.long	614                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	11                              // Abbrev [11] 0x249:0xe DW_TAG_lexical_block
	.byte	16                              // Abbrev [16] 0x24a:0xc DW_TAG_variable
	.long	.Linfo_string42                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	271                             // DW_AT_decl_line
	.long	614                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	11                              // Abbrev [11] 0x257:0xe DW_TAG_lexical_block
	.byte	16                              // Abbrev [16] 0x258:0xc DW_TAG_variable
	.long	.Linfo_string42                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	275                             // DW_AT_decl_line
	.long	614                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x266:0x5 DW_TAG_const_type
	.long	619                             // DW_AT_type
	.byte	2                               // Abbrev [2] 0x26b:0x7 DW_TAG_base_type
	.long	.Linfo_string43                 // DW_AT_name
	.byte	2                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x272:0x18 DW_TAG_subprogram
	.long	.Linfo_string44                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	75                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	344                             // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0x27e:0xb DW_TAG_formal_parameter
	.long	.Linfo_string15                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	75                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	4                               // Abbrev [4] 0x28a:0x23 DW_TAG_subprogram
	.long	.Linfo_string45                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	249                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	344                             // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0x296:0xb DW_TAG_formal_parameter
	.long	.Linfo_string46                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	249                             // DW_AT_decl_line
	.long	470                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x2a1:0xb DW_TAG_variable
	.long	.Linfo_string29                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	251                             // DW_AT_decl_line
	.long	685                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x2ad:0x5 DW_TAG_const_type
	.long	344                             // DW_AT_type
	.byte	17                              // Abbrev [17] 0x2b2:0x20d DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string47                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	19                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	109                             // DW_AT_type
                                        // DW_AT_external
	.byte	18                              // Abbrev [18] 0x2c7:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string15                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	19                              // DW_AT_decl_line
	.long	109                             // DW_AT_type
	.byte	18                              // Abbrev [18] 0x2d6:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string16                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	19                              // DW_AT_decl_line
	.long	109                             // DW_AT_type
	.byte	19                              // Abbrev [19] 0x2e5:0x1bd DW_TAG_inlined_subroutine
	.long	163                             // DW_AT_abstract_origin
	.long	.Ldebug_ranges0                 // DW_AT_ranges
	.byte	3                               // DW_AT_call_file
	.byte	21                              // DW_AT_call_line
	.byte	12                              // DW_AT_call_column
	.byte	20                              // Abbrev [20] 0x2f1:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	175                             // DW_AT_abstract_origin
	.byte	20                              // Abbrev [20] 0x2fa:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	186                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x303:0x9 DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	197                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x30c:0x9 DW_TAG_variable
	.long	.Ldebug_loc5                    // DW_AT_location
	.long	208                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x315:0x9 DW_TAG_variable
	.long	.Ldebug_loc6                    // DW_AT_location
	.long	219                             // DW_AT_abstract_origin
	.byte	22                              // Abbrev [22] 0x31e:0x5 DW_TAG_variable
	.long	230                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x323:0x9 DW_TAG_variable
	.long	.Ldebug_loc7                    // DW_AT_location
	.long	241                             // DW_AT_abstract_origin
	.byte	22                              // Abbrev [22] 0x32c:0x5 DW_TAG_variable
	.long	252                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x331:0x9 DW_TAG_variable
	.long	.Ldebug_loc14                   // DW_AT_location
	.long	263                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x33a:0x9 DW_TAG_variable
	.long	.Ldebug_loc15                   // DW_AT_location
	.long	274                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x343:0x9 DW_TAG_variable
	.long	.Ldebug_loc18                   // DW_AT_location
	.long	285                             // DW_AT_abstract_origin
	.byte	23                              // Abbrev [23] 0x34c:0x1d DW_TAG_inlined_subroutine
	.long	74                              // DW_AT_abstract_origin
	.long	.Ltmp0                          // DW_AT_low_pc
	.long	.Ltmp1-.Ltmp0                   // DW_AT_high_pc
	.byte	4                               // DW_AT_call_file
	.byte	18                              // DW_AT_call_line
	.byte	36                              // DW_AT_call_column
	.byte	24                              // Abbrev [24] 0x35c:0xc DW_TAG_formal_parameter
	.byte	6                               // DW_AT_location
	.byte	81
	.byte	147
	.byte	4
	.byte	80
	.byte	147
	.byte	4
	.long	86                              // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	25                              // Abbrev [25] 0x369:0x7e DW_TAG_lexical_block
	.long	.Ldebug_ranges2                 // DW_AT_ranges
	.byte	21                              // Abbrev [21] 0x36e:0x9 DW_TAG_variable
	.long	.Ldebug_loc16                   // DW_AT_location
	.long	297                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x377:0x9 DW_TAG_variable
	.long	.Ldebug_loc17                   // DW_AT_location
	.long	308                             // DW_AT_abstract_origin
	.byte	19                              // Abbrev [19] 0x380:0x31 DW_TAG_inlined_subroutine
	.long	650                             // DW_AT_abstract_origin
	.long	.Ldebug_ranges1                 // DW_AT_ranges
	.byte	4                               // DW_AT_call_file
	.byte	59                              // DW_AT_call_line
	.byte	42                              // DW_AT_call_column
	.byte	26                              // Abbrev [26] 0x38c:0x5 DW_TAG_formal_parameter
	.long	662                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x391:0x9 DW_TAG_variable
	.long	.Ldebug_loc22                   // DW_AT_location
	.long	673                             // DW_AT_abstract_origin
	.byte	23                              // Abbrev [23] 0x39a:0x16 DW_TAG_inlined_subroutine
	.long	626                             // DW_AT_abstract_origin
	.long	.Ltmp98                         // DW_AT_low_pc
	.long	.Ltmp100-.Ltmp98                // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	251                             // DW_AT_call_line
	.byte	23                              // DW_AT_call_column
	.byte	26                              // Abbrev [26] 0x3aa:0x5 DW_TAG_formal_parameter
	.long	638                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	23                              // Abbrev [23] 0x3b1:0x35 DW_TAG_inlined_subroutine
	.long	650                             // DW_AT_abstract_origin
	.long	.Ltmp116                        // DW_AT_low_pc
	.long	.Ltmp126-.Ltmp116               // DW_AT_high_pc
	.byte	4                               // DW_AT_call_file
	.byte	60                              // DW_AT_call_line
	.byte	42                              // DW_AT_call_column
	.byte	26                              // Abbrev [26] 0x3c1:0x5 DW_TAG_formal_parameter
	.long	662                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x3c6:0x9 DW_TAG_variable
	.long	.Ldebug_loc23                   // DW_AT_location
	.long	673                             // DW_AT_abstract_origin
	.byte	23                              // Abbrev [23] 0x3cf:0x16 DW_TAG_inlined_subroutine
	.long	626                             // DW_AT_abstract_origin
	.long	.Ltmp116                        // DW_AT_low_pc
	.long	.Ltmp119-.Ltmp116               // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	251                             // DW_AT_call_line
	.byte	23                              // DW_AT_call_column
	.byte	26                              // Abbrev [26] 0x3df:0x5 DW_TAG_formal_parameter
	.long	638                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	23                              // Abbrev [23] 0x3e7:0x5b DW_TAG_inlined_subroutine
	.long	351                             // DW_AT_abstract_origin
	.long	.Ltmp10                         // DW_AT_low_pc
	.long	.Ltmp29-.Ltmp10                 // DW_AT_high_pc
	.byte	4                               // DW_AT_call_file
	.byte	75                              // DW_AT_call_line
	.byte	5                               // DW_AT_call_column
	.byte	26                              // Abbrev [26] 0x3f7:0x5 DW_TAG_formal_parameter
	.long	359                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x3fc:0x5 DW_TAG_formal_parameter
	.long	370                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x401:0x5 DW_TAG_formal_parameter
	.long	381                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x406:0x5 DW_TAG_formal_parameter
	.long	392                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x40b:0x9 DW_TAG_variable
	.long	.Ldebug_loc8                    // DW_AT_location
	.long	403                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x414:0x9 DW_TAG_variable
	.long	.Ldebug_loc9                    // DW_AT_location
	.long	414                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x41d:0x9 DW_TAG_variable
	.long	.Ldebug_loc10                   // DW_AT_location
	.long	425                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x426:0x9 DW_TAG_variable
	.long	.Ldebug_loc11                   // DW_AT_location
	.long	436                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x42f:0x9 DW_TAG_variable
	.long	.Ldebug_loc12                   // DW_AT_location
	.long	447                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x438:0x9 DW_TAG_variable
	.long	.Ldebug_loc13                   // DW_AT_location
	.long	458                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	23                              // Abbrev [23] 0x442:0x21 DW_TAG_inlined_subroutine
	.long	480                             // DW_AT_abstract_origin
	.long	.Ltmp35                         // DW_AT_low_pc
	.long	.Ltmp38-.Ltmp35                 // DW_AT_high_pc
	.byte	4                               // DW_AT_call_file
	.byte	82                              // DW_AT_call_line
	.byte	10                              // DW_AT_call_column
	.byte	26                              // Abbrev [26] 0x452:0x5 DW_TAG_formal_parameter
	.long	489                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x457:0x5 DW_TAG_formal_parameter
	.long	501                             // DW_AT_abstract_origin
	.byte	27                              // Abbrev [27] 0x45c:0x6 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_const_value
	.long	513                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	25                              // Abbrev [25] 0x463:0x3e DW_TAG_lexical_block
	.long	.Ldebug_ranges5                 // DW_AT_ranges
	.byte	21                              // Abbrev [21] 0x468:0x9 DW_TAG_variable
	.long	.Ldebug_loc19                   // DW_AT_location
	.long	321                             // DW_AT_abstract_origin
	.byte	19                              // Abbrev [19] 0x471:0x2f DW_TAG_inlined_subroutine
	.long	526                             // DW_AT_abstract_origin
	.long	.Ldebug_ranges3                 // DW_AT_ranges
	.byte	4                               // DW_AT_call_file
	.byte	99                              // DW_AT_call_line
	.byte	9                               // DW_AT_call_column
	.byte	26                              // Abbrev [26] 0x47d:0x5 DW_TAG_formal_parameter
	.long	535                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x482:0x5 DW_TAG_formal_parameter
	.long	547                             // DW_AT_abstract_origin
	.byte	20                              // Abbrev [20] 0x487:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc20                   // DW_AT_location
	.long	559                             // DW_AT_abstract_origin
	.byte	25                              // Abbrev [25] 0x490:0xf DW_TAG_lexical_block
	.long	.Ldebug_ranges4                 // DW_AT_ranges
	.byte	21                              // Abbrev [21] 0x495:0x9 DW_TAG_variable
	.long	.Ldebug_loc21                   // DW_AT_location
	.long	572                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	28                              // Abbrev [28] 0x4a2:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp12                         // DW_AT_low_pc
	.byte	28                              // Abbrev [28] 0x4a9:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp15                         // DW_AT_low_pc
	.byte	28                              // Abbrev [28] 0x4b0:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp18                         // DW_AT_low_pc
	.byte	28                              // Abbrev [28] 0x4b7:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp20                         // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_ranges,"",@progbits
.Ldebug_ranges0:
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp68-.Lfunc_begin0
	.long	.Ltmp70-.Lfunc_begin0
	.long	.Ltmp129-.Lfunc_begin0
	.long	0
	.long	0
.Ldebug_ranges1:
	.long	.Ltmp98-.Lfunc_begin0
	.long	.Ltmp100-.Lfunc_begin0
	.long	.Ltmp109-.Lfunc_begin0
	.long	.Ltmp114-.Lfunc_begin0
	.long	0
	.long	0
.Ldebug_ranges2:
	.long	.Ltmp39-.Lfunc_begin0
	.long	.Ltmp45-.Lfunc_begin0
	.long	.Ltmp57-.Lfunc_begin0
	.long	.Ltmp67-.Lfunc_begin0
	.long	.Ltmp84-.Lfunc_begin0
	.long	.Ltmp100-.Lfunc_begin0
	.long	.Ltmp109-.Lfunc_begin0
	.long	.Ltmp129-.Lfunc_begin0
	.long	0
	.long	0
.Ldebug_ranges3:
	.long	.Ltmp76-.Lfunc_begin0
	.long	.Ltmp84-.Lfunc_begin0
	.long	.Ltmp102-.Lfunc_begin0
	.long	.Ltmp108-.Lfunc_begin0
	.long	0
	.long	0
.Ldebug_ranges4:
	.long	.Ltmp76-.Lfunc_begin0
	.long	.Ltmp84-.Lfunc_begin0
	.long	.Ltmp102-.Lfunc_begin0
	.long	.Ltmp108-.Lfunc_begin0
	.long	0
	.long	0
.Ldebug_ranges5:
	.long	.Ltmp74-.Lfunc_begin0
	.long	.Ltmp84-.Lfunc_begin0
	.long	.Ltmp102-.Lfunc_begin0
	.long	.Ltmp108-.Lfunc_begin0
	.long	0
	.long	0
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/muldf3.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=152
.Linfo_string3:
	.asciz	"unsigned int"                  // string offset=173
.Linfo_string4:
	.asciz	"long unsigned int"             // string offset=186
.Linfo_string5:
	.asciz	"uint64_t"                      // string offset=204
.Linfo_string6:
	.asciz	"rep_t"                         // string offset=213
.Linfo_string7:
	.asciz	"toRep"                         // string offset=219
.Linfo_string8:
	.asciz	"x"                             // string offset=225
.Linfo_string9:
	.asciz	"double"                        // string offset=227
.Linfo_string10:
	.asciz	"fp_t"                          // string offset=234
.Linfo_string11:
	.asciz	"rep"                           // string offset=239
.Linfo_string12:
	.asciz	"f"                             // string offset=243
.Linfo_string13:
	.asciz	"i"                             // string offset=245
.Linfo_string14:
	.asciz	"__mulXf3__"                    // string offset=247
.Linfo_string15:
	.asciz	"a"                             // string offset=258
.Linfo_string16:
	.asciz	"b"                             // string offset=260
.Linfo_string17:
	.asciz	"aExponent"                     // string offset=262
.Linfo_string18:
	.asciz	"bExponent"                     // string offset=272
.Linfo_string19:
	.asciz	"productSign"                   // string offset=282
.Linfo_string20:
	.asciz	"aSignificand"                  // string offset=294
.Linfo_string21:
	.asciz	"scale"                         // string offset=307
.Linfo_string22:
	.asciz	"int"                           // string offset=313
.Linfo_string23:
	.asciz	"bSignificand"                  // string offset=317
.Linfo_string24:
	.asciz	"productHi"                     // string offset=330
.Linfo_string25:
	.asciz	"productExponent"               // string offset=340
.Linfo_string26:
	.asciz	"productLo"                     // string offset=356
.Linfo_string27:
	.asciz	"bAbs"                          // string offset=366
.Linfo_string28:
	.asciz	"aAbs"                          // string offset=371
.Linfo_string29:
	.asciz	"shift"                         // string offset=376
.Linfo_string30:
	.asciz	"wideMultiply"                  // string offset=382
.Linfo_string31:
	.asciz	"hi"                            // string offset=395
.Linfo_string32:
	.asciz	"lo"                            // string offset=398
.Linfo_string33:
	.asciz	"plolo"                         // string offset=401
.Linfo_string34:
	.asciz	"plohi"                         // string offset=407
.Linfo_string35:
	.asciz	"philo"                         // string offset=413
.Linfo_string36:
	.asciz	"phihi"                         // string offset=419
.Linfo_string37:
	.asciz	"r1"                            // string offset=425
.Linfo_string38:
	.asciz	"r0"                            // string offset=428
.Linfo_string39:
	.asciz	"wideLeftShift"                 // string offset=431
.Linfo_string40:
	.asciz	"count"                         // string offset=445
.Linfo_string41:
	.asciz	"wideRightShiftWithSticky"      // string offset=451
.Linfo_string42:
	.asciz	"sticky"                        // string offset=476
.Linfo_string43:
	.asciz	"_Bool"                         // string offset=483
.Linfo_string44:
	.asciz	"rep_clz"                       // string offset=489
.Linfo_string45:
	.asciz	"normalize"                     // string offset=497
.Linfo_string46:
	.asciz	"significand"                   // string offset=507
.Linfo_string47:
	.asciz	"__muldf3"                      // string offset=519
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
