	.text
	.file	"mulosi4.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/syslib/int_types.h"
	.section	.text.__mulosi4,"ax",@progbits
	.globl	__mulosi4                       // -- Begin function __mulosi4
	.type	__mulosi4,@function
__mulosi4:                              // @__mulosi4
.Lfunc_begin0:
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/mulosi4.c"
	.loc	2 23 0                          // uPIMulator_frontend/sdk/syslib/mulosi4.c:23:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __mulosi4:a <- $r0
	//DEBUG_VALUE: __mulosi4:b <- $r1
	//DEBUG_VALUE: __mulosi4:overflow <- $r2
	.cfi_def_cfa_offset -24
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 16, d22
	add r22, r22, 24
	.cfi_offset 15, -16
	.cfi_offset 14, -12
	sd r22, -16, d14
	.cfi_offset 17, -24
	.cfi_offset 16, -20
	sd r22, -24, d16
	move r16, r2
	move r15, r1
	move r14, r0
	move r0, -2147483648
.Ltmp0:
	//DEBUG_VALUE: __mulosi4:result <- undef
	//DEBUG_VALUE: __mulosi4:MAX <- 2147483647
	//DEBUG_VALUE: __mulosi4:MIN <- -2147483648
	//DEBUG_VALUE: __mulosi4:N <- 32
	//DEBUG_VALUE: __mulosi4:overflow <- $r16
	//DEBUG_VALUE: __mulosi4:b <- $r15
	//DEBUG_VALUE: __mulosi4:a <- $r14
	.loc	2 27 15 prologue_end            // uPIMulator_frontend/sdk/syslib/mulosi4.c:27:15
	sw r16, 0, 0
	.loc	2 29 9                          // uPIMulator_frontend/sdk/syslib/mulosi4.c:29:9
	jneq r14, r0, .LBB0_2
.Ltmp1:
// %bb.1:
	//DEBUG_VALUE: __mulosi4:overflow <- $r16
	//DEBUG_VALUE: __mulosi4:b <- $r15
	//DEBUG_VALUE: __mulosi4:a <- $r14
	//DEBUG_VALUE: __mulosi4:N <- 32
	//DEBUG_VALUE: __mulosi4:MIN <- -2147483648
	//DEBUG_VALUE: __mulosi4:MAX <- 2147483647
	.loc	2 30 20                         // uPIMulator_frontend/sdk/syslib/mulosi4.c:30:20
	jgeu r15, 2, .LBB0_9
	jump .LBB0_10
.Ltmp2:
.LBB0_2:
	//DEBUG_VALUE: __mulosi4:overflow <- $r16
	//DEBUG_VALUE: __mulosi4:b <- $r15
	//DEBUG_VALUE: __mulosi4:a <- $r14
	//DEBUG_VALUE: __mulosi4:N <- 32
	//DEBUG_VALUE: __mulosi4:MIN <- -2147483648
	//DEBUG_VALUE: __mulosi4:MAX <- 2147483647
	.loc	2 34 9                          // uPIMulator_frontend/sdk/syslib/mulosi4.c:34:9
	jneq r15, r0, .LBB0_4
.Ltmp3:
// %bb.3:
	//DEBUG_VALUE: __mulosi4:overflow <- $r16
	//DEBUG_VALUE: __mulosi4:b <- $r15
	//DEBUG_VALUE: __mulosi4:a <- $r14
	//DEBUG_VALUE: __mulosi4:N <- 32
	//DEBUG_VALUE: __mulosi4:MIN <- -2147483648
	//DEBUG_VALUE: __mulosi4:MAX <- 2147483647
	.loc	2 35 20                         // uPIMulator_frontend/sdk/syslib/mulosi4.c:35:20
	jgeu r14, 2, .LBB0_9
	jump .LBB0_10
.Ltmp4:
.LBB0_4:
	//DEBUG_VALUE: __mulosi4:overflow <- $r16
	//DEBUG_VALUE: __mulosi4:b <- $r15
	//DEBUG_VALUE: __mulosi4:a <- $r14
	//DEBUG_VALUE: __mulosi4:N <- 32
	//DEBUG_VALUE: __mulosi4:MIN <- -2147483648
	//DEBUG_VALUE: __mulosi4:MAX <- 2147483647
	.loc	2 39 19                         // uPIMulator_frontend/sdk/syslib/mulosi4.c:39:19
	asr r0, r14, 31
.Ltmp5:
	//DEBUG_VALUE: __mulosi4:sa <- $r0
	.loc	2 40 23                         // uPIMulator_frontend/sdk/syslib/mulosi4.c:40:23
	xor r1, r0, r14
	.loc	2 40 29 is_stmt 0               // uPIMulator_frontend/sdk/syslib/mulosi4.c:40:29
	sub r17, r1, r0
.Ltmp6:
	//DEBUG_VALUE: __mulosi4:abs_b <- undef
	//DEBUG_VALUE: __mulosi4:sb <- undef
	//DEBUG_VALUE: __mulosi4:abs_a <- $r17
	.loc	2 43 19 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mulosi4.c:43:19
	jlts r17, 2, .LBB0_10
.Ltmp7:
// %bb.5:
	//DEBUG_VALUE: __mulosi4:abs_a <- $r17
	//DEBUG_VALUE: __mulosi4:overflow <- $r16
	//DEBUG_VALUE: __mulosi4:b <- $r15
	//DEBUG_VALUE: __mulosi4:a <- $r14
	//DEBUG_VALUE: __mulosi4:sa <- $r0
	//DEBUG_VALUE: __mulosi4:N <- 32
	//DEBUG_VALUE: __mulosi4:MIN <- -2147483648
	//DEBUG_VALUE: __mulosi4:MAX <- 2147483647
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/mulosi4.c:0:0
	asr r2, r15, 31
.Ltmp8:
	//DEBUG_VALUE: __mulosi4:sb <- $r2
	xor r1, r2, r15
	sub r1, r1, r2
.Ltmp9:
	//DEBUG_VALUE: __mulosi4:abs_b <- $r1
	.loc	2 43 19                         // uPIMulator_frontend/sdk/syslib/mulosi4.c:43:19
	jlts r1, 2, .LBB0_10
.Ltmp10:
// %bb.6:
	//DEBUG_VALUE: __mulosi4:abs_a <- $r17
	//DEBUG_VALUE: __mulosi4:overflow <- $r16
	//DEBUG_VALUE: __mulosi4:b <- $r15
	//DEBUG_VALUE: __mulosi4:a <- $r14
	//DEBUG_VALUE: __mulosi4:sb <- $r2
	//DEBUG_VALUE: __mulosi4:abs_b <- $r1
	//DEBUG_VALUE: __mulosi4:sa <- $r0
	//DEBUG_VALUE: __mulosi4:N <- 32
	//DEBUG_VALUE: __mulosi4:MIN <- -2147483648
	//DEBUG_VALUE: __mulosi4:MAX <- 2147483647
	.loc	2 45 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/mulosi4.c:45:9
	jneq r0, r2, .LBB0_8
.Ltmp11:
// %bb.7:
	//DEBUG_VALUE: __mulosi4:abs_a <- $r17
	//DEBUG_VALUE: __mulosi4:overflow <- $r16
	//DEBUG_VALUE: __mulosi4:b <- $r15
	//DEBUG_VALUE: __mulosi4:a <- $r14
	//DEBUG_VALUE: __mulosi4:sb <- $r2
	//DEBUG_VALUE: __mulosi4:abs_b <- $r1
	//DEBUG_VALUE: __mulosi4:sa <- $r0
	//DEBUG_VALUE: __mulosi4:N <- 32
	//DEBUG_VALUE: __mulosi4:MIN <- -2147483648
	//DEBUG_VALUE: __mulosi4:MAX <- 2147483647
	.loc	2 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/mulosi4.c:0:9
	move r0, 2147483647
.Ltmp12:
	.loc	2 46 25 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mulosi4.c:46:25
	call r23, __udiv32
.Ltmp13:
	.loc	2 46 13 is_stmt 0               // uPIMulator_frontend/sdk/syslib/mulosi4.c:46:13
	jgts r17, r0, .LBB0_9
	jump .LBB0_10
.Ltmp14:
.LBB0_8:
	//DEBUG_VALUE: __mulosi4:abs_a <- $r17
	//DEBUG_VALUE: __mulosi4:overflow <- $r16
	//DEBUG_VALUE: __mulosi4:b <- $r15
	//DEBUG_VALUE: __mulosi4:a <- $r14
	//DEBUG_VALUE: __mulosi4:sb <- $r2
	//DEBUG_VALUE: __mulosi4:abs_b <- $r1
	//DEBUG_VALUE: __mulosi4:sa <- $r0
	//DEBUG_VALUE: __mulosi4:N <- 32
	//DEBUG_VALUE: __mulosi4:MIN <- -2147483648
	//DEBUG_VALUE: __mulosi4:MAX <- 2147483647
	.loc	2 49 27 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mulosi4.c:49:27
	neg r1, r1
.Ltmp15:
	.loc	2 0 27 is_stmt 0                // uPIMulator_frontend/sdk/syslib/mulosi4.c:0:27
	move r0, -2147483648
.Ltmp16:
	.loc	2 49 25                         // uPIMulator_frontend/sdk/syslib/mulosi4.c:49:25
	call r23, __div32
.Ltmp17:
	.loc	2 49 13                         // uPIMulator_frontend/sdk/syslib/mulosi4.c:49:13
	jles r17, r0, .LBB0_10
.Ltmp18:
.LBB0_9:
	//DEBUG_VALUE: __mulosi4:overflow <- $r16
	//DEBUG_VALUE: __mulosi4:b <- $r15
	//DEBUG_VALUE: __mulosi4:a <- $r14
	//DEBUG_VALUE: __mulosi4:N <- 32
	//DEBUG_VALUE: __mulosi4:MIN <- -2147483648
	//DEBUG_VALUE: __mulosi4:MAX <- 2147483647
	.loc	2 0 0                           // uPIMulator_frontend/sdk/syslib/mulosi4.c:0:0
	sw r16, 0, 1
.Ltmp19:
.LBB0_10:
	//DEBUG_VALUE: __mulosi4:overflow <- $r16
	//DEBUG_VALUE: __mulosi4:b <- $r15
	//DEBUG_VALUE: __mulosi4:a <- $r14
	//DEBUG_VALUE: __mulosi4:N <- 32
	//DEBUG_VALUE: __mulosi4:MIN <- -2147483648
	//DEBUG_VALUE: __mulosi4:MAX <- 2147483647
	.loc	2 28 23 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mulosi4.c:28:23
	move r0, r15
	move r1, r14
	call r23, __mulsi3
.Ltmp20:
	//DEBUG_VALUE: __mulosi4:result <- $r0
	.loc	2 53 1                          // uPIMulator_frontend/sdk/syslib/mulosi4.c:53:1
	ld d16, r22, -24
.Ltmp21:
	ld d14, r22, -16
.Ltmp22:
	ld d22, r22, -8
	jump r23
.Ltmp23:
.Lfunc_end0:
	.size	__mulosi4, .Lfunc_end0-__mulosi4
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__mulosi4
	.long	.Lfunc_begin0
	.byte	24
	.section	.text.__mulosi4,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp22-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp22-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp21-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	96                              // DW_OP_reg16
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Ltmp20-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc4:
	.long	.Ltmp5-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Ltmp16-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc5:
	.long	.Ltmp9-.Lfunc_begin0
	.long	.Ltmp15-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc6:
	.long	.Ltmp8-.Lfunc_begin0
	.long	.Ltmp18-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc7:
	.long	.Ltmp6-.Lfunc_begin0
	.long	.Ltmp18-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	97                              // DW_OP_reg17
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	28                              // DW_AT_const_value
	.byte	13                              // DW_FORM_sdata
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.ascii	"\211\202\001"                  // DW_TAG_GNU_call_site
	.byte	0                               // DW_CHILDREN_no
	.ascii	"\223B"                         // DW_AT_GNU_call_site_target
	.byte	24                              // DW_FORM_exprloc
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x10c DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	3                               // Abbrev [3] 0x2d:0xb DW_TAG_typedef
	.long	38                              // DW_AT_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	27                              // DW_AT_decl_line
	.byte	4                               // Abbrev [4] 0x38:0xcf DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string5                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	45                              // DW_AT_type
                                        // DW_AT_external
	.byte	5                               // Abbrev [5] 0x4d:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string6                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	5                               // Abbrev [5] 0x5c:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string7                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	5                               // Abbrev [5] 0x6b:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
	.long	263                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x7a:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string9                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	28                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	7                               // Abbrev [7] 0x89:0x10 DW_TAG_variable
	.ascii	"\377\377\377\377\007"          // DW_AT_const_value
	.long	.Linfo_string10                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	26                              // DW_AT_decl_line
	.long	268                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0x99:0x10 DW_TAG_variable
	.ascii	"\200\200\200\200x"             // DW_AT_const_value
	.long	.Linfo_string11                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	25                              // DW_AT_decl_line
	.long	268                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0xa9:0xc DW_TAG_variable
	.byte	32                              // DW_AT_const_value
	.long	.Linfo_string12                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	24                              // DW_AT_decl_line
	.long	273                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xb5:0xf DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	.Linfo_string13                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	39                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0xc4:0xf DW_TAG_variable
	.long	.Ldebug_loc5                    // DW_AT_location
	.long	.Linfo_string14                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	42                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0xd3:0xf DW_TAG_variable
	.long	.Ldebug_loc6                    // DW_AT_location
	.long	.Linfo_string15                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	41                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0xe2:0xf DW_TAG_variable
	.long	.Ldebug_loc7                    // DW_AT_location
	.long	.Linfo_string16                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	40                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0xf1:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp13                         // DW_AT_low_pc
	.byte	8                               // Abbrev [8] 0xf8:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp17                         // DW_AT_low_pc
	.byte	8                               // Abbrev [8] 0xff:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp20                         // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	9                               // Abbrev [9] 0x107:0x5 DW_TAG_pointer_type
	.long	38                              // DW_AT_type
	.byte	10                              // Abbrev [10] 0x10c:0x5 DW_TAG_const_type
	.long	45                              // DW_AT_type
	.byte	10                              // Abbrev [10] 0x111:0x5 DW_TAG_const_type
	.long	38                              // DW_AT_type
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/mulosi4.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=153
.Linfo_string3:
	.asciz	"int"                           // string offset=174
.Linfo_string4:
	.asciz	"si_int"                        // string offset=178
.Linfo_string5:
	.asciz	"__mulosi4"                     // string offset=185
.Linfo_string6:
	.asciz	"a"                             // string offset=195
.Linfo_string7:
	.asciz	"b"                             // string offset=197
.Linfo_string8:
	.asciz	"overflow"                      // string offset=199
.Linfo_string9:
	.asciz	"result"                        // string offset=208
.Linfo_string10:
	.asciz	"MAX"                           // string offset=215
.Linfo_string11:
	.asciz	"MIN"                           // string offset=219
.Linfo_string12:
	.asciz	"N"                             // string offset=223
.Linfo_string13:
	.asciz	"sa"                            // string offset=225
.Linfo_string14:
	.asciz	"abs_b"                         // string offset=228
.Linfo_string15:
	.asciz	"sb"                            // string offset=234
.Linfo_string16:
	.asciz	"abs_a"                         // string offset=237
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
