	.text
	.file	"mulodi4.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/syslib/int_types.h"
	.section	.text.__mulodi4,"ax",@progbits
	.globl	__mulodi4                       // -- Begin function __mulodi4
	.type	__mulodi4,@function
__mulodi4:                              // @__mulodi4
.Lfunc_begin0:
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/mulodi4.c"
	.loc	2 23 0                          // uPIMulator_frontend/sdk/syslib/mulodi4.c:23:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __mulodi4:a <- $d0
	//DEBUG_VALUE: __mulodi4:b <- $d2
	//DEBUG_VALUE: __mulodi4:overflow <- $r4
	.cfi_def_cfa_offset -40
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 32, d22
	add r22, r22, 40
	.cfi_offset 15, -16
	.cfi_offset 14, -12
	sd r22, -16, d14
	.cfi_offset 17, -24
	.cfi_offset 16, -20
	sd r22, -24, d16
	.cfi_offset 19, -32
	.cfi_offset 18, -28
	sd r22, -32, d18
	.cfi_offset 21, -40
	.cfi_offset 20, -36
	sd r22, -40, d20
	move r18, r4
	movd d16, d2
	movd d14, d0
	move r1, 0
.Ltmp0:
	move r0, 2147483648
.Ltmp1:
	//DEBUG_VALUE: __mulodi4:result <- undef
	//DEBUG_VALUE: __mulodi4:MAX <- 9223372036854775807
	//DEBUG_VALUE: __mulodi4:MIN <- -9223372036854775808
	//DEBUG_VALUE: __mulodi4:N <- 64
	//DEBUG_VALUE: __mulodi4:overflow <- $r18
	//DEBUG_VALUE: __mulodi4:b <- $d16
	//DEBUG_VALUE: __mulodi4:a <- $d14
	.loc	2 27 15 prologue_end            // uPIMulator_frontend/sdk/syslib/mulodi4.c:27:15
	sw r18, 0, 0
	.loc	2 29 9                          // uPIMulator_frontend/sdk/syslib/mulodi4.c:29:9
	jneq r15, r1, .LBB0_2
.Ltmp2:
// %bb.11:
	jneq r14, r0, .LBB0_2
// %bb.12:
// %bb.1:
.Ltmp3:
	//DEBUG_VALUE: __mulodi4:overflow <- $r18
	//DEBUG_VALUE: __mulodi4:b <- $d16
	//DEBUG_VALUE: __mulodi4:a <- $d14
	//DEBUG_VALUE: __mulodi4:N <- 64
	//DEBUG_VALUE: __mulodi4:MIN <- -9223372036854775808
	//DEBUG_VALUE: __mulodi4:MAX <- 9223372036854775807
	.loc	2 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/mulodi4.c:0:9
	move.s d0, 2
.Ltmp4:
	.loc	2 30 20 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mulodi4.c:30:20
	sub zero, r17, r1
	subc zero, r16, r0, geu, .LBB0_9
	jump .LBB0_10
.Ltmp5:
.LBB0_2:
	//DEBUG_VALUE: __mulodi4:overflow <- $r18
	//DEBUG_VALUE: __mulodi4:b <- $d16
	//DEBUG_VALUE: __mulodi4:a <- $d14
	//DEBUG_VALUE: __mulodi4:N <- 64
	//DEBUG_VALUE: __mulodi4:MIN <- -9223372036854775808
	//DEBUG_VALUE: __mulodi4:MAX <- 9223372036854775807
	.loc	2 34 9                          // uPIMulator_frontend/sdk/syslib/mulodi4.c:34:9
	jneq r17, r1, .LBB0_4
.Ltmp6:
// %bb.13:
	jneq r16, r0, .LBB0_4
// %bb.14:
// %bb.3:
.Ltmp7:
	//DEBUG_VALUE: __mulodi4:overflow <- $r18
	//DEBUG_VALUE: __mulodi4:b <- $d16
	//DEBUG_VALUE: __mulodi4:a <- $d14
	//DEBUG_VALUE: __mulodi4:N <- 64
	//DEBUG_VALUE: __mulodi4:MIN <- -9223372036854775808
	//DEBUG_VALUE: __mulodi4:MAX <- 9223372036854775807
	.loc	2 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/mulodi4.c:0:9
	move.s d0, 2
.Ltmp8:
	.loc	2 35 20 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mulodi4.c:35:20
	sub zero, r15, r1
	subc zero, r14, r0, geu, .LBB0_9
	jump .LBB0_10
.Ltmp9:
.LBB0_4:
	//DEBUG_VALUE: __mulodi4:overflow <- $r18
	//DEBUG_VALUE: __mulodi4:b <- $d16
	//DEBUG_VALUE: __mulodi4:a <- $d14
	//DEBUG_VALUE: __mulodi4:N <- 64
	//DEBUG_VALUE: __mulodi4:MIN <- -9223372036854775808
	//DEBUG_VALUE: __mulodi4:MAX <- 9223372036854775807
	.loc	2 39 19                         // uPIMulator_frontend/sdk/syslib/mulodi4.c:39:19
	asr.s d0, r14, 31
.Ltmp10:
	//DEBUG_VALUE: __mulodi4:sa <- $d0
	.loc	2 40 23                         // uPIMulator_frontend/sdk/syslib/mulodi4.c:40:23
	xor r3, r1, r15
	xor r2, r0, r14
	.loc	2 40 29 is_stmt 0               // uPIMulator_frontend/sdk/syslib/mulodi4.c:40:29
	sub r21, r3, r1
	subc r20, r2, r0
.Ltmp11:
	//DEBUG_VALUE: __mulodi4:abs_a <- $d20
	.loc	2 0 29                          // uPIMulator_frontend/sdk/syslib/mulodi4.c:0:29
	move.s d6, 2
	.loc	2 41 19 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mulodi4.c:41:19
	asr.s d4, r16, 31
.Ltmp12:
	//DEBUG_VALUE: __mulodi4:abs_b <- undef
	//DEBUG_VALUE: __mulodi4:sb <- $d4
	.loc	2 43 19                         // uPIMulator_frontend/sdk/syslib/mulodi4.c:43:19
	sub zero, r21, r7
	subc zero, r20, r6, lts, .LBB0_10
.Ltmp13:
// %bb.5:
	//DEBUG_VALUE: __mulodi4:overflow <- $r18
	//DEBUG_VALUE: __mulodi4:abs_a <- $d20
	//DEBUG_VALUE: __mulodi4:b <- $d16
	//DEBUG_VALUE: __mulodi4:a <- $d14
	//DEBUG_VALUE: __mulodi4:sb <- $d4
	//DEBUG_VALUE: __mulodi4:sa <- $d0
	//DEBUG_VALUE: __mulodi4:N <- 64
	//DEBUG_VALUE: __mulodi4:MIN <- -9223372036854775808
	//DEBUG_VALUE: __mulodi4:MAX <- 9223372036854775807
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/mulodi4.c:0:0
	xor r3, r5, r17
	xor r2, r4, r16
	sub r3, r3, r5
	subc r2, r2, r4
.Ltmp14:
	//DEBUG_VALUE: __mulodi4:abs_b <- $d2
	.loc	2 43 19                         // uPIMulator_frontend/sdk/syslib/mulodi4.c:43:19
	sub zero, r3, r7
	subc zero, r2, r6, lts, .LBB0_10
.Ltmp15:
// %bb.6:
	//DEBUG_VALUE: __mulodi4:overflow <- $r18
	//DEBUG_VALUE: __mulodi4:abs_a <- $d20
	//DEBUG_VALUE: __mulodi4:b <- $d16
	//DEBUG_VALUE: __mulodi4:a <- $d14
	//DEBUG_VALUE: __mulodi4:sb <- $d4
	//DEBUG_VALUE: __mulodi4:abs_b <- $d2
	//DEBUG_VALUE: __mulodi4:sa <- $d0
	//DEBUG_VALUE: __mulodi4:N <- 64
	//DEBUG_VALUE: __mulodi4:MIN <- -9223372036854775808
	//DEBUG_VALUE: __mulodi4:MAX <- 9223372036854775807
	.loc	2 45 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/mulodi4.c:45:9
	jneq r1, r5, .LBB0_8
.Ltmp16:
// %bb.15:
	jneq r0, r4, .LBB0_8
// %bb.16:
// %bb.7:
.Ltmp17:
	//DEBUG_VALUE: __mulodi4:overflow <- $r18
	//DEBUG_VALUE: __mulodi4:abs_a <- $d20
	//DEBUG_VALUE: __mulodi4:b <- $d16
	//DEBUG_VALUE: __mulodi4:a <- $d14
	//DEBUG_VALUE: __mulodi4:sb <- $d4
	//DEBUG_VALUE: __mulodi4:abs_b <- $d2
	//DEBUG_VALUE: __mulodi4:sa <- $d0
	//DEBUG_VALUE: __mulodi4:N <- 64
	//DEBUG_VALUE: __mulodi4:MIN <- -9223372036854775808
	//DEBUG_VALUE: __mulodi4:MAX <- 9223372036854775807
	.loc	2 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/mulodi4.c:0:9
	move r1, 4294967295
.Ltmp18:
	move r0, 2147483647
.Ltmp19:
	.loc	2 46 25 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mulodi4.c:46:25
	call r23, __udivdi3
.Ltmp20:
	.loc	2 46 13 is_stmt 0               // uPIMulator_frontend/sdk/syslib/mulodi4.c:46:13
	sub zero, r21, r1
	subc zero, r20, r0, xgts, .LBB0_9
	jump .LBB0_10
.Ltmp21:
.LBB0_8:
	//DEBUG_VALUE: __mulodi4:overflow <- $r18
	//DEBUG_VALUE: __mulodi4:abs_a <- $d20
	//DEBUG_VALUE: __mulodi4:b <- $d16
	//DEBUG_VALUE: __mulodi4:a <- $d14
	//DEBUG_VALUE: __mulodi4:sb <- $d4
	//DEBUG_VALUE: __mulodi4:abs_b <- $d2
	//DEBUG_VALUE: __mulodi4:sa <- $d0
	//DEBUG_VALUE: __mulodi4:N <- 64
	//DEBUG_VALUE: __mulodi4:MIN <- -9223372036854775808
	//DEBUG_VALUE: __mulodi4:MAX <- 9223372036854775807
	.loc	2 0 13                          // uPIMulator_frontend/sdk/syslib/mulodi4.c:0:13
	move.s d0, 0
.Ltmp22:
	.loc	2 49 27 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mulodi4.c:49:27
	sub r3, r1, r3
.Ltmp23:
	subc r2, r0, r2
	move r1, 0
	move r0, 2147483648
	.loc	2 49 25 is_stmt 0               // uPIMulator_frontend/sdk/syslib/mulodi4.c:49:25
	call r23, __divdi3
.Ltmp24:
	.loc	2 49 13                         // uPIMulator_frontend/sdk/syslib/mulodi4.c:49:13
	sub zero, r21, r1
	subc zero, r20, r0, xles, .LBB0_10
.Ltmp25:
.LBB0_9:
	//DEBUG_VALUE: __mulodi4:overflow <- $r18
	//DEBUG_VALUE: __mulodi4:b <- $d16
	//DEBUG_VALUE: __mulodi4:a <- $d14
	//DEBUG_VALUE: __mulodi4:N <- 64
	//DEBUG_VALUE: __mulodi4:MIN <- -9223372036854775808
	//DEBUG_VALUE: __mulodi4:MAX <- 9223372036854775807
	.loc	2 0 0                           // uPIMulator_frontend/sdk/syslib/mulodi4.c:0:0
	sw r18, 0, 1
.Ltmp26:
.LBB0_10:
	//DEBUG_VALUE: __mulodi4:overflow <- $r18
	//DEBUG_VALUE: __mulodi4:b <- $d16
	//DEBUG_VALUE: __mulodi4:a <- $d14
	//DEBUG_VALUE: __mulodi4:N <- 64
	//DEBUG_VALUE: __mulodi4:MIN <- -9223372036854775808
	//DEBUG_VALUE: __mulodi4:MAX <- 9223372036854775807
	.loc	2 28 23 is_stmt 1               // uPIMulator_frontend/sdk/syslib/mulodi4.c:28:23
	movd d0, d16
	movd d2, d14
	call r23, __muldi3
.Ltmp27:
	//DEBUG_VALUE: __mulodi4:result <- $d0
	.loc	2 53 1                          // uPIMulator_frontend/sdk/syslib/mulodi4.c:53:1
	ld d20, r22, -40
	ld d18, r22, -32
.Ltmp28:
	ld d16, r22, -24
.Ltmp29:
	ld d14, r22, -16
.Ltmp30:
	ld d22, r22, -8
	jump r23
.Ltmp31:
.Lfunc_end0:
	.size	__mulodi4, .Lfunc_end0-__mulodi4
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__mulodi4
	.long	.Lfunc_begin0
	.byte	40
	.section	.text.__mulodi4,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp0-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp1-.Lfunc_begin0
	.long	.Ltmp2-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	95                              // sub-register DW_OP_reg15
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	94                              // sub-register DW_OP_reg14
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp6-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	95                              // sub-register DW_OP_reg15
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	94                              // sub-register DW_OP_reg14
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp7-.Lfunc_begin0
	.long	.Ltmp16-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	95                              // sub-register DW_OP_reg15
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	94                              // sub-register DW_OP_reg14
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp17-.Lfunc_begin0
	.long	.Ltmp30-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	95                              // sub-register DW_OP_reg15
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	94                              // sub-register DW_OP_reg14
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp1-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp1-.Lfunc_begin0
	.long	.Ltmp2-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	97                              // sub-register DW_OP_reg17
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	96                              // sub-register DW_OP_reg16
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp6-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	97                              // sub-register DW_OP_reg17
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	96                              // sub-register DW_OP_reg16
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp7-.Lfunc_begin0
	.long	.Ltmp16-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	97                              // sub-register DW_OP_reg17
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	96                              // sub-register DW_OP_reg16
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp17-.Lfunc_begin0
	.long	.Ltmp29-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	97                              // sub-register DW_OP_reg17
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	96                              // sub-register DW_OP_reg16
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp1-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp1-.Lfunc_begin0
	.long	.Ltmp2-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	98                              // DW_OP_reg18
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp6-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	98                              // DW_OP_reg18
	.long	.Ltmp7-.Lfunc_begin0
	.long	.Ltmp16-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	98                              // DW_OP_reg18
	.long	.Ltmp17-.Lfunc_begin0
	.long	.Ltmp28-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	98                              // DW_OP_reg18
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Ltmp27-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc4:
	.long	.Ltmp1-.Lfunc_begin0
	.long	.Ltmp2-.Lfunc_begin0
	.short	11                              // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	255                             // 9223372036854775807
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	127                             // 
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp6-.Lfunc_begin0
	.short	11                              // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	255                             // 9223372036854775807
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	127                             // 
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp7-.Lfunc_begin0
	.long	.Ltmp16-.Lfunc_begin0
	.short	11                              // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	255                             // 9223372036854775807
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	127                             // 
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp17-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	11                              // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	255                             // 9223372036854775807
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	127                             // 
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc5:
	.long	.Ltmp1-.Lfunc_begin0
	.long	.Ltmp2-.Lfunc_begin0
	.short	12                              // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	128                             // 9223372036854775808
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	1                               // 
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp6-.Lfunc_begin0
	.short	12                              // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	128                             // 9223372036854775808
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	1                               // 
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp7-.Lfunc_begin0
	.long	.Ltmp16-.Lfunc_begin0
	.short	12                              // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	128                             // 9223372036854775808
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	1                               // 
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp17-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	12                              // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	128                             // 9223372036854775808
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	1                               // 
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc6:
	.long	.Ltmp1-.Lfunc_begin0
	.long	.Ltmp2-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	64                              // 64
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp6-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	64                              // 64
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp7-.Lfunc_begin0
	.long	.Ltmp16-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	64                              // 64
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp17-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	64                              // 64
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc7:
	.long	.Ltmp10-.Lfunc_begin0
	.long	.Ltmp16-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp17-.Lfunc_begin0
	.long	.Ltmp18-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp21-.Lfunc_begin0
	.long	.Ltmp22-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc8:
	.long	.Ltmp11-.Lfunc_begin0
	.long	.Ltmp16-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	101                             // sub-register DW_OP_reg21
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	100                             // sub-register DW_OP_reg20
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp17-.Lfunc_begin0
	.long	.Ltmp25-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	101                             // sub-register DW_OP_reg21
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	100                             // sub-register DW_OP_reg20
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc9:
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Ltmp16-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp17-.Lfunc_begin0
	.long	.Ltmp23-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	83                              // sub-register DW_OP_reg3
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	82                              // sub-register DW_OP_reg2
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc10:
	.long	.Ltmp12-.Lfunc_begin0
	.long	.Ltmp16-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp17-.Lfunc_begin0
	.long	.Ltmp25-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	85                              // sub-register DW_OP_reg5
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	84                              // sub-register DW_OP_reg4
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.ascii	"\211\202\001"                  // DW_TAG_GNU_call_site
	.byte	0                               // DW_CHILDREN_no
	.ascii	"\223B"                         // DW_AT_GNU_call_site_target
	.byte	24                              // DW_FORM_exprloc
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x114 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	3                               // Abbrev [3] 0x2d:0xb DW_TAG_typedef
	.long	56                              // DW_AT_type
	.long	.Linfo_string5                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	30                              // DW_AT_decl_line
	.byte	2                               // Abbrev [2] 0x38:0x7 DW_TAG_base_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x3f:0xd0 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string6                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	45                              // DW_AT_type
                                        // DW_AT_external
	.byte	5                               // Abbrev [5] 0x54:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string7                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	5                               // Abbrev [5] 0x63:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	5                               // Abbrev [5] 0x72:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string9                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
	.long	271                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x81:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string10                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	28                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0x90:0xf DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	.Linfo_string11                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	26                              // DW_AT_decl_line
	.long	276                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x9f:0xf DW_TAG_variable
	.long	.Ldebug_loc5                    // DW_AT_location
	.long	.Linfo_string12                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	25                              // DW_AT_decl_line
	.long	276                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xae:0xf DW_TAG_variable
	.long	.Ldebug_loc6                    // DW_AT_location
	.long	.Linfo_string13                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	24                              // DW_AT_decl_line
	.long	281                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xbd:0xf DW_TAG_variable
	.long	.Ldebug_loc7                    // DW_AT_location
	.long	.Linfo_string14                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	39                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0xcc:0xf DW_TAG_variable
	.long	.Ldebug_loc8                    // DW_AT_location
	.long	.Linfo_string15                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	40                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0xdb:0xf DW_TAG_variable
	.long	.Ldebug_loc9                    // DW_AT_location
	.long	.Linfo_string16                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	42                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0xea:0xf DW_TAG_variable
	.long	.Ldebug_loc10                   // DW_AT_location
	.long	.Linfo_string17                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	41                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	7                               // Abbrev [7] 0xf9:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp20                         // DW_AT_low_pc
	.byte	7                               // Abbrev [7] 0x100:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp24                         // DW_AT_low_pc
	.byte	7                               // Abbrev [7] 0x107:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp27                         // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	8                               // Abbrev [8] 0x10f:0x5 DW_TAG_pointer_type
	.long	38                              // DW_AT_type
	.byte	9                               // Abbrev [9] 0x114:0x5 DW_TAG_const_type
	.long	45                              // DW_AT_type
	.byte	9                               // Abbrev [9] 0x119:0x5 DW_TAG_const_type
	.long	38                              // DW_AT_type
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/mulodi4.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=153
.Linfo_string3:
	.asciz	"int"                           // string offset=174
.Linfo_string4:
	.asciz	"long long int"                 // string offset=178
.Linfo_string5:
	.asciz	"di_int"                        // string offset=192
.Linfo_string6:
	.asciz	"__mulodi4"                     // string offset=199
.Linfo_string7:
	.asciz	"a"                             // string offset=209
.Linfo_string8:
	.asciz	"b"                             // string offset=211
.Linfo_string9:
	.asciz	"overflow"                      // string offset=213
.Linfo_string10:
	.asciz	"result"                        // string offset=222
.Linfo_string11:
	.asciz	"MAX"                           // string offset=229
.Linfo_string12:
	.asciz	"MIN"                           // string offset=233
.Linfo_string13:
	.asciz	"N"                             // string offset=237
.Linfo_string14:
	.asciz	"sa"                            // string offset=239
.Linfo_string15:
	.asciz	"abs_a"                         // string offset=242
.Linfo_string16:
	.asciz	"abs_b"                         // string offset=248
.Linfo_string17:
	.asciz	"sb"                            // string offset=254
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
