	.text
	.file	"mulsf3.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/stdint.h"
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/fp_lib.h"
	.section	.text.__mulsf3,"ax",@progbits
	.globl	__mulsf3                        // -- Begin function __mulsf3
	.type	__mulsf3,@function
__mulsf3:                               // @__mulsf3
.Lfunc_begin0:
	.file	3 "/root" "uPIMulator_frontend/sdk/syslib/mulsf3.c"
	.loc	3 20 0                          // uPIMulator_frontend/sdk/syslib/mulsf3.c:20:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __mulsf3:a <- $r0
	//DEBUG_VALUE: __mulsf3:a <- $r0
	//DEBUG_VALUE: __mulsf3:b <- $r1
	//DEBUG_VALUE: __mulsf3:b <- $r1
	//DEBUG_VALUE: __mulXf3__:a <- $r0
	//DEBUG_VALUE: __mulXf3__:a <- $r0
	//DEBUG_VALUE: __mulXf3__:b <- $r1
	//DEBUG_VALUE: __mulXf3__:b <- $r1
	//DEBUG_VALUE: toRep:x <- $r0
	//DEBUG_VALUE: toRep:x <- $r0
	.cfi_def_cfa_offset -24
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 16, d22
	add r22, r22, 24
	.cfi_offset 15, -16
	.cfi_offset 14, -12
.Ltmp0:
	sd r22, -16, d14
	.cfi_offset 17, -24
	.cfi_offset 16, -20
	sd r22, -24, d16
	//DEBUG_VALUE: toRep:rep <- $r0
	//DEBUG_VALUE: toRep:rep <- $r0
.Ltmp1:
	.file	4 "/root" "uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc"
	.loc	4 18 45 prologue_end            // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:18:45
	lsr r2, r0, 23
	.loc	4 18 64 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:18:64
	and r15, r2, 255
.Ltmp2:
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	.loc	4 19 45 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:19:45
	lsr r2, r1, 23
	.loc	4 19 64 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:19:64
	and r16, r2, 255
.Ltmp3:
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	.loc	4 20 41 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:20:41
	xor r2, r1, r0
	.loc	4 20 53 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:20:53
	and r14, r2, -2147483648
.Ltmp4:
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	.loc	4 22 35 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:22:35
	and r2, r0, 8388607
.Ltmp5:
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: __mulXf3__:aSignificand <- $r2
	.loc	4 23 35                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:23:35
	and r3, r1, 8388607
.Ltmp6:
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	//DEBUG_VALUE: __mulXf3__:bSignificand <- $r3
	.loc	4 27 18                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:27:18
	add r4, r15, -1
	.loc	4 27 40 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:27:40
	jgtu r4, 253, .LBB0_7
.Ltmp7:
// %bb.1:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: __mulXf3__:bSignificand <- $r3
	//DEBUG_VALUE: __mulXf3__:aSignificand <- $r2
	//DEBUG_VALUE: __mulXf3__:b <- $r1
	//DEBUG_VALUE: __mulsf3:b <- $r1
	//DEBUG_VALUE: __mulXf3__:a <- $r0
	//DEBUG_VALUE: __mulsf3:a <- $r0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 0 40                          // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:40
	move r17, 0
	add r4, r16, -1
	.loc	4 27 40                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:27:40
	jgeu r4, 254, .LBB0_7
.Ltmp8:
.LBB0_2:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: __mulXf3__:aSignificand <- $r2
	//DEBUG_VALUE: __mulXf3__:scale <- $r17
	.loc	4 66 18 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:66:18
	or r0, r2, 8388608
.Ltmp9:
	//DEBUG_VALUE: __mulXf3__:bSignificand <- [DW_OP_constu 8388608, DW_OP_or, DW_OP_stack_value] $r3
	//DEBUG_VALUE: __mulXf3__:aSignificand <- $r0
	.loc	4 75 45                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:75:45
	lsl r1, r3, 8
	or r1, r1, -2147483648
.Ltmp10:
	//DEBUG_VALUE: wideMultiply:lo <- undef
	//DEBUG_VALUE: wideMultiply:hi <- undef
	//DEBUG_VALUE: wideMultiply:a <- $r0
	//DEBUG_VALUE: wideMultiply:b <- $r1
	.loc	2 59 30                         // uPIMulator_frontend/sdk/syslib/fp_lib.h:59:30
	move.u d2, r0
.Ltmp11:
	.loc	2 59 44 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_lib.h:59:44
	move.u d0, r1
.Ltmp12:
	.loc	2 59 42                         // uPIMulator_frontend/sdk/syslib/fp_lib.h:59:42
	call r23, __muldi3
.Ltmp13:
	//DEBUG_VALUE: wideMultiply:product <- $d0
	.loc	4 78 37 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:78:37
	add r2, r15, r16
	.loc	4 78 49 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:78:49
	add r2, r2, r17
	.loc	4 78 64                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:78:64
	add r2, r2, -127
.Ltmp14:
	//DEBUG_VALUE: __mulXf3__:productHi <- $r0
	//DEBUG_VALUE: __mulXf3__:productExponent <- $r2
	.loc	4 81 19 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:81:19
	and r3, r0, 8388608
.Ltmp15:
	.loc	4 81 9 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:81:9
	jneq r3, 0, .LBB0_9
.Ltmp16:
// %bb.3:
	//DEBUG_VALUE: __mulXf3__:scale <- $r17
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: __mulXf3__:productExponent <- $r2
	//DEBUG_VALUE: __mulXf3__:productHi <- $r0
	//DEBUG_VALUE: wideLeftShift:hi <- undef
	//DEBUG_VALUE: wideLeftShift:lo <- undef
	//DEBUG_VALUE: wideLeftShift:count <- 1
	.loc	2 259 24 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_lib.h:259:24
	lsr r3, r1, 31
	lsl_add r0, r3, r0, 1
.Ltmp17:
	.loc	2 260 15                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:260:15
	lsl r1, r1, 1
.Ltmp18:
	//DEBUG_VALUE: __mulXf3__:productExponent <- $r2
	.loc	4 85 9                          // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:85:9
	jges r2, 255, .LBB0_15
	jump .LBB0_4
.Ltmp19:
.LBB0_7:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: __mulXf3__:bSignificand <- $r3
	//DEBUG_VALUE: __mulXf3__:aSignificand <- $r2
	//DEBUG_VALUE: __mulXf3__:b <- $r1
	//DEBUG_VALUE: __mulsf3:b <- $r1
	//DEBUG_VALUE: __mulXf3__:a <- $r0
	//DEBUG_VALUE: __mulsf3:a <- $r0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 29 37                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:29:37
	and r4, r0, 2147483647
.Ltmp20:
	//DEBUG_VALUE: bAbs <- undef
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: aAbs <- $r4
	.loc	4 0 37 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:37
	move r5, 2139095041
.Ltmp21:
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	.loc	4 33 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:33:13
	jltu r4, r5, .LBB0_11
.Ltmp22:
// %bb.8:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: aAbs <- $r4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- $r3
	//DEBUG_VALUE: __mulXf3__:aSignificand <- $r2
	//DEBUG_VALUE: __mulXf3__:b <- $r1
	//DEBUG_VALUE: __mulsf3:b <- $r1
	//DEBUG_VALUE: __mulXf3__:a <- $r0
	//DEBUG_VALUE: __mulsf3:a <- $r0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 33 52 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:33:52
	or r14, r0, 4194304
.Ltmp23:
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $r14
	.loc	4 0 52                          // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:52
	jump .LBB0_30
.Ltmp24:
.LBB0_9:
	//DEBUG_VALUE: __mulXf3__:scale <- $r17
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: __mulXf3__:productExponent <- $r2
	//DEBUG_VALUE: __mulXf3__:productHi <- $r0
	.loc	4 81 49 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:81:49
	add r2, r2, 1
.Ltmp25:
	//DEBUG_VALUE: __mulXf3__:productExponent <- $r2
	//DEBUG_VALUE: __mulXf3__:productExponent <- $r2
	.loc	4 85 9                          // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:85:9
	jges r2, 255, .LBB0_15
.Ltmp26:
.LBB0_4:
	//DEBUG_VALUE: __mulXf3__:scale <- $r17
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: __mulXf3__:productExponent <- $r2
	.loc	4 87 9                          // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:87:9
	jles r2, 0, .LBB0_16
.Ltmp27:
// %bb.5:
	//DEBUG_VALUE: __mulXf3__:scale <- $r17
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: __mulXf3__:productExponent <- $r2
	//DEBUG_VALUE: __mulXf3__:productHi <- $r0
	.loc	4 103 19                        // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:103:19
	and r3, r0, 8388607
	.loc	4 104 19                        // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:104:19
	lsl_add r2, r3, r2, 23
.Ltmp28:
	//DEBUG_VALUE: __mulXf3__:productHi <- $r2
	//DEBUG_VALUE: __mulXf3__:productHi <- $r2
	.loc	4 0 19 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:19
	move r3, -2147483647
.Ltmp29:
	//DEBUG_VALUE: __mulXf3__:productLo <- $r1
	//DEBUG_VALUE: __mulXf3__:productHi <- undef
	.loc	4 108 15 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:108:15
	or r14, r2, r14
.Ltmp30:
	.loc	4 113 9                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:113:9
	jltu r1, r3, .LBB0_18
.Ltmp31:
.LBB0_6:
	//DEBUG_VALUE: __mulXf3__:scale <- $r17
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productLo <- $r1
	//DEBUG_VALUE: __mulXf3__:productLo <- undef
	//DEBUG_VALUE: __mulXf3__:productHi <- $r14
	//DEBUG_VALUE: fromRep:x <- $r14
	//DEBUG_VALUE: fromRep:rep <- undef
	.loc	4 113 39 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:113:39
	add r14, r14, 1, true, .LBB0_30
.Ltmp32:
.LBB0_11:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: aAbs <- $r4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- $r3
	//DEBUG_VALUE: __mulXf3__:aSignificand <- $r2
	//DEBUG_VALUE: __mulXf3__:b <- $r1
	//DEBUG_VALUE: __mulsf3:b <- $r1
	//DEBUG_VALUE: __mulXf3__:a <- $r0
	//DEBUG_VALUE: __mulsf3:a <- $r0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 0 0                           // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:0
	and r0, r1, 2147483647
.Ltmp33:
	//DEBUG_VALUE: bAbs <- $r0
	.loc	4 35 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:35:13
	jltu r0, r5, .LBB0_13
.Ltmp34:
// %bb.12:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: aAbs <- $r4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- $r3
	//DEBUG_VALUE: __mulXf3__:aSignificand <- $r2
	//DEBUG_VALUE: __mulXf3__:b <- $r1
	//DEBUG_VALUE: __mulsf3:b <- $r1
	//DEBUG_VALUE: bAbs <- $r0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 35 52 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:35:52
	or r14, r1, 4194304
.Ltmp35:
	//DEBUG_VALUE: toRep:rep <- undef
	//DEBUG_VALUE: toRep:x <- undef
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $r14
	.loc	4 0 52                          // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:52
	jump .LBB0_30
.Ltmp36:
.LBB0_13:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: aAbs <- $r4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- $r3
	//DEBUG_VALUE: __mulXf3__:aSignificand <- $r2
	//DEBUG_VALUE: __mulXf3__:b <- $r1
	//DEBUG_VALUE: __mulsf3:b <- $r1
	//DEBUG_VALUE: bAbs <- $r0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	move r1, 2139095040
.Ltmp37:
	.loc	4 37 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:37:13
	jneq r4, r1, .LBB0_20
.Ltmp38:
// %bb.14:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: aAbs <- $r4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- $r3
	//DEBUG_VALUE: __mulXf3__:aSignificand <- $r2
	//DEBUG_VALUE: bAbs <- $r0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 39 17                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:39:17
	jeq r0, 0, .LBB0_29
.Ltmp39:
.LBB0_15:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	.loc	4 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:0
	or r14, r14, 2139095040
.Ltmp40:
	//DEBUG_VALUE: fromRep:rep <- undef
	//DEBUG_VALUE: fromRep:x <- $r14
.LBB0_30:
	.loc	3 21 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/mulsf3.c:21:5
	move r0, r14
	ld d16, r22, -24
	ld d14, r22, -16
	ld d22, r22, -8
	jump r23
.LBB0_16:
.Ltmp41:
	//DEBUG_VALUE: __mulXf3__:scale <- $r17
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: __mulXf3__:productExponent <- $r2
	.loc	4 94 45                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:94:45
	sub r3, 1, r2
.Ltmp42:
	//DEBUG_VALUE: shift <- $r3
	.loc	4 95 13                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:95:13
	jgeu r3, 32, .LBB0_30
.Ltmp43:
// %bb.17:
	//DEBUG_VALUE: __mulXf3__:scale <- $r17
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: shift <- $r3
	//DEBUG_VALUE: __mulXf3__:productExponent <- $r2
	//DEBUG_VALUE: wideRightShiftWithSticky:hi <- undef
	//DEBUG_VALUE: wideRightShiftWithSticky:lo <- undef
	//DEBUG_VALUE: wideRightShiftWithSticky:count <- $r3
	.loc	2 267 47                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:267:47
	add r2, r2, 31
.Ltmp44:
	.loc	2 267 33 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_lib.h:267:33
	lsl r4, r1, r2
	move r5, 0
	.loc	2 267 29                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:267:29
	sub r4, r4, r5, neq
.Ltmp45:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] $r4
	.loc	2 268 19 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_lib.h:268:19
	lsl r2, r0, r2
	.loc	2 268 48 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_lib.h:268:48
	lsr r5, r1, r3
	.loc	2 268 42                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:268:42
	or r2, r2, r5
	.loc	2 268 57                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:268:57
	or r1, r2, r4
	.loc	2 269 19 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_lib.h:269:19
	lsr r2, r0, r3
.Ltmp46:
	//DEBUG_VALUE: __mulXf3__:productHi <- $r2
	.loc	2 0 19 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_lib.h:0:19
	move r3, -2147483647
.Ltmp47:
	//DEBUG_VALUE: __mulXf3__:productLo <- $r1
	//DEBUG_VALUE: __mulXf3__:productHi <- undef
	.loc	4 108 15 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:108:15
	or r14, r2, r14
.Ltmp48:
	.loc	4 113 9                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:113:9
	jgeu r1, r3, .LBB0_6
.Ltmp49:
.LBB0_18:
	//DEBUG_VALUE: __mulXf3__:scale <- $r17
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productLo <- $r1
	//DEBUG_VALUE: __mulXf3__:productLo <- $r1
	.loc	4 0 9 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:9
	move r3, -2147483648
	.loc	4 114 9 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:114:9
	jneq r1, r3, .LBB0_30
.Ltmp50:
// %bb.19:
	//DEBUG_VALUE: __mulXf3__:scale <- $r17
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productLo <- $r1
	//DEBUG_VALUE: __mulXf3__:productHi <- undef
	.loc	4 114 54 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:114:54
	and r0, r2, 1
.Ltmp51:
	//DEBUG_VALUE: __mulXf3__:productHi <- $r14
	//DEBUG_VALUE: fromRep:x <- $r14
	//DEBUG_VALUE: fromRep:rep <- undef
	.loc	4 114 41                        // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:114:41
	add r14, r14, r0, true, .LBB0_30
.Ltmp52:
.LBB0_20:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: aAbs <- $r4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- $r3
	//DEBUG_VALUE: __mulXf3__:aSignificand <- $r2
	//DEBUG_VALUE: bAbs <- $r0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 44 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:44:13
	jneq r0, r1, .LBB0_23
.Ltmp53:
// %bb.21:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: aAbs <- $r4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- $r3
	//DEBUG_VALUE: __mulXf3__:aSignificand <- $r2
	//DEBUG_VALUE: bAbs <- $r0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 46 17                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:46:17
	jneq r4, 0, .LBB0_15
.Ltmp54:
.LBB0_29:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: aAbs <- $r4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- $r3
	//DEBUG_VALUE: __mulXf3__:aSignificand <- $r2
	//DEBUG_VALUE: bAbs <- $r0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 0 17 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:17
	move r14, 2143289344
.Ltmp55:
	jump .LBB0_30
.Ltmp56:
.LBB0_23:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: aAbs <- $r4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- $r3
	//DEBUG_VALUE: __mulXf3__:aSignificand <- $r2
	//DEBUG_VALUE: bAbs <- $r0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 52 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:52:13
	jeq r4, 0, .LBB0_30
.Ltmp57:
// %bb.24:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: aAbs <- $r4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- $r3
	//DEBUG_VALUE: __mulXf3__:aSignificand <- $r2
	//DEBUG_VALUE: bAbs <- $r0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 54 13                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:54:13
	jeq r0, 0, .LBB0_30
.Ltmp58:
// %bb.25:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: aAbs <- $r4
	//DEBUG_VALUE: __mulXf3__:bSignificand <- $r3
	//DEBUG_VALUE: __mulXf3__:aSignificand <- $r2
	//DEBUG_VALUE: bAbs <- $r0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 59 13                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:59:13
	clz r5, r2
	add r1, r5, -8
	lsr r4, r4, 23, nz, .LBB0_31
.Ltmp59:
// %bb.26:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: __mulXf3__:bSignificand <- $r3
	//DEBUG_VALUE: __mulXf3__:aSignificand <- $r2
	//DEBUG_VALUE: bAbs <- $r0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	sub r17, 9, r5
	jneq r4, 0, .LBB0_32
.Ltmp60:
.LBB0_27:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: __mulXf3__:bSignificand <- $r3
	//DEBUG_VALUE: __mulXf3__:aSignificand <- $r2
	//DEBUG_VALUE: bAbs <- $r0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:0
	lsl r2, r2, r1
.Ltmp61:
	//DEBUG_VALUE: __mulXf3__:scale <- $r17
	.loc	4 60 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:60:13
	lsr r0, r0, 23
.Ltmp62:
	jneq r0, 0, .LBB0_2
	jump .LBB0_33
.Ltmp63:
.LBB0_31:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: __mulXf3__:bSignificand <- $r3
	//DEBUG_VALUE: __mulXf3__:aSignificand <- $r2
	//DEBUG_VALUE: bAbs <- $r0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:13
	move r1, 0
	.loc	4 59 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:59:13
	sub r17, 9, r5
	jeq r4, 0, .LBB0_27
.Ltmp64:
.LBB0_32:
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: __mulXf3__:bSignificand <- $r3
	//DEBUG_VALUE: __mulXf3__:aSignificand <- $r2
	//DEBUG_VALUE: bAbs <- $r0
	//DEBUG_VALUE: __mulXf3__:scale <- 0
	.loc	4 0 13 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:0:13
	move r17, 0
	lsl r2, r2, r1
.Ltmp65:
	//DEBUG_VALUE: __mulXf3__:scale <- $r17
	.loc	4 60 13 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:60:13
	lsr r0, r0, 23, nz, .LBB0_2
.Ltmp66:
.LBB0_33:
	//DEBUG_VALUE: __mulXf3__:scale <- $r17
	//DEBUG_VALUE: __mulXf3__:bExponent <- $r16
	//DEBUG_VALUE: __mulXf3__:aExponent <- $r15
	//DEBUG_VALUE: __mulXf3__:productSign <- $r14
	//DEBUG_VALUE: __mulXf3__:bSignificand <- $r3
	//DEBUG_VALUE: normalize:significand <- undef
	//DEBUG_VALUE: rep_clz:a <- $r3
	.loc	2 52 12                         // uPIMulator_frontend/sdk/syslib/fp_lib.h:52:12
	clz r0, r3
.Ltmp67:
	//DEBUG_VALUE: rep_clz:a <- 8388608
	.loc	2 251 45                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:251:45
	add r1, r0, -8
.Ltmp68:
	//DEBUG_VALUE: normalize:shift <- $r1
	.loc	2 252 18                        // uPIMulator_frontend/sdk/syslib/fp_lib.h:252:18
	lsl r3, r3, r1
.Ltmp69:
	.loc	4 60 39                         // uPIMulator_frontend/sdk/syslib/fp_mul_impl.inc:60:39
	sub r0, r17, r0
	//DEBUG_VALUE: __mulXf3__:scale <- $r17
	add r17, r0, 9, true, .LBB0_2
.Ltmp70:
.Lfunc_end0:
	.size	__mulsf3, .Lfunc_end0-__mulsf3
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__mulsf3
	.long	.Lfunc_begin0
	.byte	24
	.section	.text.__mulsf3,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp8-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp19-.Lfunc_begin0
	.long	.Ltmp24-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp32-.Lfunc_begin0
	.long	.Ltmp33-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp8-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp19-.Lfunc_begin0
	.long	.Ltmp24-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp32-.Lfunc_begin0
	.long	.Ltmp37-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp8-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp19-.Lfunc_begin0
	.long	.Ltmp24-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp32-.Lfunc_begin0
	.long	.Ltmp33-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp8-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp19-.Lfunc_begin0
	.long	.Ltmp24-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp32-.Lfunc_begin0
	.long	.Ltmp37-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc4:
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp40-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	.Ltmp41-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	95                              // DW_OP_reg15
	.long	0
	.long	0
.Ldebug_loc5:
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp40-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	96                              // DW_OP_reg16
	.long	.Ltmp41-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	96                              // DW_OP_reg16
	.long	0
	.long	0
.Ldebug_loc6:
	.long	.Ltmp4-.Lfunc_begin0
	.long	.Ltmp23-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	.Ltmp24-.Lfunc_begin0
	.long	.Ltmp30-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	.Ltmp32-.Lfunc_begin0
	.long	.Ltmp35-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	.Ltmp36-.Lfunc_begin0
	.long	.Ltmp40-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	.Ltmp41-.Lfunc_begin0
	.long	.Ltmp48-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	.Ltmp52-.Lfunc_begin0
	.long	.Ltmp55-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	.Ltmp56-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	0
	.long	0
.Ldebug_loc7:
	.long	.Ltmp5-.Lfunc_begin0
	.long	.Ltmp9-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp9-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp19-.Lfunc_begin0
	.long	.Ltmp24-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp32-.Lfunc_begin0
	.long	.Ltmp39-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp52-.Lfunc_begin0
	.long	.Ltmp61-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp63-.Lfunc_begin0
	.long	.Ltmp65-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc8:
	.long	.Ltmp6-.Lfunc_begin0
	.long	.Ltmp8-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp8-.Lfunc_begin0
	.long	.Ltmp19-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	97                              // DW_OP_reg17
	.long	.Ltmp19-.Lfunc_begin0
	.long	.Ltmp24-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp24-.Lfunc_begin0
	.long	.Ltmp32-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	97                              // DW_OP_reg17
	.long	.Ltmp32-.Lfunc_begin0
	.long	.Ltmp39-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp41-.Lfunc_begin0
	.long	.Ltmp52-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	97                              // DW_OP_reg17
	.long	.Ltmp52-.Lfunc_begin0
	.long	.Ltmp61-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp61-.Lfunc_begin0
	.long	.Ltmp63-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	97                              // DW_OP_reg17
	.long	.Ltmp63-.Lfunc_begin0
	.long	.Ltmp65-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	17                              // DW_OP_consts
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp65-.Lfunc_begin0
	.long	.Ltmp70-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	97                              // DW_OP_reg17
	.long	0
	.long	0
.Ldebug_loc9:
	.long	.Ltmp6-.Lfunc_begin0
	.long	.Ltmp8-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp9-.Lfunc_begin0
	.long	.Ltmp11-.Lfunc_begin0
	.short	9                               // Loc expr size
	.byte	115                             // DW_OP_breg3
	.byte	0                               // 0
	.byte	16                              // DW_OP_constu
	.byte	128                             // 8388608
	.byte	128                             // 
	.byte	128                             // 
	.byte	4                               // 
	.byte	33                              // DW_OP_or
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp19-.Lfunc_begin0
	.long	.Ltmp24-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp32-.Lfunc_begin0
	.long	.Ltmp39-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp52-.Lfunc_begin0
	.long	.Ltmp69-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc10:
	.long	.Ltmp10-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc11:
	.long	.Ltmp10-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc12:
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Ltmp17-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp24-.Lfunc_begin0
	.long	.Ltmp26-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp27-.Lfunc_begin0
	.long	.Ltmp28-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp28-.Lfunc_begin0
	.long	.Ltmp29-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp31-.Lfunc_begin0
	.long	.Ltmp32-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	.Ltmp46-.Lfunc_begin0
	.long	.Ltmp47-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp51-.Lfunc_begin0
	.long	.Ltmp52-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	0
	.long	0
.Ldebug_loc13:
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Ltmp19-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp24-.Lfunc_begin0
	.long	.Ltmp28-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp41-.Lfunc_begin0
	.long	.Ltmp44-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc14:
	.long	.Ltmp33-.Lfunc_begin0
	.long	.Ltmp39-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp52-.Lfunc_begin0
	.long	.Ltmp62-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp63-.Lfunc_begin0
	.long	.Ltmp66-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc15:
	.long	.Ltmp20-.Lfunc_begin0
	.long	.Ltmp24-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp32-.Lfunc_begin0
	.long	.Ltmp39-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp52-.Lfunc_begin0
	.long	.Ltmp59-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	0
	.long	0
.Ldebug_loc16:
	.long	.Ltmp29-.Lfunc_begin0
	.long	.Ltmp31-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	.Ltmp47-.Lfunc_begin0
	.long	.Ltmp52-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc17:
	.long	.Ltmp42-.Lfunc_begin0
	.long	.Ltmp47-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc18:
	.long	.Ltmp45-.Lfunc_begin0
	.long	.Ltmp49-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	116                             // DW_OP_breg4
	.byte	0                               // 0
	.byte	16                              // DW_OP_constu
	.byte	1                               // 1
	.byte	26                              // DW_OP_and
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc19:
	.long	.Ltmp68-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	23                              // DW_TAG_union_type
	.byte	1                               // DW_CHILDREN_yes
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	13                              // DW_TAG_member
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	56                              // DW_AT_data_member_location
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	11                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	12                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	13                              // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	14                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	5                               // DW_FORM_data2
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	15                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	5                               // DW_FORM_data2
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	16                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	5                               // DW_FORM_data2
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	17                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	18                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	19                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	1                               // DW_CHILDREN_yes
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	20                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	21                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	22                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	1                               // DW_CHILDREN_yes
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	23                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	24                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	25                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	26                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	28                              // DW_AT_const_value
	.byte	13                              // DW_FORM_sdata
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	27                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	28                              // Abbreviation Code
	.ascii	"\211\202\001"                  // DW_TAG_GNU_call_site
	.byte	0                               // DW_CHILDREN_no
	.ascii	"\223B"                         // DW_AT_GNU_call_site_target
	.byte	24                              // DW_FORM_exprloc
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x424 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	3                               // Abbrev [3] 0x2d:0xb DW_TAG_typedef
	.long	56                              // DW_AT_type
	.long	.Linfo_string5                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	43                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x38:0xb DW_TAG_typedef
	.long	38                              // DW_AT_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	48                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x43:0xb DW_TAG_typedef
	.long	78                              // DW_AT_type
	.long	.Linfo_string7                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	53                              // DW_AT_decl_line
	.byte	2                               // Abbrev [2] 0x4e:0x7 DW_TAG_base_type
	.long	.Linfo_string6                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x55:0x23 DW_TAG_subprogram
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	229                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	45                              // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0x61:0xb DW_TAG_formal_parameter
	.long	.Linfo_string9                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	229                             // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x6c:0xb DW_TAG_variable
	.long	.Linfo_string12                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	234                             // DW_AT_decl_line
	.long	138                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	3                               // Abbrev [3] 0x78:0xb DW_TAG_typedef
	.long	131                             // DW_AT_type
	.long	.Linfo_string11                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	45                              // DW_AT_decl_line
	.byte	2                               // Abbrev [2] 0x83:0x7 DW_TAG_base_type
	.long	.Linfo_string10                 // DW_AT_name
	.byte	4                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	7                               // Abbrev [7] 0x8a:0x5 DW_TAG_const_type
	.long	144                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x8f:0x1f DW_TAG_subprogram
	.byte	9                               // Abbrev [9] 0x90:0x1d DW_TAG_union_type
	.byte	4                               // DW_AT_byte_size
	.byte	2                               // DW_AT_decl_file
	.byte	231                             // DW_AT_decl_line
	.byte	10                              // Abbrev [10] 0x94:0xc DW_TAG_member
	.long	.Linfo_string13                 // DW_AT_name
	.long	120                             // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	232                             // DW_AT_decl_line
	.byte	0                               // DW_AT_data_member_location
	.byte	10                              // Abbrev [10] 0xa0:0xc DW_TAG_member
	.long	.Linfo_string14                 // DW_AT_name
	.long	45                              // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	233                             // DW_AT_decl_line
	.byte	0                               // DW_AT_data_member_location
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	4                               // Abbrev [4] 0xae:0xab DW_TAG_subprogram
	.long	.Linfo_string15                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	17                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	120                             // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0xba:0xb DW_TAG_formal_parameter
	.long	.Linfo_string16                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	17                              // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0xc5:0xb DW_TAG_formal_parameter
	.long	.Linfo_string17                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	17                              // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xd0:0xb DW_TAG_variable
	.long	.Linfo_string18                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	18                              // DW_AT_decl_line
	.long	345                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xdb:0xb DW_TAG_variable
	.long	.Linfo_string19                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	19                              // DW_AT_decl_line
	.long	345                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xe6:0xb DW_TAG_variable
	.long	.Linfo_string20                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	20                              // DW_AT_decl_line
	.long	350                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0xf1:0xb DW_TAG_variable
	.long	.Linfo_string21                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0xfc:0xb DW_TAG_variable
	.long	.Linfo_string22                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	24                              // DW_AT_decl_line
	.long	355                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x107:0xb DW_TAG_variable
	.long	.Linfo_string24                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	23                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0x112:0xb DW_TAG_variable
	.long	.Linfo_string25                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	74                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0x11d:0xb DW_TAG_variable
	.long	.Linfo_string26                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	78                              // DW_AT_decl_line
	.long	355                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x128:0xb DW_TAG_variable
	.long	.Linfo_string27                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	74                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	11                              // Abbrev [11] 0x133:0x18 DW_TAG_lexical_block
	.byte	6                               // Abbrev [6] 0x134:0xb DW_TAG_variable
	.long	.Linfo_string28                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	30                              // DW_AT_decl_line
	.long	350                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x13f:0xb DW_TAG_variable
	.long	.Linfo_string29                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	29                              // DW_AT_decl_line
	.long	350                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	11                              // Abbrev [11] 0x14b:0xd DW_TAG_lexical_block
	.byte	6                               // Abbrev [6] 0x14c:0xb DW_TAG_variable
	.long	.Linfo_string30                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	94                              // DW_AT_decl_line
	.long	345                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x159:0x5 DW_TAG_const_type
	.long	38                              // DW_AT_type
	.byte	7                               // Abbrev [7] 0x15e:0x5 DW_TAG_const_type
	.long	45                              // DW_AT_type
	.byte	2                               // Abbrev [2] 0x163:0x7 DW_TAG_base_type
	.long	.Linfo_string23                 // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	12                              // Abbrev [12] 0x16a:0x40 DW_TAG_subprogram
	.long	.Linfo_string31                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	57                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0x172:0xb DW_TAG_formal_parameter
	.long	.Linfo_string16                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	57                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	5                               // Abbrev [5] 0x17d:0xb DW_TAG_formal_parameter
	.long	.Linfo_string17                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	57                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	5                               // Abbrev [5] 0x188:0xb DW_TAG_formal_parameter
	.long	.Linfo_string32                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	57                              // DW_AT_decl_line
	.long	426                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0x193:0xb DW_TAG_formal_parameter
	.long	.Linfo_string33                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	57                              // DW_AT_decl_line
	.long	426                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x19e:0xb DW_TAG_variable
	.long	.Linfo_string34                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	59                              // DW_AT_decl_line
	.long	431                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	13                              // Abbrev [13] 0x1aa:0x5 DW_TAG_pointer_type
	.long	45                              // DW_AT_type
	.byte	7                               // Abbrev [7] 0x1af:0x5 DW_TAG_const_type
	.long	67                              // DW_AT_type
	.byte	14                              // Abbrev [14] 0x1b4:0x2e DW_TAG_subprogram
	.long	.Linfo_string35                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	257                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.byte	1                               // DW_AT_inline
	.byte	15                              // Abbrev [15] 0x1bd:0xc DW_TAG_formal_parameter
	.long	.Linfo_string32                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	257                             // DW_AT_decl_line
	.long	426                             // DW_AT_type
	.byte	15                              // Abbrev [15] 0x1c9:0xc DW_TAG_formal_parameter
	.long	.Linfo_string33                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	257                             // DW_AT_decl_line
	.long	426                             // DW_AT_type
	.byte	15                              // Abbrev [15] 0x1d5:0xc DW_TAG_formal_parameter
	.long	.Linfo_string36                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	257                             // DW_AT_decl_line
	.long	355                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	14                              // Abbrev [14] 0x1e2:0x58 DW_TAG_subprogram
	.long	.Linfo_string37                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	264                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.byte	1                               // DW_AT_inline
	.byte	15                              // Abbrev [15] 0x1eb:0xc DW_TAG_formal_parameter
	.long	.Linfo_string32                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	264                             // DW_AT_decl_line
	.long	426                             // DW_AT_type
	.byte	15                              // Abbrev [15] 0x1f7:0xc DW_TAG_formal_parameter
	.long	.Linfo_string33                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	264                             // DW_AT_decl_line
	.long	426                             // DW_AT_type
	.byte	15                              // Abbrev [15] 0x203:0xc DW_TAG_formal_parameter
	.long	.Linfo_string36                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	264                             // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	11                              // Abbrev [11] 0x20f:0xe DW_TAG_lexical_block
	.byte	16                              // Abbrev [16] 0x210:0xc DW_TAG_variable
	.long	.Linfo_string38                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	267                             // DW_AT_decl_line
	.long	570                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	11                              // Abbrev [11] 0x21d:0xe DW_TAG_lexical_block
	.byte	16                              // Abbrev [16] 0x21e:0xc DW_TAG_variable
	.long	.Linfo_string38                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	271                             // DW_AT_decl_line
	.long	570                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	11                              // Abbrev [11] 0x22b:0xe DW_TAG_lexical_block
	.byte	16                              // Abbrev [16] 0x22c:0xc DW_TAG_variable
	.long	.Linfo_string38                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.short	275                             // DW_AT_decl_line
	.long	570                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x23a:0x5 DW_TAG_const_type
	.long	575                             // DW_AT_type
	.byte	2                               // Abbrev [2] 0x23f:0x7 DW_TAG_base_type
	.long	.Linfo_string39                 // DW_AT_name
	.byte	2                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x246:0x18 DW_TAG_subprogram
	.long	.Linfo_string40                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	50                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	355                             // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0x252:0xb DW_TAG_formal_parameter
	.long	.Linfo_string16                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	50                              // DW_AT_decl_line
	.long	45                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	4                               // Abbrev [4] 0x25e:0x23 DW_TAG_subprogram
	.long	.Linfo_string41                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	249                             // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	355                             // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	5                               // Abbrev [5] 0x26a:0xb DW_TAG_formal_parameter
	.long	.Linfo_string42                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	249                             // DW_AT_decl_line
	.long	426                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x275:0xb DW_TAG_variable
	.long	.Linfo_string30                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	251                             // DW_AT_decl_line
	.long	641                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x281:0x5 DW_TAG_const_type
	.long	355                             // DW_AT_type
	.byte	17                              // Abbrev [17] 0x286:0x1a8 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string43                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	19                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	120                             // DW_AT_type
                                        // DW_AT_external
	.byte	18                              // Abbrev [18] 0x29b:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string16                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	19                              // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	18                              // Abbrev [18] 0x2aa:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string17                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	19                              // DW_AT_decl_line
	.long	120                             // DW_AT_type
	.byte	19                              // Abbrev [19] 0x2b9:0x16d DW_TAG_inlined_subroutine
	.long	174                             // DW_AT_abstract_origin
	.long	.Ldebug_ranges0                 // DW_AT_ranges
	.byte	3                               // DW_AT_call_file
	.byte	21                              // DW_AT_call_line
	.byte	12                              // DW_AT_call_column
	.byte	20                              // Abbrev [20] 0x2c5:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	186                             // DW_AT_abstract_origin
	.byte	20                              // Abbrev [20] 0x2ce:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	197                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x2d7:0x9 DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	208                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x2e0:0x9 DW_TAG_variable
	.long	.Ldebug_loc5                    // DW_AT_location
	.long	219                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x2e9:0x9 DW_TAG_variable
	.long	.Ldebug_loc6                    // DW_AT_location
	.long	230                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x2f2:0x9 DW_TAG_variable
	.long	.Ldebug_loc7                    // DW_AT_location
	.long	241                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x2fb:0x9 DW_TAG_variable
	.long	.Ldebug_loc8                    // DW_AT_location
	.long	252                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x304:0x9 DW_TAG_variable
	.long	.Ldebug_loc9                    // DW_AT_location
	.long	263                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x30d:0x9 DW_TAG_variable
	.long	.Ldebug_loc12                   // DW_AT_location
	.long	274                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x316:0x9 DW_TAG_variable
	.long	.Ldebug_loc13                   // DW_AT_location
	.long	285                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x31f:0x9 DW_TAG_variable
	.long	.Ldebug_loc16                   // DW_AT_location
	.long	296                             // DW_AT_abstract_origin
	.byte	22                              // Abbrev [22] 0x328:0x18 DW_TAG_inlined_subroutine
	.long	85                              // DW_AT_abstract_origin
	.long	.Ltmp0                          // DW_AT_low_pc
	.long	.Ltmp1-.Ltmp0                   // DW_AT_high_pc
	.byte	4                               // DW_AT_call_file
	.byte	18                              // DW_AT_call_line
	.byte	36                              // DW_AT_call_column
	.byte	23                              // Abbrev [23] 0x338:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	97                              // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	24                              // Abbrev [24] 0x340:0x4f DW_TAG_lexical_block
	.long	.Ldebug_ranges1                 // DW_AT_ranges
	.byte	21                              // Abbrev [21] 0x345:0x9 DW_TAG_variable
	.long	.Ldebug_loc14                   // DW_AT_location
	.long	308                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x34e:0x9 DW_TAG_variable
	.long	.Ldebug_loc15                   // DW_AT_location
	.long	319                             // DW_AT_abstract_origin
	.byte	22                              // Abbrev [22] 0x357:0x37 DW_TAG_inlined_subroutine
	.long	606                             // DW_AT_abstract_origin
	.long	.Ltmp66                         // DW_AT_low_pc
	.long	.Ltmp69-.Ltmp66                 // DW_AT_high_pc
	.byte	4                               // DW_AT_call_file
	.byte	60                              // DW_AT_call_line
	.byte	42                              // DW_AT_call_column
	.byte	25                              // Abbrev [25] 0x367:0x5 DW_TAG_formal_parameter
	.long	618                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x36c:0x9 DW_TAG_variable
	.long	.Ldebug_loc19                   // DW_AT_location
	.long	629                             // DW_AT_abstract_origin
	.byte	22                              // Abbrev [22] 0x375:0x18 DW_TAG_inlined_subroutine
	.long	582                             // DW_AT_abstract_origin
	.long	.Ltmp66                         // DW_AT_low_pc
	.long	.Ltmp67-.Ltmp66                 // DW_AT_high_pc
	.byte	2                               // DW_AT_call_file
	.byte	251                             // DW_AT_call_line
	.byte	23                              // DW_AT_call_column
	.byte	23                              // Abbrev [23] 0x385:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	83
	.long	594                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x38f:0x2d DW_TAG_inlined_subroutine
	.long	362                             // DW_AT_abstract_origin
	.long	.Ltmp10                         // DW_AT_low_pc
	.long	.Ltmp13-.Ltmp10                 // DW_AT_high_pc
	.byte	4                               // DW_AT_call_file
	.byte	75                              // DW_AT_call_line
	.byte	5                               // DW_AT_call_column
	.byte	20                              // Abbrev [20] 0x39f:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc10                   // DW_AT_location
	.long	370                             // DW_AT_abstract_origin
	.byte	20                              // Abbrev [20] 0x3a8:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc11                   // DW_AT_location
	.long	381                             // DW_AT_abstract_origin
	.byte	25                              // Abbrev [25] 0x3b1:0x5 DW_TAG_formal_parameter
	.long	392                             // DW_AT_abstract_origin
	.byte	25                              // Abbrev [25] 0x3b6:0x5 DW_TAG_formal_parameter
	.long	403                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	22                              // Abbrev [22] 0x3bc:0x21 DW_TAG_inlined_subroutine
	.long	436                             // DW_AT_abstract_origin
	.long	.Ltmp16                         // DW_AT_low_pc
	.long	.Ltmp18-.Ltmp16                 // DW_AT_high_pc
	.byte	4                               // DW_AT_call_file
	.byte	82                              // DW_AT_call_line
	.byte	10                              // DW_AT_call_column
	.byte	25                              // Abbrev [25] 0x3cc:0x5 DW_TAG_formal_parameter
	.long	445                             // DW_AT_abstract_origin
	.byte	25                              // Abbrev [25] 0x3d1:0x5 DW_TAG_formal_parameter
	.long	457                             // DW_AT_abstract_origin
	.byte	26                              // Abbrev [26] 0x3d6:0x6 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_const_value
	.long	469                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	27                              // Abbrev [27] 0x3dd:0x48 DW_TAG_lexical_block
	.long	.Ltmp41                         // DW_AT_low_pc
	.long	.Ltmp47-.Ltmp41                 // DW_AT_high_pc
	.byte	21                              // Abbrev [21] 0x3e6:0x9 DW_TAG_variable
	.long	.Ldebug_loc17                   // DW_AT_location
	.long	332                             // DW_AT_abstract_origin
	.byte	22                              // Abbrev [22] 0x3ef:0x35 DW_TAG_inlined_subroutine
	.long	482                             // DW_AT_abstract_origin
	.long	.Ltmp43                         // DW_AT_low_pc
	.long	.Ltmp47-.Ltmp43                 // DW_AT_high_pc
	.byte	4                               // DW_AT_call_file
	.byte	99                              // DW_AT_call_line
	.byte	9                               // DW_AT_call_column
	.byte	25                              // Abbrev [25] 0x3ff:0x5 DW_TAG_formal_parameter
	.long	491                             // DW_AT_abstract_origin
	.byte	25                              // Abbrev [25] 0x404:0x5 DW_TAG_formal_parameter
	.long	503                             // DW_AT_abstract_origin
	.byte	23                              // Abbrev [23] 0x409:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	83
	.long	515                             // DW_AT_abstract_origin
	.byte	27                              // Abbrev [27] 0x410:0x13 DW_TAG_lexical_block
	.long	.Ltmp43                         // DW_AT_low_pc
	.long	.Ltmp47-.Ltmp43                 // DW_AT_high_pc
	.byte	21                              // Abbrev [21] 0x419:0x9 DW_TAG_variable
	.long	.Ldebug_loc18                   // DW_AT_location
	.long	528                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	28                              // Abbrev [28] 0x426:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp13                         // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_ranges,"",@progbits
.Ldebug_ranges0:
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp40-.Lfunc_begin0
	.long	.Ltmp41-.Lfunc_begin0
	.long	.Ltmp70-.Lfunc_begin0
	.long	0
	.long	0
.Ldebug_ranges1:
	.long	.Ltmp19-.Lfunc_begin0
	.long	.Ltmp24-.Lfunc_begin0
	.long	.Ltmp32-.Lfunc_begin0
	.long	.Ltmp39-.Lfunc_begin0
	.long	.Ltmp52-.Lfunc_begin0
	.long	.Ltmp60-.Lfunc_begin0
	.long	.Ltmp61-.Lfunc_begin0
	.long	.Ltmp64-.Lfunc_begin0
	.long	.Ltmp65-.Lfunc_begin0
	.long	.Ltmp70-.Lfunc_begin0
	.long	0
	.long	0
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/mulsf3.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=152
.Linfo_string3:
	.asciz	"unsigned int"                  // string offset=173
.Linfo_string4:
	.asciz	"uint32_t"                      // string offset=186
.Linfo_string5:
	.asciz	"rep_t"                         // string offset=195
.Linfo_string6:
	.asciz	"long unsigned int"             // string offset=201
.Linfo_string7:
	.asciz	"uint64_t"                      // string offset=219
.Linfo_string8:
	.asciz	"toRep"                         // string offset=228
.Linfo_string9:
	.asciz	"x"                             // string offset=234
.Linfo_string10:
	.asciz	"float"                         // string offset=236
.Linfo_string11:
	.asciz	"fp_t"                          // string offset=242
.Linfo_string12:
	.asciz	"rep"                           // string offset=247
.Linfo_string13:
	.asciz	"f"                             // string offset=251
.Linfo_string14:
	.asciz	"i"                             // string offset=253
.Linfo_string15:
	.asciz	"__mulXf3__"                    // string offset=255
.Linfo_string16:
	.asciz	"a"                             // string offset=266
.Linfo_string17:
	.asciz	"b"                             // string offset=268
.Linfo_string18:
	.asciz	"aExponent"                     // string offset=270
.Linfo_string19:
	.asciz	"bExponent"                     // string offset=280
.Linfo_string20:
	.asciz	"productSign"                   // string offset=290
.Linfo_string21:
	.asciz	"aSignificand"                  // string offset=302
.Linfo_string22:
	.asciz	"scale"                         // string offset=315
.Linfo_string23:
	.asciz	"int"                           // string offset=321
.Linfo_string24:
	.asciz	"bSignificand"                  // string offset=325
.Linfo_string25:
	.asciz	"productHi"                     // string offset=338
.Linfo_string26:
	.asciz	"productExponent"               // string offset=348
.Linfo_string27:
	.asciz	"productLo"                     // string offset=364
.Linfo_string28:
	.asciz	"bAbs"                          // string offset=374
.Linfo_string29:
	.asciz	"aAbs"                          // string offset=379
.Linfo_string30:
	.asciz	"shift"                         // string offset=384
.Linfo_string31:
	.asciz	"wideMultiply"                  // string offset=390
.Linfo_string32:
	.asciz	"hi"                            // string offset=403
.Linfo_string33:
	.asciz	"lo"                            // string offset=406
.Linfo_string34:
	.asciz	"product"                       // string offset=409
.Linfo_string35:
	.asciz	"wideLeftShift"                 // string offset=417
.Linfo_string36:
	.asciz	"count"                         // string offset=431
.Linfo_string37:
	.asciz	"wideRightShiftWithSticky"      // string offset=437
.Linfo_string38:
	.asciz	"sticky"                        // string offset=462
.Linfo_string39:
	.asciz	"_Bool"                         // string offset=469
.Linfo_string40:
	.asciz	"rep_clz"                       // string offset=475
.Linfo_string41:
	.asciz	"normalize"                     // string offset=483
.Linfo_string42:
	.asciz	"significand"                   // string offset=493
.Linfo_string43:
	.asciz	"__mulsf3"                      // string offset=505
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
