	.text
	.file	"paritysi2.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/syslib/int_types.h"
	.section	.text.__paritysi2,"ax",@progbits
	.globl	__paritysi2                     // -- Begin function __paritysi2
	.type	__paritysi2,@function
__paritysi2:                            // @__paritysi2
.Lfunc_begin0:
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/paritysi2.c"
	.loc	2 21 0                          // uPIMulator_frontend/sdk/syslib/paritysi2.c:21:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __paritysi2:a <- $r0
	//DEBUG_VALUE: __paritysi2:a <- $r0
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: __paritysi2:x <- $r0
	//DEBUG_VALUE: __paritysi2:x <- $r0
	.loc	2 23 12 prologue_end            // uPIMulator_frontend/sdk/syslib/paritysi2.c:23:12
	lsr r1, r0, 16
	.loc	2 23 7 is_stmt 0                // uPIMulator_frontend/sdk/syslib/paritysi2.c:23:7
	xor r0, r1, r0
.Ltmp0:
	//DEBUG_VALUE: __paritysi2:x <- $r0
	.loc	2 24 12 is_stmt 1               // uPIMulator_frontend/sdk/syslib/paritysi2.c:24:12
	lsr r1, r0, 8
	.loc	2 24 7 is_stmt 0                // uPIMulator_frontend/sdk/syslib/paritysi2.c:24:7
	xor r0, r1, r0
.Ltmp1:
	//DEBUG_VALUE: __paritysi2:x <- $r0
	.loc	2 25 12 is_stmt 1               // uPIMulator_frontend/sdk/syslib/paritysi2.c:25:12
	lsr r1, r0, 4
	.loc	2 25 7 is_stmt 0                // uPIMulator_frontend/sdk/syslib/paritysi2.c:25:7
	xor r0, r1, r0
.Ltmp2:
	//DEBUG_VALUE: __paritysi2:x <- $r0
	.loc	2 26 26 is_stmt 1               // uPIMulator_frontend/sdk/syslib/paritysi2.c:26:26
	and r0, r0, 15
.Ltmp3:
	.loc	2 0 26 is_stmt 0                // uPIMulator_frontend/sdk/syslib/paritysi2.c:0:26
	move r1, 27030
	.loc	2 26 20                         // uPIMulator_frontend/sdk/syslib/paritysi2.c:26:20
	lsr r0, r1, r0
	.loc	2 26 34                         // uPIMulator_frontend/sdk/syslib/paritysi2.c:26:34
	and r0, r0, 1
	.loc	2 26 5                          // uPIMulator_frontend/sdk/syslib/paritysi2.c:26:5
	jump r23
.Ltmp4:
.Lfunc_end0:
	.size	__paritysi2, .Lfunc_end0-__paritysi2
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__paritysi2
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.__paritysi2,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp3-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x74 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0xb DW_TAG_typedef
	.long	49                              // DW_AT_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	28                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x31:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x38:0x34 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string5                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	20                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	108                             // DW_AT_type
                                        // DW_AT_external
	.byte	5                               // Abbrev [5] 0x4d:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	20                              // DW_AT_decl_line
	.long	108                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x5c:0xf DW_TAG_variable
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string9                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	2                               // Abbrev [2] 0x6c:0xb DW_TAG_typedef
	.long	119                             // DW_AT_type
	.long	.Linfo_string7                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	27                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x77:0x7 DW_TAG_base_type
	.long	.Linfo_string6                  // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/paritysi2.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=155
.Linfo_string3:
	.asciz	"unsigned int"                  // string offset=176
.Linfo_string4:
	.asciz	"su_int"                        // string offset=189
.Linfo_string5:
	.asciz	"__paritysi2"                   // string offset=196
.Linfo_string6:
	.asciz	"int"                           // string offset=208
.Linfo_string7:
	.asciz	"si_int"                        // string offset=212
.Linfo_string8:
	.asciz	"a"                             // string offset=219
.Linfo_string9:
	.asciz	"x"                             // string offset=221
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
