	.text
	.file	"paritydi2.c"
	.section	.text.__paritydi2,"ax",@progbits
	.globl	__paritydi2                     // -- Begin function __paritydi2
	.type	__paritydi2,@function
__paritydi2:                            // @__paritydi2
.Lfunc_begin0:
	.file	1 "/root" "uPIMulator_frontend/sdk/syslib/paritydi2.c"
	.loc	1 21 0                          // uPIMulator_frontend/sdk/syslib/paritydi2.c:21:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __paritydi2:a <- $d0
	//DEBUG_VALUE: __paritydi2:a <- $d0
	.cfi_def_cfa_offset -8
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 0, d22
	add r22, r22, 8
.Ltmp0:
	//DEBUG_VALUE: __paritydi2:x <- [DW_OP_LLVM_convert 64 7, DW_OP_LLVM_convert 32 7, DW_OP_stack_value, DW_OP_LLVM_fragment 0 32] $d0
	//DEBUG_VALUE: __paritydi2:x <- [DW_OP_LLVM_convert 64 7, DW_OP_LLVM_convert 32 7, DW_OP_stack_value, DW_OP_LLVM_fragment 0 32] $d0
	.loc	1 23 11 prologue_end            // uPIMulator_frontend/sdk/syslib/paritydi2.c:23:11
	move.u d2, r0
.Ltmp1:
	//DEBUG_VALUE: __paritydi2:x <- [DW_OP_LLVM_convert 64 7, DW_OP_LLVM_convert 32 7, DW_OP_stack_value, DW_OP_LLVM_fragment 32 32] $d2
	.loc	1 24 33                         // uPIMulator_frontend/sdk/syslib/paritydi2.c:24:33
	xor r1, r3, r1
.Ltmp2:
	xor r0, r2, r0
	.loc	1 24 12 is_stmt 0               // uPIMulator_frontend/sdk/syslib/paritydi2.c:24:12
	move r0, r1
	call r23, __paritysi2
.Ltmp3:
	.loc	1 24 5                          // uPIMulator_frontend/sdk/syslib/paritydi2.c:24:5
	ld d22, r22, -8
	jump r23
.Ltmp4:
.Lfunc_end0:
	.size	__paritydi2, .Lfunc_end0-__paritydi2
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__paritydi2
	.long	.Lfunc_begin0
	.byte	8
	.section	.text.__paritydi2,"ax",@progbits
                                        // -- End function
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/int_types.h"
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp2-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp1-.Lfunc_begin0
	.short	5                               // Loc expr size
	.byte	113                             // DW_OP_breg1
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp1-.Lfunc_begin0
	.long	.Ltmp2-.Lfunc_begin0
	.short	10                              // Loc expr size
	.byte	113                             // DW_OP_breg1
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	115                             // DW_OP_breg3
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	7                               // Loc expr size
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	115                             // DW_OP_breg3
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.ascii	"\211\202\001"                  // DW_TAG_GNU_call_site
	.byte	0                               // DW_CHILDREN_no
	.ascii	"\223B"                         // DW_AT_GNU_call_site_target
	.byte	24                              // DW_FORM_exprloc
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	23                              // DW_TAG_union_type
	.byte	1                               // DW_CHILDREN_yes
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	13                              // DW_TAG_member
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	56                              // DW_AT_data_member_location
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	19                              // DW_TAG_structure_type
	.byte	1                               // DW_CHILDREN_yes
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0xd2 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x3b DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string3                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	20                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	97                              // DW_AT_type
                                        // DW_AT_external
	.byte	3                               // Abbrev [3] 0x3b:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string6                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	20                              // DW_AT_decl_line
	.long	115                             // DW_AT_type
	.byte	4                               // Abbrev [4] 0x4a:0xf DW_TAG_variable
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string9                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
	.long	133                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0x59:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp3                          // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	6                               // Abbrev [6] 0x61:0xb DW_TAG_typedef
	.long	108                             // DW_AT_type
	.long	.Linfo_string5                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	27                              // DW_AT_decl_line
	.byte	7                               // Abbrev [7] 0x6c:0x7 DW_TAG_base_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	6                               // Abbrev [6] 0x73:0xb DW_TAG_typedef
	.long	126                             // DW_AT_type
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	30                              // DW_AT_decl_line
	.byte	7                               // Abbrev [7] 0x7e:0x7 DW_TAG_base_type
	.long	.Linfo_string7                  // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	6                               // Abbrev [6] 0x85:0xb DW_TAG_typedef
	.long	144                             // DW_AT_type
	.long	.Linfo_string16                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	44                              // DW_AT_decl_line
	.byte	8                               // Abbrev [8] 0x90:0x3a DW_TAG_union_type
	.byte	8                               // DW_AT_byte_size
	.byte	2                               // DW_AT_decl_file
	.byte	33                              // DW_AT_decl_line
	.byte	9                               // Abbrev [9] 0x94:0xc DW_TAG_member
	.long	.Linfo_string10                 // DW_AT_name
	.long	115                             // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	34                              // DW_AT_decl_line
	.byte	0                               // DW_AT_data_member_location
	.byte	9                               // Abbrev [9] 0xa0:0xc DW_TAG_member
	.long	.Linfo_string11                 // DW_AT_name
	.long	172                             // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	43                              // DW_AT_decl_line
	.byte	0                               // DW_AT_data_member_location
	.byte	10                              // Abbrev [10] 0xac:0x1d DW_TAG_structure_type
	.byte	8                               // DW_AT_byte_size
	.byte	2                               // DW_AT_decl_file
	.byte	35                              // DW_AT_decl_line
	.byte	9                               // Abbrev [9] 0xb0:0xc DW_TAG_member
	.long	.Linfo_string12                 // DW_AT_name
	.long	202                             // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	37                              // DW_AT_decl_line
	.byte	0                               // DW_AT_data_member_location
	.byte	9                               // Abbrev [9] 0xbc:0xc DW_TAG_member
	.long	.Linfo_string15                 // DW_AT_name
	.long	97                              // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	38                              // DW_AT_decl_line
	.byte	4                               // DW_AT_data_member_location
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	6                               // Abbrev [6] 0xca:0xb DW_TAG_typedef
	.long	213                             // DW_AT_type
	.long	.Linfo_string14                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	28                              // DW_AT_decl_line
	.byte	7                               // Abbrev [7] 0xd5:0x7 DW_TAG_base_type
	.long	.Linfo_string13                 // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/paritydi2.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=155
.Linfo_string3:
	.asciz	"__paritydi2"                   // string offset=176
.Linfo_string4:
	.asciz	"int"                           // string offset=188
.Linfo_string5:
	.asciz	"si_int"                        // string offset=192
.Linfo_string6:
	.asciz	"a"                             // string offset=199
.Linfo_string7:
	.asciz	"long long int"                 // string offset=201
.Linfo_string8:
	.asciz	"di_int"                        // string offset=215
.Linfo_string9:
	.asciz	"x"                             // string offset=222
.Linfo_string10:
	.asciz	"all"                           // string offset=224
.Linfo_string11:
	.asciz	"s"                             // string offset=228
.Linfo_string12:
	.asciz	"low"                           // string offset=230
.Linfo_string13:
	.asciz	"unsigned int"                  // string offset=234
.Linfo_string14:
	.asciz	"su_int"                        // string offset=247
.Linfo_string15:
	.asciz	"high"                          // string offset=254
.Linfo_string16:
	.asciz	"dwords"                        // string offset=259
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
