	.text
	.file	"perfcounter.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/syslib/perfcounter.h"
	.file	2 "/root" "uPIMulator_frontend/sdk/stdlib/stdint.h"
	.section	.text.perfcounter_get,"ax",@progbits
	.globl	perfcounter_get                 // -- Begin function perfcounter_get
	.type	perfcounter_get,@function
perfcounter_get:                        // @perfcounter_get
.Lfunc_begin0:
	.file	3 "/root" "uPIMulator_frontend/sdk/syslib/perfcounter.c"
	.loc	3 13 0                          // uPIMulator_frontend/sdk/syslib/perfcounter.c:13:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	.cfi_def_cfa_offset 0
	.loc	3 15 5 prologue_end             // uPIMulator_frontend/sdk/syslib/perfcounter.c:15:5
	// inline asm
	time r0
	// inline asm
.Ltmp0:
	//DEBUG_VALUE: perfcounter_get:reg_value <- $r0
	.loc	3 16 13                         // uPIMulator_frontend/sdk/syslib/perfcounter.c:16:13
	move.u d2, r0
	.loc	3 16 39 is_stmt 0               // uPIMulator_frontend/sdk/syslib/perfcounter.c:16:39
	lslx r0, r3, 4
.Ltmp1:
	lsl_add r0, r0, r2, 4
	lsl r1, r3, 4
	.loc	3 16 5                          // uPIMulator_frontend/sdk/syslib/perfcounter.c:16:5
	jump r23
.Ltmp2:
.Lfunc_end0:
	.size	perfcounter_get, .Lfunc_end0-perfcounter_get
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.perfcounter_get
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.perfcounter_get,"ax",@progbits
                                        // -- End function
	.section	.text.perfcounter_config,"ax",@progbits
	.globl	perfcounter_config              // -- Begin function perfcounter_config
	.type	perfcounter_config,@function
perfcounter_config:                     // @perfcounter_config
.Lfunc_begin1:
	.loc	3 22 0 is_stmt 1                // uPIMulator_frontend/sdk/syslib/perfcounter.c:22:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: perfcounter_config:config <- $r0
	//DEBUG_VALUE: perfcounter_config:config <- $r0
	//DEBUG_VALUE: perfcounter_config:reset_value <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] $r1
	//DEBUG_VALUE: perfcounter_config:reset_value <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] $r1
	.cfi_def_cfa_offset 0
	.loc	3 24 49 prologue_end            // uPIMulator_frontend/sdk/syslib/perfcounter.c:24:49
	lsl_add r0, r1, r0, 1
.Ltmp3:
	//DEBUG_VALUE: perfcounter_config:reg_config <- $r0
	.loc	3 25 5                          // uPIMulator_frontend/sdk/syslib/perfcounter.c:25:5
	// inline asm
	time_cfg r0, r0
	// inline asm
.Ltmp4:
	//DEBUG_VALUE: perfcounter_config:reg_value <- $r0
	.loc	3 26 13                         // uPIMulator_frontend/sdk/syslib/perfcounter.c:26:13
	move.u d2, r0
	.loc	3 26 39 is_stmt 0               // uPIMulator_frontend/sdk/syslib/perfcounter.c:26:39
	lslx r0, r3, 4
.Ltmp5:
	lsl_add r0, r0, r2, 4
.Ltmp6:
	lsl r1, r3, 4
	.loc	3 26 5                          // uPIMulator_frontend/sdk/syslib/perfcounter.c:26:5
	jump r23
.Ltmp7:
.Lfunc_end1:
	.size	perfcounter_config, .Lfunc_end1-perfcounter_config
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.perfcounter_config
	.long	.Lfunc_begin1
	.byte	0
	.section	.text.perfcounter_config,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp1-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc1:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Lfunc_begin1-.Lfunc_begin1
	.long	.Ltmp3-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc2:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Lfunc_begin1-.Lfunc_begin1
	.long	.Ltmp6-.Lfunc_begin1
	.short	6                               // Loc expr size
	.byte	113                             // DW_OP_breg1
	.byte	0                               // 0
	.byte	16                              // DW_OP_constu
	.byte	1                               // 1
	.byte	26                              // DW_OP_and
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc3:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp3-.Lfunc_begin1
	.long	.Ltmp4-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc4:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp4-.Lfunc_begin1
	.long	.Ltmp5-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	4                               // DW_TAG_enumeration_type
	.byte	1                               // DW_CHILDREN_yes
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	40                              // DW_TAG_enumerator
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	28                              // DW_AT_const_value
	.byte	15                              // DW_FORM_udata
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0xf9 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	0                               // DW_AT_low_pc
	.long	.Ldebug_ranges0                 // DW_AT_ranges
	.byte	2                               // Abbrev [2] 0x26:0x25 DW_TAG_enumeration_type
	.long	75                              // DW_AT_type
	.long	.Linfo_string8                  // DW_AT_name
	.byte	4                               // DW_AT_byte_size
	.byte	1                               // DW_AT_decl_file
	.byte	33                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x32:0x6 DW_TAG_enumerator
	.long	.Linfo_string4                  // DW_AT_name
	.byte	0                               // DW_AT_const_value
	.byte	3                               // Abbrev [3] 0x38:0x6 DW_TAG_enumerator
	.long	.Linfo_string5                  // DW_AT_name
	.byte	1                               // DW_AT_const_value
	.byte	3                               // Abbrev [3] 0x3e:0x6 DW_TAG_enumerator
	.long	.Linfo_string6                  // DW_AT_name
	.byte	2                               // DW_AT_const_value
	.byte	3                               // Abbrev [3] 0x44:0x6 DW_TAG_enumerator
	.long	.Linfo_string7                  // DW_AT_name
	.byte	3                               // DW_AT_const_value
	.byte	0                               // End Of Children Mark
	.byte	4                               // Abbrev [4] 0x4b:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	5                               // Abbrev [5] 0x52:0xb DW_TAG_typedef
	.long	93                              // DW_AT_type
	.long	.Linfo_string11                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
	.byte	5                               // Abbrev [5] 0x5d:0xb DW_TAG_typedef
	.long	104                             // DW_AT_type
	.long	.Linfo_string10                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	53                              // DW_AT_decl_line
	.byte	4                               // Abbrev [4] 0x68:0x7 DW_TAG_base_type
	.long	.Linfo_string9                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	6                               // Abbrev [6] 0x6f:0x25 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string12                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	12                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	82                              // DW_AT_type
                                        // DW_AT_external
	.byte	7                               // Abbrev [7] 0x84:0xf DW_TAG_variable
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string14                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	14                              // DW_AT_decl_line
	.long	230                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	6                               // Abbrev [6] 0x94:0x52 DW_TAG_subprogram
	.long	.Lfunc_begin1                   // DW_AT_low_pc
	.long	.Lfunc_end1-.Lfunc_begin1       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string13                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	21                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	82                              // DW_AT_type
                                        // DW_AT_external
	.byte	8                               // Abbrev [8] 0xa9:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string16                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	21                              // DW_AT_decl_line
	.long	241                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0xb8:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string18                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	21                              // DW_AT_decl_line
	.long	252                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0xc7:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string20                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	24                              // DW_AT_decl_line
	.long	230                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0xd6:0xf DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	.Linfo_string14                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	23                              // DW_AT_decl_line
	.long	230                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	5                               // Abbrev [5] 0xe6:0xb DW_TAG_typedef
	.long	75                              // DW_AT_type
	.long	.Linfo_string15                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	48                              // DW_AT_decl_line
	.byte	5                               // Abbrev [5] 0xf1:0xb DW_TAG_typedef
	.long	38                              // DW_AT_type
	.long	.Linfo_string17                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	38                              // DW_AT_decl_line
	.byte	4                               // Abbrev [4] 0xfc:0x7 DW_TAG_base_type
	.long	.Linfo_string19                 // DW_AT_name
	.byte	2                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_ranges,"",@progbits
.Ldebug_ranges0:
	.long	.Lfunc_begin0
	.long	.Lfunc_end0
	.long	.Lfunc_begin1
	.long	.Lfunc_end1
	.long	0
	.long	0
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/perfcounter.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=157
.Linfo_string3:
	.asciz	"unsigned int"                  // string offset=178
.Linfo_string4:
	.asciz	"COUNT_SAME"                    // string offset=191
.Linfo_string5:
	.asciz	"COUNT_CYCLES"                  // string offset=202
.Linfo_string6:
	.asciz	"COUNT_INSTRUCTIONS"            // string offset=215
.Linfo_string7:
	.asciz	"COUNT_NOTHING"                 // string offset=234
.Linfo_string8:
	.asciz	"_perfcounter_config_t"         // string offset=248
.Linfo_string9:
	.asciz	"long unsigned int"             // string offset=270
.Linfo_string10:
	.asciz	"uint64_t"                      // string offset=288
.Linfo_string11:
	.asciz	"perfcounter_t"                 // string offset=297
.Linfo_string12:
	.asciz	"perfcounter_get"               // string offset=311
.Linfo_string13:
	.asciz	"perfcounter_config"            // string offset=327
.Linfo_string14:
	.asciz	"reg_value"                     // string offset=346
.Linfo_string15:
	.asciz	"uint32_t"                      // string offset=356
.Linfo_string16:
	.asciz	"config"                        // string offset=365
.Linfo_string17:
	.asciz	"perfcounter_config_t"          // string offset=372
.Linfo_string18:
	.asciz	"reset_value"                   // string offset=393
.Linfo_string19:
	.asciz	"_Bool"                         // string offset=405
.Linfo_string20:
	.asciz	"reg_config"                    // string offset=411
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
