	.text
	.file	"powidf2.c"
	.section	.text.__powidf2,"ax",@progbits
	.globl	__powidf2                       // -- Begin function __powidf2
	.type	__powidf2,@function
__powidf2:                              // @__powidf2
.Lfunc_begin0:
	.file	1 "/root" "uPIMulator_frontend/sdk/syslib/powidf2.c"
	.loc	1 21 0                          // uPIMulator_frontend/sdk/syslib/powidf2.c:21:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __powidf2:a <- $d0
	//DEBUG_VALUE: __powidf2:b <- $r2
	.cfi_def_cfa_offset -40
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 32, d22
	add r22, r22, 40
	.cfi_offset 15, -16
	.cfi_offset 14, -12
	sd r22, -16, d14
	.cfi_offset 17, -24
	.cfi_offset 16, -20
	sd r22, -24, d16
	.cfi_offset 19, -32
	.cfi_offset 18, -28
	sd r22, -32, d18
	.cfi_offset 21, -40
	.cfi_offset 20, -36
	sd r22, -40, d20
	move r16, r2
	movd d18, d0
.Ltmp0:
	//DEBUG_VALUE: __powidf2:r <- 1.000000e+00
	//DEBUG_VALUE: __powidf2:recip <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 32 7, DW_OP_stack_value] undef
	//DEBUG_VALUE: __powidf2:b <- $r16
	//DEBUG_VALUE: __powidf2:a <- $d18
	.loc	1 25 15 prologue_end            // uPIMulator_frontend/sdk/syslib/powidf2.c:25:15
	and r0, r16, 1, z, .LBB0_1
.Ltmp1:
// %bb.2:
	//DEBUG_VALUE: __powidf2:b <- $r16
	//DEBUG_VALUE: __powidf2:a <- $d18
	//DEBUG_VALUE: __powidf2:r <- 1.000000e+00
	.loc	1 25 13 is_stmt 0               // uPIMulator_frontend/sdk/syslib/powidf2.c:25:13
	movd d14, d18
.Ltmp2:
	//DEBUG_VALUE: __powidf2:b <- [DW_OP_constu 2, DW_OP_div, DW_OP_stack_value] $r16
	//DEBUG_VALUE: __powidf2:r <- $d14
	.loc	1 28 15 is_stmt 1               // uPIMulator_frontend/sdk/syslib/powidf2.c:28:15
	add r0, r16, 1
.Ltmp3:
	.loc	1 28 13 is_stmt 0               // uPIMulator_frontend/sdk/syslib/powidf2.c:28:13
	jltu r0, 3, .LBB0_8
	jump .LBB0_4
.Ltmp4:
.LBB0_1:
	//DEBUG_VALUE: __powidf2:b <- $r16
	//DEBUG_VALUE: __powidf2:a <- $d18
	//DEBUG_VALUE: __powidf2:r <- 1.000000e+00
	.loc	1 0 13                          // uPIMulator_frontend/sdk/syslib/powidf2.c:0:13
	move r15, 0
	move r14, 1072693248
.Ltmp5:
	//DEBUG_VALUE: __powidf2:b <- [DW_OP_constu 2, DW_OP_div, DW_OP_stack_value] $r16
	//DEBUG_VALUE: __powidf2:r <- $d14
	.loc	1 28 15                         // uPIMulator_frontend/sdk/syslib/powidf2.c:28:15
	add r0, r16, 1
.Ltmp6:
	.loc	1 28 13                         // uPIMulator_frontend/sdk/syslib/powidf2.c:28:13
	jgeu r0, 3, .LBB0_4
.Ltmp7:
.LBB0_8:
	//DEBUG_VALUE: __powidf2:r <- $d14
	//DEBUG_VALUE: __powidf2:recip <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 32 7, DW_OP_stack_value] undef
	.loc	1 32 12 is_stmt 1               // uPIMulator_frontend/sdk/syslib/powidf2.c:32:12
	jgts r16, -1, .LBB0_10
.Ltmp8:
// %bb.9:
	//DEBUG_VALUE: __powidf2:r <- $d14
	.loc	1 0 12 is_stmt 0                // uPIMulator_frontend/sdk/syslib/powidf2.c:0:12
	move r1, 0
	move r0, 1072693248
	.loc	1 32 12                         // uPIMulator_frontend/sdk/syslib/powidf2.c:32:12
	movd d2, d14
	call r23, __divdf3
.Ltmp9:
	movd d14, d0
.Ltmp10:
.LBB0_10:
	.loc	1 32 5                          // uPIMulator_frontend/sdk/syslib/powidf2.c:32:5
	movd d0, d14
	ld d20, r22, -40
	ld d18, r22, -32
	ld d16, r22, -24
	ld d14, r22, -16
	ld d22, r22, -8
	jump r23
.LBB0_4:
.Ltmp11:
	//DEBUG_VALUE: __powidf2:b <- [DW_OP_constu 2, DW_OP_div, DW_OP_stack_value] $r16
	//DEBUG_VALUE: __powidf2:a <- $d18
	//DEBUG_VALUE: __powidf2:r <- $d14
	.loc	1 0 5                           // uPIMulator_frontend/sdk/syslib/powidf2.c:0:5
	move r17, r16, true, .LBB0_5
.Ltmp12:
.LBB0_7:                                //   in Loop: Header=BB0_5 Depth=1
	//DEBUG_VALUE: __powidf2:b <- $r17
	//DEBUG_VALUE: __powidf2:b <- [DW_OP_constu 2, DW_OP_div, DW_OP_stack_value] $r17
	//DEBUG_VALUE: __powidf2:r <- $d14
	.loc	1 28 15 is_stmt 1               // uPIMulator_frontend/sdk/syslib/powidf2.c:28:15
	add r0, r17, 1
.Ltmp13:
	.loc	1 28 13 is_stmt 0               // uPIMulator_frontend/sdk/syslib/powidf2.c:28:13
	jleu r0, 2, .LBB0_8
.Ltmp14:
.LBB0_5:                                // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: __powidf2:r <- $d14
	//DEBUG_VALUE: __powidf2:a <- $d18
	//DEBUG_VALUE: __powidf2:b <- $r17
	.loc	1 27 11 is_stmt 1               // uPIMulator_frontend/sdk/syslib/powidf2.c:27:11
	lsr_add r0, r17, r17, 31
	asr r17, r0, 1
.Ltmp15:
	//DEBUG_VALUE: __powidf2:b <- $r17
	.loc	1 30 11                         // uPIMulator_frontend/sdk/syslib/powidf2.c:30:11
	movd d0, d18
	movd d2, d18
	call r23, __muldf3
.Ltmp16:
	movd d18, d0
.Ltmp17:
	//DEBUG_VALUE: __powidf2:r <- $d14
	//DEBUG_VALUE: __powidf2:a <- undef
	.loc	1 25 15                         // uPIMulator_frontend/sdk/syslib/powidf2.c:25:15
	and r20, r17, 1
	movd d2, d14
	call r23, __muldf3
.Ltmp18:
	.loc	1 25 13 is_stmt 0               // uPIMulator_frontend/sdk/syslib/powidf2.c:25:13
	jeq r20, 0, .LBB0_7
.Ltmp19:
// %bb.6:                               //   in Loop: Header=BB0_5 Depth=1
	//DEBUG_VALUE: __powidf2:b <- $r17
	//DEBUG_VALUE: __powidf2:r <- $d14
	movd d14, d0
.Ltmp20:
	.loc	1 0 13                          // uPIMulator_frontend/sdk/syslib/powidf2.c:0:13
	jump .LBB0_7
.Ltmp21:
.Lfunc_end0:
	.size	__powidf2, .Lfunc_end0-__powidf2
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__powidf2
	.long	.Lfunc_begin0
	.byte	40
	.section	.text.__powidf2,"ax",@progbits
                                        // -- End function
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/int_types.h"
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp0-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	81                              // sub-register DW_OP_reg1
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	80                              // sub-register DW_OP_reg0
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp7-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	99                              // sub-register DW_OP_reg19
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	98                              // sub-register DW_OP_reg18
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp11-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	99                              // sub-register DW_OP_reg19
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	98                              // sub-register DW_OP_reg18
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Ltmp17-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	99                              // sub-register DW_OP_reg19
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	98                              // sub-register DW_OP_reg18
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp2-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	96                              // DW_OP_reg16
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp4-.Lfunc_begin0
	.short	5                               // Loc expr size
	.byte	128                             // DW_OP_breg16
	.byte	0                               // 0
	.byte	50                              // DW_OP_lit2
	.byte	27                              // DW_OP_div
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp4-.Lfunc_begin0
	.long	.Ltmp5-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	96                              // DW_OP_reg16
	.long	.Ltmp5-.Lfunc_begin0
	.long	.Ltmp7-.Lfunc_begin0
	.short	5                               // Loc expr size
	.byte	128                             // DW_OP_breg16
	.byte	0                               // 0
	.byte	50                              // DW_OP_lit2
	.byte	27                              // DW_OP_div
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp11-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.short	5                               // Loc expr size
	.byte	128                             // DW_OP_breg16
	.byte	0                               // 0
	.byte	50                              // DW_OP_lit2
	.byte	27                              // DW_OP_div
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp12-.Lfunc_begin0
	.long	.Ltmp14-.Lfunc_begin0
	.short	5                               // Loc expr size
	.byte	129                             // DW_OP_breg17
	.byte	0                               // 0
	.byte	50                              // DW_OP_lit2
	.byte	27                              // DW_OP_div
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Lfunc_end0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	97                              // DW_OP_reg17
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp2-.Lfunc_begin0
	.short	10                              // Loc expr size
	.byte	158                             // DW_OP_implicit_value
	.byte	8                               // 8
	.byte	0                               //  
	.byte	0                               //  
	.byte	0                               //  
	.byte	0                               //  
	.byte	0                               //  
	.byte	0                               //  
	.byte	240                             // ð
	.byte	63 // ?
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp4-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	95                              // sub-register DW_OP_reg15
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	94                              // sub-register DW_OP_reg14
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp4-.Lfunc_begin0
	.long	.Ltmp5-.Lfunc_begin0
	.short	10                              // Loc expr size
	.byte	158                             // DW_OP_implicit_value
	.byte	8                               // 8
	.byte	0                               //  
	.byte	0                               //  
	.byte	0                               //  
	.byte	0                               //  
	.byte	0                               //  
	.byte	0                               //  
	.byte	240                             // ð
	.byte	63 // ?
	.long	.Ltmp5-.Lfunc_begin0
	.long	.Ltmp10-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	95                              // sub-register DW_OP_reg15
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	94                              // sub-register DW_OP_reg14
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	.Ltmp11-.Lfunc_begin0
	.long	.Ltmp20-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	95                              // sub-register DW_OP_reg15
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.byte	94                              // sub-register DW_OP_reg14
	.byte	147                             // DW_OP_piece
	.byte	4                               // 4
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.ascii	"\211\202\001"                  // DW_TAG_GNU_call_site
	.byte	0                               // DW_CHILDREN_no
	.ascii	"\223B"                         // DW_AT_GNU_call_site_target
	.byte	24                              // DW_FORM_exprloc
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x9d DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x63 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string3                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	20                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	137                             // DW_AT_type
                                        // DW_AT_external
	.byte	3                               // Abbrev [3] 0x3b:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string5                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	20                              // DW_AT_decl_line
	.long	137                             // DW_AT_type
	.byte	3                               // Abbrev [3] 0x4a:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string6                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	20                              // DW_AT_decl_line
	.long	144                             // DW_AT_type
	.byte	4                               // Abbrev [4] 0x59:0xf DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string9                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	23                              // DW_AT_decl_line
	.long	137                             // DW_AT_type
	.byte	5                               // Abbrev [5] 0x68:0xb DW_TAG_variable
	.long	.Linfo_string10                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	22                              // DW_AT_decl_line
	.long	162                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x73:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp9                          // DW_AT_low_pc
	.byte	6                               // Abbrev [6] 0x7a:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp16                         // DW_AT_low_pc
	.byte	6                               // Abbrev [6] 0x81:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp18                         // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	7                               // Abbrev [7] 0x89:0x7 DW_TAG_base_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	4                               // DW_AT_encoding
	.byte	8                               // DW_AT_byte_size
	.byte	8                               // Abbrev [8] 0x90:0xb DW_TAG_typedef
	.long	155                             // DW_AT_type
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	27                              // DW_AT_decl_line
	.byte	7                               // Abbrev [7] 0x9b:0x7 DW_TAG_base_type
	.long	.Linfo_string7                  // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	9                               // Abbrev [9] 0xa2:0x5 DW_TAG_const_type
	.long	155                             // DW_AT_type
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/powidf2.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=153
.Linfo_string3:
	.asciz	"__powidf2"                     // string offset=174
.Linfo_string4:
	.asciz	"double"                        // string offset=184
.Linfo_string5:
	.asciz	"a"                             // string offset=191
.Linfo_string6:
	.asciz	"b"                             // string offset=193
.Linfo_string7:
	.asciz	"int"                           // string offset=195
.Linfo_string8:
	.asciz	"si_int"                        // string offset=199
.Linfo_string9:
	.asciz	"r"                             // string offset=206
.Linfo_string10:
	.asciz	"recip"                         // string offset=208
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
