	.text
	.file	"seqread256.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/stdlib/stdint.h"
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/seqread.h"
	.section	.text.seqread256_alloc,"ax",@progbits
	.globl	seqread256_alloc                // -- Begin function seqread256_alloc
	.type	seqread256_alloc,@function
seqread256_alloc:                       // @seqread256_alloc
.Lfunc_begin0:
	.file	3 "/root" "uPIMulator_frontend/sdk/syslib/seqread.inc"
	.loc	3 26 0                          // uPIMulator_frontend/sdk/syslib/seqread.inc:26:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	.cfi_def_cfa_offset -16
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 8, d22
	add r22, r22, 16
	.cfi_offset 15, -16
	.cfi_offset 14, -12
.Ltmp0:
	sd r22, -16, d14
	.loc	3 27 5 prologue_end             // uPIMulator_frontend/sdk/syslib/seqread.inc:27:5
	// inline asm
.Ltmp1:
	acquire zero, __atomic_bit___heap_pointer, nz, .Ltmp1
	// inline asm
	.loc	3 29 33                         // uPIMulator_frontend/sdk/syslib/seqread.inc:29:33
	lw r0, zero, __sys_heap_pointer
.Ltmp2:
	//DEBUG_VALUE: seqread256_alloc:heap_pointer <- $r0
	.loc	3 30 69                         // uPIMulator_frontend/sdk/syslib/seqread.inc:30:69
	add r1, r0, 255
	.loc	3 30 86 is_stmt 0               // uPIMulator_frontend/sdk/syslib/seqread.inc:30:86
	and r14, r1, -256
.Ltmp3:
	//DEBUG_VALUE: seqread256_alloc:pointer <- $r14
	.loc	3 31 45 is_stmt 1               // uPIMulator_frontend/sdk/syslib/seqread.inc:31:45
	sub r0, r14, r0
.Ltmp4:
	add r0, r0, 512
.Ltmp5:
	//DEBUG_VALUE: seqread256_alloc:size <- $r0
	.loc	3 34 5                          // uPIMulator_frontend/sdk/syslib/seqread.inc:34:5
	call r23, mem_alloc_nolock
.Ltmp6:
	.loc	3 36 5                          // uPIMulator_frontend/sdk/syslib/seqread.inc:36:5
	// inline asm
.Ltmp7:
	release zero, __atomic_bit___heap_pointer, nz, .Ltmp7+1
	// inline asm
	.loc	3 38 5                          // uPIMulator_frontend/sdk/syslib/seqread.inc:38:5
	move r0, r14
.Ltmp8:
	ld d14, r22, -16
.Ltmp9:
	ld d22, r22, -8
	jump r23
.Ltmp10:
.Lfunc_end0:
	.size	seqread256_alloc, .Lfunc_end0-seqread256_alloc
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.seqread256_alloc
	.long	.Lfunc_begin0
	.byte	16
	.section	.text.seqread256_alloc,"ax",@progbits
                                        // -- End function
	.section	.text.seqread256_init,"ax",@progbits
	.globl	seqread256_init                 // -- Begin function seqread256_init
	.type	seqread256_init,@function
seqread256_init:                        // @seqread256_init
.Lfunc_begin1:
	.loc	3 43 0                          // uPIMulator_frontend/sdk/syslib/seqread.inc:43:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: seqread256_init:cache <- $r0
	//DEBUG_VALUE: seqread256_init:cache <- $r0
	//DEBUG_VALUE: seqread256_init:mram_addr <- $r1
	//DEBUG_VALUE: seqread256_init:mram_addr <- $r1
	//DEBUG_VALUE: seqread256_init:reader <- $r2
	//DEBUG_VALUE: seqread256_init:reader <- $r2
	.cfi_def_cfa_offset 0
	.loc	3 44 24 prologue_end            // uPIMulator_frontend/sdk/syslib/seqread.inc:44:24
	sw r2, 0, r0
	move r3, 67108864
	.loc	3 45 23                         // uPIMulator_frontend/sdk/syslib/seqread.inc:45:23
	sw r2, 4, r3
.Ltmp11:
	//DEBUG_VALUE: seqread256_seek:wram_cache <- $r0
	//DEBUG_VALUE: seqread256_seek:current_addr <- 67108864
	//DEBUG_VALUE: seqread256_seek:target_addr <- $r1
	//DEBUG_VALUE: seqread256_seek:reader <- $r2
	//DEBUG_VALUE: seqread256_seek:mram_addr <- $r1
	.loc	3 62 41                         // uPIMulator_frontend/sdk/syslib/seqread.inc:62:41
	add r3, r1, -67108864
.Ltmp12:
	//DEBUG_VALUE: seqread256_seek:mram_offset <- $r3
	.loc	3 63 9                          // uPIMulator_frontend/sdk/syslib/seqread.inc:63:9
	jltu r3, 256, .LBB1_2
.Ltmp13:
// %bb.1:
	//DEBUG_VALUE: seqread256_seek:mram_offset <- $r3
	//DEBUG_VALUE: seqread256_seek:reader <- $r2
	//DEBUG_VALUE: seqread256_init:reader <- $r2
	//DEBUG_VALUE: seqread256_seek:mram_addr <- $r1
	//DEBUG_VALUE: seqread256_seek:target_addr <- $r1
	//DEBUG_VALUE: seqread256_init:mram_addr <- $r1
	//DEBUG_VALUE: seqread256_seek:wram_cache <- $r0
	//DEBUG_VALUE: seqread256_init:cache <- $r0
	//DEBUG_VALUE: seqread256_seek:current_addr <- 67108864
	.loc	3 64 54                         // uPIMulator_frontend/sdk/syslib/seqread.inc:64:54
	and r4, r1, -256
.Ltmp14:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 512
	//DEBUG_VALUE: mram_read:from <- $r4
	//DEBUG_VALUE: mram_read:to <- $r0
	//DEBUG_VALUE: target_addr_idx_page <- $r4
	.file	4 "/root" "uPIMulator_frontend/sdk/syslib/mram.h"
	.loc	4 35 24                         // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r0, r4, 63
.Ltmp15:
	.loc	3 66 35                         // uPIMulator_frontend/sdk/syslib/seqread.inc:66:35
	and r3, r1, 255
.Ltmp16:
	//DEBUG_VALUE: seqread256_seek:mram_offset <- $r3
	.loc	3 67 27                         // uPIMulator_frontend/sdk/syslib/seqread.inc:67:27
	sw r2, 4, r4
.Ltmp17:
.LBB1_2:
	//DEBUG_VALUE: seqread256_seek:mram_offset <- $r3
	//DEBUG_VALUE: seqread256_seek:reader <- $r2
	//DEBUG_VALUE: seqread256_init:reader <- $r2
	//DEBUG_VALUE: seqread256_seek:mram_addr <- $r1
	//DEBUG_VALUE: seqread256_seek:target_addr <- $r1
	//DEBUG_VALUE: seqread256_init:mram_addr <- $r1
	//DEBUG_VALUE: seqread256_seek:wram_cache <- $r0
	//DEBUG_VALUE: seqread256_init:cache <- $r0
	//DEBUG_VALUE: seqread256_seek:current_addr <- 67108864
	//DEBUG_VALUE: seqread256_seek:mram_offset <- $r3
	.loc	3 69 33                         // uPIMulator_frontend/sdk/syslib/seqread.inc:69:33
	add r0, r3, r0
.Ltmp18:
	.loc	3 47 5                          // uPIMulator_frontend/sdk/syslib/seqread.inc:47:5
	jump r23
.Ltmp19:
.Lfunc_end1:
	.size	seqread256_init, .Lfunc_end1-seqread256_init
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.seqread256_init
	.long	.Lfunc_begin1
	.byte	0
	.section	.text.seqread256_init,"ax",@progbits
                                        // -- End function
	.section	.text.seqread256_seek,"ax",@progbits
	.globl	seqread256_seek                 // -- Begin function seqread256_seek
	.type	seqread256_seek,@function
seqread256_seek:                        // @seqread256_seek
.Lfunc_begin2:
	.loc	3 58 0                          // uPIMulator_frontend/sdk/syslib/seqread.inc:58:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: seqread256_seek:mram_addr <- $r0
	//DEBUG_VALUE: seqread256_seek:reader <- $r1
	//DEBUG_VALUE: seqread256_seek:reader <- $r1
	.cfi_def_cfa_offset 0
	.loc	3 60 49 prologue_end            // uPIMulator_frontend/sdk/syslib/seqread.inc:60:49
	lw r3, r1, 4
.Ltmp20:
	//DEBUG_VALUE: seqread256_seek:current_addr <- $r3
	.loc	3 61 47                         // uPIMulator_frontend/sdk/syslib/seqread.inc:61:47
	lw r2, r1, 0
.Ltmp21:
	//DEBUG_VALUE: seqread256_seek:target_addr <- $r0
	//DEBUG_VALUE: seqread256_seek:wram_cache <- $r2
	//DEBUG_VALUE: seqread256_seek:mram_addr <- $r0
	.loc	3 62 41                         // uPIMulator_frontend/sdk/syslib/seqread.inc:62:41
	sub r3, r0, r3
.Ltmp22:
	//DEBUG_VALUE: seqread256_seek:mram_offset <- $r3
	.loc	3 63 9                          // uPIMulator_frontend/sdk/syslib/seqread.inc:63:9
	jltu r3, 256, .LBB2_2
.Ltmp23:
// %bb.1:
	//DEBUG_VALUE: seqread256_seek:mram_offset <- $r3
	//DEBUG_VALUE: seqread256_seek:wram_cache <- $r2
	//DEBUG_VALUE: seqread256_seek:reader <- $r1
	//DEBUG_VALUE: seqread256_seek:target_addr <- $r0
	//DEBUG_VALUE: seqread256_seek:mram_addr <- $r0
	.loc	3 64 54                         // uPIMulator_frontend/sdk/syslib/seqread.inc:64:54
	and r4, r0, -256
.Ltmp24:
	//DEBUG_VALUE: mram_read:nb_of_bytes <- 512
	//DEBUG_VALUE: mram_read:from <- $r4
	//DEBUG_VALUE: mram_read:to <- $r2
	//DEBUG_VALUE: target_addr_idx_page <- $r4
	.loc	4 35 24                         // uPIMulator_frontend/sdk/syslib/mram.h:35:24
	ldma r2, r4, 63
.Ltmp25:
	.loc	3 66 35                         // uPIMulator_frontend/sdk/syslib/seqread.inc:66:35
	and r3, r0, 255
.Ltmp26:
	//DEBUG_VALUE: seqread256_seek:mram_offset <- $r3
	.loc	3 67 27                         // uPIMulator_frontend/sdk/syslib/seqread.inc:67:27
	sw r1, 4, r4
.Ltmp27:
.LBB2_2:
	//DEBUG_VALUE: seqread256_seek:mram_offset <- $r3
	//DEBUG_VALUE: seqread256_seek:wram_cache <- $r2
	//DEBUG_VALUE: seqread256_seek:reader <- $r1
	//DEBUG_VALUE: seqread256_seek:target_addr <- $r0
	//DEBUG_VALUE: seqread256_seek:mram_addr <- $r0
	//DEBUG_VALUE: seqread256_seek:mram_offset <- $r3
	.loc	3 69 33                         // uPIMulator_frontend/sdk/syslib/seqread.inc:69:33
	add r0, r3, r2
.Ltmp28:
	.loc	3 69 5 is_stmt 0                // uPIMulator_frontend/sdk/syslib/seqread.inc:69:5
	jump r23
.Ltmp29:
.Lfunc_end2:
	.size	seqread256_seek, .Lfunc_end2-seqread256_seek
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.seqread256_seek
	.long	.Lfunc_begin2
	.byte	0
	.section	.text.seqread256_seek,"ax",@progbits
                                        // -- End function
	.section	.text.seqread256_get,"ax",@progbits
	.globl	seqread256_get                  // -- Begin function seqread256_get
	.type	seqread256_get,@function
seqread256_get:                         // @seqread256_get
.Lfunc_begin3:
	.loc	3 52 0 is_stmt 1                // uPIMulator_frontend/sdk/syslib/seqread.inc:52:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: seqread256_get:ptr <- $r0
	//DEBUG_VALUE: seqread256_get:ptr <- $r0
	//DEBUG_VALUE: seqread256_get:inc <- $r1
	//DEBUG_VALUE: seqread256_get:inc <- $r1
	//DEBUG_VALUE: seqread256_get:reader <- $r2
	//DEBUG_VALUE: seqread256_get:reader <- $r2
	.cfi_def_cfa_offset 0
	.loc	3 53 20 prologue_end            // uPIMulator_frontend/sdk/syslib/seqread.inc:53:20
	add r0, r0, r1, nc8, .LBB3_2
.Ltmp30:
// %bb.1:
	//DEBUG_VALUE: seqread256_get:reader <- $r2
	//DEBUG_VALUE: seqread256_get:inc <- $r1
	//DEBUG_VALUE: seqread256_get:ptr <- $r0
	lw r1, r2, 4
.Ltmp31:
	add r1, r1, 256
	sw r2, 4, r1
	lw r2, r2, 0
.Ltmp32:
	ldma r2, r1, 63
	add r0, r0, 4294967040
.Ltmp33:
.LBB3_2:
	.loc	3 53 5 is_stmt 0                // uPIMulator_frontend/sdk/syslib/seqread.inc:53:5
	jump r23
.Ltmp34:
.Lfunc_end3:
	.size	seqread256_get, .Lfunc_end3-seqread256_get
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.seqread256_get
	.long	.Lfunc_begin3
	.byte	0
	.section	.text.seqread256_get,"ax",@progbits
                                        // -- End function
	.section	.text.seqread256_tell,"ax",@progbits
	.globl	seqread256_tell                 // -- Begin function seqread256_tell
	.type	seqread256_tell,@function
seqread256_tell:                        // @seqread256_tell
.Lfunc_begin4:
	.loc	3 74 0 is_stmt 1                // uPIMulator_frontend/sdk/syslib/seqread.inc:74:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: seqread256_tell:ptr <- $r0
	//DEBUG_VALUE: seqread256_tell:reader <- $r1
	//DEBUG_VALUE: seqread256_tell:reader <- $r1
	.cfi_def_cfa_offset 0
	.loc	3 75 51 prologue_end            // uPIMulator_frontend/sdk/syslib/seqread.inc:75:51
	lw r1, r1, 4
.Ltmp35:
	//DEBUG_VALUE: seqread256_tell:ptr <- $r0
	.loc	3 75 79 is_stmt 0               // uPIMulator_frontend/sdk/syslib/seqread.inc:75:79
	and r0, r0, 255
.Ltmp36:
	.loc	3 75 61                         // uPIMulator_frontend/sdk/syslib/seqread.inc:75:61
	add r0, r1, r0
	.loc	3 75 5                          // uPIMulator_frontend/sdk/syslib/seqread.inc:75:5
	jump r23
.Ltmp37:
.Lfunc_end4:
	.size	seqread256_tell, .Lfunc_end4-seqread256_tell
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.seqread256_tell
	.long	.Lfunc_begin4
	.byte	0
	.section	.text.seqread256_tell,"ax",@progbits
                                        // -- End function
	.file	5 "/root" "uPIMulator_frontend/sdk/stdlib/stddef.h"
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp2-.Lfunc_begin0
	.long	.Ltmp4-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc1:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp9-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	94                              // DW_OP_reg14
	.long	0
	.long	0
.Ldebug_loc2:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp5-.Lfunc_begin0
	.long	.Ltmp8-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc3:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Lfunc_begin1-.Lfunc_begin1
	.long	.Ltmp18-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc4:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp12-.Lfunc_begin1
	.long	.Lfunc_end1-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc5:
	.long	-1
	.long	.Lfunc_begin1                   //   base address
	.long	.Ltmp14-.Lfunc_begin1
	.long	.Ltmp17-.Lfunc_begin1
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	0
	.long	0
.Ldebug_loc6:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Lfunc_begin2-.Lfunc_begin2
	.long	.Ltmp28-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc7:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp20-.Lfunc_begin2
	.long	.Ltmp22-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc8:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp21-.Lfunc_begin2
	.long	.Ltmp28-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc9:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp21-.Lfunc_begin2
	.long	.Lfunc_end2-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc10:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp22-.Lfunc_begin2
	.long	.Lfunc_end2-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc11:
	.long	-1
	.long	.Lfunc_begin2                   //   base address
	.long	.Ltmp24-.Lfunc_begin2
	.long	.Ltmp27-.Lfunc_begin2
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	0
	.long	0
.Ldebug_loc12:
	.long	-1
	.long	.Lfunc_begin3                   //   base address
	.long	.Lfunc_begin3-.Lfunc_begin3
	.long	.Ltmp33-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc13:
	.long	-1
	.long	.Lfunc_begin3                   //   base address
	.long	.Lfunc_begin3-.Lfunc_begin3
	.long	.Ltmp31-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc14:
	.long	-1
	.long	.Lfunc_begin3                   //   base address
	.long	.Lfunc_begin3-.Lfunc_begin3
	.long	.Ltmp32-.Lfunc_begin3
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc15:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Lfunc_begin4-.Lfunc_begin4
	.long	.Ltmp36-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc16:
	.long	-1
	.long	.Lfunc_begin4                   //   base address
	.long	.Lfunc_begin4-.Lfunc_begin4
	.long	.Ltmp35-.Lfunc_begin4
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.ascii	"\211\202\001"                  // DW_TAG_GNU_call_site
	.byte	0                               // DW_CHILDREN_no
	.ascii	"\223B"                         // DW_AT_GNU_call_site_target
	.byte	24                              // DW_FORM_exprloc
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	11                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	12                              // Abbreviation Code
	.byte	15                              // DW_TAG_pointer_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	13                              // Abbreviation Code
	.byte	19                              // DW_TAG_structure_type
	.byte	1                               // DW_CHILDREN_yes
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	14                              // Abbreviation Code
	.byte	13                              // DW_TAG_member
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	56                              // DW_AT_data_member_location
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	15                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	16                              // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	17                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	18                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	19                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	1                               // DW_CHILDREN_yes
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	20                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	21                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	22                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	28                              // DW_AT_const_value
	.byte	15                              // DW_FORM_udata
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	23                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	24                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	25                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	28                              // DW_AT_const_value
	.byte	15                              // DW_FORM_udata
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	26                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	27                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x2fe DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	0                               // DW_AT_low_pc
	.long	.Ldebug_ranges0                 // DW_AT_ranges
	.byte	2                               // Abbrev [2] 0x26:0xb DW_TAG_typedef
	.long	49                              // DW_AT_type
	.long	.Linfo_string5                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	57                              // DW_AT_decl_line
	.byte	2                               // Abbrev [2] 0x31:0xb DW_TAG_typedef
	.long	60                              // DW_AT_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	144                             // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x3c:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x43:0x1 DW_TAG_pointer_type
	.byte	5                               // Abbrev [5] 0x44:0x4a DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string19                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	25                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	38                              // DW_AT_type
                                        // DW_AT_external
	.byte	6                               // Abbrev [6] 0x59:0xf DW_TAG_variable
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string23                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	29                              // DW_AT_decl_line
	.long	60                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0x68:0xf DW_TAG_variable
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string24                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	30                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	6                               // Abbrev [6] 0x77:0xf DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string25                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	31                              // DW_AT_decl_line
	.long	754                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0x86:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp6                          // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	8                               // Abbrev [8] 0x8e:0x5c DW_TAG_subprogram
	.long	.Linfo_string6                  // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	57                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	67                              // DW_AT_type
                                        // DW_AT_external
	.byte	1                               // DW_AT_inline
	.byte	9                               // Abbrev [9] 0x9a:0xb DW_TAG_formal_parameter
	.long	.Linfo_string7                  // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	57                              // DW_AT_decl_line
	.long	67                              // DW_AT_type
	.byte	9                               // Abbrev [9] 0xa5:0xb DW_TAG_formal_parameter
	.long	.Linfo_string8                  // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	57                              // DW_AT_decl_line
	.long	234                             // DW_AT_type
	.byte	10                              // Abbrev [10] 0xb0:0xb DW_TAG_variable
	.long	.Linfo_string9                  // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	61                              // DW_AT_decl_line
	.long	49                              // DW_AT_type
	.byte	10                              // Abbrev [10] 0xbb:0xb DW_TAG_variable
	.long	.Linfo_string11                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	60                              // DW_AT_decl_line
	.long	49                              // DW_AT_type
	.byte	10                              // Abbrev [10] 0xc6:0xb DW_TAG_variable
	.long	.Linfo_string12                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	59                              // DW_AT_decl_line
	.long	49                              // DW_AT_type
	.byte	10                              // Abbrev [10] 0xd1:0xb DW_TAG_variable
	.long	.Linfo_string13                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	62                              // DW_AT_decl_line
	.long	49                              // DW_AT_type
	.byte	11                              // Abbrev [11] 0xdc:0xd DW_TAG_lexical_block
	.byte	10                              // Abbrev [10] 0xdd:0xb DW_TAG_variable
	.long	.Linfo_string14                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	64                              // DW_AT_decl_line
	.long	49                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	12                              // Abbrev [12] 0xea:0x5 DW_TAG_pointer_type
	.long	239                             // DW_AT_type
	.byte	2                               // Abbrev [2] 0xef:0xb DW_TAG_typedef
	.long	250                             // DW_AT_type
	.long	.Linfo_string10                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	66                              // DW_AT_decl_line
	.byte	13                              // Abbrev [13] 0xfa:0x1d DW_TAG_structure_type
	.byte	8                               // DW_AT_byte_size
	.byte	2                               // DW_AT_decl_file
	.byte	63                              // DW_AT_decl_line
	.byte	14                              // Abbrev [14] 0xfe:0xc DW_TAG_member
	.long	.Linfo_string9                  // DW_AT_name
	.long	38                              // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	64                              // DW_AT_decl_line
	.byte	0                               // DW_AT_data_member_location
	.byte	14                              // Abbrev [14] 0x10a:0xc DW_TAG_member
	.long	.Linfo_string7                  // DW_AT_name
	.long	49                              // DW_AT_type
	.byte	2                               // DW_AT_decl_file
	.byte	65                              // DW_AT_decl_line
	.byte	4                               // DW_AT_data_member_location
	.byte	0                               // End Of Children Mark
	.byte	15                              // Abbrev [15] 0x117:0x2a DW_TAG_subprogram
	.long	.Linfo_string15                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	33                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.byte	1                               // DW_AT_inline
	.byte	9                               // Abbrev [9] 0x11f:0xb DW_TAG_formal_parameter
	.long	.Linfo_string16                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	33                              // DW_AT_decl_line
	.long	321                             // DW_AT_type
	.byte	9                               // Abbrev [9] 0x12a:0xb DW_TAG_formal_parameter
	.long	.Linfo_string17                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	33                              // DW_AT_decl_line
	.long	67                              // DW_AT_type
	.byte	9                               // Abbrev [9] 0x135:0xb DW_TAG_formal_parameter
	.long	.Linfo_string18                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	33                              // DW_AT_decl_line
	.long	60                              // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	12                              // Abbrev [12] 0x141:0x5 DW_TAG_pointer_type
	.long	326                             // DW_AT_type
	.byte	16                              // Abbrev [16] 0x146:0x1 DW_TAG_const_type
	.byte	5                               // Abbrev [5] 0x147:0xb7 DW_TAG_subprogram
	.long	.Lfunc_begin1                   // DW_AT_low_pc
	.long	.Lfunc_end1-.Lfunc_begin1       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string20                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	42                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	67                              // DW_AT_type
                                        // DW_AT_external
	.byte	17                              // Abbrev [17] 0x15c:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string27                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	42                              // DW_AT_decl_line
	.long	38                              // DW_AT_type
	.byte	18                              // Abbrev [18] 0x16b:0xd DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	.Linfo_string7                  // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	42                              // DW_AT_decl_line
	.long	67                              // DW_AT_type
	.byte	18                              // Abbrev [18] 0x178:0xd DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	82
	.long	.Linfo_string8                  // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	42                              // DW_AT_decl_line
	.long	234                             // DW_AT_type
	.byte	19                              // Abbrev [19] 0x185:0x78 DW_TAG_inlined_subroutine
	.long	142                             // DW_AT_abstract_origin
	.long	.Ltmp11                         // DW_AT_low_pc
	.long	.Ltmp18-.Ltmp11                 // DW_AT_high_pc
	.byte	3                               // DW_AT_call_file
	.byte	47                              // DW_AT_call_line
	.byte	12                              // DW_AT_call_column
	.byte	20                              // Abbrev [20] 0x195:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	154                             // DW_AT_abstract_origin
	.byte	20                              // Abbrev [20] 0x19c:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	82
	.long	165                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x1a3:0x7 DW_TAG_variable
	.byte	1                               // DW_AT_location
	.byte	80
	.long	176                             // DW_AT_abstract_origin
	.byte	22                              // Abbrev [22] 0x1aa:0x9 DW_TAG_variable
	.ascii	"\200\200\200 "                 // DW_AT_const_value
	.long	187                             // DW_AT_abstract_origin
	.byte	21                              // Abbrev [21] 0x1b3:0x7 DW_TAG_variable
	.byte	1                               // DW_AT_location
	.byte	81
	.long	198                             // DW_AT_abstract_origin
	.byte	23                              // Abbrev [23] 0x1ba:0x9 DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	209                             // DW_AT_abstract_origin
	.byte	24                              // Abbrev [24] 0x1c3:0x39 DW_TAG_lexical_block
	.long	.Ltmp13                         // DW_AT_low_pc
	.long	.Ltmp17-.Ltmp13                 // DW_AT_high_pc
	.byte	23                              // Abbrev [23] 0x1cc:0x9 DW_TAG_variable
	.long	.Ldebug_loc5                    // DW_AT_location
	.long	221                             // DW_AT_abstract_origin
	.byte	19                              // Abbrev [19] 0x1d5:0x26 DW_TAG_inlined_subroutine
	.long	279                             // DW_AT_abstract_origin
	.long	.Ltmp14                         // DW_AT_low_pc
	.long	.Ltmp15-.Ltmp14                 // DW_AT_high_pc
	.byte	3                               // DW_AT_call_file
	.byte	65                              // DW_AT_call_line
	.byte	9                               // DW_AT_call_column
	.byte	20                              // Abbrev [20] 0x1e5:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	84
	.long	287                             // DW_AT_abstract_origin
	.byte	20                              // Abbrev [20] 0x1ec:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	298                             // DW_AT_abstract_origin
	.byte	25                              // Abbrev [25] 0x1f3:0x7 DW_TAG_formal_parameter
	.ascii	"\200\004"                      // DW_AT_const_value
	.long	309                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	26                              // Abbrev [26] 0x1fe:0x7d DW_TAG_subprogram
	.long	.Lfunc_begin2                   // DW_AT_low_pc
	.long	.Lfunc_end2-.Lfunc_begin2       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	142                             // DW_AT_abstract_origin
	.byte	27                              // Abbrev [27] 0x20d:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc6                    // DW_AT_location
	.long	154                             // DW_AT_abstract_origin
	.byte	20                              // Abbrev [20] 0x216:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	165                             // DW_AT_abstract_origin
	.byte	23                              // Abbrev [23] 0x21d:0x9 DW_TAG_variable
	.long	.Ldebug_loc7                    // DW_AT_location
	.long	187                             // DW_AT_abstract_origin
	.byte	23                              // Abbrev [23] 0x226:0x9 DW_TAG_variable
	.long	.Ldebug_loc8                    // DW_AT_location
	.long	198                             // DW_AT_abstract_origin
	.byte	23                              // Abbrev [23] 0x22f:0x9 DW_TAG_variable
	.long	.Ldebug_loc9                    // DW_AT_location
	.long	176                             // DW_AT_abstract_origin
	.byte	23                              // Abbrev [23] 0x238:0x9 DW_TAG_variable
	.long	.Ldebug_loc10                   // DW_AT_location
	.long	209                             // DW_AT_abstract_origin
	.byte	24                              // Abbrev [24] 0x241:0x39 DW_TAG_lexical_block
	.long	.Ltmp23                         // DW_AT_low_pc
	.long	.Ltmp27-.Ltmp23                 // DW_AT_high_pc
	.byte	23                              // Abbrev [23] 0x24a:0x9 DW_TAG_variable
	.long	.Ldebug_loc11                   // DW_AT_location
	.long	221                             // DW_AT_abstract_origin
	.byte	19                              // Abbrev [19] 0x253:0x26 DW_TAG_inlined_subroutine
	.long	279                             // DW_AT_abstract_origin
	.long	.Ltmp24                         // DW_AT_low_pc
	.long	.Ltmp25-.Ltmp24                 // DW_AT_high_pc
	.byte	3                               // DW_AT_call_file
	.byte	65                              // DW_AT_call_line
	.byte	9                               // DW_AT_call_column
	.byte	20                              // Abbrev [20] 0x263:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	84
	.long	287                             // DW_AT_abstract_origin
	.byte	20                              // Abbrev [20] 0x26a:0x7 DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	82
	.long	298                             // DW_AT_abstract_origin
	.byte	25                              // Abbrev [25] 0x271:0x7 DW_TAG_formal_parameter
	.ascii	"\200\004"                      // DW_AT_const_value
	.long	309                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	5                               // Abbrev [5] 0x27b:0x43 DW_TAG_subprogram
	.long	.Lfunc_begin3                   // DW_AT_low_pc
	.long	.Lfunc_end3-.Lfunc_begin3       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string21                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	51                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	67                              // DW_AT_type
                                        // DW_AT_external
	.byte	17                              // Abbrev [17] 0x290:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc12                   // DW_AT_location
	.long	.Linfo_string28                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	51                              // DW_AT_decl_line
	.long	67                              // DW_AT_type
	.byte	17                              // Abbrev [17] 0x29f:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc13                   // DW_AT_location
	.long	.Linfo_string29                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	51                              // DW_AT_decl_line
	.long	765                             // DW_AT_type
	.byte	17                              // Abbrev [17] 0x2ae:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc14                   // DW_AT_location
	.long	.Linfo_string8                  // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	51                              // DW_AT_decl_line
	.long	234                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	5                               // Abbrev [5] 0x2be:0x34 DW_TAG_subprogram
	.long	.Lfunc_begin4                   // DW_AT_low_pc
	.long	.Lfunc_end4-.Lfunc_begin4       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string22                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	73                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	67                              // DW_AT_type
                                        // DW_AT_external
	.byte	17                              // Abbrev [17] 0x2d3:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc15                   // DW_AT_location
	.long	.Linfo_string28                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	73                              // DW_AT_decl_line
	.long	67                              // DW_AT_type
	.byte	17                              // Abbrev [17] 0x2e2:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc16                   // DW_AT_location
	.long	.Linfo_string8                  // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	73                              // DW_AT_decl_line
	.long	234                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	2                               // Abbrev [2] 0x2f2:0xb DW_TAG_typedef
	.long	60                              // DW_AT_type
	.long	.Linfo_string26                 // DW_AT_name
	.byte	5                               // DW_AT_decl_file
	.byte	26                              // DW_AT_decl_line
	.byte	2                               // Abbrev [2] 0x2fd:0xb DW_TAG_typedef
	.long	60                              // DW_AT_type
	.long	.Linfo_string30                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	48                              // DW_AT_decl_line
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_ranges,"",@progbits
.Ldebug_ranges0:
	.long	.Lfunc_begin0
	.long	.Lfunc_end0
	.long	.Lfunc_begin1
	.long	.Lfunc_end1
	.long	.Lfunc_begin2
	.long	.Lfunc_end2
	.long	.Lfunc_begin3
	.long	.Lfunc_end3
	.long	.Lfunc_begin4
	.long	.Lfunc_end4
	.long	0
	.long	0
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/seqread256.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=156
.Linfo_string3:
	.asciz	"unsigned int"                  // string offset=177
.Linfo_string4:
	.asciz	"uintptr_t"                     // string offset=190
.Linfo_string5:
	.asciz	"seqreader_buffer_t"            // string offset=200
.Linfo_string6:
	.asciz	"seqread256_seek"               // string offset=219
.Linfo_string7:
	.asciz	"mram_addr"                     // string offset=235
.Linfo_string8:
	.asciz	"reader"                        // string offset=245
.Linfo_string9:
	.asciz	"wram_cache"                    // string offset=252
.Linfo_string10:
	.asciz	"seqreader_t"                   // string offset=263
.Linfo_string11:
	.asciz	"current_addr"                  // string offset=275
.Linfo_string12:
	.asciz	"target_addr"                   // string offset=288
.Linfo_string13:
	.asciz	"mram_offset"                   // string offset=300
.Linfo_string14:
	.asciz	"target_addr_idx_page"          // string offset=312
.Linfo_string15:
	.asciz	"mram_read"                     // string offset=333
.Linfo_string16:
	.asciz	"from"                          // string offset=343
.Linfo_string17:
	.asciz	"to"                            // string offset=348
.Linfo_string18:
	.asciz	"nb_of_bytes"                   // string offset=351
.Linfo_string19:
	.asciz	"seqread256_alloc"              // string offset=363
.Linfo_string20:
	.asciz	"seqread256_init"               // string offset=380
.Linfo_string21:
	.asciz	"seqread256_get"                // string offset=396
.Linfo_string22:
	.asciz	"seqread256_tell"               // string offset=411
.Linfo_string23:
	.asciz	"heap_pointer"                  // string offset=427
.Linfo_string24:
	.asciz	"pointer"                       // string offset=440
.Linfo_string25:
	.asciz	"size"                          // string offset=448
.Linfo_string26:
	.asciz	"size_t"                        // string offset=453
.Linfo_string27:
	.asciz	"cache"                         // string offset=460
.Linfo_string28:
	.asciz	"ptr"                           // string offset=466
.Linfo_string29:
	.asciz	"inc"                           // string offset=470
.Linfo_string30:
	.asciz	"uint32_t"                      // string offset=474
	.addrsig
	.addrsig_sym __atomic_bit___heap_pointer
	.addrsig_sym __sys_heap_pointer
	.section	.debug_line,"",@progbits
.Lline_table_start0:
