	.text
	.file	"truncsfhf2.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/syslib/fp_trunc.h"
	.file	2 "/root" "uPIMulator_frontend/sdk/stdlib/stdint.h"
	.section	.text.__truncsfhf2,"ax",@progbits
	.globl	__truncsfhf2                    // -- Begin function __truncsfhf2
	.type	__truncsfhf2,@function
__truncsfhf2:                           // @__truncsfhf2
.Lfunc_begin0:
	.file	3 "/root" "uPIMulator_frontend/sdk/syslib/truncsfhf2.c"
	.loc	3 18 0                          // uPIMulator_frontend/sdk/syslib/truncsfhf2.c:18:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __truncsfhf2:a <- $r0
	//DEBUG_VALUE: __truncsfhf2:a <- $r0
	//DEBUG_VALUE: __truncXfYf2__:a <- $r0
	//DEBUG_VALUE: __truncXfYf2__:a <- $r0
	//DEBUG_VALUE: srcToRep:x <- $r0
	//DEBUG_VALUE: srcToRep:x <- $r0
	.cfi_def_cfa_offset 0
	//DEBUG_VALUE: srcToRep:rep <- $r0
	//DEBUG_VALUE: srcToRep:rep <- $r0
	//DEBUG_VALUE: __truncXfYf2__:srcBits <- 32
	//DEBUG_VALUE: __truncXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __truncXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __truncXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __truncXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __truncXfYf2__:srcSignificandMask <- 8388607
	//DEBUG_VALUE: __truncXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __truncXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __truncXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __truncXfYf2__:roundMask <- 8191
	//DEBUG_VALUE: __truncXfYf2__:halfway <- 4096
	//DEBUG_VALUE: __truncXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __truncXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __truncXfYf2__:dstBits <- 16
	//DEBUG_VALUE: __truncXfYf2__:dstExpBits <- 5
	//DEBUG_VALUE: __truncXfYf2__:dstInfExp <- 31
	//DEBUG_VALUE: __truncXfYf2__:dstExpBias <- 15
	//DEBUG_VALUE: __truncXfYf2__:underflowExponent <- 113
	//DEBUG_VALUE: __truncXfYf2__:overflowExponent <- 143
	//DEBUG_VALUE: __truncXfYf2__:underflow <- 947912704
	//DEBUG_VALUE: __truncXfYf2__:overflow <- 1199570944
	//DEBUG_VALUE: __truncXfYf2__:dstQNaN <- 512
	//DEBUG_VALUE: __truncXfYf2__:dstNaNCode <- 511
	//DEBUG_VALUE: __truncXfYf2__:aRep <- $r0
	.file	4 "/root" "uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc"
	.loc	4 75 33 prologue_end            // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:75:33
	and r2, r0, 2147483647
.Ltmp0:
	//DEBUG_VALUE: __truncXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:aAbs <- [DW_OP_constu 2147483647, DW_OP_and, DW_OP_stack_value] $r0
	.loc	4 79 14                         // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:79:14
	add r1, r2, -947912704
	.loc	4 79 33 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:79:33
	add r3, r2, -1199570944
.Ltmp1:
	.loc	4 79 9                          // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:79:9
	jgeu r1, r3, .LBB0_5
.Ltmp2:
// %bb.1:
	//DEBUG_VALUE: __truncXfYf2__:aAbs <- [DW_OP_constu 2147483647, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __truncXfYf2__:a <- $r0
	//DEBUG_VALUE: __truncsfhf2:a <- $r0
	//DEBUG_VALUE: __truncXfYf2__:dstNaNCode <- 511
	//DEBUG_VALUE: __truncXfYf2__:dstQNaN <- 512
	//DEBUG_VALUE: __truncXfYf2__:overflow <- 1199570944
	//DEBUG_VALUE: __truncXfYf2__:underflow <- 947912704
	//DEBUG_VALUE: __truncXfYf2__:overflowExponent <- 143
	//DEBUG_VALUE: __truncXfYf2__:underflowExponent <- 113
	//DEBUG_VALUE: __truncXfYf2__:dstExpBias <- 15
	//DEBUG_VALUE: __truncXfYf2__:dstInfExp <- 31
	//DEBUG_VALUE: __truncXfYf2__:dstExpBits <- 5
	//DEBUG_VALUE: __truncXfYf2__:dstBits <- 16
	//DEBUG_VALUE: __truncXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __truncXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __truncXfYf2__:halfway <- 4096
	//DEBUG_VALUE: __truncXfYf2__:roundMask <- 8191
	//DEBUG_VALUE: __truncXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __truncXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __truncXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __truncXfYf2__:srcSignificandMask <- 8388607
	//DEBUG_VALUE: __truncXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __truncXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __truncXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __truncXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __truncXfYf2__:srcBits <- 32
	.loc	4 83 26 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:83:26
	lsr r2, r0, 13
	.loc	4 86 42                         // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:86:42
	and r3, r0, 8191
.Ltmp3:
	//DEBUG_VALUE: roundBits <- $r3
	.loc	4 0 42 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:0:42
	move r4, 4097
	.loc	4 84 19 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:84:19
	and r1, r2, 65535
.Ltmp4:
	//DEBUG_VALUE: __truncXfYf2__:absResult <- [DW_OP_LLVM_convert 32 7, DW_OP_LLVM_convert 16 7, DW_OP_stack_value] undef
	.loc	4 88 13                         // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:88:13
	jltu r3, r4, .LBB0_3
.Ltmp5:
// %bb.2:
	//DEBUG_VALUE: roundBits <- $r3
	//DEBUG_VALUE: __truncXfYf2__:aAbs <- [DW_OP_constu 2147483647, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __truncXfYf2__:a <- $r0
	//DEBUG_VALUE: __truncsfhf2:a <- $r0
	//DEBUG_VALUE: __truncXfYf2__:dstNaNCode <- 511
	//DEBUG_VALUE: __truncXfYf2__:dstQNaN <- 512
	//DEBUG_VALUE: __truncXfYf2__:overflow <- 1199570944
	//DEBUG_VALUE: __truncXfYf2__:underflow <- 947912704
	//DEBUG_VALUE: __truncXfYf2__:overflowExponent <- 143
	//DEBUG_VALUE: __truncXfYf2__:underflowExponent <- 113
	//DEBUG_VALUE: __truncXfYf2__:dstExpBias <- 15
	//DEBUG_VALUE: __truncXfYf2__:dstInfExp <- 31
	//DEBUG_VALUE: __truncXfYf2__:dstExpBits <- 5
	//DEBUG_VALUE: __truncXfYf2__:dstBits <- 16
	//DEBUG_VALUE: __truncXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __truncXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __truncXfYf2__:halfway <- 4096
	//DEBUG_VALUE: __truncXfYf2__:roundMask <- 8191
	//DEBUG_VALUE: __truncXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __truncXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __truncXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __truncXfYf2__:srcSignificandMask <- 8388607
	//DEBUG_VALUE: __truncXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __truncXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __truncXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __truncXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __truncXfYf2__:srcBits <- 32
	.loc	4 89 22                         // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:89:22
	add r1, r1, -114687
.Ltmp6:
	//DEBUG_VALUE: __truncXfYf2__:absResult <- [DW_OP_LLVM_convert 32 7, DW_OP_LLVM_convert 16 7, DW_OP_plus_uconst 1, DW_OP_stack_value] $r1
	.loc	4 0 22 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:0:22
	jump .LBB0_14
.Ltmp7:
.LBB0_5:
	//DEBUG_VALUE: __truncXfYf2__:aAbs <- [DW_OP_constu 2147483647, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __truncXfYf2__:a <- $r0
	//DEBUG_VALUE: __truncsfhf2:a <- $r0
	//DEBUG_VALUE: __truncXfYf2__:dstNaNCode <- 511
	//DEBUG_VALUE: __truncXfYf2__:dstQNaN <- 512
	//DEBUG_VALUE: __truncXfYf2__:overflow <- 1199570944
	//DEBUG_VALUE: __truncXfYf2__:underflow <- 947912704
	//DEBUG_VALUE: __truncXfYf2__:overflowExponent <- 143
	//DEBUG_VALUE: __truncXfYf2__:underflowExponent <- 113
	//DEBUG_VALUE: __truncXfYf2__:dstExpBias <- 15
	//DEBUG_VALUE: __truncXfYf2__:dstInfExp <- 31
	//DEBUG_VALUE: __truncXfYf2__:dstExpBits <- 5
	//DEBUG_VALUE: __truncXfYf2__:dstBits <- 16
	//DEBUG_VALUE: __truncXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __truncXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __truncXfYf2__:halfway <- 4096
	//DEBUG_VALUE: __truncXfYf2__:roundMask <- 8191
	//DEBUG_VALUE: __truncXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __truncXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __truncXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __truncXfYf2__:srcSignificandMask <- 8388607
	//DEBUG_VALUE: __truncXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __truncXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __truncXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __truncXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __truncXfYf2__:srcBits <- 32
	move r1, 2139095041
	.loc	4 94 14 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:94:14
	jltu r2, r1, .LBB0_7
.Ltmp8:
// %bb.6:
	//DEBUG_VALUE: __truncXfYf2__:aAbs <- [DW_OP_constu 2147483647, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __truncXfYf2__:a <- $r0
	//DEBUG_VALUE: __truncsfhf2:a <- $r0
	//DEBUG_VALUE: __truncXfYf2__:dstNaNCode <- 511
	//DEBUG_VALUE: __truncXfYf2__:dstQNaN <- 512
	//DEBUG_VALUE: __truncXfYf2__:overflow <- 1199570944
	//DEBUG_VALUE: __truncXfYf2__:underflow <- 947912704
	//DEBUG_VALUE: __truncXfYf2__:overflowExponent <- 143
	//DEBUG_VALUE: __truncXfYf2__:underflowExponent <- 113
	//DEBUG_VALUE: __truncXfYf2__:dstExpBias <- 15
	//DEBUG_VALUE: __truncXfYf2__:dstInfExp <- 31
	//DEBUG_VALUE: __truncXfYf2__:dstExpBits <- 5
	//DEBUG_VALUE: __truncXfYf2__:dstBits <- 16
	//DEBUG_VALUE: __truncXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __truncXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __truncXfYf2__:halfway <- 4096
	//DEBUG_VALUE: __truncXfYf2__:roundMask <- 8191
	//DEBUG_VALUE: __truncXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __truncXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __truncXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __truncXfYf2__:srcSignificandMask <- 8388607
	//DEBUG_VALUE: __truncXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __truncXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __truncXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __truncXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __truncXfYf2__:srcBits <- 32
	//DEBUG_VALUE: __truncXfYf2__:absResult <- 32256
	.loc	4 100 43                        // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:100:43
	lsr r1, r0, 13
	and r1, r1, 511
	.loc	4 100 19 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:100:19
	or r1, r1, 32256
.Ltmp9:
	//DEBUG_VALUE: __truncXfYf2__:absResult <- [DW_OP_LLVM_convert 32 7, DW_OP_LLVM_convert 16 7, DW_OP_stack_value] $r1
	.loc	4 0 19                          // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:0:19
	jump .LBB0_14
.Ltmp10:
.LBB0_3:
	//DEBUG_VALUE: roundBits <- $r3
	//DEBUG_VALUE: __truncXfYf2__:aAbs <- [DW_OP_constu 2147483647, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __truncXfYf2__:a <- $r0
	//DEBUG_VALUE: __truncsfhf2:a <- $r0
	//DEBUG_VALUE: __truncXfYf2__:dstNaNCode <- 511
	//DEBUG_VALUE: __truncXfYf2__:dstQNaN <- 512
	//DEBUG_VALUE: __truncXfYf2__:overflow <- 1199570944
	//DEBUG_VALUE: __truncXfYf2__:underflow <- 947912704
	//DEBUG_VALUE: __truncXfYf2__:overflowExponent <- 143
	//DEBUG_VALUE: __truncXfYf2__:underflowExponent <- 113
	//DEBUG_VALUE: __truncXfYf2__:dstExpBias <- 15
	//DEBUG_VALUE: __truncXfYf2__:dstInfExp <- 31
	//DEBUG_VALUE: __truncXfYf2__:dstExpBits <- 5
	//DEBUG_VALUE: __truncXfYf2__:dstBits <- 16
	//DEBUG_VALUE: __truncXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __truncXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __truncXfYf2__:halfway <- 4096
	//DEBUG_VALUE: __truncXfYf2__:roundMask <- 8191
	//DEBUG_VALUE: __truncXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __truncXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __truncXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __truncXfYf2__:srcSignificandMask <- 8388607
	//DEBUG_VALUE: __truncXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __truncXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __truncXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __truncXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __truncXfYf2__:srcBits <- 32
	move r4, 4096
	add r1, r1, -114688
.Ltmp11:
	//DEBUG_VALUE: __truncXfYf2__:absResult <- [DW_OP_LLVM_convert 32 7, DW_OP_LLVM_convert 16 7, DW_OP_stack_value] $r1
	.loc	4 91 18 is_stmt 1               // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:91:18
	jneq r3, r4, .LBB0_14
.Ltmp12:
// %bb.4:
	//DEBUG_VALUE: roundBits <- $r3
	//DEBUG_VALUE: __truncXfYf2__:absResult <- [DW_OP_LLVM_convert 32 7, DW_OP_LLVM_convert 16 7, DW_OP_stack_value] $r1
	//DEBUG_VALUE: __truncXfYf2__:aAbs <- [DW_OP_constu 2147483647, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __truncXfYf2__:a <- $r0
	//DEBUG_VALUE: __truncsfhf2:a <- $r0
	//DEBUG_VALUE: __truncXfYf2__:dstNaNCode <- 511
	//DEBUG_VALUE: __truncXfYf2__:dstQNaN <- 512
	//DEBUG_VALUE: __truncXfYf2__:overflow <- 1199570944
	//DEBUG_VALUE: __truncXfYf2__:underflow <- 947912704
	//DEBUG_VALUE: __truncXfYf2__:overflowExponent <- 143
	//DEBUG_VALUE: __truncXfYf2__:underflowExponent <- 113
	//DEBUG_VALUE: __truncXfYf2__:dstExpBias <- 15
	//DEBUG_VALUE: __truncXfYf2__:dstInfExp <- 31
	//DEBUG_VALUE: __truncXfYf2__:dstExpBits <- 5
	//DEBUG_VALUE: __truncXfYf2__:dstBits <- 16
	//DEBUG_VALUE: __truncXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __truncXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __truncXfYf2__:halfway <- 4096
	//DEBUG_VALUE: __truncXfYf2__:roundMask <- 8191
	//DEBUG_VALUE: __truncXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __truncXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __truncXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __truncXfYf2__:srcSignificandMask <- 8388607
	//DEBUG_VALUE: __truncXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __truncXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __truncXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __truncXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __truncXfYf2__:srcBits <- 32
	.loc	4 92 26                         // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:92:26
	and r1, r1, 65535
.Ltmp13:
	.loc	4 92 36 is_stmt 0               // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:92:36
	and r2, r2, 1
.Ltmp14:
.LBB0_13:
	//DEBUG_VALUE: __truncXfYf2__:aAbs <- [DW_OP_constu 2147483647, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __truncXfYf2__:a <- $r0
	//DEBUG_VALUE: __truncsfhf2:a <- $r0
	//DEBUG_VALUE: __truncXfYf2__:dstNaNCode <- 511
	//DEBUG_VALUE: __truncXfYf2__:dstQNaN <- 512
	//DEBUG_VALUE: __truncXfYf2__:overflow <- 1199570944
	//DEBUG_VALUE: __truncXfYf2__:underflow <- 947912704
	//DEBUG_VALUE: __truncXfYf2__:overflowExponent <- 143
	//DEBUG_VALUE: __truncXfYf2__:underflowExponent <- 113
	//DEBUG_VALUE: __truncXfYf2__:dstExpBias <- 15
	//DEBUG_VALUE: __truncXfYf2__:dstInfExp <- 31
	//DEBUG_VALUE: __truncXfYf2__:dstExpBits <- 5
	//DEBUG_VALUE: __truncXfYf2__:dstBits <- 16
	//DEBUG_VALUE: __truncXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __truncXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __truncXfYf2__:halfway <- 4096
	//DEBUG_VALUE: __truncXfYf2__:roundMask <- 8191
	//DEBUG_VALUE: __truncXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __truncXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __truncXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __truncXfYf2__:srcSignificandMask <- 8388607
	//DEBUG_VALUE: __truncXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __truncXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __truncXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __truncXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __truncXfYf2__:srcBits <- 32
	//DEBUG_VALUE: __truncXfYf2__:absResult <- [DW_OP_LLVM_convert 32 7, DW_OP_LLVM_convert 16 7, DW_OP_stack_value] $r1
	.loc	4 0 0                           // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:0:0
	add r1, r1, r2, true, .LBB0_14
.Ltmp15:
.LBB0_7:
	//DEBUG_VALUE: __truncXfYf2__:aAbs <- [DW_OP_constu 2147483647, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __truncXfYf2__:a <- $r0
	//DEBUG_VALUE: __truncsfhf2:a <- $r0
	//DEBUG_VALUE: __truncXfYf2__:dstNaNCode <- 511
	//DEBUG_VALUE: __truncXfYf2__:dstQNaN <- 512
	//DEBUG_VALUE: __truncXfYf2__:overflow <- 1199570944
	//DEBUG_VALUE: __truncXfYf2__:underflow <- 947912704
	//DEBUG_VALUE: __truncXfYf2__:overflowExponent <- 143
	//DEBUG_VALUE: __truncXfYf2__:underflowExponent <- 113
	//DEBUG_VALUE: __truncXfYf2__:dstExpBias <- 15
	//DEBUG_VALUE: __truncXfYf2__:dstInfExp <- 31
	//DEBUG_VALUE: __truncXfYf2__:dstExpBits <- 5
	//DEBUG_VALUE: __truncXfYf2__:dstBits <- 16
	//DEBUG_VALUE: __truncXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __truncXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __truncXfYf2__:halfway <- 4096
	//DEBUG_VALUE: __truncXfYf2__:roundMask <- 8191
	//DEBUG_VALUE: __truncXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __truncXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __truncXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __truncXfYf2__:srcSignificandMask <- 8388607
	//DEBUG_VALUE: __truncXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __truncXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __truncXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __truncXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __truncXfYf2__:srcBits <- 32
	move r1, 31744
.Ltmp16:
	.loc	4 102 14 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:102:14
	lsr r3, r2, 23
	jgtu r3, 142, .LBB0_14
.Ltmp17:
// %bb.8:
	//DEBUG_VALUE: __truncXfYf2__:aAbs <- [DW_OP_constu 2147483647, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __truncXfYf2__:a <- $r0
	//DEBUG_VALUE: __truncsfhf2:a <- $r0
	//DEBUG_VALUE: __truncXfYf2__:dstNaNCode <- 511
	//DEBUG_VALUE: __truncXfYf2__:dstQNaN <- 512
	//DEBUG_VALUE: __truncXfYf2__:overflow <- 1199570944
	//DEBUG_VALUE: __truncXfYf2__:underflow <- 947912704
	//DEBUG_VALUE: __truncXfYf2__:overflowExponent <- 143
	//DEBUG_VALUE: __truncXfYf2__:underflowExponent <- 113
	//DEBUG_VALUE: __truncXfYf2__:dstExpBias <- 15
	//DEBUG_VALUE: __truncXfYf2__:dstInfExp <- 31
	//DEBUG_VALUE: __truncXfYf2__:dstExpBits <- 5
	//DEBUG_VALUE: __truncXfYf2__:dstBits <- 16
	//DEBUG_VALUE: __truncXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __truncXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __truncXfYf2__:halfway <- 4096
	//DEBUG_VALUE: __truncXfYf2__:roundMask <- 8191
	//DEBUG_VALUE: __truncXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __truncXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __truncXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __truncXfYf2__:srcSignificandMask <- 8388607
	//DEBUG_VALUE: __truncXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __truncXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __truncXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __truncXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __truncXfYf2__:srcBits <- 32
	//DEBUG_VALUE: shift <- undef
	//DEBUG_VALUE: significand <- undef
	.loc	4 0 14 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:0:14
	move r1, 0
.Ltmp18:
	//DEBUG_VALUE: aExp <- $r3
	.loc	4 116 13 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:116:13
	lsr r2, r2, 24
	jltu r2, 45, .LBB0_14
.Ltmp19:
// %bb.9:
	//DEBUG_VALUE: aExp <- $r3
	//DEBUG_VALUE: __truncXfYf2__:aAbs <- [DW_OP_constu 2147483647, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __truncXfYf2__:a <- $r0
	//DEBUG_VALUE: __truncsfhf2:a <- $r0
	//DEBUG_VALUE: __truncXfYf2__:dstNaNCode <- 511
	//DEBUG_VALUE: __truncXfYf2__:dstQNaN <- 512
	//DEBUG_VALUE: __truncXfYf2__:overflow <- 1199570944
	//DEBUG_VALUE: __truncXfYf2__:underflow <- 947912704
	//DEBUG_VALUE: __truncXfYf2__:overflowExponent <- 143
	//DEBUG_VALUE: __truncXfYf2__:underflowExponent <- 113
	//DEBUG_VALUE: __truncXfYf2__:dstExpBias <- 15
	//DEBUG_VALUE: __truncXfYf2__:dstInfExp <- 31
	//DEBUG_VALUE: __truncXfYf2__:dstExpBits <- 5
	//DEBUG_VALUE: __truncXfYf2__:dstBits <- 16
	//DEBUG_VALUE: __truncXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __truncXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __truncXfYf2__:halfway <- 4096
	//DEBUG_VALUE: __truncXfYf2__:roundMask <- 8191
	//DEBUG_VALUE: __truncXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __truncXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __truncXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __truncXfYf2__:srcSignificandMask <- 8388607
	//DEBUG_VALUE: __truncXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __truncXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __truncXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __truncXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __truncXfYf2__:srcBits <- 32
	.loc	4 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:0:0
	and r1, r0, 8388607
	or r1, r1, 8388608
.Ltmp20:
	//DEBUG_VALUE: significand <- $r1
	.loc	4 111 58 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:111:58
	sub r2, 113, r3
.Ltmp21:
	//DEBUG_VALUE: shift <- $r2
	.loc	4 119 57                        // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:119:57
	add r3, r3, -81
.Ltmp22:
	.loc	4 119 45 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:119:45
	lsl r3, r1, r3
	move r4, 0
	.loc	4 119 33                        // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:119:33
	sub r3, r3, r4, neq
.Ltmp23:
	//DEBUG_VALUE: sticky <- [DW_OP_LLVM_convert 1 7, DW_OP_LLVM_convert 8 7, DW_OP_stack_value] $r3
	.loc	4 120 61 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:120:61
	lsr r1, r1, r2
.Ltmp24:
	//DEBUG_VALUE: denormalizedSignificand <- undef
	.loc	4 122 65                        // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:122:65
	and r2, r1, 8191
.Ltmp25:
	or r2, r2, r3
.Ltmp26:
	//DEBUG_VALUE: roundBits <- $r2
	.loc	4 0 65 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:0:65
	move r3, 4097
.Ltmp27:
	.loc	4 121 49 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:121:49
	lsr r1, r1, 13
.Ltmp28:
	//DEBUG_VALUE: __truncXfYf2__:absResult <- [DW_OP_LLVM_convert 32 7, DW_OP_LLVM_convert 16 7, DW_OP_stack_value] $r1
	.loc	4 124 17                        // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:124:17
	jltu r2, r3, .LBB0_11
.Ltmp29:
// %bb.10:
	//DEBUG_VALUE: roundBits <- $r2
	//DEBUG_VALUE: __truncXfYf2__:absResult <- [DW_OP_LLVM_convert 32 7, DW_OP_LLVM_convert 16 7, DW_OP_stack_value] $r1
	//DEBUG_VALUE: __truncXfYf2__:aAbs <- [DW_OP_constu 2147483647, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __truncXfYf2__:a <- $r0
	//DEBUG_VALUE: __truncsfhf2:a <- $r0
	//DEBUG_VALUE: __truncXfYf2__:dstNaNCode <- 511
	//DEBUG_VALUE: __truncXfYf2__:dstQNaN <- 512
	//DEBUG_VALUE: __truncXfYf2__:overflow <- 1199570944
	//DEBUG_VALUE: __truncXfYf2__:underflow <- 947912704
	//DEBUG_VALUE: __truncXfYf2__:overflowExponent <- 143
	//DEBUG_VALUE: __truncXfYf2__:underflowExponent <- 113
	//DEBUG_VALUE: __truncXfYf2__:dstExpBias <- 15
	//DEBUG_VALUE: __truncXfYf2__:dstInfExp <- 31
	//DEBUG_VALUE: __truncXfYf2__:dstExpBits <- 5
	//DEBUG_VALUE: __truncXfYf2__:dstBits <- 16
	//DEBUG_VALUE: __truncXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __truncXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __truncXfYf2__:halfway <- 4096
	//DEBUG_VALUE: __truncXfYf2__:roundMask <- 8191
	//DEBUG_VALUE: __truncXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __truncXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __truncXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __truncXfYf2__:srcSignificandMask <- 8388607
	//DEBUG_VALUE: __truncXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __truncXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __truncXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __truncXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __truncXfYf2__:srcBits <- 32
	//DEBUG_VALUE: __truncXfYf2__:absResult <- [DW_OP_LLVM_convert 32 7, DW_OP_LLVM_convert 16 7, DW_OP_plus_uconst 1, DW_OP_stack_value] $r1
	.loc	4 125 26                        // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:125:26
	add r1, r1, 1, true, .LBB0_14
.Ltmp30:
.LBB0_11:
	//DEBUG_VALUE: roundBits <- $r2
	//DEBUG_VALUE: __truncXfYf2__:absResult <- [DW_OP_LLVM_convert 32 7, DW_OP_LLVM_convert 16 7, DW_OP_stack_value] $r1
	//DEBUG_VALUE: __truncXfYf2__:aAbs <- [DW_OP_constu 2147483647, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __truncXfYf2__:a <- $r0
	//DEBUG_VALUE: __truncsfhf2:a <- $r0
	//DEBUG_VALUE: __truncXfYf2__:dstNaNCode <- 511
	//DEBUG_VALUE: __truncXfYf2__:dstQNaN <- 512
	//DEBUG_VALUE: __truncXfYf2__:overflow <- 1199570944
	//DEBUG_VALUE: __truncXfYf2__:underflow <- 947912704
	//DEBUG_VALUE: __truncXfYf2__:overflowExponent <- 143
	//DEBUG_VALUE: __truncXfYf2__:underflowExponent <- 113
	//DEBUG_VALUE: __truncXfYf2__:dstExpBias <- 15
	//DEBUG_VALUE: __truncXfYf2__:dstInfExp <- 31
	//DEBUG_VALUE: __truncXfYf2__:dstExpBits <- 5
	//DEBUG_VALUE: __truncXfYf2__:dstBits <- 16
	//DEBUG_VALUE: __truncXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __truncXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __truncXfYf2__:halfway <- 4096
	//DEBUG_VALUE: __truncXfYf2__:roundMask <- 8191
	//DEBUG_VALUE: __truncXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __truncXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __truncXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __truncXfYf2__:srcSignificandMask <- 8388607
	//DEBUG_VALUE: __truncXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __truncXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __truncXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __truncXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __truncXfYf2__:srcBits <- 32
	.loc	4 0 26 is_stmt 0                // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:0:26
	move r3, 4096
	.loc	4 127 22 is_stmt 1              // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:127:22
	jneq r2, r3, .LBB0_14
.Ltmp31:
// %bb.12:
	//DEBUG_VALUE: roundBits <- $r2
	//DEBUG_VALUE: __truncXfYf2__:absResult <- [DW_OP_LLVM_convert 32 7, DW_OP_LLVM_convert 16 7, DW_OP_stack_value] $r1
	//DEBUG_VALUE: __truncXfYf2__:aAbs <- [DW_OP_constu 2147483647, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __truncXfYf2__:a <- $r0
	//DEBUG_VALUE: __truncsfhf2:a <- $r0
	//DEBUG_VALUE: __truncXfYf2__:dstNaNCode <- 511
	//DEBUG_VALUE: __truncXfYf2__:dstQNaN <- 512
	//DEBUG_VALUE: __truncXfYf2__:overflow <- 1199570944
	//DEBUG_VALUE: __truncXfYf2__:underflow <- 947912704
	//DEBUG_VALUE: __truncXfYf2__:overflowExponent <- 143
	//DEBUG_VALUE: __truncXfYf2__:underflowExponent <- 113
	//DEBUG_VALUE: __truncXfYf2__:dstExpBias <- 15
	//DEBUG_VALUE: __truncXfYf2__:dstInfExp <- 31
	//DEBUG_VALUE: __truncXfYf2__:dstExpBits <- 5
	//DEBUG_VALUE: __truncXfYf2__:dstBits <- 16
	//DEBUG_VALUE: __truncXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __truncXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __truncXfYf2__:halfway <- 4096
	//DEBUG_VALUE: __truncXfYf2__:roundMask <- 8191
	//DEBUG_VALUE: __truncXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __truncXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __truncXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __truncXfYf2__:srcSignificandMask <- 8388607
	//DEBUG_VALUE: __truncXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __truncXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __truncXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __truncXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __truncXfYf2__:srcBits <- 32
	.loc	4 128 40                        // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:128:40
	and r2, r1, 1, true, .LBB0_13
.Ltmp32:
.LBB0_14:
	//DEBUG_VALUE: __truncXfYf2__:aAbs <- [DW_OP_constu 2147483647, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:aRep <- $r0
	//DEBUG_VALUE: __truncXfYf2__:a <- $r0
	//DEBUG_VALUE: __truncsfhf2:a <- $r0
	//DEBUG_VALUE: __truncXfYf2__:dstNaNCode <- 511
	//DEBUG_VALUE: __truncXfYf2__:dstQNaN <- 512
	//DEBUG_VALUE: __truncXfYf2__:overflow <- 1199570944
	//DEBUG_VALUE: __truncXfYf2__:underflow <- 947912704
	//DEBUG_VALUE: __truncXfYf2__:overflowExponent <- 143
	//DEBUG_VALUE: __truncXfYf2__:underflowExponent <- 113
	//DEBUG_VALUE: __truncXfYf2__:dstExpBias <- 15
	//DEBUG_VALUE: __truncXfYf2__:dstInfExp <- 31
	//DEBUG_VALUE: __truncXfYf2__:dstExpBits <- 5
	//DEBUG_VALUE: __truncXfYf2__:dstBits <- 16
	//DEBUG_VALUE: __truncXfYf2__:srcNaNCode <- 4194303
	//DEBUG_VALUE: __truncXfYf2__:srcQNaN <- 4194304
	//DEBUG_VALUE: __truncXfYf2__:halfway <- 4096
	//DEBUG_VALUE: __truncXfYf2__:roundMask <- 8191
	//DEBUG_VALUE: __truncXfYf2__:srcAbsMask <- 2147483647
	//DEBUG_VALUE: __truncXfYf2__:srcSignMask <- -2147483648
	//DEBUG_VALUE: __truncXfYf2__:srcInfinity <- 2139095040
	//DEBUG_VALUE: __truncXfYf2__:srcSignificandMask <- 8388607
	//DEBUG_VALUE: __truncXfYf2__:srcMinNormal <- 8388608
	//DEBUG_VALUE: __truncXfYf2__:srcExpBias <- 127
	//DEBUG_VALUE: __truncXfYf2__:srcInfExp <- 255
	//DEBUG_VALUE: __truncXfYf2__:srcExpBits <- 8
	//DEBUG_VALUE: __truncXfYf2__:srcBits <- 32
	//DEBUG_VALUE: __truncXfYf2__:sign <- [DW_OP_constu 18446744071562067968, DW_OP_and, DW_OP_stack_value] $r0
	//DEBUG_VALUE: __truncXfYf2__:absResult <- undef
	.loc	4 133 47                        // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:133:47
	lsr r0, r0, 16
.Ltmp33:
	and r0, r0, 32768
	.loc	4 133 40 is_stmt 0              // uPIMulator_frontend/sdk/syslib/fp_trunc_impl.inc:133:40
	or r0, r1, r0
.Ltmp34:
	.loc	3 19 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/truncsfhf2.c:19:5
	and r0, r0, 65535
	//DEBUG_VALUE: __truncXfYf2__:result <- $r0
	jump r23
.Ltmp35:
.Lfunc_end0:
	.size	__truncsfhf2, .Lfunc_end0-__truncsfhf2
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__truncsfhf2
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.__truncsfhf2,"ax",@progbits
                                        // -- End function
	.section	.text.__gnu_f2h_ieee,"ax",@progbits
	.globl	__gnu_f2h_ieee                  // -- Begin function __gnu_f2h_ieee
	.type	__gnu_f2h_ieee,@function
__gnu_f2h_ieee:                         // @__gnu_f2h_ieee
.Lfunc_begin1:
	.loc	3 24 0                          // uPIMulator_frontend/sdk/syslib/truncsfhf2.c:24:0
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __gnu_f2h_ieee:a <- $r0
	//DEBUG_VALUE: __gnu_f2h_ieee:a <- $r0
	//DEBUG_VALUE: __gnu_f2h_ieee:a <- $r0
	.cfi_def_cfa_offset -8
	.cfi_offset 23, -8
	.cfi_offset 22, -4
	sd r22, 0, d22
	add r22, r22, 8
.Ltmp36:
	.loc	3 25 12 prologue_end            // uPIMulator_frontend/sdk/syslib/truncsfhf2.c:25:12
	call r23, __truncsfhf2
.Ltmp37:
	.loc	3 25 5 is_stmt 0                // uPIMulator_frontend/sdk/syslib/truncsfhf2.c:25:5
	ld d22, r22, -8
	jump r23
.Ltmp38:
.Lfunc_end1:
	.size	__gnu_f2h_ieee, .Lfunc_end1-__gnu_f2h_ieee
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__gnu_f2h_ieee
	.long	.Lfunc_begin1
	.byte	8
	.section	.text.__gnu_f2h_ieee,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp33-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc1:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp33-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc2:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp33-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc3:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp33-.Lfunc_begin0
	.short	15                              // Loc expr size
	.byte	112                             // DW_OP_breg0
	.byte	0                               // 0
	.byte	16                              // DW_OP_constu
	.byte	128                             // 18446744071562067968
	.byte	128                             // 
	.byte	128                             // 
	.byte	128                             // 
	.byte	248                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	1                               // 
	.byte	26                              // DW_OP_and
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc4:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp33-.Lfunc_begin0
	.short	10                              // Loc expr size
	.byte	112                             // DW_OP_breg0
	.byte	0                               // 0
	.byte	16                              // DW_OP_constu
	.byte	255                             // 2147483647
	.byte	255                             // 
	.byte	255                             // 
	.byte	255                             // 
	.byte	7                               // 
	.byte	26                              // DW_OP_and
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc5:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp7-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp10-.Lfunc_begin0
	.long	.Ltmp14-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc6:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp6-.Lfunc_begin0
	.long	.Ltmp7-.Lfunc_begin0
	.short	5                               // Loc expr size
	.byte	113                             // DW_OP_breg1
	.byte	0                               // 0
	.byte	35                              // DW_OP_plus_uconst
	.byte	1                               // 1
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp8-.Lfunc_begin0
	.long	.Ltmp9-.Lfunc_begin0
	.short	5                               // Loc expr size
	.byte	16                              // DW_OP_constu
	.byte	128                             // 32256
	.byte	252                             // 
	.byte	1                               // 
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp9-.Lfunc_begin0
	.long	.Ltmp10-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	113                             // DW_OP_breg1
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp11-.Lfunc_begin0
	.long	.Ltmp13-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	113                             // DW_OP_breg1
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Ltmp15-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	113                             // DW_OP_breg1
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp28-.Lfunc_begin0
	.long	.Ltmp29-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	113                             // DW_OP_breg1
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp29-.Lfunc_begin0
	.long	.Ltmp30-.Lfunc_begin0
	.short	5                               // Loc expr size
	.byte	113                             // DW_OP_breg1
	.byte	0                               // 0
	.byte	35                              // DW_OP_plus_uconst
	.byte	1                               // 1
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp30-.Lfunc_begin0
	.long	.Ltmp32-.Lfunc_begin0
	.short	3                               // Loc expr size
	.byte	113                             // DW_OP_breg1
	.byte	0                               // 0
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc7:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp21-.Lfunc_begin0
	.long	.Ltmp25-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc8:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp20-.Lfunc_begin0
	.long	.Ltmp24-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	81                              // DW_OP_reg1
	.long	0
	.long	0
.Ldebug_loc9:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp18-.Lfunc_begin0
	.long	.Ltmp22-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc10:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp23-.Lfunc_begin0
	.long	.Ltmp27-.Lfunc_begin0
	.short	6                               // Loc expr size
	.byte	115                             // DW_OP_breg3
	.byte	0                               // 0
	.byte	16                              // DW_OP_constu
	.byte	1                               // 1
	.byte	26                              // DW_OP_and
	.byte	159                             // DW_OP_stack_value
	.long	0
	.long	0
.Ldebug_loc11:
	.long	-1
	.long	.Lfunc_begin0                   //   base address
	.long	.Ltmp26-.Lfunc_begin0
	.long	.Ltmp32-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	28                              // DW_AT_const_value
	.byte	15                              // DW_FORM_udata
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	32                              // DW_AT_inline
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	11                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	12                              // Abbreviation Code
	.byte	29                              // DW_TAG_inlined_subroutine
	.byte	1                               // DW_CHILDREN_yes
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	88                              // DW_AT_call_file
	.byte	11                              // DW_FORM_data1
	.byte	89                              // DW_AT_call_line
	.byte	11                              // DW_FORM_data1
	.byte	87                              // DW_AT_call_column
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	13                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	14                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	28                              // DW_AT_const_value
	.byte	13                              // DW_FORM_sdata
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	15                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	28                              // DW_AT_const_value
	.byte	15                              // DW_FORM_udata
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	16                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	17                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	18                              // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	19                              // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	49                              // DW_AT_abstract_origin
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	20                              // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	21                              // Abbreviation Code
	.ascii	"\211\202\001"                  // DW_TAG_GNU_call_site
	.byte	0                               // DW_CHILDREN_no
	.ascii	"\223B"                         // DW_AT_GNU_call_site_target
	.byte	24                              // DW_FORM_exprloc
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x3e5 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	0                               // DW_AT_low_pc
	.long	.Ldebug_ranges1                 // DW_AT_ranges
	.byte	2                               // Abbrev [2] 0x26:0xc DW_TAG_variable
	.long	.Linfo_string3                  // DW_AT_name
	.long	50                              // DW_AT_type
	.byte	1                               // DW_AT_decl_file
	.byte	23                              // DW_AT_decl_line
	.byte	23                              // DW_AT_const_value
	.byte	3                               // Abbrev [3] 0x32:0x5 DW_TAG_const_type
	.long	55                              // DW_AT_type
	.byte	4                               // Abbrev [4] 0x37:0x7 DW_TAG_base_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	2                               // Abbrev [2] 0x3e:0xc DW_TAG_variable
	.long	.Linfo_string5                  // DW_AT_name
	.long	50                              // DW_AT_type
	.byte	1                               // DW_AT_decl_file
	.byte	57                              // DW_AT_decl_line
	.byte	10                              // DW_AT_const_value
	.byte	5                               // Abbrev [5] 0x4a:0xb DW_TAG_typedef
	.long	85                              // DW_AT_type
	.long	.Linfo_string8                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	21                              // DW_AT_decl_line
	.byte	5                               // Abbrev [5] 0x55:0xb DW_TAG_typedef
	.long	96                              // DW_AT_type
	.long	.Linfo_string7                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	48                              // DW_AT_decl_line
	.byte	4                               // Abbrev [4] 0x60:0x7 DW_TAG_base_type
	.long	.Linfo_string6                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	5                               // Abbrev [5] 0x67:0xb DW_TAG_typedef
	.long	114                             // DW_AT_type
	.long	.Linfo_string11                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	55                              // DW_AT_decl_line
	.byte	5                               // Abbrev [5] 0x72:0xb DW_TAG_typedef
	.long	125                             // DW_AT_type
	.long	.Linfo_string10                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	44                              // DW_AT_decl_line
	.byte	4                               // Abbrev [4] 0x7d:0x7 DW_TAG_base_type
	.long	.Linfo_string9                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	2                               // DW_AT_byte_size
	.byte	6                               // Abbrev [6] 0x84:0x19f DW_TAG_subprogram
	.long	.Linfo_string12                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	42                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	547                             // DW_AT_type
	.byte	1                               // DW_AT_inline
	.byte	7                               // Abbrev [7] 0x90:0xb DW_TAG_formal_parameter
	.long	.Linfo_string14                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	42                              // DW_AT_decl_line
	.long	558                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x9b:0xb DW_TAG_variable
	.long	.Linfo_string17                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	45                              // DW_AT_decl_line
	.long	50                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0xa6:0xb DW_TAG_variable
	.long	.Linfo_string18                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	46                              // DW_AT_decl_line
	.long	50                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0xb1:0xb DW_TAG_variable
	.long	.Linfo_string19                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	47                              // DW_AT_decl_line
	.long	50                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0xbc:0xb DW_TAG_variable
	.long	.Linfo_string20                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	48                              // DW_AT_decl_line
	.long	50                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0xc7:0xb DW_TAG_variable
	.long	.Linfo_string21                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	50                              // DW_AT_decl_line
	.long	576                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0xd2:0xb DW_TAG_variable
	.long	.Linfo_string22                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	51                              // DW_AT_decl_line
	.long	576                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0xdd:0xb DW_TAG_variable
	.long	.Linfo_string23                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	52                              // DW_AT_decl_line
	.long	576                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0xe8:0xb DW_TAG_variable
	.long	.Linfo_string24                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	53                              // DW_AT_decl_line
	.long	576                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0xf3:0xb DW_TAG_variable
	.long	.Linfo_string25                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	54                              // DW_AT_decl_line
	.long	576                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0xfe:0xb DW_TAG_variable
	.long	.Linfo_string26                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	55                              // DW_AT_decl_line
	.long	576                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x109:0xb DW_TAG_variable
	.long	.Linfo_string27                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	56                              // DW_AT_decl_line
	.long	576                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x114:0xb DW_TAG_variable
	.long	.Linfo_string28                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	57                              // DW_AT_decl_line
	.long	576                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x11f:0xb DW_TAG_variable
	.long	.Linfo_string29                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	58                              // DW_AT_decl_line
	.long	576                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x12a:0xb DW_TAG_variable
	.long	.Linfo_string30                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	60                              // DW_AT_decl_line
	.long	50                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0x135:0xb DW_TAG_variable
	.long	.Linfo_string31                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	61                              // DW_AT_decl_line
	.long	50                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0x140:0xb DW_TAG_variable
	.long	.Linfo_string32                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	62                              // DW_AT_decl_line
	.long	50                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0x14b:0xb DW_TAG_variable
	.long	.Linfo_string33                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	63                              // DW_AT_decl_line
	.long	50                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0x156:0xb DW_TAG_variable
	.long	.Linfo_string34                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	65                              // DW_AT_decl_line
	.long	50                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0x161:0xb DW_TAG_variable
	.long	.Linfo_string35                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	66                              // DW_AT_decl_line
	.long	50                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0x16c:0xb DW_TAG_variable
	.long	.Linfo_string36                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	67                              // DW_AT_decl_line
	.long	576                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x177:0xb DW_TAG_variable
	.long	.Linfo_string37                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	68                              // DW_AT_decl_line
	.long	576                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x182:0xb DW_TAG_variable
	.long	.Linfo_string38                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	70                              // DW_AT_decl_line
	.long	581                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x18d:0xb DW_TAG_variable
	.long	.Linfo_string39                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	71                              // DW_AT_decl_line
	.long	581                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x198:0xb DW_TAG_variable
	.long	.Linfo_string40                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	74                              // DW_AT_decl_line
	.long	576                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x1a3:0xb DW_TAG_variable
	.long	.Linfo_string41                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	76                              // DW_AT_decl_line
	.long	576                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x1ae:0xb DW_TAG_variable
	.long	.Linfo_string42                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	75                              // DW_AT_decl_line
	.long	576                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x1b9:0xb DW_TAG_variable
	.long	.Linfo_string43                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	77                              // DW_AT_decl_line
	.long	103                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x1c4:0xb DW_TAG_variable
	.long	.Linfo_string44                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	133                             // DW_AT_decl_line
	.long	581                             // DW_AT_type
	.byte	9                               // Abbrev [9] 0x1cf:0xd DW_TAG_lexical_block
	.byte	8                               // Abbrev [8] 0x1d0:0xb DW_TAG_variable
	.long	.Linfo_string45                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	86                              // DW_AT_decl_line
	.long	576                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	9                               // Abbrev [9] 0x1dc:0x46 DW_TAG_lexical_block
	.byte	8                               // Abbrev [8] 0x1dd:0xb DW_TAG_variable
	.long	.Linfo_string46                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	111                             // DW_AT_decl_line
	.long	50                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0x1e8:0xb DW_TAG_variable
	.long	.Linfo_string47                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	113                             // DW_AT_decl_line
	.long	576                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x1f3:0xb DW_TAG_variable
	.long	.Linfo_string48                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	110                             // DW_AT_decl_line
	.long	50                              // DW_AT_type
	.byte	9                               // Abbrev [9] 0x1fe:0x23 DW_TAG_lexical_block
	.byte	8                               // Abbrev [8] 0x1ff:0xb DW_TAG_variable
	.long	.Linfo_string49                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	119                             // DW_AT_decl_line
	.long	586                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x20a:0xb DW_TAG_variable
	.long	.Linfo_string51                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	120                             // DW_AT_decl_line
	.long	74                              // DW_AT_type
	.byte	8                               // Abbrev [8] 0x215:0xb DW_TAG_variable
	.long	.Linfo_string45                 // DW_AT_name
	.byte	4                               // DW_AT_decl_file
	.byte	122                             // DW_AT_decl_line
	.long	576                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	5                               // Abbrev [5] 0x223:0xb DW_TAG_typedef
	.long	114                             // DW_AT_type
	.long	.Linfo_string13                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	54                              // DW_AT_decl_line
	.byte	5                               // Abbrev [5] 0x22e:0xb DW_TAG_typedef
	.long	569                             // DW_AT_type
	.long	.Linfo_string16                 // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	20                              // DW_AT_decl_line
	.byte	4                               // Abbrev [4] 0x239:0x7 DW_TAG_base_type
	.long	.Linfo_string15                 // DW_AT_name
	.byte	4                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	3                               // Abbrev [3] 0x240:0x5 DW_TAG_const_type
	.long	74                              // DW_AT_type
	.byte	3                               // Abbrev [3] 0x245:0x5 DW_TAG_const_type
	.long	103                             // DW_AT_type
	.byte	3                               // Abbrev [3] 0x24a:0x5 DW_TAG_const_type
	.long	591                             // DW_AT_type
	.byte	4                               // Abbrev [4] 0x24f:0x7 DW_TAG_base_type
	.long	.Linfo_string50                 // DW_AT_name
	.byte	2                               // DW_AT_encoding
	.byte	1                               // DW_AT_byte_size
	.byte	10                              // Abbrev [10] 0x256:0x16f DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string52                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	17                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	114                             // DW_AT_type
                                        // DW_AT_external
	.byte	11                              // Abbrev [11] 0x26b:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string14                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	17                              // DW_AT_decl_line
	.long	569                             // DW_AT_type
	.byte	12                              // Abbrev [12] 0x27a:0x14a DW_TAG_inlined_subroutine
	.long	132                             // DW_AT_abstract_origin
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Ltmp34-.Lfunc_begin0           // DW_AT_high_pc
	.byte	3                               // DW_AT_call_file
	.byte	19                              // DW_AT_call_line
	.byte	12                              // DW_AT_call_column
	.byte	13                              // Abbrev [13] 0x28a:0x9 DW_TAG_formal_parameter
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	144                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x293:0x6 DW_TAG_variable
	.byte	32                              // DW_AT_const_value
	.long	155                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x299:0x6 DW_TAG_variable
	.byte	8                               // DW_AT_const_value
	.long	166                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x29f:0x7 DW_TAG_variable
	.ascii	"\377\001"                      // DW_AT_const_value
	.long	177                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x2a6:0x7 DW_TAG_variable
	.asciz	"\377"                          // DW_AT_const_value
	.long	188                             // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x2ad:0x9 DW_TAG_variable
	.ascii	"\200\200\200\004"              // DW_AT_const_value
	.long	199                             // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x2b6:0x9 DW_TAG_variable
	.ascii	"\377\377\377\003"              // DW_AT_const_value
	.long	210                             // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x2bf:0xa DW_TAG_variable
	.ascii	"\200\200\200\374\007"          // DW_AT_const_value
	.long	221                             // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x2c9:0xf DW_TAG_variable
	.ascii	"\200\200\200\200\370\377\377\377\377\001" // DW_AT_const_value
	.long	232                             // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x2d8:0xa DW_TAG_variable
	.ascii	"\377\377\377\377\007"          // DW_AT_const_value
	.long	243                             // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x2e2:0x7 DW_TAG_variable
	.ascii	"\377?"                         // DW_AT_const_value
	.long	254                             // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x2e9:0x7 DW_TAG_variable
	.ascii	"\200 "                         // DW_AT_const_value
	.long	265                             // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x2f0:0x9 DW_TAG_variable
	.ascii	"\200\200\200\002"              // DW_AT_const_value
	.long	276                             // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x2f9:0x9 DW_TAG_variable
	.ascii	"\377\377\377\001"              // DW_AT_const_value
	.long	287                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x302:0x6 DW_TAG_variable
	.byte	16                              // DW_AT_const_value
	.long	298                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x308:0x6 DW_TAG_variable
	.byte	5                               // DW_AT_const_value
	.long	309                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x30e:0x6 DW_TAG_variable
	.byte	31                              // DW_AT_const_value
	.long	320                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x314:0x6 DW_TAG_variable
	.byte	15                              // DW_AT_const_value
	.long	331                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x31a:0x7 DW_TAG_variable
	.asciz	"\361"                          // DW_AT_const_value
	.long	342                             // DW_AT_abstract_origin
	.byte	14                              // Abbrev [14] 0x321:0x7 DW_TAG_variable
	.ascii	"\217\001"                      // DW_AT_const_value
	.long	353                             // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x328:0xa DW_TAG_variable
	.ascii	"\200\200\200\304\003"          // DW_AT_const_value
	.long	364                             // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x332:0xa DW_TAG_variable
	.ascii	"\200\200\200\274\004"          // DW_AT_const_value
	.long	375                             // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x33c:0x7 DW_TAG_variable
	.ascii	"\200\004"                      // DW_AT_const_value
	.long	386                             // DW_AT_abstract_origin
	.byte	15                              // Abbrev [15] 0x343:0x7 DW_TAG_variable
	.ascii	"\377\003"                      // DW_AT_const_value
	.long	397                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x34a:0x9 DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	408                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x353:0x9 DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	419                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x35c:0x9 DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	430                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x365:0x9 DW_TAG_variable
	.long	.Ldebug_loc6                    // DW_AT_location
	.long	441                             // DW_AT_abstract_origin
	.byte	17                              // Abbrev [17] 0x36e:0xf DW_TAG_lexical_block
	.long	.Ldebug_ranges0                 // DW_AT_ranges
	.byte	16                              // Abbrev [16] 0x373:0x9 DW_TAG_variable
	.long	.Ldebug_loc5                    // DW_AT_location
	.long	464                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	18                              // Abbrev [18] 0x37d:0x46 DW_TAG_lexical_block
	.long	.Ltmp18                         // DW_AT_low_pc
	.long	.Ltmp32-.Ltmp18                 // DW_AT_high_pc
	.byte	16                              // Abbrev [16] 0x386:0x9 DW_TAG_variable
	.long	.Ldebug_loc7                    // DW_AT_location
	.long	477                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x38f:0x9 DW_TAG_variable
	.long	.Ldebug_loc8                    // DW_AT_location
	.long	488                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x398:0x9 DW_TAG_variable
	.long	.Ldebug_loc9                    // DW_AT_location
	.long	499                             // DW_AT_abstract_origin
	.byte	18                              // Abbrev [18] 0x3a1:0x21 DW_TAG_lexical_block
	.long	.Ltmp21                         // DW_AT_low_pc
	.long	.Ltmp32-.Ltmp21                 // DW_AT_high_pc
	.byte	16                              // Abbrev [16] 0x3aa:0x9 DW_TAG_variable
	.long	.Ldebug_loc10                   // DW_AT_location
	.long	511                             // DW_AT_abstract_origin
	.byte	19                              // Abbrev [19] 0x3b3:0x5 DW_TAG_variable
	.long	522                             // DW_AT_abstract_origin
	.byte	16                              // Abbrev [16] 0x3b8:0x9 DW_TAG_variable
	.long	.Ldebug_loc11                   // DW_AT_location
	.long	533                             // DW_AT_abstract_origin
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	10                              // Abbrev [10] 0x3c5:0x2a DW_TAG_subprogram
	.long	.Lfunc_begin1                   // DW_AT_low_pc
	.long	.Lfunc_end1-.Lfunc_begin1       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string53                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	23                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	114                             // DW_AT_type
                                        // DW_AT_external
	.byte	20                              // Abbrev [20] 0x3da:0xd DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	80
	.long	.Linfo_string14                 // DW_AT_name
	.byte	3                               // DW_AT_decl_file
	.byte	23                              // DW_AT_decl_line
	.long	569                             // DW_AT_type
	.byte	21                              // Abbrev [21] 0x3e7:0x7 DW_TAG_GNU_call_site
	.byte	1                               // DW_AT_GNU_call_site_target
	.byte	103
	.long	.Ltmp37                         // DW_AT_low_pc
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_ranges,"",@progbits
.Ldebug_ranges0:
	.long	.Ltmp2
	.long	.Ltmp7
	.long	.Ltmp11
	.long	.Ltmp14
	.long	0
	.long	0
.Ldebug_ranges1:
	.long	.Lfunc_begin0
	.long	.Lfunc_end0
	.long	.Lfunc_begin1
	.long	.Lfunc_end1
	.long	0
	.long	0
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/truncsfhf2.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=156
.Linfo_string3:
	.asciz	"srcSigBits"                    // string offset=177
.Linfo_string4:
	.asciz	"int"                           // string offset=188
.Linfo_string5:
	.asciz	"dstSigBits"                    // string offset=192
.Linfo_string6:
	.asciz	"unsigned int"                  // string offset=203
.Linfo_string7:
	.asciz	"uint32_t"                      // string offset=216
.Linfo_string8:
	.asciz	"src_rep_t"                     // string offset=225
.Linfo_string9:
	.asciz	"unsigned short"                // string offset=235
.Linfo_string10:
	.asciz	"uint16_t"                      // string offset=250
.Linfo_string11:
	.asciz	"dst_rep_t"                     // string offset=259
.Linfo_string12:
	.asciz	"__truncXfYf2__"                // string offset=269
.Linfo_string13:
	.asciz	"dst_t"                         // string offset=284
.Linfo_string14:
	.asciz	"a"                             // string offset=290
.Linfo_string15:
	.asciz	"float"                         // string offset=292
.Linfo_string16:
	.asciz	"src_t"                         // string offset=298
.Linfo_string17:
	.asciz	"srcBits"                       // string offset=304
.Linfo_string18:
	.asciz	"srcExpBits"                    // string offset=312
.Linfo_string19:
	.asciz	"srcInfExp"                     // string offset=323
.Linfo_string20:
	.asciz	"srcExpBias"                    // string offset=333
.Linfo_string21:
	.asciz	"srcMinNormal"                  // string offset=344
.Linfo_string22:
	.asciz	"srcSignificandMask"            // string offset=357
.Linfo_string23:
	.asciz	"srcInfinity"                   // string offset=376
.Linfo_string24:
	.asciz	"srcSignMask"                   // string offset=388
.Linfo_string25:
	.asciz	"srcAbsMask"                    // string offset=400
.Linfo_string26:
	.asciz	"roundMask"                     // string offset=411
.Linfo_string27:
	.asciz	"halfway"                       // string offset=421
.Linfo_string28:
	.asciz	"srcQNaN"                       // string offset=429
.Linfo_string29:
	.asciz	"srcNaNCode"                    // string offset=437
.Linfo_string30:
	.asciz	"dstBits"                       // string offset=448
.Linfo_string31:
	.asciz	"dstExpBits"                    // string offset=456
.Linfo_string32:
	.asciz	"dstInfExp"                     // string offset=467
.Linfo_string33:
	.asciz	"dstExpBias"                    // string offset=477
.Linfo_string34:
	.asciz	"underflowExponent"             // string offset=488
.Linfo_string35:
	.asciz	"overflowExponent"              // string offset=506
.Linfo_string36:
	.asciz	"underflow"                     // string offset=523
.Linfo_string37:
	.asciz	"overflow"                      // string offset=533
.Linfo_string38:
	.asciz	"dstQNaN"                       // string offset=542
.Linfo_string39:
	.asciz	"dstNaNCode"                    // string offset=550
.Linfo_string40:
	.asciz	"aRep"                          // string offset=561
.Linfo_string41:
	.asciz	"sign"                          // string offset=566
.Linfo_string42:
	.asciz	"aAbs"                          // string offset=571
.Linfo_string43:
	.asciz	"absResult"                     // string offset=576
.Linfo_string44:
	.asciz	"result"                        // string offset=586
.Linfo_string45:
	.asciz	"roundBits"                     // string offset=593
.Linfo_string46:
	.asciz	"shift"                         // string offset=603
.Linfo_string47:
	.asciz	"significand"                   // string offset=609
.Linfo_string48:
	.asciz	"aExp"                          // string offset=621
.Linfo_string49:
	.asciz	"sticky"                        // string offset=626
.Linfo_string50:
	.asciz	"_Bool"                         // string offset=633
.Linfo_string51:
	.asciz	"denormalizedSignificand"       // string offset=639
.Linfo_string52:
	.asciz	"__truncsfhf2"                  // string offset=663
.Linfo_string53:
	.asciz	"__gnu_f2h_ieee"                // string offset=676
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
