	.text
	.file	"udivsi3.c"
	.file	1 "/root" "uPIMulator_frontend/sdk/syslib/int_types.h"
	.section	.text.__udivsi3,"ax",@progbits
	.globl	__udivsi3                       // -- Begin function __udivsi3
	.type	__udivsi3,@function
__udivsi3:                              // @__udivsi3
.Lfunc_begin0:
	.file	2 "/root" "uPIMulator_frontend/sdk/syslib/udivsi3.c"
	.loc	2 24 0                          // uPIMulator_frontend/sdk/syslib/udivsi3.c:24:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	//DEBUG_VALUE: __udivsi3:n <- $r0
	//DEBUG_VALUE: __udivsi3:d <- $r1
	.cfi_def_cfa_offset 0
	move r2, r0
	move r0, 0
.Ltmp0:
	//DEBUG_VALUE: __udivsi3:n_uword_bits <- 32
	//DEBUG_VALUE: __udivsi3:d <- $r1
	//DEBUG_VALUE: __udivsi3:n <- $r2
	.loc	2 30 9 prologue_end             // uPIMulator_frontend/sdk/syslib/udivsi3.c:30:9
	jeq r2, 0, .LBB0_8
.Ltmp1:
// %bb.1:
	//DEBUG_VALUE: __udivsi3:n <- $r2
	//DEBUG_VALUE: __udivsi3:d <- $r1
	//DEBUG_VALUE: __udivsi3:n_uword_bits <- 32
	jeq r1, 0, .LBB0_8
.Ltmp2:
// %bb.2:
	//DEBUG_VALUE: __udivsi3:n <- $r2
	//DEBUG_VALUE: __udivsi3:d <- $r1
	//DEBUG_VALUE: __udivsi3:n_uword_bits <- 32
	.loc	2 34 10                         // uPIMulator_frontend/sdk/syslib/udivsi3.c:34:10
	clz r3, r1
	.loc	2 34 29 is_stmt 0               // uPIMulator_frontend/sdk/syslib/udivsi3.c:34:29
	clz r5, r2
	.loc	2 34 27                         // uPIMulator_frontend/sdk/syslib/udivsi3.c:34:27
	sub r4, r3, r5
.Ltmp3:
	//DEBUG_VALUE: __udivsi3:sr <- $r4
	.loc	2 36 9 is_stmt 1                // uPIMulator_frontend/sdk/syslib/udivsi3.c:36:9
	jgtu r4, 31, .LBB0_8
.Ltmp4:
// %bb.3:
	//DEBUG_VALUE: __udivsi3:sr <- $r4
	//DEBUG_VALUE: __udivsi3:n <- $r2
	//DEBUG_VALUE: __udivsi3:d <- $r1
	//DEBUG_VALUE: __udivsi3:n_uword_bits <- 32
	.loc	2 38 9                          // uPIMulator_frontend/sdk/syslib/udivsi3.c:38:9
	jneq r4, 31, .LBB0_5
.Ltmp5:
// %bb.4:
	//DEBUG_VALUE: __udivsi3:sr <- $r4
	//DEBUG_VALUE: __udivsi3:n <- $r2
	//DEBUG_VALUE: __udivsi3:d <- $r1
	//DEBUG_VALUE: __udivsi3:n_uword_bits <- 32
	.loc	2 0 0 is_stmt 0                 // uPIMulator_frontend/sdk/syslib/udivsi3.c:0:0
	move r0, r2
	.loc	2 63 1 is_stmt 1                // uPIMulator_frontend/sdk/syslib/udivsi3.c:63:1
	jump r23
.Ltmp6:
.LBB0_5:
	//DEBUG_VALUE: __udivsi3:sr <- $r4
	//DEBUG_VALUE: __udivsi3:n <- $r2
	//DEBUG_VALUE: __udivsi3:d <- $r1
	//DEBUG_VALUE: __udivsi3:n_uword_bits <- 32
	.loc	2 40 5                          // uPIMulator_frontend/sdk/syslib/udivsi3.c:40:5
	add r6, r4, 1
.Ltmp7:
	//DEBUG_VALUE: __udivsi3:sr <- $r6
	.loc	2 43 28                         // uPIMulator_frontend/sdk/syslib/udivsi3.c:43:28
	sub r0, 31, r4
	.loc	2 43 11 is_stmt 0               // uPIMulator_frontend/sdk/syslib/udivsi3.c:43:11
	lsl r0, r2, r0
.Ltmp8:
	//DEBUG_VALUE: __udivsi3:q <- $r0
	.loc	2 44 11 is_stmt 1               // uPIMulator_frontend/sdk/syslib/udivsi3.c:44:11
	lsr r4, r2, r6
.Ltmp9:
	//DEBUG_VALUE: __udivsi3:carry <- 0
	//DEBUG_VALUE: __udivsi3:r <- $r4
	//DEBUG_VALUE: __udivsi3:sr <- undef
	.loc	2 46 5                          // uPIMulator_frontend/sdk/syslib/udivsi3.c:46:5
	not r2, r3
.Ltmp10:
	add r2, r2, r5
	move r3, 0
.Ltmp11:
.LBB0_6:                                // =>This Inner Loop Header: Depth=1
	//DEBUG_VALUE: __udivsi3:r <- $r4
	//DEBUG_VALUE: __udivsi3:d <- $r1
	//DEBUG_VALUE: __udivsi3:q <- $r0
	//DEBUG_VALUE: __udivsi3:n_uword_bits <- 32
	//DEBUG_VALUE: __udivsi3:sr <- undef
	//DEBUG_VALUE: __udivsi3:q <- $r0
	//DEBUG_VALUE: __udivsi3:r <- $r4
	//DEBUG_VALUE: __udivsi3:carry <- $r3
	.loc	2 48 22                         // uPIMulator_frontend/sdk/syslib/udivsi3.c:48:22
	lsr r5, r0, 31
	lsl_add r6, r5, r4, 1
.Ltmp12:
	//DEBUG_VALUE: __udivsi3:r <- $r6
	lsl r4, r4, 1
	.loc	2 49 16                         // uPIMulator_frontend/sdk/syslib/udivsi3.c:49:16
	lsl r0, r0, 1
.Ltmp13:
	.loc	2 49 22 is_stmt 0               // uPIMulator_frontend/sdk/syslib/udivsi3.c:49:22
	or r0, r3, r0
.Ltmp14:
	//DEBUG_VALUE: __udivsi3:q <- $r0
	.loc	2 57 41 is_stmt 1               // uPIMulator_frontend/sdk/syslib/udivsi3.c:57:41
	nor r3, r4, r5
.Ltmp15:
	add r3, r3, r1
	.loc	2 57 46 is_stmt 0               // uPIMulator_frontend/sdk/syslib/udivsi3.c:57:46
	asr r4, r3, 31
.Ltmp16:
	//DEBUG_VALUE: s <- $r4
	.loc	2 58 19 is_stmt 1               // uPIMulator_frontend/sdk/syslib/udivsi3.c:58:19
	and r3, r4, 1
.Ltmp17:
	//DEBUG_VALUE: __udivsi3:carry <- $r3
	.loc	2 59 16                         // uPIMulator_frontend/sdk/syslib/udivsi3.c:59:16
	and r4, r4, r1
.Ltmp18:
	.loc	2 46 15                         // uPIMulator_frontend/sdk/syslib/udivsi3.c:46:15
	add r5, r2, 1
	sub r7, r5, r2, ltu
.Ltmp19:
	.loc	2 59 11                         // uPIMulator_frontend/sdk/syslib/udivsi3.c:59:11
	sub r4, r6, r4
.Ltmp20:
	//DEBUG_VALUE: __udivsi3:r <- $r4
	//DEBUG_VALUE: __udivsi3:sr <- [DW_OP_constu 1, DW_OP_minus, DW_OP_stack_value] undef
	.loc	2 0 11 is_stmt 0                // uPIMulator_frontend/sdk/syslib/udivsi3.c:0:11
	move r2, r5
.Ltmp21:
	.loc	2 46 5 is_stmt 1                // uPIMulator_frontend/sdk/syslib/udivsi3.c:46:5
	jneq r7, 1, .LBB0_6
.Ltmp22:
// %bb.7:
	//DEBUG_VALUE: __udivsi3:r <- $r4
	//DEBUG_VALUE: __udivsi3:carry <- $r3
	//DEBUG_VALUE: __udivsi3:d <- $r1
	//DEBUG_VALUE: __udivsi3:q <- $r0
	//DEBUG_VALUE: __udivsi3:n_uword_bits <- 32
	.loc	2 61 18                         // uPIMulator_frontend/sdk/syslib/udivsi3.c:61:18
	lsl_add r0, r3, r0, 1
.Ltmp23:
	//DEBUG_VALUE: __udivsi3:q <- $r0
.LBB0_8:
	//DEBUG_VALUE: __udivsi3:d <- $r1
	//DEBUG_VALUE: __udivsi3:n_uword_bits <- 32
	.loc	2 63 1                          // uPIMulator_frontend/sdk/syslib/udivsi3.c:63:1
	jump r23
.Ltmp24:
.Lfunc_end0:
	.size	__udivsi3, .Lfunc_end0-__udivsi3
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__udivsi3
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.__udivsi3,"ax",@progbits
                                        // -- End function
	.section	.debug_loc,"",@progbits
.Ldebug_loc0:
	.long	.Lfunc_begin0-.Lfunc_begin0
	.long	.Ltmp0-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp0-.Lfunc_begin0
	.long	.Ltmp10-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	82                              // DW_OP_reg2
	.long	0
	.long	0
.Ldebug_loc1:
	.long	.Ltmp3-.Lfunc_begin0
	.long	.Ltmp7-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp7-.Lfunc_begin0
	.long	.Ltmp9-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	86                              // DW_OP_reg6
	.long	0
	.long	0
.Ldebug_loc2:
	.long	.Ltmp8-.Lfunc_begin0
	.long	.Ltmp13-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	.Ltmp14-.Lfunc_begin0
	.long	.Ltmp23-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	80                              // DW_OP_reg0
	.long	0
	.long	0
.Ldebug_loc3:
	.long	.Ltmp9-.Lfunc_begin0
	.long	.Ltmp11-.Lfunc_begin0
	.short	2                               // Loc expr size
	.byte	48                              // DW_OP_lit0
	.byte	159                             // DW_OP_stack_value
	.long	.Ltmp11-.Lfunc_begin0
	.long	.Ltmp15-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	.Ltmp17-.Lfunc_begin0
	.long	.Ltmp23-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	83                              // DW_OP_reg3
	.long	0
	.long	0
.Ldebug_loc4:
	.long	.Ltmp9-.Lfunc_begin0
	.long	.Ltmp12-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	.Ltmp12-.Lfunc_begin0
	.long	.Ltmp20-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	86                              // DW_OP_reg6
	.long	.Ltmp20-.Lfunc_begin0
	.long	.Ltmp23-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	0
	.long	0
.Ldebug_loc5:
	.long	.Ltmp16-.Lfunc_begin0
	.long	.Ltmp18-.Lfunc_begin0
	.short	1                               // Loc expr size
	.byte	84                              // DW_OP_reg4
	.long	0
	.long	0
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	22                              // DW_TAG_typedef
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	3                               // Abbreviation Code
	.byte	36                              // DW_TAG_base_type
	.byte	0                               // DW_CHILDREN_no
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	62                              // DW_AT_encoding
	.byte	11                              // DW_FORM_data1
	.byte	11                              // DW_AT_byte_size
	.byte	11                              // DW_FORM_data1
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	4                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	1                               // DW_CHILDREN_yes
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	39                              // DW_AT_prototyped
	.byte	25                              // DW_FORM_flag_present
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	5                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	6                               // Abbreviation Code
	.byte	5                               // DW_TAG_formal_parameter
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	24                              // DW_FORM_exprloc
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	7                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	28                              // DW_AT_const_value
	.byte	15                              // DW_FORM_udata
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	8                               // Abbreviation Code
	.byte	52                              // DW_TAG_variable
	.byte	0                               // DW_CHILDREN_no
	.byte	2                               // DW_AT_location
	.byte	23                              // DW_FORM_sec_offset
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	9                               // Abbreviation Code
	.byte	11                              // DW_TAG_lexical_block
	.byte	1                               // DW_CHILDREN_yes
	.byte	85                              // DW_AT_ranges
	.byte	23                              // DW_FORM_sec_offset
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	10                              // Abbreviation Code
	.byte	38                              // DW_TAG_const_type
	.byte	0                               // DW_CHILDREN_no
	.byte	73                              // DW_AT_type
	.byte	19                              // DW_FORM_ref4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0xd9 DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0xb DW_TAG_typedef
	.long	49                              // DW_AT_type
	.long	.Linfo_string4                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	27                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0x31:0x7 DW_TAG_base_type
	.long	.Linfo_string3                  // DW_AT_name
	.byte	5                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	4                               // Abbrev [4] 0x38:0x8f DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string5                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	23                              // DW_AT_decl_line
                                        // DW_AT_prototyped
	.long	199                             // DW_AT_type
                                        // DW_AT_external
	.byte	5                               // Abbrev [5] 0x4d:0xf DW_TAG_formal_parameter
	.long	.Ldebug_loc0                    // DW_AT_location
	.long	.Linfo_string8                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	23                              // DW_AT_decl_line
	.long	199                             // DW_AT_type
	.byte	6                               // Abbrev [6] 0x5c:0xd DW_TAG_formal_parameter
	.byte	1                               // DW_AT_location
	.byte	81
	.long	.Linfo_string9                  // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	23                              // DW_AT_decl_line
	.long	199                             // DW_AT_type
	.byte	7                               // Abbrev [7] 0x69:0xc DW_TAG_variable
	.byte	32                              // DW_AT_const_value
	.long	.Linfo_string10                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	25                              // DW_AT_decl_line
	.long	217                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x75:0xf DW_TAG_variable
	.long	.Ldebug_loc1                    // DW_AT_location
	.long	.Linfo_string11                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	28                              // DW_AT_decl_line
	.long	210                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x84:0xf DW_TAG_variable
	.long	.Ldebug_loc2                    // DW_AT_location
	.long	.Linfo_string12                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	26                              // DW_AT_decl_line
	.long	199                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0x93:0xf DW_TAG_variable
	.long	.Ldebug_loc3                    // DW_AT_location
	.long	.Linfo_string13                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	45                              // DW_AT_decl_line
	.long	199                             // DW_AT_type
	.byte	8                               // Abbrev [8] 0xa2:0xf DW_TAG_variable
	.long	.Ldebug_loc4                    // DW_AT_location
	.long	.Linfo_string14                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	27                              // DW_AT_decl_line
	.long	199                             // DW_AT_type
	.byte	9                               // Abbrev [9] 0xb1:0x15 DW_TAG_lexical_block
	.long	.Ldebug_ranges0                 // DW_AT_ranges
	.byte	8                               // Abbrev [8] 0xb6:0xf DW_TAG_variable
	.long	.Ldebug_loc5                    // DW_AT_location
	.long	.Linfo_string15                 // DW_AT_name
	.byte	2                               // DW_AT_decl_file
	.byte	57                              // DW_AT_decl_line
	.long	222                             // DW_AT_type
	.byte	0                               // End Of Children Mark
	.byte	0                               // End Of Children Mark
	.byte	2                               // Abbrev [2] 0xc7:0xb DW_TAG_typedef
	.long	210                             // DW_AT_type
	.long	.Linfo_string7                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	28                              // DW_AT_decl_line
	.byte	3                               // Abbrev [3] 0xd2:0x7 DW_TAG_base_type
	.long	.Linfo_string6                  // DW_AT_name
	.byte	7                               // DW_AT_encoding
	.byte	4                               // DW_AT_byte_size
	.byte	10                              // Abbrev [10] 0xd9:0x5 DW_TAG_const_type
	.long	210                             // DW_AT_type
	.byte	10                              // Abbrev [10] 0xde:0x5 DW_TAG_const_type
	.long	38                              // DW_AT_type
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_ranges,"",@progbits
.Ldebug_ranges0:
	.long	.Ltmp11-.Lfunc_begin0
	.long	.Ltmp18-.Lfunc_begin0
	.long	.Ltmp19-.Lfunc_begin0
	.long	.Ltmp21-.Lfunc_begin0
	.long	0
	.long	0
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/syslib/udivsi3.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=153
.Linfo_string3:
	.asciz	"int"                           // string offset=174
.Linfo_string4:
	.asciz	"si_int"                        // string offset=178
.Linfo_string5:
	.asciz	"__udivsi3"                     // string offset=185
.Linfo_string6:
	.asciz	"unsigned int"                  // string offset=195
.Linfo_string7:
	.asciz	"su_int"                        // string offset=208
.Linfo_string8:
	.asciz	"n"                             // string offset=215
.Linfo_string9:
	.asciz	"d"                             // string offset=217
.Linfo_string10:
	.asciz	"n_uword_bits"                  // string offset=219
.Linfo_string11:
	.asciz	"sr"                            // string offset=232
.Linfo_string12:
	.asciz	"q"                             // string offset=235
.Linfo_string13:
	.asciz	"carry"                         // string offset=237
.Linfo_string14:
	.asciz	"r"                             // string offset=243
.Linfo_string15:
	.asciz	"s"                             // string offset=245
	.addrsig
	.section	.debug_line,"",@progbits
.Lline_table_start0:
