	.text
	.file	"restoreRegisters.c"
	.section	.text.__bootstrap,"ax",@progbits
	.globl	__bootstrap                     // -- Begin function __bootstrap
	.type	__bootstrap,@function
__bootstrap:                            // @__bootstrap
.Lfunc_begin0:
	.file	1 "/root" "uPIMulator_frontend/sdk/misc/restoreRegisters.c"
	.loc	1 14 0                          // uPIMulator_frontend/sdk/misc/restoreRegisters.c:14:0
	.cfi_sections .debug_frame
	.cfi_startproc
// %bb.0:
	.loc	1 16 5 prologue_end             // uPIMulator_frontend/sdk/misc/restoreRegisters.c:16:5
	// inline asm
.Ltmp0:
	jeq id, 23, .Ltmp0+2
	boot id, 1
	ld d2, id8, 448
	ld d4, id8, 640
	ld d6, id8, 832
	ld d8, id8, 1024
	ld d10, id8, 1216
	ld d12, id8, 1408
	ld d14, id8, 1600
	ld d16, id8, 1792
	ld d18, id8, 1984
	ld d20, id8, 2176
	ld d22, id8, 2368
	jnz id, atomic_done
	move r0, 255
atomic_loop:
	lbu r1, r0, 0
	jz r1, atomic_release
	acquire r0, 0, true, atomic_next
atomic_release:
	release r0, 0, nz, atomic_next
atomic_next:
	add r0, r0, -1, pl, atomic_loop
atomic_done:
	lw r0, id4, 2560
	add r1, r0, r0
	add r0, r0, r1
	or r1, id8, 0
	add r1, id4, r1
	add r0, r0, r1
	call zero, r0, ending_routines
ending_routines:
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 1
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483649
	ld d0, id8, 256
	stop true, 0x0
	add r0, zero, 0
	ld d0, id8, 256
	stop true, 0x0
	add r0, mneg, 2147483648
	ld d0, id8, 256
	stop true, 0x0

	// inline asm
.Ltmp1:
.Lfunc_end0:
	.size	__bootstrap, .Lfunc_end0-__bootstrap
	.cfi_endproc
	.section	.stack_sizes,"o",@progbits,.text.__bootstrap
	.long	.Lfunc_begin0
	.byte	0
	.section	.text.__bootstrap,"ax",@progbits
                                        // -- End function
	.section	.debug_abbrev,"",@progbits
	.byte	1                               // Abbreviation Code
	.byte	17                              // DW_TAG_compile_unit
	.byte	1                               // DW_CHILDREN_yes
	.byte	37                              // DW_AT_producer
	.byte	14                              // DW_FORM_strp
	.byte	19                              // DW_AT_language
	.byte	5                               // DW_FORM_data2
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	16                              // DW_AT_stmt_list
	.byte	23                              // DW_FORM_sec_offset
	.byte	27                              // DW_AT_comp_dir
	.byte	14                              // DW_FORM_strp
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	2                               // Abbreviation Code
	.byte	46                              // DW_TAG_subprogram
	.byte	0                               // DW_CHILDREN_no
	.byte	17                              // DW_AT_low_pc
	.byte	1                               // DW_FORM_addr
	.byte	18                              // DW_AT_high_pc
	.byte	6                               // DW_FORM_data4
	.byte	64                              // DW_AT_frame_base
	.byte	24                              // DW_FORM_exprloc
	.ascii	"\227B"                         // DW_AT_GNU_all_call_sites
	.byte	25                              // DW_FORM_flag_present
	.byte	3                               // DW_AT_name
	.byte	14                              // DW_FORM_strp
	.byte	58                              // DW_AT_decl_file
	.byte	11                              // DW_FORM_data1
	.byte	59                              // DW_AT_decl_line
	.byte	11                              // DW_FORM_data1
	.byte	63                              // DW_AT_external
	.byte	25                              // DW_FORM_flag_present
	.byte	0                               // EOM(1)
	.byte	0                               // EOM(2)
	.byte	0                               // EOM(3)
	.section	.debug_info,"",@progbits
.Lcu_begin0:
	.long	.Ldebug_info_end0-.Ldebug_info_start0 // Length of Unit
.Ldebug_info_start0:
	.short	4                               // DWARF version number
	.long	.debug_abbrev                   // Offset Into Abbrev. Section
	.byte	4                               // Address Size (in bytes)
	.byte	1                               // Abbrev [1] 0xb:0x2d DW_TAG_compile_unit
	.long	.Linfo_string0                  // DW_AT_producer
	.short	12                              // DW_AT_language
	.long	.Linfo_string1                  // DW_AT_name
	.long	.Lline_table_start0             // DW_AT_stmt_list
	.long	.Linfo_string2                  // DW_AT_comp_dir
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	2                               // Abbrev [2] 0x26:0x11 DW_TAG_subprogram
	.long	.Lfunc_begin0                   // DW_AT_low_pc
	.long	.Lfunc_end0-.Lfunc_begin0       // DW_AT_high_pc
	.byte	1                               // DW_AT_frame_base
	.byte	102
                                        // DW_AT_GNU_all_call_sites
	.long	.Linfo_string3                  // DW_AT_name
	.byte	1                               // DW_AT_decl_file
	.byte	13                              // DW_AT_decl_line
                                        // DW_AT_external
	.byte	0                               // End Of Children Mark
.Ldebug_info_end0:
	.section	.debug_str,"MS",@progbits,1
.Linfo_string0:
	.asciz	"clang version 12.0.0 (https://github.com/upmem/llvm-project.git d36425841d9a4d1420b7aa155675f6ae8bcf9f08)" // string offset=0
.Linfo_string1:
	.asciz	"/root/uPIMulator_frontend/sdk/misc/restoreRegisters.c" // string offset=106
.Linfo_string2:
	.asciz	"/root/upmem_compiler"          // string offset=160
.Linfo_string3:
	.asciz	"__bootstrap"                   // string offset=181
	.addrsig
	.addrsig_sym __bootstrap
	.section	.debug_line,"",@progbits
.Lline_table_start0:
